clues_Beyond_Belief_CR_6_23_11 = Array.new
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BCS', number: 1, clue: 'NCAA football matchup system'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BOGGLES', number: 1, clue: 'Bewilders, as the mind'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CHORIZO', number: 2, clue: 'Spicy Spanish pork sausage'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SIDEARMS', number: 3, clue: 'Body heat?'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'SEX', number: 4, clue: 'Group activity, at times'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SUEDE', number: 4, clue: 'Big name in Britpop'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ETSY', number: 5, clue: 'Online crafts warehouse'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'XES', number: 6, clue: 'Letters on coaches\' chalkboards'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'ALGEBRA', number: 7, clue: 'School subject with variables'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ABSENT', number: 7, clue: 'Truant, perhaps'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LIEIN', number: 8, clue: '\'60s protest type'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'GRADY', number: 9, clue: 'Short-lived "Sanford and Son" spinoff'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ETD', number: 10, clue: 'Frequently overoptimistic JFK guess'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BHOPAL', number: 11, clue: 'Indian city in 1984 gas leak news'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'REVOLT', number: 12, clue: 'Follow an Arabesque pattern?'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'AREOLA', number: 13, clue: 'Nipple area'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OHI', number: 14, clue: '"___ get it now!"'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'UTE', number: 15, clue: 'Offroad vehicle, for short'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'BIRTHER', number: 16, clue: 'Trump, for one'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GODLESS', number: 17, clue: 'Without a prayer, and like 24-, 34-, 46-, and 56-Across'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'LEN', number: 18, clue: 'Hall of Fame quarterback Dawson'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'SEADOVE', number: 19, clue: 'Little auk'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'GREEDY', number: 20, clue: 'Scroogelike'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'REID', number: 21, clue: 'Senate Majority Leader Harry'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 4, col: 8, dir: 'Down', answer: 'RECONNECT', number: 21, clue: 'Find out what that weird dude from high school is up to, via Facebook'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'POO', number: 22, clue: 'Crap'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LIANE', number: 23, clue: 'Hansen who retired from NPR last month'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'PENNYHALL', number: 24, clue: 'Museum wing dedicated to small change? (Roman, war)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'PERI', number: 24, clue: 'Gilpin of "Frasier"'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'HASID', number: 25, clue: 'Certain devout Brooklynite'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'EZR', number: 26, clue: 'O.T. book about returning to Zion'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'SECT', number: 27, clue: 'Religious branch'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'SEGA', number: 27, clue: 'Sonic the Hedgehog company'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'ALTA', number: 28, clue: '___Vista (search engine that still exists)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SOMBRERO', number: 29, clue: 'Hat in westerns'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'BILLS', number: 30, clue: 'You\'ll get them regularly if you have gas'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'RNA', number: 31, clue: 'Biology class topic'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'IRS', number: 32, clue: 'Early label for R.E.M.'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'INKS', number: 32, clue: 'Comic book artist\'s choices'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'RTE', number: 33, clue: 'Way, for short'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'SINGININTIN', number: 34, clue: 'Movie featuring performers who croon into cans? (Greek, marriage)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'IASK', number: 35, clue: '"That\'s all ___ ..."'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'NEOPHYTE', number: 36, clue: 'Noob'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'LAA', number: 37, clue: 'Baseball rival of SEA and TEX'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'NAKEDEYE', number: 38, clue: 'Unmediated observer'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'YESISEE', number: 39, clue: '"That much is obvious"'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'ERECTOR', number: 40, clue: '___ set (future engineer\'s toy)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'JAIL', number: 41, clue: 'Place with tons of bars'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'JIHADS', number: 41, clue: 'Spiritual struggles misunderstood by extremists and American conservatives alike'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ADONAI', number: 42, clue: 'Torah VIP'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'IATEIT', number: 43, clue: 'Disrespectful roommate\'s reply to an inquiry about that last slice of pizza you were saving'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'HESS', number: 44, clue: 'Company with toy trucks'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'HOSERS', number: 44, clue: 'Canadian jerks'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'OER', number: 45, clue: 'National anthem contraction'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IDASAROCK', number: 46, clue: 'Determine the geological origin of, say? (Rome, sun)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ADDLE', number: 47, clue: 'Discombobulate'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'RULER', number: 48, clue: 'Stick for a drawer'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'LAPSE', number: 49, clue: 'Temporary failure, as of judgment'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'LOPEZ', number: 49, clue: 'Talk show host George'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'ATT', number: 50, clue: 'Part of D.A.: Abbr.'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HOT', number: 51, clue: 'Like hell'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'DUST', number: 52, clue: 'Housekeeper\'s concern'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'GOTHIC', number: 53, clue: 'Dark and gloomy, aesthetically'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'GMAN', number: 53, clue: 'Paranoid fed. employee'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ANEEDLE', number: 54, clue: '"It is easier for a camel to go through the eye of ___ ..." (Matthew 19:24)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'EMT', number: 55, clue: '911 responder, for short'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'EMPTYST', number: 56, clue: 'Ave. in a ghost town? (Greek, war)'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ETE', number: 56, clue: 'Touristy time in Paris'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'DAIMLER', number: 57, clue: 'Chrysler partner, once'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'TAE', number: 58, clue: '___ kwon do'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'TEO', number: 59, clue: 'Former Formula One driver Fabi'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SITTERS', number: 60, clue: 'Parents\' weekend hirees'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'ENZ', number: 61, clue: 'New Zealand new wave band Split ___'))
clues_Beyond_Belief_CR_6_23_11.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'EER', number: 62, clue: 'Ballad ending?'))
Puzzle.create(title: 'Beyond Belief', grid: 'BCS.SEX.ALGEBRA|OHI.UTE.BIRTHER|GODLESS.SEADOVE|GREEDY.REID.POO|LIANE.PENNYHALL|EZR..SECT..ALTA|SOMBRERO.IRS...|..SINGININTIN..|...LAA.NAKEDEYE|JAIL..HESS..OER|IDASAROCK.LAPSE|HOT.DUST.GOTHIC|ANEEDLE.EMPTYST|DAIMLER.TAE.TEO|SITTERS.ENZ.EER', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/6/23', entries: clues_Beyond_Belief_CR_6_23_11)
