clues_Ch_ch_ch_Changes_CR_9_1_11 = Array.new
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ADAM', number: 1, clue: 'Man who\'s first in line?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'AIWA', number: 1, clue: 'Defunct electronics brand'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'DAHL', number: 2, clue: 'Novelist and WWII flying ace Roald'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ANAL', number: 3, clue: 'Stuffy, as it were'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MATADOR', number: 4, clue: 'Label for Yo La Tengo and the New Pornographers'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ATMS', number: 5, clue: '"Fast cash" conveniences'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ABO', number: 5, clue: 'Letters of concern to a transfusionist'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TRUCK', number: 6, clue: 'Semi, e.g.'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'MALIA', number: 7, clue: 'Obama who became a teenager in July 2011'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SUDAN', number: 8, clue: 'Country that split into North and South in July 2011'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'GIZMO', number: 9, clue: '"Gremlins" gremlin voiced by Howie Mandel'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'GOP', number: 9, clue: 'Org. with a Boehner for frustrating Obama'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ICESHOW', number: 10, clue: 'Skating spectacle'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ZETTABYTES', number: 11, clue: 'Data units in which the whole internet is measured'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MATRI', number: 12, clue: 'Lineal lead-in'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ONION', number: 13, clue: 'Edible bulb'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IANA', number: 14, clue: 'Archivist\'s suffix'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'BRAU', number: 15, clue: 'Oktoberfest drink'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'OCEAN', number: 16, clue: 'Place for piracy'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'WHATWOULD', number: 17, clue: 'With 64-Across, reflective question from one experimenting with sandwich toppings?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'WHIR', number: 18, clue: 'Blender sound'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'PETTI', number: 19, clue: 'Coat opening?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ALLAH', number: 20, clue: 'God, to 1/5 of the planet'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'CIAO', number: 21, clue: '"I\'m out"'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ODD', number: 22, clue: 'Unmatched'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'STRO', number: 23, clue: 'Houston baseball player, casually'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'DICKANDCHAIN', number: 24, clue: 'Apt name for a gay S&M supply store?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'CELL', number: 25, clue: 'Node in a terrorist network'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'CODE', number: 26, clue: 'You might crack one with your brain'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'IGNORE', number: 27, clue: 'Tune out'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'IBMS', number: 27, clue: 'Watson and Big Blue, for two'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'GORE', number: 28, clue: 'Slasher movie display'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'NOSPINZONE', number: 29, clue: 'Ostensibly bullshit-free Bill O\'Reilly segment'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'DOOB', number: 30, clue: 'Reefer'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BOOR', number: 31, clue: 'Many a Dangerfield character'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'LOLO', number: 32, clue: '___ Soetoro (Obama\'s stepfather)'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'OUT', number: 33, clue: 'Totally last season'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'LEI', number: 34, clue: 'Tropical trip souvenir'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'OCD', number: 35, clue: '"Monk" condition'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'DWYER', number: 36, clue: 'Game show host and comedian Bil'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ERIE', number: 37, clue: 'New York canal'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'REID', number: 38, clue: 'Tara or Harry'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MRS', number: 39, clue: 'Post-wedding day title'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'BLUECHE', number: 40, clue: 'Argentine revolutionary down in the dumps?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'BARI', number: 40, clue: 'Italian port on the Adriatic'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'HERO', number: 41, clue: 'Classic Mariah Carey jam from "Music Box"'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'TRE', number: 42, clue: 'Green Day drummer Cool'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SEPIA', number: 43, clue: 'Tone in novelty photos where you put on old-timey clothes'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'INNOWAY', number: 44, clue: 'Not even a little'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'TIDE', number: 45, clue: 'Surfers monitor it'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'QEII', number: 46, clue: 'Famed Cunard liner, familiarly'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'QUEUEUP', number: 46, clue: 'Join the line'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'INRI', number: 47, clue: 'Letters on paintings of the cross'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'INB', number: 48, clue: 'Bach\'s "Mass ___ minor"'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'REUSED', number: 49, clue: 'Was green, in a way'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'EKES', number: 50, clue: '___ out a victory'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RUNNINGCHOKE', number: 51, clue: 'Wrestling move for the Strangling Sprinter?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'READS', number: 51, clue: 'Gets to know something by Harte?'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'UNTIE', number: 52, clue: 'Free, in a way'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'GUCCI', number: 53, clue: 'Brand for some rappers'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'COHEN', number: 54, clue: 'Leonard of dirty lyrics'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'HYENA', number: 55, clue: 'Doglike scavenger'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ENZO', number: 56, clue: 'Italian car magnate Ferrari'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'BUOY', number: 57, clue: 'Marker for boaters'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'EUROS', number: 58, clue: 'Units in a 2011 debt crisis'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'RSTU', number: 59, clue: 'Sequence late in the alphabet'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ODES', number: 60, clue: 'Pindaric or Horatian poems'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SOPH', number: 61, clue: 'Second-year, for short'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ATOWN', number: 62, clue: 'Hotlanta'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'NRA', number: 63, clue: 'Org. that favors concealed carry licenses'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'CHEESESDO', number: 64, clue: 'See 17-Across'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'EAT', number: 65, clue: 'Follow an implied final recipe instruction'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'DINAR', number: 66, clue: 'Bill that once featured Saddam Hussein'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'CENA', number: 67, clue: 'Wrestler John with 18 WWE championships'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'UTEP', number: 68, clue: 'Texas sch. in the 2006 film "Glory Road"'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SEEYA', number: 69, clue: '"I\'m out"'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'INAT', number: 70, clue: 'Check ___ the gate'))
clues_Ch_ch_ch_Changes_CR_9_1_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'PUSH', number: 71, clue: 'Novel on which the film "Precious" is based'))
Puzzle.create(title: 'Ch-ch-ch-Changes', grid: 'ADAM.ATMS.GIZMO|IANA.BRAU.OCEAN|WHATWOULD.PETTI|ALLAH.CIAO.STRO|...DICKANDCHAIN|IGNORE...DOOB..|BOOR.LOLO.DWYER|MRS.BLUECHE.TRE|SEPIA.TIDE.QEII|..INRI...REUSED|RUNNINGCHOKE...|ENZO.BUOY.EUROS|ATOWN.CHEESESDO|DINAR.CENA.UTEP|SEEYA.INAT.PUSH', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/9/1', entries: clues_Ch_ch_ch_Changes_CR_9_1_11)
