clues_Drinking_on_a_Starry_Night_CR_2_24_11 = Array.new
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'WIIS', number: 1, clue: 'Some wireless consoles'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'WATT', number: 1, clue: 'Speaker unit'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IMRE', number: 2, clue: 'Ever ___ Morissette-Treadway (Alanis\'s new baby)'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'IOUS', number: 3, clue: 'Some signed notes'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SKELTER', number: 4, clue: 'Half of a Beatles song'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'MORDOR', number: 5, clue: 'Dark Tolkien land'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MOA', number: 5, clue: 'Bird in a natural history museum'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ONNA', number: 6, clue: '"Oliver!" choreographer White'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'REGROUP', number: 7, clue: 'Prepare to start over'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DURIAN', number: 8, clue: 'Asian fruit that smells so bad it\'s often banned from hotels'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'OPIATE', number: 9, clue: 'Heroin, for one'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'RSA', number: 10, clue: 'The only African G20 country: Abbr.'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BCE', number: 11, clue: 'Dater\'s letters'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BAWK', number: 11, clue: 'Word repeated when goading someone into something'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CHAO', number: 12, clue: 'French musician Manu'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EARN', number: 13, clue: 'Pull in'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMOK', number: 14, clue: 'Wild'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ONEUPS', number: 15, clue: 'Beats in H.O.R.S.E., say'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'AHA', number: 16, clue: '"Eureka!"'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TRUESANGRIA', number: 17, clue: '61-Across nominee about familial vengeance in a Spanish wine mulling community?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'SARS', number: 18, clue: 'WHO concern of several years ago'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'WAR', number: 19, clue: 'Hell, as they say'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'TESLA', number: 20, clue: 'Physicist and coil creator Nikola'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'ARIA', number: 21, clue: '"Nessun dorma" from "Turandot," e.g.'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'AKON', number: 22, clue: '"Angel" rapper'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ASWE', number: 22, clue: '"It\'s The End Of The World ___ Know It (And I Feel Fine)"'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'TRY', number: 23, clue: '"Do, or do not. There is no ___" (quote from 24-Down)'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'YODA', number: 24, clue: 'Speaker of 23-Across'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'OATHS', number: 25, clue: 'They may be taken on bibles'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'HTML', number: 26, clue: 'Language in which many websites are written'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'THESOJUNETWORK', number: 27, clue: '61-Across nominee about the early years of a website that helps people connect to Korean potato liquor?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'TORAH', number: 27, clue: 'Contents of a certain ark'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'HENCE', number: 28, clue: 'So'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'JIG', number: 29, clue: 'Upbeat Irish dance'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'OLMEC', number: 30, clue: 'Ancient Mexican people'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'REACH', number: 31, clue: 'Big name in bristles'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'KENT', number: 32, clue: 'Reporter played by Reeve'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DOER', number: 33, clue: 'Person of action'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'DUCT', number: 33, clue: 'Tight space in which chase scenes are sometimes set'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'DIP', number: 34, clue: 'It\'s often near crackers or carrots'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'MELEE', number: 35, clue: 'Throwdown'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'URN', number: 36, clue: 'Grecian vessel'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'ZAG', number: 37, clue: 'Go the other way'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'ZOIC', number: 37, clue: 'Suffix with some dinosaur era names'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'HDL', number: 38, clue: '"Good" cholesterol'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'HRS', number: 38, clue: 'Many mins.'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'DEPP', number: 39, clue: 'Frequent collaborator with Burton'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'MAN', number: 40, clue: 'Recent Bar Mitzvah, e.g.'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'CACAO', number: 41, clue: 'Chocolate source'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'APSE', number: 42, clue: 'Place for some relics'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ERE', number: 43, clue: 'Before, archaically'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ESTATES', number: 43, clue: 'Will subjects'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'SECT', number: 44, clue: 'Church branch'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'SEANCES', number: 44, clue: 'Occasions for calling people back?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'THEPIMMSSPEECH', number: 45, clue: '61-Across nominee about how the president of a British liquor company became eloquent?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'MORESO', number: 46, clue: 'To a higher degree'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'MOISES', number: 47, clue: 'An Alou'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'EDIT', number: 48, clue: 'Clean up your language?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'SCOOT', number: 49, clue: 'Rush'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'PDA', number: 50, clue: 'Making out in public, e.g.: Abbr.'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LIFE', number: 51, clue: 'Existence'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'LOLZ', number: 51, clue: 'Bit of online laughter'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ICEE', number: 52, clue: 'Frozen drink company with a polar bear mascot'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'FTEN', number: 53, clue: 'Key at the top-right of some keyboards'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'RIAA', number: 54, clue: 'Org. that once sued a dead woman for illegal downloading'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'APIE', number: 55, clue: '"...blackbirds baked in ___"'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'INTRO', number: 56, clue: 'First album track, perhaps'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'THAI', number: 57, clue: 'Like a great many rice farmers'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'REST', number: 58, clue: 'Take a load off'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ORES', number: 59, clue: 'Pitchblende and bauxite'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OCT', number: 60, clue: '2011 mo. when Harold Camping predicts the world will end'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'BESTPITCHER', number: 61, clue: 'Award for which 17-, 27-, and 45-Across are among the hopefuls?'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'BIT', number: 61, clue: 'Attacked dentally'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'ITD', number: 62, clue: '"___ be an honor"'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LEE', number: 63, clue: 'Levi\'s alternative'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ISEEIT', number: 64, clue: '"You can stop pointing now"'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'EASE', number: 65, clue: 'Comfort'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ZEN', number: 66, clue: 'Religion derived from the teachings of Siddhartha Gautama'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'TOSSED', number: 67, clue: 'Threw (out)'))
clues_Drinking_on_a_Starry_Night_CR_2_24_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SITS', number: 68, clue: 'Perches'))
Puzzle.create(title: 'Drinking on a Starry Night', grid: 'WIIS.MORDOR.BCE|AMOK.ONEUPS.AHA|TRUESANGRIA.WAR|TESLA.ARIA.AKON|...TRY.OATHS...|.THESOJUNETWORK|DOER.DIP..MELEE|URN.ZAG.HDL.MAN|CACAO..ERE.SECT|THEPIMMSSPEECH.|...SCOOT.PDA...|LIFE.RIAA.INTRO|OCT.BESTPITCHER|LEE.ISEEIT.EASE|ZEN.TOSSED.SITS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/2/24', entries: clues_Drinking_on_a_Starry_Night_CR_2_24_11)
