clues_Early_Dismissal_CR_6_2_11 = Array.new
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PSA', number: 1, clue: '"Knowing Is Half the Battle" spot, e.g.'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PULPIT', number: 1, clue: 'Stand in church'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'SPEEDO', number: 2, clue: 'Clothing company associated with wet, near-naked bodies'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ASTROS', number: 3, clue: 'Perennial NL Central cellar-dwellers'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'APLEA', number: 4, clue: '___ for sanity'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ARE', number: 4, clue: '"What ___ you, nuts?"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'POR', number: 5, clue: '___ favor'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LUSTS', number: 6, clue: 'Is hot for, with "after"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ENOCH', number: 7, clue: 'Cain\'s eldest son'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ADFEE', number: 8, clue: 'Website\'s charge'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'RHODA', number: 9, clue: '1970s James L. Brooks sitcom'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'REPLAY', number: 9, clue: 'One may be instant'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HASSLE', number: 10, clue: 'Bug'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OTA', number: 11, clue: 'Taxonomic suffix'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'DEL', number: 12, clue: '___ the Funky Homosapien'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ARM', number: 13, clue: 'Limb in many a gym logo'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'UPSGROUND', number: 14, clue: 'Shipping option that uses trucks'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'GTO', number: 15, clue: 'Classic muscle car'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'EATER', number: 16, clue: 'Faster\'s opposite'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LETTERSOF', number: 17, clue: 'With 61-Across, disheartening missives written into the beginnings of this puzzle\'s theme answers'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'PSALM', number: 18, clue: 'Song of David'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'PERO', number: 19, clue: 'Spanish "but"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'TCELLS', number: 20, clue: 'Immune system agents'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'LSD', number: 21, clue: 'Drug in some fabulously misguided episodes of "Dragnet"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'IDO', number: 22, clue: 'Words that affect one\'s tax status'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'NOSHESALADY', number: 23, clue: 'Has a casual snack, as a cannibal?'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'NINA', number: 23, clue: 'Columbus vessel'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ONCD', number: 24, clue: 'One way to burn music'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'AVON', number: 25, clue: 'Cosmetics company for which Derek Jeter is a spokesman'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'DALE', number: 26, clue: 'Chip\'s chipmunk counterpart'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'YTD', number: 27, clue: 'Letters on a pay stub'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TOSSIN', number: 28, clue: 'Include free'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'SEM', number: 29, clue: 'School year section: Abbr.'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'DYEVAT', number: 30, clue: 'Container with coloring'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ENCAMP', number: 31, clue: 'Pitch a tent'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'AMA', number: 32, clue: '"I ___ jelly donut"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'MAR', number: 33, clue: 'Ruin'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'PGA', number: 34, clue: 'Club circuit?'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'OLD', number: 35, clue: 'On in years'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'NOMADMAGAZINE', number: 36, clue: 'Periodical with 0% home subscription rates?'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'NOHO', number: 36, clue: 'Area near NYU'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'OLAV', number: 37, clue: 'One of five Norwegian kings'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'AGHA', number: 38, clue: 'Ottoman title'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ZOID', number: 39, clue: 'Sci-fi suffix'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'INC', number: 40, clue: 'Business letter abbr.'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'AOL', number: 41, clue: 'Co. that once sold modems'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'AWN', number: 41, clue: 'Plant bristle'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ARAGON', number: 42, clue: 'Catherine of ___ (Henry VIII\'s first wife)'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'WHAMMY', number: 43, clue: 'Dreaded "Press Your Luck" result'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'MIATAS', number: 44, clue: 'Mazda MX-5s'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'MCDUCK', number: 45, clue: 'Animated Scrooge'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'YEN', number: 46, clue: 'Desire'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'HICKOK', number: 47, clue: 'Wild Bill\'s surname'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'KIBITZ', number: 48, clue: 'Butt in'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'ORIOLE', number: 49, clue: 'Orange and black bird'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'KEENEN', number: 50, clue: 'Ivory Wayans who hosted "In Living Color"'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NOVICESQUAD', number: 51, clue: 'Little league team?'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'SORTA', number: 52, clue: 'In a way'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'QUEER', number: 53, clue: 'Gay, self-affirmatively'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'UNJAM', number: 54, clue: 'Fix, as an overstuffed copier'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'IRE', number: 55, clue: 'Anger'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'ADNOUN', number: 56, clue: 'Adjective used as a person, place, or thing'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'OBIE', number: 57, clue: 'New York theater award'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'OTT', number: 57, clue: 'He\'s ahead of Sheffield on the all-time home run list'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BANTU', number: 58, clue: 'African language family'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'BID', number: 58, clue: 'Use eBay, say'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ASA', number: 59, clue: 'Simile center'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'NAN', number: 60, clue: 'Indian flatbread'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'REJECTION', number: 61, clue: 'See 17-Across'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'EKE', number: 62, clue: '___ out a living'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'CEE', number: 63, clue: '___ Lo Green'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ISAAC', number: 64, clue: 'Grammy-winning Hayes'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'TEAKETTLE', number: 65, clue: 'Whistler in the kitchen'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DANSK', number: 66, clue: 'Big name in good china'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'ARMEE', number: 67, clue: 'French military force'))
clues_Early_Dismissal_CR_6_2_11.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'ZEN', number: 68, clue: 'Calm, so to speak'))
Puzzle.create(title: 'Early Dismissal', grid: 'PSA.APLEA.RHODA|UPSGROUND.EATER|LETTERSOF.PSALM|PERO..TCELLS...|IDO.NOSHESALADY|TOSSIN...DYEVAT|...ENCAMP...OLD|.NOMADMAGAZINE.|AOL...ARAGON...|WHAMMY...HICKOK|NOVICESQUAD.IRE|...ADNOUN..OBIE|BANTU.REJECTION|ISAAC.TEAKETTLE|DANSK.ARMEE.ZEN', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/6/2', entries: clues_Early_Dismissal_CR_6_2_11)
