clues_G_Movie_Edits_CR_1_13_11 = Array.new
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DICER', number: 1, clue: 'Infomercial kitchen gadget'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DISBAND', number: 1, clue: 'Break up'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IMHOTEP', number: 2, clue: 'Egyptian pyramid builder who became a god'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'COYOTES', number: 3, clue: 'We assume they ate my grandparents\' cat that disappeared in San Diego like twenty years ago'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EVOKE', number: 4, clue: 'Bring to mind'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'REFINISH', number: 5, clue: 'Give a fresh surface'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'SALT', number: 6, clue: 'Kitchen pinchful'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SPUN', number: 6, clue: 'Went around in circles'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALLI', number: 7, clue: 'Sheryl Crow\'s "___ Wanna Do"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'LIEGE', number: 8, clue: 'Lord of the Middle Ages'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TEEHEE', number: 9, clue: 'Twitter'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'VIBE', number: 10, clue: 'General feeling'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'VICS', number: 10, clue: '"Trader ___"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'IMO', number: 11, clue: 'As I see it, in texts'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BOL', number: 12, clue: 'Sudanese activist/athlete Manute who died in 2010'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'END', number: 13, clue: 'Cessation'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IMOVE', number: 14, clue: 'Proposal starter, under Robert\'s Rules of Order'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'PLIE', number: 15, clue: 'Ballet move'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'IMON', number: 16, clue: '"Wish me luck!"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SHYOF', number: 17, clue: 'Less than'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'ULEESCOLD', number: 18, clue: 'Film in which Peter Fonda sneezes a lot?'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'STEP', number: 19, clue: 'Do a certain synchronized dance'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BOOKIENIGHTS', number: 20, clue: 'Film in which Mark Wahlberg runs an after-hours betting parlor?'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'EDDIE', number: 21, clue: 'Son of Harriette and Carl Winslow'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ATTEND', number: 22, clue: 'Be part of the crowd?'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'EEE', number: 23, clue: 'Small Asus PC'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'SPA', number: 24, clue: 'Hot stone massage spot'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'SPY', number: 24, clue: 'Be a voyeur, perhaps'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'PEE', number: 25, clue: 'Go'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'AND', number: 26, clue: 'Common operator'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'NEE', number: 27, clue: 'Born as'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'IDEA', number: 28, clue: 'Entrepreneur\'s need'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'EMME', number: 29, clue: 'Palindromic plus-sized model'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ABEER', number: 30, clue: '"Buy me ___?"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'EPIPEN', number: 31, clue: 'Brand for people with strong allergies'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'IDO', number: 32, clue: 'Civil ceremony words'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DPS', number: 33, clue: 'MLB "twin killings"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'SIMBA', number: 34, clue: '"I\'m gonna be King of Pride Rock" speaker'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ANNO', number: 35, clue: 'A.D. part'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'DYED', number: 36, clue: 'Colored cloth'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'THEMENWHO', number: 37, clue: 'With 57-Across, film in which George Clooney and Ewan McGregor play quality control employees at a garment factory?'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'TOV', number: 37, clue: '"Mazel ___!"'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'WINAT', number: 38, clue: 'Succeed in'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'HEADCASE', number: 39, clue: 'Manny Ramirez, famously'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LOGO', number: 40, clue: 'Company mark'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'LBJ', number: 40, clue: 'Eighth prez before BHO'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'OED', number: 41, clue: 'Subject of the book "The Meaning of Everything," briefly'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'GAS', number: 42, clue: 'Problem caused by starchy foods'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'EENIE', number: 43, clue: 'Start of a playground rhyme to see who has to do something'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'SML', number: 44, clue: 'Spec on a shirt tag'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'STEAMER', number: 44, clue: 'Cooking vessel sometimes made from bamboo'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'MARTINI', number: 45, clue: 'Drink that may be garnished with a lemon peel'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'LETSSEE', number: 46, clue: '"Hmm ..."'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BEAVIS', number: 47, clue: 'Mike Judge character'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'IOTA', number: 48, clue: 'Minimal trace'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'SPADES', number: 49, clue: 'Black suit'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'RONA', number: 50, clue: '"Mazes and Monsters" novelist Jaffe'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'TAE', number: 51, clue: '___ kwon do'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'JDS', number: 52, clue: 'Law grads'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'OPT', number: 53, clue: 'Go (for)'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'TROUT', number: 54, clue: 'Freshwater catch'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'ADVERT', number: 55, clue: 'Commercial, in Britain'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'VOICE', number: 56, clue: 'It may change during puberty'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'STAREATCOATS', number: 57, clue: 'See 37-Across'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'SHOX', number: 57, clue: 'Nike shoe with clear rubber turbo things'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ECRU', number: 58, clue: 'Bridal gown shade'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'AKON', number: 59, clue: '"Angel" rapper'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ALPHADOCK', number: 60, clue: 'Emile Hirsch film about the best place to load and unload boats?'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ABS', number: 60, clue: 'Muscles worked by crunches'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'LOT', number: 61, clue: 'He fled Sodom'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'PGA', number: 62, clue: 'Vijay Singh\'s org.'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'AIMIS', number: 63, clue: '"My ___ True" (Elvis Costello album)'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BOGO', number: 64, clue: 'Common promotion deal, for short'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EURO', number: 65, clue: 'Estonian currency, as of January 1, 2011'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'SCENE', number: 66, clue: 'Commotion'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STAX', number: 67, clue: 'Classic Memphis soul label'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'STUN', number: 68, clue: 'Throw for a loop'))
clues_G_Movie_Edits_CR_1_13_11.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'EERIE', number: 69, clue: 'Spooky'))
Puzzle.create(title: 'G Movie Edits', grid: 'DICER.SALT.VIBE|IMOVE.PLIE.IMON|SHYOF.ULEESCOLD|BOOKIENIGHTS...|ATTEND..EEE.SPA|NEE.IDEA.EPIPEN|DPS.SIMBA..DYED|...THEMENWHO...|LOGO..EENIE.SML|BEAVIS.RONA.TAE|JDS.OPT..ADVERT|...STAREATCOATS|ALPHADOCK.AIMIS|BOGO.EURO.SCENE|STAX.STUN.EERIE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/1/13', entries: clues_G_Movie_Edits_CR_1_13_11)
