clues_Midterm_Exams_CR_7_21_11 = Array.new
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MOTIF', number: 1, clue: 'Theme'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MAP', number: 1, clue: 'One might represent your city'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OVO', number: 2, clue: 'Lacto-___ vegetarian'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TEL', number: 3, clue: 'Shorthand on a business card'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'IDIOT', number: 4, clue: 'Easily-manipulated type'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'FATCAT', number: 5, clue: 'Cigar smoker, stereotypically'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'EEKS', number: 6, clue: 'Horror movie responses'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ETCETC', number: 6, clue: '"You see what I\'m getting at here"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ERATO', number: 7, clue: 'Muse of sexy poetry'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'KYL', number: 8, clue: 'Senator Jon of non-factual statements'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SASE', number: 9, clue: 'Encl. with a sweepstakes entry'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'GAYS', number: 10, clue: 'Some newly eligible bachelors, in New York?'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GOTOSLEEP', number: 10, clue: 'Annoyed comment from a bedmate'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ANI', number: 11, clue: 'Major-label critic DiFranco'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'YER', number: 12, clue: '"So\'s ___ old man!"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SIE', number: 13, clue: 'German 101 pronoun'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AVEDA', number: 14, clue: 'Est&#233;e Lauder subsidiary'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'TRYA', number: 15, clue: '"___ Little Tenderness" (Redding tune)'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ONEI', number: 16, clue: 'R.E.M.\'s "The ___ Love"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'POLITICALSATIRE', number: 17, clue: 'Colbert\'s specialty'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'ITCH', number: 18, clue: 'Scabies symptom'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'ANARCH', number: 19, clue: 'Many a punk, philosophically'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'OCTET', number: 20, clue: 'Planets in the solar system, e.g.'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'ENO', number: 21, clue: 'London-based renaissance man Brian'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TICTACTOE', number: 22, clue: 'Cat\'s game game'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'TIP', number: 22, clue: 'Restaurant table leaving'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ICEDTEA', number: 23, clue: 'Drink from Arizona'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'CURRANT', number: 24, clue: 'Modern-sounding fruit'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'EGOT', number: 25, clue: '"30 Rock" acronym about entertainment awards'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ASFAR', number: 26, clue: 'Equally distant'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'FARRAGO', number: 27, clue: 'Hodgepodge'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'ANTSIER', number: 28, clue: 'More likely to fidget, say'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'RDS', number: 29, clue: 'Boxing units: Abbr.'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ICU', number: 30, clue: 'Post-ER ward'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'THC', number: 31, clue: 'Strong weed has a lot of it: Abbr.'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'GARLAND', number: 32, clue: 'Bundle of flowers'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ANC', number: 33, clue: 'Mandela\'s org.'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'PERP', number: 34, clue: 'Cop\'s pursuit'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'PERIMETER', number: 35, clue: 'Place for a fence, perhaps'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'CONCERTS', number: 36, clue: 'They often feature merch tables'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'CAS', number: 36, clue: '___ in Charlie'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'DREAMCATCHERS', number: 37, clue: 'Southwestern souvenirs'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'AWGEEZ', number: 38, clue: '"Shucks"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'MAN', number: 39, clue: 'Blue ___ Group'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'CRIB', number: 40, clue: 'Home, so to speak'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'STARWARS', number: 41, clue: 'Epic with heroic rebels'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SBE', number: 41, clue: 'Compass pt. around 168.75&#176;'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'PAID', number: 42, clue: 'Sticker on purchased merchandise'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'DOT', number: 43, clue: '.'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BENIGNI', number: 44, clue: '1999 Best Actor winner'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'XES', number: 45, clue: 'Characters in pornography?'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'XGAMES', number: 45, clue: 'Competition featuring snowboarding and rally cars'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ERMA', number: 46, clue: 'Columnist Bombeck'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'SEETHE', number: 47, clue: 'Feel inner rage'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'GEO', number: 48, clue: 'Prefix with thermal or strategic'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'EATME', number: 49, clue: '1980s insult line'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'BUGREPORT', number: 50, clue: 'Software designer\'s feedback'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'UNGER', number: 51, clue: 'Half of "The Odd Couple"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'PRIUS', number: 52, clue: 'Volt competitor'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'EEL', number: 53, clue: 'Go-to sushi fish'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'LIFE', number: 54, clue: 'It isn\'t fair, it\'s said'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'NAMER', number: 55, clue: 'Parent, generally'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'WALTZINGMATILDA', number: 56, clue: 'Noted Australian folk song'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'WIG', number: 56, clue: 'Lady Gaga accessory'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ADE', number: 57, clue: 'Drink at a summer stand'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'LEA', number: 58, clue: 'Thompson who played the mother in "Back to the Future"'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'NRA', number: 59, clue: 'Lobbying org. with an intimidating eagle logo'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'LLP', number: 60, clue: 'Certain corporate tax status, briefly'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'DAY', number: 61, clue: '86,400 seconds'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'ASS', number: 62, clue: 'Fool'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'IDEE', number: 63, clue: 'French brainstorm'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'FREE', number: 64, clue: 'Like some stuff on Craigslist'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'HULAS', number: 65, clue: 'Luau dances'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'GEAR', number: 66, clue: 'Clothes, in slang'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'EARS', number: 67, clue: 'Feature embellished in Obama cartoons'))
clues_Midterm_Exams_CR_7_21_11.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ESPYS', number: 68, clue: 'Sports award event held on July 13, 2011'))
spec_feat = '3_9:C|3_10:C|3_11:C|3_12:C|5_5:C|5_6:C|5_7:C|8_6:C|8_7:C|8_8:C|8_9:C|11_9:C|11_10:C|11_11:C|13_8:C|13_9:C|13_10:C|13_11:C'
Puzzle.create(title: 'Midterm Exams', grid: 'MOTIF.EEKS.GAYS|AVEDA.TRYA.ONEI|POLITICALSATIRE|...OCTET.ENO...|TICTACTOE.ASFAR|ICU.THC.GARLAND|PERP...CONCERTS|.DREAMCATCHERS.|STARWARS...PAID|BENIGNI.XES.GEO|EATME.BUGREPORT|...EEL.NAMER...|WALTZINGMATILDA|IDEE.FREE.HULAS|GEAR.EARS.ESPYS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/7/21', entries: clues_Midterm_Exams_CR_7_21_11, special_features: spec_feat)
