clues_Music_Swap_CR_6_30_11 = Array.new
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'APPT', number: 1, clue: 'BlackBerry entry: Abbr.'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'AGLOW', number: 1, clue: 'Postcoital, perhaps'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PLUSH', number: 2, clue: 'Like thick carpets'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PEACESIGNS', number: 3, clue: 'They may be flashed at hippie gatherings'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TENANTRY', number: 4, clue: 'Renter\'s association'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'EGDON', number: 5, clue: 'Thomas Hardy\'s fictitious ___ Heath'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'EGGNOG', number: 5, clue: 'Thick, sweet Christmas goop'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'GROOVE', number: 6, clue: 'Sense of confidence, as it were'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DIODE', number: 7, clue: 'Electronics tube'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'OMG', number: 8, clue: '2010 Usher single'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'NEL', number: 9, clue: '"___ Blu, Dipinto Di Blu"'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'DVDS', number: 10, clue: 'Movie media'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'DECOYS', number: 10, clue: 'Fake ducks, e.g.'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'VLOG', number: 11, clue: 'Site with many YouTube embeds, probably'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'DIDO', number: 12, clue: 'One-named singer sampled on Eminem\'s "Stan"'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SASS', number: 13, clue: 'Lip'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'GLEE', number: 14, clue: 'Show with the New Directions'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'GRIME', number: 15, clue: 'Gross accumulation?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ELIA', number: 16, clue: 'Oscar-winning Kazan'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LUAN', number: 17, clue: 'B-movie actress Peters'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'GOOGLECODS', number: 18, clue: 'Silicon Valley fish farm product?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'EGRET', number: 19, clue: 'Everglades bird'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OSCARNOD', number: 20, clue: 'Recognition from the Academy, as it were'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'RCAS', number: 21, clue: 'Some HDTVs'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'GOGOS', number: 22, clue: '"We Got the Beat" band, with "the"'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'WHENCOVESDRY', number: 23, clue: 'Prince song about the effects of low tide?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'SPEC', number: 24, clue: 'On ___ (without a contract)'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'DRED', number: 25, clue: 'Scott in 1857 news'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'STAGE', number: 26, clue: 'Put on'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'PRESTON', number: 27, clue: 'Raspberry Award winner and Travolta wife Kelly'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'TOOTSIEPOP', number: 28, clue: 'Treat with an apparently unsolvable licking paradox'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ODOR', number: 29, clue: 'Pit problem'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'NEMO', number: 30, clue: 'Disney fish'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'STIRS', number: 31, clue: 'Keeps from congealing, perhaps'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'SLAM', number: 31, clue: 'Lambaste'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'TONI', number: 32, clue: 'Morrison who turned 80 in 2011'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'DEET', number: 33, clue: 'Insect repellent ingredient'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'DXI', number: 33, clue: 'Sixth-century death year of Clovis I'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ODE', number: 34, clue: 'Kind words of a sort'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LOGY', number: 35, clue: 'Sluggish'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'MIXCD', number: 36, clue: 'Personalized album, and this puzzle\'s theme'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'MESA', number: 36, clue: 'Landform in the western U.S.'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'IMAC', number: 37, clue: 'Machine running OSX'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'BOOM', number: 38, clue: 'Bust\'s opposite'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'BEERNUTS', number: 38, clue: 'They\'re supposed to drive you to drinking'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ANN', number: 39, clue: 'Barack\'s mother'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'SEMI', number: 40, clue: 'Highway behemoth'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SURAH', number: 40, clue: 'Qur\'an chapter'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'RETRO', number: 41, clue: 'Back in again'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'RIPA', number: 41, clue: '"Mom, Inc." star'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MISSUSA', number: 42, clue: 'Contest once hosted by Bob Barker and Dick Clark'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'STOGIE', number: 43, clue: 'Cheap smoke'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'SKIES', number: 44, clue: 'Heavens'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'SNAPUP', number: 44, clue: 'Buy greedily'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'KGBSPY', number: 45, clue: 'Putin, once, maybe'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'TRACINGPRIDE', number: 46, clue: 'What a budding preschool artist feels?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'IHOPE', number: 47, clue: '"If all goes well ..."'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'DRAMA', number: 48, clue: 'High schooler\'s problem'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'EATEN', number: 49, clue: 'Devoured'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'OCHOA', number: 50, clue: 'Retired golf star Lorena'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'ODON', number: 50, clue: 'Get too high from'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'COMA', number: 51, clue: 'Time out?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'HUNT', number: 52, clue: 'Participate in a one-sided sport'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'HABANERA', number: 53, clue: '\'\'Carmen\'\' dance'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DOUGHCROPS', number: 54, clue: 'Wheat fields?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'CTS', number: 55, clue: 'Cadillac luxury model'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ROE', number: 56, clue: 'Salmon roll topper'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'UPAT', number: 57, clue: '___ the crack of dawn'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OMNI', number: 58, clue: 'Luxury hotel company'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'TOPUP', number: 59, clue: 'Fill anew'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'TOME', number: 60, clue: 'Plenty of volume?'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NATE', number: 61, clue: '"Six Feet Under" brother'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SEEPY', number: 62, clue: 'Oozing'))
clues_Music_Swap_CR_6_30_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SPAN', number: 63, clue: 'Bridge'))
Puzzle.create(title: 'Music Swap', grid: 'APPT.EGDON.DVDS|GLEE.GRIME.ELIA|LUAN.GOOGLECODS|OSCARNOD..GOGOS|WHENCOVESDRY...|..STAGE.PRESTON|STIRS..DEET.ODE|LOGY.MIXCD.BOOM|ANN.SEMI..RETRO|MISSUSA.SKIES..|...TRACINGPRIDE|OCHOA..HABANERA|DOUGHCROPS.UPAT|OMNI.TOPUP.TOME|NATE.SEEPY.SPAN', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/6/30', entries: clues_Music_Swap_CR_6_30_11)
