clues_New_Slants_CR_12_22_11 = Array.new
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CAPCOM', number: 1, clue: '"Street Fighter" maker'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CST', number: 1, clue: 'Wisconsin hrs.'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AHH', number: 2, clue: '"That\'s the spot ..."'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PER', number: 3, clue: 'Each'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'CLEFT', number: 4, clue: 'Split, as some chins'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'OVERHERE', number: 5, clue: 'Words after a loud whistle'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MELO', number: 6, clue: 'Knicks nickname'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'AGEE', number: 7, clue: 'James with the ironically titled "Let Us Now Praise Famous Men"'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AFGHANI', number: 7, clue: 'Opium farmer, often'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'GIG', number: 8, clue: 'Live performance'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ENEMA', number: 9, clue: 'Backdoor medical procedure?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ENDURE', number: 10, clue: 'Put up with'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'PSP', number: 11, clue: 'Sony device since 2004, for short'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PREHISTORIC', number: 11, clue: 'With 43-Across, caveman who refuses to hunt with grandpa Grok?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SUGE', number: 12, clue: 'Impresario Knight from Compton'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'PEGS', number: 13, clue: 'BMX features'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'SHELVE', number: 14, clue: 'Put away'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'FINN', number: 15, clue: 'Huck ___'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'RUE', number: 16, clue: 'Have second thoughts about'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'THREELEGGED', number: 17, clue: 'With 35-Across, mutant Klansman?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'ETHIC', number: 18, clue: 'Value system'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'EGG', number: 19, clue: 'Huevos rancheros ingredient'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'FROTH', number: 20, clue: 'Cappuccino bubbles'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'MUSHES', number: 21, clue: 'Moves the dogs along'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'STAIR', number: 22, clue: 'One might help you get a leg up'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DEPTH', number: 23, clue: 'Complexity'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'DITHER', number: 23, clue: 'Flustered state'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ESKIMO', number: 24, clue: 'Inuit, somewhat offensively'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'PHONESEXIST', number: 25, clue: 'One who thinks women make lousy operators?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'HAVARTI', number: 26, clue: 'Cheese with dill, sometimes'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'VAS', number: 27, clue: '___ deferens'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ISH', number: 28, clue: '-like'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'EDINA', number: 29, clue: '"Fargo" filming location'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'DADA', number: 30, clue: 'WWI-era art movement'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'EASYA', number: 31, clue: 'Cruise course?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'YOUARE', number: 32, clue: 'Surprised question after a personal admission'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ANTHEM', number: 33, clue: 'National tune'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TKO', number: 34, clue: 'Klitschko bout outcome'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'RACIST', number: 35, clue: 'See 17-Across'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'TASE', number: 36, clue: 'Subdue aggressively, as a protester'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ITON', number: 37, clue: '"Blame ___ the Rain"'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'HINTED', number: 38, clue: 'Insinuated'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'TREYS', number: 39, clue: 'Songz and Anastasio'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'AIROUT', number: 40, clue: 'Remove the smell of B.O. from, say'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ITSSOSAD', number: 41, clue: '"Pity!"'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EMER', number: 42, clue: 'E.R. part: Abbr.'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'AGEIST', number: 43, clue: 'See 11-Down'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'GLO', number: 44, clue: 'Shine, in ads'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'EARACHE', number: 45, clue: 'Drum problem for many drummers?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'IDEAL', number: 46, clue: 'Platonic thing'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'RAH', number: 47, clue: 'Rapper Digga'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ROSES', number: 48, clue: 'You might bring a dozen on a date'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SEEGER', number: 49, clue: 'Pete or Peggy of folk'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'LADES', number: 50, clue: 'Fills with cargo'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'IRE', number: 51, clue: 'Wrath'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'EYESORE', number: 52, clue: 'Decrepit building, e.g.'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'STYLE', number: 53, clue: 'Fashion'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'SICEM', number: 54, clue: '"Bite that man, boy!"'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'INSUM', number: 55, clue: '"To conclude ..."'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'BOXSET', number: 56, clue: 'Police collection, say?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'BAWK', number: 56, clue: 'Syllable repeated when baiting someone'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ORCA', number: 57, clue: 'Killer whale'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'AARON', number: 58, clue: 'Singer Carter in rehab in 2011'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'RASA', number: 59, clue: 'Tabula ___'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ARI', number: 60, clue: 'Gold or Fleischer'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'GYMCLASSIST', number: 61, clue: 'One who feels dodgeball is for the unwashed masses?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'MAN', number: 62, clue: 'Dude'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'IDI', number: 63, clue: 'Amin of autocracy'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'SIR', number: 64, clue: 'UK title'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'TSE', number: 65, clue: 'Follower of Mao?'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WCS', number: 66, clue: 'Loos'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ELAH', number: 67, clue: 'Valley of ___ (where David fought Goliath)'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'SAUDIS', number: 68, clue: 'Some hijab wearers'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'KAT', number: 69, clue: '___ Von D'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'RENE', number: 70, clue: 'Dualist Descartes'))
clues_New_Slants_CR_12_22_11.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'ADMIRE', number: 71, clue: 'Be a fan of'))
Puzzle.create(title: 'New Slants', grid: 'CAPCOM.AGEE.PSP|SHELVE.FINN.RUE|THREELEGGED.EGG|...FROTH.MUSHES|DEPTH.HAVARTI..|ISH.EDINA.EASYA|TKO.RACIST.ITON|HINTED...AIROUT|EMER.AGEIST.RAH|ROSES.LADES.IRE|..EYESORE.SICEM|BOXSET.AARON...|ARI.GYMCLASSIST|WCS.ELAH.SAUDIS|KAT.RENE.ADMIRE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/12/22', entries: clues_New_Slants_CR_12_22_11)
