clues_Pop_Duos_CR_8_11_11 = Array.new
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CLAIR', number: 1, clue: 'Mother of the Huxtable family'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CBS', number: 1, clue: '"Murder, She Wrote" network'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LIPBALM', number: 2, clue: 'Application from a tube'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ALROKER', number: 3, clue: 'Goofy weatherman of note'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'IBISES', number: 4, clue: 'Sacred Egyptian birds'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ROTOS', number: 5, clue: 'Fantasy leagues that aren\'t head-to-head'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CONGA', number: 6, clue: 'Drum in many a Cuban ensemble'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CBC', number: 6, clue: 'In certain areas it\'s called Radio Nord Qu&#233;bec'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ORRS', number: 7, clue: 'Bobby and (less famously) Colton of hockey'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NOUN', number: 8, clue: 'A proper one is capitalized'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'GASOIL', number: 9, clue: 'Home heating option'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ADHOC', number: 10, clue: 'Latin phrase for improvisers'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'CTS', number: 11, clue: 'Typist\'s condition: Abbr.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'COKETAB', number: 11, clue: 'Account with a drug dealer?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TRIREME', number: 12, clue: 'Ship in some sweet old war paintings'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SETSAIL', number: 13, clue: 'Go, on a scow'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BILBO', number: 14, clue: 'Hobbit played by Ian Holm'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'BROAD', number: 15, clue: 'Sweeping'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ORE', number: 16, clue: 'Bauxite, e.g.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SPRITECRUSH', number: 17, clue: 'Romantic fantasy for an elf?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'EXILER', number: 18, clue: 'One doing some casting out'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'KIT', number: 19, clue: 'Drums, collectively'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'BOSOX', number: 20, clue: 'NY Yanks\' rivals'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'SNOOZERS', number: 21, clue: 'People sleeping for just a few more minutes'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ZETAS', number: 22, clue: 'Major Mexican drug cartel, with "los"'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'FAKESIT', number: 23, clue: 'Flatters one\'s partner, in a way'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'FAM', number: 23, clue: 'Gp. of relatives'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'TODDLE', number: 24, clue: 'Move unsteadily, generally'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'ICETEA', number: 25, clue: 'Cold Thai drink, as spelled on some menus'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ALES', number: 26, clue: 'They\'re fermented warmer than lagers'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'LOCAL', number: 27, clue: 'Like some produce and bands'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'CAGES', number: 28, clue: 'Match boxes?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ALANIS', number: 29, clue: 'How Ms. Morissette was known on "You Can\'t Do That on Television"'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'TAMI', number: 30, clue: 'Bestselling author Hoag'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MMR', number: 31, clue: 'Three-part vaccine given to kids: Abbr.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'MEDAL', number: 32, clue: 'Goal for Phelps'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'MOO', number: 32, clue: '[I\'m getting absolutely milked here]'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'LABEL', number: 33, clue: 'Place for an address, say'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'LEX', number: 33, clue: 'Supervillain Luthor'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'WORDGAMES', number: 34, clue: 'Scrabble, Boggle, etc.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'WINOS', number: 34, clue: 'People who make hard choices too often?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'MOTTST', number: 35, clue: 'Artery in NYC\'s Chinatown'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'RADIO', number: 36, clue: 'XM medium'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'RAMPAGE', number: 36, clue: 'Episode with violence, perhaps'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'ARIADNE', number: 37, clue: 'She helped Theseus escape the Minotaur'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'DADSMUG', number: 38, clue: 'Picture of a criminal relation?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'LENOX', number: 39, clue: 'Where the Tanglewood Music Festival happens'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'KSU', number: 40, clue: 'Sch. in 1970 protest news'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'KINDRED', number: 40, clue: 'Related'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SEGMENT', number: 41, clue: 'Part'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'USS', number: 42, clue: 'Battleship letters'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ARAN', number: 43, clue: 'Irish sweater worn by fishermen'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'RESIT', number: 44, clue: 'Pose again'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'RISQUE', number: 44, clue: 'Off-color'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'MIES', number: 45, clue: 'Ludwig ___ van der Rohe'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'MINIME', number: 45, clue: 'Verne Troyer character in "Austin Powers"'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'MIDORI', number: 46, clue: 'Green cordial'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'RESTS', number: 47, clue: 'Regains one\'s energy, in a way'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'STRINGS', number: 48, clue: 'They may be pulled as a favor'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'RAHAL', number: 49, clue: 'Bobby of auto racing'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'PASSESON', number: 50, clue: 'Opts not to buy'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'OURN', number: 51, clue: 'Belonging to me and y\'all both'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'NIBS', number: 52, clue: 'Pen points'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'SANDM', number: 53, clue: 'Rihanna single from "Loud"'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ADM', number: 54, clue: 'Explorer Byrd\'s rank: Abbr.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'SQUIRTHIRES', number: 55, clue: 'Child laborers?'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ROE', number: 56, clue: 'Caviar, e.g.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'SDO', number: 57, clue: 'Heliocentric NASA mission: Abbr.'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GNU', number: 58, clue: 'Bearded big game animal'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TURBO', number: 59, clue: 'Supercharger'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'AMEND', number: 60, clue: 'Modify, as a charter'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'EEG', number: 61, clue: 'Diagnostic test for epilepsy, for short'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SENSE', number: 62, clue: 'Start to suspect'))
clues_Pop_Duos_CR_8_11_11.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'LEDTO', number: 63, clue: 'Caused'))
Puzzle.create(title: 'Pop Duos', grid: 'CLAIR.CONGA.CTS|BILBO.BROAD.ORE|SPRITECRUSH.KIT|.BOSOX.SNOOZERS|FAKESIT..ICETEA|ALES.LOCAL.TAMI|MMR.MEDAL.LABEL|...WORDGAMES...|RADIO.LENOX.KSU|ARAN.RESIT.MIES|MIDORI..STRINGS|PASSESON.SANDM.|ADM.SQUIRTHIRES|GNU.TURBO.AMEND|EEG.SENSE.LEDTO', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/8/11', entries: clues_Pop_Duos_CR_8_11_11)
