clues_Roger_CR_11_17_11 = Array.new
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CAL', number: 1, clue: 'Stanford rival, casually'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CRUMB', number: 1, clue: 'Leaving after dessert?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ADLAI', number: 2, clue: 'Two-time loser to Dwight'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LAUNDROMAT', number: 3, clue: 'Campus facility that\'s on the quarter system'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'LAREDO', number: 4, clue: 'Texas city where Tom DeLay was born'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'LAUDED', number: 4, clue: 'Sang the praises of'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALFAS', number: 5, clue: 'Fast submarines'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RAFT', number: 6, clue: 'Whitewater conveyance'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ERIE', number: 7, clue: 'Pennsylvania city, or its lake'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DIN', number: 8, clue: 'Pink noise, say'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'OAT', number: 9, clue: 'Grain species'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'PAR', number: 10, clue: 'Good score, if the course is tough'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PUPA', number: 10, clue: 'Future moth'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ASIT', number: 11, clue: '"___ so happens ..."'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'RACY', number: 12, clue: 'Blue'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'RDA', number: 13, clue: '2,400 mg, for sodium'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'MALARIA', number: 14, clue: 'Cause of high temperatures in the tropics?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 2, col: 5, dir: 'Down', answer: 'MMCII', number: 14, clue: 'Year Miley Cyrus turns 110'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'USA', number: 15, clue: 'Letters on many exported arms'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ULU', number: 16, clue: 'Inuit knife'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'MUFFINTOPIC', number: 17, clue: 'Point of discussion at Otis Spunkmeyer headquarters?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'OKRA', number: 18, clue: 'Gooey veggie'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MANICDATE', number: 19, clue: 'Romantic outing comprised of sprinting and screaming?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'IDARE', number: 20, clue: 'Beginning of a slumber party challenge'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'KATY', number: 21, clue: 'Singer Perry'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BIDDIES', number: 22, clue: 'Annoying old ladies'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'EUR', number: 23, clue: 'Backpacker\'s destination: Abbr.'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'EDEL', number: 23, clue: 'Henry James biographer Leon'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'UPSA', number: 24, clue: '"___-daisy!"'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'RAID', number: 25, clue: 'Killer of crawlers'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'BEDPANIC', number: 26, clue: 'Source of sexual dysfunction?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'BEFOG', number: 26, clue: 'Render cloudy'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ETCS', number: 27, clue: 'List enders: Abbr.'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'NOISEMAKER', number: 28, clue: 'Grogger or vuvuzela'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'IATE', number: 29, clue: '"___ your Halloween candy" (recent meme)'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'CRY', number: 30, clue: 'React, as most children to 29-Down\'s meme'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'POR', number: 31, clue: 'Favor preceder?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'PORN', number: 31, clue: 'Much of the internet'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'JETES', number: 32, clue: 'Anna Pavlova leaps'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'JONG', number: 32, clue: '"Fear of Flying" novelist Erica'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'OAR', number: 33, clue: 'Thing in a boathouse'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MOMENTOFCLARITY', number: 34, clue: 'What one must have to solve this puzzle\'s theme answers'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'MIA', number: 34, clue: 'Rapper with the line "if you catch me at the border I got visas in my name"'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'NLCS', number: 35, clue: 'The Brewers lost it in 2011'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'TIES', number: 36, clue: 'Connections'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'RELIC', number: 37, clue: 'Out-of-touch person'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'IRA', number: 38, clue: 'Nest egg letters'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'LINOS', number: 39, clue: 'Brits\' floor coverings'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ESE', number: 40, clue: 'Suffix with journal or legal'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ANTICEGG', number: 41, clue: 'Object used for Halloween pranking?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'IBET', number: 42, clue: '"Uh-huh, yeah, sure"'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'GALE', number: 43, clue: 'Strong wind'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'GENOAS', number: 43, clue: 'Some salamis'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ALIFS', number: 44, clue: 'Arabic alphabet starters'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'BSS', number: 45, clue: 'NASA workers\' undergrad degrees'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'DELIMIT', number: 46, clue: 'Bound'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'DOOZY', number: 46, clue: 'Wild one'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'IGAVE', number: 47, clue: '"At least ___ it a shot"'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'TENAM', number: 48, clue: 'Base 1000?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'WAVE', number: 49, clue: 'Hand motion'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'WRAP', number: 49, clue: 'Potentially low-carb alternative to a sandwich'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AURA', number: 50, clue: 'Mystique'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'VSIX', number: 51, clue: 'Midsized engine'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'IRONICAGE', number: 52, clue: 'Historical period when nobody seems to mean what they say?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'IPAD', number: 52, clue: 'Tablet that\'s a theft target'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'RRNA', number: 53, clue: 'AP biology subj.'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RUSTICPROOF', number: 54, clue: 'Off-limits to country folk?'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'IST', number: 55, clue: 'Delhi clock setting'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'CTO', number: 56, clue: 'Company\'s IT VIP'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'KAN', number: 57, clue: 'Japanese PM Naoto who resigned in August 2011'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ARI', number: 58, clue: 'Role for Jeremy on "Entourage"'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'STANZAS', number: 59, clue: 'Poet\'s units'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'EVA', number: 60, clue: 'Mendes or Longoria'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'PAX', number: 61, clue: 'Goddess of peace'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'TODAYS', number: 62, clue: '___ horoscope'))
clues_Roger_CR_11_17_11.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'REM', number: 63, clue: 'Band that broke up in September 2011'))
Puzzle.create(title: 'Roger', grid: 'CAL..LAREDO.PAR|RDA.MALARIA.USA|ULU.MUFFINTOPIC|MANICDATE..KATY|BIDDIES..EUR...|..RAID.BEDPANIC|.POR..JETES.OAR|MOMENTOFCLARITY|IRA.LINOS..ESE.|ANTICEGG.GALE..|...BSS..DELIMIT|WAVE..IRONICAGE|RUSTICPROOF.KAN|ARI.STANZAS.EVA|PAX.TODAYS..REM', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/11/17', entries: clues_Roger_CR_11_17_11)
