clues_Shades_of_Change_CR_9_15_11 = Array.new
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BFFS', number: 1, clue: 'Lifelong buds, 4 short'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BENS', number: 1, clue: 'Sheets and Folds'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'FRAT', number: 2, clue: 'Site of collegiate debauchery'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FIVE', number: 3, clue: 'Grief stage count, according to K&#252;bler-Ross'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SKYWRITE', number: 4, clue: 'Create a smoking advertisement?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'TNT', number: 5, clue: '"Franklin & Bash" station'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TRUDGE', number: 5, clue: 'Participate in a forced march'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'NAB', number: 6, clue: 'Pick up, as a crook'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'THEMINI', number: 7, clue: 'Austin Powers-era vehicle'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'JOBETH', number: 8, clue: 'Williams you no doubt remember from "Poltergeist" and "Dutch"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'JOANMIRO', number: 8, clue: 'Pablo Picasso contemporary'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'OLE', number: 9, clue: 'Longstanding, casually'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BIGTOE', number: 10, clue: 'Digit that might experience hallux rigidus'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'EVER', number: 11, clue: '"Have You ___ Been (To Electric Ladyland)"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TIAA', number: 12, clue: 'CREF\'s partner'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HAND', number: 13, clue: 'Brake operator, at times'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ERIK', number: 14, clue: 'The phantom in "The Phantom of the Opera"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'RAH', number: 15, clue: 'Old-timey cheer word'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'OLIVIA', number: 16, clue: 'A Cosby girl'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NAVYLUBE', number: 17, clue: 'Bedroom product allowed in the post-DADT military?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'LEAR', number: 18, clue: 'Shakespearean king who partly inspired Kurosawa\'s "Ran"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'AEGEAN', number: 19, clue: 'Trojan War sea'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'STEWED', number: 20, clue: 'Stayed pissed'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'MTN', number: 21, clue: 'Setting for many an SUV commercial: Abbr.'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'TAGALOG', number: 22, clue: 'Manila language'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'TRAD', number: 23, clue: 'Like folk mus.'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'RAG', number: 24, clue: 'Oil-changing need'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'IAMSO', number: 25, clue: 'Reply to "You\'re not even smart enough to be in fourth grade"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'SNAG', number: 26, clue: 'Buy before someone else does'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'FIREENGINEDRE', number: 27, clue: 'Hip-hop producer tooling around with a Dalmatian in the window?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'FREDA', number: 27, clue: 'Soul and disco singer Payne'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'ETHICAL', number: 28, clue: 'Guided by good'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'DROVE', number: 29, clue: 'Sat in the right seat, in London?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ROUT', number: 30, clue: 'Overwhelming victory'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'EMTS', number: 31, clue: 'Stretcher carriers, for short'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BURT', number: 32, clue: 'Namesake of a noted beeswax lip balm brand'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'BCCS', number: 32, clue: 'Includes furtively, on an email'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'UHOH', number: 33, clue: '"That didn\'t sound good ..."'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'TIARA', number: 34, clue: 'Intense bride\'s headwear'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ROM', number: 35, clue: 'CD-___'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CHEETAH', number: 36, clue: 'African sprinter'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'TARO', number: 37, clue: 'Tuber in some tropical medicines'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'AVOGADRO', number: 38, clue: 'You might get his number in chemistry class'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'LOGSOUT', number: 39, clue: 'Leaves Gmail, say'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'SPRINGER', number: 40, clue: 'TV Guide\'s "Worst TV Show Ever," familiarly'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'COD', number: 41, clue: 'Icelandic fish'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'AVISO', number: 42, clue: 'Dispatch boat'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SKETCHY', number: 43, clue: 'Suspicious'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'PVTS', number: 44, clue: 'Low-ranking GI\'s'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SHAMROCKGENRE', number: 45, clue: 'Style of music &#224; la U2?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'MTVVJS', number: 46, clue: 'Former "TRL" hosts, e.g.'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ENVOYS', number: 47, clue: 'Ambassador\'s agents'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'NOEL', number: 48, clue: 'Holiday tune'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'TOGAE', number: 49, clue: 'Forum-al attire?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'NOI', number: 50, clue: '"There\'s ___ in team"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'PERV', number: 51, clue: 'One with lewd tastes, casually'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'PCTS', number: 51, clue: 'Real estate agent\'s figs.'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ERIE', number: 52, clue: 'Tribe native to Ohio'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'RAPT', number: 53, clue: 'Extremely attentive'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'ALT', number: 54, clue: 'It\'s labeled "option" on a Mac'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'VENTIS', number: 55, clue: 'Larges, at Starbucks'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'TATU', number: 56, clue: 'Russian pop duo that broke up in 2011'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IRON', number: 57, clue: 'Work out some wrinkles'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SYNE', number: 58, clue: 'Last word of the first song of the year'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CRAVED', number: 59, clue: 'Lusted after'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'EAT', number: 60, clue: 'Fuel up, in a way'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'COOLGARY', number: 61, clue: 'Slogan for a down-and-out Indiana city trying to attract creative types?'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'OWE', number: 62, clue: 'Have a balance'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TIPJAR', number: 63, clue: 'It might have "karma" written on it'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'HWY', number: 64, clue: '"___: An American Pastoral" (Jim Morrison movie)'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ETON', number: 65, clue: 'David Cameron\'s school'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SETSTO', number: 66, clue: 'Begins, as work'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'YES', number: 67, clue: 'Prog band who partly inspired "This Is Spinal Tap"'))
clues_Shades_of_Change_CR_9_15_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'RUNE', number: 68, clue: 'Mysterious symbol in "The Hobbit"'))
Puzzle.create(title: 'Shades of Change', grid: 'BFFS.TNT.JOBETH|ERIK.RAH.OLIVIA|NAVYLUBE.AEGEAN|STEWED.MTN.TRAD|...RAG.IAMSO...|..FIREENGINEDRE|BURT..TIARA.ROM|CHEETAH.LOGSOUT|COD.AVISO..PVTS|SHAMROCKGENRE..|...TOGAE.NOI...|PERV.ALT.VENTIS|CRAVED.COOLGARY|TIPJAR.HWY.ETON|SETSTO.YES.RUNE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/9/15', entries: clues_Shades_of_Change_CR_9_15_11)
