clues_Thats_Not_All_CR_8_18_11 = Array.new
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SALAD', number: 1, clue: 'Leaves undressed, perhaps'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SEGA', number: 1, clue: 'Company that made "Barkley Shut Up and Jam!"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ACAN', number: 2, clue: 'Bang on ___ (New York music collective)'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LOUDMOUTH', number: 3, clue: 'Blabberer'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ALL', number: 4, clue: 'More than a lot'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DISGUISE', number: 5, clue: 'Spying device'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'PGAS', number: 6, clue: 'The ___ of Europe (international links org.)'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PROOFS', number: 6, clue: 'Editor\'s copies'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GUNLOCK', number: 7, clue: 'Firearm safety mechanism'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AGE', number: 8, clue: 'Life time'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SSS', number: 9, clue: 'Bad sound to hear in rattlesnake country'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ABLE', number: 10, clue: 'Sure-handed'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ARIZONA', number: 10, clue: 'State with lax firearm laws'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BANTU', number: 11, clue: 'African language from which the word "chimpanzee" comes'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LIGER', number: 12, clue: 'Animal drawn in "Napoleon Dynamite"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENACT', number: 13, clue: 'Make into law'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ECOLI', number: 14, clue: 'It can cause urinary tract infections'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'RUGS', number: 15, clue: 'Souvenirs from Istanbul'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'RAIN', number: 16, clue: 'Dark sky\'s omen'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GAULSTONES', number: 17, clue: 'Skipped objects in ancient France?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'TEL', number: 18, clue: 'Cell no., e.g.'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'INGA', number: 19, clue: 'Actress Swenson on "Benson"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AND', number: 20, clue: '"Is there more to the story?"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'GEOL', number: 21, clue: 'Science course listing abbr.'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'AZTEC', number: 22, clue: 'Cuitlahuac\'s people'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'ACE', number: 22, clue: 'Pitcher in the first game of a playoff series, usually'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'MAULFOODCOURT', number: 23, clue: 'Where a certain Sith lord goes to eat at Cinnabon and Sbarro?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'ALE', number: 24, clue: 'It\'s made with hops'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ORIG', number: 25, clue: 'Copier fodder: Abbr.'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'DENIM', number: 26, clue: 'It goes with pretty much any color'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PAOLI', number: 27, clue: '1777 battle site near Philadelphia'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PIER', number: 27, clue: 'Fishing spot'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AGFA', number: 28, clue: 'Film company not doing too well these days'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'SCREEN', number: 29, clue: 'Select, as incoming phone calls'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'IGUESS', number: 30, clue: 'Words often said with a shrug'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'SMURF', number: 31, clue: 'Animated star of a 2011 summer blockbuster'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'KIN', number: 32, clue: 'Relations'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'AJAR', number: 33, clue: 'Just open'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'JOCKSTRAP', number: 34, clue: 'It keeps balls safe on the field'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'AXEL', number: 35, clue: 'Tricky skating trick'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ROSE', number: 36, clue: '"Every ___ Has Its Thorn"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'EFT', number: 37, clue: 'Little pond dweller'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'EMT', number: 38, clue: 'Tech who usually carries an AED in her vehicle'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'TSAR', number: 39, clue: 'Autocrat before the Revolution'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'GIF', number: 40, clue: 'One may be animated'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'FEARLESS', number: 41, clue: 'Not likely to flinch'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'OXO', number: 42, clue: 'Brand at Bed Bath & Beyond'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'RAHM', number: 43, clue: 'Emanuel who succeeded Mayor Daley'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'MULATTO', number: 44, clue: 'Mixed, in antiquated census parlance'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'USE', number: 45, clue: 'Enjoy coke, say?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'EYECUPS', number: 46, clue: 'Ocular cleaning aids'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'MEECES', number: 47, clue: '"I hate those ___ to pieces!"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'END', number: 48, clue: 'Crusty bread piece'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'UVRAYS', number: 49, clue: 'Sunglasses may block them'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'VOX', number: 50, clue: 'Voice of old Rome'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'SCULPT', number: 51, clue: 'Emulate Rodin'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ANKLE', number: 52, clue: 'Place for some cute tattoos'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'HAULOFRECORDS', number: 53, clue: 'Crate digger\'s score?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'HEDGE', number: 53, clue: '___ fund (controversial investment)'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'AXONS', number: 54, clue: 'Synaptic transmitters'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'ULNAS', number: 55, clue: 'Bones often injured by tennis players'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ORB', number: 56, clue: 'Ambient electronic duo, with "the"'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EXLAX', number: 57, clue: 'Drug that keeps you going?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'CURL', number: 58, clue: 'Dumbbell exercise'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TSA', number: 59, clue: 'Gp. authorized to look through people\'s clothing'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'SETI', number: 60, clue: '"Are We Alone?" research org.'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AREA', number: 61, clue: '___ 51'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DONT', number: 62, clue: 'Fashion faux pas'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'PAULBEARER', number: 63, clue: 'McCartney\'s limo?'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'PCP', number: 63, clue: 'Angel dust'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'AAA', number: 64, clue: 'Where a baseball prospect might play'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'APE', number: 65, clue: 'CGI star of a 2011 summer blockbuster'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GNAT', number: 66, clue: 'Picnic headache'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'CAPP', number: 67, clue: 'Al who drew Li\'l Abner'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'SPATE', number: 68, clue: 'Torrent'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ESSO', number: 69, clue: 'Foreign gas brand with a red, white, and blue logo'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'PAST', number: 70, clue: 'Former'))
clues_Thats_Not_All_CR_8_18_11.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SEPIA', number: 71, clue: 'Tone option on some digital SLRs'))
Puzzle.create(title: 'That\'s Not All', grid: 'SALAD.PGAS.ABLE|ECOLI.RUGS.RAIN|GAULSTONES.INGA|AND.GEOL..AZTEC|..MAULFOODCOURT|PAOLI.SCREEN...|IGUESS.KIN.AJAR|EFT.EMT.GIF.OXO|RAHM.USE.MEECES|...UVRAYS.ANKLE|HAULOFRECORDS..|EXLAX..CURL.TSA|DONT.PAULBEARER|GNAT.CAPP.SPATE|ESSO.PAST.SEPIA', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/8/18', entries: clues_Thats_Not_All_CR_8_18_11)
