clues_The_Passing_Year_CR_12_15_11 = Array.new
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 2, dir: 'Across', answer: 'ASP', number: 1, clue: 'Armband snake'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALLUDES', number: 1, clue: 'Refers indirectly'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SKYMALL', number: 2, clue: 'In-flight catalog with an "upside-down tomato garden"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PYLON', number: 3, clue: 'Construction cone'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'WEPT', number: 4, clue: 'Broke down, in a way'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WOKS', number: 4, clue: 'Pad Thai vessels'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ERE', number: 5, clue: '"We\'ll teach you to drink deep ___ you depart": Shak.'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'PEABO', number: 6, clue: 'Bryson who paired with C&#233;line on "Beauty and the Beast"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TONAL', number: 7, clue: 'Harmonious'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'TBAR', number: 8, clue: 'Ski slope transport'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TRAUMA', number: 8, clue: 'NBC bust about paramedics'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BUGLEBOY', number: 9, clue: 'Big name in 1980s denim'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ABLATED', number: 10, clue: 'Removed by eroding'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RYE', number: 11, clue: 'Whiskey grain'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALKY', number: 12, clue: 'Person in need of rehab, say'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 2, col: 1, dir: 'Down', answer: 'AFRAME', number: 12, clue: 'House shape with a steeply sloped roof'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'OREO', number: 13, clue: 'Cookie with parallel chocolate disks'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'RUBY', number: 14, clue: 'Gem mined in Myanmar'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'FLYLIKEANEAGLE', number: 15, clue: '1976 Steve Miller Band single (*cartoonist)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'IRAISE', number: 16, clue: 'Likely words from one with a strong hand'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'EKU', number: 17, clue: 'Bluegrass State sch.'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'RUMORS', number: 18, clue: 'Spreadable stuff?'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'BAKULA', number: 19, clue: '"Quantum Leap" star Scott'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ADANA', number: 20, clue: 'Turkish city known for its kebabs'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'VOLUMETWO', number: 21, clue: 'Follow-up album, perhaps (*director)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'VALVE', number: 21, clue: 'It might help you let off some steam'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'WEI', number: 22, clue: 'Fifth-century Chinese dynasty'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'ORE', number: 23, clue: 'Miner\'s discovery'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'MEL', number: 24, clue: 'Gibson of increasingly strange box office flops'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'IFA', number: 25, clue: '"___ tree falls ..."'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'FAA', number: 26, clue: 'Org. involved in the 1981 air traffic controllers\' strike'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ABEER', number: 27, clue: '"I need ___" (Friday afternoon words)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ESL', number: 28, clue: 'Course that might maximize wk. opportunities'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'SALSA', number: 29, clue: 'Mexican restaurant freebie'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'SYD', number: 30, clue: 'Barrett profiled in "Songs in the Key of Z"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ADISH', number: 31, clue: '"Revenge is ___ ..."'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ODIE', number: 32, clue: '"Garfield Minus Garfield" character'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'HEAVYDUTY', number: 33, clue: 'Sturdy and powerful (*rapper)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'HOUSERED', number: 33, clue: 'Relatively cheap wine option, often'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'UFO', number: 34, clue: 'Craft with probes on board, apparently'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'TYBALT', number: 35, clue: 'Juliet\'s cousin'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'WEGO', number: 36, clue: '"And away ___!"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'WSJ', number: 36, clue: 'NYT alternative'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'ECO', number: 37, clue: '___-friendly'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'GOBROKE', number: 38, clue: 'Get cleaned out'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'EDIFY', number: 39, clue: 'Enlighten'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ATE', number: 40, clue: 'Had a frog in one\'s throat?'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'ASHANTI', number: 40, clue: 'One-named R&B singer with "Always on Time"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'TIECLIP', number: 41, clue: 'Dapper gent\'s accessory'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'ESSAYS', number: 42, clue: 'Cheater\'s downloads'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SCOUR', number: 43, clue: 'Use a Brillo pad on'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'READDS', number: 44, clue: 'Friends again, on Facebook'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'SOB', number: 45, clue: 'MFer'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'SIS', number: 46, clue: 'Palindromic family nickname'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'JOBSEARCH', number: 47, clue: 'Soul-sucking endeavor in a bad economy (*CEO)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'AGE', number: 48, clue: 'Go through life'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'RAPID', number: 49, clue: 'Brisk'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'CNOTE', number: 50, clue: 'Benjamin'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'ASHES', number: 51, clue: 'Word repeated in "Ring Around the Rosie"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'SPOOR', number: 52, clue: 'Trail left by an animal'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'REAGAN', number: 53, clue: 'Noted Alzheimer\'s sufferer Ronald'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ALPACA', number: 54, clue: 'Bolivian pack animal'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'AIMS', number: 54, clue: 'Prepares to fire'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 13, col: 2, dir: 'Across', answer: 'FORDEPOSITONLY', number: 55, clue: 'Words on some checks (*First Lady)'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'FOB', number: 55, clue: 'Watch chain'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'SEN', number: 56, clue: 'The Upper House, briefly'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 14, col: 2, dir: 'Across', answer: 'OKED', number: 57, clue: 'Gave the go-ahead for'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ITEM', number: 58, clue: 'Couple'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'OTIS', number: 59, clue: 'Jay-Z song that samples "Try a Little Tenderness"'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 15, col: 2, dir: 'Across', answer: 'BEDS', number: 60, clue: 'Places for planting'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'DENS', number: 61, clue: 'Fox hideouts'))
clues_The_Passing_Year_CR_12_15_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'RIP', number: 62, clue: 'Letters for the names "buried" in this puzzle\'s theme answers'))
spec_feat = '3_6:C|3_7:C|3_8:C|3_9:C|3_10:C|5_9:C|5_10:C|5_11:C|5_12:C|5_13:C|8_4:C|8_5:C|8_6:C|8_7:C|8_8:C|8_9:C|11_1:C|11_2:C|11_3:C|11_4:C|13_2:C|13_3:C|13_4:C|13_5:C|'
Puzzle.create(title: 'The Passing Year', grid: '.ASP.WEPT.TBAR.|ALKY.OREO.RUBY.|FLYLIKEANEAGLE.|RUMORS.BAKULA..|ADANA.VOLUMETWO|MEL.IFA...ABEER|ESL.SALSA..ODIE|...HEAVYDUTY...|WEGO..EDIFY.ATE|SCOUR...SOB.SIS|JOBSEARCH.ASHES|..REAGAN.ALPACA|.FORDEPOSITONLY|.OKED.ITEM.OTIS|.BEDS.DENS.RIP.', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/12/15', entries: clues_The_Passing_Year_CR_12_15_11, special_features: spec_feat)
