clues_Wrong_From_the_Start_CR_11_30_11 = Array.new
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ISTS', number: 1, clue: 'Suffixes for believers'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ISLA', number: 1, clue: 'Cuba, por ejemplo'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'STAX', number: 2, clue: 'Label for Isaac Hayes'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TABLESALT', number: 3, clue: 'Refined comestible used by pretty much every cook'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SNO', number: 4, clue: '___-Caps'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'GIDE', number: 5, clue: '1947 literature Nobelist Andre'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GELATI', number: 5, clue: 'Rich Italian desserts'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IVANOV', number: 6, clue: 'Four-act Chekhov drama'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DEW', number: 7, clue: 'Blade moisture, in the morning'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ESSO', number: 8, clue: 'Gas company that sounds like it could be spelled with two letters'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'BLESS', number: 9, clue: 'Excuse, perhaps, in church'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'BBQRUB', number: 9, clue: 'Brisket flavoring'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'LAD', number: 10, clue: 'Fellow'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ENOKI', number: 11, clue: 'Mushroom eaten with udon'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SABIN', number: 12, clue: 'Albert elected to the Polio Hall of Fame in 1958'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SLANG', number: 13, clue: 'Urbandictionary.com specialty'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'STAN', number: 14, clue: 'Word fragment repeated by Herman Cain when discussing foreign policy in October'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'EVES', number: 15, clue: 'Sleepless nights, at times'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'BANAL', number: 16, clue: 'Everyday'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LABORLAWS', number: 17, clue: 'After 40-Across, legislation meant to protect OB/GYNs from needless trips to the hospital at 2:00 a.m.?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'RESTS', number: 18, clue: 'Takes a nap, say'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'QDOBA', number: 19, clue: 'Chipotle competitor'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AXL', number: 20, clue: 'Rose who turns 50 in February'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'EAN', number: 21, clue: 'Ending with Caesar'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'OCR', number: 22, clue: 'Text-scanning tech.'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'CRIME', number: 23, clue: 'Possession or fraud'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'KIN', number: 24, clue: 'Folks'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'EASTON', number: 25, clue: 'Name in bats'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'AIRIEST', number: 26, clue: 'Most spacious and open'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'NEWLEAF', number: 27, clue: 'Fresh start, metaphorically'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'RULING', number: 28, clue: 'One might set a precedent'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'LETMEBE', number: 29, clue: '"Eff off!"'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'POSITIVEVIBE', number: 30, clue: 'After 40-Across, nagging feeling that one\'s lab test results aren\'t actually meaningful?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PILE', number: 30, clue: 'Heap'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OBIT', number: 31, clue: 'Sad news item'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'VPS', number: 32, clue: 'Bush Sr. and Nixon, e.g.'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'IBARS', number: 33, clue: 'Girder beams'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'WPM', number: 34, clue: 'Typist\'s letters?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'TBAS', number: 35, clue: 'Schedule placeholders'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'BEWITCHED', number: 36, clue: 'Sitcom in which the lead male actor magically changed in 1969'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ATIC', number: 37, clue: 'Problem ending?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SASS', number: 38, clue: 'Talk back to'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LILI', number: 39, clue: 'Taylor of "Six Feet Under"'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'FALSE', number: 40, clue: 'See 17-, 30-, 46-, and 63-Across'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'FIEND', number: 40, clue: 'Obsessed person'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'ARP', number: 41, clue: 'German/French sculptor Jean/Hans'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'META', number: 42, clue: 'Abstract, as it were'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ETTE', number: 43, clue: 'Suffix for a small product'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'IRE', number: 44, clue: 'Fury'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'LEWIS', number: 45, clue: 'Clark\'s partner in exploration'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'LORNA', number: 45, clue: '___ Doone cookies'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'STEPAEROBICS', number: 46, clue: 'After 40-Across, exercise program for klutzes?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'TOASTS', number: 47, clue: 'Moments of raised spirits?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ELIDED', number: 48, clue: 'Left out, as a syllable'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ROOFER', number: 49, clue: 'Treater of shingles?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'KEPTON', number: 50, clue: 'Persisted'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'KESHA', number: 50, clue: '"Tik Tok" singer who spells her name with a dollar sign'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'EXLAX', number: 51, clue: 'It makes waste, in a way'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'POISE', number: 52, clue: 'Composure'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'FLORET', number: 53, clue: 'Broccoli piece'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EXO', number: 54, clue: 'Endo\'s opposite'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'ADE', number: 55, clue: 'Cooling summer drink'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'EGGS', number: 56, clue: 'They might be made over hard'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ION', number: 57, clue: 'Old Saturn model'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'CBC', number: 58, clue: 'News source to the north'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'BEKI', number: 59, clue: 'Word fragment repeated multiple times by Herman Cain when discussing foreign policy in October'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'CREE', number: 60, clue: 'Fur trade tribe'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SLIMS', number: 61, clue: '"You\'ve come a long way, baby" shapes'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'MIL', number: 62, clue: 'Private address part?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'GODFATHER', number: 63, clue: 'After 40-Across, founder of an illegitimate religion?'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'OLA', number: 64, clue: 'Brazilian\'s "hello"'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'TZE', number: 65, clue: 'Taoism founder Lao-___'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'HASIT', number: 66, clue: 'Is gifted'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'GLEE', number: 67, clue: 'Fox show with choral versions of pop songs'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ZEKE', number: 68, clue: '"The Wizard of Oz" farmhand'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'AXELS', number: 69, clue: 'Skating rotations'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SADR', number: 70, clue: 'Muqtada al-___'))
clues_Wrong_From_the_Start_CR_11_30_11.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'EDIE', number: 71, clue: 'Falco of "Nurse Jackie"'))
Puzzle.create(title: 'Wrong From the Start', grid: 'ISTS.GIDE.BLESS|STAN.EVES.BANAL|LABORLAWS.QDOBA|AXL.EAN.OCR.KIN|..EASTON.RULING|POSITIVEVIBE...|IBARS..WPM.TBAS|LILI.FALSE.META|ETTE.IRE..LEWIS|...STEPAEROBICS|KEPTON.FLORET..|EXO.ADE.ION.CBC|SLIMS.GODFATHER|HASIT.GLEE.ZEKE|AXELS.SADR.EDIE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2011/11/30', entries: clues_Wrong_From_the_Start_CR_11_30_11)
