clues_campus_crosswords_jan25 = Array.new
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TEABAG', number: 1, clue: 'Pull a not at all homoerotic prank on your passed-out drunk friend'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TAP', number: 1, clue: '"I\'d ___ that"'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EUR', number: 2, clue: 'Blue cont. on a standard "Risk" board'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ARA', number: 3, clue: 'Palindromic Parseghian of Notre Dame'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'BOYMEETSWORLD', number: 4, clue: 'Television series featuring characters coming of age'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'AREA', number: 5, clue: 'What a hectare measures'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GARTER', number: 6, clue: 'Type of snake or belt'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'GARB', number: 7, clue: 'Threads'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GIRLSGONEWILD', number: 7, clue: 'Video series featuring characters who are hopefully already of age'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ALOE', number: 8, clue: 'Moisturizer additive'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RIFT', number: 9, clue: 'Falling-out'))
clues_campus_crosswords_jan25.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'BALE', number: 10, clue: 'Christian in Batman movies'))
clues_campus_crosswords_jan25.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AURORA', number: 11, clue: 'Greenery in the sky?'))
clues_campus_crosswords_jan25.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'ILIA', number: 12, clue: 'Pelvic bones'))
clues_campus_crosswords_jan25.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PRAYER', number: 13, clue: 'It might bring you to your knees'))
clues_campus_crosswords_jan25.push(Entry.create(row: 3, col: 8, dir: 'Across', answer: 'ROFL', number: 14, clue: 'Not just LOL'))
clues_campus_crosswords_jan25.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'MATHLETE', number: 15, clue: 'One taking the AIME, e.g.'))
clues_campus_crosswords_jan25.push(Entry.create(row: 4, col: 7, dir: 'Down', answer: 'HMOS', number: 16, clue: 'Managed care providers, briefly'))
clues_campus_crosswords_jan25.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'MOTE', number: 17, clue: 'Bit of a dust bunny'))
clues_campus_crosswords_jan25.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'MGMT', number: 17, clue: '"Kids" band'))
clues_campus_crosswords_jan25.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'OLIO', number: 18, clue: 'A dash of this, a smidgeon of that, ...'))
clues_campus_crosswords_jan25.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'TERN', number: 19, clue: '"...leave no ___ unstoned" (punchline of a classic Ogden Nash pun)'))
clues_campus_crosswords_jan25.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'EMS', number: 20, clue: 'Male-male-female threesome?'))
clues_campus_crosswords_jan25.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'GLEE', number: 21, clue: 'Hit television show with a multi-volume soundtrack'))
clues_campus_crosswords_jan25.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'ROGETS', number: 22, clue: 'thesaurus.com alternative'))
clues_campus_crosswords_jan25.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'EDEN', number: 23, clue: 'Place with a talking serpent'))
clues_campus_crosswords_jan25.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'TOAD', number: 24, clue: 'Mushroom-headed character in the Mario series'))
clues_campus_crosswords_jan25.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'SIRS', number: 25, clue: 'Word on mail for males'))
clues_campus_crosswords_jan25.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MIRTH', number: 26, clue: 'Merriment'))
clues_campus_crosswords_jan25.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'HIES', number: 27, clue: 'Shakes a leg'))
clues_campus_crosswords_jan25.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'SODOI', number: 28, clue: '"Same here!"'))
clues_campus_crosswords_jan25.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TONSIL', number: 29, clue: 'Uvula neighbor'))
clues_campus_crosswords_jan25.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'LETSGO', number: 30, clue: '"Are you ready yet?!"'))
clues_campus_crosswords_jan25.push(Entry.create(row: 8, col: 8, dir: 'Across', answer: 'NEAR', number: 31, clue: 'In spitting distance'))
clues_campus_crosswords_jan25.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'WEE', number: 32, clue: 'Itty-bitty'))
clues_campus_crosswords_jan25.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ENDS', number: 33, clue: 'Crappiest slices of a loaf'))
clues_campus_crosswords_jan25.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'HOBOSTEW', number: 34, clue: 'Hearty dish for a vagabond or poor student'))
clues_campus_crosswords_jan25.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'HORN', number: 34, clue: 'Feature of African geography'))
clues_campus_crosswords_jan25.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ODIE', number: 35, clue: 'Character absent in "Garfield Minus Garfield"'))
clues_campus_crosswords_jan25.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'BOAR', number: 36, clue: 'It may be served with a whole apple'))
clues_campus_crosswords_jan25.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'EKED', number: 37, clue: '___ out (just got by)'))
clues_campus_crosswords_jan25.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ODOR', number: 38, clue: 'Stank'))
clues_campus_crosswords_jan25.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'SKIRUN', number: 39, clue: 'Black diamond, e.g.'))
clues_campus_crosswords_jan25.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'RAJ', number: 40, clue: 'British rule in India'))
clues_campus_crosswords_jan25.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'UTO', number: 41, clue: '"Teach ___ Fly" (2009 single for Wiz Khalifa)'))
clues_campus_crosswords_jan25.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'NIB', number: 42, clue: 'Quill tip'))
clues_campus_crosswords_jan25.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'RIAL', number: 43, clue: 'Iranian currency'))
clues_campus_crosswords_jan25.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'GELATI', number: 44, clue: 'Frogurt alternatives'))
clues_campus_crosswords_jan25.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'NERD', number: 45, clue: '15-Across, most likely'))
clues_campus_crosswords_jan25.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'ODDJOB', number: 46, clue: 'Miscellaneous task'))
Puzzle.create(title: '01/25/2012', grid: 'TEABAG.GARB|AURORA.ILIA|PRAYER.ROFL|...MATHLETE|MOTE.EMS...|GLEE.ROGETS|MIRTH.SODOI|TONSIL.NEAR|...WEE.ENDS|HOBOSTEW...|ODOR.SKIRUN|RIAL.GELATI|NERD.ODDJOB', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_campus_crosswords_jan25, puzzle_type: 'themed')
