clues_consider_yourself_blessed = Array.new
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'EDTV', number: 1, clue: '1999 Ron Howard bomb similar to "The Truman Show"'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ELSA', number: 1, clue: '"Lohengrin" heroine'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'DITS', number: 2, clue: 'Morse code for "shies," essentially'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TMAC', number: 3, clue: 'Nickname for a seven-time N.B.A. All-Star'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'VOTE', number: 4, clue: 'Have your say'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'REBAR', number: 5, clue: 'Concrete support'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RHETT', number: 5, clue: 'Tara\'s butler'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EOS', number: 6, clue: 'Greek goddess of the dawn'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BBQ', number: 7, clue: 'Patio potluck, for short'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ABU', number: 8, clue: 'Aladdin\'s furry friend'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RYES', number: 9, clue: 'Canadian whiskeys'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'HOBO', number: 10, clue: 'Rail rider'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HYPNOTOAD', number: 10, clue: 'Mesmerizing green animal on "FuturamALL GLORY TO THE ___!'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OAR', number: 11, clue: 'It may swung to the beat of a drum'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BRO', number: 12, clue: '___-seph Stalin (comrade)'))
clues_consider_yourself_blessed.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ODD', number: 13, clue: 'Like 7 and 11'))
clues_consider_yourself_blessed.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LIMO', number: 14, clue: 'It might be a stretch'))
clues_consider_yourself_blessed.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HOBBY', number: 15, clue: '"My ___: standing in the supermarket\'s produce section holding a tube of K-Y Jelly, looking contemplative" (xkcd #236)'))
clues_consider_yourself_blessed.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'YARD', number: 16, clue: 'Pitbull\'s turf'))
clues_consider_yourself_blessed.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'STATUESQUE', number: 17, clue: 'Beautiful and dignified (are you allergic to crosswords or something?)'))
clues_consider_yourself_blessed.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'UNCLEANANIMAL', number: 18, clue: 'Pig, for some'))
clues_consider_yourself_blessed.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'PROD', number: 19, clue: 'Cattle driver'))
clues_consider_yourself_blessed.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ASCENT', number: 20, clue: 'Climb'))
clues_consider_yourself_blessed.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'SON', number: 21, clue: 'Tyrion to Tywin Lannister, in "A Song of Ice and Fire"'))
clues_consider_yourself_blessed.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'OBESE', number: 22, clue: 'Unable to leave one\'s house, perhaps'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'CTRLV', number: 23, clue: 'Paste in many systems'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'ROO', number: 24, clue: 'Hopping animal that doesn\'t fart, briefly'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'LUV', number: 25, clue: '<3'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'VIA', number: 26, clue: 'By way of'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'BOWTO', number: 27, clue: 'Honor by lowering oneself'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'WHATYOU', number: 28, clue: 'With 33-Down, \'80s sitcom catchphrase (cover your nose next time!)'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'TARHEEL', number: 29, clue: 'Sand-lapper\'s neighbour to the north'))
clues_consider_yourself_blessed.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'ONS', number: 30, clue: 'Turn-___ (leather, dimples, etc.)'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'METAL', number: 31, clue: 'Genre for Necrophagist and Cephalic Carnage'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'MAPLE', number: 31, clue: 'Canada\'s national tree'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'EMAIL', number: 32, clue: 'Where your signature might be an image'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'TALKINBOUT', number: 33, clue: 'See 28-Down'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'ARMENIA', number: 34, clue: 'Eurasian country where chess lessons are part of the public school curriculum'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'OUI', number: 35, clue: 'Yves\' yes'))
clues_consider_yourself_blessed.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ETHAN', number: 36, clue: '"The Big Lebowski" co-director Coen'))
clues_consider_yourself_blessed.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AMARE', number: 37, clue: 'Knicks\' power forward Stoudemire'))
clues_consider_yourself_blessed.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'OVA', number: 38, clue: 'Eggs in tubes or test tubes'))
clues_consider_yourself_blessed.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'SOARS', number: 39, clue: 'Takes off'))
clues_consider_yourself_blessed.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PALMA', number: 40, clue: '"Scarface" director Brian De ___'))
clues_consider_yourself_blessed.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'HEATH', number: 41, clue: 'Ledger once found on a studio\'s payroll?'))
clues_consider_yourself_blessed.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'HICCUP', number: 41, clue: 'Minor setback'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LIKEN', number: 42, clue: 'Compare (to)'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'DIDI', number: 43, clue: 'Question in response to an accusation'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'DEPICTS', number: 43, clue: 'Commemorates, as a painting might'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'INASHOE', number: 44, clue: 'Where an old woman and her many children lived'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'DATSUNS', number: 45, clue: 'Nissans, formerly'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'DYES', number: 46, clue: 'Gets light-headed, perhaps?'))
clues_consider_yourself_blessed.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'SRI', number: 47, clue: 'Hindu honorific'))
clues_consider_yourself_blessed.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ELINA', number: 48, clue: 'Latvian mezzo-soprano Garanca'))
clues_consider_yourself_blessed.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'ENACT', number: 49, clue: 'Make into law'))
clues_consider_yourself_blessed.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'THEICE', number: 50, clue: 'It might be broken at a party'))
clues_consider_yourself_blessed.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'OER', number: 51, clue: 'Francis Scott Key contraction'))
clues_consider_yourself_blessed.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'NIN', number: 52, clue: 'Writer Anais'))
clues_consider_yourself_blessed.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'PATCHOULI', number: 53, clue: 'No one who smells it on you ever suspects you\'ve been smoking weed (hanky?)'))
clues_consider_yourself_blessed.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'OSCAR', number: 54, clue: 'Canadian jazz pianist Peterson'))
clues_consider_yourself_blessed.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'DUBAI', number: 55, clue: 'Home of Burj Al Arab'))
clues_consider_yourself_blessed.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'DISH', number: 55, clue: 'Wet bar site?'))
clues_consider_yourself_blessed.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'UPTO', number: 56, clue: '___ something (hatching a scheme)'))
clues_consider_yourself_blessed.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'ISSUES', number: 57, clue: 'Emotional baggage'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IPO', number: 58, clue: 'May 18, 2012 debut for Facebook, Inc.'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'MACHUPICCHU', number: 59, clue: 'South American site (anything else I could say would blow the theme wide open)'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'ANY', number: 60, clue: 'Whichever'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'CIA', number: 61, clue: 'Cold War org.'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'HRS', number: 62, clue: 'Min. hand revolutions'))
clues_consider_yourself_blessed.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'UNE', number: 63, clue: 'A, as in "Amelie"?'))
clues_consider_yourself_blessed.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'STU', number: 64, clue: 'Disco dude on "The Simpsons"'))
clues_consider_yourself_blessed.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ANTON', number: 65, clue: 'Composer Webern or Bruckner'))
clues_consider_yourself_blessed.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'CAIRN', number: 66, clue: 'Stone monument'))
clues_consider_yourself_blessed.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HOT', number: 67, clue: 'Smokin\''))
clues_consider_yourself_blessed.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'LYSES', number: 68, clue: 'Dissolves, as cells'))
clues_consider_yourself_blessed.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ERASE', number: 69, clue: 'Wipe, as memory'))
Puzzle.create(title: 'Consider Yourself Blessed', grid: 'EDTV.REBAR.HOBO|LIMO.HOBBY.YARD|STATUESQUE.PROD|ASCENT...SON...|....CTRLV.BOWTO|METAL.OUI.ETHAN|AMARE.OVA.SOARS|PALMA....HEATH.|LIKEN.DIDI.DYES|ELINA.ENACT.OER|..NIN.PATCHOULI|DUBAI.ISSUES...|IPO.MACHUPICCHU|STU.ANTON.CAIRN|HOT.LYSES.ERASE', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_consider_yourself_blessed, puzzle_type: 'themed')
