clues_famous_last_words = Array.new
clues_famous_last_words.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SPYON', number: 1, clue: 'Peep at using binoculars, perhaps'))
clues_famous_last_words.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SINEW', number: 1, clue: 'Tendon'))
clues_famous_last_words.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PLAZA', number: 2, clue: 'Public square'))
clues_famous_last_words.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'YOKEL', number: 3, clue: 'Bumpkin'))
clues_famous_last_words.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OVERDUE', number: 4, clue: 'Like outstanding novels?'))
clues_famous_last_words.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NED', number: 5, clue: 'Patriarch of the Stark family, in "Game of Thrones"'))
clues_famous_last_words.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'YOYO', number: 6, clue: '"Around the World" toy'))
clues_famous_last_words.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'YOUR', number: 6, clue: '"There right, and ___ wrong, n00b" (typical bit of online debating)'))
clues_famous_last_words.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ORNOT', number: 7, clue: '"...that is, if you feel like it, I guess..."'))
clues_famous_last_words.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'YECCH', number: 8, clue: '"Barf out!"'))
clues_famous_last_words.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'OOH', number: 9, clue: 'Reaction to an illusionist'))
clues_famous_last_words.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'EPPS', number: 10, clue: 'Omar of "House"'))
clues_famous_last_words.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ENCHANT', number: 10, clue: 'Make magical'))
clues_famous_last_words.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'POLEVAULT', number: 11, clue: 'Event for bar hoppers?'))
clues_famous_last_words.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PAUSE', number: 12, clue: 'YouTube control with a symbol that looks like 11'))
clues_famous_last_words.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SHEEN', number: 13, clue: 'One of "Two and a Half Men," once'))
clues_famous_last_words.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ILOVE', number: 14, clue: 'Words before a rainy night or rock \'n\' roll, in song titles'))
clues_famous_last_words.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OREO', number: 15, clue: 'Snack that looks like a miniature ice cream sandwich'))
clues_famous_last_words.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'NOAH', number: 16, clue: 'It was the end of the world as they knew it, but he felt fine'))
clues_famous_last_words.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NAKEDLUNCH', number: 17, clue: '*"No got... C\'lom Fliday"'))
clues_famous_last_words.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'LINE', number: 18, clue: '"What does my character say here?"'))
clues_famous_last_words.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'CLUE', number: 19, clue: 'ANSWER (wait, I got this one backwards didn\'t I?)'))
clues_famous_last_words.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EZER', number: 20, clue: 'Old Israeli president Weizman'))
clues_famous_last_words.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'IROC', number: 21, clue: 'Chotchy Camaro'))
clues_famous_last_words.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'THESE', number: 22, clue: '"What, ___ old things?"'))
clues_famous_last_words.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'TRUE', number: 22, clue: 'Boolean logic value'))
clues_famous_last_words.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'WALDEN', number: 23, clue: '*"The sun is but a morning star."'))
clues_famous_last_words.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ETS', number: 24, clue: 'They\'re not of this earth, briefly'))
clues_famous_last_words.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'THERAVEN', number: 25, clue: '*"Shall be lifted - nevermore!"'))
clues_famous_last_words.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ETRE', number: 26, clue: 'To be in the Tour de France'))
clues_famous_last_words.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'UTEP', number: 27, clue: 'Lone Star State sch.'))
clues_famous_last_words.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'PTUI', number: 28, clue: 'Cartoon spitting sound'))
clues_famous_last_words.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'TUNA', number: 29, clue: 'Volcano roll fish'))
clues_famous_last_words.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ROBES', number: 30, clue: 'Judgmental garb'))
clues_famous_last_words.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'RIO', number: 30, clue: 'Kia coupe'))
clues_famous_last_words.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'OOF', number: 31, clue: 'Gut punch sound'))
clues_famous_last_words.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'BUTTERCUP', number: 32, clue: 'The princess bride in "The Princess Bride"'))
clues_famous_last_words.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'THERETURN', number: 33, clue: '*With 41-Across, "\'Well, I\'m back,\' he said."'))
clues_famous_last_words.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'HEN', number: 34, clue: 'Stag\'s counterpart'))
clues_famous_last_words.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'EDGY', number: 35, clue: 'Provocative'))
clues_famous_last_words.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ROO', number: 36, clue: 'Kanga\'s kin'))
clues_famous_last_words.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'NUN', number: 37, clue: 'Sister'))
clues_famous_last_words.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IOU', number: 38, clue: 'Word found in "penurious," or something penurious types don\'t like'))
clues_famous_last_words.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'SUEDE', number: 39, clue: 'Blue shoes material'))
clues_famous_last_words.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'SKYE', number: 39, clue: 'Isle in the Inner Hebrides'))
clues_famous_last_words.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'LOU', number: 40, clue: 'Cop partner of Eddie, on "The Simpsons"'))
clues_famous_last_words.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OFTHEKING', number: 41, clue: '*See 33-Across'))
clues_famous_last_words.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'HOGNOSE', number: 42, clue: 'Having a smushed up face, in some animal names'))
clues_famous_last_words.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'ERRS', number: 43, clue: 'Goofs'))
clues_famous_last_words.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'BATON', number: 44, clue: 'Conducting rod'))
clues_famous_last_words.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'BRA', number: 44, clue: 'Over-shoulder boulder holder, as they say'))
clues_famous_last_words.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ANTIFAN', number: 45, clue: 'One devoted to hating "Twilight," e.g.'))
clues_famous_last_words.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'TORY', number: 46, clue: 'Commonwealth Conservative'))
clues_famous_last_words.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'YARN', number: 47, clue: 'Knitting need'))
clues_famous_last_words.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'AGUA', number: 48, clue: 'Caliente pepper chaser'))
clues_famous_last_words.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'THEGREAT', number: 49, clue: '*With 53-Across, "So we beat on, boats against the current, borne back ceaselessly into the past."'))
clues_famous_last_words.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'TEACH', number: 49, clue: 'Edumacate'))
clues_famous_last_words.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HARPY', number: 50, clue: 'Bird-woman of myth'))
clues_famous_last_words.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'ATNOS', number: 51, clue: 'Periodic table figures, for short'))
clues_famous_last_words.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'TRIPP', number: 52, clue: 'Linda who convinced Lewinsky to not wash her semen-stained dress (later used as evidence against Clinton)'))
clues_famous_last_words.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'GATSBY', number: 53, clue: '*See 49-Across'))
clues_famous_last_words.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'SCALD', number: 54, clue: 'Throw hot water on'))
clues_famous_last_words.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'BERIO', number: 55, clue: 'Experimental composer Luciano'))
clues_famous_last_words.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'YEMEN', number: 56, clue: 'It\'s across the Gulf of Aden from Somalia'))
clues_famous_last_words.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EARNS', number: 57, clue: 'Works to deserve'))
clues_famous_last_words.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'TROU', number: 58, clue: 'You might see boxers if it\'s dropped'))
clues_famous_last_words.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'OMEN', number: 59, clue: 'It\'s a bad sign'))
clues_famous_last_words.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'ICEE', number: 60, clue: 'Slush Puppie maker'))
clues_famous_last_words.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ARCO', number: 61, clue: 'With the bow, in a string quartet score'))
clues_famous_last_words.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'ANIMALFARM', number: 62, clue: '*"...and from pig to man again; but already it was impossible to say which was which."'))
clues_famous_last_words.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'APE', number: 62, clue: 'Breast beater'))
clues_famous_last_words.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'LYE', number: 63, clue: 'Caustic cleaner'))
clues_famous_last_words.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CPUS', number: 64, clue: 'The brains of the operations, in computers: Abbr.'))
clues_famous_last_words.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'POPE', number: 65, clue: 'Tall-hatted religious leader'))
clues_famous_last_words.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'YALIE', number: 66, clue: 'Bill or Hillary, in their college days'))
clues_famous_last_words.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HYPE', number: 67, clue: '___ man (hip hop crew member responsible for pumping up the crowd)'))
clues_famous_last_words.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ESPN', number: 68, clue: 'College GameDay network'))
clues_famous_last_words.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ENDON', number: 69, clue: '___ a high note (which I\'m certainly not going to do by using partial phrases in my puzzle)'))
Puzzle.create(title: 'Famous Last Words', grid: 'SPYON.YOYO.EPPS|ILOVE.OREO.NOAH|NAKEDLUNCH.CLUE|EZER.IROC.THESE|WALDEN.THERAVEN|...UTEP..TUNA..|ROBES.THERETURN|IOU..SUEDE..LOU|OFTHEKING.BATON|..TORY..YARN...|THEGREAT.GATSBY|EARNS.TROU.ICEE|ARCO.ANIMALFARM|CPUS.POPE.YALIE|HYPE.ESPN.ENDON', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_famous_last_words, puzzle_type: 'themed')
