clues_freestyle21 = Array.new
clues_freestyle21.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PACS', number: 1, clue: 'Givers to office seekers, for short'))
clues_freestyle21.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PALLIATE', number: 1, clue: 'Ease, as chronic pain'))
clues_freestyle21.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ANAISNIN', number: 2, clue: '"House of Incest" author'))
clues_freestyle21.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'COMMUTES', number: 3, clue: 'Solves crosswords with shaky handwriting, perhaps'))
clues_freestyle21.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SNEEZEGUARD', number: 4, clue: 'Sanitary Subway barrier'))
clues_freestyle21.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'RAP', number: 5, clue: 'Genre with long lyric sheets, typically'))
clues_freestyle21.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ROCCO', number: 5, clue: 'Male pornstar Siffredi'))
clues_freestyle21.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALOHAOE', number: 6, clue: 'Classic Queen Lili\'uokalani song'))
clues_freestyle21.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'PELOSI', number: 7, clue: 'Former Speaker of the House Nancy'))
clues_freestyle21.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'JICAMA', number: 8, clue: 'Tuber also known as a Mexican Turnip'))
clues_freestyle21.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'JESUSFISH', number: 8, clue: 'Symbol you might see if you get taken for a ride by a preachy Christian?'))
clues_freestyle21.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'IDES', number: 9, clue: 'Mid-month day'))
clues_freestyle21.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CIA', number: 10, clue: 'Its memorial wall for agents who died in service contains no names, only stars'))
clues_freestyle21.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ASSAIL', number: 11, clue: 'Lambaste'))
clues_freestyle21.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MOONED', number: 12, clue: 'Offered some crack?'))
clues_freestyle21.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ANNALS', number: 13, clue: 'Historical records that are never singular'))
clues_freestyle21.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ANON', number: 14, clue: 'Shakespeare\'s river, plus a line?'))
clues_freestyle21.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'OLE', number: 15, clue: 'Cry to a hero with a cape'))
clues_freestyle21.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'EDISON', number: 16, clue: 'Inventor who invented something above the heads of inventors in cartoons'))
clues_freestyle21.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LAME', number: 17, clue: 'Far from jumping, as a party'))
clues_freestyle21.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'COLDSEASON', number: 18, clue: 'Good time to catch certain bugs'))
clues_freestyle21.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'DRILL', number: 19, clue: 'Exercise'))
clues_freestyle21.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'LIME', number: 20, clue: 'Common beer flavor, nowadays'))
clues_freestyle21.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'CHORUS', number: 21, clue: '"All together now!" song section'))
clues_freestyle21.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ANA', number: 22, clue: 'Gasteyer of SNL'))
clues_freestyle21.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ISUZUOASIS', number: 23, clue: 'Mid-\'90s Dodge Caravan alternative, named for somewhere a caravan would stop'))
clues_freestyle21.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'USARMY', number: 24, clue: 'Military branch whose 2012 budget was over $150 billion, casually'))
clues_freestyle21.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'RIEL', number: 25, clue: 'Cambodian currency'))
clues_freestyle21.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'REZAPAHLAVI', number: 25, clue: 'Exiled leader who is an "Advocate of secularism and parliamentary democracy in Iran," according to his Twitter homepage'))
clues_freestyle21.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ANTES', number: 26, clue: 'Pays to play'))
clues_freestyle21.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'OILFIELDS', number: 27, clue: 'Contentious territory in the Iraq-Kuwait War'))
clues_freestyle21.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'INPAWN', number: 28, clue: 'Hocked'))
clues_freestyle21.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TIEGAME', number: 29, clue: 'It may require extra time to resolve'))
clues_freestyle21.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'METHMOUTH', number: 30, clue: 'Tooth decay seen on "Breaking Bad"'))
clues_freestyle21.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'LINZ', number: 31, clue: 'Austrian city on the Danube'))
clues_freestyle21.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ENSURE', number: 32, clue: 'Guarantee'))
clues_freestyle21.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'SPATES', number: 33, clue: 'Outpourings'))
clues_freestyle21.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'TAKEOVER', number: 34, clue: 'Corporate raider\'s acquisition'))
clues_freestyle21.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'ELEANORA', number: 35, clue: 'Billie Holiday\'s real (and more stuffy-sounding) first name'))
clues_freestyle21.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'SARDINES', number: 36, clue: 'Metaphor for subway passengers, during rush-hour'))
clues_freestyle21.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'AMTS', number: 37, clue: 'Qtys.'))
clues_freestyle21.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'SOARS', number: 38, clue: 'Flies high'))
clues_freestyle21.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'CHAPALA', number: 39, clue: 'Mexico\'s largest freshwater lake'))
clues_freestyle21.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'CEDARED', number: 39, clue: 'Like some woodsy lodges'))
clues_freestyle21.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'GLORYHOLE', number: 40, clue: 'Aperture for anonymous public sexual encounters'))
clues_freestyle21.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'GRASPS', number: 40, clue: 'Comprehends'))
clues_freestyle21.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'LIGULE', number: 41, clue: 'Thin connective material between the sheath and blade of a grass leaf'))
clues_freestyle21.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'ONAPAR', number: 42, clue: 'Equivalent (with)'))
clues_freestyle21.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'LITEFM', number: 43, clue: 'Name of many an adult contemporary station'))
clues_freestyle21.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'WAKER', number: 44, clue: 'One that gets you up'))
clues_freestyle21.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RIND', number: 45, clue: 'Husk'))
clues_freestyle21.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'MAIDENHEAD', number: 46, clue: 'Virginity, back when it might be taken by pillagers'))
clues_freestyle21.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ELSES', number: 47, clue: 'Secondary options in some if-then statements'))
clues_freestyle21.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AGA', number: 48, clue: 'Palindromic Turkish title'))
clues_freestyle21.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'PORTAL', number: 49, clue: 'Interdimensional gateway, sometimes'))
clues_freestyle21.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'PREP', number: 49, clue: 'Get ready, quickly'))
clues_freestyle21.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'LONI', number: 50, clue: 'Anderson who portrayed Jayne Mansfield'))
clues_freestyle21.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SUPERUSERS', number: 51, clue: 'Those with root-level access, in Unix-like systems'))
clues_freestyle21.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'ENA', number: 52, clue: 'Bambi\'s aunt'))
clues_freestyle21.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'AVON', number: 53, clue: 'Shakespeare\'s soon, minus a line?'))
clues_freestyle21.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PLANET', number: 54, clue: 'One of 849 identified in the universe (as of October 12, 2012)'))
clues_freestyle21.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'FEE', number: 55, clue: 'Word after booking or agent'))
clues_freestyle21.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'VERE', number: 56, clue: '"Billy Budd" captain (anagram of EVER)'))
clues_freestyle21.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SERAPH', number: 57, clue: 'Angel that multiplies when it receives an IM?'))
clues_freestyle21.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'MDS', number: 58, clue: '"M*A*S*H" extras'))
clues_freestyle21.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'IRAS', number: 59, clue: 'Some nest eggs, for short'))
Puzzle.create(title: 'Freestyle #21', grid: 'PACS.RAP.JICAMA|ANON.OLE.EDISON|LAME.COLDSEASON|LIME.CHORUS.ANA|ISUZUOASIS.RIEL|ANTES.OILFIELDS|TIEGAME.LINZ...|ENSURE...SPATES|...AMTS.CHAPALA|GLORYHOLE.WAKER|RIND.MAIDENHEAD|AGA.PORTAL.LONI|SUPERUSERS.AVON|PLANET.FEE.VERE|SERAPH.MDS.IRAS', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_freestyle21, puzzle_type: 'freestyle')
