clues_guerrilla_hard = Array.new
clues_guerrilla_hard.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AVA', number: 1, clue: 'Female pornstar ___ Devine (You\'ll get this one from the crossings, I\'m sure)'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ALOOF', number: 1, clue: 'Detached and disinterested'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'VIRAL', number: 2, clue: 'Like the "Nyan Cat" meme'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ALEXA', number: 3, clue: 'Daughter of Billy Joel and Christie Brinkley'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'BBOYS', number: 4, clue: 'Half of the battlers in Run-DMC\'s "It\'s Like That" video'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'BITCHSLAP', number: 4, clue: 'Violently disrespect'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'BTEAMS', number: 5, clue: 'Second-stringers'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OSE', number: 6, clue: 'Suffix for sugars'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'YON', number: 7, clue: 'Opposite of hither'))
clues_guerrilla_hard.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SKY', number: 8, clue: 'Group with the 1998 hit "Some Kinda Wonderful"'))
clues_guerrilla_hard.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LIL', number: 9, clue: 'Title before Jon or Wayne'))
clues_guerrilla_hard.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ITSOK', number: 10, clue: '"Whatevs"'))
clues_guerrilla_hard.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ORE', number: 11, clue: 'Lode load'))
clues_guerrilla_hard.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'TEENY', number: 12, clue: 'Far from big, as a bopper?'))
clues_guerrilla_hard.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OAXACA', number: 13, clue: 'State that\'s the home of the Zapotec'))
clues_guerrilla_hard.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'ASIAGO', number: 14, clue: 'Often grated cheese'))
clues_guerrilla_hard.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'FLASHMOBS', number: 15, clue: 'Some Grand Central Station happenings'))
clues_guerrilla_hard.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'OUTED', number: 16, clue: 'Like some dishonourably discharged military personnel'))
clues_guerrilla_hard.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'BEARS', number: 17, clue: 'Burly gay men, in LGBT jargon'))
clues_guerrilla_hard.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'SDRAM', number: 18, clue: 'Type of flash memory'))
clues_guerrilla_hard.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ISSUED', number: 19, clue: 'Wrote, as a ticket'))
clues_guerrilla_hard.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'IDEAL', number: 20, clue: 'Optimal'))
clues_guerrilla_hard.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'IMF', number: 20, clue: 'World financial org.'))
clues_guerrilla_hard.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'DAS', number: 21, clue: '___ Boot'))
clues_guerrilla_hard.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ENT', number: 22, clue: 'Tolkien tree creature...or one tokin\' trees, in Reddit jargon'))
clues_guerrilla_hard.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'TAR', number: 23, clue: 'It\'s all over the road'))
clues_guerrilla_hard.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MANGA', number: 24, clue: 'Lolicon, e.g.'))
clues_guerrilla_hard.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'ERA', number: 25, clue: 'The Gay Nineties, e.g.'))
clues_guerrilla_hard.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'FSTOP', number: 26, clue: 'SLR setting'))
clues_guerrilla_hard.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'DSM', number: 27, clue: 'Psych. reference tome'))
Puzzle.create(title: 'Guerrilla Crosswords - Hard', grid: 'AVA.BBOYS|LIL.ITSOK|ORE.TEENY|OAXACA...|FLASHMOBS|...ISSUED|IDEAL.TAR|MANGA.ERA|FSTOP.DSM', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_guerrilla_hard, puzzle_type: 'themed')
