clues_guest_puzzle_steve_riley = Array.new
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BFFS', number: 1, clue: 'Endless buds'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BLOB', number: 1, clue: '1950\'s horror movie villain'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'FUJI', number: 2, clue: 'High point of Japan'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FRAG', number: 3, clue: 'Attack a fellow soldier'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SKIFF', number: 4, clue: 'A little dinghy?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'JOBOP', number: 5, clue: 'What a Monster seeker seeks'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'JUSTRELAX', number: 5, clue: '"Chill, guy!"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OPTS', number: 6, clue: 'Elects'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BOYOBOY', number: 7, clue: '"Golly gee!"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ONECAR', number: 8, clue: 'Garage type'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PESKY', number: 9, clue: 'Nettlesome'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MGMT', number: 10, clue: 'Execs'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MRS', number: 10, clue: 'Honorific in L.A.'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'GOEATADISK', number: 11, clue: 'Command to a frisbee dog?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MAGIC', number: 12, clue: 'Lakers\' Earvin'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TRASH', number: 13, clue: 'Pan'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LURK', number: 14, clue: 'Skulk'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'UPONE', number: 15, clue: 'Barely leading'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ROAR', number: 16, clue: 'Tiger talk'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OJAI', number: 17, clue: 'Ventura County city'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'STYES', number: 18, clue: 'Eye afflictions'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'SEGA', number: 19, clue: 'It precedes Genesis'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BIGFATSOCKS', number: 20, clue: 'What men with large feet have?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ADS', number: 21, clue: 'Sterling Cooper Draper Pryce\'s stock-in-trade'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'SWARM', number: 22, clue: 'Flock of bees'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'AIS', number: 23, clue: 'Sue Grafton\'s "___ for Alibi"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'FDR', number: 24, clue: 'NYC\'s east side hwy.'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'BAYWATCH', number: 25, clue: 'It\'s worth the Hasselhoff?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ANIMA', number: 26, clue: 'Latin soul?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PCP', number: 27, clue: 'Angeldust'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PAPI', number: 27, clue: 'Red Sox\'s Ortiz'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CLAN', number: 28, clue: 'It\'s signified by a tartan'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'POPASHERRY', number: 29, clue: 'Celebrate by opening something nice?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SENOR', number: 30, clue: 'Honorific in Havana'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'NAS', number: 31, clue: 'East-coast rapper'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ANA', number: 32, clue: 'RN Org.'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALOT', number: 33, clue: 'Oodles'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'TABOO', number: 34, clue: 'Anathema'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'LAY', number: 35, clue: 'Bed'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'PRIDES', number: 36, clue: 'Flocks of lions'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'PIPSQUEAK', number: 36, clue: 'Whippersnapper'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ECHO', number: 37, clue: 'Reverberation'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SKYS', number: 38, clue: '"The ___ the limit!"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PAPAYAS', number: 39, clue: 'South American pawpaws'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'YOYOS', number: 40, clue: 'Flip-flops'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'GIMMICK', number: 41, clue: 'Schtick'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'GOT', number: 41, clue: 'Acquired'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'INABOX', number: 42, clue: 'Where Jack lives'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'BOP', number: 43, clue: 'Charlie Parker\'s genre'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'BERMUDA', number: 43, clue: 'The Somers Isles'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ASHY', number: 44, clue: 'Nuclear winter weather report?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'SOY', number: 45, clue: 'Milk or meat substitute'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'BETSY', number: 46, clue: 'Flag-maker Ross'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'BEARER', number: 46, clue: 'Carrier'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'YUM', number: 47, clue: '"Delicious!"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'KOS', number: 48, clue: 'Boxer W\'s'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TJHOOKER', number: 49, clue: 'Shatner role'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'THAIS', number: 49, clue: 'Siamese'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'JOINT', number: 50, clue: 'Spliff'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'KLIMT', number: 51, clue: 'Creator of "The Kiss"'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'QUO', number: 52, clue: 'Status ___'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'OPTIC', number: 53, clue: 'Visionary?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HOE', number: 54, clue: 'It makes the earth move?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'SLAMBUMPERS', number: 55, clue: 'Bend each others\' fenders?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'BLIN', number: 56, clue: 'Russian pancake'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ERST', number: 57, clue: 'Once, once'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ROMO', number: 58, clue: 'Cowboys\' quarterback'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SUSS', number: 59, clue: 'Figure (out)'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AIRS', number: 60, clue: 'Something to put on'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'SEX', number: 61, clue: 'Booty'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'IRULE', number: 62, clue: 'Fitting proclamation for a king'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'TROU', number: 63, clue: 'Short pants?'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'INRE', number: 64, clue: 'Brief memo opener'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'MEDIA', number: 65, clue: 'Lamestream ___'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ISMS', number: 66, clue: 'Belief systems'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STYX', number: 67, clue: 'River you only cross once'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TRANK', number: 68, clue: 'It\'ll stop a horse in it\'s tracks, colloquially'))
clues_guest_puzzle_steve_riley.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'CTOS', number: 69, clue: 'They keep their metaphorical grids clean at work - also a hint to keeping the grid clean in 20-across, 55-across, 11-down and 29-down'))
Puzzle.create(title: 'Guest Puzzle - Keeping the Grid Clean', grid: 'BFFS.JOBOP.MGMT|LURK.UPONE.ROAR|OJAI.STYES.SEGA|BIGFATSOCKS.AIS|...FDR.BAYWATCH|PCP.SENOR.ANA..|ALOT.LAY.PRIDES|PAPAYAS.GIMMICK|INABOX.BOP.ASHY|..SOY.BETSY.KOS|TJHOOKER.QUO...|HOE.SLAMBUMPERS|AIRS.IRULE.TROU|INRE.MEDIA.ISMS|STYX.TRANK.CTOS', :constructors => Constructor.where(:name => 'Steve Riley'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_guest_puzzle_steve_riley, puzzle_type: 'themed')
