clues_mini_tl_3_cdn = Array.new
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BFF', number: 1, clue: 'Abbr. which is the title of a "Bratz" straight-to-DVD release'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BART', number: 1, clue: 'The only Simpson family member not named after someone in Matt Groening\'s immediate family'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'FLEETCARS', number: 2, clue: 'Some vehicles seen in the Zapruder film'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FLQCRISIS', number: 3, clue: 'It involved the kidnapping of James Cross and Pierre Laporte'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'OCTOBER', number: 4, clue: 'See 10-Down ... or, when the events of 3-Down took place'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'OBI', number: 4, clue: 'Japanese kimono tie mainly used for tying crosswords together'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'CROWDSOURCING', number: 5, clue: 'Distributed problem-solving approach, notably used by Vancouver police to learn the names of offenders in the 2011 riots'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TANDY', number: 6, clue: 'Actress Jessica who played Miss Daisy'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OSIS', number: 7, clue: 'Suffix with narc'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BIZ', number: 8, clue: 'Rapper ___ Markie'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'EZE', number: 9, clue: 'Sleep-___, an in-ear white noise machine'))
clues_mini_tl_3_cdn.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'RED', number: 10, clue: 'With 4-Across, object of a famous hunt'))
clues_mini_tl_3_cdn.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALL', number: 11, clue: 'The whole enchilada'))
clues_mini_tl_3_cdn.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'BRASIZE', number: 12, clue: 'One may be represented by B or C'))
clues_mini_tl_3_cdn.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'REQ', number: 13, clue: 'Not opt.'))
clues_mini_tl_3_cdn.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'IONIZED', number: 14, clue: 'Like water that some crackpot health gurus claim can reverse aging'))
clues_mini_tl_3_cdn.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'TECH', number: 15, clue: 'Cal___'))
clues_mini_tl_3_cdn.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'HENS', number: 16, clue: '___ teeth'))
clues_mini_tl_3_cdn.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'WDS', number: 17, clue: 'This puz. is full of them'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'TRENDY', number: 18, clue: 'Like organic food'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'NGO', number: 19, clue: 'Doctors Without Borders, for one: Abbr.'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'SVU', number: 20, clue: 'Letters in the title of a "Law and Order" spinoff'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'SPONGEBOB', number: 20, clue: 'One with pants of an unusual shape'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'VALUEMEAL', number: 21, clue: '32-Across offering, maybe'))
clues_mini_tl_3_cdn.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'UNOS', number: 22, clue: 'Ones in Juarez'))
clues_mini_tl_3_cdn.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ICINGS', number: 23, clue: 'Licking them off rubber spatulas is about the extent of my baking experience'))
clues_mini_tl_3_cdn.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'IBMS', number: 23, clue: 'Watson, Deep Blue, and others'))
clues_mini_tl_3_cdn.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'PAN', number: 24, clue: '"Bangarang!" crier'))
clues_mini_tl_3_cdn.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BASSOONSOLO', number: 25, clue: 'What "The Rite of Spring" opens with, notably'))
clues_mini_tl_3_cdn.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'NRA', number: 26, clue: 'Gp. with gats'))
clues_mini_tl_3_cdn.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'SANK', number: 27, clue: 'Made like the Andrea Doria'))
clues_mini_tl_3_cdn.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MRI', number: 28, clue: 'Med. scan that you have to remove your piercings for'))
clues_mini_tl_3_cdn.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'URANUS', number: 29, clue: 'One of the gas giants'))
clues_mini_tl_3_cdn.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SSS', number: 30, clue: 'The sound of sibilance'))
clues_mini_tl_3_cdn.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ORANGE', number: 31, clue: 'It almost rhymes with lozenge ... maybe?'))
clues_mini_tl_3_cdn.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'OFTEN', number: 31, clue: 'When an alcoholic drinks'))
clues_mini_tl_3_cdn.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'KFC', number: 32, clue: '"Double Down" purveyor'))
clues_mini_tl_3_cdn.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'KIMI', number: 32, clue: 'Finnish Formula One driver Raikkonen'))
clues_mini_tl_3_cdn.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'KEMP', number: 33, clue: 'Former pro football player Jack, who was also Dole\'s running mate'))
clues_mini_tl_3_cdn.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'PART', number: 34, clue: 'Hair line'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'WAPITIS', number: 35, clue: 'Elks'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'WEB', number: 35, clue: 'It may contain lies'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ALA', number: 36, clue: 'In the style of'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'PEZ', number: 37, clue: 'Dispensers hold 12 of them'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'STA', number: 38, clue: 'RR depot'))
clues_mini_tl_3_cdn.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'BEA', number: 39, clue: 'She played Dorothy on "The Golden Girls"'))
clues_mini_tl_3_cdn.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ELEMENT', number: 40, clue: 'One may be represented by B or C'))
clues_mini_tl_3_cdn.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'OAR', number: 41, clue: 'Dragonboat propeller'))
clues_mini_tl_3_cdn.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BAZINGA', number: 42, clue: 'Sheldon\'s catchphrase on "The Big Bang Theory"'))
clues_mini_tl_3_cdn.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'BLT', number: 43, clue: 'Short order at a deli?'))
Puzzle.create(title: 'Mini Freestyle #3 - Canadian Edition', grid: 'BFF.OCTOBER|ALL.BRASIZE|REQ.IONIZED|TECH.WDS...|.TRENDY.SVU|ICINGS..PAN|BASSOONSOLO|MRI..URANUS|SSS.ORANGE.|...KFC.KEMP|WAPITIS.BEA|ELEMENT.OAR|BAZINGA.BLT', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_mini_tl_3_cdn, puzzle_type: 'themed')
