clues_mini_tl_13 = Array.new
clues_mini_tl_13.push(Entry.create(row: 1, col: 3, dir: 'Across', answer: 'ZOES', number: 1, clue: '___ Dance Moves (2003 DVD release featuring Elmo\'s female counterpart)'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ZEROSUMGAMES', number: 1, clue: 'They were studied by John Nash, subject of "A Beautiful Mind"'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OLIGOPOLY', number: 2, clue: 'The American entertainment industry, for one'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ELFS', number: 3, clue: 'Characters in a 2003 Will Ferrell movie: var'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'SOFTG', number: 4, clue: 'Start to gyrate?'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'SCAMARTIST', number: 5, clue: 'Burner that tries to throw off heat?'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SLUMPED', number: 5, clue: 'Bottomed out'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'CORPORATETAXHAVEN', number: 6, clue: 'The Bahamas, e.g.'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ATA', number: 7, clue: 'One-time connector?'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'MUNG', number: 8, clue: 'Bean with a gross-sounding name'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ASIAN', number: 9, clue: 'Like gunpowder, initially'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'REUBEN', number: 10, clue: 'Katz\'s Deli choice'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TAM', number: 11, clue: 'Mortarboard alternative'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ITOO', number: 12, clue: '"Me as well," a little more elegantly'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'SERB', number: 13, clue: 'Ana Ivanovic of Tennis, e.g.'))
clues_mini_tl_13.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'TRES', number: 14, clue: 'Overly overseas'))
clues_mini_tl_13.push(Entry.create(row: 2, col: 2, dir: 'Across', answer: 'CELLO', number: 15, clue: 'Instrument covering Geddy Lee\'s parts on "The String Quartet Tribute to Rush\'s 2112"'))
clues_mini_tl_13.push(Entry.create(row: 2, col: 2, dir: 'Down', answer: 'CARLO', number: 15, clue: '"Turandot" playwright Gozzi'))
clues_mini_tl_13.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'LOTUSEATER', number: 16, clue: 'Drug abuser of Greek myth'))
clues_mini_tl_13.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TARIFF', number: 17, clue: 'Vancouver to Eugene levy?'))
clues_mini_tl_13.push(Entry.create(row: 3, col: 1, dir: 'Down', answer: 'TFAL', number: 17, clue: 'Bad cookwear for making potstickers?'))
clues_mini_tl_13.push(Entry.create(row: 3, col: 8, dir: 'Across', answer: 'URANIUMORE', number: 18, clue: 'Northern Saskatchewan find'))
clues_mini_tl_13.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'FROGSTOMP', number: 19, clue: 'Silverchair\'s debut album'))
clues_mini_tl_13.push(Entry.create(row: 4, col: 7, dir: 'Down', answer: 'OSX', number: 20, clue: 'One of a number of big cats running on computers?'))
clues_mini_tl_13.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'GAB', number: 21, clue: 'Flap'))
clues_mini_tl_13.push(Entry.create(row: 4, col: 15, dir: 'Across', answer: 'OBS', number: 22, clue: 'Delivering docs'))
clues_mini_tl_13.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ALSO', number: 23, clue: '"___ sprach Zarathustra" ("2001: A Space Odyssey" opening theme)'))
clues_mini_tl_13.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'GSPOT', number: 24, clue: 'It might be used in the making of a big O'))
clues_mini_tl_13.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'TOKEN', number: 25, clue: '___ Black ("South Park" character)'))
clues_mini_tl_13.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'NET', number: 26, clue: 'Bottom lines to help a fisherman\'s bottom line?'))
clues_mini_tl_13.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'TIA', number: 27, clue: 'Model Carrere of "Celebrity Apprentice"'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LOUPE', number: 28, clue: 'Imperfection finder\'s tool'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ERIES', number: 29, clue: 'Crosswordy northwesterners who had almost no contact with Europeans'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'XEROX', number: 30, clue: 'Company whose PARC division invented Ethernet and the Graphical User Interface'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'XANAX', number: 31, clue: 'Palindromic anti-anxiety drug sometimes used to counteract bad acid trips'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'NIFTY', number: 32, clue: 'Whizbang'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'FREAKONOMICS', number: 33, clue: '2005 non-fiction book about the Klan, sumo wrestling, and crack dealers, among other things'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 16, dir: 'Down', answer: 'TERRI', number: 34, clue: 'Clark of country music'))
clues_mini_tl_13.push(Entry.create(row: 6, col: 17, dir: 'Down', answer: 'YARDS', number: 35, clue: 'Three-foot stretches'))
clues_mini_tl_13.push(Entry.create(row: 7, col: 3, dir: 'Across', answer: 'MORE', number: 36, clue: 'Bit of 43-Down'))
clues_mini_tl_13.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'ENDON', number: 37, clue: 'Stop at'))
clues_mini_tl_13.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'DAKAR', number: 38, clue: 'Westernmost capital on the African mainland'))
clues_mini_tl_13.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'RAZED', number: 39, clue: 'Brought the house down'))
clues_mini_tl_13.push(Entry.create(row: 7, col: 14, dir: 'Across', answer: 'AREA', number: 40, clue: 'It\'s measured under curves using integrals, in math'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TAGLINE', number: 41, clue: 'Movie trailer?'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'TPAIN', number: 41, clue: 'Rapper who portrayed Frylock in the live action episode of "Aqua Teen Hunger Force"'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'ALIVE', number: 42, clue: '1993 film involving a plane crash and cannibalism'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'ETHOS', number: 43, clue: 'Collection of cultural 36-Acrosses'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'TENAM', number: 44, clue: 'When I walk down the street for a breakfast muffin on workdays'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'MINAJ', number: 45, clue: 'Nicki who released "Beez in the Trap" in 2012'))
clues_mini_tl_13.push(Entry.create(row: 8, col: 15, dir: 'Across', answer: 'ERR', number: 46, clue: 'Hit a wrong note, say'))
clues_mini_tl_13.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PLAYEDTHENAZICARD', number: 47, clue: 'Used a dirty debate tactic'))
clues_mini_tl_13.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'HOPES', number: 48, clue: 'Dreams accompaniers'))
clues_mini_tl_13.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'CANADIANA', number: 49, clue: 'Habs memorabilia, bulging jodhpurs and red coats, etc.'))
clues_mini_tl_13.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'AIM', number: 50, clue: '"Call of Duty" asset'))
clues_mini_tl_13.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'SOHOT', number: 51, clue: '"___, want to touch the hiney" (Adam Sandler in "Billy Madison")'))
clues_mini_tl_13.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'XENAKIS', number: 52, clue: '20th century composer Iannis, whose "Pithoprakta" includes 46 independent string parts'))
clues_mini_tl_13.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IVES', number: 53, clue: 'Charles of polytonal music'))
clues_mini_tl_13.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'STN', number: 54, clue: '"Empire Builder" stop, briefly'))
clues_mini_tl_13.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'NOPAR', number: 55, clue: 'Without face value'))
clues_mini_tl_13.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'REAREND', number: 56, clue: 'Behind, or smack from behind'))
clues_mini_tl_13.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'DANO', number: 57, clue: 'Actor Paul of "There Will Be Blood"'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'NESTS', number: 58, clue: 'Even bird brains know how to build them?'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'STROHS', number: 59, clue: 'Pabst product'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'SEXED', number: 60, clue: 'Course with crabs and clams?'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'DNA', number: 61, clue: 'Spiral-bound thing in a laboratory textbook?'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'JANIS', number: 62, clue: 'She toured on the "Festival Express" in 1970 with The Band and Ian & Sylvia'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 16, dir: 'Down', answer: 'IRENE', number: 63, clue: 'Name in a Carrey/Zellweger movie'))
clues_mini_tl_13.push(Entry.create(row: 12, col: 17, dir: 'Down', answer: 'SASS', number: 64, clue: 'Lip or cheek'))
clues_mini_tl_13.push(Entry.create(row: 13, col: 4, dir: 'Across', answer: 'NTH', number: 65, clue: 'High power?'))
clues_mini_tl_13.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'HOSEA', number: 66, clue: 'Text between Daniel and Joel'))
clues_mini_tl_13.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'SHANT', number: 67, clue: 'Snooty negative contraction'))
clues_mini_tl_13.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'TBSPS', number: 68, clue: 'They\'re two to a fluid oz.'))
clues_mini_tl_13.push(Entry.create(row: 13, col: 14, dir: 'Across', answer: 'DORA', number: 69, clue: 'TV explorer antagonized by Swiper the Fox'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WHO', number: 70, clue: '"Don\'t know \'em"'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 1, dir: 'Down', answer: 'WAIL', number: 70, clue: 'Play a facemelting solo'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 2, dir: 'Down', answer: 'HUME', number: 71, clue: 'David that could out-consume Wilhelm Friedrich Hegel according to Monty Python\'s "Philosopher\'s Drinking Song"'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 3, dir: 'Down', answer: 'ODIN', number: 72, clue: 'Norse-inspired "Final Fantasy" summon'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ROB', number: 73, clue: '___ blind'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 7, dir: 'Down', answer: 'BLAH', number: 74, clue: 'Tepid'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'ARABTIMES', number: 75, clue: 'Kuwaiti paper since 1977'))
clues_mini_tl_13.push(Entry.create(row: 14, col: 13, dir: 'Down', answer: 'TTOP', number: 76, clue: 'Bare-bones roof option'))
clues_mini_tl_13.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'AUDIOSLAVE', number: 77, clue: 'Band that shared three members with Rage Against the Machine'))
clues_mini_tl_13.push(Entry.create(row: 15, col: 4, dir: 'Down', answer: 'IND', number: 78, clue: 'Third party option, briefly'))
clues_mini_tl_13.push(Entry.create(row: 15, col: 8, dir: 'Down', answer: 'AVA', number: 79, clue: 'Palindromic music video prize'))
clues_mini_tl_13.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'STAINS', number: 80, clue: 'Prepares some slides'))
clues_mini_tl_13.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'IMINHEAVEN', number: 81, clue: '"This must be a dream"'))
clues_mini_tl_13.push(Entry.create(row: 16, col: 12, dir: 'Across', answer: 'PONCE', number: 82, clue: 'Puerto Rico city named for an explorer'))
clues_mini_tl_13.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'LENDSAHAND', number: 83, clue: 'Gets involved'))
clues_mini_tl_13.push(Entry.create(row: 17, col: 12, dir: 'Across', answer: 'SPAS', number: 84, clue: 'Many mani providers'))
Puzzle.create(title: 'Freestyle #13', grid: '..ZOES.SCAMARTIST|.CELLO.LOTUSEATER|TARIFF.URANIUMORE|FROGSTOMP.GAB.OBS|ALSO.GSPOT.NET...|LOUPE.XEROX.NIFTY|..MORE.DAKAR.AREA|TAGLINE.TENAM.ERR|PLAYEDTHENAZICARD|AIM.SOHOT.XENAKIS|IVES.NOPAR.DANO..|NESTS.SEXED.JANIS|...NTH.SHANT.DORA|WHO.ROB.ARABTIMES|AUDIOSLAVE.STAINS|IMINHEAVEN.PONCE.|LENDSAHAND.SPAS..', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_mini_tl_13, puzzle_type: 'freestyle')
