clues_mini_tl_7 = Array.new
clues_mini_tl_7.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SHANGHAI', number: 1, clue: 'Draft, in a way'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SHIAS', number: 1, clue: 'Some Muslims'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HITCH', number: 2, clue: 'Pickup attachment need'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ATSEA', number: 3, clue: 'Discombobulated'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'NIN', number: 4, clue: 'Trent Reznor\'s band, initially'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'GTOS', number: 5, clue: 'Classic Pontiacs'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'HATTERS', number: 6, clue: 'Their work will go right over your head'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANYONE', number: 7, clue: '"Don\'t all speak up at once"'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'IDONOT', number: 8, clue: '"Never have, never will"'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'QTIPS', number: 9, clue: 'Sound system cleaners?'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'QUI', number: 9, clue: 'Paris who?'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TIT', number: 10, clue: '"Melon"'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ITSBEST', number: 11, clue: '"We made the right choice"'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PIMENTO', number: 12, clue: 'Source of red in a martini, perhaps'))
clues_mini_tl_7.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'STETSON', number: 13, clue: '"Boss of the Plains" maker'))
clues_mini_tl_7.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HITITANDQUITIT', number: 14, clue: 'Pick up while avoiding attachment'))
clues_mini_tl_7.push(Entry.create(row: 2, col: 9, dir: 'Down', answer: 'QUES', number: 15, clue: 'Whats in Mexico?'))
clues_mini_tl_7.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ITSNOTYOUITSME', number: 16, clue: 'Dumping delivery'))
clues_mini_tl_7.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ACE', number: 17, clue: 'Hollywood\'s Ventura, e.g.'))
clues_mini_tl_7.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'STONE', number: 18, clue: 'British weight'))
clues_mini_tl_7.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'BET', number: 19, clue: 'One may be made or taken but not given'))
clues_mini_tl_7.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SHAD', number: 20, clue: 'Canadian rapper who shares a name with a small herring'))
clues_mini_tl_7.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'DERAT', number: 21, clue: 'Purge like the Pied Piper'))
clues_mini_tl_7.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'ENOS', number: 22, clue: 'He\'s two branches below Eve on the family tree'))
clues_mini_tl_7.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'MENS', number: 23, clue: 'John for John'))
clues_mini_tl_7.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'MERYL', number: 23, clue: 'Margaret\'s portrayer in "The Iron Lady"'))
clues_mini_tl_7.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'EGRET', number: 24, clue: 'White water wader'))
clues_mini_tl_7.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'GUS', number: 25, clue: 'Former "March Madness" announcer Johnson'))
clues_mini_tl_7.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'PESTO', number: 26, clue: 'Good spread to serve with Ratatouille?'))
clues_mini_tl_7.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'PAL', number: 26, clue: 'Chum (around)'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ICARUS', number: 27, clue: 'Sunburn victim of myth?'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'INSPITE', number: 27, clue: 'Not irregardless (of)'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'CAPTCHA', number: 28, clue: 'Online test that computers are meant to fail'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ANISEED', number: 29, clue: 'Sambuca flavorer'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'CARTON', number: 30, clue: 'Heavy smoker\'s purchase'))
clues_mini_tl_7.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'CLOSURE', number: 30, clue: 'Mourner\'s desire'))
clues_mini_tl_7.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NANAS', number: 31, clue: 'English sitters?'))
clues_mini_tl_7.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'SILLY', number: 32, clue: '"...let\'s not go to Camelot.  It is a ___ place." ("Monty Python and the Holy Grail")'))
clues_mini_tl_7.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'STOPGO', number: 32, clue: 'Like traffic in jams'))
clues_mini_tl_7.push(Entry.create(row: 8, col: 8, dir: 'Down', answer: 'IMOPEN', number: 33, clue: 'Cry to one in a position to pass'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SPIT', number: 34, clue: 'Fire twirler?'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ATMO', number: 35, clue: 'Spheric head?'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'ALAN', number: 35, clue: 'Pioneering radio DJ Freed'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'LAMP', number: 36, clue: 'Headwear for 38-Down'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ASIMO', number: 37, clue: 'Robot made by Honda, with a name reminiscent of the "Three Laws of Robotics" creator'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'MINER', number: 38, clue: 'Bird watcher, once upon a time'))
clues_mini_tl_7.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'PROSY', number: 39, clue: 'Mundane, like my attempts at poetry'))
clues_mini_tl_7.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'PTS', number: 40, clue: 'They\'re made by dunking, sometimes: Abbr.'))
clues_mini_tl_7.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'LOOSE', number: 41, clue: 'Roomy, as a sweater'))
clues_mini_tl_7.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ECGS', number: 42, clue: 'Ticker tape producers?'))
clues_mini_tl_7.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'SIR', number: 43, clue: 'Address for John'))
clues_mini_tl_7.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ICEDCAPPUCCINO', number: 44, clue: 'Tim Horton\'s offering, which is awesome for about 4 months of the year in Saskatchewan'))
clues_mini_tl_7.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'DHI', number: 45, clue: 'Letters after Aloha State senator Daniel Inouye\'s name'))
clues_mini_tl_7.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'CUE', number: 46, clue: 'Signal for a horn'))
clues_mini_tl_7.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'CAT', number: 47, clue: 'Source of off-color clothing fibres for some?'))
clues_mini_tl_7.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'THEHUNGERGAMES', number: 48, clue: 'Much anticipated adaptation of 2012'))
clues_mini_tl_7.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EADIE', number: 49, clue: 'Title lady in a 1932 Ethel Merman song'))
clues_mini_tl_7.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'ONESTORY', number: 50, clue: 'Like houses with easily washed windows'))
Puzzle.create(title: 'Mini Freestyle #7', grid: 'SHANGHAI.QTIPS|HITITANDQUITIT|ITSNOTYOUITSME|ACE.STONE..BET|SHAD.ENOS.MENS|...EGRET.PESTO|ICARUS..CARTON|NANAS.SILLY...|SPIT.ATMO.LAMP|PTS..LOOSE.SIR|ICEDCAPPUCCINO|THEHUNGERGAMES|EADIE.ONESTORY', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_mini_tl_7, puzzle_type: 'freestyle')
