clues_mini_tl_4 = Array.new
clues_mini_tl_4.push(Entry.create(row: 1, col: 2, dir: 'Across', answer: 'CAIRO', number: 1, clue: 'Arab Spring location'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CUDDLE', number: 1, clue: 'Couples\' get-together?'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ASAFORMALITY', number: 2, clue: 'Insincerely, perhaps'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ISM', number: 3, clue: 'Follower of Bush or Palin?'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'RYAN', number: 4, clue: 'Nugent-Hopkins on the ice'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OWNED', number: 5, clue: 'Beat, in video game slang'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'DUOS', number: 6, clue: 'Flight of the Conchords and Tenacious D'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DIS', number: 6, clue: '"Yo Mama" joke, e.g.'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'UPTO', number: 7, clue: 'As far as'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'OPENMARRIAGE', number: 8, clue: 'Swinging arrangement?'))
clues_mini_tl_4.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SEVENSAMURAI', number: 9, clue: 'Influential 1954 film on which "A Bug\'s Life" is loosely based'))
clues_mini_tl_4.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PUSSYWHIPPED', number: 10, clue: 'Unable to engage in the kind of stereotypical male behaviour seen in sexist beer commercials, perhaps'))
clues_mini_tl_4.push(Entry.create(row: 2, col: 1, dir: 'Down', answer: 'PAPAL', number: 10, clue: 'Kind of bull'))
clues_mini_tl_4.push(Entry.create(row: 2, col: 7, dir: 'Down', answer: 'HDTVS', number: 11, clue: 'Some sports bar offerings: Abbr.'))
clues_mini_tl_4.push(Entry.create(row: 2, col: 12, dir: 'Down', answer: 'DECO', number: 12, clue: 'Art style often seen in film noir'))
clues_mini_tl_4.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ADAMANDSTEVE', number: 13, clue: 'Part of an anti-gay Christian slogan'))
clues_mini_tl_4.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'PDF', number: 14, clue: 'Acrobat might be used for it: Abbr.'))
clues_mini_tl_4.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'NET', number: 15, clue: 'Acrobats might use it'))
clues_mini_tl_4.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'ONEC', number: 16, clue: 'First floor apartment number, maybe (or, what this clue has, letter-wise)'))
clues_mini_tl_4.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ALOP', number: 17, clue: 'Drooping'))
clues_mini_tl_4.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'POOR', number: 18, clue: 'Piss ___'))
clues_mini_tl_4.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'DVD', number: 19, clue: 'Place for an easter egg, perhaps'))
clues_mini_tl_4.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'DOH', number: 20, clue: '(Annoyed grunt)'))
clues_mini_tl_4.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'MNO', number: 21, clue: 'L-P track?'))
clues_mini_tl_4.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LEROI', number: 22, clue: '"The king" of France'))
clues_mini_tl_4.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'INCITED', number: 23, clue: 'Like violence, often'))
clues_mini_tl_4.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'SODAS', number: 24, clue: 'Jones et al.'))
clues_mini_tl_4.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'DOE', number: 25, clue: 'Homynym of a series starter, as pointed out in a 1959 song'))
clues_mini_tl_4.push(Entry.create(row: 7, col: 3, dir: 'Across', answer: 'MONO', number: 26, clue: 'The Beach Boys\' "Pet Sounds" was recorded in it'))
clues_mini_tl_4.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'OHNO', number: 27, clue: '"We\'re boned!"'))
clues_mini_tl_4.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'HORAS', number: 28, clue: 'Activities involving chair lifts?'))
clues_mini_tl_4.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SAMMY', number: 29, clue: 'He twice filled in for David Lee in Van Halen'))
clues_mini_tl_4.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ANARCHY', number: 30, clue: 'State of Somalia from 1991-2006, essentially'))
clues_mini_tl_4.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'ACTV', number: 30, clue: 'When Yorick\'s skull is unearthed'))
clues_mini_tl_4.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'NOWIN', number: 31, clue: 'Like a catch-22'))
clues_mini_tl_4.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'YANNI', number: 32, clue: 'One-named musician (who prefers the term "contemporary instrumental" to "new age", thank you very much)'))
clues_mini_tl_4.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'ERMA', number: 33, clue: 'Witty Bombeck'))
clues_mini_tl_4.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'COL', number: 34, clue: 'Mustard, for one: Abbr.'))
clues_mini_tl_4.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'INAN', number: 35, clue: '___ ever-changing world...'))
clues_mini_tl_4.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'NEOS', number: 36, clue: '"The Matrix" protagonist and namesakes (I assume there\'s at least one other)'))
clues_mini_tl_4.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'IUM', number: 37, clue: 'End for Titan and Nobel'))
clues_mini_tl_4.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'TWISTONESARM', number: 38, clue: 'Be persuasive'))
clues_mini_tl_4.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'SAP', number: 39, clue: 'Suck, or sucker'))
clues_mini_tl_4.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'SRS', number: 40, clue: 'Prom kings and queens, most likely: Abbr.'))
clues_mini_tl_4.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'VITAE', number: 41, clue: 'Curriculum follower'))
clues_mini_tl_4.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'NORGAY', number: 42, clue: 'He got high with Hillary'))
clues_mini_tl_4.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'NYPD', number: 43, clue: 'Gp. associated with Occupy Wall Street'))
clues_mini_tl_4.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'ISSEI', number: 44, clue: 'Japanese immigrant'))
Puzzle.create(title: 'Mini Freestyle #4', grid: '.CAIRO.DUOS.|PUSSYWHIPPED|ADAMANDSTEVE|PDF.NET.ONEC|ALOP.DVD.MNO|LEROI.SODAS.|..MONO.HORAS|ANARCHY.ERMA|COL.INAN.IUM|TWISTONESARM|VITAE.NORGAY|.NYPD.ISSEI.', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_mini_tl_4, puzzle_type: 'freestyle')
