clues_mini_tl_8 = Array.new
clues_mini_tl_8.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PAD', number: 1, clue: 'Stuff, as a bra'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PWR', number: 1, clue: 'Often the only button on a desktop computer: Abbr.'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AHA', number: 2, clue: '"I knew it all along!"'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'DONTGETCUTE', number: 3, clue: '"Spare me the lip"'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'ADFEE', number: 4, clue: 'Charge for a spot'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ASHES', number: 4, clue: 'Tidies the joint up?'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DJED', number: 5, clue: 'Spun'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'FOR', number: 6, clue: 'Pro'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EHOW', number: 7, clue: 'Site with the tagline "Discover the expert in you"'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ENSUE', number: 8, clue: 'Come after'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'STU', number: 9, clue: '"Rugrats" dad'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SAUSAGEFEST', number: 9, clue: 'Many a board games night'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TLC', number: 10, clue: 'Group with the 1994 Diamond record "CrazySexyCool"'))
clues_mini_tl_8.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'UTE', number: 11, clue: 'People indigenous to Colorado'))
clues_mini_tl_8.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'WHOISJOHNGALT', number: 12, clue: 'Iconic opening line of "Atlas Shrugged"'))
clues_mini_tl_8.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'ICET', number: 13, clue: 'Artist with the first hip-hop album to be given an "explicit content" sticker'))
clues_mini_tl_8.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'GASS', number: 14, clue: 'Black\'s Tenacious D bandmate'))
clues_mini_tl_8.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RANCHEROSAUCE', number: 15, clue: 'Part of the whole enchilada, maybe?'))
clues_mini_tl_8.push(Entry.create(row: 4, col: 3, dir: 'Across', answer: 'TEED', number: 16, clue: 'Opened a hole, with "up"'))
clues_mini_tl_8.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'WUSS', number: 17, clue: 'One to whom you might make fowl noises'))
clues_mini_tl_8.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'AGTS', number: 18, clue: 'Smart and others: Abbr.'))
clues_mini_tl_8.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'AMNIOS', number: 18, clue: 'Prenatal procedures, informally'))
clues_mini_tl_8.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ESAU', number: 19, clue: 'Vowel-heavy Genesis name'))
clues_mini_tl_8.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'UPLIFT', number: 20, clue: 'Make all warm and fuzzy'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'NME', number: 21, clue: 'British music mag that sounds like a foe'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'NOSY', number: 21, clue: 'Uncomfortably inquisitive'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'SET', number: 22, clue: 'Venn diagram circle'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'SMITES', number: 22, clue: 'Bitchslaps, biblically'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'ELAH', number: 23, clue: '"In the Valley of ___" (2007 Tommy Lee Jones film)'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TINEYE', number: 24, clue: '"Reverse image search" site'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'GPS', number: 25, clue: 'Geocaching tool, initially'))
clues_mini_tl_8.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'STAT', number: 26, clue: 'P.D.Q. in the I.C.U.'))
clues_mini_tl_8.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ONTV', number: 27, clue: 'Watched'))
clues_mini_tl_8.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'VIRAL', number: 28, clue: 'Video quality'))
clues_mini_tl_8.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'MLI', number: 29, clue: 'II^X + XXVII'))
clues_mini_tl_8.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'DELT', number: 30, clue: 'Military press target, briefly'))
clues_mini_tl_8.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'DALAI', number: 30, clue: 'Mongolian (not Tibetan) word for "ocean"'))
clues_mini_tl_8.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SICILIANMAFIA', number: 31, clue: 'Cosa Nostra'))
clues_mini_tl_8.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'LOKI', number: 32, clue: 'Norse shit disturber'))
clues_mini_tl_8.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'MRED', number: 33, clue: 'Show horse?'))
clues_mini_tl_8.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'YOUROTHERLEFT', number: 34, clue: '"No, that\'s right"'))
clues_mini_tl_8.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'STAKE', number: 35, clue: 'Weapon for Willow'))
clues_mini_tl_8.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'YEAST', number: 36, clue: '___ infection'))
clues_mini_tl_8.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'ELIS', number: 37, clue: 'Bush\'s college buddies'))
clues_mini_tl_8.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'EDIT', number: 38, clue: 'Radio ___'))
Puzzle.create(title: 'Mini Freestyle #8', grid: 'PAD.ADFEE.STU|WHOISJOHNGALT|RANCHEROSAUCE|..TEED.WUSS..|.AGTS...ESAU.|NME..SET..GPS|ONTV.MLI.DELT|SICILIANMAFIA|YOUROTHERLEFT|.STAKE.YEAST.|..ELIS.EDIT..', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_mini_tl_8, puzzle_type: 'freestyle')
