clues_not_now = Array.new
clues_not_now.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ATEAM', number: 1, clue: '2010 movie from which Mr. T was conspicuously absent, with "The"'))
clues_not_now.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ADMIRED', number: 1, clue: 'Looked up to'))
clues_not_now.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TRALALA', number: 2, clue: 'Happy refrain'))
clues_not_now.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'EARLDOM', number: 3, clue: 'Certain peer\'s title'))
clues_not_now.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AMYS', number: 4, clue: 'Authors Tan and Chua'))
clues_not_now.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'MAL', number: 5, clue: '"Firefly" protagonist, or "Inception" antagonist'))
clues_not_now.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'OREO', number: 6, clue: 'Prop for a dunk contest?'))
clues_not_now.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OMNES', number: 6, clue: 'Exeunt ___ (everyone leaves, to the Bard)'))
clues_not_now.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RIDS', number: 7, clue: 'Disburdens (of)'))
clues_not_now.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ENTEREDIN', number: 8, clue: 'Joined, as an agreement'))
clues_not_now.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ONETOTEN', number: 9, clue: 'Talc through diamond, on the Mohs scale'))
clues_not_now.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'TSPS', number: 10, clue: 'Oil amts.'))
clues_not_now.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TAR', number: 10, clue: 'Feather\'s partner'))
clues_not_now.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'STAPLES', number: 11, clue: 'Center of Los Angeles?'))
clues_not_now.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'POPINJAYS', number: 12, clue: 'Clotheshorses'))
clues_not_now.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SISSIES', number: 13, clue: 'Girlie men'))
clues_not_now.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'DRAMA', number: 14, clue: '"White Collar," for one'))
clues_not_now.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'MINN', number: 15, clue: 'Vikings\' home: Abbr.'))
clues_not_now.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ATOI', number: 16, clue: 'Yours sincerement'))
clues_not_now.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MARYLANDTERRAPINS', number: 17, clue: '2002 NCAA Men\'s Basketball Champions'))
clues_not_now.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'APT', number: 18, clue: '221B Baker St., e.g.'))
clues_not_now.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'RAYS', number: 19, clue: 'Team that lost the "Devil" in 2007'))
clues_not_now.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ILLS', number: 20, clue: 'Woes'))
clues_not_now.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'PESETA', number: 21, clue: 'Pre-Euro coin'))
clues_not_now.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'PJS', number: 22, clue: 'Wood sawer\'s attire, briefly'))
clues_not_now.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'RAD', number: 23, clue: '"Cool" that was hot in the \'90s'))
clues_not_now.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'OTS', number: 24, clue: 'NBA nailbiters'))
clues_not_now.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'OGPU', number: 24, clue: 'KGB ancestor'))
clues_not_now.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ROY', number: 25, clue: 'Award for QB Cam Newton'))
clues_not_now.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'LAI', number: 26, clue: 'Chou En-___'))
clues_not_now.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ELOPING', number: 27, clue: 'Get-hitched-quick scheme?'))
clues_not_now.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'PINUPS', number: 28, clue: 'Ones with nice gams'))
clues_not_now.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'ETS', number: 29, clue: 'F-ers of UOs'))
clues_not_now.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'EYE', number: 30, clue: 'Seer?'))
clues_not_now.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DAMUP', number: 31, clue: 'Block off, as a river'))
clues_not_now.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'CODE', number: 32, clue: 'Do lines?'))
clues_not_now.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'CAMECLOSE', number: 32, clue: 'Missed it by that much'))
clues_not_now.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'OPINE', number: 33, clue: 'Have one\'s say'))
clues_not_now.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SSSS', number: 34, clue: 'Sound from a leaky radiator, or, I don\'t know, someone who really likes the letter S'))
clues_not_now.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'STOPIN', number: 34, clue: 'Visit'))
clues_not_now.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'PUTAPININIT', number: 35, clue: 'Phrase from a procrastinator ... or an ATM user? ... or what you should do to each of five squares in this puzzle'))
clues_not_now.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'TATERTOT', number: 36, clue: 'Morsel in a school cafeteria'))
clues_not_now.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'INST', number: 37, clue: 'The I in MIT'))
clues_not_now.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BESS', number: 38, clue: 'Myerson who said "To fall in love is awfully simple, but to fall out of love is simply awful"'))
clues_not_now.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'BUTTSIN', number: 38, clue: 'Intrudes'))
clues_not_now.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'EZIOPINZA', number: 39, clue: '"Bonino" star'))
clues_not_now.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'SIMPSON', number: 40, clue: 'Homer, for one'))
clues_not_now.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'AMEN', number: 41, clue: '2012 Meek Mill single that incited a church boycott'))
clues_not_now.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'NOMAS', number: 42, clue: 'Hermano\'s uncle?'))
clues_not_now.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'MALLRAT', number: 43, clue: 'Mart-aleck?'))
clues_not_now.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'ACETONE', number: 44, clue: 'Polish remover'))
clues_not_now.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'SHIELDS', number: 45, clue: 'Actress Brooke'))
clues_not_now.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'UZI', number: 46, clue: '"Lethal Weapon" weapon'))
clues_not_now.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ETE', number: 47, clue: 'When Haiti gets hot'))
clues_not_now.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ESAU', number: 47, clue: 'He was cozened by his brother'))
clues_not_now.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'SPINACH', number: 48, clue: 'Popeye\'s food'))
clues_not_now.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TIM', number: 49, clue: 'DeKay of "White Collar"'))
clues_not_now.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'SEC', number: 50, clue: 'Jif'))
clues_not_now.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ENT', number: 51, clue: 'Seven-toed Tolkien character'))
clues_not_now.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ENCES', number: 51, clue: 'Plural suffix with refer or persist'))
clues_not_now.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'NEO', number: 52, clue: 'Role for Keanu'))
clues_not_now.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'LEI', number: 53, clue: 'Polynesian garland'))
clues_not_now.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TOP', number: 54, clue: 'V-neck, e.g.'))
clues_not_now.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'ARLENE', number: 55, clue: 'Debra Messing\'s "Garfield: The Movie" role'))
clues_not_now.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'EFTS', number: 56, clue: 'Junior newts'))
clues_not_now.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'ALTE', number: 57, clue: 'He\'s getting older by the Oder'))
clues_not_now.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'ATRA', number: 57, clue: 'Gillette brand'))
clues_not_now.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SPINSOUTOFCONTROL', number: 58, clue: 'Runs amok'))
clues_not_now.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'ODS', number: 59, clue: 'Has too much, briefly'))
clues_not_now.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'NGO', number: 60, clue: '___ Dinh Diem'))
clues_not_now.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'IZOD', number: 61, clue: 'Company with a crocodile logo'))
clues_not_now.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'OSTE', number: 62, clue: 'Bone: Prefix'))
clues_not_now.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'GRAND', number: 63, clue: 'Large in scope ... or large, in slang'))
clues_not_now.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NANS', number: 64, clue: 'Mamas\' mamas'))
clues_not_now.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TESS', number: 65, clue: '"___ of the d\'Urbervilles"'))
clues_not_now.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'OATES', number: 66, clue: 'Hall\'s musical partner'))
spec_feat = '3_14:RPIN|6_4:RPIN|8_8:RPIN|10_12:RPIN|13_2:RPIN'
Puzzle.create(title: 'Guest Puzzle - Not Now...', grid: 'ATEAM.OREO.TSPS|DRAMA.MINN.ATOI|MARYLANDTERRAPS|ILLS.PESETA.PJS|RAD.OTS.ROY.LAI|ELOPG...ETS.EYE|DAMUP.CODE.SSSS|...PUTAPINIT...|BESS.AMEN.NOMAS|UZI.ETE...SPACH|TIM.SEC.ENT.LEI|TOP.ARLENE.ALTE|SPSOUTOFCONTROL|IZOD.OSTE.GRAND|NANS.TESS.OATES', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_not_now, puzzle_type: 'themed', special_features: spec_feat)
