clues_open_the_gates = Array.new
clues_open_the_gates.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'FIZZ', number: 1, clue: 'Pop feature'))
clues_open_the_gates.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'FAN', number: 1, clue: 'Homer, to the Isotopes'))
clues_open_the_gates.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ICI', number: 2, clue: 'Part of a quote from the dubbed French version of "Poltergeist"'))
clues_open_the_gates.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ZAP', number: 3, clue: 'Nuke'))
clues_open_the_gates.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ZIPBY', number: 4, clue: 'Fly, as time'))
clues_open_the_gates.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'PHRASE', number: 5, clue: 'Jazz lick, e.g.'))
clues_open_the_gates.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'PREZ', number: 5, clue: 'Rappers Dead ___'))
clues_open_the_gates.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HECK', number: 6, clue: '"What the ___?!"'))
clues_open_the_gates.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RELIC', number: 7, clue: 'It\'s a thing of the past'))
clues_open_the_gates.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AVATAR', number: 8, clue: '2009 film featuring interspecies sex, in a way'))
clues_open_the_gates.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SEM', number: 9, clue: 'Part of a school yr.'))
clues_open_the_gates.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ESP', number: 10, clue: '"Penn & Teller: Bullshit!" subj.'))
clues_open_the_gates.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'RGS', number: 11, clue: 'QB protectors'))
clues_open_the_gates.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'REDUCE', number: 11, clue: 'Boil down'))
clues_open_the_gates.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'GAYBAR', number: 12, clue: 'It might be found under a rainbow'))
clues_open_the_gates.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'STEERS', number: 13, clue: 'They\'re castrated yet horny?'))
clues_open_the_gates.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ACAI', number: 14, clue: 'Trendy berry for health nuts'))
clues_open_the_gates.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'REEVES', number: 15, clue: 'He was Mnemonic in "Johnny Mnemonic"'))
clues_open_the_gates.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'EAT', number: 16, clue: 'Put down roots, maybe?'))
clues_open_the_gates.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NIPPLECLAMP', number: 17, clue: 'S&M device which may be substituted with a clothespin'))
clues_open_the_gates.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'LIST', number: 18, clue: 'Rattle off'))
clues_open_the_gates.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'DYE', number: 19, clue: 'Make the carpet not match the drapes, as they say'))
clues_open_the_gates.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'BIZKIT', number: 20, clue: 'Limp ___'))
clues_open_the_gates.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'RUBE', number: 21, clue: 'Inventor Goldberg'))
clues_open_the_gates.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'REDDIT', number: 21, clue: '"The front page of the Internet" site'))
clues_open_the_gates.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SPAYS', number: 22, clue: 'Fixes'))
clues_open_the_gates.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'SIS', number: 22, clue: '62-Across member'))
clues_open_the_gates.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'PLOW', number: 23, clue: 'Pusher of white powder?'))
clues_open_the_gates.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'ALBA', number: 24, clue: 'Jessica on many "Sexiest Women Alive"-type lists'))
clues_open_the_gates.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'CABLECAR', number: 25, clue: 'Gripman\'s milieu'))
clues_open_the_gates.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'BEIRUT', number: 26, clue: 'Band with the 2011 album "The Rip Tide" (and yet another name of a Eurasian metropolis in this grid)'))
clues_open_the_gates.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'LAUD', number: 27, clue: 'Props, quaintly'))
clues_open_the_gates.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ILL', number: 28, clue: 'Metal band ___ Nino'))
clues_open_the_gates.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'THC', number: 29, clue: 'Part of some oil, briefly'))
clues_open_the_gates.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'HEROIC', number: 30, clue: 'Deserving of a statue in one\'s likeness, maybe'))
clues_open_the_gates.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'CAB', number: 31, clue: 'Vehicle with a phone number on it'))
clues_open_the_gates.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'READERS', number: 32, clue: 'Tablets with "E"?'))
clues_open_the_gates.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SOBA', number: 33, clue: 'Noodle whose name means "buckwheat"'))
clues_open_the_gates.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'ATTEND', number: 34, clue: 'What I do for roughly 1/3 of my university classes'))
clues_open_the_gates.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'EAR', number: 35, clue: '___ worm (catchy song)'))
clues_open_the_gates.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ROE', number: 36, clue: 'It\'s generally not on the cheap sushi they serve for the all-you-can-eat special'))
clues_open_the_gates.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'IUD', number: 37, clue: 'Pill alternative: Abbr.'))
clues_open_the_gates.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'WATERBOARDING', number: 38, clue: 'Treatment that Christopher Hitchens underwent voluntarily'))
clues_open_the_gates.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'ESPY', number: 39, clue: '"Arthur Ashe Courage Award," for one'))
clues_open_the_gates.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'ADE', number: 40, clue: 'Ending for brig or dec'))
clues_open_the_gates.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'NORM', number: 41, clue: 'Usual way'))
clues_open_the_gates.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'GAZA', number: 42, clue: 'Famous strip'))
clues_open_the_gates.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'TSO', number: 43, clue: 'Spicy Chinese General'))
clues_open_the_gates.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EDU', number: 44, clue: 'T.A.\'s e-mail domain'))
clues_open_the_gates.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'TOAD', number: 45, clue: 'Hallucination producer when put on the tongue'))
clues_open_the_gates.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'DAN', number: 46, clue: 'Rank in the game of Go'))
clues_open_the_gates.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SLEEPIN', number: 47, clue: 'Miss "Live! with Kelly", maybe'))
clues_open_the_gates.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'SNAFUS', number: 47, clue: 'Train wrecks'))
clues_open_the_gates.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'LABATT', number: 48, clue: 'Producer of "Blue"'))
clues_open_the_gates.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'ENEMAS', number: 49, clue: 'Cleanses'))
clues_open_the_gates.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'NADINE', number: 50, clue: 'Nobelist Gordimer'))
clues_open_the_gates.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ETS', number: 51, clue: 'Dr. Zoiberg and Nibbler, on "Futurama": Abbr.'))
clues_open_the_gates.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'SAVE', number: 52, clue: 'Menu option'))
clues_open_the_gates.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'RZA', number: 53, clue: 'Wu-Tang Clan member who wrote the "Kill Bill" soundtrack'))
clues_open_the_gates.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NANNYCAM', number: 54, clue: 'Remote home monitoring option'))
clues_open_the_gates.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'MEMES', number: 55, clue: 'Rage Comics, Troll Face, and the like'))
clues_open_the_gates.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'AMMAN', number: 56, clue: 'Jordan\'s capital'))
clues_open_the_gates.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'MUZAK', number: 57, clue: 'Piped airs?'))
clues_open_the_gates.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ABED', number: 58, clue: 'Sawing logs the old-fashioned way?'))
clues_open_the_gates.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'DEJAVU', number: 59, clue: 'Feeling that\'s caused by "a glitch in the Matrix" according to Trinity'))
clues_open_the_gates.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'JARS', number: 60, clue: 'Disturbs'))
clues_open_the_gates.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ATYA', number: 61, clue: '"Comin\' ___!"'))
clues_open_the_gates.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'FAM', number: 62, clue: '___-damily'))
clues_open_the_gates.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'CLIMATEZONE', number: 63, clue: '"Polar" or "Humid Subtropical," e.g.'))
clues_open_the_gates.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'CFO', number: 63, clue: 'Big cheese of cheddar?: Abbr.'))
clues_open_the_gates.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'LID', number: 64, clue: 'Travel mug feature'))
clues_open_the_gates.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'ONO', number: 65, clue: 'Modern artist who scrawled little instructions on the walls throughout MOMA'))
clues_open_the_gates.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'NUB', number: 66, clue: 'Many a long-serving pencil'))
clues_open_the_gates.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'ESE', number: 67, clue: 'Calgary-to-Moose Jaw dir.'))
clues_open_the_gates.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'UTA', number: 68, clue: 'Broadway and crosswords superstar Hagen'))
clues_open_the_gates.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'FINERY', number: 69, clue: 'Bling, quaintly'))
clues_open_the_gates.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ANUS', number: 70, clue: 'Chocolate starfish'))
clues_open_the_gates.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STS', number: 71, clue: 'Google Maps abbrs.'))
clues_open_the_gates.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ODESSA', number: 72, clue: 'Setting of the "Potemkin Stairs"'))
clues_open_the_gates.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'KOBE', number: 73, clue: 'First name in hoops, said by Dave Chapelle while throwing an used condom into a trashcan'))
Puzzle.create(title: 'Open the Gates', grid: 'FIZZ.PHRASE.RGS|ACAI.REEVES.EAT|NIPPLECLAMP.DYE|...BIZKIT..RUBE|SPAYS..CABLECAR|ILL.THC.READERS|SOBA.EAR.IUD...|.WATERBOARDING.|...TSO.EDU.TOAD|SLEEPIN.ETS.RZA|NANNYCAM..AMMAN|ABED..DEJAVU...|FAM.CLIMATEZONE|UTA.FINERY.ANUS|STS.ODESSA.KOBE', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_open_the_gates, puzzle_type: 'themed')
