clues_play_that_funky_music = Array.new
clues_play_that_funky_music.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'LET', number: 1, clue: 'Permit'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'LBJ', number: 1, clue: 'Pres. to whom Forrest Gump exposed his wounded buttocks'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ERA', number: 2, clue: 'A history class might cover one per lecture'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TAZ', number: 3, clue: 'Looney Tunes character from the Southern Hemisphere, familiarly'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'FRANK', number: 4, clue: 'With 62-Across, speaker of the quote at 16/41-Across'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'FESS', number: 4, clue: 'Own (up)'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RANT', number: 5, clue: 'Specialty of Rick Mercer (CanCon alert!) and Dennis Miller'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ATOB', number: 6, clue: 'Go from ___ (complete step 1)'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NOTO', number: 7, clue: 'Just say ___ drugs'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'KUDU', number: 8, clue: 'Large African antelope with helical horns'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'OWE', number: 9, clue: 'Be on the run from a bookie'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OCD', number: 9, clue: 'Condition of TV\'s Monk'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'WII', number: 10, clue: 'Gaming system that makes you sweat'))
clues_play_that_funky_music.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EAT', number: 11, clue: 'Snarf'))
clues_play_that_funky_music.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BRA', number: 12, clue: 'It holds half of T&A'))
clues_play_that_funky_music.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'BEATOUT', number: 13, clue: 'Knock from the Open, say'))
clues_play_that_funky_music.push(Entry.create(row: 2, col: 5, dir: 'Down', answer: 'BIAS', number: 13, clue: 'Inclination'))
clues_play_that_funky_music.push(Entry.create(row: 2, col: 11, dir: 'Down', answer: 'TEND', number: 14, clue: 'Be inclined'))
clues_play_that_funky_music.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'CIA', number: 15, clue: 'Org. in the "Bourne" series'))
clues_play_that_funky_music.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'JAZZISNOTDEADIT', number: 16, clue: 'Start of a quote by 4/62-Across'))
clues_play_that_funky_music.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'ZENO', number: 17, clue: 'He argued that, paradoxically, motion should be impossible'))
clues_play_that_funky_music.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'ADIA', number: 18, clue: 'Sarah McLachlan ballad'))
clues_play_that_funky_music.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'EASTBOUND', number: 19, clue: 'Like Amtrak\'s "Empire Builder," half of the time'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'MTNS', number: 20, clue: 'They\'re within a certain range: Abbr.'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'MILIEUS', number: 20, clue: 'Social environments'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'TRAMPSTAMPS', number: 21, clue: 'They involve temporary lower back pain'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'DIET', number: 22, clue: '100-mile or Paleo, e.g.'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'ENDSINTEARS', number: 23, clue: 'Doesn\'t go so well'))
clues_play_that_funky_music.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'TURNONS', number: 24, clue: 'Balloons, to a "looner"'))
clues_play_that_funky_music.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'MIRO', number: 25, clue: 'Spanish surrealist Joan'))
clues_play_that_funky_music.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'MARYJ', number: 25, clue: 'Blige of hip-hop, or what she might smoke'))
clues_play_that_funky_music.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'ANUS', number: 26, clue: '30-Across, medically'))
clues_play_that_funky_music.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'STONY', number: 27, clue: 'Like some gazes and silences'))
clues_play_that_funky_music.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALA', number: 28, clue: 'Chicken--king connection'))
clues_play_that_funky_music.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'DRT', number: 29, clue: 'Title character for Mr. Gere, in a film that sounds vaguely like a porno'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RIM', number: 30, clue: '26-Across, slangily'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'HOSNI', number: 31, clue: 'First name in 2011 Egyptian revolution news'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'HUM', number: 31, clue: 'Strange sound, as seen in many a YouTube video of late'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'ONE', number: 32, clue: 'The multiplicative identity'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 8, dir: 'Down', answer: 'STL', number: 33, clue: 'Cardinal letters?'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'NFL', number: 34, clue: 'Org. that just had a big weekend (assuming you\'re doing this puzzle during the week of Feb 5, 2012)'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ILS', number: 35, clue: 'They, in Tours'))
clues_play_that_funky_music.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SNO', number: 36, clue: '___-Cat (winter vehicle)'))
clues_play_that_funky_music.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'YEP', number: 37, clue: '"Affirmative"'))
clues_play_that_funky_music.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'AUNTFLO', number: 38, clue: 'Visitor that can cramp your sex life (or give you cramps), in slang'))
clues_play_that_funky_music.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'ASSHAT', number: 38, clue: 'Buffoon, in Internet jargon'))
clues_play_that_funky_music.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'OFACES', number: 39, clue: 'They\'re shown during la petite mort, in slang'))
clues_play_that_funky_music.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ION', number: 40, clue: 'One that\'s not neutral'))
clues_play_that_funky_music.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'JUSTSMELLSFUNNY', number: 41, clue: 'End of the quote'))
clues_play_that_funky_music.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'TUT', number: 42, clue: 'King in a classic Steve Martin song'))
clues_play_that_funky_music.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'URN', number: 43, clue: 'It contains remains'))
clues_play_that_funky_music.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'STUS', number: 44, clue: 'The dad on "Rugrats" and a character on "The Simpsons" with an afro'))
clues_play_that_funky_music.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'ARTS', number: 45, clue: 'Graffiti and dubstep, like it or not'))
clues_play_that_funky_music.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'ATHS', number: 46, clue: 'Pitchers and catchers, briefly'))
clues_play_that_funky_music.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'SPAZ', number: 47, clue: '___ out (go apeshit)'))
clues_play_that_funky_music.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ACNE', number: 48, clue: 'Teenage eruption'))
clues_play_that_funky_music.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ALMA', number: 48, clue: '___ mater'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BAM', number: 49, clue: 'Lagasse\'s catchphrase'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'BAD', number: 49, clue: '18-minute Michael Jackson music video directed by Martin Scorsese'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'AMI', number: 50, clue: 'Frere from another mere'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'APOSTLE', number: 51, clue: 'Chris Rock played the 13th one in "Dogma"'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'OMA', number: 52, clue: 'Gunther\'s granny'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'STP', number: 53, clue: 'Oil additive inits.'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'TAP', number: 54, clue: '"I\'d ___ that"'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'APT', number: 55, clue: 'Keen, as a pupil'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'POO', number: 56, clue: 'Mr. Hankey, for one'))
clues_play_that_funky_music.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'TON', number: 57, clue: 'Long or short quantity'))
clues_play_that_funky_music.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AMP', number: 58, clue: 'It might have EQ and tone control built in'))
clues_play_that_funky_music.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TAMTAMS', number: 59, clue: 'The proper name for large, supended, orchestral gongs (actual gongs are smaller and have a definite pitch)'))
clues_play_that_funky_music.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ROO', number: 60, clue: 'Owl\'s pal'))
clues_play_that_funky_music.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DIS', number: 61, clue: 'Play starter?'))
clues_play_that_funky_music.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ZAPPA', number: 62, clue: 'See 4-Across'))
clues_play_that_funky_music.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SON', number: 63, clue: 'Bastard, perhaps'))
Puzzle.create(title: 'Play That Funky Music', grid: 'LET..FRANK..OWE|BRA.BEATOUT.CIA|JAZZISNOTDEADIT|...EASTBOUND...|.MTNS.....DIET.|MIRO.......ANUS|ALA.........DRT|RIM..HOSNI..SNO|YEP.AUNTFLO.ION|JUSTSMELLSFUNNY|.STUS.....ARTS.|..ATHS...ACNE..|BAM.APOSTLE.APT|AMP.TAMTAMS.ROO|DIS..ZAPPA..SON', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_play_that_funky_music, puzzle_type: 'themed')
