clues_really_packing_it_in = Array.new
clues_really_packing_it_in.push(Entry.create(row: 1, col: 2, dir: 'Across', answer: 'CHALET', number: 1, clue: 'Where snowboarders might board'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CLUSTERED', number: 1, clue: 'Like some distributed computing systems'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'HALLOWEENAPPLES', number: 2, clue: '*Next meal: healthy mid-day snacks (in October)'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EMER', number: 3, clue: 'The first letter of ER'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TED', number: 4, clue: '2012 Seth MacFarlane comedy'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'THAT', number: 5, clue: 'Partner of this'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TWISTY', number: 5, clue: 'Gnarly'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HETERO', number: 6, clue: 'Prefix with normativity, in queer theory'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ADIEU', number: 7, clue: 'Final bid?'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TONGS', number: 8, clue: 'Sausage grippers'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'EUCHRE', number: 9, clue: 'Trick game that introduced the joker to the standard deck'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ETE', number: 9, clue: 'Somme summer solstice season'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'URNS', number: 10, clue: 'Carafes\' cousins'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CHRISTMASTURKEY', number: 11, clue: '*Final meal: dinner bird (in December)'))
clues_really_packing_it_in.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EASYASABC', number: 12, clue: 'A snap'))
clues_really_packing_it_in.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALLME', number: 13, clue: '"I got this"'))
clues_really_packing_it_in.push(Entry.create(row: 2, col: 1, dir: 'Down', answer: 'AQUA', number: 13, clue: 'Bluish-green'))
clues_really_packing_it_in.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'WEDO', number: 14, clue: 'Song sung by The Stonecutters," which is the answer to the question "who keeps Atlantis off the maps?"'))
clues_really_packing_it_in.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'TRISTAR', number: 15, clue: 'Sony Pictures subsidiary with a pegasus in its logo'))
clues_really_packing_it_in.push(Entry.create(row: 2, col: 16, dir: 'Down', answer: 'REEL', number: 16, clue: 'It\'s 70mm wide for IMAX projections'))
clues_really_packing_it_in.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'QUEENED', number: 17, clue: 'Like some pawns'))
clues_really_packing_it_in.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'ITIN', number: 18, clue: '"Is ___ yet?" (penetrating question to a not-so-well-endowed lover, perhaps)'))
clues_really_packing_it_in.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ENMASSE', number: 19, clue: 'How crowds doing "the wave" move'))
clues_really_packing_it_in.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'USAR', number: 20, clue: 'Part time soldiers\' org.'))
clues_really_packing_it_in.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'EASTEREGG', number: 21, clue: '*First meal: breakfast staple (in March or April)'))
clues_really_packing_it_in.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'EAST', number: 21, clue: 'Way to travel around the equator to speed up time'))
clues_really_packing_it_in.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'GAB', number: 22, clue: 'Run off at the mouth'))
clues_really_packing_it_in.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'STYE', number: 23, clue: 'Eye affliction'))
clues_really_packing_it_in.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ATP', number: 24, clue: 'Org. for netmen (not netwomen, alas)'))
clues_really_packing_it_in.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'ASYOUSAY', number: 25, clue: 'Words from one agreeing to follow orders'))
clues_really_packing_it_in.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'AON', number: 25, clue: 'Get an ___ (smoke, as a test)'))
clues_really_packing_it_in.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'YOO', number: 26, clue: 'First of two rhyming attention-getting syllables'))
clues_really_packing_it_in.push(Entry.create(row: 5, col: 14, dir: 'Across', answer: 'UAL', number: 27, clue: 'Suffix for man and spirit'))
clues_really_packing_it_in.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'EPCOT', number: 28, clue: 'Disney World theme park'))
clues_really_packing_it_in.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'COLOR', number: 29, clue: 'Hue that I spell with a \'u\''))
clues_really_packing_it_in.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'BOARS', number: 30, clue: 'Babe\'s savage cousins'))
clues_really_packing_it_in.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'ASDOI', number: 31, clue: '"Same here"'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ORLON', number: 32, clue: 'Acrylic fiber trademarked by DuPont'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'OHO', number: 32, clue: '"So that\'s how it\'s going to be!"'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'JIMI', number: 33, clue: 'First name in guitar conflagrating'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'JACKSQUAT', number: 33, clue: 'Sweet fuck all'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ISO', number: 34, clue: 'Metric prefix'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'MAD', number: 35, clue: 'Bonkers'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'IPADDRESS', number: 36, clue: 'Name : Phone no. :: URL : ___'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'OSKAR', number: 37, clue: 'Schindler of a notable black and white movie'))
clues_really_packing_it_in.push(Entry.create(row: 7, col: 16, dir: 'Down', answer: 'RTE', number: 38, clue: 'Short path?'))
clues_really_packing_it_in.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'HEEL', number: 39, clue: 'Wardrobe part that doubles as a knife for Catwoman in "The Dark Knight Rises"'))
clues_really_packing_it_in.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'ASAP', number: 40, clue: '"Lickety split!"'))
clues_really_packing_it_in.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'DEBT', number: 41, clue: '"I.O.U.S.A." subject'))
clues_really_packing_it_in.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ODSON', number: 42, clue: 'Takes to much of, briefly'))
clues_really_packing_it_in.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'NOHEART', number: 43, clue: 'One of the villains in the "Care Bears" cartoon'))
clues_really_packing_it_in.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'CODA', number: 44, clue: 'Where a perfect authentic cadence might be found, in music'))
clues_really_packing_it_in.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'JOYCE', number: 45, clue: 'Author James with an alliterative name'))
clues_really_packing_it_in.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'JETSKIS', number: 45, clue: 'Tubers\' towers, sometimes'))
clues_really_packing_it_in.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ROCK', number: 46, clue: 'Metal may be found in it (in a few ways)'))
clues_really_packing_it_in.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'CIS', number: 47, clue: 'Opposite of trans-'))
clues_really_packing_it_in.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'DREI', number: 48, clue: 'Three, to Klaus Teuber'))
clues_really_packing_it_in.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'RAE', number: 49, clue: 'Canadian pop idol Carly ___ Jepsen, who sings "Call Me Maybe"'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ACK', number: 50, clue: '"Gah!" in the funny pages'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'ATPAR', number: 50, clue: 'How some stocks are bought and sold'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'CHASE', number: 51, clue: 'It goes after a wild goose?'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'KRUPA', number: 52, clue: 'Legendary jazz drummer Gene'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'HISSEDAT', number: 53, clue: 'Threatened'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'SURLY', number: 54, clue: 'One of The Seven Duffs of "The Simpsons," along with Sleazy, Tipsy, et al.'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'EAGLE', number: 55, clue: 'Steve Miller wants to fly like one'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 14, dir: 'Across', answer: 'ILL', number: 56, clue: 'Not well'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'IDLER', number: 56, clue: 'Goldbricker'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'LAINE', number: 57, clue: '"That\'s My Desire" singer Frankie'))
clues_really_packing_it_in.push(Entry.create(row: 11, col: 16, dir: 'Down', answer: 'LYSES', number: 58, clue: 'Ruptures, as a cell wall'))
clues_really_packing_it_in.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'THREESQUARESADAY', number: 59, clue: 'Room and board offering . . . and a hint to this puzzle\'s theme'))
clues_really_packing_it_in.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'ELEC', number: 60, clue: 'Co. replaced by a Piranha Plant on the Nintendo Collector\'s Edition "Monopoly" board'))
clues_really_packing_it_in.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'AERO', number: 61, clue: 'Without it, Boeing manufactures nautical crafts?'))
clues_really_packing_it_in.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PAULA', number: 62, clue: 'Cruciverbalist Gamache or judge Adbul'))
clues_really_packing_it_in.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'URGE', number: 63, clue: 'Implore'))
clues_really_packing_it_in.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'KELIS', number: 64, clue: 'Singer with that silly "Milkshake" song'))
clues_really_packing_it_in.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ASPER', number: 65, clue: 'In accordance with'))
clues_really_packing_it_in.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ALLS', number: 66, clue: '"___ I said was..."'))
clues_really_packing_it_in.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'IRENE', number: 67, clue: 'Woman\'s name in a 2000 Zellweger/Carrey comedy'))
clues_really_packing_it_in.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REACT', number: 68, clue: 'Flinch'))
clues_really_packing_it_in.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'TYES', number: 69, clue: 'Nautical ropes'))
clues_really_packing_it_in.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SORES', number: 70, clue: 'They may be of the cold variety, on the lips'))
spec_feat = "1_3:RHAL|2_3:RLOW|3_3:REEN|1_14:RCHR|2_14:RIST|3_14:RMAS|4_6:REA|4_7:RST|4_8:RER"
Puzzle.create(title: 'Really Packing It In', grid: '.CHET.THAT.EUCE.|ALLME.WEDO.TRIAR|QUEED.ITIN.ENMSE|USAR.ESEEGG.STYE|ATP.ASYOUSAY.UAL|.EPCOT....BOARS.|ORLON.JIMI.OSKAR|HEEL..ASAP..DEBT|ODSON.CODA.JOYCE|...ROCK..DREI...|ACK.HISSEDAT.ILL|THREESQUARESADAY|PAULA.URGE.KELIS|ASPER.ALLS.IRENE|REACT.TYES.SORES', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_really_packing_it_in, special_features: spec_feat, puzzle_type: 'themed')
