clues_take_the_day_off = Array.new
clues_take_the_day_off.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JAB', number: 1, clue: 'Ring toss?'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JWOWW', number: 1, clue: 'Snooki\'s co-star in a recently debuted "Jersey Shore" spinoff'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AISHA', number: 2, clue: 'Actress Tyler of "The Talk"'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BITER', number: 3, clue: 'Dirty fighter'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'AUDI', number: 4, clue: 'Car with a four-ring logo'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'APPLETV', number: 4, clue: 'iTunes receiver'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'UAL', number: 5, clue: 'Carrier whose theme song is "Rhapsody in Blue": Abbr.'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'DIAMOND', number: 6, clue: 'Base formation?'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'INNER', number: 7, clue: 'Tube or circle opening'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'PASCAL', number: 8, clue: 'Mathematician Blaise who invented the mechanical calculator'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PETCATS', number: 8, clue: 'What some crazy old ladies have in abundance'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ALE', number: 9, clue: 'Blonde or ginger, e.g.'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SPAT', number: 10, clue: 'Falling out'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CAREBEARS', number: 11, clue: 'Tenderheart and others'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ASTRO', number: 12, clue: 'Minute Maid Park player'))
clues_take_the_day_off.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'LOHAN', number: 13, clue: 'Her name was the second Google Instant result after typing just "lin" (these clues practically write themselves!)'))
clues_take_the_day_off.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'WII', number: 14, clue: '"New Super Marios Bros." platform'))
clues_take_the_day_off.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'PAIN', number: 15, clue: 'You\'ve got a lot of nerves to sense it'))
clues_take_the_day_off.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'ELPASO', number: 16, clue: 'Southern border city'))
clues_take_the_day_off.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OST', number: 17, clue: 'Like Belarus, to a German'))
clues_take_the_day_off.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'PLANETEARTH', number: 18, clue: 'The first program to air on BBC HD'))
clues_take_the_day_off.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'ELISA', number: 19, clue: 'Napoleon Bonaparte\'s sister (this name seemed more common when I put it in the grid)'))
clues_take_the_day_off.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'WHEEL', number: 20, clue: 'Revolutionary invention?'))
clues_take_the_day_off.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'EMERALD', number: 21, clue: '___ City (experimental prison unit in HBO\'s "Oz")'))
clues_take_the_day_off.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'MELC', number: 22, clue: '"Sporty Spice"'))
clues_take_the_day_off.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'TERA', number: 23, clue: 'Kilo : Mega :: Giga : ___'))
clues_take_the_day_off.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'WARMEMORIAL', number: 24, clue: 'The Arc de Triomphe, e.g.'))
clues_take_the_day_off.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'MOE', number: 25, clue: 'Duff Beer pourer'))
clues_take_the_day_off.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'LOP', number: 26, clue: 'Amputate, with "off"'))
clues_take_the_day_off.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'BON', number: 27, clue: '"Good Godot!"'))
clues_take_the_day_off.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ETON', number: 28, clue: 'Captain Hook\'s alma mater (but not J.M. Barrie\'s)'))
clues_take_the_day_off.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'STOWE', number: 29, clue: 'Uncle Tom creator'))
clues_take_the_day_off.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'WHATTHE', number: 30, clue: '"Did I miss something?"'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'STARVED', number: 31, clue: 'Deprived'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'SLO', number: 31, clue: '___-pitch softball'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'TED', number: 32, clue: 'Group that staged a fictional talk for the "Prometheus" viral marketing campaign'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ANDCHANGE', number: 33, clue: 'Plus a bit extra'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'ASPHALT', number: 34, clue: 'Drag coverer?'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'LEO', number: 35, clue: 'He was J. in "J. Edgar" and will be Jay in "The Great Gatsby"'))
clues_take_the_day_off.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'TAN', number: 36, clue: 'You might get one on a bed'))
clues_take_the_day_off.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LENA', number: 37, clue: '___ Dunham, creator and star of HBO\'s "Girls"'))
clues_take_the_day_off.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'AREA', number: 38, clue: 'Geometry measure'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ODDLOTS', number: 39, clue: 'Stock purchases of fewer than 100 shares'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'ORS', number: 40, clue: 'Breast reduction locations, for short'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'TOTALBS', number: 41, clue: 'Lies, lies, lies, briefly'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'SMELL', number: 42, clue: 'Sample a bouquet'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'SHITSON', number: 43, clue: '"Awww snap"'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'SAFEBET', number: 43, clue: 'Sure thing'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'HUA', number: 44, clue: '___ Mulan (character of Chinese legend upon which Disney\'s "Mulan" was based)'))
clues_take_the_day_off.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'INTERNS', number: 45, clue: 'Ones practicing medicine?'))
clues_take_the_day_off.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'CDROM', number: 46, clue: 'A typical one can store roughly the same amount of information as the human genome'))
clues_take_the_day_off.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'AUNT', number: 47, clue: 'The Fresh Prince\'s lived in Bel Air'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NIH', number: 48, clue: 'Federal research org. that funded the Guatemala Syphilis Experiment'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'NUMBS', number: 48, clue: 'Administers a local anesthetic'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ISAAK', number: 49, clue: '"Wicked Game" singer Chris'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'STEPFATHERS', number: 50, clue: 'Claudius of "Hamlet" and Robert Baratheon of "Game of Thrones" (spoiler alert!)'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'PEARL', number: 51, clue: 'Bit of wisdom'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'ERWIN', number: 52, clue: 'Schr&#246;dinger with a famous paradox about a cat'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'RIATA', number: 53, clue: 'Gaucho\'s grabber'))
clues_take_the_day_off.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SEXTS', number: 54, clue: 'Discusses fingering with the thumbs?'))
clues_take_the_day_off.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'USAF', number: 55, clue: 'Mil. branch that once used "Aim High" as a recruiting slogan'))
clues_take_the_day_off.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'FUJI', number: 56, clue: 'Mountain represented in the Infiniti logo'))
clues_take_the_day_off.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'ALEE', number: 57, clue: 'Out of wind?'))
clues_take_the_day_off.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'EERIE', number: 58, clue: 'Unsettling'))
clues_take_the_day_off.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MANUALLABOR', number: 59, clue: 'Work on the chain gang'))
clues_take_the_day_off.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'AON', number: 60, clue: 'Insurance giant with an eponymous Chicago skyscraper'))
clues_take_the_day_off.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'OID', number: 61, clue: 'Meteor tail?'))
clues_take_the_day_off.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'WAX', number: 62, clue: 'Make a landing strip, maybe'))
clues_take_the_day_off.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BAGJOB', number: 63, clue: 'Illegal entry by a government spy, slangily'))
clues_take_the_day_off.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'REIN', number: 64, clue: 'It\'s held with one hand in Polo'))
clues_take_the_day_off.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ITT', number: 65, clue: 'Addams family member whose name in the Hungarian version translates to "Cousin Whatshisname"'))
clues_take_the_day_off.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SKEINS', number: 66, clue: 'Yarn units'))
clues_take_the_day_off.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'LTDS', number: 67, clue: '\'80s Fords'))
clues_take_the_day_off.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'NAS', number: 68, clue: 'Rapper whose "Illmatic" record was released 18 years ago (am I really that old?)'))
instructions = 'This week\'s contest answer is a brand of alcohol.'
explanation = '<MA>BOMBAY SAPPHIRE</MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'Take the Day Off and Get Stoned (Month of Metas 3/4)', grid: 'JAB.AUDI.PASCAL|WII.PAIN.ELPASO|OST.PLANETEARTH|WHEEL.MELC.TERA|WARMEMORIAL.BON|...ETON.STOWE..|STARVED.ASPHALT|LENA.......AREA|ODDLOTS.SHITSON|..CDROM.AUNT...|NIH.STEPFATHERS|USAF.ALEE.EERIE|MANUALLABOR.WAX|BAGJOB.REIN.ITT|SKEINS.LTDS.NAS', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_take_the_day_off, puzzle_type: 'meta', instructions: instructions, explanation: explanation)
