clues_themeless_11 = Array.new
clues_themeless_11.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SUNSTROKE', number: 1, clue: 'UV OD, less briefly?'))
clues_themeless_11.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SFPD', number: 1, clue: 'Grp. that investigated the Zodiac murders'))
clues_themeless_11.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ULLA', number: 2, clue: 'Uma\'s role in "The Producers"'))
clues_themeless_11.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NAAN', number: 3, clue: 'Flatbread with vindaloo'))
clues_themeless_11.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'STYLISH', number: 4, clue: 'In'))
clues_themeless_11.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TPS', number: 5, clue: '"Decorates" a tree: Abbr.'))
clues_themeless_11.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RAW', number: 6, clue: '"WWE ___" (SmackDown alternative)'))
clues_themeless_11.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ONE', number: 7, clue: 'Zero factorial, in math'))
clues_themeless_11.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'KELP', number: 8, clue: 'Delicacy for a Dugong'))
clues_themeless_11.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ELLEN', number: 9, clue: '\'90s sitcom with a famous coming-out episode'))
clues_themeless_11.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'ZOOTSUITS', number: 10, clue: '1943 riot gear?'))
clues_themeless_11.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ZHIVAGO', number: 10, clue: 'Doctor of letters?'))
clues_themeless_11.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'OAT', number: 11, clue: 'Kashi ingredient'))
clues_themeless_11.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OSHA', number: 12, clue: 'Org. concerned with ergonomic office supplies'))
clues_themeless_11.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TTOP', number: 13, clue: '"Smokey and the Bandit" car feature'))
clues_themeless_11.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SOTS', number: 14, clue: 'Many Bukowski characters (write what you know, eh?)'))
clues_themeless_11.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'USHER', number: 15, clue: 'R&B singer who was seen texting during the sign-off of the SNL episode he co-hosted'))
clues_themeless_11.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'ITE', number: 16, clue: 'Cousin of -ian'))
clues_themeless_11.push(Entry.create(row: 1, col: 18, dir: 'Down', answer: 'TAR', number: 17, clue: 'Black ___ heroin'))
clues_themeless_11.push(Entry.create(row: 1, col: 19, dir: 'Down', answer: 'SYS', number: 18, clue: 'Part of iOS and OSX'))
clues_themeless_11.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'FLATPANEL', number: 19, clue: 'Hardly a distinguishing monitor feature, these days'))
clues_themeless_11.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'HASTOSTAY', number: 20, clue: 'Eats off a tray, maybe'))
clues_themeless_11.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PLAYSWELLWITHOTHERS', number: 21, clue: 'What a gold star might mean'))
clues_themeless_11.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'WRONGNOTE', number: 22, clue: 'Accidental accident, maybe?'))
clues_themeless_11.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'DANL', number: 23, clue: 'Bush-pushing Boone, folksily'))
clues_themeless_11.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'PERV', number: 24, clue: 'Lech'))
clues_themeless_11.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'APSE', number: 25, clue: 'Recess at Sunday school?'))
clues_themeless_11.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'INTL', number: 26, clue: 'Like the WWW, as per its name'))
clues_themeless_11.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'NEIL', number: 27, clue: 'First name in small steps and big leaps'))
clues_themeless_11.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'TONE', number: 28, clue: 'Instrumentalist\'s concern'))
clues_themeless_11.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'LUKA', number: 29, clue: 'Second floor dweller in a Suzanne Vega hit'))
clues_themeless_11.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'NOAH', number: 30, clue: 'He got to the top of a mountain with a pair of pumas?'))
clues_themeless_11.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'HUFF', number: 31, clue: 'Use gas, in a way'))
clues_themeless_11.push(Entry.create(row: 5, col: 16, dir: 'Across', answer: 'RAAB', number: 32, clue: '___ Himself of MTV\'s "Viva La Bam"'))
clues_themeless_11.push(Entry.create(row: 5, col: 17, dir: 'Down', answer: 'AMBI', number: 33, clue: 'Prefix with sextrous'))
clues_themeless_11.push(Entry.create(row: 5, col: 18, dir: 'Down', answer: 'AMEN', number: 34, clue: 'Word sung over many a Bach cadence'))
clues_themeless_11.push(Entry.create(row: 5, col: 19, dir: 'Down', answer: 'BERG', number: 35, clue: 'Baffin bay danger'))
clues_themeless_11.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'POSSEOUT', number: 36, clue: '"Let\'s jet"'))
clues_themeless_11.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PIUS', number: 36, clue: 'Name before any of I - XII'))
clues_themeless_11.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OMNI', number: 37, clue: 'Universal opening?'))
clues_themeless_11.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'STEM', number: 38, clue: 'Flute stand'))
clues_themeless_11.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TINA', number: 39, clue: 'Musical partner of 69-Down'))
clues_themeless_11.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'NGUYEN', number: 40, clue: 'One of the ten most common surnames in the world'))
clues_themeless_11.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'YALL', number: 41, clue: '"Dolla dolla bill ___ ..."'))
clues_themeless_11.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ENYA', number: 42, clue: 'Irish singer born Eithne Ne Bhraonein'))
clues_themeless_11.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'NUTS', number: 43, clue: 'Apeshit'))
clues_themeless_11.push(Entry.create(row: 6, col: 17, dir: 'Across', answer: 'MME', number: 44, clue: 'Tussaud\'s title: Abbr.'))
clues_themeless_11.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'IMTHINKINGOFANUMBER', number: 45, clue: 'Start of an announcement to value seekers?'))
clues_themeless_11.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'NOWISER', number: 46, clue: 'Having not learned a thing'))
clues_themeless_11.push(Entry.create(row: 7, col: 16, dir: 'Down', answer: 'MYSPACE', number: 47, clue: 'Where Sean Kingston was discovered'))
clues_themeless_11.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'UNE', number: 48, clue: 'Article in a Parisian newspaper?'))
clues_themeless_11.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'LEANON', number: 49, clue: 'Use for support, as your sober friend'))
clues_themeless_11.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'FLYTYING', number: 50, clue: 'Working on one\'s lure'))
clues_themeless_11.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SIMS', number: 51, clue: 'Titular characters in a popular video game series'))
clues_themeless_11.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'SATIE', number: 52, clue: 'Composer Erik who wrote "(Dessicated embryo) of a Holothurian"'))
clues_themeless_11.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'AWOL', number: 53, clue: 'Status after an improper air base take-off?'))
clues_themeless_11.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'LIGER', number: 54, clue: 'Big cat hybrid drawn by Napoleon Dynamite (fun fact: it actually exists!)'))
clues_themeless_11.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'LASS', number: 55, clue: 'Two-piece wearer at a loch, maybe'))
clues_themeless_11.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ARAB', number: 56, clue: 'Many a resident of the world\'s tallest manmade structure'))
clues_themeless_11.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'REND', number: 57, clue: 'Tear asunder'))
clues_themeless_11.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ANTS', number: 58, clue: 'Farm critters'))
clues_themeless_11.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'BOAT', number: 59, clue: 'It can be missed or rocked'))
clues_themeless_11.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ITIS', number: 60, clue: '"For reals?"'))
clues_themeless_11.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SERA', number: 61, clue: 'They\'re administered to spies in movies to get them to tell the truth'))
clues_themeless_11.push(Entry.create(row: 10, col: 16, dir: 'Across', answer: 'PESO', number: 62, clue: 'Fitting name for a Mexican rent-a-car company?'))
clues_themeless_11.push(Entry.create(row: 10, col: 17, dir: 'Down', answer: 'ETAS', number: 63, clue: 'The heads of Hesiod and Herodotus?'))
clues_themeless_11.push(Entry.create(row: 10, col: 18, dir: 'Down', answer: 'SORT', number: 64, clue: 'Basic list operation, in Computer Science'))
clues_themeless_11.push(Entry.create(row: 10, col: 19, dir: 'Down', answer: 'ORTS', number: 65, clue: 'Table scraps resulting from a partial 64-Down of 64-Down'))
clues_themeless_11.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'WHITENOISEGENERATOR', number: 66, clue: 'Modern sleep aid'))
clues_themeless_11.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'WAS', number: 66, clue: 'Isn\'t any longer'))
clues_themeless_11.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HIP', number: 67, clue: '"I\'m so ___ I have trouble seeing over my pelvis" (Zaphod Beeblebrox)'))
clues_themeless_11.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'IRE', number: 68, clue: '"___ Works" (2007 Dillinger Escape Plan album full of angry songs)'))
clues_themeless_11.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'IKE', number: 69, clue: 'Musical partner of 39-Down'))
clues_themeless_11.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'NOT', number: 70, clue: '"Psyche!"'))
clues_themeless_11.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ETS', number: 71, clue: 'They may be little and green, initially'))
clues_themeless_11.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'RIN', number: 72, clue: 'What Tin Tin might follow?'))
clues_themeless_11.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AIRINTAKE', number: 73, clue: 'Where a spiral is often seen, on jet airliners'))
clues_themeless_11.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'EROTICART', number: 74, clue: 'Obscenity trial subject, perhaps'))
clues_themeless_11.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SPEEDSTER', number: 75, clue: 'Vintage Porsche (which wasn\'t all that fast, by today\'s standards)'))
clues_themeless_11.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'RATSNESTS', number: 76, clue: 'Bad wiring jobs, colloquially'))
Puzzle.create(title: 'Freestyle #11', grid: 'SUNSTROKE.ZOOTSUITS|FLATPANEL.HASTOSTAY|PLAYSWELLWITHOTHERS|DANL...PERV.APSE...|...INTL.NOAH...RAAB|POSSEOUT.NGUYEN.MME|IMTHINKINGOFANUMBER|UNE.LEANON.FLYTYING|SIMS...AWOL.LASS...|...ARAB.ITIS...PESO|WHITENOISEGENERATOR|AIRINTAKE.EROTICART|SPEEDSTER.RATSNESTS', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_themeless_11, puzzle_type: 'freestyle')
