clues_themeless_10 = Array.new
clues_themeless_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ATLAST', number: 1, clue: '"I thought that would never end"'))
clues_themeless_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ASP', number: 1, clue: 'Low Nile creature'))
clues_themeless_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TEL', number: 2, clue: 'Abbr. in an e-mail signature'))
clues_themeless_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LEA', number: 3, clue: 'Actress Michele of "Glee"'))
clues_themeless_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ATYA', number: 4, clue: '"Right back ___!" (poor response to "I love you")'))
clues_themeless_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SHITSANDGIGGLES', number: 5, clue: 'The hell of it'))
clues_themeless_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TENNER', number: 6, clue: 'Two fins'))
clues_themeless_10.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'GAS', number: 7, clue: 'It flows into a Rio'))
clues_themeless_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GIF', number: 7, clue: 'Still or animated file format'))
clues_themeless_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ANOS', number: 8, clue: 'Cinco de Mayo separators'))
clues_themeless_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SHOWWITHINASHOW', number: 9, clue: '"Squidward\'s House Party," e.g.'))
clues_themeless_10.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MAT', number: 10, clue: 'Tumbler site'))
clues_themeless_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MUSTNT', number: 10, clue: 'Prohibitive contraction'))
clues_themeless_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ASIANS', number: 11, clue: 'Most Muslims'))
clues_themeless_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TEETER', number: 12, clue: 'Be on the brink'))
clues_themeless_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'SEETHE', number: 13, clue: 'Stew'))
clues_themeless_10.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'INHOUSE', number: 14, clue: 'Like fewer and fewer helpdesks, these days'))
clues_themeless_10.push(Entry.create(row: 2, col: 11, dir: 'Down', answer: 'OTAY', number: 15, clue: 'Affirmation of "The Little Rascals"'))
clues_themeless_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PLAYINGFOOTSIE', number: 16, clue: 'Sexual activity between the legs?'))
clues_themeless_10.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'GOAT', number: 17, clue: 'One\'s may be gotten'))
clues_themeless_10.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'ATNO', number: 18, clue: 'It would be 85 and 102 for the two two-letter abbrs. in this answer'))
clues_themeless_10.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'SWATAT', number: 19, clue: 'Try to bring down, as a fly'))
clues_themeless_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'FAB', number: 20, clue: 'Opener for The Beatles?'))
clues_themeless_10.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'FDA', number: 20, clue: 'Pill testing org.'))
clues_themeless_10.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ARCH', number: 21, clue: 'Parabola of St. Louis'))
clues_themeless_10.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'BYTE', number: 22, clue: '1/16 of an IPv6 address'))
clues_themeless_10.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'SEAM', number: 23, clue: 'It might keep the legs together'))
clues_themeless_10.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'MINX', number: 24, clue: 'Coquette'))
clues_themeless_10.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'WYNNE', number: 25, clue: 'Arthur who created the crossword puzzle'))
clues_themeless_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'DRYMARTINI', number: 26, clue: 'Surprisingly, James Bond will not have one in the upcoming "Skyfall"'))
clues_themeless_10.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'MINE', number: 27, clue: 'Word repeated by the greedy seagulls in "Finding Nemo"'))
clues_themeless_10.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'NIC', number: 28, clue: 'Star Cage, for one, familiarly'))
clues_themeless_10.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'TSR', number: 29, clue: 'Game publishing co. founded by Gary Gygax'))
clues_themeless_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ACTIN', number: 30, clue: 'Be a part of, as a film'))
clues_themeless_10.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'NITS', number: 31, clue: '"It was founded by Gygax AND Don Kaye" and "There\'s a word mispelled in the clue for 31-Across," e.g.'))
clues_themeless_10.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'SOLI', number: 32, clue: 'Unassisted performances'))
clues_themeless_10.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'HENDRIXCHORD', number: 33, clue: 'E7#9, for one, in contemporary musical analysis'))
clues_themeless_10.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'RON', number: 34, clue: 'Jazz bassist Carter, who has played on over 2,500 records'))
clues_themeless_10.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'INDO', number: 35, clue: '___-European language'))
clues_themeless_10.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'RIDE', number: 36, clue: '"It\'s a Small World," e.g.'))
clues_themeless_10.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'DEON', number: 37, clue: '"Un Taxi Mauve" author Michel'))
clues_themeless_10.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'EGON', number: 38, clue: 'Mad scientist type Spangler of "Ghostbusters"'))
clues_themeless_10.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'ILIED', number: 39, clue: '"Scratch that..."'))
clues_themeless_10.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'DLO', number: 40, clue: '___ Brown of professional wrestling (whose first name sounds real hush-hush)'))
clues_themeless_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MVP', number: 41, clue: 'Star cager, for one, briefly'))
clues_themeless_10.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'MYSHIP', number: 41, clue: 'Weill-Gershwin work'))
clues_themeless_10.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'VOLUME', number: 42, clue: 'Issue at a library, or a collection of several issues at a library'))
clues_themeless_10.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'PUENTE', number: 43, clue: 'Bandleader featured in "The Mambo Kings" and "The Simpsons"'))
clues_themeless_10.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'INDIANIDOL', number: 44, clue: 'Televised contest with celebrity judges Anu Malik, Sunidhi Chauhan, and Salim Merchant'))
clues_themeless_10.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'IRAE', number: 45, clue: '"Of wrath," in Latin hymns'))
clues_themeless_10.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ACLASS', number: 46, clue: 'Mercedes-Benz hatchback (which is, ironically, an entry-level model)'))
clues_themeless_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'YOUNG', number: 47, clue: 'Calves, e.g.'))
clues_themeless_10.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'NIGH', number: 48, clue: 'Upon us'))
clues_themeless_10.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'ORCA', number: 49, clue: '"Frozen Planet" killer'))
clues_themeless_10.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'ENO', number: 50, clue: 'Composer whose ambient music helps when solving crosswords, and whose name helps when constructing them'))
clues_themeless_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SLEIGH', number: 51, clue: 'Cupid\'s burden'))
clues_themeless_10.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'HIRE', number: 52, clue: 'Welcome aboard'))
clues_themeless_10.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ALSO', number: 53, clue: '"But wait, there\'s more..."'))
clues_themeless_10.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'OONA', number: 54, clue: 'Last wife of Charlie Chaplin'))
clues_themeless_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HUNGLIKEAHORSE', number: 55, clue: 'Longfellow simile?'))
clues_themeless_10.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'KEW', number: 56, clue: 'Setting of London\'s Royal Botanic Gardens'))
clues_themeless_10.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'RIM', number: 57, clue: 'Where many Grand Canyon photos are taken from'))
clues_themeless_10.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'SCI', number: 58, clue: 'Comp. ___'))
clues_themeless_10.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'ESS', number: 59, clue: 'One of two in this answer'))
clues_themeless_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'IMTHERE', number: 60, clue: '"Wouldn\'t miss it for the world"'))
clues_themeless_10.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'SONICS', number: 61, clue: 'Thunder of the NBA, formerly and familiarly'))
clues_themeless_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'PEE', number: 62, clue: 'It\'s number one'))
clues_themeless_10.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SEW', number: 63, clue: 'Patch'))
clues_themeless_10.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'SWAMIS', number: 64, clue: 'Yoga instructors, before it was trendy'))
Puzzle.create(title: 'Freestyle #10', grid: 'ATLAST.GAS.MAT|SEETHE.INHOUSE|PLAYINGFOOTSIE|...ATNO.SWATAT|FAB.SEAM.WYNNE|DRYMARTINI.TSR|ACTIN..NITS...|.HENDRIXCHORD.|...EGON..ILIED|MVP.INDIANIDOL|YOUNG.ORCA.ENO|SLEIGH.ALSO...|HUNGLIKEAHORSE|IMTHERE.SONICS|PEE.SEW.SWAMIS', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_themeless_10, puzzle_type: 'freestyle')
