clues_xnerd_themeless_14 = Array.new
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ITSPAT', number: 1, clue: '1994 Julia Sweeney SNL spin-off that has recieved a rare 0% on rottentomatoes.com'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'IMS', number: 1, clue: 'Chats on ICQ with (yes, people still do that)'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TAP', number: 2, clue: 'With "out," end a hold'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SHO', number: 3, clue: '"The Real L Word" airer, briefly'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PANCAKE', number: 4, clue: 'Fast-starting disc, sometimes'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ALGORE', number: 5, clue: 'Harvard housemate of Tommy Lee Jones'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TIERED', number: 6, clue: 'Stacked'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'SCIS', number: 7, clue: 'Bio and chem'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SHERE', number: 7, clue: '___ Khan, Kipling\'s tiger'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CANIGONOW', number: 8, clue: '"Finished?"'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'INSEASON', number: 9, clue: 'Like farmer\'s market fare, often'))
clues_xnerd_themeless_14.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SEASLUG', number: 10, clue: 'Pelagic nonconchiferous gastropod'))
clues_xnerd_themeless_14.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MAHALIA', number: 11, clue: 'Singer Jackson who received the Grammy Lifetime Achievement Award in 1972'))
clues_xnerd_themeless_14.push(Entry.create(row: 2, col: 7, dir: 'Down', answer: 'ASOLO', number: 12, clue: '"Take ___!" (music to a show-off\'s ears during a jam session)'))
clues_xnerd_themeless_14.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'SHANE', number: 13, clue: 'Western classic named for its hero'))
clues_xnerd_themeless_14.push(Entry.create(row: 2, col: 9, dir: 'Down', answer: 'SMALT', number: 13, clue: '"Cobalt Blue" coloring agent'))
clues_xnerd_themeless_14.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SPONGES', number: 14, clue: 'Holey beings?'))
clues_xnerd_themeless_14.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'MENSA', number: 15, clue: 'Pornstar Asia Carrera is among their members'))
clues_xnerd_themeless_14.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'CORONARIES', number: 16, clue: 'What some people fear during scary movies, familiarly'))
clues_xnerd_themeless_14.push(Entry.create(row: 4, col: 8, dir: 'Down', answer: 'NYU', number: 17, clue: 'Greenwich sch.'))
clues_xnerd_themeless_14.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'BARELYLEGAL', number: 18, clue: 'Part of many a pornography pitch'))
clues_xnerd_themeless_14.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'BONGODRUM', number: 18, clue: 'Where a beat beats a beat'))
clues_xnerd_themeless_14.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'COKEDOUT', number: 19, clue: 'Like a ripped snorter, slangily'))
clues_xnerd_themeless_14.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'COLONIAL', number: 19, clue: 'Like coral'))
clues_xnerd_themeless_14.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'OSU', number: 20, clue: 'Famous UMich gridiron rival'))
clues_xnerd_themeless_14.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TONE', number: 21, clue: 'Concern for a lead guitarist'))
clues_xnerd_themeless_14.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'TABITHA', number: 21, clue: 'Author King, wife of Stephen'))
clues_xnerd_themeless_14.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'SNOG', number: 22, clue: 'Play tonsil hockey across the pond'))
clues_xnerd_themeless_14.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'STOSSEL', number: 22, clue: 'Regular "O\'Reilly Factor" guest and consumer advocate John'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ALG', number: 23, clue: 'Variable domain? (Abbr.)'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'INSISTON', number: 24, clue: 'Demand'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'IBEST', number: 24, clue: 'Start to be going, perhaps?'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'NOG', number: 25, clue: 'It begins with an "egg," often'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'SOAPS', number: 26, clue: 'Your great-aunt\'s stories, perhaps'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 8, dir: 'Down', answer: 'IMMIES', number: 27, clue: 'Aggie look-alikes'))
clues_xnerd_themeless_14.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'SPEECH', number: 28, clue: 'Shout heard over a din of cutlery on crystal'))
clues_xnerd_themeless_14.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BOOMBOOMPOW', number: 29, clue: 'Onomato-pea-ic hit of 2009 that will leave you with a black eye?'))
clues_xnerd_themeless_14.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'MIENS', number: 30, clue: 'Airs'))
clues_xnerd_themeless_14.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'INDIEGAMES', number: 31, clue: '"Minecraft" and "RuneScape," e.g.'))
clues_xnerd_themeless_14.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TIRES', number: 32, clue: 'Pickup circles?'))
clues_xnerd_themeless_14.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'PIESAFE', number: 33, clue: 'Ventilated kitchen cabinet'))
clues_xnerd_themeless_14.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'ADO', number: 34, clue: 'Production'))
clues_xnerd_themeless_14.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'FEM', number: 35, clue: '___bot (one of an army facing Austin Powers)'))
clues_xnerd_themeless_14.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'EDO', number: 36, clue: 'Where the Tokugawa shogunate ruled from'))
clues_xnerd_themeless_14.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HAUNT', number: 37, clue: 'Repossess one\'s house?'))
clues_xnerd_themeless_14.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'SECEDED', number: 38, clue: 'Made a declaration of independence'))
clues_xnerd_themeless_14.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ALMS', number: 39, clue: 'Poor reception?'))
clues_xnerd_themeless_14.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'SHLOMO', number: 40, clue: 'Hebrew name that means "God\'s peace," not "instant replay"'))
Puzzle.create(title: 'Freestyle #14', grid: 'ITSPAT...SCIS|MAHALIA.SHANE|SPONGES.MENSA|...CORONARIES|..BARELYLEGAL|.COKEDOUT.OSU|TONE.....SNOG|ALG.INSISTON.|BOOMBOOMPOW..|INDIEGAMES...|TIRES.PIESAFE|HAUNT.SECEDED|ALMS...SHLOMO', :constructors => Constructor.where(:name => 'Peter Broda'), :sources => Source.where(:name => 'The Cross Nerd'), publication_date: '', entries: clues_xnerd_themeless_14, puzzle_type: 'freestyle')
