clues_03_FOREVER_UNCLEAN = Array.new
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SATS', number: 1, clue: 'Exams with three 800-pt. sections'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SETUPS', number: 1, clue: 'Frame jobs'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALISON', number: 2, clue: 'Brie of "Community"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TOMATO', number: 3, clue: 'The Supreme Court ruled it a vegetable in 1893'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SIEGE', number: 4, clue: 'Prolonged attack on a castle'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'USBANK', number: 5, clue: 'Money lender that sounds like it\'s affiliated with the American government, but isn\'t'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'UMS', number: 5, clue: 'Speech stumbles'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SEQS', number: 6, clue: '"The Matrix Reloaded" and "Harry Potter and the Chamber of Secrets": Abbr.'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BLUE', number: 7, clue: 'A primary color'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ALAN', number: 8, clue: 'Portrayer of Severus'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'NORS', number: 9, clue: 'Neithers\' partners'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'KNEEDEEP', number: 10, clue: '#1 hit for Zac Brown Band and Jimmy Buffett'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'LOT', number: 11, clue: 'Parking ___'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LANDFILL', number: 11, clue: 'Odor emanator'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OLIVEOIL', number: 12, clue: 'Bread accompanier, in an Italian restaurant'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TSHIRTS', number: 13, clue: 'Jason Sadler wears them for a living'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ELOI', number: 14, clue: 'Curly-haired creatures in "The Time Machine"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'MELLON', number: 15, clue: 'The M in CMU'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ALS', number: 16, clue: 'Green and Jarreau of soul'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TIMESSQUARE', number: 17, clue: '"Dick Clark\'s New Year\'s Rockin\' Eve" locale'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'SENT', number: 18, clue: 'Shot off, as an email'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'NIH', number: 19, clue: 'Gov\'t research org. headquartered in 36-Down'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'USAGE', number: 20, clue: 'Grammar concern'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'SENSE', number: 21, clue: 'Taste or smell'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'DVI', number: 22, clue: '506, in Roman numerals'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'POTENT', number: 23, clue: '___ Potables (alliterative "Celebrity Jeopardy" category)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'TOMS', number: 24, clue: 'Sawyer and Marvolo Riddle of literature'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'DEFER', number: 25, clue: 'Choose to choose later'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ELLO', number: 26, clue: 'Greeting to \'enry'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SNO', number: 27, clue: 'Commercial prefix with Cat or Caps'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'TOGAS', number: 28, clue: 'Sheets, at a frat party'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'GETTO', number: 29, clue: 'Reach'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'AARON', number: 30, clue: 'QB Rodgers who does the Discount Double Check'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'STATE', number: 31, clue: '36-Down is one'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ELIOT', number: 32, clue: 'T.S. who wrote "I should have been a pair of ragged claws/Scuttling across the floors of silent seas"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'MEAT', number: 33, clue: 'Dress material for Lady Gaga'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ELLIS', number: 34, clue: '___ Island (immigration site)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'AMESSTRAWPOLL', number: 35, clue: 'Iowa vote won by Michele Bachmann in 2011'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'ACTSUPON', number: 35, clue: 'Heeds, as advice'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'MARYLAND', number: 36, clue: 'DMV: D.C., ___, Virginia'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'ELIN', number: 37, clue: 'Tiger\'s ex'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SPACEJAM', number: 38, clue: '1996 Michael Jordan/Bugs Bunny movie'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'WELL', number: 39, clue: '"Wishing ___" (Terence Trent D\'Arby song)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SCALP', number: 40, clue: 'Resell outside a stadium'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SANJOSE', number: 40, clue: 'Where Sharks skate'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'TOTE', number: 41, clue: 'Bag used for carrying'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ATRIA', number: 42, clue: 'Central courts'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'ONELB', number: 43, clue: 'A fourteenth of a stone, for short'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'BUMP', number: 44, clue: '___ uglies'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'LAS', number: 45, clue: '___ Vegas Locomotives (UFL team)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'LETDIE', number: 45, clue: 'Partner of live, in a Roger Moore movie'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'AIRERS', number: 46, clue: 'Broadcasters'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'SNORES', number: 47, clue: 'Annoys the crap out of one\'s roommate at night, perhaps'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NSYNC', number: 48, clue: '"Bye Bye Bye" boy band'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'LUREIN', number: 49, clue: 'Entice evilly'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'REALM', number: 50, clue: 'Area'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'JUL', number: 51, clue: 'Aug. preceder'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'ECOLI', number: 52, clue: 'Cause of a beef patty recall'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'CAGE', number: 53, clue: 'Nicolas of "The Wicker Man"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'OMAN', number: 54, clue: 'Neighbor of Yemen'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'LEST', number: 55, clue: '"___ we forget..."'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'ISSO', number: 56, clue: '"That ___ funny!"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'METRO', number: 57, clue: 'Prefix with sexual, as of 1994'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OPA', number: 58, clue: '___-locka, Florida'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'JAMESSPADER', number: 59, clue: 'Actor whose "The Office" character says "There is only sex. Everything is sex."'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'SIS', number: 60, clue: 'Bro\'s sib'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SON', number: 61, clue: '"C\'mon, ___!" (Ed Lover exclamation)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'AGASSI', number: 62, clue: 'Andre on clay'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'LIRE', number: 63, clue: 'Former Italian currency'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'END', number: 64, clue: '"Every new beginning comes from some other beginning\'s ___" (Semisonic lyric)'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'MENTOS', number: 65, clue: '"The Freshmaker"'))
clues_03_FOREVER_UNCLEAN.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'MESS', number: 66, clue: 'Condition for many a dorm room, and what\'s hidden inside this puzzle\'s three longest answers'))
Puzzle.create(title: 'FOREVER UNCLEAN!', grid: 'SATS.USBANK.LOT|ELOI.MELLON.ALS|TIMESSQUARE.NIH|USAGE.SENSE.DVI|POTENT....DEFER|SNO.TOGAS.ELIOT|.....MEAT.ELLIS|.AMESSTRAWPOLL.|SCALP.TOTE.....|ATRIA.ONELB.LAS|NSYNC....LUREIN|JUL.ECOLI.METRO|OPA.JAMESSPADER|SON.AGASSI.LIRE|END.MENTOS.MESS', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:display_name => 'Anoa Place'), publication_date: '2012-7-7', entries: clues_03_FOREVER_UNCLEAN, puzzle_type: 'themed')
