clues_12_SHIRTS_VS_SKINS = Array.new
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BASIC', number: 1, clue: 'Unlike 19-Across'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BICS', number: 1, clue: 'Some pens'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ACHE', number: 2, clue: 'Feel sore'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SOOT', number: 3, clue: '"...tarnish\'d with ashes and ___..."'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ISPS', number: 4, clue: 'They give you connections: Abbr.'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'CASTLE', number: 5, clue: 'Nathan Fillion dramedy'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'MAYS', number: 6, clue: 'Fielder Willie or pitcher Billy'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MXI', number: 6, clue: '1011, in Roman numerals'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ABCTV', number: 7, clue: 'Network that airs 5-Down'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'YOKO', number: 8, clue: 'Ono, it\'s her!'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SXSW', number: 9, clue: 'Event held in Austin, TX'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SLAV', number: 10, clue: 'Montenegrin, e.g.'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SPARTA', number: 10, clue: 'Battle of Thermopylae side'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LOCUS', number: 11, clue: 'Center of power'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ALICE', number: 12, clue: 'Wonderland character'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'VODKA', number: 13, clue: 'Burnett\'s, e.g.'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ICOSA', number: 14, clue: 'Prefix meaning "twenty"'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'XBOX', number: 15, clue: '"Madden NFL 09" was the last game released for it'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'POLO', number: 16, clue: 'Izod competitor'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CHOPSTICKS', number: 17, clue: 'Two-digit number*'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'TOIL', number: 18, clue: '"Double, double, ___ and trouble..."'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ACID', number: 19, clue: 'Substance with a pH under 7'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SETSTO', number: 20, clue: 'Fixes at (stun), as a phaser'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'TOWTRUCK', number: 21, clue: 'Vehicle with a lot of pull*'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'TAMAR', number: 22, clue: 'Toni Braxton\'s youngest sister'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'LIEV', number: 23, clue: 'Schreiber of "X-Men Origins: Wolverine"'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'ESKIMO', number: 24, clue: 'Language group that has about as many words for snow as English does'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ATSEA', number: 25, clue: 'On the open water'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'DAMSELS', number: 26, clue: 'They\'re often distressed in fairy tales'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'DART', number: 26, clue: 'Pub projectile'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AWES', number: 27, clue: 'Makes jaws drop'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'MOCK', number: 28, clue: 'Ersatz'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'SLO', number: 29, clue: '___-pitch softball'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'ZIMA', number: 30, clue: 'Coors alcopop whose name means "winter"'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ZAGREB', number: 30, clue: 'Croatian capital'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ILA', number: 31, clue: 'Dockworkers\' grp. (or a backwards boxing great)'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AWOL', number: 32, clue: 'Way off base?'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'KOALA', number: 33, clue: 'Cuddly marsupial'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ONE', number: 34, clue: '"The ___" (2001 Jet Li film)'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'BOB', number: 35, clue: '"Airplanes" rapper'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'BIDS', number: 35, clue: 'Frat invitations'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'OSLO', number: 36, clue: 'City for Edvard Munch and Henrik Ibsen'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'BTEN', number: 37, clue: 'Alphanumeric bomber aircraft'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RECORDINGARTIST', number: 38, clue: 'Prince, e.g.*'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'REPEL', number: 39, clue: 'Stave off'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'DLS', number: 40, clue: 'Comedian Hughley et al.'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'TIA', number: 41, clue: 'Madre\'s hermana'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TSK', number: 42, clue: 'Syllable of reproach'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ELMER', number: 43, clue: 'Glue mascot and husband of Elsie'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'IDLE', number: 44, clue: 'Sit in traffic'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'IPSO', number: 45, clue: '___ facto'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'IBEAMS', number: 45, clue: 'Letter-shaped girders'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ESIASON', number: 46, clue: 'Boomer on CBS Sports'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'SITU', number: 47, clue: 'In ___: untouched'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ISOPOD', number: 48, clue: 'Crustacean with similar-sized legs'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'GLOBE', number: 49, clue: '___ Theatre, stomping ground for groundlings'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'GLEAM', number: 49, clue: 'Sparkle'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'LITHE', number: 50, clue: 'Like a gymnast'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'OFTEN', number: 51, clue: 'Daily, maybe'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'RBIS', number: 52, clue: 'Stat for Stan the Man'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'RECON', number: 52, clue: 'Intel-gathering mission'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LIFELINE', number: 53, clue: 'Fifty-Fifty or Ask The Audience, in "Who Wants to Be a Millionaire"*'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'IPAD', number: 54, clue: 'Apple product codenamed K48'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'NILE', number: 55, clue: 'River through South Sudan'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'TOAMAN', number: 56, clue: 'Unanimously'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'AGAR', number: 57, clue: 'Gel used in making ice cream'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'MAKO', number: 58, clue: 'Deadly shark'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'AMEN', number: 59, clue: 'Church cry'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'NENE', number: 60, clue: 'Hawaiian bird, or a Brazilian NBAer'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ETTA', number: 61, clue: '"I\'d Rather Go Blind" singer James'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'PICKUPGAME', number: 62, clue: 'Court appointment... or what\'s being played by the ends of the starred answers?'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'KEY', number: 63, clue: 'Peele\'s comedy partner'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AHEM', number: 64, clue: '"I HAVE SOMETHING STUCK IN MY THROAT! THAT MEANS YOU SHOULD GIVE ME YOUR UNDIVIDED ATTENTION!"'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ALOE', number: 65, clue: '___ vera'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'OAKEN', number: 66, clue: '"The ___ Throne" (1993 book with anthropomorphic squirrels)'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MENS', number: 67, clue: 'Room in a restaurant'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DENY', number: 68, clue: 'Put to rest, as allegations'))
clues_12_SHIRTS_VS_SKINS.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'DRONE', number: 69, clue: 'Worker bee'))
Puzzle.create(title: 'SHIRTS VS. SKINS', grid: 'BASIC.MAYS.SLAV|ICOSA.XBOX.POLO|CHOPSTICKS.ACID|SETSTO.TOWTRUCK|....LIEV..ATSEA|DAMSELS.ZIMA...|AWOL..KOALA.BOB|RECORDINGARTIST|TSK.ELMER..IDLE|...IPSO.ESIASON|GLOBE..RBIS....|LIFELINE.TOAMAN|ETTA.PICKUPGAME|AHEM.ALOE.OAKEN|MENS.DENY.DRONE', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:display_name => 'Anoa Place'), publication_date: '2012-7-7', entries: clues_12_SHIRTS_VS_SKINS, puzzle_type: 'themed')
