clues_13_TAKING_STOC = Array.new
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JEWEL', number: 1, clue: 'Super Bowl XXXII lip-syncer'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JAPAN', number: 1, clue: 'Host of the 1964 Summer Olympics'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EMOTES', number: 2, clue: 'Acts one\'s heart out'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'WARHOL', number: 3, clue: '"Campbell\'s Soup Cans" painter'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ETTE', number: 4, clue: 'Ending with cigar or kitchen'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'LIONSCHAIR', number: 5, clue: 'Throne for the king of the jungle?'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CHICK', number: 6, clue: 'Girl, slangily'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CSI', number: 6, clue: 'Franchise based in Las Vegas, Miami, and New York'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HENRI', number: 7, clue: '"Woman with a Hat" painter Matisse'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'INTACT', number: 8, clue: 'Unbroken'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'COWPEA', number: 9, clue: 'Zoologically named plant'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'KROC', number: 10, clue: 'Ray who started as a milkshake salesman'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BBC', number: 11, clue: '"Doctor Who" airer'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BERENGER', number: 11, clue: 'Tom of "Inception"'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BLOATERS', number: 12, clue: 'Cold-smoked herrings'))
clues_13_TAKING_STOC.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CONTORT', number: 13, clue: 'Twist one\'s arm?'))
clues_13_TAKING_STOC.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMATI', number: 14, clue: 'Violin played by Thomas Bowes'))
clues_13_TAKING_STOC.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'SENOR', number: 15, clue: 'Mexican mister'))
clues_13_TAKING_STOC.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ELO', number: 16, clue: '"10538 Overture" band'))
clues_13_TAKING_STOC.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PORTO', number: 17, clue: '___-Novo (Beninese capital)'))
clues_13_TAKING_STOC.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'INTWO', number: 18, clue: 'Halved'))
clues_13_TAKING_STOC.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'RON', number: 19, clue: 'Swanson who said "Birthdays were invented by Hallmark to sell cards"'))
clues_13_TAKING_STOC.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ATHENA', number: 20, clue: 'Source of Zeus\'s headache'))
clues_13_TAKING_STOC.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'ALEAP', number: 21, clue: 'Take ___ of faith'))
clues_13_TAKING_STOC.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'RAPCHEAT', number: 22, clue: 'One plagiarizing a freestyle?'))
clues_13_TAKING_STOC.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'HEAVEHO', number: 23, clue: 'Ejection'))
clues_13_TAKING_STOC.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NEO', number: 24, clue: 'Nazi leader?'))
clues_13_TAKING_STOC.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'SLUICE', number: 25, clue: 'Water conduit'))
clues_13_TAKING_STOC.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'USOC', number: 26, clue: '"Don\'t Be An Asterisk" org.'))
clues_13_TAKING_STOC.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'ENTO', number: 27, clue: 'Inner: Prefix'))
clues_13_TAKING_STOC.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'SLICES', number: 28, clue: 'Pizza pie portions'))
clues_13_TAKING_STOC.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'ICELAND', number: 29, clue: 'Its flag colors stand for sea, snow, and volcanoes'))
clues_13_TAKING_STOC.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'TANAGER', number: 30, clue: 'Bird that\'s often scarlet'))
clues_13_TAKING_STOC.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'NORTHCHORE', number: 31, clue: 'KP duty, for Ollie?'))
clues_13_TAKING_STOC.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'CHAOS', number: 32, clue: 'Disarray'))
clues_13_TAKING_STOC.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'SHA', number: 33, clue: 'Nonsense word followed by "na na" or "la la"'))
clues_13_TAKING_STOC.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'OVERT', number: 34, clue: 'As plain as the nose on one\'s face'))
clues_13_TAKING_STOC.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'CHEAPCHEERERS', number: 35, clue: 'Fans who refuse to shell out for a ten dollar beer?'))
clues_13_TAKING_STOC.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'CHESHIRE', number: 35, clue: 'Grinning cat of literature'))
clues_13_TAKING_STOC.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'HAWAIIAN', number: 36, clue: 'Punch type'))
clues_13_TAKING_STOC.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'ERIS', number: 37, clue: 'The "tenth" of our eight planets'))
clues_13_TAKING_STOC.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'EINES', number: 38, clue: 'German indefinite article'))
clues_13_TAKING_STOC.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'GHALI', number: 39, clue: 'Boutros Boutros-___'))
clues_13_TAKING_STOC.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'GRACING', number: 39, clue: 'Favoring, as with one\'s presence'))
clues_13_TAKING_STOC.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ARITH', number: 40, clue: 'Type of mean or series, for short'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'REWARDS', number: 41, clue: 'Bounty hunters\' payoffs'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'DIVING', number: 42, clue: 'Jumping into the water'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'SNIPPY', number: 43, clue: 'Short-tempered'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'INHOME', number: 44, clue: 'Like some care'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'MOUSSE', number: 45, clue: 'Chocolate dessert'))
clues_13_TAKING_STOC.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'EDGEIN', number: 46, clue: 'Enter shyly'))
clues_13_TAKING_STOC.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ASAN', number: 47, clue: '___ alternative (instead)'))
clues_13_TAKING_STOC.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'INASEC', number: 48, clue: '"Would you be patient?!"'))
clues_13_TAKING_STOC.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ALLUP', number: 49, clue: '___ in one\'s grill'))
clues_13_TAKING_STOC.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'ODA', number: 50, clue: '___ Mae (Oscar-winning role for Whoopi)'))
clues_13_TAKING_STOC.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'ASSNS', number: 51, clue: 'Orgs.'))
clues_13_TAKING_STOC.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CHIDEVIL', number: 52, clue: 'Imp that messes with your feng shui?'))
clues_13_TAKING_STOC.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'EDIE', number: 53, clue: 'Falco who guested on "30 Rock"'))
clues_13_TAKING_STOC.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'SHRUGS', number: 54, clue: 'Shows Kanye-esque indifference'))
clues_13_TAKING_STOC.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'RAID', number: 55, clue: 'Ransack, as one\'s fridge'))
clues_13_TAKING_STOC.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'III', number: 56, clue: 'Robert Griffin ___'))
clues_13_TAKING_STOC.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'DIPLO', number: 57, clue: 'Major Lazer producer'))
clues_13_TAKING_STOC.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'OTT', number: 58, clue: 'He shares the record for consecutive walks drawn'))
clues_13_TAKING_STOC.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'OASES', number: 59, clue: 'Desert stops'))
clues_13_TAKING_STOC.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NRA', number: 60, clue: 'Org. with an eagle in its logo'))
clues_13_TAKING_STOC.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'INPUT', number: 61, clue: 'Say'))
clues_13_TAKING_STOC.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'RISIN', number: 62, clue: 'Mr. Mojo ___ (Jim Morrison\'s anagrammatic nickname)'))
clues_13_TAKING_STOC.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'GEN', number: 63, clue: 'X or Y'))
clues_13_TAKING_STOC.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'EGYPT', number: 64, clue: 'Pyramid schemers of yore?'))
clues_13_TAKING_STOC.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'EDENS', number: 65, clue: 'Utopias'))
Puzzle.create(title: 'TAKING STOC', grid: 'JEWEL.CHICK.BBC|AMATI.SENOR.ELO|PORTO.INTWO.RON|ATHENA.RAPCHEAT|NEO.SLUICE.ENTO|.SLICES.TANAGER|...CHAOS..OVERT|.CHEAPCHEERERS.|GHALI..ARITH...|REWARDS.INHOME.|ASAN.INASEC.ODA|CHIDEVIL.SHRUGS|III.DIPLO.OASES|NRA.INPUT.RISIN|GEN.EGYPT.EDENS', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Anoa Place'), publication_date: '', entries: clues_13_TAKING_STOC, puzzle_type: 'themed')