clues_15_MAKE_A_WISH = Array.new
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TYPE', number: 1, clue: 'Bang away, as on a keyboard'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'THEFABF', number: 1, clue: 'John, Paul, George, and Ringo'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'YALELAW', number: 2, clue: 'Alma mater for three current Supreme Court Justices'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PRORATA', number: 3, clue: 'In proportion, in Latin'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EMIRS', number: 4, clue: 'Mideast rulers'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ARTRK', number: 5, clue: 'Louvre display'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ADMS', number: 5, clue: 'Ackbar and others, in ugly military abbrevs'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RIA', number: 6, clue: 'Coastel inlet with a treelike outline'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TCHAINZ', number: 7, clue: '"Spend It" rapper who wears double the normal amount of neckwear'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'READSTO', number: 8, clue: 'Tells a bedtime story, perhaps'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'KYLIE', number: 9, clue: '"Can\'t Get You Out of My Head" singer Minogue'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SKIM', number: 10, clue: 'Alternative to whole, in the dairy aisle'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SML', number: 10, clue: 'Lge.\'s opposite, in shirt sizing'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'KAISHEK', number: 11, clue: 'Chiang ___, former Kuomintang leader'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'IMALONE', number: 12, clue: '"We\'ll have the place all to ourselves!"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MAROONF', number: 13, clue: '"Payphone" band'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HARM', number: 14, clue: 'Primum non nocere: First, do no ___'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'DICEY', number: 15, clue: 'Not without risk'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'MAMA', number: 16, clue: 'Papa\'s partner'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ELOI', number: 17, clue: 'Prey of the Morlocks'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'MAHAL', number: 18, clue: 'Bluesician Taj'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'LIAR', number: 19, clue: 'One whose pants are on fire, so to speak'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'FERRIS', number: 20, clue: '"___ Bueller\'s Day Off"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ITS', number: 21, clue: 'Part of FWIW'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'ADIT', number: 22, clue: 'Entrance of mine?'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'TRUTH', number: 23, clue: 'It shall set you free'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'SLO', number: 24, clue: '___-mo replay'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ALAST', number: 25, clue: 'As ___ resort'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'MISER', number: 26, clue: 'Scrooge McDuck, for one'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'MAR', number: 26, clue: 'Apr. preceder'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'HOO', number: 27, clue: '"Oh, boo ___!" ("Get over yourself!")'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BAT', number: 28, clue: 'Fear for a young Bruce Wayne'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SLANT', number: 29, clue: 'Feature of italics'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'LOS', number: 30, clue: 'Word before Angeles or Alamos'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'UPENN', number: 31, clue: 'School founded by Benjamin Franklin, familiarly'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'PAIR', number: 32, clue: 'It beats a high card'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'FWAY', number: 33, clue: 'Intersection that looks like a plus on street signs'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'YEAH', number: 34, clue: 'Affirmatively titled Usher song'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ORZO', number: 35, clue: 'Rice-like pasta'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'TAKEF', number: 36, clue: 'Dave Brubeck jazz standard, or a Hershey candy bar'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'EPS', number: 37, clue: 'Records shorter than 25 mins.'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'PROOF', number: 38, clue: 'It may end with "QED"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'PHI', number: 39, clue: 'The Eagles or the Sixers, on scoreboards'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'PSY', number: 39, clue: 'Prefix with beam or wave, for a telekinetic Pok&#233;mon'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LEHAR', number: 40, clue: '"Dein ist mein ganzes Herz" composer Franz'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'LIKEAGO', number: 40, clue: 'Far East Movement song with the line "Let me see you fly"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'EDIBLES', number: 41, clue: 'Pot brownies and weed cookies'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'HAMBONE', number: 42, clue: 'Meaty-sounding dance performed in lieu of rhythmic instruments'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'EONS', number: 43, clue: 'Eras upon eras'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'EXAMINE', number: 43, clue: 'Turn a critical eye towards'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ORLANDO', number: 44, clue: 'Where the Magic play'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'NAS', number: 45, clue: '"Street Dreams" rapper'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'REFS', number: 46, clue: 'Touching them gets you a technical foul, in b-ball'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'ESTRADA', number: 47, clue: 'Erik of "CHiPs"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'FIEDLER', number: 48, clue: 'Quarterback Jay whose name is a letter swap away from being a baseball position'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'STRIKET', number: 49, clue: 'Words heard while being fanned?'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'IDAHO', number: 50, clue: 'Its slogan is "Great Potatoes. Tasty Destinations."'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'XRAYS', number: 51, clue: 'Radiation happened upon by Roentgen'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'SEE', number: 52, clue: '"What did I say?!"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'SIT', number: 53, clue: 'Get behind on something?'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'KIM', number: 54, clue: '"Kourtney and ___ Take New York"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'ORALS', number: 55, clue: 'Pre-Ph.D. ordeals'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'REBEL', number: 56, clue: 'Stick it to The Man'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'ENTER', number: 57, clue: 'It\'s next to Page Down on my keyboard, inexplicably'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'NOTIP', number: 58, clue: 'What a waiter gets from a 26-Across'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EBB', number: 59, clue: 'Opposite of flow'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'FEMA', number: 60, clue: '"Brownie, you\'re doing a heck of a job" org.'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'GEORDI', number: 61, clue: 'LeVar\'s "Star Trek: The Next Generation" role'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'GERE', number: 61, clue: 'Richard of "Pretty Woman"'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ALOT', number: 62, clue: 'Often'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'TEC', number: 63, clue: 'Gumshoe, slangily'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'BINGE', number: 64, clue: 'Consume too much alcohol/food/reality television'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'GEN', number: 65, clue: '___ Xer'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'TALK', number: 66, clue: 'Squeal'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GENE', number: 67, clue: 'Wilder or Simmons'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ENDER', number: 68, clue: 'Orson Scott Card character who\'s got Game?'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'IDEE', number: 69, clue: 'French notion'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'OSEC', number: 70, clue: '"Gimme a moment..."'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'LEONE', number: 71, clue: 'Sierra ___'))
clues_15_MAKE_A_WISH.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'PART', number: 72, clue: 'Type of hole on which a double eagle is impossible'))
Puzzle.create(title: 'MAKE A WISH', grid: 'TYPE.ARTRK.SKIM|HARM.DICEY.MAMA|ELOI.MAHAL.LIAR|FERRIS.ADIT.SLO|ALAST.MISER.HOO|BAT.SLANT.UPENN|FWAY.ORZO.TAKEF|...EPS...PHI...|LEHAR.EONS.REFS|IDAHO.XRAYS.SIT|KIM.ORALS.ENTER|EBB.FEMA.GEORDI|ALOT.BINGE.TALK|GENE.ENDER.IDEE|OSEC.LEONE.PART', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:display_name => 'Anoa Place'), publication_date: '2012-7-7', entries: clues_15_MAKE_A_WISH, puzzle_type: 'themed')
