clues_21x = Array.new
clues_21x.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PARA', number: 1, clue: 'Military leader?'))
clues_21x.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PPL', number: 1, clue: 'Folks, in txtspk'))
clues_21x.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARE', number: 2, clue: '"___ You Gonna Go My Way"'))
clues_21x.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RIO', number: 3, clue: 'Where Felix Baumgartner BASE jumped from the hand of the "Christ the Redeemer" statue'))
clues_21x.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AMNIOS', number: 4, clue: 'Prenatal procedures, pithily'))
clues_21x.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'PROOF', number: 5, clue: 'Number of yards?'))
clues_21x.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'PDAS', number: 5, clue: 'BlackBerry and Treo, for two, for short'))
clues_21x.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RON', number: 6, clue: '"Arrested Development" producer/director/character Howard'))
clues_21x.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ONELAP', number: 7, clue: 'A quarter mile, perhaps'))
clues_21x.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ONTARGET', number: 8, clue: 'Accurate'))
clues_21x.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'FATWA', number: 9, clue: 'Mufti\'s judgment'))
clues_21x.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BOMBBLAST', number: 10, clue: 'Certain explosion'))
clues_21x.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BAHA', number: 10, clue: '___ Men ("Who Let the Dogs Out?" group)'))
clues_21x.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OVERCOAT', number: 11, clue: 'Winter wear'))
clues_21x.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MARTINIS', number: 12, clue: 'Bond booze'))
clues_21x.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'BIASTIRE', number: 13, clue: 'Radial alternative'))
clues_21x.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'BLK', number: 14, clue: 'Not wht.'))
clues_21x.push(Entry.create(row: 1, col: 18, dir: 'Down', answer: 'LAL', number: 15, clue: 'Scoreboard letters for Dwight Howard, until recently'))
clues_21x.push(Entry.create(row: 1, col: 19, dir: 'Down', answer: 'ABIES', number: 16, clue: '"___ Irish Rose"'))
clues_21x.push(Entry.create(row: 1, col: 20, dir: 'Down', answer: 'SLOPE', number: 17, clue: 'Rise over run, in Algebra class'))
clues_21x.push(Entry.create(row: 1, col: 21, dir: 'Down', answer: 'TENTS', number: 18, clue: 'Pup places?'))
clues_21x.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PRIMADONNAS', number: 19, clue: 'Divas'))
clues_21x.push(Entry.create(row: 2, col: 5, dir: 'Down', answer: 'APOSTLE', number: 20, clue: 'Bartholomew, e.g.'))
clues_21x.push(Entry.create(row: 2, col: 11, dir: 'Down', answer: 'SANFRANCISCOBAYAREA', number: 21, clue: 'Warrior\'s realm?'))
clues_21x.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'AVAILABLE', number: 22, clue: 'Single and ready to mingle'))
clues_21x.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LEONPANETTA', number: 23, clue: 'Chuck Hagel\'s predecessor'))
clues_21x.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'HERAKLION', number: 24, clue: 'Cretan capital, whose name derives from that of a hero in Greek myth'))
clues_21x.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'IOS', number: 25, clue: '"Temple Run" runner?'))
clues_21x.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'LAWNDARTS', number: 26, clue: 'Game with points'))
clues_21x.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'DEA', number: 27, clue: 'Raidmakers?: Abbr.'))
clues_21x.push(Entry.create(row: 4, col: 19, dir: 'Across', answer: 'EPT', number: 28, clue: 'One way to check "the oven," for short'))
clues_21x.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SILOS', number: 29, clue: 'Grain stations'))
clues_21x.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'SAW', number: 29, clue: 'Perform a certain illusion'))
clues_21x.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'IVE', number: 30, clue: '"___ made a huge mistake"'))
clues_21x.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'LADOLCEVITA', number: 31, clue: 'First movie reviewed by Roger Ebert'))
clues_21x.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'CARAFE', number: 32, clue: 'Wine container'))
clues_21x.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'CMS', number: 32, clue: 'Ruler lgths.'))
clues_21x.push(Entry.create(row: 5, col: 14, dir: 'Across', answer: 'CITRUSES', number: 33, clue: 'Lemon, orange, etc.'))
clues_21x.push(Entry.create(row: 5, col: 17, dir: 'Down', answer: 'ROSA', number: 34, clue: 'Parks in Statuary Hall'))
clues_21x.push(Entry.create(row: 5, col: 18, dir: 'Down', answer: 'UNA', number: 35, clue: 'Article written by Gabriel Garc&#237;a M&#225;rquez?'))
clues_21x.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'AVAST', number: 36, clue: 'Stop in the middle of the ocean?'))
clues_21x.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'MPG', number: 37, clue: '43-Across concern'))
clues_21x.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'RAWONION', number: 38, clue: 'Topping on a half-smoke'))
clues_21x.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'WHATAMI', number: 39, clue: 'Question of identity'))
clues_21x.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'WED', number: 40, clue: 'One'))
clues_21x.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'LPS', number: 41, clue: 'Groove-y records: Abbr.'))
clues_21x.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'PSALMS', number: 42, clue: 'Job follower'))
clues_21x.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'EPA', number: 43, clue: 'Green party: Abbr.'))
clues_21x.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'PIEDISH', number: 44, clue: 'Cobbler\'s container'))
clues_21x.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'HAIRSALON', number: 45, clue: 'Grounds for some big budget cuts?'))
clues_21x.push(Entry.create(row: 7, col: 19, dir: 'Down', answer: 'LISASIMPSON', number: 46, clue: 'She helped popularize the word "meh"'))
clues_21x.push(Entry.create(row: 7, col: 20, dir: 'Down', answer: 'OPENTOE', number: 47, clue: 'Like thongs'))
clues_21x.push(Entry.create(row: 7, col: 21, dir: 'Down', answer: 'NOTAONE', number: 48, clue: 'Goose egg'))
clues_21x.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'ORES', number: 49, clue: 'Boolean-sounding resources'))
clues_21x.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'ROYCES', number: 50, clue: 'Rolls-___ (fancy whips)'))
clues_21x.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'TIN', number: 51, clue: 'Like some gods and soldiers'))
clues_21x.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ATSEA', number: 52, clue: 'Under maritime law'))
clues_21x.push(Entry.create(row: 8, col: 19, dir: 'Across', answer: 'IPO', number: 53, clue: '2012 event for FB'))
clues_21x.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MILO', number: 54, clue: '"The Adventures of ___ and Otis"'))
clues_21x.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'METRICS', number: 54, clue: 'Yardsticks, ironically'))
clues_21x.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'INHERIT', number: 55, clue: 'Come into'))
clues_21x.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ADS', number: 56, clue: 'Rep placements'))
clues_21x.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'DOME', number: 57, clue: 'Head'))
clues_21x.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SPUD', number: 58, clue: 'Tater'))
clues_21x.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'ECHT', number: 59, clue: 'Authentic, to Angela Merkel'))
clues_21x.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'HATREDS', number: 60, clue: 'Odiums'))
clues_21x.push(Entry.create(row: 9, col: 18, dir: 'Across', answer: 'ASET', number: 61, clue: 'Play ___ (make a court appearance?)'))
clues_21x.push(Entry.create(row: 9, col: 18, dir: 'Down', answer: 'ACETIC', number: 61, clue: '___ acid'))
clues_21x.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ENCYCLOPEDIAAMERICANA', number: 62, clue: 'States facts?'))
clues_21x.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'COR', number: 63, clue: '"___ blimey!"'))
clues_21x.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ENISLED', number: 64, clue: 'Marooned'))
clues_21x.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'MAMA', number: 65, clue: 'Papa partner'))
clues_21x.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ENIS', number: 66, clue: 'Oft-ridden Bear back Curtis (or, backwards, ___ wave)'))
clues_21x.push(Entry.create(row: 10, col: 16, dir: 'Down', answer: 'RINGUP', number: 67, clue: 'Record, as a payment'))
clues_21x.push(Entry.create(row: 10, col: 17, dir: 'Down', answer: 'IFA', number: 68, clue: '"___ tree falls..."'))
clues_21x.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'THECOMMUNISTMANIFESTO', number: 69, clue: 'Class work?'))
clues_21x.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'REVERSEDISCRIMINATION', number: 70, clue: 'Pro-few\'s-ness?'))
clues_21x.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IRIS', number: 71, clue: 'Goo Goo Dolls song on the "City of Angels" soundtrack'))
clues_21x.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'SHOE', number: 72, clue: 'Pen for little piggies?'))
clues_21x.push(Entry.create(row: 13, col: 14, dir: 'Across', answer: 'ASG', number: 73, clue: 'Annual MLB, NBA, or NHL exhibition (the NFL calls it a Pro Bowl)'))
clues_21x.push(Entry.create(row: 13, col: 18, dir: 'Across', answer: 'IMEE', number: 74, clue: 'Politician Marcos (hidden in RUNTIME ERROR)'))
clues_21x.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CIT', number: 75, clue: 'Op.-and-loc. follower'))
clues_21x.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TIDAL', number: 76, clue: '___ wave'))
clues_21x.push(Entry.create(row: 14, col: 5, dir: 'Down', answer: 'TESO', number: 76, clue: 'Ugandan ethnic group (hidden in WHITE SOX)'))
clues_21x.push(Entry.create(row: 14, col: 6, dir: 'Down', answer: 'IMALOSER', number: 77, clue: 'Beatles song which Paul McCartney later called one of "John\'s cries for help"'))
clues_21x.push(Entry.create(row: 14, col: 7, dir: 'Down', answer: 'DATELINE', number: 78, clue: '"To Catch a Predator" show'))
clues_21x.push(Entry.create(row: 14, col: 8, dir: 'Down', answer: 'ATOMIZES', number: 79, clue: 'Makes mist'))
clues_21x.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'BDS', number: 80, clue: 'Actor Wong and a "Doonesbury" veteran'))
clues_21x.push(Entry.create(row: 14, col: 13, dir: 'Down', answer: 'SUREHAND', number: 81, clue: 'Surgeon\'s asset'))
clues_21x.push(Entry.create(row: 14, col: 16, dir: 'Across', answer: 'UMCP', number: 82, clue: 'My sch.'))
clues_21x.push(Entry.create(row: 14, col: 17, dir: 'Down', answer: 'MANILOW', number: 83, clue: '"Copacabana" singer'))
clues_21x.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STALEMATE', number: 84, clue: 'Kingpin?'))
clues_21x.push(Entry.create(row: 15, col: 4, dir: 'Down', answer: 'LUG', number: 85, clue: 'Tote'))
clues_21x.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ASU', number: 86, clue: 'Tempe sch.'))
clues_21x.push(Entry.create(row: 15, col: 15, dir: 'Across', answer: 'SPA', number: 87, clue: 'Balneotherapy site'))
clues_21x.push(Entry.create(row: 15, col: 15, dir: 'Down', answer: 'SOT', number: 87, clue: 'Spirit animal?'))
clues_21x.push(Entry.create(row: 15, col: 19, dir: 'Across', answer: 'SUP', number: 88, clue: '"What\'s good?"'))
clues_21x.push(Entry.create(row: 15, col: 20, dir: 'Down', answer: 'UNO', number: 89, clue: 'Numero that an egotista looks out for'))
clues_21x.push(Entry.create(row: 15, col: 21, dir: 'Down', answer: 'PST', number: 90, clue: 'Athletic setting?: Abbr.'))
clues_21x.push(Entry.create(row: 16, col: 4, dir: 'Across', answer: 'USATODAY', number: 91, clue: 'Wall Street Journal competitor'))
clues_21x.push(Entry.create(row: 16, col: 10, dir: 'Down', answer: 'ALA', number: 92, clue: 'As an homage to'))
clues_21x.push(Entry.create(row: 16, col: 13, dir: 'Across', answer: 'ROO', number: 93, clue: 'Joey of kidlit'))
clues_21x.push(Entry.create(row: 16, col: 14, dir: 'Down', answer: 'ONSITE', number: 94, clue: 'Like some inspections'))
clues_21x.push(Entry.create(row: 16, col: 17, dir: 'Across', answer: 'NEONS', number: 95, clue: 'Old Chrysler/Dodge/Plymouth cars'))
clues_21x.push(Entry.create(row: 16, col: 18, dir: 'Down', answer: 'EMPTOR', number: 96, clue: '"Caveat ___"'))
clues_21x.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'THEGOLEM', number: 97, clue: 'Isaac Bashevis Singer novel about a clay giant brought to life'))
clues_21x.push(Entry.create(row: 17, col: 1, dir: 'Down', answer: 'THUMP', number: 97, clue: 'Beat soundly'))
clues_21x.push(Entry.create(row: 17, col: 2, dir: 'Down', answer: 'HANOI', number: 98, clue: '2019 Asian Games host city'))
clues_21x.push(Entry.create(row: 17, col: 3, dir: 'Down', answer: 'ENDIN', number: 99, clue: 'Conclude at'))
clues_21x.push(Entry.create(row: 17, col: 10, dir: 'Across', answer: 'LAMENT', number: 100, clue: 'Wax lugubrious'))
clues_21x.push(Entry.create(row: 17, col: 12, dir: 'Down', answer: 'MCVII', number: 101, clue: 'CCCLXIX * III'))
clues_21x.push(Entry.create(row: 17, col: 17, dir: 'Across', answer: 'IMNOT', number: 102, clue: 'Childish retort to a 1983 Lionel Richie song?'))
clues_21x.push(Entry.create(row: 18, col: 1, dir: 'Across', answer: 'HAN', number: 103, clue: 'Solo, flyer'))
clues_21x.push(Entry.create(row: 18, col: 6, dir: 'Across', answer: 'OLIGARCHS', number: 104, clue: 'Some co-leaders'))
clues_21x.push(Entry.create(row: 18, col: 9, dir: 'Down', answer: 'GERT', number: 105, clue: 'Fr&#246;be who played Auric Goldfinger'))
clues_21x.push(Entry.create(row: 18, col: 16, dir: 'Across', answer: 'ALP', number: 106, clue: 'Peak of a skier\'s career?'))
clues_21x.push(Entry.create(row: 18, col: 16, dir: 'Down', answer: 'ABAT', number: 106, clue: 'Blind as ___'))
clues_21x.push(Entry.create(row: 19, col: 1, dir: 'Across', answer: 'UNDERSIZE', number: 107, clue: 'Surprisingly small'))
clues_21x.push(Entry.create(row: 19, col: 4, dir: 'Down', answer: 'EST', number: 108, clue: 'Stab: Abbr.'))
clues_21x.push(Entry.create(row: 19, col: 5, dir: 'Down', answer: 'RTE', number: 109, clue: 'GPS output'))
clues_21x.push(Entry.create(row: 19, col: 11, dir: 'Across', answer: 'EVAIBBOTSON', number: 110, clue: '"The Secret of Platform 13" author'))
clues_21x.push(Entry.create(row: 19, col: 15, dir: 'Down', answer: 'BIN', number: 111, clue: 'Garbage container'))
clues_21x.push(Entry.create(row: 19, col: 19, dir: 'Down', answer: 'SMU', number: 112, clue: 'The Mustangs of the AAC'))
clues_21x.push(Entry.create(row: 19, col: 20, dir: 'Down', answer: 'OAS', number: 113, clue: 'Gp. estd. in 1948'))
clues_21x.push(Entry.create(row: 19, col: 21, dir: 'Down', answer: 'NNE', number: 114, clue: 'SSW opposite'))
clues_21x.push(Entry.create(row: 20, col: 1, dir: 'Across', answer: 'MOISTENER', number: 115, clue: 'Wetter'))
clues_21x.push(Entry.create(row: 20, col: 11, dir: 'Across', answer: 'AINTIAWOMAN', number: 116, clue: '1851 Sojourner Truth speech'))
clues_21x.push(Entry.create(row: 21, col: 1, dir: 'Across', answer: 'PINTEREST', number: 117, clue: 'Social media website that contains "a few (million) of your favorite things"'))
clues_21x.push(Entry.create(row: 21, col: 12, dir: 'Across', answer: 'IDENT', number: 118, clue: 'Broadcaster\'s tag'))
clues_21x.push(Entry.create(row: 21, col: 18, dir: 'Across', answer: 'RUSE', number: 119, clue: 'Ploy'))
Puzzle.create(title: 'THEMELESS TWENTY-ONE', grid: 'PARA.PROOF..BOMBBLAST|PRIMADONNAS.AVAILABLE|LEONPANETTA.HERAKLION|...IOS.LAWNDARTS..EPT|SILOS.CARAFE.CITRUSES|AVAST.MPG.RAWONION...|WED.LPS.EPA.HAIRSALON|..ORES..TIN.ATSEA.IPO|MILO.ADS.ECHT....ASET|ENCYCLOPEDIAAMERICANA|THECOMMUNISTMANIFESTO|REVERSEDISCRIMINATION|IRIS....SHOE.ASG.IMEE|CIT.TIDAL.BDS..UMCP..|STALEMATE.ASU.SPA.SUP|...USATODAY.ROO.NEONS|THEGOLEM.LAMENT.IMNOT|HAN..OLIGARCHS.ALP...|UNDERSIZE.EVAIBBOTSON|MOISTENER.AINTIAWOMAN|PINTEREST..IDENT.RUSE', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2013-7-9', entries: clues_21x, puzzle_type: 'freestyle')
