clues_butt_heads = Array.new
clues_butt_heads.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'LSAT', number: 1, clue: 'Exam for D.A. hopefuls'))
clues_butt_heads.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'LABEL', number: 1, clue: 'Record ___'))
clues_butt_heads.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'STAVE', number: 2, clue: 'Fend (off)'))
clues_butt_heads.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ATSEA', number: 3, clue: 'Sailing'))
clues_butt_heads.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TAI', number: 4, clue: '"Drunken ___ Chi" (1984 martial arts film)'))
clues_butt_heads.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'DELI', number: 5, clue: 'Chop shop?'))
clues_butt_heads.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DAMIEN', number: 5, clue: '"The Omen" devil child'))
clues_butt_heads.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EXAM', number: 6, clue: 'Midterm or final'))
clues_butt_heads.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'LIT', number: 7, clue: 'On'))
clues_butt_heads.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ISH', number: 8, clue: '-esque'))
clues_butt_heads.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'OHMAN', number: 9, clue: '"Jeez!"'))
clues_butt_heads.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ONEMISSEDCALL', number: 9, clue: '2008 horror movie with a 0% approval rating on Rotten Tomatoes'))
clues_butt_heads.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HOTTEA', number: 10, clue: 'Coffee alternative (if such a thing were possible)'))
clues_butt_heads.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'MOHR', number: 11, clue: 'Comedian Jay with a stint on "Ghost Whisperer"'))
clues_butt_heads.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ASIA', number: 12, clue: 'Kyrgyzstan locale'))
clues_butt_heads.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NECK', number: 13, clue: 'Snog'))
clues_butt_heads.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ATTA', number: 14, clue: '"___ girl!"'))
clues_butt_heads.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AXIS', number: 15, clue: 'Plot line?'))
clues_butt_heads.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'NOOSE', number: 16, clue: 'Lasso loop'))
clues_butt_heads.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BASICMATH', number: 17, clue: '*Division, e.g.'))
clues_butt_heads.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'CRUISECONTROL', number: 18, clue: 'Speed limit?'))
clues_butt_heads.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'ETHIC', number: 19, clue: 'Work ___'))
clues_butt_heads.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EVE', number: 20, clue: '"___\'s Bayou" (1997 film starring Samuel L. Jackson)'))
clues_butt_heads.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'RIM', number: 21, clue: 'Brink'))
clues_butt_heads.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'AMTRAK', number: 22, clue: 'Train service headquartered at Washington Union Station'))
clues_butt_heads.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ANNEX', number: 22, clue: 'Where Toby and Kelly work, on "The Office"'))
clues_butt_heads.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LEAGUE', number: 23, clue: 'With "The," FX show about fantasy football'))
clues_butt_heads.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'GWB', number: 24, clue: 'B.H.O.\'s predecessor'))
clues_butt_heads.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'ERNIE', number: 25, clue: 'Hudson of "Ghostbusters"'))
clues_butt_heads.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'ETA', number: 25, clue: 'Seventh Greek letter'))
clues_butt_heads.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ROTATE', number: 26, clue: 'Let have a turn?'))
clues_butt_heads.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'WINSTONSALEM', number: 27, clue: '*Wake Forest University\'s city (this one\'s a twofer!)'))
clues_butt_heads.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'SPARTA', number: 28, clue: 'Ancient rival of Athens'))
clues_butt_heads.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'LITZ', number: 29, clue: 'Help out at www.preshortzianpuzzleproject.com'))
clues_butt_heads.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'EDGE', number: 30, clue: 'Brink'))
clues_butt_heads.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'MAIN', number: 31, clue: 'Word after water, or a German body of water'))
clues_butt_heads.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'JAMBS', number: 32, clue: 'Door parts'))
clues_butt_heads.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'JOHN', number: 32, clue: '"The Fault in Our Stars" author Green'))
clues_butt_heads.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ALOE', number: 33, clue: '___ vera'))
clues_butt_heads.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'MEOW', number: 34, clue: '"If you touch my tail more time, so help me god..."'))
clues_butt_heads.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'PATES', number: 35, clue: 'Tops of heads'))
clues_butt_heads.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'IDA', number: 36, clue: 'Journalist Wells or Tarbell'))
clues_butt_heads.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'OLE', number: 37, clue: '"Rah rah, Real Madrid!"'))
clues_butt_heads.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'EPA', number: 38, clue: 'Green org.'))
clues_butt_heads.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'PARCH', number: 39, clue: 'Make thirsty'))
clues_butt_heads.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'AXE', number: 40, clue: 'Can'))
clues_butt_heads.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'TGI', number: 41, clue: '___ Friday\'s'))
clues_butt_heads.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'HOO', number: 42, clue: 'Yoo-___'))
clues_butt_heads.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'CARAT', number: 43, clue: 'Unit of diamond weight'))
clues_butt_heads.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ABS', number: 44, clue: 'It\'s good when they\'re ripped, but bad when they\'re torn'))
clues_butt_heads.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'DOZEN', number: 45, clue: '"The Dirty ___"'))
clues_butt_heads.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'OHM', number: 46, clue: 'Unit of resistance'))
clues_butt_heads.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'NEWPORTBEACH', number: 47, clue: '*Setting for "Arrested Development" and "The O.C."'))
clues_butt_heads.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'PIRATE', number: 48, clue: 'Torrent, e.g. (do not do this, it is bad)'))
clues_butt_heads.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ABLEST', number: 49, clue: 'Most competent'))
clues_butt_heads.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'INCAS', number: 50, clue: 'Quipu users'))
clues_butt_heads.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'BAMBER', number: 51, clue: 'Jamie of "Battlestar Galactica"'))
clues_butt_heads.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'BEADY', number: 52, clue: 'Like eyes full of malice'))
clues_butt_heads.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ELLIE', number: 53, clue: '"Lights" singer Goulding ... or 9-Down antagonist ... or 23-Across kid'))
clues_butt_heads.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'ROKER', number: 54, clue: 'Mystery writer Al'))
clues_butt_heads.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'DEARTH', number: 55, clue: 'Lack'))
clues_butt_heads.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'DESK', number: 55, clue: '___ jockey (worker who sits around all day)'))
clues_butt_heads.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'EDEN', number: 56, clue: 'Biblical garden'))
clues_butt_heads.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'AGEE', number: 57, clue: 'Steve of "The Sarah Silverman Program"'))
clues_butt_heads.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ILL', number: 58, clue: '___ Doctrine (Jay Smooth\'s hip-hop blog)'))
clues_butt_heads.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'IMAX', number: 58, clue: 'Big big screen'))
clues_butt_heads.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ELO', number: 59, clue: '"Do Ya" band'))
clues_butt_heads.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EDGAR', number: 60, clue: 'Award for mystery writers'))
clues_butt_heads.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'CAMELWALK', number: 61, clue: '*1960s dance often performed by James Brown'))
clues_butt_heads.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'CBS', number: 61, clue: 'Network that airs "48 Hours" and "60 Minutes" 21 hours apart'))
clues_butt_heads.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ARE', number: 62, clue: '"___ mermaids real?" (question that Google autocompleted with when I typed in this word)'))
clues_butt_heads.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'WON', number: 63, clue: 'Was victorious'))
clues_butt_heads.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SEETO', number: 64, clue: 'Take care of'))
clues_butt_heads.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'BRAS', number: 65, clue: 'Push-ups, e.g.'))
clues_butt_heads.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ODIE', number: 66, clue: 'Dog missing from "Garfield Minus Garfield"'))
clues_butt_heads.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'KNEEL', number: 67, clue: 'Prepare to be dubbed'))
clues_butt_heads.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SEXT', number: 68, clue: 'Use Snapchat, perhaps'))
clues_butt_heads.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'NYER', number: 69, clue: 'Big Apple resident, for short'))
instructions = 'The contest answer is a band (14 letters in total) that would make a good theme entry in this puzzle.'
explanation = '<MA>KOOL AND THE GANG</MA><TEXT>Each theme answer begins with the name of a cigarette brand (and 27-Across is comprised of two): BASIC, WINSTON, SALEM, NEWPORT, and CAMEL. KOOL is also a brand of cigarettes, and KOOL AND THE GANG is 14 letters long, making it the answer.</TEXT>'
Puzzle.create(title: 'BUTT HEADS', grid: 'LSAT.DELI.OHMAN|ATTA.AXIS.NOOSE|BASICMATH.ETHIC|EVE.RIM..AMTRAK|LEAGUE.ERNIE...|...WINSTONSALEM|JAMBS.PATES.IDA|OLE.EPA.AXE.TGI|HOO.CARAT.DOZEN|NEWPORTBEACH...|...INCAS.BAMBER|DEARTH..ILL.ELO|EDGAR.CAMELWALK|SEETO.BRAS.ODIE|KNEEL.SEXT.NYER', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2012-12-4', entries: clues_butt_heads, instructions: instructions, explanation: explanation, puzzle_type: 'meta')