clues_impaired = Array.new
clues_impaired.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'WAFT', number: 1, clue: 'Float, as a scent'))
clues_impaired.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'WEVE', number: 1, clue: '"___ Only Just Begun" (hit for The Carpenters)'))
clues_impaired.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ASIA', number: 2, clue: 'Cambodian continent'))
clues_impaired.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FACT', number: 3, clue: '"Fun ___..."'))
clues_impaired.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TUTSI', number: 4, clue: 'Don Cheadle\'s character\'s wife, for one, in "Hotel Rwanda"'))
clues_impaired.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'JABS', number: 5, clue: 'Injections'))
clues_impaired.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'JUMPOUT', number: 5, clue: 'Emerge, as a stripper from a giant cake'))
clues_impaired.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ACL', number: 6, clue: 'Knee part injured by some athletes: Abbr.'))
clues_impaired.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BLEU', number: 7, clue: 'French flag color'))
clues_impaired.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SASS', number: 8, clue: 'Backtalk'))
clues_impaired.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'AMORE', number: 9, clue: 'Love, to Dean Martin'))
clues_impaired.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ARC', number: 9, clue: 'Circle section'))
clues_impaired.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MORRISSEY', number: 10, clue: 'Lead singer of The Smiths'))
clues_impaired.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ODIE', number: 11, clue: 'Garfield\'s canine foil'))
clues_impaired.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RAMP', number: 12, clue: 'What a skateboarder is inclined to use?'))
clues_impaired.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EYES', number: 13, clue: '"Their ___ Were Watching God"'))
clues_impaired.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ESAU', number: 14, clue: 'Biblical twin'))
clues_impaired.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'UCLA', number: 15, clue: 'Shabazz Muhammad\'s sch.'))
clues_impaired.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'RODAY', number: 16, clue: 'James of "Psych"'))
clues_impaired.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'VICTIMLESSCRIME', number: 17, clue: 'Author of "Sister Carrie" and "An American Tragedy"'))
clues_impaired.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'IUDS', number: 18, clue: 'Alternatives to the pill'))
clues_impaired.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'SEAM', number: 19, clue: 'Part of a baseball that a pitcher grips'))
clues_impaired.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EATSUP', number: 20, clue: 'Consumes'))
clues_impaired.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'USE', number: 21, clue: 'Consume'))
clues_impaired.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'REPS', number: 22, clue: 'Weight room count'))
clues_impaired.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'IDOS', number: 23, clue: 'Wedding exchange'))
clues_impaired.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'SNOOKI', number: 24, clue: 'Reality star who doesn\'t eat lobster because it\'s "alive when you kill it"'))
clues_impaired.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'AQI', number: 25, clue: 'EPA measure'))
clues_impaired.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'QUAD', number: 26, clue: 'Four-person dorm room'))
clues_impaired.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'MOM', number: 27, clue: 'She has a day in May'))
clues_impaired.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'MINAJ', number: 27, clue: 'Colleague of Jackson, Urban, and Carey'))
clues_impaired.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OMANI', number: 28, clue: 'One whose national emblem includes a sheathed khanjar dagger'))
clues_impaired.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'MAXIM', number: 29, clue: 'Magazine with a "Hot 100" list'))
clues_impaired.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SUNNIMUSLIM', number: 30, clue: 'He won an Oscar for scoring "The Social Network"'))
clues_impaired.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'NOVEM', number: 31, clue: 'IX'))
clues_impaired.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'INARMS', number: 32, clue: 'Words after "comrade" or "up"'))
clues_impaired.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'LIMOS', number: 33, clue: 'Long rides'))
clues_impaired.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'IDOLS', number: 34, clue: 'Kelly Clarkson and Phillip Phillips, for two'))
clues_impaired.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'MESON', number: 35, clue: 'Particle composed of a quark and an antiquark'))
clues_impaired.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'IMAC', number: 36, clue: '1998 Apple debut with a giggly Jeff Goldblum-narrated commercial'))
clues_impaired.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'COMMUNITY', number: 37, clue: 'Show with a lot of Chase scenes?'))
clues_impaired.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'TOON', number: 38, clue: 'Any "Archer" character'))
clues_impaired.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ASIDE', number: 39, clue: 'Comment to the audience'))
clues_impaired.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NAXOS', number: 40, clue: 'Record label named after a Greek island (anagram of SAXON)'))
clues_impaired.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SAYS', number: 41, clue: 'Utters'))
clues_impaired.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'OVA', number: 42, clue: 'Caesar\'s cartonful'))
clues_impaired.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'DEMOS', number: 43, clue: 'Test drives'))
clues_impaired.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ANIMA', number: 44, clue: 'Jung\'s feminine side'))
clues_impaired.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'KERR', number: 45, clue: 'Model Miranda married to Orlando Bloom'))
clues_impaired.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'RENAMES', number: 46, clue: 'Gives a new title'))
clues_impaired.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'YOLO', number: 47, clue: 'Motto that Zac Efron has tattooed on his hand'))
clues_impaired.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'JIMMYKIMMEL', number: 48, clue: '"Shall We Dance" star'))
clues_impaired.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'KATE', number: 49, clue: 'Upton featured in the first Antarctican fashion shoot'))
clues_impaired.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'LATE', number: 50, clue: 'Fashionably unpunctual'))
clues_impaired.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'SSN', number: 51, clue: 'Digits on an IRS form'))
clues_impaired.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'USA', number: 52, clue: '"Suits" network'))
clues_impaired.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SNAG', number: 53, clue: 'Catch'))
clues_impaired.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'GLOSS', number: 54, clue: 'Lip ___'))
clues_impaired.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SPIN', number: 55, clue: 'Test drive'))
clues_impaired.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SLED', number: 55, clue: 'Iditarod vehicle'))
clues_impaired.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'PILE', number: 56, clue: 'Heap'))
clues_impaired.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'IMAX', number: 57, clue: 'It\'s big in movie theaters?'))
clues_impaired.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'TAX', number: 58, clue: '___ Day (April 15)'))
clues_impaired.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'ADAM', number: 59, clue: 'Colleague of Blake, Shakira, and Usher'))
clues_impaired.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'XTRA', number: 60, clue: 'Ad exec\'s bonus?'))
clues_impaired.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ATLAST', number: 61, clue: 'Etta James classic'))
clues_impaired.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ANNE', number: 62, clue: 'Hathaway who voiced a macaw in "Rio"'))
clues_impaired.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'SLOG', number: 63, clue: 'Struggle (through)'))
clues_impaired.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'TYGA', number: 64, clue: 'Animalistic-sounding "Rack City" rapper'))
clues_impaired.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LIMITEDTIMEONLY', number: 65, clue: 'He challenged Mr. Gorbachev in 1987'))
clues_impaired.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'TES', number: 66, clue: 'They might block for, or catch a pass from, the QB'))
clues_impaired.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'INN', number: 67, clue: 'Holiday ___'))
clues_impaired.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ELATE', number: 68, clue: 'Delight'))
clues_impaired.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ARNE', number: 69, clue: 'Duncan who scored 11 points in the 2013 NBA Celebrity All-Star Game (also, he\'s the Secretary of Education)'))
clues_impaired.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'SNOG', number: 70, clue: 'Make out, across the pond'))
clues_impaired.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DEXYS', number: 71, clue: '___ Midnight Runners ("Come On Eileen" group)'))
clues_impaired.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'MANS', number: 72, clue: '"It\'s a ___ ___ ___ World" (James Brown song)'))
clues_impaired.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SEGA', number: 73, clue: 'Dreamcast maker'))
Puzzle.create(title: 'IMPAIRED JUDGMENT', grid: 'WAFT.JABS.AMORE|ESAU.UCLA.RODAY|VICTIMLESSCRIME|EATSUP.USE.REPS|...IDOS..AQI...|MOM.SUNNIMUSLIM|IMAC.TOON.ASIDE|NAXOS.OVA.DEMOS|ANIMA.KERR.YOLO|JIMMYKIMMEL.SSN|...USA..SNAG...|SPIN.TAX.ATLAST|LIMITEDTIMEONLY|ELATE.ARNE.SNOG|DEXYS.MANS.SEGA', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2013-3-31', entries: clues_impaired, puzzle_type: 'themed')