clues_lol = Array.new
clues_lol.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BARBS', number: 1, clue: 'Some fish, or fish hook parts'))
clues_lol.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BACON', number: 1, clue: 'Most actors have his number'))
clues_lol.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ADORE', number: 2, clue: '"My cherie amour, pretty little one that I ___..." (Stevie Wonder lyric)'))
clues_lol.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RULER', number: 3, clue: 'Measuring tool'))
clues_lol.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'BLOODPH', number: 4, clue: 'It should stay between 7.35 and 7.45'))
clues_lol.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'STN', number: 5, clue: 'RR depot'))
clues_lol.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'HOP', number: 6, clue: 'Emulate the Easter Bunny'))
clues_lol.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HELDON', number: 6, clue: 'Hung in there'))
clues_lol.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OVERRIPE', number: 7, clue: 'Bitter, say'))
clues_lol.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'PEA', number: 8, clue: 'Chicken &#224; la King ingredient'))
clues_lol.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'LAX', number: 9, clue: 'Sport with sticks, for short'))
clues_lol.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'LASTLAP', number: 9, clue: 'An anchor holds it down'))
clues_lol.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'AGELINE', number: 10, clue: 'What Dumbledore draws to keep young students away from the Goblet of Fire'))
clues_lol.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'XES', number: 11, clue: 'Letters on a pro bowler\'s scorecard'))
clues_lol.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ADULTBEVERAGE', number: 12, clue: 'Porter or boilermaker'))
clues_lol.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'BCD', number: 13, clue: 'Pre-E three'))
clues_lol.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'RNS', number: 14, clue: 'IV luggers?'))
clues_lol.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'COLONCLEANSES', number: 15, clue: 'Some irrigations'))
clues_lol.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OREO', number: 16, clue: 'Krispy Kreme donut variety with the tagline "No twisting required"'))
clues_lol.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'DDR', number: 17, clue: 'Video game that involves hitting arrows with one\'s feet: Abbr.'))
clues_lol.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'STL', number: 18, clue: 'Cardinal cap letters'))
clues_lol.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NERD', number: 19, clue: 'Erik Agard, for one'))
clues_lol.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'ORI', number: 20, clue: '"...___ quit!"'))
clues_lol.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ICET', number: 21, clue: 'Rapper/actor who played himself playing a detective in the "30 Rock" finale'))
clues_lol.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'LIN', number: 22, clue: 'Rocket Jeremy'))
clues_lol.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'NOR', number: 23, clue: '"Neither snow ___ rain ___ heat ___ gloom of night..."'))
clues_lol.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'PHONIC', number: 24, clue: 'Sound-related'))
clues_lol.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'HOER', number: 25, clue: 'Gardener, at times'))
clues_lol.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'OFFICERS', number: 26, clue: 'Blue man group?'))
clues_lol.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ANO', number: 27, clue: 'Word in "Feliz Navidad"'))
clues_lol.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DASHOF', number: 28, clue: 'With 31-Across, it\'s enough to add flavor, but not enough to make you sneeze'))
clues_lol.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'DEB', number: 28, clue: '"It\'s Not PMS, It\'s You" author Amlen'))
clues_lol.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ACCORDS', number: 29, clue: 'Some Hondas'))
clues_lol.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'SOSPADS', number: 30, clue: 'Brillo alternatives'))
clues_lol.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'PEPPER', number: 31, clue: 'See 28-Across'))
clues_lol.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'PEEKSAT', number: 32, clue: 'Glimpses'))
clues_lol.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ECO', number: 33, clue: 'Prefix with conscious'))
clues_lol.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'EFFETE', number: 34, clue: 'Self-indulgent'))
clues_lol.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'FOOTED', number: 35, clue: 'Sure-___ (not likely to trip)'))
clues_lol.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BCS', number: 36, clue: 'NCAA football selection system'))
clues_lol.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'RIO', number: 37, clue: 'Site of the next Summer Olympics'))
clues_lol.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'EGAD', number: 38, clue: '"Oh my stars!"'))
clues_lol.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'GOTYE', number: 39, clue: '"Somebody That I Used To Know" singer'))
clues_lol.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ALENE', number: 40, clue: 'Coeur d\'___ (birthplace of NBA guard Luke Ridnour)'))
clues_lol.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'DARED', number: 41, clue: 'Had the courage'))
clues_lol.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'OPS', number: 42, clue: '"Call of Duty: Black ___ II"'))
clues_lol.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'SCI', number: 43, clue: 'Agr., anth., or astr.'))
clues_lol.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'CON', number: 44, clue: 'Scam'))
clues_lol.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'NBD', number: 45, clue: '"Lol, don\'t worry about it"'))
clues_lol.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'KOLA', number: 46, clue: 'Inca ___ (Peruvian soft drink)'))
clues_lol.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BRACKETBUSTER', number: 47, clue: 'Florida Gulf Coast University, for most'))
clues_lol.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'BEE', number: 47, clue: '"Honey ___" (2011 Blake Shelton song)'))
clues_lol.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'KEL', number: 48, clue: '"Kenan & ___"'))
clues_lol.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'UMS', number: 49, clue: 'Verbal stumbles'))
clues_lol.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EDDIEREDMAYNE', number: 50, clue: 'He played Marius Pontmercy in 2012\'s "Les Mis&#233;rables"'))
clues_lol.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ESS', number: 51, clue: 'Swelled head'))
clues_lol.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'LSD', number: 52, clue: 'Acid'))
clues_lol.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'STEED', number: 53, clue: 'Mount'))
Puzzle.create(title: 'LOL SMILEY FACE', grid: 'BARBS.HOP.LAX|ADULTBEVERAGE|COLONCLEANSES|OREO.DDR.STL.|NERD..ORI.LIN|...PHONIC.ANO|DASHOF.PEPPER|ECO.EFFETE...|BCS.RIO..EGAD|.OPS.CON.KOLA|BRACKETBUSTER|EDDIEREDMAYNE|ESS.LSD.STEED', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2013-3-26', entries: clues_lol, puzzle_type: 'themed')