clues_shenanigans = Array.new
clues_shenanigans.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MMM', number: 1, clue: 'STEINEM MAGAZINE / "DELICIOUS!"'))
clues_shenanigans.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MAPLE', number: 1, clue: 'With 56-Down, waffle topping'))
clues_shenanigans.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MARIA', number: 2, clue: '"Ave ___"'))
clues_shenanigans.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MAELSTROM', number: 3, clue: 'Shipwreck cause in a Poe story'))
clues_shenanigans.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'ZAS', number: 4, clue: 'Papa John\'s pies, for people who talk in archaic Scrabble slang'))
clues_shenanigans.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ZOIC', number: 4, clue: 'Era suffix'))
clues_shenanigans.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'AUS', number: 5, clue: 'Ger. neighbor'))
clues_shenanigans.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'STP', number: 6, clue: '___ 400 (NASCAR race held at Kansas Speedway)'))
clues_shenanigans.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'BAC', number: 7, clue: 'DUI stat'))
clues_shenanigans.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BOSOM', number: 7, clue: '___ buddies'))
clues_shenanigans.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ANEMIC', number: 8, clue: 'Devoid of vitality'))
clues_shenanigans.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CEDE', number: 9, clue: 'Turn over'))
clues_shenanigans.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ASS', number: 10, clue: 'Big Sean song whose title word is replaced with "Dance" in the radio version'))
clues_shenanigans.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AKERS', number: 10, clue: 'Placekicker David or criminologist Ronald'))
clues_shenanigans.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SKEET', number: 11, clue: 'Actor Ulrich'))
clues_shenanigans.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SKEWS', number: 12, clue: 'Misrepresents'))
clues_shenanigans.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AAA', number: 13, clue: 'STEVIE WONDER SONG WITH THE LYRIC "UNTIL WE DREAM OF LIFE AND LIFE BECOMES A DREAM" / ORG. THAT CAN GIVE YOU A JUMP'))
clues_shenanigans.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'OUTDONE', number: 14, clue: 'Bested'))
clues_shenanigans.push(Entry.create(row: 2, col: 8, dir: 'Down', answer: 'DOHA', number: 15, clue: 'Qatar capital'))
clues_shenanigans.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'KKK', number: 16, clue: 'TOPEKA\'S ST. / HATEFUL GRP. IN WHITE ROBES'))
clues_shenanigans.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PREDISPOSED', number: 17, clue: 'Susceptible'))
clues_shenanigans.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'DATAMINING', number: 18, clue: 'Statistical analysis buzzword'))
clues_shenanigans.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'EEE', number: 19, clue: 'IT IS, EN ESPANOL/ WIDE SHOE SIZE'))
clues_shenanigans.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'LILAC', number: 20, clue: 'The Color Purple (well, a shade of it)'))
clues_shenanigans.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'HOMEBREW', number: 21, clue: 'Flat drink?'))
clues_shenanigans.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'BASSETOBOE', number: 22, clue: 'Woodwind that sounds like it should have droopy ears'))
clues_shenanigans.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'EAST', number: 23, clue: 'The Sun Also Rises there (well, the sun only rises there)'))
clues_shenanigans.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'MIAMI', number: 24, clue: 'Marlins\' home'))
clues_shenanigans.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'MES', number: 24, clue: 'Diciembre, por ejemplo'))
clues_shenanigans.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'IDIOM', number: 25, clue: 'Turn of phrase'))
clues_shenanigans.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'ASTS', number: 26, clue: 'Point guard\'s stat: Abbr.'))
clues_shenanigans.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'TAMED', number: 27, clue: '"Can\'t Be ___" (title track from a Miley Cyrus album)'))
clues_shenanigans.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'MISOS', number: 28, clue: 'Japanese seasonings'))
clues_shenanigans.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'CSS', number: 29, clue: 'Webpage formatting lang.'))
clues_shenanigans.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'SARAH', number: 30, clue: '"The Truth About Forever" author Dessen'))
clues_shenanigans.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SURMISING', number: 31, clue: 'Conjecturing'))
clues_shenanigans.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'STK', number: 31, clue: 'NYSE buy'))
clues_shenanigans.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'URL', number: 32, clue: 'koalastothemax.com, e.g.'))
clues_shenanigans.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'NRA', number: 33, clue: 'Gun rights gp.'))
clues_shenanigans.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'GENII', number: 34, clue: 'Spirits that encourage wishful thinking'))
clues_shenanigans.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ASBAD', number: 35, clue: 'Comparatively atrocious'))
clues_shenanigans.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'BUTTERCUP', number: 36, clue: 'Flower in a Foundations hit'))
clues_shenanigans.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ASA', number: 37, clue: 'Ender\'s portrayer in the upcoming "Ender\'s Game"'))
clues_shenanigans.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'DEN', number: 38, clue: 'Peyton Manning\'s team, on scoreboards'))
clues_shenanigans.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TROIS', number: 39, clue: 'M&#233;nage &#224; ___'))
clues_shenanigans.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'ORE', number: 40, clue: 'Setting for Duck tales?: Abbr.'))
clues_shenanigans.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'REUSE', number: 41, clue: 'One of the EPA\'s three R\'s'))
clues_shenanigans.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'KLMNO', number: 42, clue: 'Letters between J and P'))
clues_shenanigans.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'MANHATTAN', number: 43, clue: 'Whiskey cocktail'))
clues_shenanigans.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'HSN', number: 44, clue: 'QVC alternative'))
clues_shenanigans.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ISH', number: 45, clue: '-like'))
clues_shenanigans.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'HORACE', number: 46, clue: 'Mann or Greeley'))
clues_shenanigans.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ISHOT', number: 47, clue: '"___ the Sheriff"'))
clues_shenanigans.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SHUN', number: 48, clue: 'Eschew'))
clues_shenanigans.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'SKITS', number: 48, clue: '"Key &amp; Peele" segments'))
clues_shenanigans.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HAITI', number: 49, clue: 'Port-au-Prince is its capital'))
clues_shenanigans.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'UNITE', number: 50, clue: 'Get together'))
clues_shenanigans.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'OPTIN', number: 51, clue: 'Enlist'))
clues_shenanigans.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'PORES', number: 52, clue: 'Reads (over)'))
clues_shenanigans.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'TODD', number: 53, clue: 'With "the," high-fiving "Scrubs" character'))
clues_shenanigans.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'BEGS', number: 54, clue: 'Voices one\'s hunger for dog food'))
clues_shenanigans.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'GROUP', number: 55, clue: 'Assort'))
clues_shenanigans.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SYRUP', number: 56, clue: 'See 1-Down'))
clues_shenanigans.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'KANGAROO', number: 57, clue: 'It has hops and a powerful kick'))
clues_shenanigans.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'AGIN', number: 58, clue: 'Opposed to, in dialect'))
clues_shenanigans.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'SORRY', number: 59, clue: '"My b!"'))
clues_shenanigans.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'SDAK', number: 59, clue: 'Sioux Falls st.'))
clues_shenanigans.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'III', number: 60, clue: '= / ROBERT GRIFFIN ___'))
clues_shenanigans.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'GARDENDECOR', number: 61, clue: 'Gnomes or flamingos'))
clues_shenanigans.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ETA', number: 62, clue: 'H as in Hellenic'))
clues_shenanigans.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'NEO', number: 63, clue: '"The Matrix" hero whose name is an anagram of "one," as in "The One," which he is, GASP'))
clues_shenanigans.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TTT', number: 64, clue: 'POET ELIOT / SECOND BOOK OF THE LOTR TRILOGY'))
clues_shenanigans.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ICEDTEA', number: 65, clue: 'Half and half half'))
clues_shenanigans.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'UUU', number: 66, clue: 'YOU AND I / FORMER CHEMICAL SYMBOL FOR THE ELEMENT NOW KNOWN AS ROENTGENIUM'))
clues_shenanigans.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SIE', number: 67, clue: '"Sprechen ___ Deutsch?"'))
clues_shenanigans.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'NES', number: 68, clue: 'Video game console released as the "Family Computer" in Japan'))
clues_shenanigans.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'AOK', number: 69, clue: 'Peachy keen'))
clues_shenanigans.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'PPP', number: 70, clue: 'ADDENDUM TO A LETTER, BRIEFLY / VERY QUIET, IN SHEET MUSIC'))
instructions = 'This week\'s contest answer turned 100 this year!'
explanation = '<MA>BBB (The Better Business Bureau)</MA><TEXT>The eight short theme answers each consist of three repeated letters, and each is clued in two ways. The first clue provides the literal answer (as in "Delicious" for MMM), while the second clue provides an alternative reading of the answer as (repeated letter)S (as in "Steinem magazine" for MS). Thus AAA can be read as AS, KKK as KS, EEE as ES, etc. The letters, in order, spell out "make it up," which, together with the title, hints at the term BS. Reversing the gimmick used in the theme answers gives us BBB, the answer.</TEXT>'
Puzzle.create(title: 'SHENANIGANS!', grid: 'MMM.ZAS.BAC.ASS|AAA.OUTDONE.KKK|PREDISPOSED.EEE|LILAC..HOMEBREW|EAST.MIAMI.ASTS|..TAMED..CSS...|SURMISING.ASBAD|TROIS.ORE.REUSE|KLMNO.MANHATTAN|...ISH..ISHOT..|SHUN.OPTIN.BEGS|KANGAROO..SORRY|III.GARDENDECOR|TTT.ICEDTEA.UUU|SIE.NES.AOK.PPP', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2012-12-18', entries: clues_shenanigans, instructions: instructions, explanation: explanation, puzzle_type: 'meta')