clues_spoiler_alert = Array.new
clues_spoiler_alert.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TEASE', number: 1, clue: 'Backcomb'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TAO', number: 1, clue: 'The way, in China'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELL', number: 2, clue: 'Wing of a building'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ALI', number: 3, clue: 'Landry known as the girl from those Doritos commercials'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SOVIET', number: 4, clue: 'SSR part'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'EYED', number: 5, clue: 'Visually coveted'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ADOPT', number: 6, clue: 'Bring home, as a stray'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'AMS', number: 6, clue: 'OJ times'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DATUM', number: 7, clue: 'Stat'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ORONO', number: 8, clue: 'Maine college town'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PINING', number: 9, clue: 'Aching (for)'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TEE', number: 10, clue: 'Clothing article with a dumb one-liner, often'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'CAT', number: 11, clue: 'Word after keyboard or nyan, in internet memes'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'COMPILATION', number: 11, clue: '"At the Close of a Century," for Stevie Wonder, e.g.'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'APIECE', number: 12, clue: 'Each'))
clues_spoiler_alert.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TARGET', number: 13, clue: 'You might have one on your back'))
clues_spoiler_alert.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALLOY', number: 14, clue: 'Bronze, for one'))
clues_spoiler_alert.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'MARIE', number: 15, clue: 'Antoinette who lost her head in a crisis'))
clues_spoiler_alert.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'OPA', number: 16, clue: '___-locka, Florida'))
clues_spoiler_alert.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OLIVERSTONE', number: 17, clue: '*"Platoon" director'))
clues_spoiler_alert.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'ROLLER', number: 18, clue: '___ derby'))
clues_spoiler_alert.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'MIR', number: 19, clue: '2001 deorbiter'))
clues_spoiler_alert.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'IDO', number: 20, clue: '"Yes, dear!"'))
clues_spoiler_alert.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'UNI', number: 21, clue: 'It can come before sex... or corn'))
clues_spoiler_alert.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'JPEG', number: 22, clue: 'File format for photos'))
clues_spoiler_alert.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'JULIA', number: 22, clue: 'Louis-Dreyfus of "Veep"'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SAFE', number: 23, clue: '"___ House" (2012 thriller)'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'SAPP', number: 23, clue: 'Ex-Buc Warren'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ALOE', number: 24, clue: '___ vera'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'FLIPONESLID', number: 25, clue: 'Go ape'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'LEMONJUICE', number: 26, clue: '*Tart part of a yellow fruit'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'EDAMS', number: 27, clue: 'Cheeses that are smade backwards (wait, this joke doesn\'t work here)'))
clues_spoiler_alert.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'JUMPON', number: 28, clue: 'Play with, as a trampoline'))
clues_spoiler_alert.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ALLTOLD', number: 29, clue: 'Looking at the big picture'))
clues_spoiler_alert.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ONESEC', number: 30, clue: '"Hold your horses!"'))
clues_spoiler_alert.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'GULLET', number: 31, clue: 'Maw'))
clues_spoiler_alert.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'POI', number: 32, clue: 'Taro-based treat'))
clues_spoiler_alert.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'NEARS', number: 33, clue: 'Approaches'))
clues_spoiler_alert.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'RIP', number: 34, clue: 'Tear'))
clues_spoiler_alert.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'SNITS', number: 35, clue: 'Hissy fits'))
clues_spoiler_alert.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'MIA', number: 36, clue: 'Hamm or Wasikowska'))
clues_spoiler_alert.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PEPPERMINTPATTY', number: 37, clue: '*Friend of Chuck Brown'))
clues_spoiler_alert.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'PRINT', number: 38, clue: 'Run in the paper'))
clues_spoiler_alert.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'TRISTE', number: 39, clue: 'Sad, in Spain'))
clues_spoiler_alert.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'TGIF', number: 40, clue: '"Bring on the weekend!"'))
clues_spoiler_alert.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'YOLO', number: 41, clue: '"Carpe diem!"'))
clues_spoiler_alert.push(Entry.create(row: 9, col: 3, dir: 'Across', answer: 'ORS', number: 42, clue: 'Transplant sites: Abbr.'))
clues_spoiler_alert.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'SPIRO', number: 43, clue: 'Agnew who was the first Greek American Vice President'))
clues_spoiler_alert.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'IGO', number: 44, clue: '"Where did ___ wrong?"'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'DENIES', number: 45, clue: 'Gainsays'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'DFLATS', number: 45, clue: 'C sharp equivalents'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'EROICA', number: 46, clue: 'Beethoven\'s Third'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'SHOWER', number: 47, clue: 'Bath alternative'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'TINFOIL', number: 48, clue: 'Alcoa product'))
clues_spoiler_alert.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'FIDDLE', number: 49, clue: 'Proverbially fit instrument'))
clues_spoiler_alert.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'FRENCHKISS', number: 50, clue: '*Passionate smooch'))
clues_spoiler_alert.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'KRILL', number: 51, clue: 'Whale\'s diet'))
clues_spoiler_alert.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ITSME', number: 52, clue: '"Speaking"'))
clues_spoiler_alert.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'INFO', number: 53, clue: 'Details, briefly'))
clues_spoiler_alert.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LOST', number: 54, clue: 'Subject of the Entertainment Weekly quote "Plane crash. Smoke monster. Polar bear. Crazy French lady."'))
clues_spoiler_alert.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'ORT', number: 55, clue: 'Food scrap'))
clues_spoiler_alert.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'TAD', number: 56, clue: 'Bit'))
clues_spoiler_alert.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'ANON', number: 57, clue: 'Oft-quoted auth.'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AIL', number: 58, clue: 'Be sick as a dog'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'TWISTENDING', number: 59, clue: 'Moviegoer\'s mindblower ... or what the first word of each starred answer can have'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'TSA', number: 59, clue: 'Org. that has patting down down pat'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'TAN', number: 60, clue: 'You basked for it!'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'IDA', number: 61, clue: 'Civil rights hero Wells (I think I used this clue like 10 times already - but seriously, google her, she\'s amazing)'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'NIT', number: 62, clue: 'Picked bug'))
clues_spoiler_alert.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'GEO', number: 63, clue: 'Prefix with thermal'))
clues_spoiler_alert.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TCI', number: 64, clue: 'Old cable inits.'))
clues_spoiler_alert.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'SELMA', number: 65, clue: 'Turnaround Tuesday starting point'))
clues_spoiler_alert.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'OLDIE', number: 66, clue: 'Golden tune'))
clues_spoiler_alert.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SAD', number: 67, clue: 'Lugubrious'))
clues_spoiler_alert.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ARLEN', number: 68, clue: 'Senator Specter (may he rest in peace)'))
clues_spoiler_alert.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'NEATO', number: 69, clue: '"Rad!"'))
Puzzle.create(title: 'SPOILER ALERT!', grid: 'TEASE.ADOPT.CAT|ALLOY.MARIE.OPA|OLIVERSTONE.MIR|...IDO.UNI.JPEG|SAFE.LEMONJUICE|ALLTOLD..GULLET|POI.NEARS.MIA..|PEPPERMINTPATTY|..ORS.SPIRO.IGO|DENIES..TINFOIL|FRENCHKISS.INFO|LOST.ORT.TAD...|AIL.TWISTENDING|TCI.SELMA.OLDIE|SAD.ARLEN.NEATO', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2012-11-27', entries: clues_spoiler_alert, puzzle_type: 'themed')