clues_the_war = Array.new
clues_the_war.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'LIZZIE', number: 1, clue: 'Animated role for Hilary', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('LIZZIE'))]))
clues_the_war.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'LOSER', number: 1, clue: '"The Biggest ___" (NBC diet competition)', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('LOSER'))]))
clues_the_war.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'INUSE', number: 2, clue: 'Occupied', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('INUSE'))]))
clues_the_war.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ZESTS', number: 3, clue: 'Grates, as a lemon', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ZESTS'))]))
clues_the_war.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ZACH', number: 4, clue: '"Between Two Ferns with ___ Galifianakis"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ZACH'))]))
clues_the_war.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'IRA', number: 5, clue: 'Retiree\'s nest egg: Abbr.', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('IRA'))]))
clues_the_war.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'EMBERS', number: 6, clue: 'Grill remnants', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('EMBERS'))]))
clues_the_war.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'AMAS', number: 7, clue: 'Reddit Q&amp;As', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AMAS'))]))
clues_the_war.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AMOI', number: 7, clue: 'Mine, on the Rhine', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AMOI'))]))
clues_the_war.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'MATCHBOX', number: 8, clue: 'Striking scene?', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('MATCHBOX'))]))
clues_the_war.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'AXE', number: 9, clue: 'Body gel brand known as Lynx outside of the United States', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AXE'))]))
clues_the_war.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SID', number: 10, clue: '"___ the Science Kid"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('SID'))]))
clues_the_war.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'COT', number: 11, clue: 'Basic bed', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('COT'))]))
clues_the_war.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CHIEFTAIN', number: 11, clue: 'Tribe\'s top banana', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('CHIEFTAIN'))]))
clues_the_war.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OUBLIETTE', number: 12, clue: 'Dungeon only accessible from the top', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('OUBLIETTE'))]))
clues_the_war.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TEMPTRESS', number: 13, clue: 'Siren', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('TEMPTRESS'))]))
clues_the_war.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ONEARM', number: 14, clue: 'Feature of Def Leppard drummer Rick Allen', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ONEARM'))]))
clues_the_war.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'MAXI', number: 15, clue: '___ pad', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('MAXI'))]))
clues_the_war.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'HUE', number: 16, clue: 'Shade', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('HUE'))]))
clues_the_war.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SUSCABOOTED', number: 17, clue: 'Like a tightrope walker, hopefully', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('SUSCABOOTED'))]))
clues_the_war.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'OPEC', number: 18, clue: 'Gp. for Qatar and Venezuela', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('OPEC'))]))
clues_the_war.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'IBM', number: 19, clue: 'Watson\'s maker', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('IBM'))]))
clues_the_war.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ESTH', number: 20, clue: 'Bk. read at Purim', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ESTH'))]))
clues_the_war.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'EPIC', number: 21, clue: 'Word before fail or win, in modern parlance', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('EPIC'))]))
clues_the_war.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'HELP', number: 22, clue: '"___ is on the way"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('HELP'))]))
clues_the_war.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'HAH', number: 22, clue: 'Palindromist\'s scoff', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('HAH'))]))
clues_the_war.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'RES', number: 23, clue: 'Lo-___ monitor', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('RES'))]))
clues_the_war.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'DRE', number: 24, clue: 'Beats by Dr. ___', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('DRE'))]))
clues_the_war.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'DIM', number: 24, clue: 'Poorly lit', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('DIM'))]))
clues_the_war.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'HASAFIT', number: 25, clue: 'Erupts', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('HASAFIT'))]))
clues_the_war.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'AIDA', number: 26, clue: 'Operatic slave', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AIDA'))]))
clues_the_war.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'SGS', number: 27, clue: 'Kobe and D-Wade, positionally: Abbr.', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('SGS'))]))
clues_the_war.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'FISCABIGHTER', number: 28, clue: 'One going to blazes?', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('FISCABIGHTER'))]))
clues_the_war.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'FAO', number: 28, clue: '___ Schwarz', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('FAO'))]))
clues_the_war.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ARENA', number: 29, clue: 'Amway Center, for one', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ARENA'))]))
clues_the_war.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BTEAM', number: 30, clue: 'Second squad', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('BTEAM'))]))
clues_the_war.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'BOYFRIEND', number: 30, clue: '2012 Justin Bieber single', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('BOYFRIEND'))]))
clues_the_war.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'THEEAGLES', number: 31, clue: '"Take It Easy" band', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('THEEAGLES'))]))
clues_the_war.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ENTANGLES', number: 32, clue: 'Mixes up (in)', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ENTANGLES'))]))
clues_the_war.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'RODS', number: 33, clue: 'Fishing apparatuses', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('RODS'))]))
clues_the_war.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ATE', number: 34, clue: 'Had a cow, e.g.?', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ATE'))]))
clues_the_war.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'OHNO', number: 35, clue: '"The horror!"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('OHNO'))]))
clues_the_war.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'ALEXA', number: 36, clue: 'Vega of "Spy Kids"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ALEXA'))]))
clues_the_war.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'AMSO', number: 36, clue: '"I ___ sorry!"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AMSO'))]))
clues_the_war.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'LOCKOUTS', number: 37, clue: 'Sports fans\' disappointments', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('LOCKOUTS'))]))
clues_the_war.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'ZITS', number: 38, clue: 'Comic strip about a teen', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ZITS'))]))
clues_the_war.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'ZIM', number: 38, clue: '"Invader ___"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ZIM'))]))
clues_the_war.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'YET', number: 39, clue: 'To date', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('YET'))]))
clues_the_war.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'CMON', number: 40, clue: '"Allons-y!"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('CMON'))]))
clues_the_war.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'CUM', number: 40, clue: 'Word on a diploma or in a sext', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('CUM'))]))
clues_the_war.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'MINES', number: 41, clue: 'They\'re swept for in a popular game', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('MINES'))]))
clues_the_war.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'MLK', number: 41, clue: 'Civ. rights hero', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('MLK'))]))
clues_the_war.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'FEATUSCABILM', number: 42, clue: 'The big picture?', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('FEATUSCABILM'))]))
clues_the_war.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'TAY', number: 43, clue: '"Chocolate Rain" singer Zonday', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('TAY'))]))
clues_the_war.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'BARS', number: 44, clue: 'Chase scenes?', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('BARS'))]))
clues_the_war.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ICECAP', number: 45, clue: 'Melting Martian mass', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ICECAP'))]))
clues_the_war.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RANAMOK', number: 46, clue: 'Got out of hand', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('RANAMOK'))]))
clues_the_war.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ACK', number: 47, clue: 'Cathy\'s cry, in the comics', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ACK'))]))
clues_the_war.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'DON', number: 48, clue: 'Cheadle of "House of Lies"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('DON'))]))
clues_the_war.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'DEERE', number: 48, clue: 'John of farm equipment manufacturing', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('DEERE'))]))
clues_the_war.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ONEAL', number: 49, clue: '"Shaq Vs." star', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ONEAL'))]))
clues_the_war.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'NATLS', number: 50, clue: 'Countrywide competiton: Abbr.', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('NATLS'))]))
clues_the_war.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'IGGY', number: 51, clue: 'Rapper Azalea or singer Pop', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('IGGY'))]))
clues_the_war.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'OGRE', number: 52, clue: 'Fairy tale a-hole', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('OGRE'))]))
clues_the_war.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'GAZE', number: 53, clue: 'Scrutiny', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('GAZE'))]))
clues_the_war.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'XENA', number: 54, clue: 'The Warrior Princess', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('XENA'))]))
clues_the_war.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'XBOX', number: 54, clue: 'PlayStation alternative', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('XBOX'))]))
clues_the_war.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ELL', number: 55, clue: 'Building wing', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('ELL'))]))
clues_the_war.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'SQUASCABEET', number: 56, clue: 'Area units', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('SQUASCABEET'))]))
clues_the_war.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'SLC', number: 56, clue: 'Utah\'s capital, initially', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('SLC'))]))
clues_the_war.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'QUA', number: 57, clue: 'Sine ___ non', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('QUA'))]))
clues_the_war.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'AMI', number: 58, clue: '"___ Blue?"', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AMI'))]))
clues_the_war.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NEE', number: 59, clue: 'Louise Jefferson, ___ Mills', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('NEE'))]))
clues_the_war.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'LUTZ', number: 60, clue: 'Eponymous skater Alois', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('LUTZ'))]))
clues_the_war.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'AMORAL', number: 61, clue: 'Lacking ethical principles', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('AMORAL'))]))
clues_the_war.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DSS', number: 62, clue: 'Org. that accommodates students with learning impediments', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('DSS'))]))
clues_the_war.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'CASE', number: 63, clue: 'Detective\'s pursuit', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('CASE'))]))
clues_the_war.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'PIXELS', number: 64, clue: 'You\'re looking at \'em (note: if you printed this puzzle out, go look at your computer, or this will be a really dumb clue)', :solvables => [Solvable.create(word_type: 'answer', word: Word.find_or_create_by_grid_text('PIXELS'))]))
instructions = 'The contest answer is a two word phrase.'
explanation = '<MA>REPLACEMENT REF</MA><TEXT>Each theme answer is formed by replacing the letters REF with SCAB. This puzzle was released during the 2012 NFL referee lockout.</TEXT>'
Puzzle.create(title: 'THE WAR ON WHISTLEBLOWERS', grid: 'LIZZIE.AMAS.COT|ONEARM.MAXI.HUE|SUSCABOOTED.IBM|ESTH.EPIC..HELP|RES.DRE.HASAFIT|...FISCABIGHTER|BTEAM..RODS.ATE|OHNO.ALEXA.ZITS|YET.CMON..MINES|FEATUSCABILM...|RANAMOK.ACK.DON|IGGY..OGRE.XENA|ELL.SQUASCABEET|NEE.LUTZ.AMORAL|DSS.CASE.PIXELS', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2012-10-9', entries: clues_the_war, instructions: instructions, explanation: explanation, puzzle_type: 'meta')
