clues_themeless5 = Array.new
clues_themeless5.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CAMPS', number: 1, clue: 'Has an in-tents experience?'))
clues_themeless5.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CARBS', number: 1, clue: 'Atkins no-no'))
clues_themeless5.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AREAT', number: 2, clue: 'Attend'))
clues_themeless5.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MENSA', number: 3, clue: 'Its logo is a three-legged table'))
clues_themeless5.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PETERPAULRUBENS', number: 4, clue: '"The Judgement of Paris" painter'))
clues_themeless5.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SLAB', number: 5, clue: 'Big piece of meat'))
clues_themeless5.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'SBUX', number: 6, clue: 'Coffee chain\'s stock market symbol'))
clues_themeless5.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SCALAR', number: 6, clue: 'Vector multiplier (anagram of RASCAL)'))
clues_themeless5.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BALLROOMDANCING', number: 7, clue: 'Subject of jive talk?'))
clues_themeless5.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'USED', number: 8, clue: 'Not new'))
clues_themeless5.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'XAXIS', number: 9, clue: 'Horizontal graph line'))
clues_themeless5.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ATOB', number: 10, clue: 'First volume of an encyclopedia, back when they were made with paper and you had to buy them'))
clues_themeless5.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ANIMATEDFEATURE', number: 10, clue: '"Brave," for one'))
clues_themeless5.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TODO', number: 11, clue: 'List heading'))
clues_themeless5.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OVEN', number: 12, clue: 'Easy-Bake ___'))
clues_themeless5.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BARD', number: 13, clue: 'Shakespeare, with "the"'))
clues_themeless5.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AREEL', number: 14, clue: 'Spinning'))
clues_themeless5.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'CASA', number: 15, clue: '"Mi ___ es su ___!"'))
clues_themeless5.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'NOVA', number: 16, clue: 'Salmon variety named for a Canadian province'))
clues_themeless5.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RENTA', number: 17, clue: '&#195;scar Aristides de la ___ Fiallo'))
clues_themeless5.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'ALEXRIDER', number: 18, clue: 'Teen spy in a series of young adult novels'))
clues_themeless5.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'RAPS', number: 19, clue: 'Pitbull sounds'))
clues_themeless5.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BASEBALLDIAMOND', number: 20, clue: 'Red zone?'))
clues_themeless5.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'ABRADE', number: 21, clue: 'Wear away'))
clues_themeless5.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'STAR', number: 22, clue: 'Ebert\'s rating unit ... or what Ebert got on the Hollywood Walk of Fame'))
clues_themeless5.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'BAR', number: 23, clue: 'Cosmo headquarters?'))
clues_themeless5.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'SPA', number: 24, clue: 'Facial place'))
clues_themeless5.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'PARROT', number: 25, clue: 'Repetitive squawker'))
clues_themeless5.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ADS', number: 26, clue: 'Banner annoyances'))
clues_themeless5.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'TAB', number: 27, clue: 'Soda mostly replaced by Diet Coke'))
clues_themeless5.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'STAFF', number: 28, clue: 'Workers'))
clues_themeless5.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'ATOI', number: 29, clue: 'Tours "yours"'))
clues_themeless5.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'FARR', number: 30, clue: 'Jamie who played a cross-dressing corporal'))
clues_themeless5.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'FLEE', number: 31, clue: 'Leg it'))
clues_themeless5.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'RAMADA', number: 32, clue: 'Hotel chain that becomes a naval fleet if you switch its first two letters'))
clues_themeless5.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'RAYS', number: 32, clue: 'Tanner\'s catch'))
clues_themeless5.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ALAN', number: 33, clue: 'Rickman of "Quigley Down Under"'))
clues_themeless5.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'MBWA', number: 34, clue: 'Business technique involving perambulation: Abbr. (hidden in DUMBWAITER)'))
clues_themeless5.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'OAF', number: 35, clue: 'Inept one'))
clues_themeless5.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'FLORAL', number: 36, clue: 'Like some dress patterns'))
clues_themeless5.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ETAL', number: 37, clue: '"...and a bunch of people who aren\'t important enough to be listed by name": Abbr.'))
clues_themeless5.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ALBUSDUMBLEDORE', number: 38, clue: 'He says "It is our choices, Harry, that show what we truly are, far more than our abilities"'))
clues_themeless5.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'UNI', number: 39, clue: 'Sex tip?'))
clues_themeless5.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ENE', number: 40, clue: 'WSW opposite'))
clues_themeless5.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'YAWL', number: 41, clue: 'Boat that sounds like a southern pronoun'))
clues_themeless5.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'END', number: 42, clue: 'Aim'))
clues_themeless5.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'ONFIRE', number: 43, clue: 'Lit'))
clues_themeless5.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SNARL', number: 44, clue: 'Say rudely'))
clues_themeless5.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'LOLZ', number: 45, clue: 'Laughter, in leetspeak'))
clues_themeless5.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'IAGREE', number: 46, clue: '"Amen!"'))
clues_themeless5.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'GAUZES', number: 47, clue: 'Some surgical dressings'))
clues_themeless5.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'UOF', number: 48, clue: 'Wds. preceding a state in some college names'))
clues_themeless5.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'FEWER', number: 49, clue: 'Word often conflated with "less," annoying the hell out of prescriptivists'))
clues_themeless5.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'NAA', number: 50, clue: 'Initials of the first man to walk on the moon'))
clues_themeless5.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'AJAX', number: 51, clue: 'Household cleaning product'))
clues_themeless5.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'JUBAL', number: 52, clue: 'General Early nicknamed "Bad Old Man" by Robert E. Lee'))
clues_themeless5.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ARENA', number: 53, clue: 'Stadium'))
clues_themeless5.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'XEROX', number: 54, clue: 'Tissue : kleenex :: photocopy : ___'))
clues_themeless5.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MARBLESCULPTURE', number: 55, clue: '"Apollo Belvedere" or "Laoco&#246;n and His Sons"'))
clues_themeless5.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'MCCI', number: 55, clue: '1201'))
clues_themeless5.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AHAB', number: 56, clue: 'Peck role'))
clues_themeless5.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'REAM', number: 57, clue: '"The Office" unit'))
clues_themeless5.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'SHIA', number: 58, clue: 'LaBeouf who\'s la-beefing (yikes) with Alec Baldwin'))
clues_themeless5.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'PTDR', number: 59, clue: 'French chatroom initialism that means "broken from laughing" (hidden in CONCEPT DRIVEN)'))
clues_themeless5.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CHEEZWHIZ', number: 60, clue: 'Bright orange spread that can be used as a stain remover'))
clues_themeless5.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'TUBER', number: 61, clue: 'Manioc, e.g.'))
clues_themeless5.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CAAN', number: 62, clue: 'Scott of "Hawaii Five-0"'))
clues_themeless5.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EINE', number: 63, clue: 'German one'))
clues_themeless5.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'DRANO', number: 64, clue: 'Household cleaning product'))
clues_themeless5.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'IBMS', number: 65, clue: 'Some PCs'))
clues_themeless5.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'RAGS', number: 66, clue: 'Symbolic attire in the beginning of an Alger-esque narrative'))
clues_themeless5.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'RELAX', number: 67, clue: '"Take a chill pill!"'))
Puzzle.create(title: 'THEMELESS FIVE', grid: 'CAMPS.SBUX.ATOB|AREEL.CASA.NOVA|RENTA.ALEXRIDER|BASEBALLDIAMOND|STAR.BAR.SPA...|...PARROT.STAFF|RAMADA.OAF.ETAL|ALBUSDUMBLEDORE|YAWL.END.ONFIRE|SNARL.IAGREE...|...UOF.NAA.AJAX|MARBLESCULPTURE|CHEEZWHIZ.TUBER|CAAN.EINE.DRANO|IBMS.RAGS.RELAX', :constructors => Constructor.where(:name => 'Erik Agard'), :sources => Source.where(:name => 'Glutton For Pun'), publication_date: '2013-4-16', entries: clues_themeless5, puzzle_type: 'freestyle')