clues_A_Substitution_CR_7_6_06 = Array.new
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PGA', number: 1, clue: 'Geoff Ogilvy\'s org.'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PRIMES', number: 1, clue: 'Prepares to paint'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'GENEVA', number: 2, clue: 'Conventions concerned with wartime conduct'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ADAGES', number: 3, clue: 'Saws'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'CHI', number: 4, clue: '___-Town'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'COOLS', number: 4, clue: 'Sits on a sill, say'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'HALO', number: 5, clue: 'Circle of heaven'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ITEM', number: 6, clue: 'Tabloid tidbit'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'SLY', number: 7, clue: 'Rocky player, in tabloids'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SAHIB', number: 7, clue: 'Hindi "master"'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LYONS', number: 8, clue: 'City in Beaujolais country'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'YETI', number: 9, clue: 'Nepalese terrorist'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'QED', number: 10, clue: 'Proof ender'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'QUACKERY', number: 10, clue: 'Penis enlargement products, e.g.'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'EEK', number: 11, clue: 'It\'s a scream'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DYE', number: 12, clue: 'Blacken or redden, often'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'REDCOAT', number: 13, clue: 'Lobsterback'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'CHANEL', number: 14, clue: 'No. 5 company'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'AYE', number: 15, clue: 'Limey\'s 65-Across'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'UEY', number: 16, clue: '180, slangily'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'INAHOLE', number: 17, clue: 'Down at the casino'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'HOTSAKE', number: 18, clue: 'Sushi go-with'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'SATIE', number: 19, clue: 'Composer from the French avant-garde'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MEGALOMEINIAC', number: 20, clue: 'Ardent fan of stir-fried noodles?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 4, col: 8, dir: 'Down', answer: 'ETTA', number: 21, clue: 'Singer James'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'EVENS', number: 22, clue: 'They\'re at odds with odds'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'TBS', number: 23, clue: '"Dinner and a Movie" channel'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'TKTS', number: 24, clue: 'Discount theater letters in NYC'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'TIME', number: 25, clue: 'You might make it for a friend in need'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'SASH', number: 26, clue: 'Beauty pageant accessory'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SASE', number: 27, clue: 'Encl. with an RSVP'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'VET', number: 28, clue: 'Boxer\'s doc'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'VIII', number: 28, clue: 'Roman 2x4?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'EMIT', number: 29, clue: 'Give off'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'EIEIA', number: 30, clue: 'Alternate title for this puzzle'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'ETNA', number: 30, clue: '2005 eruptor'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'LEIMANSTERMS', number: 31, clue: 'Aloha and luau, e.g.?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'EWES', number: 32, clue: 'Fold females'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'NEON', number: 33, clue: 'Gas at a diner'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'SENT', number: 34, clue: 'En route'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ARK', number: 35, clue: 'Torah spot'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'ASKS', number: 35, clue: 'Charges, as a retailer'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'REEK', number: 36, clue: 'Stench'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'KNEEPADS', number: 37, clue: 'Rollerblader\'s safety precaution'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'WII', number: 38, clue: 'Nintendo console slated for fall 2006'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'EEN', number: 39, clue: 'Poetic contraction'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'YEH', number: 40, clue: 'Casual affirmation'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SENSEITIONAL', number: 41, clue: 'Great, as Mr. Miyagi?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'SLEET', number: 42, clue: 'Hazardous forecast'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ITAL', number: 43, clue: 'The U.S. tied them in the first round of the 2006 World Cup: Abbr.'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'LABOUR', number: 44, clue: 'Party in London'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'KEELS', number: 45, clue: 'Topples (over)'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'TNT', number: 46, clue: 'Big bang creator'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'ACRE', number: 47, clue: 'Plot element?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'COUNTS', number: 48, clue: 'Goes from 0 to 60?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'RENDER', number: 49, clue: 'Melt down, as fat'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ESTADO', number: 50, clue: 'S&#227;o Paulo, for one'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SKEE', number: 51, clue: '___-ball'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'SPA', number: 52, clue: 'Where to find sweaters'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'SPIKE', number: 52, clue: 'Sharp rise'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'PATSY', number: 53, clue: 'Fall guy'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'OBOES', number: 54, clue: 'Instruments played by Yusef Lateef and Sufjan Stevens'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'OCTET', number: 54, clue: 'Ska band, perhaps'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'PEIPALACCOUNT', number: 55, clue: 'Deposit spot for I.M.\'s crony?'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'IZOD', number: 56, clue: 'Tenniswear brand'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'ARAB', number: 57, clue: 'Emirate resident'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'COLA', number: 58, clue: 'Soft quaff'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'WHATZIT', number: 59, clue: 'Thingee (Var.)'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'WHY', number: 59, clue: 'Kid\'s inquiry'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'HOE', number: 60, clue: 'Weed'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'ROTUNDA', number: 61, clue: 'Capitol feature'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'HOD', number: 62, clue: 'Coal scuttle'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'OKS', number: 63, clue: 'Greenlights'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'ALERTED', number: 64, clue: 'On guard'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'YES', number: 65, clue: 'Landlubber\'s 15-Across'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'DEY', number: 66, clue: 'Susan of "L.A. Law"'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'BAT', number: 67, clue: 'Cub\'s club'))
clues_A_Substitution_CR_7_6_06.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SRO', number: 68, clue: 'Sellout sign'))
Puzzle.create(title: 'A Substitution', grid: 'PGA.CHI.SLY.QED|REDCOAT.AYE.UEY|INAHOLE.HOTSAKE|MEGALOMEINIAC..|EVENS..TBS.TKTS|SASE.VET..EIEIA|...LEIMANSTERMS|ARK.WII.EEN.YEH|SENSEITIONAL...|KEELS..TNT.ACRE|SKEE.SPA..OBOES|..PEIPALACCOUNT|WHATZIT.ROTUNDA|HOD.OKS.ALERTED|YES.DEY.BAT.SRO', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/7/6', entries: clues_A_Substitution_CR_7_6_06)
