clues_Buzzwords_VV_2_21_06 = Array.new
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ONEUP', number: 1, clue: 'Early Ping-Pong tie'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ONRAMPS', number: 1, clue: 'Interstate entrances'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'NEUTRAL', number: 2, clue: 'Like Switzerland, Laos, and Costa Rica'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'EURASIA', number: 3, clue: 'Silk Road supercontinent'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'URAL', number: 4, clue: 'River to the Caspian'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'POLO', number: 5, clue: 'Shirt style'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'APB', number: 6, clue: 'P.D. call'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ADDSALT', number: 6, clue: 'Simple seasoning instruction'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'PER', number: 7, clue: 'Part of WPM'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BLANKET', number: 8, clue: 'Cover, as snow'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'BLESS', number: 9, clue: 'Post-sneeze word'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'BBQS', number: 9, clue: 'July 4th events, briefly'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'LEU', number: 10, clue: 'Romanian currency'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ELECTEE', number: 11, clue: 'Seat winner'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SLEPTIN', number: 12, clue: 'Rose late'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SENIORS', number: 13, clue: 'Graduating class'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NEURO', number: 14, clue: 'Logical beginning?'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'DEL', number: 15, clue: 'El Museo ___ Barrio'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'BELLE', number: 16, clue: 'Southern gal'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RURAL', number: 17, clue: 'Like the sticks'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'DRAGQUEEN', number: 18, clue: 'Divine, notably'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'GEARUP', number: 19, clue: 'Prepare for action'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ATALOSS', number: 20, clue: 'Baffled'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'SKI', number: 21, clue: 'Slalom'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'NES', number: 22, clue: '8-bit giant, briefly'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'CPI', number: 23, clue: 'Cost-of-living stat.'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'MRS', number: 24, clue: 'Ed and Magoo'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'KAFKA', number: 25, clue: '"The Trial" author'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'FLU', number: 26, clue: 'Avian menace'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'OTTO', number: 27, clue: '"Simpsons" driver'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'OHYOKO', number: 27, clue: 'Ode to Ono'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PAINKILLER', number: 28, clue: 'Opiate, e.g.'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'NTESTS', number: 29, clue: 'Bikini blasts'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'KEN', number: 30, clue: '"Jeopardy!" phenomenon Jennings'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'HEIR', number: 31, clue: 'Will name'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SLATE', number: 32, clue: 'Salon alternative'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'TUTU', number: 33, clue: 'Dainty attire'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'YENS', number: 34, clue: 'Hankerings'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'END', number: 35, clue: 'Terminal'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'DAPPER', number: 36, clue: 'Spiffy-looking'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'PAO', number: 37, clue: 'Kung ___ chicken'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ASH', number: 38, clue: 'Tap a butt'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EPPS', number: 39, clue: '"House" actor Omar'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'ENCODED', number: 39, clue: 'Ciphered'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'PETNAME', number: 40, clue: 'Sweetie, say'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'PARTYON', number: 41, clue: '"Wayne\'s World" catchphrase'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ALMA', number: 42, clue: '___ mater'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'LALAKER', number: 43, clue: 'Kobe, e.g.'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'MBA', number: 44, clue: 'Dubya\'s degree'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'ALTERED', number: 45, clue: 'Not the same'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'SKITS', number: 46, clue: 'SNL bits'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'INSULIN', number: 47, clue: 'Diabetic\'s dose'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'TEUTONS', number: 48, clue: 'Ancient Germanic tribe'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'SYNERGY', number: 49, clue: 'Cross-promotion, to a marketer'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'NEAT', number: 50, clue: 'In order'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'PABLOHONEY', number: 51, clue: 'Radiohead album with "Creep"'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'OON', number: 52, clue: 'Drag or ball suffix'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CTRS', number: 53, clue: 'Javits and Lincoln: Abbr.'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'PLATO', number: 54, clue: 'Old republican?'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'SUN', number: 55, clue: 'New York broadsheet'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ONT', number: 56, clue: 'Windsor\'s prov.'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'TEA', number: 57, clue: 'Bagged leaves'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'TOYS', number: 57, clue: 'Playthings'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ENROUTE', number: 58, clue: 'Getting there'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'RASP', number: 59, clue: 'Rough sound'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'OLLA', number: 60, clue: 'Dish cooked in a pot'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DAYWORKER', number: 61, clue: 'Ad hoc employee'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'WRY', number: 62, clue: 'Like some humor'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ERA', number: 63, clue: 'Time of note'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'ALLOR', number: 64, clue: 'Words before nothing?'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EMORY', number: 65, clue: 'Atlanta university'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ERE', number: 66, clue: 'Prior to'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'SLING', number: 67, clue: 'David\'s weapon'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DENYS', number: 68, clue: 'Patron saint of France'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'RAD', number: 69, clue: 'Super cool'))
clues_Buzzwords_VV_2_21_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'PANSY', number: 70, clue: 'Velvety violet'))
Puzzle.create(title: 'Buzzwords', grid: 'ONEUP.APB.BLESS|NEURO.DEL.BELLE|RURAL.DRAGQUEEN|ATALOSS.NES.CPI|MRS..KAFKA.OTTO|PAINKILLER.HEIR|SLATE.TUTU.YENS|...END...PAO...|EPPS.ALMA.SKITS|NEAT.PABLOHONEY|CTRS.PLATO..SUN|ONT.TEA.ENROUTE|DAYWORKER.ALLOR|EMORY.ERE.SLING|DENYS.RAD.PANSY', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/2/21', entries: clues_Buzzwords_VV_2_21_06)
