clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06 = Array.new
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MAMA', number: 1, clue: 'Kid\'s cry'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MAKEWAY', number: 1, clue: 'Step aside'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AVARICE', number: 2, clue: 'It\'s a sin'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MOZILLA', number: 3, clue: 'Browser maker'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ANA', number: 4, clue: 'California Santa'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'AMASS', number: 5, clue: 'Stockpile'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'AXHANDLE', number: 5, clue: 'Bunyan\'s grip'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MASK', number: 6, clue: 'Conceal'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ACT', number: 7, clue: 'Do some lines?'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'STALE', number: 8, clue: 'Told and retold, perhaps'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SONATA', number: 9, clue: 'Hyundai model'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'TWIN', number: 10, clue: 'The New Pornographers\' "___ Cinema"'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'THESILKROAD', number: 10, clue: 'Ancient route through 17-Across'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'WAGONER', number: 11, clue: 'Oregon Trail driver'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ING', number: 12, clue: 'Gerund maker'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NGO', number: 13, clue: 'Gp. interested in sustainable development, perhaps'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AVON', number: 14, clue: 'Type of lady'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'XACTO', number: 15, clue: 'Hobby knife'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'HANG', number: 16, clue: 'Chill'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'KAZAKHSTAN', number: 17, clue: 'Place in entertainment news, and the subject of this puzzle'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'KOO', number: 18, clue: '"Rock and Roll, Hoochie ____"'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'EGGO', number: 19, clue: 'Brand in the freezer'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ERI', number: 20, clue: 'Verdi\'s "___ tu"'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'OAK', number: 21, clue: 'Hard wood'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'LASSO', number: 22, clue: 'Western projectile'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'SARAH', number: 23, clue: 'Comedian Silverman'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'WILSON', number: 24, clue: 'Late August?'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'SUNNIMUSLIM', number: 25, clue: 'Like more than half the population of 17-Across'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'RETAINER', number: 26, clue: 'Follow-up to braces, often'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RXS', number: 26, clue: 'Dr.\'s orders'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'ENO', number: 27, clue: 'Roger or Brian'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'REN', number: 28, clue: 'Animated chihuahua'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ACLU', number: 29, clue: 'Defender of some unpopular causes: Abbr.'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'DMX', number: 30, clue: '"Year of the Dog...Again" rapper'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'MACS', number: 31, clue: 'They\'re big at McDonald\'s'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'ARLENE', number: 32, clue: 'Garfield\'s girl'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'YEAN', number: 33, clue: 'Bear young, in the barnyard'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'LAST', number: 34, clue: 'In the cellar'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'TBAR', number: 35, clue: 'Lift up a mountain'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'AKRON', number: 36, clue: 'Hometown of the Black Keys'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'NSEC', number: 37, clue: 'Tiny time period: Abbr.'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SNAPS', number: 38, clue: 'Goes ape'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'BOHR', number: 39, clue: 'Nuclear Nobelist'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'OXYMORON', number: 40, clue: 'Elevated subway, e.g.'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ASTIN', number: 41, clue: 'Sean of "The Lord of the Rings"'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'ALP', number: 41, clue: 'Matterhorn, e.g.'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'SLO', number: 42, clue: '___-mo'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'TAPIOCA', number: 43, clue: 'Bubble tea balls'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'STAX', number: 44, clue: 'Memphis soul label'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'TDS', number: 45, clue: '6-pointers, briefly'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ORSO', number: 46, clue: 'Approximately'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'REDEYES', number: 47, clue: 'Pillow flights?'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SOLDERS', number: 48, clue: 'Joins with an iron'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'ONEOVER', number: 49, clue: 'Near par'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'LLAMAS', number: 50, clue: 'Incan conveyances'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'SAUNAS', number: 51, clue: 'Steamy places'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'DRY', number: 52, clue: 'Like some counties'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'AEON', number: 53, clue: 'Forever, seemingly'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'POPUPADS', number: 54, clue: 'Surfer\'s annoyance'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'DEALT', number: 55, clue: 'Gave a hand'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'MEDDLE', number: 56, clue: 'Interfere'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'EBB', number: 57, clue: 'Withdraw'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'ISSUE', number: 58, clue: 'Debate topic'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'BOB', number: 59, clue: 'The Builder of TV'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'BARR', number: 59, clue: 'Roseanne, once'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'EDO', number: 60, clue: 'Tokyo, once'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'TOOL', number: 61, clue: 'Manipulated person'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'TLC', number: 61, clue: 'Trio that once toured with MC Hammer'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'OUR', number: 62, clue: 'Not in ___ Name (anti-war protest group)'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'NAZARBAYEV', number: 63, clue: 'President of 17-Across'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ZEE', number: 64, clue: 'Unit of sleep?'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'APU', number: 65, clue: 'Hank Azaria character'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LUCI', number: 66, clue: 'An LBJ daughter'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ALERO', number: 67, clue: 'Old Olds'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'PERE', number: 68, clue: 'Homme de famille'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'CRAM', number: 69, clue: 'Stuff'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'STERN', number: 70, clue: 'Forbidding'))
clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'USSR', number: 71, clue: 'Outdated globe letters'))
Puzzle.create(title: 'Cultural Learnings for Make Benefit American Crossword Solver', grid: 'MAMA.AMASS.TWIN|AVON.XACTO.HANG|KAZAKHSTAN.EGGO|ERI.OAK.LASSO..|WILSON.RETAINER|ACLU.DMX.ARLENE|YEAN.LAST.AKRON|...NSEC.BOHR...|ASTIN.STAX.ORSO|LLAMAS.DRY.AEON|POPUPADS.MEDDLE|..ISSUE.BOB.EDO|TOOL.NAZARBAYEV|LUCI.ALERO.PERE|CRAM.STERN.USSR', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/11/2', entries: clues_Cultural_Learnings_for_Make_Benefit_American_Crossword_Solver_CR_11_2_06)
