clues_Dually_Noted_CR_11_16_06 = Array.new
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JINX', number: 1, clue: 'Forbid from talking, in a way'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JOJO', number: 1, clue: 'Name in the Beatles\' "Get Back"'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IRAN', number: 2, clue: 'Vice-chair of the UN Disarmament Commission'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NEVE', number: 3, clue: 'She played Julia on "Party of Five"'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'XSANDOS', number: 4, clue: 'Playbook figures'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'PLATH', number: 5, clue: 'Title role for Paltrow in 2003'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'PCP', number: 5, clue: 'Angel dust'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LAP', number: 6, clue: 'Cat nap spot'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ASL', number: 7, clue: 'Digital interface?: Abbr.'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TIEGS', number: 8, clue: 'Cover girl Cheryl'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'HOTROD', number: 9, clue: 'Modified wheels'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ZAGS', number: 10, clue: 'Veers sharply'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ZOMBIFY', number: 10, clue: 'Make undead'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ADOBE', number: 11, clue: 'Acrobat maker'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'GOTAT', number: 12, clue: 'Insinuated'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SMOG', number: 13, clue: 'Urban haze'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ORES', number: 14, clue: 'Metal deposits'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'CASIO', number: 15, clue: 'Manufacturer of cheap keyboards'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ODOM', number: 16, clue: 'Lakers\' star Lamar'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'JAVAAPPLET', number: 17, clue: 'Web program often used for games'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ADAM', number: 18, clue: 'Horovitz or Yauch'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'MOTO', number: 19, clue: '"Hello, ___" (cellphone ad catchphrase)'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ONEND', number: 20, clue: 'Continually'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'GRABBAG', number: 21, clue: 'Mishmash'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'AVERT', number: 22, clue: 'Deflect'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'DAZS', number: 23, clue: 'H&#228;agen-___'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ZIMA', number: 24, clue: 'Smirnoff Ice alternative'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'SCADS', number: 25, clue: 'Scores'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'SOVIET', number: 26, clue: 'Red, once upon a time'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'DCCOMICS', number: 27, clue: 'Batman\'s publisher'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'DERN', number: 27, clue: '"Blue Velvet" star'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CREE', number: 28, clue: 'Manitoba native'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'CASH', number: 29, clue: 'Bucks'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'SIDEB', number: 30, clue: 'Tape half'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'DEF', number: 31, clue: '___ Jam'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ERAS', number: 32, clue: 'Pitcher\'s figs.'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'MAID', number: 33, clue: 'Housekeeper'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'DIALS', number: 34, clue: 'Pushes someone\'s buttons?'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'RYDER', number: 35, clue: 'Word on some yellow trucks'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'DALY', number: 36, clue: '"Last Call" host'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'EPEE', number: 37, clue: 'Sport with masks'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'RUED', number: 38, clue: 'Regretted'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RES', number: 39, clue: 'Hi-___'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'FADDIET', number: 40, clue: 'South Beach, for one'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'FUNGI', number: 40, clue: 'Shiitakes and oysters'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ETUI', number: 41, clue: 'Toiletries case'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'APU', number: 42, clue: 'Springfield dad'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'NEHRU', number: 43, clue: 'Jacket type'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'REDFLAG', number: 44, clue: 'Warning sign'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'SEAT', number: 45, clue: 'Usher\'s offering'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'GLEE', number: 46, clue: 'Elation'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'GEORGEW', number: 46, clue: 'Figure with less than 795 days, 7 hrs., 40 mins. left in office'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ENV', number: 47, clue: 'Oscar opening: Abbr.'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'VELCRO', number: 48, clue: 'Strap-on stuff'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'BLUEEYED', number: 49, clue: 'Like some soul'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ELAN', number: 50, clue: 'Flair'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'BADGER', number: 51, clue: 'Wisconsin athlete'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'BIMBO', number: 51, clue: 'Unthinking, superficial sort'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'AFIRE', number: 52, clue: 'Flaming'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'REHAB', number: 53, clue: 'Spot for many a celeb'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SILO', number: 54, clue: 'Storage area'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'GIFFILE', number: 55, clue: 'Certain computer picture type'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'GEAR', number: 55, clue: 'Neutral, for one'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'AROMA', number: 56, clue: 'Bakery advertisement, in a way'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'OGLE', number: 57, clue: 'Gawk at'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'MULE', number: 58, clue: 'Half ass?'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AMEN', number: 59, clue: 'Church signoff'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EMIL', number: 60, clue: 'Disney\'s "____ and the Detectives"'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'CHEWINGGUM', number: 61, clue: 'Orbit or Bazooka'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'EDE', number: 62, clue: 'Eastern Dutch city'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'WAY', number: 63, clue: 'Knack'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'IRS', number: 64, clue: 'Org. whose headquarters flooded last June'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ABRA', number: 65, clue: 'Start of a spell?'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'RADAR', number: 66, clue: '"M*A*S*H*" palindrome'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ELLE', number: 67, clue: 'Magazine with a "First Look" feature'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ROEG', number: 68, clue: '"The Man Who Fell to Earth" director Nicolas'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'OBEYS', number: 69, clue: 'Stays in line'))
clues_Dually_Noted_CR_11_16_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'WEEN', number: 70, clue: 'Sophomoric rock band since 1984'))
Puzzle.create(title: 'Dually Noted', grid: 'JINX.PLATH.ZAGS|ORES.CASIO.ODOM|JAVAAPPLET.MOTO|ONEND...GRABBAG|...DAZS.SOVIET.|DCCOMICS.DEF...|ERAS.MAID.RYDER|RES.FADDIET.APU|NEHRU.SEAT.GLEE|...ENV.BLUEEYED|.BADGER.SILO...|GIFFILE...AROMA|EMIL.CHEWINGGUM|ABRA.RADAR.ELLE|ROEG.OBEYS.WEEN', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/11/16', entries: clues_Dually_Noted_CR_11_16_06)
