clues_Irish_Migration_CR_6_1_06 = Array.new
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AKON', number: 1, clue: 'Senegalese rapper on Young Jeezy\'s "Soul Survivor"'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ALI', number: 1, clue: 'Undefeated boxer, or her father'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'KIN', number: 2, clue: 'Relatives'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'OFF', number: 3, clue: 'Camping spray'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'NEOGENE', number: 4, clue: '23 million year stretch during the Cenozoic era'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'WHOS', number: 5, clue: '"___ the Boss?"'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WHIM', number: 5, clue: 'Passing fancy'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HOKE', number: 6, clue: 'Nonsense'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OREO', number: 7, clue: 'High-contrast cookie'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SNAFU', number: 8, clue: 'Impolite army acronym meaning "a big mess"'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'DECOR', number: 9, clue: 'Design for living'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DEANIAC', number: 9, clue: 'Certain 2004 Democratic enthusiast'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ELECTRA', number: 10, clue: 'Rodman\'s ex'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CASH', number: 11, clue: 'It may be petty in the office'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OTOE', number: 12, clue: 'Plains Indian'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'REPS', number: 13, clue: 'Bodybuilder\'s count'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LIFE', number: 14, clue: 'Permanent sentence?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HORN', number: 15, clue: 'What someone with road rage might lean on'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'ELATE', number: 16, clue: 'Fill with joy'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'INFO', number: 17, clue: 'Details'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'IKEA', number: 18, clue: '"Democratic design" retailer'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'AESOP', number: 19, clue: 'Fabulous Greek'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'GAMEOFINCHES', number: 20, clue: 'Irish bird-watching?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ARCO', number: 21, clue: 'Sacramento arena'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ING', number: 22, clue: 'Gerund letters'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ACHER', number: 23, clue: 'BenGay user, perhaps'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'ATREST', number: 23, clue: 'Idle'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'CRUSTY', number: 24, clue: 'Like a baguette'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'HALTER', number: 25, clue: 'Top type'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'UNIT', number: 26, clue: 'A mile or a minute'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TRANCES', number: 27, clue: 'Religious states?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'EFF', number: 28, clue: 'Fire starter?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'SLAW', number: 29, clue: 'Picnic side'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'GARISH', number: 30, clue: 'Tasteless and showy'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'INSIDE', number: 31, clue: 'Away from the elements'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'STREEP', number: 32, clue: 'Actress with a record 13 Oscar nominations'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'HISSAT', number: 33, clue: 'Intimidate, as a feline'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'RULEOFLAW', number: 34, clue: 'Irish tyranny?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'AXE', number: 35, clue: 'Let go'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'WEBB', number: 36, clue: 'Friday portrayer'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'CANTI', number: 37, clue: '"Pleeeease?"'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'EST', number: 38, clue: 'Guessing fig.'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'FAXED', number: 39, clue: 'Sent without postage'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'DOA', number: 40, clue: 'Somber ER pronouncement'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SRS', number: 41, clue: 'AARP members'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'STEPS', number: 42, clue: 'They may be taken down when going out'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'POLONIA', number: 43, clue: 'Certain Eastern European diaspora'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SNOOKER', number: 44, clue: 'English billiards game'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'WEBOFLIES', number: 45, clue: 'Irish spider\'s windfall?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'FDIC', number: 46, clue: 'Bank insuring letters'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'LINKUPS', number: 47, clue: 'Connections'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'TYRONE', number: 48, clue: 'Northern Irish county'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ESL', number: 49, clue: 'Class for a new American: Abbr.'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'BADIDEA', number: 50, clue: 'Sticking a fork in the toaster, e.g.'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'LOST', number: 51, clue: 'ABC program filmed in Hawaii'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'TOSCA', number: 52, clue: 'Puccini heroine'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'INEPT', number: 53, clue: 'Bumbling'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SCHOOLOFROCK', number: 54, clue: 'Irish seminary?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SCAR', number: 54, clue: 'Wound souvenir'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'CREE', number: 55, clue: 'Canadian native'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'HURT', number: 56, clue: 'On the DL, perhaps'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'FEEL', number: 57, clue: 'Sense'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'RACE', number: 58, clue: 'Piece of a meet'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'OLES', number: 59, clue: 'F&#250;tbol cheers'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CRUNK', number: 60, clue: 'Stoned and inebriated, slangily'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'SEAL', number: 61, clue: 'Circus barker'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'UDON', number: 62, clue: 'Soba alternative'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'DUE', number: 63, clue: 'Mom\'s date?'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'ORC', number: 64, clue: 'Tolkien beast'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'NET', number: 65, clue: 'Lunch lady\'s hair covering'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AERIE', number: 66, clue: 'Nest on a cliff'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'CECE', number: 67, clue: 'Gospel singer Winans'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'PURE', number: 68, clue: '100%'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RETAR', number: 69, clue: 'Pave over'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'ALES', number: 70, clue: 'Draft picks'))
clues_Irish_Migration_CR_6_1_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SECT', number: 71, clue: 'Certain spinoff'))
Puzzle.create(title: 'Irish Migration', grid: 'AKON.WHOS.DECOR|LIFE.HORN.ELATE|INFO.IKEA.AESOP|...GAMEOFINCHES|ACHER...UNIT...|TRANCES..GARISH|RULEOFLAW.CANTI|EST..FAXED..SRS|STEPS.WEBOFLIES|TYRONE..BADIDEA|...LOST...INEPT|SCHOOLOFROCK...|CRUNK.SEAL.UDON|AERIE.CECE.PURE|RETAR.ALES.SECT', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/6/1', entries: clues_Irish_Migration_CR_6_1_06)
