clues_Life_Lesson_VV_1_24_06 = Array.new
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AHEAD', number: 1, clue: 'Each'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ARTS', number: 1, clue: 'MFA part'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HOHO', number: 2, clue: 'Hostess treat'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'EDIT', number: 3, clue: 'Tweak'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AESOP', number: 4, clue: 'Man of morals'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DOH', number: 5, clue: '"Simpsons" cry'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ASA', number: 6, clue: 'Simile center'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALSACE', number: 6, clue: 'Historically-disputed French region'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SANIT', number: 7, clue: 'City dept. concerned with trash'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AGONIZES', number: 8, clue: 'Struggles, as over a decision'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'SIGHS', number: 9, clue: 'They may be let out in relief'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SUNTAN', number: 9, clue: 'Fire Island pick-up'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'INI', number: 10, clue: 'Pasta suffix'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'GINSU', number: 11, clue: 'Infomercial knife'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'HOJOS', number: 12, clue: 'Fast-disappearing roadside eateries'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SNAPE', number: 13, clue: 'Harry Potter\'s professor'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'RODEO', number: 14, clue: 'Drive in Los Angeles'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'LAG', number: 15, clue: 'Trail'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'UNION', number: 16, clue: 'Square in Manhattan'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'THISHASNO', number: 17, clue: 'Beginning of a hypothesis proposed by me in 51-Across'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'AMAN', number: 18, clue: 'To ___ (everyone)'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'NINJA', number: 19, clue: 'Assassin in black'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SOTO', number: 20, clue: 'Explorer Hernando De ___'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'MAINST', number: 21, clue: 'Center of Anytown, USA'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'SCALY', number: 22, clue: 'Dragonlike'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'SOP', number: 23, clue: 'Drench'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'PRACTICALUSE', number: 24, clue: 'Continuation of the hypothesis'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ROTI', number: 25, clue: 'Hindi bread'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'LETBE', number: 26, clue: 'Do not disturb'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'COP', number: 27, clue: 'Force member'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'CCCP', number: 27, clue: 'USSR, in Cyrillic'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OAHU', number: 28, clue: 'Pearl Harbor\'s island'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'PREZ', number: 29, clue: 'W, in tabloids'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'ONE', number: 30, clue: '1300 hours'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'ZANE', number: 31, clue: 'Billy of "Titanic"'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CARET', number: 32, clue: 'Insert sign'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'EMOTE', number: 33, clue: 'Overdo it'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'EEL', number: 34, clue: 'Unagi, at a sushi bar'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ELO', number: 34, clue: '70\'s rock band from Birmingham, for short'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'TTOP', number: 35, clue: 'Moonroof alternative'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'TOGA', number: 36, clue: 'Frat party outfit'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'OLIN', number: 37, clue: 'Lena of "Alias"'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'PSST', number: 38, clue: '"Yoo-hoo!"'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CHEMICALSYMBOLS', number: 39, clue: '"Elements" of the hypothesis, letter-wise'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'CIRCA', number: 40, clue: 'Approximately'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'APPETITE', number: 41, clue: 'It may get worked up'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'MARS', number: 42, clue: 'Candy name'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PUZO', number: 43, clue: '"The Godfather" author'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'IPO', number: 44, clue: 'NASDAQ debut'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'AEGIS', number: 45, clue: 'Patronage'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'TARP', number: 46, clue: 'It\'s saved for a rainy day'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ANDHOW', number: 47, clue: '"I\'ll say!"'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ERR', number: 48, clue: 'Be off'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ELNINO', number: 48, clue: 'Weird weather cause'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'RAGS', number: 49, clue: 'Tattered attire'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'ANT', number: 50, clue: 'Cooperative farm worker'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SCIENCECLASS', number: 51, clue: 'See 17- and 24-Across'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'SIDEB', number: 51, clue: 'Half an LP'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'CAINE', number: 52, clue: 'Captain Queeg\'s ship'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'INTEL', number: 53, clue: 'Processor producer'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'CITED', number: 54, clue: 'Given a ticket'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'STALL', number: 55, clue: 'Buy time'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'IAN', number: 56, clue: 'Bilbo\'s portrayer'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'DATING', number: 57, clue: 'Like Jay-Z and Beyonc&#233;'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'TEAM', number: 58, clue: 'Manager\'s company?'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ELLE', number: 59, clue: 'Glamour rival'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ASIS', number: 60, clue: 'Thrift store tag'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'MENS', number: 61, clue: 'Department with ties'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DITCH', number: 62, clue: 'Abandon'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'CRO', number: 63, clue: '___-Magnon'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'ITISFALSE', number: 64, clue: 'Given this puzzle\'s theme, conclusion about the hypothesis'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'FAB', number: 65, clue: 'Part of a "Queer Eye" nickname'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ENERO', number: 66, clue: 'It begins un a&#241;o'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'TEN', number: 67, clue: 'Metric base'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ALLIN', number: 68, clue: 'Bold poker bet'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'BELOW', number: 69, clue: 'Not on deck'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'EDO', number: 70, clue: 'Tokyo, during a shogunate'))
clues_Life_Lesson_VV_1_24_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'BLESS', number: 71, clue: 'First word after a sneeze, often'))
Puzzle.create(title: 'Life Lesson', grid: 'AHEAD.ASA.SIGHS|RODEO.LAG.UNION|THISHASNO.NINJA|SOTO.MAINST.SOP|...PRACTICALUSE|COP.ONE.ZANE...|CARET..EEL.TTOP|CHEMICALSYMBOLS|PUZO.IPO..AEGIS|...TARP.ERR.ANT|SCIENCECLASS...|IAN.DATING.TEAM|DITCH.ITISFALSE|ENERO.TEN.ALLIN|BELOW.EDO.BLESS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/1/24', entries: clues_Life_Lesson_VV_1_24_06)
