clues_Like_Lines_CR_6_22_06 = Array.new
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BARB', number: 1, clue: 'Cutting comment'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BONOBO', number: 1, clue: 'Chimpanzee that uses sex as a greeting'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARENAS', number: 2, clue: 'World Cup venues'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'REWIRE', number: 3, clue: 'Tinker with, as a robot'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'BOZO', number: 4, clue: 'Clown'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ABETS', number: 5, clue: 'Lends a hand, criminally'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'AGO', number: 5, clue: 'Erenow'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BECOOL', number: 6, clue: '"Chill . . ."'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EARS', number: 7, clue: 'Where some aids work'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TREX', number: 8, clue: 'Field Museum attraction'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SSW', number: 9, clue: 'Course heading: Abbr.'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SNCC', number: 10, clue: 'Group initially funded by the SCLC'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SPORE', number: 10, clue: 'Future mushroom'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'NOSERING', number: 11, clue: 'Popular piercing'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'COUSTEAU', number: 12, clue: 'French conservationist'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CHE', number: 13, clue: 'Subject of Steven Soderbergh\'s upcoming "Guerrilla"'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OREO', number: 14, clue: 'Crossword cookie'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'GEARS', number: 15, clue: 'Stick selections'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'POOH', number: 16, clue: 'Pal of Owl and Rabbit'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NEWZOOCREWTOSUE', number: 17, clue: '"The recent hires at Lincoln Park are planning to litigate"?'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ONEWAY', number: 18, clue: 'Type of street or ticket'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'TAUT', number: 19, clue: 'Fully drawn'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ONION', number: 20, clue: 'You might cry when you cut it'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'OSX', number: 21, clue: 'Mac platform'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'ARES', number: 22, clue: 'Greek hawk'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BAR', number: 23, clue: 'Cosmopolitan locale'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'ECO', number: 24, clue: 'Semiotician Umberto'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'CASHCOW', number: 25, clue: 'Reliable money-maker'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'PUERTO', number: 26, clue: 'Spanish "harbor"'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'PROBLEM', number: 26, clue: 'Word after word, in math class'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'ORGY', number: 27, clue: 'Group indulgence'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OSE', number: 28, clue: 'Verb ending?'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'WALMART', number: 29, clue: 'Retailer whose board of directors once included Hillary Clinton'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'MAFIA', number: 30, clue: 'Group with rackets'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ANI', number: 31, clue: 'Illinois cheerleader\'s frequent request'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'IER', number: 32, clue: 'Occupational suffix'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'LAS', number: 33, clue: 'Steps on the scale'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'LMN', number: 33, clue: 'K-O connection'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'ANO', number: 34, clue: 'Mayo is 1/12th of it'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SNAG', number: 35, clue: 'It can make your hose run'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SYS', number: 35, clue: 'Part of CBS'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TRYMYHIFIBUYGUY', number: 36, clue: '"I know someone who can help you purchase a vintage stereo system"?'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'TRAM', number: 36, clue: 'Cable conveyance'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'RETICENT', number: 37, clue: 'Reserved'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'YIELDSTO', number: 38, clue: 'Waits for, on the road'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'ISL', number: 39, clue: 'Man, e.g., briefly'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'UPDIKE', number: 40, clue: '"Terrorist" novelist'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'REIN', number: 41, clue: 'Jockey\'s strap'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'CSI', number: 42, clue: 'CBS megahit'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'LPS', number: 43, clue: 'Records'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ATE', number: 44, clue: 'Snacked or supped'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'SOLACED', number: 45, clue: 'Consoled'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SESE', number: 45, clue: 'Mobutu ___ Seko'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'CARFUL', number: 46, clue: 'Vehicle\'s worth'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'MID', number: 47, clue: 'Not pre- or -post-'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'MAPLES', number: 47, clue: 'Syrup sources'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'IGUESS', number: 48, clue: 'Comment made with a shrug'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'DETEST', number: 49, clue: 'Loathe'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'MILDEW', number: 50, clue: 'Shower scourge'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'DRESS', number: 51, clue: 'Diane von F&#252;rstenberg piece'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'AMI', number: 52, clue: 'Left Bank friend'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'AGE', number: 53, clue: 'What candles may signify'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'CDRS', number: 54, clue: 'They get burned'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'GRR', number: 55, clue: 'Spot\'s warning'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'GENE', number: 55, clue: 'Pool unit'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'RACE', number: 56, clue: '5K, e.g.'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'KAPUT', number: 57, clue: 'Busted'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'AGFA', number: 58, clue: 'Belgian film maker'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'WESEETEAFEEGLEE', number: 59, clue: '"Our experts predict that a pekoe tariff would cause widespread joy"?'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'WAG', number: 59, clue: 'Tail or tongue movement'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'TIP', number: 60, clue: 'Pointer'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'ERS', number: 61, clue: 'Stumblers\' sounds'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ANTS', number: 62, clue: 'Six-foot army'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'INCUR', number: 63, clue: 'Run up'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'FESS', number: 64, clue: 'Cop to, with "up"'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'GTOS', number: 65, clue: 'Highly-prized muscle cars'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'PEELS', number: 66, clue: 'Prepares a banana'))
clues_Like_Lines_CR_6_22_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ASST', number: 67, clue: 'Second: Abbr.'))
Puzzle.create(title: 'Like Lines', grid: 'BARB.ABETS.SNCC|OREO.GEARS.POOH|NEWZOOCREWTOSUE|ONION.OSX.ARES.|BAR.ECO..PUERTO|OSE.WALMART.IER|...LAS.ANO.SNAG|TRYMYHIFIBUYGUY|REIN.CSI.LPS...|ATE.SOLACED.MID|MILDEW..AMI.AGE|.CDRS.GRR.KAPUT|WESEETEAFEEGLEE|ANTS.INCUR.FESS|GTOS.PEELS.ASST', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/6/22', entries: clues_Like_Lines_CR_6_22_06)
