clues_Mixed_Media_VV_1_10_06 = Array.new
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BARQS', number: 1, clue: '___ Famous Old Tyme Root Beer'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BADE', number: 1, clue: 'Directed, old-style'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ABOY', number: 2, clue: '"When I was ___ . . . . . ."'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ROSE', number: 3, clue: '"Hu$tle" hitter'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'QUE', number: 4, clue: 'NY neighbor'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'STOVE', number: 5, clue: 'Range'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'FATS', number: 6, clue: 'Domino or Minnesota'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'FIRSTDATE', number: 6, clue: 'Drinks, often'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AREA', number: 7, clue: 'Field'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TOAST', number: 8, clue: 'Dedication with glasses'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SNL', number: 9, clue: 'Amy Poehler gig, for short'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'COLA', number: 10, clue: 'Brown bubbly beverage'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CUTESY', number: 10, clue: 'Too precious'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ONYX', number: 11, clue: 'Jet-black'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LITE', number: 12, clue: 'Ad word that attracts losers'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ATVS', number: 13, clue: 'Off-road bikes: Abbr.'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ABOUT', number: 14, clue: '~, mathematically'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'IRON', number: 15, clue: 'It may be cast in the kitchen'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'UNIT', number: 16, clue: 'The Big ___ (Randy Johnson sobriquet)'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DOSEOFREALITYTV', number: 17, clue: 'One hour of "The Apprentice" per week?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'FILE', number: 18, clue: 'Data in a folder'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'IVERSON', number: 19, clue: '"The Answer" of the NBA'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EYE', number: 20, clue: 'Place for a contact'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'VISAS', number: 21, clue: 'Travel papers'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'VEXES', number: 22, clue: 'Irritates'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'BELT', number: 23, clue: 'Ring prize'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'BARN', number: 23, clue: 'Hay there!'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'TOES', number: 24, clue: 'Bottom digits'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'OTIC', number: 25, clue: 'Auricular'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PAPA', number: 26, clue: 'Old man'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PECOS', number: 26, clue: 'River to the Rio Grande'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AMORE', number: 27, clue: 'Pet food brand for pampered felines'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'PEREC', number: 28, clue: 'Georges who wrote "A Void" (novel without the letter "E")'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'EDU', number: 29, clue: 'Academic conclusion?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'UNHIP', number: 30, clue: 'So yesterday'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'TRYSTS', number: 31, clue: 'Booty calls'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'SAWTO', number: 32, clue: 'Tended'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'THEME', number: 33, clue: 'Many crossword puzzles have one'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'SABER', number: 34, clue: 'Cavalry sword'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'EMERY', number: 35, clue: 'Pedicurist\'s material'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'YOTEAMO', number: 36, clue: 'Declaraci&#243;n of love'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'ANTIS', number: 37, clue: 'They just say "no"'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'TENTACLED', number: 38, clue: 'Like squids'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'AHA', number: 39, clue: '"Take On Me" band'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CORNONTHECOBWEB', number: 40, clue: 'Spider\'s ears?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'NITS', number: 41, clue: 'Faultfinders pick them'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'BODS', number: 42, clue: 'Gym displays, briefly'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ORE', number: 43, clue: 'Dig it'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'TIEIN', number: 44, clue: 'Bit of synergy'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'NOTME', number: 45, clue: '"Don\'t look over here!"'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SECRET', number: 46, clue: 'It may be hard to keep a juicy one'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'REALMS', number: 47, clue: 'Domains'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'PTA', number: 48, clue: 'Elementary org.'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ALEK', number: 49, clue: 'Sudanese supermodel Wek'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'DOER', number: 50, clue: 'Active sort'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'EAST', number: 51, clue: 'Columbus Avenue, vis-a-vis Amsterdam'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'TUTOR', number: 52, clue: 'Grade-booster, perhaps'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ALAS', number: 53, clue: '"Tis a pity"'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'ARROW', number: 54, clue: 'Straight bar?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'STEAM', number: 55, clue: 'Manhole emanation'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SPED', number: 55, clue: 'Did 90, say'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'TIDE', number: 56, clue: 'It gets high every day'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ELAN', number: 57, clue: 'Brio'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'ULCER', number: 58, clue: 'Worrier\'s worry'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'LAKE', number: 59, clue: 'Superior, e.g.'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ILL', number: 60, clue: 'Type of will or wind'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'IDLE', number: 60, clue: 'Not playing this week'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'LIED', number: 61, clue: 'Invented something'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'LOSS', number: 62, clue: 'Write-off'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PILLOWTALKRADIO', number: 63, clue: '"Sexually Speaking" with Dr. Ruth?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'WWF', number: 64, clue: 'Conservationist org.'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'AGE', number: 65, clue: 'Nothing but a number'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EDAM', number: 66, clue: 'Red-coated cheese'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'WOKE', number: 67, clue: 'Faced the day'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'OGLES', number: 68, clue: 'Studies a model?'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DENS', number: 69, clue: 'Scout groups'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'FRED', number: 70, clue: 'Mr. Rogers'))
clues_Mixed_Media_VV_1_10_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'WEEDS', number: 71, clue: 'Showtime series set in Agrestic, California'))
Puzzle.create(title: 'Mixed Media', grid: 'BARQS.FATS.COLA|ABOUT.IRON.UNIT|DOSEOFREALITYTV|EYE.VISAS.VEXES|...BELT.TOES...|PAPA.EDU.TRYSTS|EMERY.ANTIS.AHA|CORNONTHECOBWEB|ORE.TIEIN.NOTME|SECRET.PTA.DOER|...EAST.ALAS...|STEAM.ULCER.ILL|PILLOWTALKRADIO|EDAM.WOKE.OGLES|DENS.FRED.WEEDS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/1/10', entries: clues_Mixed_Media_VV_1_10_06)
