clues_Nine_In_One_CR_9_7_06 = Array.new
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PASSABLE', number: 1, clue: 'Just good enough'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PIBB', number: 1, clue: 'Mr. of soft drinks'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ACAR', number: 2, clue: 'Rent-____'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SETA', number: 3, clue: 'Biological bristle'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SCHISM', number: 4, clue: 'Church division'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ARESO', number: 5, clue: '"You ___ right!"'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'BERET', number: 6, clue: 'Arty toque'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LAM', number: 7, clue: 'Flight'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EMIT', number: 8, clue: 'Let out'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'CDCASE', number: 9, clue: 'Digipak, e.g.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'CATBURGLE', number: 9, clue: 'Steal stealthily'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DWEEB', number: 10, clue: 'Square sort'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CANT', number: 11, clue: 'Pessimist\'s word'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AKA', number: 12, clue: 'Wanted poster letters'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SEN', number: 13, clue: 'Obama (D-IL), e.g.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENT', number: 14, clue: 'Sinus specialist: Abbr.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ICECREAM', number: 15, clue: 'Parlor supply'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'AWAKEN', number: 16, clue: 'Rise'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BATHERMITTENANT', number: 17, clue: 'Cambridge U.; renter; diamond club; X; six-footer; one who might enter a pool; that lady; loner; snowball gripper'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'TINO', number: 18, clue: 'Former All-Star slugger Martinez'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BRAISE', number: 19, clue: 'Cook a tough cut'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'TIBET', number: 20, clue: 'Buddhist land'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'SOTS', number: 21, clue: 'They\'re often wasted'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'SITH', number: 22, clue: '"Revenge of the ___"'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'NUB', number: 23, clue: 'Worn-down pencil'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'MIR', number: 24, clue: 'Putin\'s "peace"'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'MOTHER', number: 24, clue: 'Coddle'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'INHALE', number: 25, clue: 'Take a deep breath'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'RKELLY', number: 26, clue: '"Trapped in the Closet" composer'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ICBM', number: 27, clue: 'SALT subject'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'INFACT', number: 27, clue: 'Really'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'COOLIO', number: 28, clue: '"Gangsta\'s Paradise" rapper'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'BARBET', number: 29, clue: '"Five bucks I can beat you at darts," e.g.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'IGOR', number: 30, clue: 'Fictional hunchback'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'GOATS', number: 31, clue: 'Heroes\' opposites'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'WONK', number: 32, clue: 'Policy wiz, in D.C. slang'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'WET', number: 32, clue: 'Alcoholic'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'NOA', number: 33, clue: '"___ la guerra!" (Spanish antiwar chant)'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'ISTO', number: 34, clue: 'Analogy words'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'ION', number: 34, clue: 'Cyclotron bit'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'STILETTOS', number: 35, clue: 'Sexy footwear'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'GOETHE', number: 36, clue: '"Faust" dramatist'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'OED', number: 37, clue: 'Ref. book whose first edition took 68 years to complete'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'FORGOTHAMLETHAL', number: 38, clue: 'Deadly; understood; take a flat; show-off; drew a blank; New York nickname; pro; director Hartley; 2000 Ethan Hawke role'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'GIN', number: 39, clue: 'Juice go-with'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'MEAL', number: 40, clue: 'One of three squares'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ALBINI', number: 41, clue: 'Prolific Chicago indie producer'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'TEED', number: 42, clue: 'Drove, with "off"'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ELL', number: 43, clue: 'Angular shape'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'CIEN', number: 44, clue: 'Juan\'s hundred'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'LISA', number: 45, clue: 'Homer\'s second'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'ITEM', number: 46, clue: 'Thing next to a bullet'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'PREY', number: 47, clue: 'The hunted'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'POINTY', number: 47, clue: 'Sharp'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TOT', number: 48, clue: '"Dora the Explorer" viewer'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'VET', number: 49, clue: 'Boxer\'s greatest fear, perhaps'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'VALID', number: 49, clue: 'Legit'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'LOCO', number: 50, clue: 'Batty'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'OASES', number: 51, clue: 'Caravan stops'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'CROAT', number: 52, clue: 'Nirvana\'s Krist Novoselic, e.g.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'EATEN', number: 53, clue: 'Taken in'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'EARN', number: 53, clue: 'Take home'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'NACL', number: 54, clue: 'Common cooking compound, chemically'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ARIANA', number: 55, clue: 'Carrier to Kabul'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ATIE', number: 56, clue: 'End in ___ (draw)'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NANA', number: 57, clue: 'Granny'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AGER', number: 58, clue: 'Free radical, e.g.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'COBALTMANSONTAG', number: 59, clue: '"A Prairie Home Companion" director; "it" game; performer Marilyn; PC key; ear part; mama\'s boy; grown boy; "Notes On \'Camp\'" essayist; blue shade'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'CBS', number: 59, clue: 'Edward R. Murrow\'s employer'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'OAT', number: 60, clue: 'Feed grain'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'BRA', number: 61, clue: 'Supporter of women?'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'NRA', number: 62, clue: 'Wayne LaPierre\'s grp.'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BARRIO', number: 63, clue: 'Bodega\'s place'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'CREATINE', number: 64, clue: 'Bodybuilder\'s supplement'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STANDS', number: 65, clue: 'Acknowledges applause, perhaps'))
clues_Nine_In_One_CR_9_7_06.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'LASTYEAR', number: 66, clue: '5765, now, to Jews'))
Puzzle.create(title: 'Nine in One', grid: 'PASSABLE.CDCASE|ICECREAM.AWAKEN|BATHERMITTENANT|BRAISE.TIBET...|...SOTS.NUB.MIR|ICBM..IGOR.WONK|NOA.ISTO.GOETHE|FORGOTHAMLETHAL|ALBINI.TEED.ELL|CIEN.LISA..PREY|TOT.VET.LOCO...|...EATEN.ARIANA|COBALTMANSONTAG|BARRIO.CREATINE|STANDS.LASTYEAR', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/9/7', entries: clues_Nine_In_One_CR_9_7_06)
