clues_State_Lines_CR_11_9_06 = Array.new
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ASEA', number: 1, clue: 'Sailing'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ABOMB', number: 1, clue: 'Weapon of mass destruction'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'SOCAL', number: 2, clue: 'L.A.\'s region, casually'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ENERO', number: 3, clue: 'Tiene treinta y uno d&#231;as'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ANALOGY', number: 4, clue: 'Equal comparison'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'MARC', number: 5, clue: 'Jacobs or Bolan'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MIL', number: 5, clue: '"Cool" fig.'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALI', number: 6, clue: 'Outspoken champ'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'REFS', number: 7, clue: 'Makes calls'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'CRETAN', number: 8, clue: 'King Minos, for one'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'SQUID', number: 9, clue: 'Source of marine ink'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SCHEDULE', number: 9, clue: 'Line up'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'QUESERA', number: 10, clue: '"That\'s life . . ."'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'URLS', number: 11, clue: 'Points online'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ISEE', number: 12, clue: '"10-4!"'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DENS', number: 13, clue: 'Hangouts'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BONN', number: 14, clue: 'Beethoven\'s birthplace'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ILER', number: 15, clue: 'Robert who plays A.J. Soprano'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'CURSE', number: 16, clue: 'This spell\'s trouble'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OCEANLIFE', number: 17, clue: 'Marlins and devil rays, e.g. (Rhode Island)'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'NAPA', number: 18, clue: 'Region near Sonoma'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'HELEN', number: 19, clue: 'Milli___ (the amount of beauty required to launch one ship)'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MARLA', number: 20, clue: 'An ex of The Donald'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'STRESSES', number: 21, clue: 'Frets, in modern parlance'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'RIB', number: 22, clue: 'Cage unit'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BLOOPER', number: 23, clue: 'Type of reel'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ERSE', number: 24, clue: 'Language from which "whiskey" comes'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'RDAS', number: 25, clue: 'Dietary stds.'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'AIDE', number: 26, clue: 'Number two'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'GARDENBURGER', number: 27, clue: 'Meatless entree (New Jersey)'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ENSUE', number: 28, clue: 'Come after'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'GULL', number: 29, clue: 'Billed beachgoer'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ERIE', number: 30, clue: 'Canal to the Hudson'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'RAPS', number: 31, clue: 'Spits rhymes, so to speak'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ATTY', number: 32, clue: 'Bar worker?: Abbr.'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ASKS', number: 32, clue: 'Prices at'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'THOU', number: 33, clue: 'Quaker pronoun'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'TORN', number: 34, clue: 'Deeply divided'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'SAN', number: 35, clue: 'Bruno or Diego'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'LAURA', number: 36, clue: 'Jeb\'s in-law'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SHO', number: 37, clue: 'Home of "Weeds" and "Bullshit!," briefly'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'MESSAGE', number: 38, clue: '1982 Grandmaster Flash hit "The ___"'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'MAHOGANY', number: 38, clue: 'Furniture material'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'APBS', number: 39, clue: 'Alerts from HQ'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'GNAT', number: 40, clue: 'Fly in the park'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'LIP', number: 41, clue: 'Gloss target'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'KOREA', number: 42, clue: 'Divided peninsula'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'ESPANOL', number: 43, clue: 'Daddy Yankee sings in it'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'UPN', number: 44, clue: 'Network shut down September, 2006'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ALES', number: 45, clue: 'Goose Island offerings'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ADVANCE', number: 45, clue: 'Come-on'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SUNSHINEBAND', number: 46, clue: 'KC\'s backers, with "the" (Florida)'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'IRA', number: 47, clue: 'S&amp;L offering'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'NEIGHS', number: 48, clue: 'Sounds horse?'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'NOTE', number: 49, clue: 'E or G, e.g.'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'PORE', number: 50, clue: 'Tiny opening'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'STOVERS', number: 51, clue: 'Candy family known for boxed chocolates'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'ERECT', number: 52, clue: 'Stiff'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ROYCE', number: 53, clue: 'Rolls\' partner'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'STEPS', number: 54, clue: 'You can take them to another level'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TRYAGAIN', number: 55, clue: '"Nope, not that one . . ."'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'TSPS', number: 55, clue: 'Food Network measure, briefly'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'RHEA', number: 56, clue: 'Carla portrayer on "Cheers"'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'YARD', number: 57, clue: 'Bear\'s small gain'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'NOOK', number: 58, clue: 'Breakfast area'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'TAROT', number: 59, clue: 'Predictive deck'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SHANA', number: 60, clue: 'Pundit Alexander'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'GOLDENEYE', number: 61, clue: 'Nintendo 64 classic based on a James Bond film (California)'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'LYE', number: 62, clue: 'Solution in soap and frosted glass'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'DAW', number: 63, clue: 'Crow cousin'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PERON', number: 64, clue: '"Evita" surname'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'HOYA', number: 65, clue: 'Georgetown player'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'CCCP', number: 66, clue: 'Old Cyrillic insignia'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SADLY', number: 67, clue: 'With a heavy heart'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SKEW', number: 68, clue: 'Warp'))
clues_State_Lines_CR_11_9_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ETES', number: 69, clue: 'Are, in Arles'))
Puzzle.create(title: 'State Lines', grid: 'ASEA.MARC.SQUID|BONN.ILER.CURSE|OCEANLIFE.HELEN|MARLA..STRESSES|BLOOPER.AIDE...|...GARDENBURGER|ATTY.SAN..LAURA|SHO.MESSAGE.LIP|KOREA..UPN.ALES|SUNSHINEBAND...|...PORE.STOVERS|TRYAGAIN..TAROT|SHANA.GOLDENEYE|PERON.HOYA.CCCP|SADLY.SKEW.ETES', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/11/9', entries: clues_State_Lines_CR_11_9_06)
