clues_Stumbling_In_CR_12_28_06 = Array.new
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BLIMP', number: 1, clue: 'Craft from Akron, Ohio'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BTW', number: 1, clue: 'Chatroom digression shorthand'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LOA', number: 2, clue: 'Mauna ___'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'INN', number: 3, clue: 'Hostelry'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MANICOTTI', number: 4, clue: 'Stuffed tubes'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'PLANET', number: 5, clue: 'Lonely ___'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'TYSON', number: 6, clue: 'Former "Baddest Man on the Planet"'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'THA', number: 6, clue: 'Article in Vibe?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'YAKS', number: 7, clue: 'Rattles on'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SNEEZE', number: 8, clue: 'Cold sound'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ONATEAR', number: 9, clue: 'Streaking'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NAB', number: 10, clue: 'Bag'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BBB', number: 11, clue: 'Consumer protection org.'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BARQ', number: 11, clue: 'Root beer magnate Edward or Gaston'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BLEU', number: 12, clue: 'La couleur du 65-Down'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BETA', number: 13, clue: 'Software version that may be glitchy'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TONAL', number: 14, clue: 'Having a key'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'HANNA', number: 15, clue: 'Huckleberry Hound co-creator'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ALE', number: 16, clue: 'It may be pale'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'WANNAMAKEABERET', number: 17, clue: '"I can teach you how to sew an artist\'s hat, if you\'re interested"?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'MEDOC', number: 18, clue: 'Red Bordeaux'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'EAT', number: 19, clue: 'Put away'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'INE', number: 20, clue: 'It can feminize a hero'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'SET', number: 21, clue: 'Where "quiet!" might be shouted'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'AQUA', number: 22, clue: 'Water color'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'PRECEDE', number: 23, clue: 'Come before'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'PSALMS', number: 23, clue: 'Whence the line "The Lord is my shepherd; I shall not want"'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'RUPEES', number: 24, clue: 'Pounds : Egypt :: ___ : India'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'EMENDS', number: 25, clue: 'Tweaks text'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'ESSE', number: 26, clue: 'Latin 101 verb'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ZEST', number: 27, clue: 'Shaving in the kitchen'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'SKID', number: 28, clue: 'Marks on the highway'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SUMOTOSPEAK', number: 29, clue: 'Headline about a Japanese wrestler\'s upcoming press conference?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'PIXAR', number: 30, clue: '"Cars" studio'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'PEG', number: 31, clue: '"Married . . . with Children" mother'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'PTBOAT', number: 31, clue: 'JFK\'s craft, once'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'EEYORE', number: 32, clue: 'Gloomy donkey of fiction'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'GRANDE', number: 33, clue: 'It\'s big at Taco Bell'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'APET', number: 34, clue: 'In ___ (annoyed)'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'CSI', number: 35, clue: 'CBS show set in Vegas'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'RIOTER', number: 36, clue: 'Upriser, put pejoratively'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'OUTOFROOM', number: 37, clue: 'In a real estate crunch'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LENTS', number: 38, clue: 'Fast times for Christians'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SAFE', number: 39, clue: 'On first, maybe'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'EXO', number: 40, clue: 'Prefix with skeleton'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'OLEG', number: 41, clue: 'Designer Cassini'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'DUBYA', number: 42, clue: 'No. 43, familiarly'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MEDIAN', number: 43, clue: 'Highway divider'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'NECTARS', number: 44, clue: 'Honey sources'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ALS', number: 45, clue: 'Green and Gore'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'STOOD', number: 46, clue: 'Abdicated a seat'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'TOON', number: 47, clue: 'A Powerpuff Girl, e.g.'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SSS', number: 48, clue: 'Leaky sound'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'FERRETBOARD', number: 49, clue: 'Advisory panel made up of weasel-like creatures?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'RAHWAY', number: 50, clue: 'New Jersey hometown of Carl Sagan and Milton Friedman'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'BLUFFS', number: 51, clue: 'Represents a flush, say'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'DECA', number: 52, clue: 'Word form for \'\'ten\'\''))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'DWI', number: 52, clue: 'Traffic court letters'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'GOLFTEE', number: 53, clue: 'Driver\'s aid'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SKEW', number: 54, clue: 'Distort'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SPAN', number: 54, clue: 'Bridge'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'KURT', number: 55, clue: 'Noted 90\'s frontman'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ETCH', number: 56, clue: 'Use acid creatively?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'THC', number: 57, clue: 'Marinol, in nature'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'CONN', number: 58, clue: 'The Constitution St.'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'OUR', number: 59, clue: 'Lord\'s Prayer start'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PUTINAWORDFORUM', number: 60, clue: 'Crossword puzzle seminar?'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'NIN', number: 61, clue: 'Nothing Records flagship band, to fans'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'RIC', number: 62, clue: '16-time World Heavyweight Champion wrestler Flair'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'ROE', number: 63, clue: 'Sushi choice'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'UTA', number: 64, clue: 'Tony winner Hagen'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'MER', number: 65, clue: 'Regardez 12-Down'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ARC', number: 66, clue: 'Javelin\'s path'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'IRANI', number: 67, clue: 'Afghan\'s neighbor'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'FOOTE', number: 68, clue: 'Civil War historian Shelby'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NTH', number: 69, clue: 'Ultimate degree'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'NSYNC', number: 70, clue: 'Joey Fatone\'s band'))
clues_Stumbling_In_CR_12_28_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SMEAR', number: 71, clue: 'Ugly kind of campaign'))
Puzzle.create(title: 'Stumbling In', grid: 'BLIMP.TYSON.BBB|TONAL.HANNA.ALE|WANNAMAKEABERET|...INE.SET.AQUA|PRECEDE.ZEST...|SUMOTOSPEAK.PEG|APET.CSI.RIOTER|LENTS.EXO.DUBYA|MEDIAN.ALS.TOON|SSS.FERRETBOARD|...DECA.GOLFTEE|SKEW.THC.OUR...|PUTINAWORDFORUM|ARC.IRANI.FOOTE|NTH.NSYNC.SMEAR', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/12/28', entries: clues_Stumbling_In_CR_12_28_06)
