clues_Tee_Time_CR_3_2_06 = Array.new
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SEVEN', number: 1, clue: 'The Chicago ___'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SAMS', number: 1, clue: '"Club" for bulk-buyers'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELEC', number: 2, clue: 'A util.'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'VILA', number: 3, clue: '"This Old House" host'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EVENODDS', number: 4, clue: '50/50 chance'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NEEDLES', number: 5, clue: 'Pine stickers'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ATOM', number: 6, clue: 'Split bit'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANTLER', number: 6, clue: 'The point of a male?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TOO', number: 7, clue: 'As well'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ONME', number: 8, clue: 'Treater\'s words'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MOBY', number: 9, clue: 'Whale Dick'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'CRAB', number: 10, clue: 'Sidestepper?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CHASER', number: 10, clue: 'Beer, at times'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'RATON', number: 11, clue: 'Betray, as an accomplice'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ALERT', number: 12, clue: 'A serious one may be red'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BORES', number: 13, clue: 'Drills'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALIVE', number: 14, clue: 'Kicking, so to speak'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'NONO', number: 15, clue: 'Sticking a fork in the toaster, e.g.'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'HALO', number: 16, clue: 'Head light'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MELEE', number: 17, clue: 'Free-for-all'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'TOMBRATER', number: 18, clue: 'Crypt judge?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'REVEL', number: 19, clue: 'Party'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SCANDAL', number: 20, clue: 'It may have a gate attached to it'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'AMA', number: 21, clue: 'Org. for an OB/GYN'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'EYESORE', number: 22, clue: 'It isn\'t pretty'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'OLMEC', number: 23, clue: 'Ancient Mexican'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'CLUBMED', number: 24, clue: 'Resort company'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'VENTS', number: 25, clue: 'Blows off steam'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'THEDEARLITER', number: 26, clue: 'Affectionate term for a soda bottle?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'TKOS', number: 26, clue: 'Refs\' ring decisions'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'HUTU', number: 27, clue: 'Tutsi foe'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ERIE', number: 28, clue: 'Toledo\'s lake'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'IRE', number: 29, clue: 'Rage'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'TAR', number: 30, clue: 'Feather\'s partner'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'KURDS', number: 31, clue: 'Iraqi minority'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'URAL', number: 32, clue: 'Eurasia\'s ___ Mountains'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'FLU', number: 33, clue: 'Common winter bug'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'FRET', number: 33, clue: 'Guitar guide'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'LAME', number: 34, clue: 'Unconvincing, as an excuse'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'USSR', number: 35, clue: 'Former red states?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'OTIS', number: 36, clue: 'Name in lifts'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'AMBER', number: 37, clue: '"America the Beautiful" color'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ALP', number: 37, clue: 'Yodeling spot, perhaps'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'MIL', number: 38, clue: '"Cool" fig.'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'ERAS', number: 39, clue: 'Spring training stats'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'ETHEREAL', number: 39, clue: 'Ghostly'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SUE', number: 40, clue: 'Try for damages'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'SLIM', number: 41, clue: 'Like some pickings'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SPEAR', number: 41, clue: 'Single pickle'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ITEMS', number: 42, clue: 'Couples in tabloids'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'IGNORES', number: 42, clue: 'Tunes out'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'APPLESIGHTER', number: 43, clue: 'One surveying the orchard?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ALLWET', number: 43, clue: 'Soaked'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'SOIREE', number: 44, clue: 'Evening affair'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'INN', number: 45, clue: 'Rest stop'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'MAPLE', number: 46, clue: 'Syrup flavor'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'MOJOS', number: 46, clue: 'Conjurer\'s items'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ANODE', number: 47, clue: 'Battery pole'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'PAYIN', number: 48, clue: 'Contribute'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'DONNE', number: 49, clue: '"For Whom the Bell Tolls" poet'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ONALARK', number: 50, clue: 'For fun'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'RIFE', number: 51, clue: 'Rampant'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'KTEL', number: 52, clue: 'Big name in compilation albums'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'INORBIT', number: 53, clue: 'Circling, as a satellite'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'BARE', number: 54, clue: 'Exposed'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IDLE', number: 55, clue: 'Run in place?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'TEST', number: 56, clue: 'Beta version, e.g.'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'JOYWRITER', number: 57, clue: 'Exuberant novelist?'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ETS', number: 58, clue: 'UFO pilots'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'READE', number: 59, clue: 'Aptly named English novelist'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ODIE', number: 60, clue: 'Dog in a strip'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'FETE', number: 61, clue: 'Wine and dine'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EARLS', number: 62, clue: 'Sandwich and Salisbury'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SENT', number: 63, clue: 'E-mailed'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ELSE', number: 64, clue: '"Or ___!"'))
clues_Tee_Time_CR_3_2_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SLEET', number: 65, clue: 'Wintry mix'))
Puzzle.create(title: 'Tee Time', grid: 'SEVEN.ATOM.CRAB|ALIVE.NONO.HALO|MELEE.TOMBRATER|SCANDAL.EYESORE|...OLMEC..VENTS|THEDEARLITER...|KURDS..URAL.FLU|OTIS.AMBER.ERAS|SUE.SLIM..ITEMS|...APPLESIGHTER|MAPLE..DONNE...|ONALARK.INORBIT|JOYWRITER.READE|ODIE.FETE.EARLS|SENT.ELSE.SLEET', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/3/2', entries: clues_Tee_Time_CR_3_2_06)
