clues_The_Longest_Sentence_DMT_10_11_06 = Array.new
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'FARM', number: 1, clue: '*MacDonald\'s workplace?'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'FAMILY', number: 1, clue: '*Nuclear group'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ANOMIE', number: 2, clue: 'Social breakdown'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RETINA', number: 3, clue: 'Image receiver'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MTST', number: 4, clue: '___ Helens, WA'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'SHELF', number: 5, clue: '*Bookstore unit'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'STATISM', number: 5, clue: 'Anarchist\'s bane'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HONES', number: 6, clue: 'Sharpens'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EDS', number: 7, clue: 'Harris and Norton'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'LIES', number: 8, clue: 'BSes'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'FELINES', number: 9, clue: 'Some predatory carnivores'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'HOME', number: 10, clue: '*Browser button'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HASID', number: 10, clue: 'Follower of Rabbi Israel ben Eliezer'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OMELETTE', number: 11, clue: 'Denver, for one'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MACARENA', number: 12, clue: 'Los del Rio\'s lone hit'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENTR', number: 13, clue: '___\'acte'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ANET', number: 14, clue: 'Without ___ (daringly)'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'TODIE', number: 15, clue: '___ for (wonderful)'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'AMAN', number: 16, clue: 'Start of a noted palindrome'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MOTS', number: 17, clue: 'Words in Lourdes'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'ANSEL', number: 18, clue: 'Zone System inventor Adams'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'SECT', number: 19, clue: 'Certain spin-off'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'IMITATE', number: 20, clue: 'Copy'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ASTIR', number: 21, clue: 'Up and about'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'SIMILAR', number: 22, clue: 'Analogous'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'MAC', number: 23, clue: 'G5 maker'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LIN', number: 24, clue: 'Vietnam War Memorial designer'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'SISI', number: 25, clue: 'Spanish affirmation'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'INROADS', number: 26, clue: 'Progress'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'NADER', number: 27, clue: 'Receiver of 84,165 votes in Michigan in 2000'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'YEASTS', number: 28, clue: 'Brewer\'s needs'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'STES', number: 29, clue: 'Jeanne d\'Arc, et al.'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'NSEC', number: 30, clue: 'Tiny fraction of a min.'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'SEWN', number: 31, clue: 'In stitches'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'TEN', number: 32, clue: 'Count on two hands'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'NAM', number: 33, clue: '60s service area'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'TIMBRES', number: 34, clue: 'Tone colors'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'BLIN', number: 35, clue: 'Russian pancake'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ETNA', number: 36, clue: 'Sicilian smoker'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'EREI', number: 36, clue: 'Part of a noted palindrome'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AFTER', number: 37, clue: '*Seeking'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'AIL', number: 37, clue: 'Have a bug'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'FREERIDE', number: 38, clue: 'Easy time'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'TASMANIA', number: 39, clue: 'Island of "devils"'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'LOW', number: 40, clue: '*Like bass'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'DREAM', number: 41, clue: '*Night vision?'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'DEBUT', number: 41, clue: 'Coming-out'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'IRAS', number: 42, clue: '401(k) alternatives'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'FIANCEE', number: 43, clue: 'Maggie Gyllenhaal, to Peter Sarsgaard'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'FIENNES', number: 43, clue: 'Lord Voldemort portrayer'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'CITADEL', number: 44, clue: 'Stronghold'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'LES', number: 45, clue: 'Guitarist Paul'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'MIND', number: 46, clue: 'Care'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'MLI', number: 46, clue: 'Mid-11th century year'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'IBIDEM', number: 47, clue: 'Footnote word'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'DOREMI', number: 48, clue: 'Run on a scale'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'EVENIF', number: 49, clue: 'Regardless of whether'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'MARINE', number: 50, clue: '*Jarhead'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'EMILE', number: 51, clue: 'Mr. Zola'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'IDEAL', number: 52, clue: 'Model'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'SITU', number: 53, clue: 'In ___ (as found)'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ICALL', number: 54, clue: 'Phrase for one who sees'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'OVA', number: 55, clue: 'Anatomical eggs'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TRADING', number: 56, clue: 'Wall Street activity'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'TSAR', number: 56, clue: 'Pre-communism leader'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'GOAT', number: 57, clue: 'Eater of almost anything'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'CATERER', number: 58, clue: 'Wedding hire'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'EVIL', number: 59, clue: 'Controversial word in a January, 2002 State of the Union address'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SINE', number: 60, clue: 'Wave type'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'NOMAD', number: 61, clue: 'Not the settling-down type'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'MRI', number: 62, clue: 'X-ray cousin'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'VENI', number: 63, clue: 'Caesar\'s "I came"'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ADIA', number: 64, clue: 'Sarah McLachlan single'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EARLE', number: 65, clue: 'Coutry singer Steve'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'IMIN', number: 66, clue: '"Sign me up!"'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REAL', number: 67, clue: '*Concrete'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'STILL', number: 68, clue: '*To this day'))
clues_The_Longest_Sentence_DMT_10_11_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'LIFE', number: 69, clue: 'Word that can follow the ten starred words in this puzzle'))
Puzzle.create(title: 'The Longest Sentence', grid: 'FARM.SHELF.HOME|ANET.TODIE.AMAN|MOTS.ANSEL.SECT|IMITATE.SIMILAR|LIN.SISI.NADER.|YEASTS.NSEC.TEN|...TIMBRES.ETNA|AFTER.LOW.DREAM|IRAS.FIANCEE...|LES.MIND.IBIDEM|.EMILE.SITU.OVA|TRADING.CATERER|SINE.NOMAD.VENI|ADIA.EARLE.IMIN|REAL.STILL.LIFE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/10/11', entries: clues_The_Longest_Sentence_DMT_10_11_06)
