clues_Triple_Play_VV_1_17_06 = Array.new
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ERRS', number: 1, clue: 'Stumbles'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ELL', number: 1, clue: '90-degree angle'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'RIOTERS', number: 2, clue: 'Unhappy prisoners, at times'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RECIPES', number: 3, clue: 'Kitchen blueprints'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SNAGS', number: 4, clue: 'Catches, as hose'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'CAROM', number: 5, clue: 'Pool glance'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'CCII', number: 5, clue: 'Early third century year'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALOSER', number: 6, clue: '"I\'m ___, baby" (Beck lyric)'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RAN', number: 7, clue: 'Kurosawa classic'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'OSX', number: 8, clue: 'Common Apple platform'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MPX', number: 9, clue: 'Oft-swapped file type'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'GIGA', number: 10, clue: 'Mega times 1,024'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GOMER', number: 10, clue: 'Private Pyle'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ITALIAN', number: 11, clue: 'Mulberry St. cuisine'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'GIRLSXX', number: 12, clue: 'M&#246;tley Cr&#252;e anthem'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ASK', number: 13, clue: 'Invite'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LIEN', number: 14, clue: 'Property claim'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'CLASP', number: 15, clue: 'Hold on tight'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'OTIS', number: 16, clue: 'Car company?'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LOCATIONXX', number: 17, clue: 'Properties adage'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'TRIAGE', number: 18, clue: '"M*A*S*H" procedure'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'MARK', number: 19, clue: 'Grade'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'TIGRIS', number: 20, clue: 'It has banks in Iraq'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'JELL', number: 21, clue: 'Take form'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'JAW', number: 21, clue: 'Chatter'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'PEPSI', number: 22, clue: 'Pop hit'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'PEA', number: 22, clue: 'Green shade'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'EUCHARIST', number: 23, clue: 'Mass consumption?'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'USS', number: 24, clue: 'Vessel initials'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'CHUG', number: 25, clue: 'Frat house chant'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'HOVELS', number: 26, clue: 'Hardly mansions'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'TED', number: 27, clue: 'A Kennedy'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ERE', number: 28, clue: 'Afore'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'AIRSHOW', number: 29, clue: 'Military flying display'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'INFANT', number: 30, clue: 'New delivery'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'AXE', number: 31, clue: 'The Nuge\'s tool'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ASSIGN', number: 32, clue: 'Give, as homework'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'IRS', number: 33, clue: '1099 org.'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'SUV', number: 34, clue: 'Gas hog'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'INXD', number: 35, clue: 'How some movies are shown'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'ISM', number: 35, clue: 'Belief system'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'REFS', number: 36, clue: 'Court judges'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'SODA', number: 37, clue: 'Scotch go-with'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'GEMS', number: 38, clue: 'Tiara adornments'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'MUESLI', number: 39, clue: 'Swiss breakfast cereal'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EYES', number: 40, clue: 'Socket contents'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'EVA', number: 40, clue: 'Per&#243;n or Longoria'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'YADDAXX', number: 41, clue: 'Etc.'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'ENVELOP', number: 42, clue: 'Completely surround'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'AOL', number: 43, clue: 'Chat room provider'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'LOG', number: 44, clue: 'Record'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'LUMPIN', number: 45, clue: 'Group together'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'PRECEDE', number: 46, clue: 'Go before'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'INDEXER', number: 47, clue: 'Librarian, at times'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'NAS', number: 48, clue: '"Illmatic" rapper'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'VAN', number: 49, clue: 'Moving vehicle'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ENDORSE', number: 50, clue: 'Back, as a candidate'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ENO', number: 50, clue: 'Ambient pioneer'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'RESCUE', number: 51, clue: 'Job for a lifeguard'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'RNA', number: 52, clue: 'Stranded carrier'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ADVANTAGE', number: 53, clue: 'Pole position, e.g.'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'AMINO', number: 54, clue: 'Acid type'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'SLEDS', number: 55, clue: 'Goes downhill fast'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'LICIT', number: 56, clue: 'Within the law'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'DEMO', number: 57, clue: 'It\'s cut in pursuit of a break'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'SPLICE', number: 58, clue: 'Piece together, as film'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'PTAS', number: 59, clue: 'Gps. with open houses'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MALI', number: 60, clue: 'Timbuktu\'s land'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'MAC', number: 60, clue: 'Big ___'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'PRACTICEXX', number: 61, clue: 'How to get to Carnegie Hall'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'PPS', number: 61, clue: 'Second letter afterthought'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'RAH', number: 62, clue: 'Cheer sound'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ADO', number: 63, clue: 'Bustle'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'XAM', number: 64, clue: 'Wee hour'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AXON', number: 65, clue: 'Neural transmitter'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'PADUA', number: 66, clue: 'St. Anthony\'s city'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'IDEA', number: 67, clue: 'Mental flash'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'CXPO', number: 68, clue: 'Noted protocol droid'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SHOES', number: 69, clue: 'Campers, e.g.'))
clues_Triple_Play_VV_1_17_06.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'TERM', number: 70, clue: 'Phrase'))
Puzzle.create(title: 'Triple Play', grid: 'ERRS.CAROM.GIGA|LIEN.CLASP.OTIS|LOCATIONXX.MARK|.TIGRIS...JELL.|PEPSI.EUCHARIST|ERE.AIRSHOW.AXE|ASSIGN.SUV.INXD|...REFS.GEMS...|EYES.AOL.LUMPIN|VAN.ENDORSE.RNA|ADVANTAGE.SLEDS|.DEMO...SPLICE.|MALI.PRACTICEXX|AXON.PADUA.IDEA|CXPO.SHOES.TERM', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/1/17', entries: clues_Triple_Play_VV_1_17_06)
