clues_World_Figures_CR_7_13_06 = Array.new
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DITSY', number: 1, clue: 'Like an airhead'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DIBS', number: 1, clue: 'Claimer\'s rights'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'INOCULATE', number: 2, clue: 'Infect on purpose'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TRATTORIA', number: 3, clue: 'Casual Italian joint'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SERVINGTRE', number: 4, clue: 'Yet another helping of risotto?'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'YDS', number: 5, clue: 'They have three feet, briefly'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ISLA', number: 6, clue: 'Puerto Rico, por ejemplo'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IFNI', number: 6, clue: 'Former Spanish territory in Morocco'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SLOB', number: 7, clue: 'Pig'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'LIVEN', number: 8, clue: 'Jazz up'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'APERITIF', number: 9, clue: 'Liquid appetizer'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SNAG', number: 10, clue: 'Fly in the ointment'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SHEL', number: 10, clue: 'Cartoonist Silverstein'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'NOTDO', number: 11, clue: 'Abstain from'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ANTON', number: 12, clue: 'LaVey or Chekhov'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'GEESE', number: 13, clue: 'Flying V components'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'INRED', number: 14, clue: 'How a teacher might mark mistakes'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'FLIPPHONE', number: 15, clue: 'Nokia option'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 2, col: 11, dir: 'Down', answer: 'PLANB', number: 16, clue: 'Fallback option'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BOARS', number: 17, clue: 'Tusked rooters'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'NOVELETTE', number: 18, clue: 'Proulx\'s "Brokeback Mountain," e.g.'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SCTV', number: 19, clue: 'Show that broke Candy'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'LIBERALDOS', number: 20, clue: 'Cesar Chavez y Los Angeles Mayor Antonio Villaraigosa?'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'LAI', number: 20, clue: 'Chou En-___'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'UTICA', number: 21, clue: 'New York city named for a Phoenician colony'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'CDE', number: 22, clue: 'String before F'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'NIN', number: 23, clue: 'Big initials in industrial music'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'ONE', number: 24, clue: 'Common bill'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'KLONDIKE', number: 25, clue: 'Bar with a polar bear logo'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'KLAN', number: 25, clue: 'Part of KKK'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'KATO', number: 26, clue: 'O.J. trial testifier'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'EMEND', number: 27, clue: 'Edit'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'TBS', number: 28, clue: 'Home of the Braves, on TV'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'SEPTDESIGN', number: 29, clue: 'French schematic of deadly sins?'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'LARGE', number: 30, clue: 'Sizable'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'AMBI', number: 31, clue: 'Prefix for a switch-hitter'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'BOSE', number: 32, clue: 'High-end speaker brand'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ESSA', number: 33, clue: 'She, in Italy'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'SATIRICAL', number: 34, clue: 'Like "Billionaires for Bush"'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'SWISSMADE', number: 35, clue: 'Like some chocolate and cheese'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ASCH', number: 36, clue: '"In the Beginning" author Sholem'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ATIT', number: 37, clue: 'Plugging away'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'ATEOF', number: 38, clue: 'Noshed on, biblically'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ATALANTA', number: 38, clue: 'Runner in Greek mythology'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'PAWS', number: 39, clue: 'Feline feet'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'NEAR', number: 40, clue: 'Just around the corner'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'TONS', number: 41, clue: 'Oodles'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ATTIC', number: 42, clue: 'You may take several flights to get there'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'APU', number: 42, clue: '"Simpsons" dad'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ETA', number: 43, clue: 'Terminal msg.'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'TOFUS', number: 44, clue: 'Silken and firm, e.g.'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'DEEPDISH', number: 45, clue: 'Chicago pie style'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ERR', number: 46, clue: 'Mess up'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'INN', number: 47, clue: 'Hostel'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'IVANA', number: 47, clue: 'The Donald\'s ex'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'NINER', number: 48, clue: 'Bear\'s NFC rival'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'NETWT', number: 49, clue: 'Cereal box amt.'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'OLS', number: 50, clue: 'Protectors of QBs'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'SCION', number: 51, clue: 'Inheritor'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'RUERS', number: 52, clue: 'Sorry souls'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'VIERFACTOR', number: 53, clue: 'Potential importance of a German quartet?'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'RISE', number: 54, clue: 'Wake up'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'TORO', number: 55, clue: 'Mower name'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'ONYX', number: 56, clue: 'Quartz type'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'SIMP', number: 57, clue: 'Dunce, once'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'PSST', number: 58, clue: '"Hey . . . over here!"'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ANTIUNION', number: 59, clue: 'Wal-Mart, to many labor advocates'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'PICAS', number: 60, clue: '12-point type choices'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'PEI', number: 60, clue: 'Architect Ieoh Ming ___'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NEWSSTORY', number: 61, clue: 'Piece in the paper'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EGADS', number: 62, clue: '"Jiminy!"'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ARTE', number: 63, clue: 'It hangs in the Prado'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ANOX', number: 64, clue: 'Strong as ___'))
clues_World_Figures_CR_7_13_06.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'INLET', number: 65, clue: 'Small bay'))
Puzzle.create(title: 'World Figures', grid: 'DITSY.ISLA.SNAG|INRED.FLIPPHONE|BOARS.NOVELETTE|SCTV.LIBERALDOS|.UTICA..NIN.ONE|KLONDIKE.TBS...|LARGE.AMBI.ESSA|ATIT.ATEOF.PAWS|NEAR.TONS.ATTIC|...ETA.DEEPDISH|INN.OLS..RUERS.|VIERFACTOR.SIMP|ANTIUNION.PICAS|NEWSSTORY.EGADS|ARTE.ANOX.INLET', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2006/7/13', entries: clues_World_Figures_CR_7_13_06)
