clues_Downgrading_CR_7_31_08 = Array.new
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'HAJJ', number: 1, clue: 'Muslim journey'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'HUB', number: 1, clue: 'Ethernet device'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AGO', number: 2, clue: 'Some time ___'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'JLO', number: 3, clue: 'Marc Anthony\'s wife, casually'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'JIBBOOM', number: 4, clue: 'Sailing spar'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'CARIB', number: 5, clue: 'Trinidadian, e.g.'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'CORONET', number: 5, clue: 'Royal crown'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ADAYS', number: 6, clue: 'Two-___ (grueling football practice regimen)'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'REIN', number: 7, clue: 'Jockey\'s strap'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ILSA', number: 8, clue: '"___, She Wolf of the SS"'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'BLEMISH', number: 9, clue: 'Makeup target'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'BLTS', number: 10, clue: 'Sandwiches that might be made with heirlooms'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BURDENS', number: 10, clue: 'Acts as an albatross'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LHASA', number: 11, clue: 'Tibet University locale'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TORUN', number: 12, clue: '"Born ___"'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SHEET', number: 13, clue: 'Cheap Halloween costume item'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'UGLI', number: 14, clue: 'Citrus hybrid'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ODELL', number: 15, clue: '"Access Hollywood" co-host Nancy'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'UHOH', number: 16, clue: '"I think I broke it ..."'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BOOB', number: 17, clue: 'Ass'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'RAISE', number: 18, clue: 'Make higher'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'RARE', number: 19, clue: 'Like some vinyl or footage'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'BBOYNAMEDSUE', number: 20, clue: 'Male breakdancer with a feminine sobriquet?'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'BALI', number: 21, clue: 'Resort island in the 4th most populous country in the world'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'EMO', number: 22, clue: 'Stereotypically self-serious genre'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SAMOANS', number: 23, clue: 'Pago Pago residents'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'SOCAL', number: 23, clue: '"The O.C." setting'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ALANA', number: 24, clue: 'Rod Stewart\'s ex'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'MERCI', number: 25, clue: 'Acknowledgment to the gar&#231;on'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'IMEANT', number: 26, clue: '"Let me rephrase that ..."'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OLEOLE', number: 27, clue: 'South Africa 2010 chant'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'ORSON', number: 28, clue: '"Ender\'s Game" author Scott Card'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'OVULE', number: 28, clue: 'Immature egg'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'RADO', number: 29, clue: 'TAG Heuer competitor'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CARMITZVAH', number: 30, clue: 'Coming-of-age on wheels?'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ZION', number: 31, clue: '"The Protocols of the Elders of ___" (antisemitic forgery)'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SETS', number: 32, clue: 'U.S. Open units'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'EMAIL', number: 33, clue: 'Forward, perhaps'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'TORRE', number: 34, clue: 'Girardi\'s predecessor as manager of the Yankees'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SIDES', number: 35, clue: 'Slaw and applesauce, e.g.'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ANC', number: 36, clue: 'Mandela\'s party: Abbr.'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'IUD', number: 37, clue: 'Alternative to the morning-after pill'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'MOI', number: 38, clue: 'Me, abroad'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LAIC', number: 39, clue: 'Of the flock'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'COARSEN', number: 40, clue: 'Make rougher'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'DOLORGUARD', number: 41, clue: 'Prozac?'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'DIARIST', number: 41, clue: 'Frank, notably'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'REENTRY', number: 42, clue: 'Sometimes-dramatic NASA event'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'GMAC', number: 43, clue: 'Auto financing co. recently sold by its parent co.'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'UPTEMPO', number: 44, clue: 'Having a high BPM'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'OPINE', number: 45, clue: 'Speak one\'s mind'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'PCP', number: 46, clue: 'Lacing agent'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'EMPIRE', number: 47, clue: 'British film monthly'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'OAXACA', number: 48, clue: 'Mexican mescal capital'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'OFALL', number: 48, clue: '"___ the gin joints ..."'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'AERIE', number: 49, clue: 'High nest'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'XACTO', number: 50, clue: 'Art class brand'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'BEATLES', number: 51, clue: 'Band with "1"'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'BERRA', number: 51, clue: 'Oft-quoted malapropist'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'FEARPRUDENCE', number: 52, clue: 'Be intimidated by good judgment?'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'UNTO', number: 53, clue: 'Golden Rule word'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'DEAD', number: 54, clue: 'Unpopulated'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ARCS', number: 55, clue: 'C shapes'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'INERT', number: 56, clue: 'Like neon'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'MYMY', number: 57, clue: '"Well, lookie here ..."'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'YOU', number: 58, clue: 'One of us?'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'MRS', number: 59, clue: '___ Dash'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'YET', number: 60, clue: 'Thus far'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LITE', number: 61, clue: '___-Brite'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'STARR', number: 62, clue: 'Ringo or Kenneth'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'PORE', number: 63, clue: 'Sweat spot'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'LEON', number: 64, clue: 'Knox ___ (one of Angelina\'s twins)'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TODAY', number: 65, clue: 'Show on which Hillary Clinton first alluded to the "vast right-wing conspiracy"'))
clues_Downgrading_CR_7_31_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'OUST', number: 66, clue: 'Remove from a position'))
Puzzle.create(title: 'Downgrading', grid: 'HAJJ.CARIB.BLTS|UGLI.ODELL.UHOH|BOOB.RAISE.RARE|...BBOYNAMEDSUE|SAMOANS..IMEANT|OLEOLE.ORSON...|CARMITZVAH.SETS|ANC...IUD...MOI|LAIC.DOLORGUARD|...OPINE.EMPIRE|OAXACA..BEATLES|FEARPRUDENCE...|ARCS.INERT.MYMY|LITE.STARR.PORE|LEON.TODAY.OUST', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/7/31', entries: clues_Downgrading_CR_7_31_08)
