clues_Dropping_E_CR_8_28_08 = Array.new
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AIMS', number: 1, clue: 'Pursuits'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'AIKMAN', number: 1, clue: 'QB-turned-sportscaster Troy'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'INATUB', number: 2, clue: 'Where "three men" are, in a rhyme'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MARISA', number: 3, clue: 'Tomei of "Before the Devil Knows You\'re Dead"'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'STAD', number: 4, clue: 'The Hague, to residents'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'UPON', number: 5, clue: 'Second word of many a fairy tale'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'URB', number: 5, clue: 'Spin alternative'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PALLOR', number: 6, clue: 'Look of one who\'s just seen a ghost'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OTTOS', number: 7, clue: 'Four Holy Roman emperors'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NASR', number: 8, clue: 'CNN correspondent Octavia'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'AFLAC', number: 9, clue: 'Company with a spokesduck'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ACTIII', number: 9, clue: '"August: Osage County" finale'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'FLYNN', number: 10, clue: 'In like ___'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LIP', number: 11, clue: 'Back talk'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'AMO', number: 12, clue: 'Latin 101 verb'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CBS', number: 13, clue: 'Airer of 32-Across'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'INAT', number: 14, clue: '___ the finish'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'RATA', number: 15, clue: 'Pro ___ (one way to divide things)'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'CLIMB', number: 16, clue: 'Scale'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'KARATBLTS', number: 17, clue: 'Deli sandwiches with purity measurements?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'TANTRA', number: 18, clue: 'Hindu doctrine with secret sexual rituals'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'TYPOS', number: 19, clue: 'Common internet message board phenomena'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MTIDA', number: 20, clue: 'Peak in Greek mythology'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'LORAIN', number: 21, clue: 'Ohio birthplace of Toni Morrison'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ASSASSIN', number: 22, clue: 'Ninja, e.g.'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'AUS', number: 23, clue: 'Schwarzenegger\'s birthplace: Abbr.'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'NGOS', number: 24, clue: 'Int\'l aid gps.'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'GANGWAYS', number: 25, clue: 'Escape passages, possibly'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'SINWAV', number: 26, clue: 'Lusty sound file?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'WINO', number: 27, clue: 'Brown bagger?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'APOP', number: 28, clue: 'Per'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'VOW', number: 29, clue: '"I do," e.g.'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'NBASTAR', number: 30, clue: 'Certain arena filler'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'SUPS', number: 31, clue: 'Has dinner'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'CSI', number: 32, clue: 'Show with regional spinoffs'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'CON', number: 32, clue: 'She may never turn pro'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'IPO', number: 33, clue: 'NYSE debut'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'URN', number: 34, clue: 'Burial vessel'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'ZOA', number: 35, clue: 'Animal group suffix'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ZIT', number: 35, clue: 'Something to put cream on'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SNOW', number: 36, clue: 'Canadian one-hit wonder with "Informer"'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SHUL', number: 36, clue: 'Place that it wouldn\'t kill you to go one of these Fridays, or maybe you think you\'re too important for G-d now?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'HOPAGAINSTHOP', number: 37, clue: 'Potato sack race, essentially?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'HOJO', number: 37, clue: 'Dwindling restaurant/hotel franchise'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'OMAN', number: 38, clue: 'Nation on its own gulf'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'AID', number: 39, clue: 'Pitch in'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'THATCH', number: 40, clue: 'Vegetative roof covering'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MOMS', number: 41, clue: 'Raisers'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'MAI', number: 41, clue: 'Month after avril'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'WIT', number: 42, clue: 'Clever person'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'SHU', number: 43, clue: 'Moo ___ pork'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'AJA', number: 44, clue: '1977 Steely Dan title track'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'SAD', number: 45, clue: 'In a blue state?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SKIMPS', number: 45, clue: 'Is a skinflint'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'DIALOGS', number: 46, clue: 'Powwows'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'DONUTS', number: 46, clue: 'Objects of Homer\'s desire'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'OKAFOR', number: 47, clue: '2005 Rookie-of-the-Year power forward Emeka'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'GASLOG', number: 48, clue: 'Fake flame maker'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'SATYRS', number: 49, clue: 'Lecherous man-goat hybrids'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IONSKY', number: 50, clue: 'Charged air?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'SLOSH', number: 51, clue: 'Bathtime noise'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'MONT', number: 52, clue: 'Blanc or Saint-Michel'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'MOONS', number: 52, clue: 'Bottoms out?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'KAA', number: 53, clue: '"The Jungle Book" python'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'LISTON', number: 54, clue: 'Victim of a 1965 "phantom punch"'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'TTOP', number: 55, clue: 'Firebird feature'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'CHAST', number: 56, clue: 'Longtime New Yorker cartoonist Roz'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'HYPO', number: 57, clue: 'Small syringe, for short'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CAROM', number: 58, clue: 'Pool glance'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'CCS', number: 58, clue: 'Includes indirectly, in a way'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ARI', number: 59, clue: '"Entourage" character played by Jeremy Piven'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'RIG', number: 60, clue: 'Semi'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'TOUCHYFLY', number: 61, clue: 'Sensitive tsetse?'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'COT', number: 62, clue: 'No-frills bed'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CRISP', number: 63, clue: 'Like tempura'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ONTO', number: 64, clue: 'Not fooled by'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'POOR', number: 65, clue: 'Destitute'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SIGHS', number: 66, clue: 'Controversial 2000 debate sounds from Al Gore'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'PSST', number: 67, clue: '"___! Pass it on ... "'))
clues_Dropping_E_CR_8_28_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ORGS', number: 68, clue: 'AAA and BBB, e.g.'))
Puzzle.create(title: 'Dropping E', grid: 'AIMS.UPON.AFLAC|INAT.RATA.CLIMB|KARATBLTS.TYPOS|MTIDA.LORAIN...|AUS.NGOS.SINWAV|NBASTAR.CSI.IPO|...URN.ZOA.SNOW|.HOPAGAINSTHOP.|MOMS.WIT.SHU...|AJA.SAD.DIALOGS|IONSKY.MONT.KAA|...LISTON.CHAST|CAROM.TOUCHYFLY|CRISP.ONTO.POOR|SIGHS.PSST.ORGS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/8/28', entries: clues_Dropping_E_CR_8_28_08)
