clues_Entanglements_CR_12_11_08 = Array.new
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CANAL', number: 1, clue: 'Ear area'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CAMS', number: 1, clue: 'Pic takers'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALEA', number: 2, clue: '"___ jacta est" ("The die is cast")'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NINJUTSU', number: 3, clue: 'Stealthy martial art'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ATLANTA', number: 4, clue: '"Real Housewives" city'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'LOOKTO', number: 5, clue: 'Rely on'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'EHS', number: 6, clue: 'Sounds of mild displeasure'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EDGESOUT', number: 6, clue: 'Beats by a hair'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HEALTHY', number: 7, clue: 'In good shape'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SARGES', number: 8, clue: 'Some noncoms, casually'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'CRAIG', number: 9, clue: 'Michelle Obama sibling Robinson'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CHER', number: 9, clue: 'Chastity Bono\'s mom'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'RON', number: 10, clue: 'Marginal 2008 candidate Paul'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AROMAS', number: 11, clue: 'Emanations from the kitchen'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'INHALE', number: 12, clue: 'Take in the air?'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'GYMRAT', number: 13, clue: 'Lifting regular'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALITO', number: 14, clue: 'Nominee after Miers'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'DEA', number: 15, clue: 'Narc\'s org.'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'HORNY', number: 16, clue: 'Ready to go, in a way'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MENLO', number: 17, clue: '___ Park, New Jersey (noted invention site)'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'GARDENOHM', number: 18, clue: 'Source of power for horticultural equipment?'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'DAD', number: 19, clue: 'Alternative when 47-Down fails to respond'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SAJAK', number: 20, clue: 'Cohost with White since 1982'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'ELGAR', number: 21, clue: '"Pomp and Circumstance" composer'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'MAR', number: 22, clue: 'Defile'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'UNTESTED', number: 23, clue: 'Green'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ENRON', number: 24, clue: 'Company whose code of 45-Down can still be found on thesmokinggun.com'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'GALA', number: 25, clue: 'Ball'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'GEE', number: 25, clue: '"Gosh!"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BUTTONOHS', number: 26, clue: 'Sounds of surprise about some fasteners?'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BUG', number: 26, clue: 'Listening device'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'URN', number: 27, clue: 'Place for ashes'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'RESET', number: 28, clue: 'NES button'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'RUT', number: 28, clue: 'Same old, same old'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'URSA', number: 29, clue: 'Nocturnal bear'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'RUY', number: 30, clue: '___ Lopez (chess opening)'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'QUE', number: 31, clue: 'Spanish "huh?"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'QANDA', number: 31, clue: 'Post-lecture session'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'GNU', number: 32, clue: 'Lion\'s dinner'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'HOT', number: 33, clue: 'Easy on the eyes'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'HAS', number: 33, clue: 'Eats'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'FAT', number: 34, clue: 'Weird Al song that parodied "Bad"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'FOIEGRAS', number: 34, clue: 'Controversial liver dish'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'WII', number: 35, clue: 'Popular 2008 holiday item'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'WEARTHIN', number: 35, clue: 'Get old'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'IDI', number: 36, clue: 'First name in Ugandan dictatorship'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'ISM', number: 37, clue: 'Suffix with sex and class'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'RAN', number: 38, clue: 'Sought a seat'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'RPG', number: 38, clue: '"Dungeons & Dragons," e.g., for short'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'CON', number: 39, clue: 'Large meeting, briefly'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'CANSECO', number: 39, clue: '"Juiced" author Jose'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'OEDS', number: 40, clue: 'British ref. volumes'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ONEACRE', number: 40, clue: 'About 4,047 square meters'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'WHUPS', number: 41, clue: 'Pastes'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'WHEEZE', number: 41, clue: 'Suffer from asthma'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'HUEVOS', number: 42, clue: '___ rancheros (brunch option)'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'UNSENT', number: 43, clue: 'Like e-mail sitting in a draft folder'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'MAIDENAIM', number: 44, clue: 'Finding a knight in shining armor?'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'MAMBOS', number: 44, clue: 'Does a certain ballroom dance'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ETHICS', number: 45, clue: 'See 24-Down'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'HUNG', number: 46, clue: 'Well-endowed, as it were'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'MANEATER', number: 47, clue: 'Hall & Oates #1 hit'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'MOM', number: 47, clue: 'Cry when besieged by a sibling, perhaps'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EES', number: 48, clue: 'Some Caltech grads'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'NOMSG', number: 49, clue: 'Promise on some salty foods'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'NUDE', number: 49, clue: 'Out there, in a way'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'HATHA', number: 50, clue: 'Yoga system'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'HAMS', number: 51, clue: 'They may be smoked'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ATEE', number: 52, clue: '"It fits you to ___!"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EVENUMBER', number: 53, clue: 'Smoothed-out pigment?'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'NEE', number: 54, clue: 'Family tree word'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'ICHAT', number: 55, clue: 'Skype alternative'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ZONED', number: 56, clue: 'Lost focus, with "out"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'OCA', number: 57, clue: 'Andean tuber'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'CRIME', number: 58, clue: 'Battery, e.g.'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ESTEE', number: 59, clue: 'Cosmetics maven Lauder'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SOS', number: 60, clue: 'Rihanna hit subtitled "Rescue Me"'))
clues_Entanglements_CR_12_11_08.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SENSE', number: 61, clue: 'Have a feeling'))
Puzzle.create(title: 'Entanglements', grid: 'CANAL.EHS.CRAIG|ALITO.DEA.HORNY|MENLO.GARDENOHM|SAJAK.ELGAR.MAR|..UNTESTED.GALA|BUTTONOHS.RESET|URSA.RUY.QUE...|GNU.HOT.FAT.WII|...RAN.CON.OEDS|WHUPS.MAIDENAIM|HUNG.MANEATER..|EES.NOMSG.HATHA|EVENUMBER.ICHAT|ZONED.OCA.CRIME|ESTEE.SOS.SENSE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/12/11', entries: clues_Entanglements_CR_12_11_08)
