clues_Going_Green_CR_5_8_08 = Array.new
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SMUG', number: 1, clue: 'Cocksure'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SLABS', number: 1, clue: 'Concrete units'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MICRO', number: 2, clue: 'Start of something small?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'USUAL', number: 3, clue: 'Everyday order, with "the"'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'GAPKIDS', number: 4, clue: 'Clothier for the 5-12 crowd'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'APSES', number: 5, clue: 'Mosaic spots in an abbey, perhaps'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ATV', number: 5, clue: 'Off-roader, for short'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PRIDE', number: 6, clue: 'Gay feeling?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SERIF', number: 7, clue: 'Font decoration'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EATS', number: 8, clue: 'Diner offering'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'STUPOR', number: 9, clue: 'Daze'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'TAGS', number: 10, clue: 'Writes graffiti on'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TELLSOF', number: 10, clue: 'Speaks about'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ATM', number: 11, clue: 'Charger of $2 service fees (give or take)'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'GNU', number: 12, clue: 'Bearded African'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SAM', number: 13, clue: 'Muppet eagle'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LISA', number: 14, clue: 'Leslie who was the first WNBA player to dunk'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'TREAT', number: 15, clue: 'Pay for'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ETNA', number: 16, clue: 'Mountain that houses Vulcan\'s forge, in myth'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ACUP', number: 17, clue: 'First bra, perhaps'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'VIRTUALMUM', number: 18, clue: 'Queen of the internet?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'AENEAS', number: 19, clue: 'Virgil subject'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BRAKE', number: 20, clue: 'Deceleratrix (a la Mr. Burns)'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'EDU', number: 21, clue: '.gov relative'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'DISPEL', number: 22, clue: 'Put to rest, as a rumor'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SOLIDREF', number: 23, clue: 'Consistent court arbiter?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'RBIS', number: 24, clue: 'Cleanup hitter\'s goals'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'ONSALE', number: 25, clue: 'Marked down'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'ALOOF', number: 26, clue: 'Too cool'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'LAUDE', number: 27, clue: 'Diploma word'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'EELED', number: 28, clue: 'Caught congers'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'DUB', number: 29, clue: 'Jamaican genre with ample echo and delay'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'AREOLAE', number: 30, clue: 'Certain erogenous zones, anatomically'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'AXED', number: 30, clue: 'Canned'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SASS', number: 31, clue: 'Give lip to'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'SIDEB', number: 31, clue: 'Cassette half'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ARENO', number: 32, clue: '"Senator, you ___ Jack Kennedy"'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'SKIRT', number: 33, clue: 'Frequent subject of dress code regulations'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'IMAX', number: 34, clue: '"Magnificant Desolation: Walking on the Moon 3D" theater'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'MEAD', number: 35, clue: 'Homemade wine'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ALI', number: 36, clue: '"The Greatest"'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'AFOUL', number: 37, clue: 'Run ___ of'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IRK', number: 38, clue: 'Get to'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'USELESS', number: 39, clue: 'Environmental slogan, or a hint to this puzzle\'s theme answers'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'UNBORN', number: 39, clue: 'Not yet delivered'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'SELF', number: 40, clue: 'Type of love or satisfaction'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ODE', number: 41, clue: 'Paean'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'DEIGN', number: 42, clue: 'Condescend'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'GOTOGUY', number: 43, clue: 'One who can be counted on'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'AIDE', number: 44, clue: 'Number two'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'KFED', number: 45, clue: 'Britney\'s ex, in tabloids'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'KILLJOY', number: 45, clue: 'Party pooper'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ENROBED', number: 46, clue: 'Attired'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'EMDASH', number: 47, clue: 'Editor\'s insert'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'LII', number: 48, clue: 'Caesar\'s 52'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IFA', number: 49, clue: '"___ tree falls ..."'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BOTTOM', number: 50, clue: 'Bum'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'WAFFLEHO', number: 51, clue: '"Avast, prepare the syrup!"?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'WATER', number: 51, clue: 'Sink stuff'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ALPES', number: 52, clue: 'Suisse range'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'ELOPE', number: 53, clue: 'Get hitched in Reno, maybe'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'HOSEA', number: 54, clue: 'Bible book after Daniel'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'OWENS', number: 55, clue: 'Sprinter Jesse who embarrassed Hitler'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'ORDEAL', number: 56, clue: 'Major hassle'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'ENTO', number: 57, clue: 'Within: Prefix'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'ALLOW', number: 58, clue: 'Sanction'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PREGNANTPA', number: 59, clue: 'Biologically confusing situation down on the farm?'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'PBS', number: 59, clue: 'Station subject to persistent federal budget cuts'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'REP', number: 60, clue: 'Public image, briefly'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'EAR', number: 61, clue: 'Add one letter, and you have an explanation of what it does'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'APE', number: 62, clue: 'Bonobo, e.g.'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'JOSE', number: 63, clue: '"Juiced" author Canseco'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BEAU', number: 64, clue: 'Date for the prom, say'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'STEEP', number: 65, clue: 'Sharply inclined'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'OPEN', number: 66, clue: 'Release the contents of'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SPRY', number: 67, clue: 'Quick and nimble'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'HORSE', number: 68, clue: 'Mount'))
clues_Going_Green_CR_5_8_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'YEAS', number: 69, clue: 'Pro votes'))
Puzzle.create(title: 'Going Green', grid: 'SMUG.APSES.TAGS|LISA.TREAT.ETNA|ACUP.VIRTUALMUM|BRAKE.DISPEL...|SOLIDREF.ONSALE|...DUB..AREOLAE|SASS.IMAX.AFOUL|IRK.USELESS.ODE|DEIGN.AIDE.KFED|ENROBED..LII...|BOTTOM.WAFFLEHO|...ORDEAL.ALLOW|PREGNANTPA.JOSE|BEAU.STEEP.OPEN|SPRY.HORSE.YEAS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/5/8', entries: clues_Going_Green_CR_5_8_08)
