clues_Holding_Water_CR_12_18_08 = Array.new
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'OAKS', number: 1, clue: 'Golf course trees'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'OBLA', number: 1, clue: 'Di or da preceder, in a Beatles song'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARUG', number: 2, clue: 'Cut ___ (get down, in a way)'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'KINGJAMES', number: 3, clue: 'Sobriquet for Lebron'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SOCIETY', number: 4, clue: 'High-class people'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'STAG', number: 5, clue: 'Unaccompanied'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'SHH', number: 5, clue: '"This is a library!"'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TAO', number: 6, clue: 'Eastern "way"'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ARUSH', number: 7, clue: '"What ___!" ("Whoa!")'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'GIRTHS', number: 8, clue: 'Porn stars\' specs'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'COILS', number: 9, clue: 'See 69-Across'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CDS', number: 9, clue: 'Some coasters, before being scratched'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'OJTRIAL', number: 10, clue: '1995 TV mega-event, repeated more quietly in 2008'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ISAID', number: 11, clue: '"To repeat ..."'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LEICA', number: 12, clue: 'Nikon rival'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'STRAY', number: 13, clue: 'Uncollared one'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BRIO', number: 14, clue: 'Dash'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HARI', number: 15, clue: 'Mata ___'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'DJSET', number: 16, clue: 'Spinning round?'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LUNCHHOUR', number: 17, clue: 'Time that may be spent at one\'s desk'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'HEWS', number: 18, clue: 'Chops down'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'STAIR', number: 19, clue: 'Flight unit?'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AGGIE', number: 20, clue: 'Texas A & M athlete'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'STD', number: 21, clue: 'Something to notify one\'s partner about: Abbr.'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'DOH', number: 22, clue: 'Noted cartoon catchphrase'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'RICA', number: 23, clue: 'Costa ___'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'JEWISHHOLIDAY', number: 24, clue: 'Simchat Torah, e.g.'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'IMRE', number: 25, clue: '2002 Literature Nobelist Kert&#233;sz'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'SETI', number: 26, clue: 'Stargazing org.'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'LIAO', number: 27, clue: 'Belligerent Chinese dynasty until 1125'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BEATSME', number: 28, clue: '"How should I know?"'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BASH', number: 28, clue: 'Soiree'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ERIE', number: 29, clue: 'HOMES part'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'SHIA', number: 30, clue: 'Islamic denomination'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARMY', number: 31, clue: 'One may be standing'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'RTE', number: 32, clue: 'AAA offering'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'EGG', number: 33, clue: 'One may get laid on the farm'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ALPHA', number: 34, clue: 'Certain male'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'PANSEXUAL', number: 35, clue: 'Into anyone, potentially'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'HOOT', number: 36, clue: 'Holler partner'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ALPS', number: 37, clue: 'European peaks'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SIE', number: 38, clue: '"Sprechen ___ Deutsch?"'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'HEIGHHO', number: 39, clue: 'Dwarf refrain'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'HEAT', number: 39, clue: 'One of four NBA teams with a non-plural nickname'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'HOAR', number: 40, clue: 'Icy coating'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'HARM', number: 41, clue: 'Medical motto word'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'AOL', number: 42, clue: 'Company with a notoriously painful cancellation process'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'HESSE', number: 43, clue: '"Siddhartha" author'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'SAWZALL', number: 44, clue: 'Multipurpose blade, commercially'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'GOA', number: 45, clue: 'Electronic genre developed in India'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'MNOP', number: 46, clue: 'Pre-Q queue'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'MINIONS', number: 46, clue: 'Movie villain\'s henchmen'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'AARP', number: 47, clue: '50-and-over org.'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'RHO', number: 48, clue: 'Sorority letter'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'PHOBIA', number: 49, clue: 'Irrational anxiety'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ARTISTS', number: 50, clue: 'Creative types'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'TOSH', number: 51, clue: 'Dreadlocked Peter'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'GROWTHHORMONE', number: 52, clue: 'Substance used by some in baseball\'s Mitchell Report'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'GLOAT', number: 52, clue: 'Dance in the end zone, say'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ROSIE', number: 53, clue: 'O\'Donnell who hosted a widely panned 2008 Thanksgiving variety special'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'OLMOS', number: 54, clue: 'Edward James of "Stand and Deliver"'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'OPALS', number: 55, clue: 'October birthstones'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LOLZ', number: 56, clue: 'Amused Twitter term'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'OOP', number: 57, clue: 'Alley ___'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'SIXAM', number: 58, clue: 'Schoolteacher\'s wake-up time, often'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ASIA', number: 59, clue: 'Brunei\'s locale'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'MELT', number: 60, clue: 'Wrap alternative'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OSMAN', number: 61, clue: 'Ottoman dynasty founder'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'NIA', number: 62, clue: 'TV actress Peeples'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'BATHHOUSE', number: 63, clue: 'Gay pickup spot, in some cases'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'TIP', number: 64, clue: 'Good thing that comes to those who wait?'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'HAS', number: 65, clue: 'Suffers from'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AIOLI', number: 66, clue: 'Vowel-laden French sauce'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ILIA', number: 67, clue: 'Hip parts'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'NAIL', number: 68, clue: 'Screw'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'TESLA', number: 69, clue: 'With 9-Across, certain science museum displays'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'ASPS', number: 70, clue: 'Hooded snakes'))
clues_Holding_Water_CR_12_18_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SLAT', number: 71, clue: 'Blind part'))
Puzzle.create(title: 'Holding Water', grid: 'OAKS.STAG.COILS|BRIO.HARI.DJSET|LUNCHHOUR.STAIR|AGGIE..STD.RICA|..JEWISHHOLIDAY|BEATSME.SHIA...|ARMY.RTE..ALPHA|SIE.HEIGHHO.AOL|HESSE..GOA.MNOP|...AARP.ARTISTS|GROWTHHORMONE..|LOLZ.OOP..SIXAM|OSMAN.BATHHOUSE|AIOLI.ILIA.NAIL|TESLA.ASPS.SLAT', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/12/18', entries: clues_Holding_Water_CR_12_18_08)
