clues_Ladies_and_Gentlemen_CR_10_16_08 = Array.new
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'IDES', number: 1, clue: 'March time'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'INST', number: 1, clue: 'Part of MIT'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'DEER', number: 2, clue: 'Highway crosser'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'EXXONJOHN', number: 3, clue: 'Sobriquet in an Obama ad about tax breaks for oil companies'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'STYLE', number: 4, clue: '___ points'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'PAW', number: 5, clue: 'Something to "shake" with'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'PEAS', number: 5, clue: 'Pod things'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'AMC', number: 6, clue: 'Big name in theatres'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'WOK', number: 7, clue: 'Cooking vessel that may be seasoned'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'ROOS', number: 8, clue: 'Footwear brand with pockets, briefly'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'REFIND', number: 8, clue: 'Discover anew'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'OXYMORON', number: 9, clue: 'Original copies, e.g.'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'OLOF', number: 10, clue: 'Former Swedish P.M. Palme'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SADIE', number: 11, clue: '___ Hawkins Day'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NEXT', number: 12, clue: 'Shout in the waiting room'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'EMO', number: 13, clue: 'Genre associated with complicated haircuts'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'EXLAX', number: 14, clue: '"Smooth move, ___!"'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 2, col: 14, dir: 'Down', answer: 'XOXO', number: 15, clue: 'Hugs and kisses, symbolically'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SEXYBACK', number: 16, clue: '#1 hit for Justin Timberlake'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'BLEW', number: 17, clue: 'Was really lame'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'FYODOR', number: 18, clue: 'Existentialist Dostoyevsky'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 3, col: 15, dir: 'Down', answer: 'RXS', number: 19, clue: 'Narcotics notes, casually'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'TROLLS', number: 20, clue: 'Bloggers\' annoyances'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'JIMFIXX', number: 21, clue: '"The Complete Book of Running" author'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'JAR', number: 21, clue: 'Bell or Mason'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'NEE', number: 22, clue: 'Society page word'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'URANO', number: 23, clue: 'Word form for \'\'heavens\'\''))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'UZIS', number: 23, clue: 'Some 9mm guns'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RAP', number: 24, clue: 'Hip-hop element'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'EOS', number: 25, clue: 'Canon SLR camera'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'HAJ', number: 26, clue: 'Trip to Mecca'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'HAUL', number: 26, clue: 'Schlep'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ACNE', number: 27, clue: 'Teenage spots?'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'WIZARDRY', number: 28, clue: 'Mad skills, as it were'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'INK', number: 29, clue: 'Substance of a newspaper article?'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'YNEZ', number: 30, clue: 'California\'s Santa ___ Valley'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ACOW', number: 31, clue: '"Don\'t have ___ ... "'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'WOOD', number: 32, clue: 'Iron alternative'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'NIP', number: 33, clue: 'Tuck\'s partner'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ONPBS', number: 34, clue: 'Where Gwen Ifill\'s "Washington Week" airs'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'PROXYVOTE', number: 35, clue: 'Option for a traveling politician'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'BANE', number: 36, clue: 'Garlic, to a vampire'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SLED', number: 37, clue: 'Toy with runners'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'UNHOOKS', number: 38, clue: 'Detaches, as a bra'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'OXYGENIC', number: 39, clue: 'Like some photosynthesis'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'FUNERAL', number: 40, clue: 'Final event?'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'FOXY', number: 40, clue: 'Fine'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'UNI', number: 41, clue: 'Athlete\'s outfit, briefly'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LENOX', number: 42, clue: 'Big name in china'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'WON', number: 43, clue: 'Took'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'WED', number: 43, clue: 'Take, and be taken by, someone with whom you\'re taken'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ZONE', number: 44, clue: 'Make commercial, say'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'DYSLEXIA', number: 45, clue: 'Character issue?'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'SINGES', number: 46, clue: 'Barely burns'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'LDS', number: 47, clue: 'Mormons, for short'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ABUD', number: 48, clue: '"Nothing beats ___"'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'XED', number: 49, clue: 'Crossed (out)'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'EES', number: 50, clue: 'Some MIT grads'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'EXO', number: 50, clue: 'Prefix with -skeleton'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'EXAM', number: 51, clue: 'Midterm, e.g.'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'STRAP', number: 52, clue: 'Guitar holder'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'GIDDY', number: 53, clue: 'Elated'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'BAY', number: 54, clue: 'Old ___ Seasoning'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'AMFAR', number: 55, clue: 'HIV research org.'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'XXTEENS', number: 56, clue: 'British dance-punk band with "Welcome to Goon Island"'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'EIRE', number: 57, clue: 'Ireland, to the Irish'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'HUMVEE', number: 58, clue: 'High Mobility Multipurpose Wheeled Vehicle, more commonly'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'HDTV', number: 58, clue: 'Clear medium for watching NFL games'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'EXOD', number: 59, clue: 'Torah book after Gen.'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'EXPO', number: 60, clue: 'Trade show'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OARING', number: 61, clue: 'Hanging with one\'s crew?'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'REDDFOXX', number: 62, clue: 'Fred Sanford portrayer'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'RAD', number: 62, clue: 'Cult film about BMX racing'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ELM', number: 63, clue: 'Wes Craven street name'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 14, col: 2, dir: 'Across', answer: 'MARIE', number: 64, clue: 'Presley\'s middle name'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ALT', number: 65, clue: '___-country'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ATOP', number: 66, clue: 'Perched on'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 15, col: 3, dir: 'Across', answer: 'PECS', number: 67, clue: 'Bodybuilders may work on them'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'DMV', number: 68, clue: 'Place with long lines, stereotypically: Abbr.'))
clues_Ladies_and_Gentlemen_CR_10_16_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'REDO', number: 69, clue: 'Second chance'))
Puzzle.create(title: 'Ladies and Gentlemen', grid: 'IDES.PAW.ROOS..|NEXT.EMO.EXLAX.|SEXYBACK.FYODOR|TROLLS..JIMFIXX|..NEE.URANO.EOS|HAJ.WIZARDRY...|ACOW.NIP..ONPBS|UNHOOKS.FUNERAL|LENOX..WON.ZONE|...DYSLEXIA.XED|EES.GIDDY.BAY..|XXTEENS..HUMVEE|OARING.REDDFOXX|.MARIE.ALT.ATOP|..PECS.DMV.REDO', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/10/16', entries: clues_Ladies_and_Gentlemen_CR_10_16_08)
