clues_Mouth_Pieces_CR_5_15_08 = Array.new
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'UPDOS', number: 1, clue: 'Some prom haircuts'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'USA', number: 1, clue: '___ Today'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PEZ', number: 2, clue: 'Collectible candy'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'DRUMBEAT', number: 3, clue: 'It should be in time for a concert'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OGRE', number: 4, clue: 'Gross, overbearing sort'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SEEM', number: 5, clue: 'Look or sound'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'PSSST', number: 6, clue: '"Hey ... buddy"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'POLEVAULT', number: 6, clue: 'Event with an approach and a takeoff'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SMORE', number: 7, clue: 'Camping unit'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SAMSA', number: 8, clue: '"As Gregor ___ awoke one morning from uneasy dreams ...": Kafka'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SHAH', number: 9, clue: 'Irani sovereign'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TAXI', number: 10, clue: 'Quick way uptown, perhaps'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ISS', number: 11, clue: 'Newsstand no.'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'IPECAC', number: 11, clue: 'Poison remedy'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SERAPH', number: 12, clue: 'Cherub\'s counterpart'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SNAPTO', number: 13, clue: 'Return suddently to awareness'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'SERGE', number: 14, clue: 'Sleazy songwriter Gainsbourg'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OMAHA', number: 15, clue: 'Poker variant'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'PEN', number: 16, clue: 'Author'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'AZURE', number: 17, clue: 'Sky blue'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'LOMAX', number: 18, clue: 'Alan who recorded Woody Guthrie'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ERA', number: 19, clue: 'Stat next to WHIP and K\'s'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 4, col: 3, dir: 'Across', answer: 'MEMBERSHIPCAP', number: 20, clue: 'Exclusive group\'s limit, or dental restoration required to get into a club?'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'BUR', number: 21, clue: 'Thing that may stick in a fur coat'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'PRY', number: 22, clue: 'Use a crowbar'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DOB', number: 23, clue: 'DMV info'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'DQS', number: 23, clue: 'Blizzard sellers, for short'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'OUT', number: 24, clue: 'Like a secret that\'s no longer secret'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'UVEA', number: 25, clue: 'Visual layer'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'RAPT', number: 26, clue: 'Entranced'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'QUESERA', number: 27, clue: '"Whatever will be"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'SIR', number: 28, clue: 'Mick Jagger, for one'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ERIKA', number: 29, clue: 'Soap Emmy-winner Slezak'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'PSYCHO', number: 30, clue: 'Batshit crazy'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'PER', number: 30, clue: 'A pop'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'STOIC', number: 31, clue: 'Even-keeled'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'STAIR', number: 32, clue: 'Flight segment'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'UPSET', number: 33, clue: 'Miffed'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'PEI', number: 34, clue: 'Ieoh Ming ____'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'SCENERIES', number: 35, clue: 'Sets'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'TRIPLECROWN', number: 36, clue: 'Racing rarity, or a multi-tooth restoration?'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'PAX', number: 37, clue: 'Family-friendly station that became ION Television in 2007'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'WVA', number: 38, clue: 'Penn. neighbor'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'NINTENDO', number: 39, clue: 'Company not-so-subtly advertised for in "The Wizard"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'KATIE', number: 40, clue: 'Suri\'s mom'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'IVIES', number: 41, clue: 'Brown et al.'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'EDU', number: 42, clue: 'College URL ending'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'SOX', number: 43, clue: 'South Side squad, briefly, with "the"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'GASTAX', number: 44, clue: 'Presently controversial campaign issue'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'GANESH', number: 44, clue: 'Well-armed deity?'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ALASKA', number: 45, clue: 'Russian neighbor'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'SITPAT', number: 46, clue: 'Lie in wait, perhaps'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'TAU', number: 47, clue: 'Greek cross'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'NOCANDO', number: 48, clue: '"Sorry, Charlie"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ORI', number: 49, clue: '" ... ___ will turn this car right around"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ALIA', number: 50, clue: 'Inter ___'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'BEER', number: 51, clue: 'Heady stuff?'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'BLINI', number: 51, clue: 'Moscow street food'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'EBBED', number: 52, clue: 'Flowed back'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'TUX', number: 53, clue: 'Men\'s Wearhouse purchase'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'NATURALBRIDGE', number: 54, clue: 'Virginia landmark, or a dental restoration that occurs on its own?'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'RARA', number: 55, clue: '___ avis'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'ALEC', number: 56, clue: 'Portrayer of Jack on "30 Rock"'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'DRIP', number: 57, clue: 'Faucet issue'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'GENE', number: 58, clue: 'It may express itself'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ESP', number: 59, clue: 'Uncommon sense'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'ALIBI', number: 60, clue: '"I was sleeping at the time," e.g.'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'RENEW', number: 61, clue: 'Keep getting'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'EIN', number: 62, clue: 'A, as in Austria'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'WES', number: 63, clue: 'First name in horror films'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SKA', number: 64, clue: 'Genre once associated with No Doubt'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'RENEE', number: 65, clue: 'Golden Globe-winner Zellweger'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'INDIE', number: 66, clue: 'Film festival selection, often'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HAT', number: 67, clue: 'Bowler, e.g.'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ACIDS', number: 68, clue: 'Litmus test materials'))
clues_Mouth_Pieces_CR_5_15_08.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'PEONS', number: 69, clue: 'Doers of dirty jobs'))
Puzzle.create(title: 'Mouth Pieces', grid: 'UPDOS.PSSST.ISS|SERGE.OMAHA.PEN|AZURE.LOMAX.ERA|..MEMBERSHIPCAP|DOB..UVEA..RAPT|QUESERA..PSYCHO|STAIR.UPSET....|..TRIPLECROWN..|....KATIE.IVIES|GASTAX..NOCANDO|ALIA..BEER..TUX|NATURALBRIDGE..|ESP.ALIBI.RENEW|SKA.RENEE.INDIE|HAT.ACIDS.PEONS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/5/15', entries: clues_Mouth_Pieces_CR_5_15_08)
