clues_October_Surprise_CR_10_30_08 = Array.new
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'REBAG', number: 1, clue: 'Organize differently, as groceries'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'REBUS', number: 1, clue: '\'\'Concentration\'\' puzzle'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ENEMA', number: 2, clue: 'Colon cleanser, perhaps'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BEEPS', number: 3, clue: 'Sounds from a truck backing up'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ARB', number: 4, clue: 'Wooded area, casually'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'GOOIER', number: 5, clue: 'Comparatively fresh from the oven, as brownies'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'AGAME', number: 6, clue: 'Maximum ability, so to speak'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ASST', number: 6, clue: 'Sec\'y, e.g.'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GOTAB', number: 7, clue: 'Did OK on the test'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AMIGOS', number: 8, clue: 'Pals'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MANSON', number: 9, clue: 'Charles or Marilyn'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ESG', number: 10, clue: 'Much-sampled South Bronx band'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'VJS', number: 11, clue: 'TRL hosts, e.g.'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'VOCAL', number: 11, clue: 'Like some minorities'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'JUNTA', number: 12, clue: 'Coup group'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SINEW', number: 13, clue: 'Tendon'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ENERO', number: 14, clue: 'Bolivian month'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'SOMAS', number: 15, clue: '"Brave New World" ingestions'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'OUI', number: 16, clue: 'Non\'s opposite'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BEEBOOSTING', number: 17, clue: 'Working for the apiarists\' lobby?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'ODDSON', number: 18, clue: 'Heavy, as a favorite'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'CNN', number: 19, clue: 'Campbell Brown\'s channel'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'UMP', number: 20, clue: 'Worker behind the plate'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'IDTAGS', number: 21, clue: 'Luggage differentiators'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'CATE', number: 22, clue: 'Blanchett who played Katharine Hepburn'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'CYBERSEX', number: 22, clue: 'Second Life hookup'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SASSED', number: 23, clue: 'Gave lip to'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'SOLOACTS', number: 24, clue: 'One-man bands, e.g.'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'BOOBYLAW', number: 25, clue: 'Rule regarding seabirds?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'BOZO', number: 26, clue: 'Goofball'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ORSO', number: 27, clue: 'Ballpark phrase?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'OLD', number: 28, clue: 'Like stuff in the attic, often'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'SNOB', number: 29, clue: 'Record-store clerk, stereotypically'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'PHIL', number: 30, clue: 'Dr. who got his start on "Oprah"'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'PBA', number: 30, clue: 'Alley org.'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'HAW', number: 31, clue: 'Hee follower'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'IBM', number: 32, clue: 'Company with a major subsidiary in India'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'OLE', number: 33, clue: '___ Miss'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'EEK', number: 34, clue: '[Horrors!]'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ZETAS', number: 35, clue: 'Some sorority women'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'TAE', number: 36, clue: '___ kwon do'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ANN', number: 37, clue: 'Taylor or Landers'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'STD', number: 38, clue: 'Result of a rubber shortage?: Abbr.'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'BABOONDEODORANT', number: 39, clue: 'Source of lavender scent from the primate cage?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'ONUP', number: 40, clue: 'Mayfield\'s "Move ___"'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'OOH', number: 41, clue: 'Air show reaction'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'DAYSPA', number: 42, clue: 'Place for a facial'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'AWMAN', number: 43, clue: '"Shoo-oot ..."'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'KOA', number: 44, clue: 'Big name in low-stress camping'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'SEND', number: 45, clue: 'Gmail button'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'CURT', number: 46, clue: 'Short'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'RAKEIN', number: 47, clue: 'Make hand over fist'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'TIRADE', number: 48, clue: 'Rant'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'HYDE', number: 49, clue: 'David ___ Pierce'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'DISBAR', number: 50, clue: 'Kick out of practice'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BOOTPAIN', number: 51, clue: 'Result of failing to break in your Timberlands?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'BURKA', number: 51, clue: 'Modest covering'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'OSCAR', number: 52, clue: 'Scorer\'s award, perhaps'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'OESTE', number: 53, clue: '270&#176; from norte'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'NUDER', number: 54, clue: 'Closer to being in the buff'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'SIXGUN', number: 55, clue: 'Shooting iron'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'GROGS', number: 56, clue: 'Rum recipes'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'UPSET', number: 57, clue: 'Out of sorts'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'NIELS', number: 58, clue: 'Manhattan Project member Bohr'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'USES', number: 59, clue: 'Exploits'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'KRUMPS', number: 60, clue: 'Dances in a clown suit, perhaps'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'MCAT', number: 61, clue: 'Future GP\'s exam'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'RPI', number: 62, clue: 'Sch. with the nickname the Engineers'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RCS', number: 63, clue: 'Some driverless cars, for short'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'HEADCABOOSE', number: 64, clue: 'Leading final car?'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'HSI', number: 64, clue: 'Chinese philosopher Chu ___'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ONE', number: 65, clue: '"That ___"'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'KAT', number: 66, clue: 'Dennings of "Nick and Norah\'s Infinite Playlist"'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'SIDEA', number: 67, clue: '45 half'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ANGEL', number: 68, clue: '"Buffy" spin-off'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ARE', number: 69, clue: '"___ you sure?"'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'INERT', number: 70, clue: 'Couchbound, perhaps'))
clues_October_Surprise_CR_10_30_08.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'RESTS', number: 71, clue: 'Silent markings'))
Puzzle.create(title: 'October Surprise', grid: 'REBAG.AGAME.VJS|ENERO.SOMAS.OUI|BEEBOOSTING.CNN|UMP.IDTAGS.CATE|SASSED.BOOBYLAW|...ORSO.SNOB...|PHIL.OLE..ZETAS|BABOONDEODORANT|AWMAN..KOA.SEND|...CURT.HYDE...|BOOTPAIN.SIXGUN|USES.KRUMPS.RPI|RCS.HEADCABOOSE|KAT.SIDEA.ANGEL|ARE.INERT.RESTS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/10/30', entries: clues_October_Surprise_CR_10_30_08)
