clues_Reinventing_the_Wheel_CR_8_21_08 = Array.new
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TJMAXX', number: 1, clue: 'Off-price clothing retailer'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TBTEST', number: 1, clue: 'The state of New York might make you get one after you were on a plane back from Hong Kong with this guy who couldn\'t stop coughing'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'JAUNTS', number: 2, clue: 'Jet-setter\'s trips'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MRBILL', number: 3, clue: 'Play-Doh character late of "SNL"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ARES', number: 4, clue: 'Greek war deity'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'XIS', number: 5, clue: 'Sorority letters'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'XOUTS', number: 6, clue: 'Editor\'s strikes'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'LAPD', number: 7, clue: 'Conservative radio host Mark Fuhrman\'s former employer: Abbr.'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'LAFF', number: 7, clue: 'Roll in the aisles, on comedy show fliers'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ALE', number: 8, clue: 'Beverage whose homonym describes what you\'ll do if you drink too much of it'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PARSI', number: 9, clue: 'Zoroastrian'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DISARM', number: 10, clue: 'Take a piece from?'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'PCT', number: 11, clue: '%, for short'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PRISONER', number: 11, clue: 'Guest of the state'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CAROUSEL', number: 12, clue: 'Fair sight'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'THESTAND', number: 13, clue: '1994 miniseries adapted from a Stephen King novel'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BARRIO', number: 14, clue: 'One might have a corner bodega'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'ALAI', number: 15, clue: 'Jai ___ (Basque sport)'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'RAH', number: 16, clue: '[What a great home run!]'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TUBESURFERS', number: 17, clue: 'UK subway daredevils'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'RIPA', number: 18, clue: 'Morning hostess Kelly'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'IRE', number: 19, clue: 'Fury'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ENIS', number: 20, clue: 'Disappointing Chicago Bears draft pick Curtis'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'TIF', number: 21, clue: '.bmp cousin'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'SAYSOS', number: 22, clue: 'Final authorities'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'YEE', number: 23, clue: '"___-haw!"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'STL', number: 24, clue: 'The Cards of the N.L. Central'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'ASP', number: 25, clue: 'Egyptian snake'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ATEE', number: 25, clue: 'To ___ (perfectly)'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'TIREOUT', number: 26, clue: 'Exhaust'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'TECH', number: 26, clue: 'Geek, of a sort'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TSLOT', number: 27, clue: 'Letter-shaped opening'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'ORK', number: 28, clue: 'Sitcom planet'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'ABE', number: 29, clue: 'Former Japanese Prime Minister Shinzo'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'BATIK', number: 30, clue: 'Sarong material'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'MENSA', number: 31, clue: 'Group that recently admitted a two-year-old with an IQ of 152'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'REW', number: 32, clue: 'Archaic button on a DVD player: Abbr.'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'WTO', number: 33, clue: 'Gp. that was the object of a noted 1999 protest'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'ACK', number: 34, clue: '"Cathy" exclamation'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'KEY', number: 35, clue: 'Critical'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'EEN', number: 36, clue: 'Hallow ending'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SPOKETOTHEWORLD', number: 37, clue: 'Opened up in front of everybody'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'SPARSEST', number: 37, clue: 'Least numerous, as a crowd'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'POSITRON', number: 38, clue: 'Antimatter particle'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'OXYMORON', number: 39, clue: 'Microsoft Works, according to some'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'OUST', number: 40, clue: 'Give the boot'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'WUSS', number: 41, clue: 'Baby, so to speak'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'OPT', number: 42, clue: 'Go (for)'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'POX', number: 43, clue: 'Curse'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'OUI', number: 44, clue: 'Possible answer to "Do you have foie gras?"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'YUP', number: 45, clue: 'Possible answer to "Do you have cheeseburgers?"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ASYET', number: 46, clue: 'To date'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ESL', number: 47, clue: 'Immigrant\'s course: Abbr.'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'THEBBC', number: 48, clue: 'Telly staple'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'SKA', number: 49, clue: 'Genre for "rude boys"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'AOKI', number: 50, clue: 'Diminutive supermodel Devon'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'STAPH', number: 51, clue: 'Possible infection cause'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ARGOTS', number: 52, clue: 'Jargons'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'PEEWEE', number: 53, clue: 'Character whose portrayer was arrested for indecent exposure in 1991'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'HYENAS', number: 54, clue: 'Cackling scavengers'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RIMSHOT', number: 55, clue: 'Late-night joke accenter'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'ONEUP', number: 56, clue: 'Be fancier than, as in H.O.R.S.E.'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'OHS', number: 57, clue: 'Japanese home run king Sadaharu and actress Sandra'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'HENRY', number: 58, clue: 'French football star Thierry'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'REY', number: 59, clue: 'Spanish king'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'STOLEN', number: 60, clue: 'Hot'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'IKE', number: 61, clue: '"South Park" sibling'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'IRKS', number: 61, clue: 'Gets on the wrong side of'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'AGEE', number: 62, clue: 'Posthumous Pulitzer winner James'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'ADDS', number: 62, clue: 'Does some kindergarten math'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ERR', number: 63, clue: 'Drop the ball'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'BEARINGDOWN', number: 64, clue: 'Focusing'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ALA', number: 65, clue: 'In the style of'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'GEE', number: 66, clue: '"Whillikers!"'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SOO', number: 67, clue: '"Annnnnnyway ..."'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'BULK', number: 68, clue: 'Something to buy beans in'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'REDTEA', number: 69, clue: 'Leaves from South Africa'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'TNN', number: 70, clue: 'Spike, before it was Spike TV'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'CPAS', number: 71, clue: '1040 experts, for short'))
clues_Reinventing_the_Wheel_CR_8_21_08.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'YESSES', number: 72, clue: 'Loyalist\'s answers'))
Puzzle.create(title: 'Reinventing the Wheel', grid: 'TJMAXX.LAPD.PCT|BARRIO.ALAI.RAH|TUBESURFERS.IRE|ENIS.TIF.SAYSOS|STL.ASP.TIREOUT|TSLOT.ABE.MENSA|...REW.ACK..EEN|SPOKETOTHEWORLD|POX..OUI.YUP...|ASYET.SKA.STAPH|RIMSHOT.OHS.REY|STOLEN.IKE.AGEE|ERR.BEARINGDOWN|SOO.BULK.REDTEA|TNN.CPAS.YESSES', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/8/21', entries: clues_Reinventing_the_Wheel_CR_8_21_08)
