clues_So_It_Is_Written_CR_11_6_08 = Array.new
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MOLE', number: 1, clue: 'Plant'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MINTTEA', number: 1, clue: 'Moroccan quaff'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ONEHALF', number: 2, clue: 'Point between plurality and majority'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LIVEJOURNAL', number: 3, clue: 'Popular blogging site since 1999'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ETAL', number: 4, clue: 'Endnotes abbr.'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ARKS', number: 5, clue: 'Torah holders'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ATMFEE', number: 5, clue: 'Charge for money'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ROMEO', number: 6, clue: 'Guy with ample game'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'KREW', number: 7, clue: 'Hip-hop posse'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SOSO', number: 8, clue: 'Just "eh"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'AQUOS', number: 9, clue: 'Sharp LCD TV'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ASADA', number: 9, clue: 'Carne ___'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'QUESTS', number: 10, clue: 'Role-playing ventures'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'USS', number: 11, clue: 'Letters on a vessel'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OHO', number: 12, clue: '"Mystery solved!"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SIP', number: 13, clue: 'Nurse'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'INIT', number: 14, clue: 'Gang of Four\'s "Natural\'s Not ___"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'TORO', number: 15, clue: 'Groundskeeper\'s brand'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'SUSHI', number: 16, clue: 'Rolls for dinner, perhaps'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NEVA', number: 17, clue: 'It has banks in Russia'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'MMES', number: 18, clue: 'Messieurs\' mates: Abbr.'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'AESOP', number: 19, clue: 'Underground rapper ___ Rock'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'THELIFEWOODS', number: 20, clue: 'Thoreau subtitle, read literally'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'INSEAM', number: 21, clue: 'Clothes line?'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ORALB', number: 22, clue: 'Floss maker'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TAJ', number: 23, clue: 'Atlantic City spot, with "the"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'NEO', number: 24, clue: 'Role for Keanu'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'RATSON', number: 25, clue: 'Reports, in a way'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'SKINNYBITCH', number: 26, clue: 'Best-selling diet tract'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'OYL', number: 27, clue: 'Olive ___'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'NYE', number: 28, clue: 'Bill on PBS'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ELOISE', number: 29, clue: 'Plaza Hotel girl'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'ISE', number: 30, clue: 'Suffix with colour'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'MOA', number: 31, clue: 'Extinct kiwi relative'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'MANGA', number: 31, clue: 'Genre often read on the Tokyo metro'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ORGY', number: 32, clue: 'Love fest?'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'SKYY', number: 33, clue: 'Grey Goose alternative'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AFUSE', number: 34, clue: 'Blow ___ (overload the system, in a way)'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'CARLS', number: 35, clue: '___ Jr. (burger chain)'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'CINE', number: 35, clue: 'Art-film theater'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'SUPPED', number: 36, clue: 'Ate, formally'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ILE', number: 37, clue: 'Land in the Seine'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'READINGBURN', number: 38, clue: '2008 Coen Brothers title, read literally'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'DANTE', number: 39, clue: 'He wrote "This way a good soul never passes"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'RUR', number: 40, clue: '1921 Karel Capek play'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BAN', number: 41, clue: 'Criminalize'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'BMW', number: 41, clue: 'Occasional James Bond car'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'ABA', number: 42, clue: 'Litigator\'s org.'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'MANGY', number: 43, clue: 'Hardly a Westminster contender'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'PUNKD', number: 44, clue: 'MTV\'s defunct "Candid Camera" equivalent'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'KEYNOTE', number: 45, clue: 'Type of address'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'DRAGNET', number: 46, clue: 'LAPD drama'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MBAS', number: 47, clue: 'Corp. recruits'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'SNAZZY', number: 48, clue: 'Sharp'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'NEA', number: 49, clue: '"Poetry Out Loud" org.'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'SPRYER', number: 50, clue: 'More young-seeming'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'SINTAX', number: 50, clue: 'Regressive source of revenue, often'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'WALNUT', number: 51, clue: 'Protein source from California'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ULEES', number: 52, clue: '"___ Gold" (1997 Fonda film)'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'LIE', number: 53, clue: 'Make something up'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'LOCUS', number: 53, clue: 'Point'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'BYA', number: 54, clue: 'Words before "nose" or "hair"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'ALESSONDYING', number: 55, clue: 'Ernest Gaines title about racism, read literally'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'STAG', number: 56, clue: 'Just for men'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SAGA', number: 57, clue: 'Epic story'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'YEAR', number: 58, clue: 'Certain rotation'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'JONZE', number: 59, clue: 'Spike who co-directed the video for Kanye\'s "Flashing Lights"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'JBS', number: 59, clue: 'Backup band for the Hardest Working Man in Show Business, with "the"'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'OOO', number: 60, clue: 'Hugs, in text'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'NON', number: 61, clue: 'Smoking alternative'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'TACT', number: 62, clue: 'Negotiation skill'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'ETON', number: 63, clue: 'George Orwell\'s school'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BOOZE', number: 64, clue: 'Hard stuff'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'AGUA', number: 65, clue: 'Water, in spain'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ACTE', number: 66, clue: 'Entr\'___'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SONYS', number: 67, clue: 'Some consumer electronics'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'GASX', number: 68, clue: 'Big name in relief'))
clues_So_It_Is_Written_CR_11_6_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'RHET', number: 69, clue: 'Subj. for Aristotle'))
Puzzle.create(title: 'So It Is Written', grid: 'MOLE.ARKS.AQUOS|INIT.TORO.SUSHI|NEVA.MMES.AESOP|THELIFEWOODS...|TAJ.NEO..RATSON|ELOISE.MOA.SKYY|AFUSE.CARLS.ILE|..READINGBURN..|BAN.MANGY.PUNKD|MBAS.NEA.SPRYER|WALNUT..LIE.BYA|...ALESSONDYING|JONZE.TACT.ETON|BOOZE.AGUA.ACTE|SONYS.GASX.RHET', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/11/6', entries: clues_So_It_Is_Written_CR_11_6_08)
