clues_Straight_As_CR_5_1_08 = Array.new
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'IFSO', number: 1, clue: '"Should that be the case ..."'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'IGUANAS', number: 1, clue: 'Iggy Pop band, before the Stooges'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'FINEART', number: 2, clue: 'Painting or sculpture'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'STIRFRY', number: 3, clue: 'Wok dish'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OST', number: 4, clue: 'D&#252;sseldorf direction'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ONTV', number: 5, clue: 'Live, perhaps'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OLDE', number: 5, clue: 'Ye ___ Shoppe'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'NEWAT', number: 6, clue: 'Not yet used to'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'THEPOPE', number: 7, clue: 'Noted Iraq war critic who recently visited the White House'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'VII', number: 8, clue: 'Number for the 2011 Puppy Bowl'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'TALKS', number: 9, clue: 'Fesses up'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TORN', number: 9, clue: 'Not sure what to do'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ACUT', number: 10, clue: '___ above'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LEBARON', number: 11, clue: 'Bygone Chrysler'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'KALPENN', number: 12, clue: 'John Cho\'s co-star in "Harold & Kumar Escape from Guantanamo Bay"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SNEEZES', number: 13, clue: 'Elicits a blessing, perhaps'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'GITS', number: 14, clue: 'Skedaddles'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'LEHI', number: 15, clue: 'Where Samson slew the Philistines'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'OCEAN', number: 16, clue: 'The Indian, for one'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UNITEDWEI', number: 17, clue: 'Brought an ancient Chinese dynasty together?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ERAS', number: 18, clue: 'Periods'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'RUBLE', number: 19, clue: 'Coin with Cyrillic lettering'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AER', number: 20, clue: 'Fizzy prefix'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'REAP', number: 21, clue: 'Enjoy, as the rewards'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'ONTAPE', number: 22, clue: 'Not live'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'OUI', number: 22, clue: 'Magazine in which Arnold Schwarzenegger discussed having an orgy with other bodybuilders'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NAFTA', number: 23, clue: 'Treaty negotiated by Pres. Clinton'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TEXANS', number: 24, clue: 'Molly Ivins and George Bush, for two'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'TOFU', number: 25, clue: 'It may be silken or firm'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'FEDEX', number: 26, clue: 'DHL competitor'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'REZ', number: 27, clue: 'Tribal land, informally, with "the"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ARREST', number: 28, clue: 'One goes on your record'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'TSK', number: 29, clue: '"For shame!"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'PEIPHONE', number: 30, clue: 'Device for having an I.M. conversation?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'PBA', number: 31, clue: 'Rollers\' org.'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'HANKER', number: 32, clue: 'Yearn'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'STYX', number: 33, clue: '"Mr. Roboto" band'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'SLED', number: 34, clue: 'Vehicle with runners'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'LABEL', number: 35, clue: 'Unsigned musician\'s pursuit'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'BANNS', number: 36, clue: 'Church engagement announcement'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'ASKA', number: 37, clue: '___ Ninja.com (satirical online advice column)'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'STY', number: 38, clue: 'Pen'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'EGAN', number: 39, clue: 'Author Jennifer with "The Keep"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'GYP', number: 40, clue: 'Rip off, politically incorrectly'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'CHANT', number: 41, clue: '"USA!" e.g.'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'CLASPED', number: 41, clue: 'Like the hands of a praying person, often'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'HOVLANE', number: 42, clue: 'Carpooler\'s reward'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'AUGUSTA', number: 43, clue: 'Masters locale'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'BOXY', number: 44, clue: 'Like some modern concept cars'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'OILWELL', number: 45, clue: '"There Will Be Blood" site'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'KOOL', number: 46, clue: 'Parliament opposition?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'ORIGAMI', number: 47, clue: 'Paper tiger, perhaps'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'ORBISON', number: 48, clue: '"Crying" singer'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'LESSENS', number: 49, clue: 'Abates'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'LOUSYLEI', number: 50, clue: 'Flower wreath with rotten petals, say?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'LES', number: 51, clue: 'Longtime CBS head Moonves'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'PIERRE', number: 52, clue: 'U.S. state capital with fewer than 15,000 residents'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IDYL', number: 53, clue: 'Pastoral poem'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'AVG', number: 54, clue: 'Batting title stat'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'ELLE', number: 55, clue: 'Fashion monthly'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ERIES', number: 56, clue: 'People with longhouses, once'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'DRIBS', number: 57, clue: 'Little bits'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SLURPS', number: 58, clue: 'Consumes conspicuously?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'REEL', number: 59, clue: 'Cinema spool'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'PORT', number: 60, clue: 'USB or FireWire plug-in spot'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'WRAY', number: 61, clue: 'Noted film captive Fay'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'APSE', number: 62, clue: 'Church niche'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'GIS', number: 63, clue: 'Jane and Joe'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PASEO', number: 64, clue: 'Toyota vehicle replaced by the Echo'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'SEIPLEASE', number: 65, clue: '"A half dozen eggs, per favore"?'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'SAE', number: 65, clue: 'Freelancer\'s enc.'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ECG', number: 66, clue: 'Hosp. readout'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ENTER', number: 67, clue: 'Input'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ALES', number: 68, clue: 'Sam Adams products'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'CMON', number: 69, clue: '"Let\'s go already!"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DEALT', number: 70, clue: 'Had the button, in poker'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'ELSE', number: 71, clue: '"Or ___ what?"'))
clues_Straight_As_CR_5_1_08.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'GINS', number: 72, clue: 'Tanqueray and Beefeater, e.g.'))
Puzzle.create(title: 'Straight A\'s', grid: 'IFSO.ONTV.TALKS|GITS.LEHI.OCEAN|UNITEDWEI.RUBLE|AER.REAP.ONTAPE|NAFTA.TOFU..REZ|ARREST.PEIPHONE|STYX.SLED.BANNS|...ASKA.EGAN...|CHANT.BOXY.KOOL|LOUSYLEI.PIERRE|AVG..ELLE.DRIBS|SLURPS.WRAY.GIS|PASEO.SEIPLEASE|ENTER.ALES.CMON|DEALT.ELSE.GINS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/5/1', entries: clues_Straight_As_CR_5_1_08)
