clues_Triple_Scramble_CR_9_11_08 = Array.new
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AMAID', number: 1, clue: 'Neil Young\'s "A Man Needs ___"'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ARCO', number: 1, clue: 'BP subsidiary'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MAUL', number: 2, clue: 'Really dig one\'s teeth into?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ANTE', number: 3, clue: 'Throw some coins on the table, maybe'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'IDES', number: 4, clue: 'Bad time of the month'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DIRTBALL', number: 5, clue: 'Scumbag'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'DARC', number: 6, clue: 'Ste. Jeanne ___'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'DORAG', number: 6, clue: 'Bit of attire for Hulk Hogan'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'APU', number: 7, clue: 'Nahasapeemapetilon of Springfield'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'REC', number: 8, clue: 'Dictation machine abbr.'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'CLEAVAGE', number: 9, clue: 'Rack display?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'CBGB', number: 10, clue: 'Bowery club now occupied by a clothing boutique'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CHER', number: 10, clue: 'Noted user of Auto-Tune'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BACO', number: 11, clue: 'Bit on a salad'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'GRUB', number: 12, clue: 'Chicken feed'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BETE', number: 13, clue: '"La Belle et la ___"'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'RANDI', number: 14, clue: 'Magician James'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OPEL', number: 15, clue: 'Autobahn auto'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'HARE', number: 16, clue: '"Fabled" beast'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CUTERTRUCERECUT', number: 17, clue: 'Director\'s edit of a war film with a more adorable treaty-signing scene?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'TRIM', number: 18, clue: 'Svelte'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'REEL', number: 19, clue: 'Theatre unit'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OLESTRA', number: 20, clue: 'Fat substitute in some chips'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'AEROBE', number: 21, clue: 'Breather'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'BIGLOVE', number: 22, clue: 'HBO polygamy program'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'LAGASSE', number: 23, clue: '"Bam!" chef'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'OTONO', number: 24, clue: 'Fall, in Spain'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LOGJAM', number: 25, clue: 'Impasse'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'LAPSE', number: 25, clue: 'Gaffe'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OREOS', number: 26, clue: 'Common after-school snack'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'GINOS', number: 27, clue: 'Noted Chicago deep dish chain'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'JEANE', number: 28, clue: 'Astrologer Dixon'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'ATALANTA', number: 29, clue: 'Mythical runner'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'AMARE', number: 30, clue: 'Phoenix Suns star Stoudemire'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'NANOS', number: 31, clue: 'iPods available in 1GB versions'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'TRESS', number: 32, clue: 'Lock of hair'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ALLEY', number: 33, clue: 'Spare room?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARIEL', number: 34, clue: 'Mermaid featured in a 2008 prequel'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'AGOG', number: 35, clue: 'Staring open-mouthed, perhaps'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ALLEN', number: 35, clue: 'Billionaire Paul who founded the Experience Music Project'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'MARL', number: 36, clue: 'Marley ___ ("Mama Said Knock You Out" producer)'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PENALPLANEPANEL', number: 37, clue: 'Committee on convict transportation?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'PACKITIN', number: 38, clue: 'Warm up the bus'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'PARTYMAN', number: 39, clue: 'Loyal politician'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SOON', number: 40, clue: 'Within minutes'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ALSO', number: 41, clue: 'Plus'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'AROSE', number: 42, clue: 'Left the couch'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ESSENCES', number: 43, clue: 'Scents'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'NICE', number: 44, clue: 'Complimentary but vague description'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'DRESSY', number: 45, clue: 'Like upscale parties'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'DIAS', number: 45, clue: 'Twenty-four hora periods'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'IKNEWIT', number: 46, clue: 'Words from one whose fears are confirmed'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'WRECK', number: 47, clue: 'Hunk o\' junk'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MEDICI', number: 48, clue: 'Big name in Renaissance patronage'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'MSGS', number: 48, clue: 'Txts, e.g.'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'EMIT', number: 49, clue: 'Give off'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'DIVE', number: 50, clue: 'Cannonball, e.g.'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'ITEM', number: 51, clue: 'Agenda thing'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'RAYGUNS', number: 52, clue: 'Sci-fi weapons'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'GIBE', number: 53, clue: 'Dig'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'UTES', number: 54, clue: 'Sporty trucks, for short'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NEAT', number: 55, clue: '"What a cool gadget!"'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SSTS', number: 56, clue: 'Retired jets'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SMITETIMESMITES', number: 57, clue: 'Exterminate the bugs in Arthur Sulzberger, Jr.\'s office?'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'IRE', number: 58, clue: 'Nation with the second highest per capita income in the EU, behind Lux.'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'MOC', number: 59, clue: 'Slip-on shoe, for short'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GIVE', number: 60, clue: 'Be charitable'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'IROC', number: 61, clue: 'Sporty Camaro'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ABEAT', number: 62, clue: 'Miss ___ (be off)'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STEM', number: 63, clue: 'Hold back, as the tide'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'NECK', number: 64, clue: 'It comes to a head'))
clues_Triple_Scramble_CR_9_11_08.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'NESTS', number: 65, clue: 'Decorates a home, so to speak'))
Puzzle.create(title: 'Triple Scramble', grid: 'AMAID.DARC.CBGB|RANDI.OPEL.HARE|CUTERTRUCERECUT|OLESTRA..AEROBE|....BIGLOVE....|LOGJAM.ATALANTA|ARIEL.AGOG.MARL|PENALPLANEPANEL|SOON.ALSO.AROSE|ESSENCES.DRESSY|....IKNEWIT....|MEDICI..RAYGUNS|SMITETIMESMITES|GIVE.IROC.ABEAT|STEM.NECK.NESTS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2008/9/11', entries: clues_Triple_Scramble_CR_9_11_08)
