clues_Puzzle_50_Do_the_Wide_Thing = Array.new
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ERESTU', number: 1, clue: 'Spain\'s entry in the 1973 Eurovision Song Contest (it came in second)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'EDU', number: 1, clue: 'www.uky.___'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'RIB', number: 2, clue: 'Part of a barbecue rack'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ENO', number: 3, clue: '"The Joshua Tree" producer Brian'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SEAFERN', number: 4, clue: 'Branching underwater growth'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TITLEIST', number: 5, clue: 'Name on Bubba Watson\'s balls'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'UNSENT', number: 6, clue: '"There are ___ messages in you outbox" (message that\'s the bane of an Outlook user)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'SOLO', number: 7, clue: 'Aviator\'s accomplishment'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SABRE', number: 7, clue: 'Company that bought Dunder Mifflin on "The Office"'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ODE', number: 8, clue: 'Keats piece'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LEE', number: 9, clue: 'Ving who played Mr. Boddy in "Clue"'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ONEARM', number: 10, clue: 'Identifying feature of drummer Rick Allen'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'FIN', number: 11, clue: 'Dorsal, e.g.'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'FATES', number: 11, clue: 'Mythical trio known for their threadwork'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'IRENE', number: 12, clue: 'Hurricane of August 2011'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NERD', number: 13, clue: 'AV Club member, maybe (do schools even have AV Clubs anymore?)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'DINEIN', number: 14, clue: 'Carryout alternative'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'ADEN', number: 15, clue: 'Yemen seaport'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ARE', number: 16, clue: 'Equal'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UBOATS', number: 17, clue: 'WWII fleet'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 3, col: 8, dir: 'Across', answer: 'BEEEATER', number: 18, clue: 'Bird named for its diet'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'AMISS', number: 19, clue: 'Just off'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'FLEUR', number: 20, clue: 'Wife of Bill Weasley'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 4, col: 7, dir: 'Down', answer: 'UTOPIANS', number: 21, clue: 'They live in a perfect world?'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'AMEND', number: 22, clue: 'Make a change'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'FREEENTERPRISE', number: 23, clue: 'Capitalist principle'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'FBOMB', number: 23, clue: 'Kids get in trouble for dropping it'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'RUMMY', number: 24, clue: 'Game with melds'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'ERECT', number: 25, clue: 'Standing up'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'RIPOSTES', number: 26, clue: 'Fencer\'s retaliations'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'PAIL', number: 27, clue: '"Jack and Jill" prop (I do NOT refer to the Adam Sandler movie)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BURRITO', number: 28, clue: 'Chipotle order'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'IAMS', number: 29, clue: 'Inventor of the Eukanuba formula of pet food'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OMENS', number: 30, clue: 'Signs of what\'s to come'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'PAPI', number: 31, clue: '"Big ___" (David Ortiz moniker)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'APT', number: 32, clue: 'Fitting'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SUMS', number: 33, clue: 'Adds up'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'URBAN', number: 34, clue: '___ Dictionary'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'MAORI', number: 35, clue: 'New Zealand culture'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SPOSE', number: 36, clue: 'Imagine, briefly'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MMC', number: 37, clue: 'Last year of this century'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'TRIPOLI', number: 38, clue: 'Libyan capital... and when said aloud, a hint to 18-, 23-, 51- and 56-Across'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ROPE', number: 39, clue: '1948 Jimmy Stewart thriller'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'INEEDYOU', number: 40, clue: 'Admission in "Two Out of Three Ain\'t Bad" (it\'s one of the two)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'RAP', number: 41, clue: '___ sheet'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BYTE', number: 42, clue: 'Eight bits'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'EENIE', number: 43, clue: 'First word in "random" selection'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'OATS', number: 44, clue: 'Honey Bunches of ___'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'NABOO', number: 45, clue: 'Planet whose capital is Theed'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ACROBAT', number: 46, clue: 'Nik Wallenda, e.g.'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ESPN', number: 47, clue: '"Around the Horn" channel'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SNELLS', number: 48, clue: '___ Law (optics formula)'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'THECARS', number: 49, clue: '"Just What I Needed" band'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'HEATHS', number: 50, clue: 'Moors'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'TENNESSEEERNIE', number: 51, clue: 'Ford who made guest appearances on "I Love Lucy"'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'TIEME', number: 51, clue: '"___ Kangaroo Down, Sport"'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'EXECS', number: 52, clue: 'Corporate bigwigs'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'SAENS', number: 53, clue: '"Samson and Delilah" composer Camille Saint-___'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'DIXIE', number: 54, clue: 'The South'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'DDAY', number: 54, clue: 'When the Normandy landings occurred'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ASADO', number: 55, clue: 'Brazilian barbecue technique'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DEEELITE', number: 56, clue: '"Groove Is in the Heart" band'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'ION', number: 57, clue: 'Charged particle'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'TOE', number: 58, clue: 'It can get stubbed'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 10, dir: 'Across', answer: 'TYBALT', number: 59, clue: 'Juliet\'s cousin'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'AGT', number: 60, clue: 'Reality show where three of the four judges are foreign, initially'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'LIE', number: 61, clue: 'Golfer\'s concern'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'TER', number: 62, clue: 'Dutch painter Gerard ___ Borch'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AMC', number: 63, clue: '"Breaking Bad" network'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'LOON', number: 64, clue: 'Paragon of craziness'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'HOAGIE', number: 65, clue: 'Hero'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'YES', number: 66, clue: '"Owner of a Lonely Heart" band'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SNES', number: 67, clue: 'Genesis alternative: Abbr.'))
clues_Puzzle_50_Do_the_Wide_Thing.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'SUTTER', number: 68, clue: 'Pioneer John known for his sawmill'))
Puzzle.create(title: 'Puzzle #50 - Do the Wide Thing', grid: 'ERESTU.SOLO.FIN|DINEIN.ADEN.ARE|UBOATS.BEEEATER|...FLEUR..AMEND|FREEENTERPRISE.|BURRITO.IAMS...|OMENS.PAPI.SUMS|MMC.TRIPOLI.RAP|BYTE.OATS.NABOO|...ESPN.THECARS|.TENNESSEEERNIE|DIXIE..ASADO...|DEEELITE.TYBALT|AMC.LOON.HOAGIE|YES.SNES.SUTTER', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-6-28', entries: clues_Puzzle_50_Do_the_Wide_Thing, puzzle_type: 'themed')
