clues_Puzzle_12_Themeless_4 = Array.new
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PLAYMATES', number: 1, clue: 'Bunnies shot for pleasure'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PRUNES', number: 1, clue: 'Sunsweet Ones'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LINEAL', number: 2, clue: 'Genealogical'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ACCUSE', number: 3, clue: 'Do a "Clue" action'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'YEH', number: 4, clue: '"Mm-hmm"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'MAAM', number: 5, clue: 'Abbreviated address'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ARIA', number: 6, clue: 'Mozart piece, perhaps'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TONIC', number: 7, clue: 'First degree, in music'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ENEMY', number: 8, clue: 'Koopa, to Mario'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SID', number: 9, clue: '"Ice Age" sloth'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'SMIRK', number: 10, clue: 'Knowing look'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SPECIE', number: 10, clue: 'Cold, hard cash'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MULE', number: 11, clue: 'Closed toe option'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'IPODMINI', number: 12, clue: 'Obsolete music player'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RADARGUN', number: 13, clue: 'Speed reader?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KEYRINGS', number: 14, clue: 'Members of a chain gang?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'RICEARONI', number: 15, clue: 'Quintessential game show parting gift'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'PUPAE', number: 16, clue: 'They\'re nearly adults'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UNCHAINEDMELODY', number: 17, clue: '1955 Best Song nominee featured in a 1990 Best Picture nominee'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'MODE', number: 18, clue: 'Measure of statistical popularity'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'NEU', number: 19, clue: 'Hip, in Hamburg'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'MAIM', number: 20, clue: 'Irreparably damage'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'OCEDAR', number: 21, clue: 'Big name in home cleaning'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'EAST', number: 22, clue: 'Right on the map?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TIARA', number: 23, clue: 'Diadem'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'CYNDI', number: 24, clue: '"She\'s So Unusual" singer Lauper'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'NEALE', number: 25, clue: 'Former tennis number one Fraser'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'MRI', number: 26, clue: 'Hosp. pic'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SLEIGH', number: 27, clue: 'Runners hold it up'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'GMC', number: 28, clue: 'Yukon XL maker'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'HAH', number: 29, clue: '"Yeah, I\'ll bet!"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'EEE', number: 30, clue: 'Rather wide'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'IGN', number: 31, clue: 'Starter: Abbr.'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'AMANDA', number: 32, clue: 'Tapping of "Stargate SG-1"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'NBCTV', number: 33, clue: 'Comcast property'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'DUH', number: 34, clue: '"You don\'t have to tell me"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SNUG', number: 35, clue: 'With no room to spare'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'STASH', number: 35, clue: 'Secret stock'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CHURCHBULLETINS', number: 36, clue: 'Mass media?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'CLANSMAN', number: 36, clue: 'William Wallace, for one'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'HEREWEGO', number: 37, clue: '"Let the games begin!"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'UNCLELEO', number: 38, clue: 'His catchphrase was "Jerry, hello!"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'LEN', number: 39, clue: 'Lesser who played 38-Down'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ETE', number: 40, clue: 'French quarter?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LENA', number: 41, clue: 'Headey of "Game of Thrones"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'CHEETA', number: 42, clue: 'Monkey on \'60s screens'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ARC', number: 43, clue: 'Volleyball\'s path'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'WIT', number: 44, clue: 'Ravenclaw\'s asset'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'WRESTS', number: 44, clue: 'Takes with effort'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'IONS', number: 45, clue: 'Chemists\' positives'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'NESSIE', number: 46, clue: 'Scottish cryptid'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'SARTRE', number: 47, clue: '"Hell is other people" author'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'INCHES', number: 48, clue: 'Parts of a yard'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'EASYAS', number: 49, clue: 'Some 100-level courses'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NEL', number: 50, clue: '1958 Eurovision entry "___ blu dipinto di blu"'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'ROVER', number: 51, clue: 'Source of movement on Mars'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ELMER', number: 52, clue: '"Rabbit of Seville" character'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'RECTI', number: 53, clue: 'Six packs, anatomically'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'HANA', number: 54, clue: 'Winding Hawaiian highway, or its destination'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SWEDEN', number: 55, clue: 'Its flag has a yellow cross'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'DINK', number: 56, clue: 'Minor hit?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'LEAK', number: 57, clue: 'Prove too loose'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ACRE', number: 58, clue: 'Farmer\'s measurement'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'KAOS', number: 59, clue: 'They tried to get Smart'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'RCS', number: 60, clue: 'Pepsi alternatives'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MELISSAMCCARTHY', number: 61, clue: '"Mike & Molly" Emmy winner'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'AMP', number: 62, clue: 'A in physics?'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'RAT', number: 63, clue: 'Subway denizen'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AGENT', number: 64, clue: 'Smart, e.g.'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'METROAREA', number: 65, clue: 'It stretches to the burbs'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NOOKS', number: 66, clue: 'Kindle competitors'))
clues_Puzzle_12_Themeless_4.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'PRIESTESS', number: 67, clue: 'Vestal Virgin, e.g.'))
Puzzle.create(title: 'Puzzle #12 - Themeless #4', grid: 'PLAYMATES.SMIRK|RICEARONI.PUPAE|UNCHAINEDMELODY|NEU.MAIM.OCEDAR|EAST..CYNDI.MRI|SLEIGH..EEE.IGN|...AMANDA..SNUG|CHURCHBULLETINS|LENA..CHEETA...|ARC.WIT..NESSIE|NEL.ROVER..HANA|SWEDEN.LEAK.RCS|MELISSAMCCARTHY|AGENT.METROAREA|NOOKS.PRIESTESS', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2012-10-5', entries: clues_Puzzle_12_Themeless_4, puzzle_type: 'freestyle')
