clues_Puzzle_29_Country_Cookin = Array.new
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CANS', number: 1, clue: 'Coke containers'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CASA', number: 1, clue: 'Good place to live in Mexico'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AMPS', number: 2, clue: 'Speakers in front of crowds?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NOAH', number: 3, clue: 'Genesis man'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SKI', number: 4, clue: 'Go cross-country, one way'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ROAD', number: 5, clue: 'Dirt thoroughfare'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RECAP', number: 5, clue: 'SportsCenter spiel'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OLIVES', number: 6, clue: 'Some pizza toppers'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALTA', number: 7, clue: '___ Vista'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DAYGAMES', number: 8, clue: 'They happen with the lights off'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'AGNES', number: 9, clue: 'Anne Bront&#235;\'s Gray'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'AFC', number: 9, clue: 'Org. for Texans and Patriots'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GRAMPA', number: 10, clue: 'Pop-pop'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'NORWAYJOSE', number: 11, clue: 'Feliciano on vacation in Oslo?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ESTAS', number: 12, clue: '"Como ___?"'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SHAHS', number: 13, clue: 'Old rulers in Tehran'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMOK', number: 14, clue: 'Frenetically'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ELLA', number: 15, clue: '1998 Newbery winner "___ Enchanted"'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'FROSH', number: 16, clue: 'First year on campus'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SPAINCITY', number: 17, clue: 'Barcelona or Bilbao?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'NSYNC', number: 18, clue: 'Justin, Chris, Joey, Lance and JC'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'CARTA', number: 19, clue: '1215 document Magna ___'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ASH', number: 20, clue: 'Volcanic hazard'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'SAVAGE', number: 21, clue: 'Barbarian'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ELECTS', number: 22, clue: 'Puts in democratically'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'MWAH', number: 23, clue: 'Sound of a kiss'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'HYPE', number: 24, clue: 'Exorbitant publicity'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'HOOK', number: 24, clue: 'Curve left midflight'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ALLPASS', number: 25, clue: 'Bidding phase ender'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'LSD', number: 26, clue: '"The Electric Kool-Aid Acid Test" subject'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ACTON', number: 27, clue: 'Follow, as advice'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ABLE', number: 27, clue: 'Talented'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CRAG', number: 28, clue: 'Rocky form'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'TONGAPARTY', number: 29, clue: 'Celebration in the South Pacific?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'SOMESAY', number: 30, clue: 'Rumormonger\'s opening'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ORATE', number: 31, clue: 'Talk at the lectern'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BROOCH', number: 32, clue: 'Lapel ornament'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'HALLOS', number: 33, clue: 'Greetings across the pond'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'RECD', number: 34, clue: 'Mail stamp: Abbr.'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'JAW', number: 35, clue: 'Chin\'s spot'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ATOP', number: 36, clue: 'On the summit'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'WOKE', number: 37, clue: 'Returned from slumber'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LANK', number: 38, clue: 'Lean and tall'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'AVAST', number: 39, clue: 'What a pirate says'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'VOICEBOX', number: 40, clue: 'Sound producer?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'TOTO', number: 41, clue: '"Africa" band'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'TYRE', number: 41, clue: '"Pericles, Prince of ___"'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EGG', number: 42, clue: '1947 film "The ___ and I"'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'BLOT', number: 43, clue: 'Clean up a spill'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'BED', number: 43, clue: 'Dorm room piece'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'SAYSOK', number: 44, clue: 'Gives permission'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'ACCRA', number: 45, clue: 'Ghanaian capital'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'ATELIER', number: 46, clue: 'Place to paint'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'TANDEM', number: 47, clue: 'Bike type'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'REIRON', number: 48, clue: 'Press further?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'CREPE', number: 49, clue: 'Party paper'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'PAPADOC', number: 50, clue: 'Big nickname in Haitian politics'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'PSHAW', number: 50, clue: '"Get out of town!"'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'AWASH', number: 51, clue: 'Teeming'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ECCE', number: 52, clue: 'Look in Rome'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'COMMA', number: 53, clue: '___ splice (grammatical error)'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SWAN', number: 54, clue: 'Mute animal?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'SENIOR', number: 55, clue: '___ management'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'NUDE', number: 56, clue: 'Art subject'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'WIN', number: 57, clue: 'Take the prize'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'WILE', number: 57, clue: 'Craftiness'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IDEA', number: 58, clue: 'Think tank thing'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'NEXT', number: 59, clue: 'Call at the counter'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HARDG', number: 60, clue: 'Sound heard once in the Ganges'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'GRE', number: 61, clue: 'Test to go beyond univ.'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'BURMARIDE', number: 62, clue: 'Rangoon roadster?'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'RAM', number: 63, clue: 'Butt with a head'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ASTER', number: 64, clue: 'Star-shaped flower'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ODOM', number: 65, clue: 'LA Clipper Lamar'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ALEX', number: 66, clue: 'Patterson\'s detective Cross'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'WHYME', number: 67, clue: 'Despairing question'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'XENA', number: 68, clue: 'Powerful woman of \'90s TV'))
clues_Puzzle_29_Country_Cookin.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'MEAT', number: 69, clue: 'Pork, e.g.'))
Puzzle.create(title: '#29 - Country Cookin\'', grid: 'CANS.ROAD.AGNES|AMOK.ELLA.FROSH|SPAINCITY.CARTA|ASH.SAVAGE.MWAH|...HYPE.ALLPASS|ACTON.SOMESAY..|BROOCH.RECD.JAW|LANK.AVAST.TOTO|EGG.BLOT.SAYSOK|..ATELIER.CREPE|PAPADOC.ECCE...|SWAN.SENIOR.WIN|HARDG.BURMARIDE|ASTER.ODOM.ALEX|WHYME.XENA.MEAT', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-2-1', entries: clues_Puzzle_29_Country_Cookin, puzzle_type: 'themed')
