clues_Puzzle_26_Team_Spirit = Array.new
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'HADJ', number: 1, clue: 'Pilgrimage to Mecca'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'HEMS', number: 1, clue: 'Skirt lines'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AGEE', number: 2, clue: 'Knoxville-born Pulitzer winner James'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'DATA', number: 3, clue: 'Number cruncher\'s numbers'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'JDATE', number: 4, clue: 'Website where you could find a nice lawyer husband, maybe? (Oy, your mother just wants you to be happy!)'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'GLOPS', number: 5, clue: 'Messy dollops'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GAUCHE', number: 5, clue: 'Not droite'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LIZ', number: 6, clue: 'Taylor who played Velvet Brown'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ORZO', number: 7, clue: 'Pasta from the Italian for "barley"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'PULP', number: 8, clue: '"Disco 2000" band'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SPEEDOS', number: 9, clue: 'Some banana hammocks'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ACCT', number: 10, clue: 'IRA component'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ARTPENCIL', number: 10, clue: 'Thing found in a drawing room?'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CORA', number: 11, clue: 'Iron Chef Cat'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CRAG', number: 12, clue: 'Tough climb'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TYPE', number: 13, clue: 'Use a keyboard'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EGAD', number: 14, clue: '"Yikers!"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AIRUP', number: 15, clue: 'Inflate, as tires'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'RORY', number: 16, clue: 'One of TV\'s "Gilmore Girls"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'METAPUZZLE', number: 17, clue: 'MIT Mystery Hunt challenge'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'PACMAN', number: 18, clue: 'Fever of the \'80s'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'TRAP', number: 19, clue: 'Sand ___ (golf course feature)'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SEATAC', number: 20, clue: 'Hub for Alaska Airlines (that\'s not in Alaska)'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'OPEDPAGE', number: 21, clue: 'It\'s made with slanted columns'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'DIR', number: 22, clue: 'Compass pt.'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ECHO', number: 23, clue: 'It\'s between Delta and Foxtrot'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'OAKIER', number: 24, clue: 'With a woodier taste, maybe'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'DIE', number: 25, clue: 'Trivial Pursuit piece'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TMI', number: 26, clue: '"Didn\'t need to know that"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'TWOPM', number: 26, clue: '1400'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'MADEA', number: 27, clue: 'Title character played by Tyler Perry'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'INSET', number: 28, clue: '32-Down feature'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'MEATTORNADO', number: 29, clue: 'Fictional burrito that\'s as deadly as it sounds'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TROLL', number: 30, clue: 'Online menace'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'TINTIN', number: 31, clue: 'Snowy companion'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'ATLAS', number: 32, clue: 'Google Earth in print form'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'DRESS', number: 33, clue: 'Put clothes on'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'OLDEN', number: 34, clue: '"Here we are as in ___ days..."'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'WANNA', number: 35, clue: '"Care to?"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'NOPEEKING', number: 36, clue: '"Look away!"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'KRIS', number: 37, clue: 'Bruce Jenner\'s wife'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'CTRL', number: 38, clue: 'Lower left key'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ODSON', number: 39, clue: 'Uses way too much of, in brief'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'ION', number: 40, clue: '"Flashpoint" network'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'OILED', number: 41, clue: 'Used WD-40'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'OBERON', number: 41, clue: '"A Midsummer Night\'s Dream" king'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PEEP', number: 42, clue: 'Chick\'s noise'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'PELT', number: 43, clue: 'Attack with a snowball'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'POORTAX', number: 43, clue: '$15, in Monopoly'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'BLASE', number: 44, clue: 'Nonchalant'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MATEFORLIFE', number: 45, clue: 'Act like turtle doves, stereotypically'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'FLA', number: 46, clue: 'Ga.\'s neighbor to the south'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'FLOATY', number: 47, clue: 'Buoyant'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'SSN', number: 48, clue: 'Nine digit ID'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'ELO', number: 49, clue: '"Strange Magic" band'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'NLRB', number: 50, clue: 'Workers\' rights agcy.'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'BLIMP', number: 51, clue: '"The Spirit of Goodyear," e.g.'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'BADKARMA', number: 52, clue: 'Result of cutting someone off or not leaving a tip'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'BOOZ', number: 52, clue: 'Tech consulting firm ___ Allen Hamilton'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AMMO', number: 53, clue: 'Biathlon need'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'DRAM', number: 54, clue: '1/16 of an ounce'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'MARA', number: 55, clue: 'Wilson of "Matilda"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'AMEN', number: 56, clue: '"So be it!"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'OOLONG', number: 57, clue: 'Traditional Chinese tea'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'OMAR', number: 58, clue: 'President al-Bashir of Sudan'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NANO', number: 59, clue: 'Metric prefix with second'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'GLOW', number: 60, clue: 'Emit a soft light'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OMRI', number: 61, clue: '"The Indian in the Cupboard" boy'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'TAMEANIMAL', number: 62, clue: 'Pet, ideally'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'END', number: 63, clue: 'Close'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OMAN', number: 64, clue: 'Southwest Asian nation'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ARENT', number: 65, clue: 'Ain\'t right?'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'MANO', number: 66, clue: 'Spanish word on either side of "-a-"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ZOMG', number: 67, clue: 'Online "Holy mackerel!"'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'XANDY', number: 68, clue: '2005 Coldplay album that algebra students are always looking for?'))
clues_Puzzle_26_Team_Spirit.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'PROW', number: 69, clue: 'Cutter\'s water-cutter'))
Puzzle.create(title: '#26 - Team Spirit', grid: 'HADJ.GLOPS.ACCT|EGAD.AIRUP.RORY|METAPUZZLE.TRAP|SEATAC.OPEDPAGE|...ECHO..DIE...|TMI.MEATTORNADO|WANNA.KRIS.CTRL|ODSON.ION.OILED|PEEP.PELT.BLASE|MATEFORLIFE.SSN|...ELO..NLRB...|BADKARMA.OOLONG|OMRI.TAMEANIMAL|OMAN.ARENT.MANO|ZOMG.XANDY.PROW', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-1-11', entries: clues_Puzzle_26_Team_Spirit, puzzle_type: 'themed')
