clues_Puzzle_17_Family_TV_Show_Finales = Array.new
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'INCA', number: 1, clue: 'South American empire'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'INDEBT', number: 1, clue: 'Owing'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'NOODLE', number: 2, clue: 'Foam pool toy'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'CORDON', number: 3, clue: 'Le ___ Bleu'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AKA', number: 4, clue: 'Pseudonym letters'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'BGIRL', number: 5, clue: 'Lady breaker'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'BANFF', number: 5, clue: 'Alberta ski town'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'GLUTEI', number: 6, clue: 'Cheek muscles?'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'IBM', number: 7, clue: 'Co. that\'s a Caesar cipher of HAL'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'REB', number: 8, clue: 'Confederate soldier'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LEES', number: 9, clue: 'Wine residue'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'BEEP', number: 10, clue: 'Page, in the \'90s'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BASKS', number: 10, clue: 'Enjoys a sunbeam'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'EIGHTIES', number: 11, clue: 'Popular party theme, nowadays'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ELUSIVE', number: 12, clue: 'Slippery'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'PSY', number: 13, clue: '"Gangnam Style" artist'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NOOK', number: 14, clue: 'Barnes &amp; Noble buy'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ALBEE', number: 15, clue: '"Who\'s Afraid of Virginia Woolf?" playwright Edward'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'AILS', number: 16, clue: 'Feels like death'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DORA', number: 17, clue: 'Nick Jr. girl'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'NUMBERSGUY', number: 18, clue: 'One with experience crunching'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'RIAL', number: 19, clue: 'Omani currency'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EDD', number: 20, clue: 'Actor Byrnes'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'AFT', number: 21, clue: 'Back, on a boat'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ADBIZ', number: 21, clue: 'Subject of "Mad Men"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'SIKHS', number: 22, clue: 'Believers in Waheguru'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BLOODFEUD', number: 23, clue: '"Romeo and Juliet" plot device'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'OLDIE', number: 24, clue: '"Mister Sandman," e.g.'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'UNCANNY', number: 25, clue: 'Eerie'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'DOIT', number: 26, clue: '"I dare you!"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ASTIN', number: 27, clue: 'John who was married to Patty Duke'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'NED', number: 28, clue: 'Beatty of "Deliverance"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TENLB', number: 29, clue: 'Bulk flour bag size: Abbr.'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'INOIL', number: 30, clue: 'Way to fry'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'IOTA', number: 31, clue: 'Kappa preceder'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'IVE', number: 32, clue: '"___ got it!"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'DIP', number: 33, clue: 'Party bowlful'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'PETA', number: 34, clue: 'Org. whose website has vegan recipes'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'CIO', number: 35, clue: 'Former trade union'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'FEED', number: 36, clue: 'News ___ (Facebook feature)'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'FROLF', number: 36, clue: 'Disc-based sport'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'SIZEMATTERS', number: 37, clue: 'Tenet held by some women'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'SEXDRIVE', number: 37, clue: 'Thing turned on by a turn on'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'MINX', number: 38, clue: 'Hussy'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'EDIFY', number: 39, clue: 'Teach'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'THEE', number: 40, clue: 'Quaker pronoun'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'TBA', number: 40, clue: 'Scheduling letters'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'HONALEE', number: 41, clue: 'Puff\'s place'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'TIN', number: 42, clue: 'Bronze component'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'ADO', number: 43, clue: 'Brouhaha'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BOX', number: 44, clue: 'Pizza holder'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'MANNA', number: 45, clue: 'Exodus food'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'MEMO', number: 45, clue: '"Dilbert" sheet'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'AZTECS', number: 46, clue: 'Some Quetzalcoatl worshippers'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ILLBE', number: 47, clue: '"Who knew!?"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'LASSIE', number: 48, clue: 'Famous collie'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'BIKINI', number: 49, clue: 'Suit leaving little to the imagination'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ERASES', number: 50, clue: 'Does away with'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ANDRE', number: 51, clue: '"My Dinner with ___"'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'ROPED', number: 52, clue: 'Snagged'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'XYZAFFAIR', number: 53, clue: '"Millions for defense, but not one cent for tribute" event of 1797'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ARSES', number: 54, clue: 'British bums'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'AROMA', number: 55, clue: 'Potpourri\'s output'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'ANNA', number: 56, clue: 'Tolstoy\'s Karenina'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'TRY', number: 57, clue: 'Have a go'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'SKA', number: 58, clue: 'Jamaican genre'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CLIPONTIES', number: 59, clue: 'Lazy dressers\' accessories'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'CNN', number: 59, clue: 'Cooper\'s employer'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'TOM', number: 60, clue: 'Newsman Brokaw'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'III', number: 61, clue: 'The third'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'ISIS', number: 62, clue: 'Goddess with a throne headress'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ILL', number: 62, clue: 'Indisposed'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NEVE', number: 63, clue: '"Scream" actress Campbell'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'NOICE', number: 64, clue: 'Request that gets you more soda'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'LINE', number: 65, clue: 'Script bit'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NEED', number: 66, clue: 'Requirement'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'AMISS', number: 67, clue: 'Wrong'))
clues_Puzzle_17_Family_TV_Show_Finales.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'LEIS', number: 68, clue: 'Hilo souvenirs'))
Puzzle.create(title: 'Puzzle #17 - Family TV Show Finales', grid: 'INCA.BGIRL.BEEP|NOOK.ALBEE.AILS|DORA.NUMBERSGUY|EDD.AFT..SIKHS.|BLOODFEUD.ASTIN|TENLB.INOIL.IVE|...DIP.CIO.FEED|..SIZEMATTERS..|THEE.TIN.ADO...|BOX.MANNA.ILLBE|ANDRE.XYZAFFAIR|.AROMA..TRY.SKA|CLIPONTIES.ISIS|NEVE.NOICE.LINE|NEED.AMISS.LEIS', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2012-11-9', entries: clues_Puzzle_17_Family_TV_Show_Finales, puzzle_type: 'themed')
