clues_Puzzle_24_Themeless_7 = Array.new
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AID', number: 1, clue: 'Lend a hand'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ADLIB', number: 1, clue: 'Vamp'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IRINA', number: 2, clue: 'One of Chekhov\'s "Three Sisters"'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'DOVER', number: 3, clue: 'Capital named for a town in Kent'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'TUBA', number: 4, clue: 'Brass member'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TICTACTOE', number: 4, clue: 'Basis of Toss Across'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'UNH', number: 5, clue: 'State sch. in New England'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BOA', number: 6, clue: 'Feathered accessory'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ANTE', number: 7, clue: 'Get the game going'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'ANNIKA', number: 8, clue: 'LPGA player Sorenstam'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ABETS', number: 8, clue: 'Helps a crook'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NONOS', number: 9, clue: 'Toddler\'s taboos'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'NOR', number: 10, clue: 'Neither\'s partner'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'INAUGURAL', number: 11, clue: 'First'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'KEPTONICE', number: 12, clue: 'Put on the back burner (surprisingly enough)'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ASTERISKS', number: 13, clue: 'Minor stars'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'DROPINON', number: 14, clue: 'Hold a welcome mat to its word'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'PERT', number: 15, clue: 'Sassy'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'BOONES', number: 16, clue: 'Singers Pat and Debby'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LIVECHAT', number: 17, clue: 'Online accompaniment of some TV shows'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'ENRAPT', number: 18, clue: 'Taken in'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'INERT', number: 19, clue: 'Not reactive'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'ESTO', number: 20, clue: '"___ Perpetua" (Idaho\'s motto)'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'SAN', number: 21, clue: 'Title for Antonio'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'UTE', number: 22, clue: 'Beehive State native'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BARTABS', number: 23, clue: 'They\'re run up'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'BLOND', number: 24, clue: 'Dishwater ___'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'SEPT', number: 25, clue: 'Trois et quatre'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ASS', number: 26, clue: 'Dunderhead'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'GOR', number: 27, clue: 'Sci-fi setting created by John Norman'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'CLEON', number: 28, clue: 'Character in "Pericles, Prince of Tyre"'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'OSKAR', number: 29, clue: 'Eponymous Schindler'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'MUNI', number: 30, clue: 'City bond, briefly'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'MOJO', number: 30, clue: '___ Jojo (foe of the Powerpuff Girls)'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TREETOPS', number: 31, clue: 'Canopy make up'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'TYBURRELL', number: 31, clue: '"Modern Family" star'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ROADTORIO', number: 32, clue: '1947 film featuring The Andrews Sisters'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'EURASIANS', number: 33, clue: 'There are about 4.62 billion of them alive today'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'EDGY', number: 34, clue: 'Avant-garde'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'MAORIS', number: 35, clue: 'Some New Zealanders'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'MORAL', number: 35, clue: 'Story\'s point'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'AWHOLELOT', number: 36, clue: 'Oodles'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'YOUDONTKNOWJACK', number: 37, clue: 'Winner of the 2012 Video Game Award for Best Social Game'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'NILE', number: 38, clue: 'African flower'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BARGED', number: 39, clue: 'Stormed (in)'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'AIRHOLES', number: 40, clue: 'They\'ll give you some breathing room'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'UDAY', number: 41, clue: 'Son of Saddam'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'DRLAO', number: 42, clue: '1964 role for Tony Randall'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'DEI', number: 42, clue: '"Agnus ___"'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RTS', number: 43, clue: 'Some linemen: Abbr.'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'LEE', number: 44, clue: 'Washington and ___ University'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'LEONI', number: 44, clue: 'T&#233;a of "Spanglish"'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'ERNST', number: 45, clue: 'Surrealist Max'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ELLYMAY', number: 46, clue: 'One of TV\'s Clampetts'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'YVES', number: 47, clue: 'YSL component'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'MAXIM', number: 48, clue: 'Magazine for 64-Across'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ADATE', number: 49, clue: '"It\'s ___!" ("See you then!")'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'YEMEN', number: 50, clue: 'Country unified in 1990'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ROI', number: 51, clue: 'Monet\'s monarch'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'ERIC', number: 52, clue: 'Children\'s author Carle or Berlin'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'COOS', number: 53, clue: 'Acts like a dove'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'EVADE', number: 54, clue: 'Duck out of'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ERAGON', number: 55, clue: 'First book in Paolini\'s Inheritance Cycle'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'GET', number: 56, clue: 'Purchase'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'ORALEXAM', number: 57, clue: 'Third degree on the way to one\'s third degree'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'RPM', number: 58, clue: 'Dashboard abbr.'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'APU', number: 59, clue: '"The Simpsons" clerk'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LINENS', number: 60, clue: 'Sheets and pillowcases'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'OPPOSITE', number: 61, clue: 'Left to right?'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'LOSTIT', number: 62, clue: 'Went bananas'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'SMUT', number: 63, clue: 'Dirty stuff'))
clues_Puzzle_24_Themeless_7.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'MEN', number: 64, clue: 'See 48-Down'))
Puzzle.create(title: 'Puzzle #24 - Themeless #7', grid: 'AID.TUBA.ANNIKA|DROPINON.BOONES|LIVECHAT.ENRAPT|INERT..ESTO.UTE|BARTABS.ASS.GOR|....CLEON..MUNI|TREETOPS.MAORIS|YOUDONTKNOWJACK|BARGED.AIRHOLES|UDAY..DRLAO....|RTS.LEE.ELLYMAY|ROI.ERIC..EVADE|ERAGON.ORALEXAM|LINENS.OPPOSITE|LOSTIT.SMUT.MEN', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2012-12-28', entries: clues_Puzzle_24_Themeless_7, puzzle_type: 'freestyle')
