clues_Puzzle_55_Capital_Tour = Array.new
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ATLAW', number: 1, clue: 'Attorney-___'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ABBY', number: 1, clue: 'Pauley\'s "NCIS" character'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TREO', number: 2, clue: 'Palm line'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LURK', number: 3, clue: 'Read a message board without posting'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ATNOCOST', number: 4, clue: 'For free'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'WEBZINE', number: 5, clue: 'Pitchfork, e.g.'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'SNERD', number: 6, clue: 'One of Bergen\'s dummies'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'STINE', number: 6, clue: 'His Twitter profile reads: "My job: to terrify kids"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NADA', number: 7, clue: 'Bupkis'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EKG', number: 8, clue: 'Hosp. test'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'REELEDIN', number: 9, clue: 'Landed, like a fish'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DISEASE', number: 10, clue: 'CDC member?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'POG', number: 11, clue: 'Disc in a \'90s game'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PRAGUEROCK', number: 11, clue: 'Music genre in the capital of the Czech Republic?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OORT', number: 12, clue: '___ cloud'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'GOTH', number: 13, clue: '1-Down, e.g., considering her style of dress'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BRUTE', number: 14, clue: 'Savage'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'TAKEI', number: 15, clue: '"Oh Myyy! (There Goes The Internet)" author George'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ROO', number: 16, clue: 'Kanga\'s joey'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BERNBRIDGES', number: 17, clue: 'Ways across the River Aare in the capital of Switzerland?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'RUTS', number: 18, clue: 'Dirt road features'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ART', number: 19, clue: 'Carney of "The Honeymooners"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'YOKOZUNA', number: 20, clue: 'Highest sumo rank'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'LENGTH', number: 21, clue: 'Fish story exaggeration'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'NNW', number: 22, clue: 'What a Hitchcock title looks like when viewed on a compass'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'CITE', number: 23, clue: 'List in a footnote'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'KEANU', number: 24, clue: 'Reeves of "The Day the Earth Stood Still"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'KITES', number: 24, clue: 'Toys on strings'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'MASONS', number: 25, clue: 'Stone workers'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'MOCHA', number: 25, clue: 'Yemeni port lending its name to a coffee drink'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ABOOT', number: 26, clue: 'Facetious Canadian-English word'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'SEOULTRAIN', number: 27, clue: 'Public transit option in the capital of South Korea?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'KIDSWEEK', number: 28, clue: 'Annual "Jeopardy!" event'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'KARTS', number: 28, clue: 'Go-___'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ENOKI', number: 29, clue: 'Long white mushroom'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'KANYE', number: 30, clue: 'West once called a "jackass" by President Obama'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OBESE', number: 31, clue: 'With a lot to lose?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'KATIE', number: 32, clue: 'Talk show since 2012'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'KUNIS', number: 32, clue: 'Mila of "Family Guy"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'RNA', number: 33, clue: 'Single-stranded stuff'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'COOT', number: 34, clue: 'Old fellow'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'BUREN', number: 35, clue: 'Martin Van ___'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'BETITALL', number: 35, clue: 'Go for broke, as on a Daily Double'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'COON', number: 36, clue: 'Source of the skin for a cap that PETA would not care for'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'CORDELIA', number: 36, clue: 'King Lear\'s youngest daughter (and remember: they die)'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'HOU', number: 37, clue: 'The Astros, on a scoreboard'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'GENTS', number: 38, clue: 'Ladies\' counterparts'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'GNOSTIC', number: 38, clue: 'Believer from the Greek for "knowledge"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ROCKY', number: 39, clue: 'Bullwinkle\'s buddy'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'RAINBOW', number: 39, clue: 'Mist creation'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ATLANTIS', number: 40, clue: 'Land down under?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ARE', number: 41, clue: '"We ___ Never Ever Getting Back Together"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'MARKIE', number: 42, clue: 'Post in "Night Court"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'MLII', number: 42, clue: 'Mid-eleventh century year'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'TROIS', number: 43, clue: 'Deux follower'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SLID', number: 44, clue: 'Used a Sorry! shortcut'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SWEDE', number: 44, clue: 'Bj&#246;rn Ulvaeus, e.g.'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'FOREST', number: 45, clue: 'Forbidden ___ (restricted area at Hogwarts)'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'FAWN', number: 45, clue: 'Bambi, e.g.'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'OHIO', number: 46, clue: 'Only state with a non-rectangular flag'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'SWINEFLU', number: 47, clue: '2009 outbreak'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SPAN', number: 47, clue: 'Set of all finite linear combinations of a set of vectors'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'FONG', number: 48, clue: 'Only Republican to hold a Senate seat from Hawaii'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'LOGO', number: 49, clue: 'Mitsubishi\'s has three diamonds'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'UDON', number: 50, clue: 'Thick noodle of Japanese cuisine'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AHA', number: 51, clue: '"I know exactly what\'s going on here!"'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'TAIPEIBLOOD', number: 52, clue: 'Bodily fluid in the capital of Taiwan?'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'III', number: 53, clue: '43-Across, in Ancient Rome'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WII', number: 54, clue: 'Elebits system'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ILIAD', number: 55, clue: 'Homeric epic'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'OINGO', number: 56, clue: '___ Boingo'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NON', number: 57, clue: 'Oui\'s opposite'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'CLINE', number: 58, clue: '"Walkin\' After Midnight" singer Patsy'))
clues_Puzzle_55_Capital_Tour.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'WAGON', number: 59, clue: 'Pioneer\'s vehicle'))
Puzzle.create(title: 'Puzzle #55 - Capital Tour', grid: 'ATLAW.SNERD.POG|BRUTE.TAKEI.ROO|BERNBRIDGES.ART|YOKOZUNA.LENGTH|...CITE.KEANU..|MASONS.KIDSWEEK|OBESE.KATIE.RNA|COOT.BUREN.COON|HOU.GENTS.ROCKY|ATLANTIS.MARKIE|..TROIS.SLID...|FOREST.SWINEFLU|AHA.TAIPEIBLOOD|WII.ILIAD.OINGO|NON.CLINE.WAGON', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-8-2', entries: clues_Puzzle_55_Capital_Tour, puzzle_type: 'themed')
