clues_Puzzle_25_2012_in_Review = Array.new
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ACTED', number: 1, clue: 'Made a scene?'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ATF', number: 1, clue: 'Gp. raiding Mount Carmel Center outside of Waco'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CREATOR', number: 2, clue: 'God, in Genesis'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TELLSON', number: 3, clue: 'Rats out'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EVIL', number: 4, clue: 'No good at all'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DIXIT', number: 5, clue: 'Card game whose name is Latin for "he said"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CACHE', number: 6, clue: 'Stash (that rhymes with "stash")'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CAB', number: 6, clue: '"Party in the USA" vehicle'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AMAJ', number: 7, clue: 'Key of "Dancing Queen," briefly'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'COULDA', number: 8, clue: 'Word of regret'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'HUMORME', number: 9, clue: '"Play along, will ya?"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ERG', number: 10, clue: 'Unit from the Greek for "work"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'DOWSE', number: 11, clue: 'Divine'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'DIRK', number: 11, clue: 'Cussler adventurer Pitt'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OCTOPI', number: 12, clue: 'Jet set?'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'WINDSOCKS', number: 13, clue: 'Airport speed indicators'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'SEE', number: 14, clue: 'Behold'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'ERR', number: 15, clue: 'Mess up'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TREVI', number: 16, clue: 'Famous fountain'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'AMOUR', number: 17, clue: '"Mon c&#339;ur se recommande &#224; vous" subject'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ICIER', number: 18, clue: 'Even less friendly'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'FELIX', number: 19, clue: 'With 20-Across, he set a new skydiving record in 2012 (39,045 meters!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'BAUMGARTNER', number: 20, clue: 'See 19-Across'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'ATOLL', number: 21, clue: 'Lagoon surrounder'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'ALLIN', number: 22, clue: 'Biggest bluff'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'NAMATH', number: 23, clue: 'Bear Bryant called him "the greatest athlete [he] ever coached"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'JLO', number: 24, clue: 'Former "American Idol" judge, familiarly'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'TKOD', number: 25, clue: 'One way to be beaten in boxing'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'STS', number: 26, clue: 'Ave. intersectors'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'SPA', number: 26, clue: 'Backyard amenity'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'TAZ', number: 27, clue: 'Animated spinner'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'ZELDA', number: 28, clue: 'Legendary Nintendo character'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'DRNO', number: 29, clue: 'Bond villain whose first name is Julius'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'NIL', number: 30, clue: 'Zero score'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 14, dir: 'Across', answer: 'PSAT', number: 31, clue: 'Exam with a perfect score of 240'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 16, dir: 'Down', answer: 'ANYA', number: 32, clue: 'Emma Caulfield\'s "Buffy" character'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 5, col: 17, dir: 'Down', answer: 'TSAR', number: 33, clue: 'Old Bulgarian leader'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'POOL', number: 34, clue: 'Backyard amenity'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'LEVIS', number: 35, clue: '501 brand'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'MEGAMILLIONS', number: 36, clue: 'It set a new lottery jackpot record in 2012 ($656,000,000 annuitized!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'GAYE', number: 37, clue: '"It Takes Two" duettist Marvin'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'LADLE', number: 38, clue: 'Big dipper?'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARNE', number: 39, clue: '18th c. British composer Thomas'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ALA', number: 40, clue: 'Chicken ___ King'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'ELLA', number: 41, clue: '1969 album that opens with a jazzy cover of "Get Ready"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 7, col: 15, dir: 'Across', answer: 'CYA', number: 42, clue: 'Due diligence initialism'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'VATDYE', number: 43, clue: 'Indigo, e.g.'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'ACTIN', number: 44, clue: 'Muscle contraction protein that works with myosin'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'ELF', number: 45, clue: '2003 Ferrell film'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'DAKAR', number: 46, clue: 'Westernmost city on the African mainland'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'APNEA', number: 47, clue: 'It takes your breath away?'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 9, col: 3, dir: 'Across', answer: 'MICHAELPHELPS', number: 48, clue: 'He set a new all-time Olympic gold record in 2012 (18 medals!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'MAINEVENT', number: 48, clue: 'Ring leader?'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'PLAY', number: 49, clue: 'VCR button'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'HALLE', number: 50, clue: 'Beautiful Berry'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'EXPEND', number: 51, clue: 'Deplete'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'COAST', number: 52, clue: 'Ivory ___'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'CBGB', number: 52, clue: 'Former Bowery club'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'OVAL', number: 53, clue: 'Elliptical figure'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'FLAXEN', number: 54, clue: '"Hair" adjective'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BVI', number: 55, clue: 'Caribbean archipelago with the capital Road Town: Abbr.'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'IBET', number: 56, clue: 'Sarcastic "Sure"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'BASTE', number: 57, clue: 'Tend to the turkey'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'EMT', number: 58, clue: 'CPR expert'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'TSONGAS', number: 59, clue: '1992 Presidential candidate Paul'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'ALP', number: 60, clue: 'European high point'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 14, dir: 'Across', answer: 'EMMY', number: 61, clue: 'Award for Lucille Ball'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'MRFIXIT', number: 62, clue: 'He\'s good with his hands'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 16, dir: 'Down', answer: 'MEANIES', number: 63, clue: 'Blue ___ (music-hating army)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 11, col: 17, dir: 'Down', answer: 'YAM', number: 64, clue: 'Thanksgiving tuber'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'GANGNAMSTYLE', number: 65, clue: 'Song whose music video set a new record on YouTube in 2012 (over 1,000,000,000 views!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'GUIANA', number: 66, clue: 'French ___'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'TWEEZE', number: 67, clue: 'Pluck'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 12, col: 14, dir: 'Across', answer: 'AREA', number: 68, clue: 'Calculus calculation'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BLEU', number: 69, clue: 'Color on the French flag'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'STOW', number: 70, clue: 'Make use of an overhead bin'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'ENO', number: 71, clue: 'Ambient musician Brian'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'ORMAN', number: 72, clue: '"The Road to Wealth" author Suze'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 13, col: 15, dir: 'Across', answer: 'FAM', number: 73, clue: 'Bro, sis, et al.'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 3, dir: 'Across', answer: 'VIET', number: 74, clue: '___ Cong'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 5, dir: 'Down', answer: 'EVER', number: 75, clue: 'Always'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'NET', number: 76, clue: 'Brooklyn player'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 10, dir: 'Down', answer: 'TROU', number: 77, clue: 'Drop ___ (show off one\'s derriere)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'DRAIN', number: 78, clue: 'Sink component'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 14, col: 14, dir: 'Down', answer: 'AMMO', number: 79, clue: 'Magazine filler'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'THEAVENGERS', number: 80, clue: 'Movie that set a new US opening weekend record in 2012 ($207,438,708!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 1, dir: 'Down', answer: 'TDS', number: 80, clue: 'Sixers on the field, briefly'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 2, dir: 'Down', answer: 'HOI', number: 81, clue: '___ polloi'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 7, dir: 'Down', answer: 'NYU', number: 82, clue: 'It\'s home to Tisch'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 11, dir: 'Down', answer: 'SOP', number: 83, clue: 'Use bread on gravy, maybe'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'MMXII', number: 84, clue: 'Year celebrated by this puzzle (heck, it\'s right there in the title!)'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 15, col: 17, dir: 'Down', answer: 'ISO', number: 85, clue: 'Equal prefix'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'DONNE', number: 86, clue: '"Biathanatos" poet John'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 16, col: 7, dir: 'Across', answer: 'YAZOO', number: 87, clue: '\'80s duo with the hit "Situation"'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 16, col: 13, dir: 'Across', answer: 'AMIES', number: 88, clue: 'Parisian pals'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'SITAR', number: 89, clue: '"Hooked on a Feeling" instrument'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 17, col: 7, dir: 'Across', answer: 'USEUP', number: 90, clue: 'Deplete'))
clues_Puzzle_25_2012_in_Review.push(Entry.create(row: 17, col: 13, dir: 'Across', answer: 'NOTSO', number: 91, clue: '"BS!"'))
Puzzle.create(title: 'Puzzle #25 - 2012 in Review', grid: 'ACTED.CACHE.DOWSE|TREVI.AMOUR.ICIER|FELIX.BAUMGARTNER|.ALLIN.JLO.TKOD..|STS.TAZ.DRNO.PSAT|POOL.MEGAMILLIONS|ARNE.ALA.ELLA.CYA|...VATDYE...DAKAR|..MICHAELPHELPS..|COAST...FLAXEN...|BVI.IBET.ALP.EMMY|GANGNAMSTYLE.AREA|BLEU.STOW.ENO.FAM|..VIET.NET.DRAIN.|THEAVENGERS.MMXII|DONNE.YAZOO.AMIES|SITAR.USEUP.NOTSO', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-1-4', entries: clues_Puzzle_25_2012_in_Review, puzzle_type: 'themed')
