clues_Puzzle_32_Bjorn_Again = Array.new
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BESS', number: 1, clue: 'First Lady born a Wallace'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BEGS', number: 1, clue: 'Asks for anything'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ERIK', number: 2, clue: 'The Phantom of the Opera'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SIMI', number: 3, clue: 'West coast valley'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SEMPER', number: 4, clue: '___ fidelis'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'MEET', number: 5, clue: 'Swimming competition'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MAGNA', number: 5, clue: '___ Doodle'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EXITS', number: 6, clue: 'Gets out'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ELMS', number: 7, clue: 'Shady bunch?'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TEM', number: 8, clue: 'President pro ___'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'EDDIE', number: 9, clue: 'Pearl Jam singer Vedder'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'EGGERT', number: 9, clue: 'Nicole who played Jamie on "Charles in Charge" (but you might remember her from "Baywatch")'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'DRINKSTO', number: 10, clue: 'Toasts'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'DAME', number: 11, clue: 'Helen Mirren, e.g.'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'INME', number: 12, clue: '"I\'ve Got the Music ___" (oft-covered Kiki Dee song)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EDER', number: 13, clue: '___ Dam ("Call of Duty 3" map set in Hesse)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ERIE', number: 14, clue: 'Canal since 1825'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AXLE', number: 15, clue: 'Shaft in the garage'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'GRAND', number: 16, clue: 'K'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GIMMEGIMMEGIMME', number: 17, clue: 'Spoiled brat\'s repetitive cry'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'EATERY', number: 18, clue: 'Restaurant'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'EVILEYE', number: 19, clue: 'The Italians call it "malocchio"'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SKIPANTS', number: 20, clue: 'Often insulated and water-resistant piece of sportswear'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'VENEER', number: 21, clue: 'Dental porcelain piece'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ETAS', number: 22, clue: 'Concerns for "The Amazing Race" teams: Abbr.'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'KIRK', number: 23, clue: 'Cameron who won a 1990 Kids\' Choice Award'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'KAREN', number: 23, clue: 'Carpenter who died at age 32'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'ACRE', number: 24, clue: 'Plot portion'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ALOOP', number: 24, clue: 'Throw for ___'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'CANNY', number: 25, clue: 'Frugal'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'MALTSHOP', number: 26, clue: 'Place for a date (maybe 60 years ago)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'MINUS', number: 26, clue: 'Sign in algebra class'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'HANOI', number: 27, clue: 'Second-largest Vietnamese city'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'OPEDS', number: 28, clue: 'Newspaper opinion pieces'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'PAYS', number: 29, clue: 'Compensates'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALA', number: 30, clue: 'Apple pie ___ mode'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'AMTS', number: 30, clue: 'Tsps. and tbsps.'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'REHIRE', number: 31, clue: 'Take back on'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'EMBARGO', number: 32, clue: 'Stop order?'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'HORSE', number: 33, clue: 'Shooting competition'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'TAPA', number: 34, clue: 'Spanish appetizer'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MONEYMONEYMONEY', number: 35, clue: 'Lottery winner\'s repetitive cry'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'EIGHTIES', number: 36, clue: 'Era of Reaganomics'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'MINCED', number: 37, clue: '___ oath'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TONI', number: 38, clue: '\'90s Bull Kukoc'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'BRUNEI', number: 39, clue: 'About 1% of Borneo'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ODS', number: 40, clue: 'Uses too much, briefly'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SPYGLASS', number: 41, clue: 'Pirate\'s device'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'LEIDAY', number: 42, clue: 'Hawaiian celebration'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'NCIS', number: 43, clue: 'Long-running Pauley Perrette series'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'CHROMA', number: 44, clue: '___ key (TV meteorologist\'s technique)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'HERE', number: 45, clue: 'In this very spot'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'KOCH', number: 46, clue: 'Former NYC mayor who passed away 2/1/13'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'KNOLL', number: 46, clue: 'Small hill'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ODILE', number: 47, clue: '"Swan Lake" swan'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ZAFTIG', number: 48, clue: 'Rubenesque'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'ZIMA', number: 48, clue: 'Alcoholic beverage discontinued in the US in 2008'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ADIN', number: 49, clue: 'Wimbledon score'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'FONT', number: 50, clue: 'Church feature'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'UNDERPAR', number: 51, clue: 'Bad in the business world but good on the golf course'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'UDAY', number: 51, clue: 'Hussein whose desk inspired Dwight\'s (acting) manager desk on "The Office"'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'PIBB', number: 52, clue: '___ Xtra (soft drink)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ADAB', number: 53, clue: 'Not much'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ROSA', number: 54, clue: '"Surfer ___" (Pixies album)'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IDOIDOIDOIDOIDO', number: 55, clue: 'Enthusiastic groom\'s repetitive cry'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'IMP', number: 56, clue: 'Gremlin-like creature'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MINEA', number: 57, clue: '"Make ___ double"'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'MALL', number: 58, clue: '"Shop \'til You Drop" setting'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'MBAS', number: 59, clue: 'They\'re framed on Wall St.'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ANTSY', number: 60, clue: 'Fidgety'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'PYLE', number: 61, clue: 'Goober on TV'))
clues_Puzzle_32_Bjorn_Again.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ABBA', number: 62, clue: 'Palindromic pop group that had hits with 17-, 35- and 55-Across'))
Puzzle.create(title: '#32 - Bjorn Again', grid: 'BESS.MEET.EDDIE|ERIE.AXLE.GRAND|GIMMEGIMMEGIMME|SKIPANTS.VENEER|...ETAS.KIRK...|.ACRE..MALTSHOP|ALA.REHIRE.TAPA|MONEYMONEYMONEY|TONI.BRUNEI.ODS|SPYGLASS..NCIS.|...HERE.KOCH...|ZAFTIG.UNDERPAR|IDOIDOIDOIDOIDO|MINEA.MALL.MBAS|ANTSY.PYLE.ABBA', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-2-22', entries: clues_Puzzle_32_Bjorn_Again, puzzle_type: 'themed')
