clues_Puzzle_9_Themeless_3 = Array.new
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SLEDDERS', number: 1, clue: 'They go downhill fast'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SHBOOM', number: 1, clue: '\'50s hit featured in "Clue"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LOUVRE', number: 2, clue: 'Where "St. Michael Vanquishing Satan" is set'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ENTAIL', number: 3, clue: 'Call for'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'DEF', number: 4, clue: '3 letters?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DYING', number: 5, clue: 'On the way out'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'EBRO', number: 6, clue: 'It collects some of the rain in Spain'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'REST', number: 7, clue: 'Remainder'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SETTLERSOFCATAN', number: 8, clue: 'Game involving a lot of hexes?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'EXALTS', number: 9, clue: 'Praises'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'EMMAS', number: 9, clue: 'Actresses Thompson and Watson'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'XOUT', number: 10, clue: 'Remove from contention, in a way'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ATS', number: 11, clue: 'Email address components'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LITERATI', number: 12, clue: 'Bookies?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TODDAKIN', number: 13, clue: 'Controversial 2012 Senate seat seeker'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SNOOPING', number: 14, clue: 'Poking one\'s nose'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HONEYBEE', number: 15, clue: 'One with a hive mentality'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'MOTION', number: 16, clue: 'Moving party\'s creation'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BUTFIRST', number: 17, clue: 'One of Julie Chen\'s "Big Brother" catchphrases'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'MUSTDO', number: 18, clue: 'Number one priority'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OVA', number: 19, clue: 'Some sex cells'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'NOTTHAT', number: 20, clue: '"My worst fears have been realized!"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'HOP', number: 21, clue: '2011 holiday film featuring the reality show "Hoff Knows Talent"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'EDO', number: 22, clue: 'Asian city renamed in 1868'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ORING', number: 23, clue: 'Challenger\'s trouble'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'NOUVEAU', number: 24, clue: 'Club ___ ("Lean on Me" band)'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'LOS', number: 25, clue: '___ Lobos'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'TRAP', number: 26, clue: 'Shooting discipline'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'THEDEEP', number: 26, clue: '1977 film featuring Jacqueline Bisset in a wet T-shirt'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'MELO', number: 27, clue: 'Dramatic start?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'STEP', number: 28, clue: 'Foothold'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'SSGT', number: 28, clue: 'USAF rank just above Senior Airman'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'TEA', number: 29, clue: 'Tetley offering'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'KHAKI', number: 30, clue: 'Fabric from the Urdu for "dusty"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'KIDS', number: 30, clue: '"Bye Bye Birdie" number'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'UNSER', number: 31, clue: 'Big name in racing'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'NEST', number: 32, clue: 'Treehouse?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'PIETIN', number: 33, clue: 'Frisbee inspiration'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'PEER', number: 33, clue: 'Review sort'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'LASVEGASWEDDING', number: 34, clue: 'Western union?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'LAPDANCE', number: 34, clue: 'Ay, there\'s the rub?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'ALLINALL', number: 35, clue: 'At the end of the day'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'SWEETPEA', number: 36, clue: '1966 Tommy Roe hit with the lyrics "Come on and dance with me / Come on, come on, come on and dance with me"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'WBA', number: 37, clue: 'Org. in which Floyd Mayweather, Jr. fights'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ALWEST', number: 38, clue: 'Div. for the Astros (starting in 2013)'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'OBESE', number: 39, clue: 'With a high BMI'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'PLEAT', number: 40, clue: 'Feature on the back of a dress shirt'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'AFAR', number: 41, clue: 'A distance'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'ALY', number: 41, clue: '___ & AJ (former name of pop duo 78violet)'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'ESTA', number: 42, clue: 'Spanish demonstrative'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'SALTII', number: 43, clue: 'Carter/Brezhnev affair'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'TWEENS', number: 44, clue: 'They\'re not allowed on Facebook (but you might find them anyway)'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ANADEM', number: 45, clue: 'Head wreath'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'DIEU', number: 46, clue: 'French god'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'TLC', number: 47, clue: '"Here Comes Honey Boo Boo" network'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'TONES', number: 47, clue: 'Pitches'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'SPAWN', number: 48, clue: 'Come into existence, as a video game enemy'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'SEGNO', number: 48, clue: 'Dal ___ (score note)'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ANT', number: 49, clue: 'Farm animal?'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'ROYALWE', number: 50, clue: 'Elizabeth I\'s I'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'RISD', number: 50, clue: 'Providence coll. whose application requires a drawing referencing a bicycle'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'LAME', number: 51, clue: 'Weak'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'WRAP', number: 52, clue: 'Panini alternative'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'LEA', number: 53, clue: 'Michele of "Glee"'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'NAPKIN', number: 54, clue: 'One folded at brunch'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'KEN', number: 55, clue: 'Loser to Watson'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'TARGETED', number: 56, clue: 'Went after'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'EDT', number: 57, clue: 'NYC setting in September'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CLEESE', number: 58, clue: 'Nearly Headless Nick portrayer'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'AMANDINE', number: 59, clue: 'Nutty, perhaps'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ELANDS', number: 60, clue: 'Veldt herd'))
clues_Puzzle_9_Themeless_3.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'NEPOTISM', number: 61, clue: 'Giving your brother the business, say'))
Puzzle.create(title: '#9 - Themeless #3', grid: 'SLEDDERS.EXALTS|HONEYBEE.MOTION|BUTFIRST.MUSTDO|OVA.NOTTHAT.EDO|ORING..LOS.TRAP|MELO.STEP.KHAKI|...UNSER.PIETIN|LASVEGASWEDDING|ALWEST.OBESE...|PLEAT.AFAR.ESTA|DIEU.TLC..SPAWN|ANT.ROYALWE.LEA|NAPKIN.TARGETED|CLEESE.AMANDINE|ELANDS.NEPOTISM', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2012-9-14', entries: clues_Puzzle_9_Themeless_3, puzzle_type: 'freestyle')
