clues_Puzzle_34_March_Madness = Array.new
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ASSTS', number: 1, clue: 'Paralegals, e.g.'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ALSO', number: 1, clue: 'Plus'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'SOWN', number: 2, clue: 'Scattered, like seeds'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SEER', number: 3, clue: 'One with spiritual insight'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TWEETS', number: 4, clue: 'Posts a short status online'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SETPIECE', number: 5, clue: 'Carpenter\'s stage creation'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ETNA', number: 6, clue: 'Sicilian mount'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EMIR', number: 6, clue: 'Middle Eastern ruler'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TEXT', number: 7, clue: 'Mobile message'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NOT', number: 8, clue: '"Yeah, right!"'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'AWE', number: 9, clue: 'State of wonder'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ACTS', number: 10, clue: 'Does like Danny DeVito'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ACNE', number: 10, clue: 'Teen\'s trouble'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CABCOMPANY', number: 11, clue: 'A bunch of hacks?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TRIKE', number: 12, clue: 'Little kid\'s vehicle'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SATYR', number: 13, clue: 'Companion of Pan'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LOEWE', number: 14, clue: 'Broadway composer Frederick'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'MEOW', number: 15, clue: 'Catcall?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'CARA', number: 16, clue: '"Fame" singer Irene'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SWEETSIXTEENBIT', number: 17, clue: 'Lovable era of classic video games?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'SOP', number: 18, clue: 'Soak (up)'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'EBAY', number: 19, clue: 'Seller\'s site'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ONREPORT', number: 20, clue: 'In serious trouble'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'BECKY', number: 21, clue: 'Thatcher created by Mark Twain'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'TIP', number: 22, clue: 'Waitress\'s reward'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'RNA', number: 23, clue: 'Single-stranded molecule'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'RASHAD', number: 23, clue: '1979 Pro Bowl MVP Ahmad'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'NYETS', number: 24, clue: 'Russian refusals'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'OER', number: 25, clue: '"___ the fields we go..."'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'POSSE', number: 26, clue: 'Sheriff\'s bunch'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PEEN', number: 26, clue: 'Hammer\'s end'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OSLO', number: 27, clue: 'City 240 miles west of Uppsala'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'SPITSHINES', number: 28, clue: 'Does a soldier\'s chore'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'KHAYYAM', number: 29, clue: 'Persian mathematician Omar'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'KEITEL', number: 29, clue: 'Harvey of "Thelma & Louise"'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'HAGEN', number: 30, clue: '"Who\'s Afraid of Virginia Woolf?" Tony winner Uta'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'AIR', number: 31, clue: 'Diving cylinder\'s contents'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ESP', number: 32, clue: '3-Down\'s asset'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'CREASE', number: 33, clue: 'Hockey rink area'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'REAPS', number: 34, clue: 'Brings in, as a crop'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'IPAS', number: 35, clue: 'Some pub selections, briefly'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ACRE', number: 36, clue: 'Farmer\'s unit'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SKAT', number: 37, clue: 'Three-player card game'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ELITEEIGHTTRACK', number: 38, clue: 'Best classic music format?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'THU', number: 39, clue: 'Wed. follower'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'TEAROOMS', number: 40, clue: 'Cozy spots?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'NOTH', number: 41, clue: 'Chris of "The Good Wife"'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ATEASE', number: 42, clue: 'Order to relax'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'NRA', number: 43, clue: 'Org. promoting marksmanship'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'SUSPEND', number: 44, clue: 'Take out of class for a while'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SAIL', number: 45, clue: 'Go boating'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ASYET', number: 46, clue: 'Until now'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SITSON', number: 47, clue: 'Holds back, as information'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'WAH', number: 48, clue: '1964 hit "Do ___ Diddy Diddy"'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'WAFER', number: 48, clue: 'Communion offering'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ALIVE', number: 49, clue: 'In play'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'ASL', number: 50, clue: 'Specialty at Gallaudet Univ.'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'ARI', number: 51, clue: 'NPR correspondent Shapiro'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'AMP', number: 51, clue: 'Roadie\'s burden'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ALIBI', number: 52, clue: 'Cover story?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'BART', number: 53, clue: 'Homer Simpson\'s eldest child'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'DEMOTAPE', number: 54, clue: 'Unsigned band\'s sample'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'DUDS', number: 54, clue: 'Clothes, in slang'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'ERIC', number: 55, clue: 'Children\'s author Carle'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ATRA', number: 56, clue: 'Gillette brand'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'PEAR', number: 57, clue: 'Still life fruit'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ERNE', number: 58, clue: 'Sea eagle'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'FINALFOURPOSTER', number: 59, clue: 'Last of the classic beds?'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'FAD', number: 60, clue: 'Passing phase'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'OUI', number: 61, clue: 'French affirmation'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EVER', number: 62, clue: 'Once'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'AUDI', number: 63, clue: 'Car manufacturer with an Euler diagram logo'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'MORAN', number: 64, clue: 'Erin of "Joanie Loves Chachi"'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REST', number: 65, clue: 'Action in bed'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DISC', number: 66, clue: 'PS4 game\'s medium'))
clues_Puzzle_34_March_Madness.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SNARE', number: 67, clue: 'It\'s a trap'))
Puzzle.create(title: 'Puzzle #34 - March Madness', grid: 'ASSTS.ETNA.ACTS|LOEWE.MEOW.CARA|SWEETSIXTEENBIT|ONREPORT..BECKY|...TIP..RNA.OER|POSSE.KHAYYAM..|ESP.CREASE.IPAS|ELITEEIGHTTRACK|NOTH.ATEASE.NRA|..SUSPEND.ASYET|WAH.ASL..ARI...|ALIBI..DEMOTAPE|FINALFOURPOSTER|EVER.AUDI.MORAN|REST.DISC.SNARE', :constructors => Constructor.where(:name => 'Neville Fogarty'), :sources => Source.where(:name => 'Neville Fogarty'), publication_date: '2013-3-8', entries: clues_Puzzle_34_March_Madness, puzzle_type: 'themed')
