clues_ACTION_CR_6_3_10 = Array.new
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TVROOM', number: 1, clue: 'Den'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TBA', number: 1, clue: 'Not yet nailed down, for short'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'VOL', number: 2, clue: 'Switch on a radio: Abbr.'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RUN', number: 3, clue: 'Leak'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ORINGS', number: 4, clue: 'Space shuttle seals'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ONCE', number: 5, clue: 'Long ago'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MEOW', number: 6, clue: '"Sex-y!"'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'BELA', number: 7, clue: 'Fleck of the Flecktones'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BETAMAX', number: 7, clue: 'Loser to VHS'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EXEMPT', number: 8, clue: 'Above the rules, in a way'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LEAP', number: 9, clue: 'Try to make it over a chasm, say'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ACTSO', number: 10, clue: '"Don\'t ___ mad!"'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'GIB', number: 11, clue: 'Male cat'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'GODIVA', number: 11, clue: 'Lady who almost always appears naked'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'INURED', number: 12, clue: 'Used (to)'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BOGEYS', number: 13, clue: 'They\'re over par'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BOURNE', number: 14, clue: 'Damon character, in several films'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'EXEC', number: 15, clue: 'Biz honcho'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ONO', number: 16, clue: 'Artist who still lives at the Dakota in New York City'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ALNICO', number: 17, clue: 'Metal alloy named for its elements'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 3, col: 8, dir: 'Across', answer: 'TEAT', number: 18, clue: 'You suck if you use one'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'DUG', number: 19, clue: 'Liked, as a hippie would'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'NEWHAMPSHIRE', number: 20, clue: 'Primary state'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 4, col: 7, dir: 'Down', answer: 'HALOS', number: 21, clue: 'Holy glows'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'HYPED', number: 22, clue: 'Talked about in advance'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ABIG', number: 23, clue: '"It\'s not ___ truck. It\'s a series of tubes" (Senator Ted Stevens describing the internet)'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'AGTS', number: 23, clue: 'FBI workers'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'BLAH', number: 24, clue: 'Boring'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'IAGO', number: 25, clue: 'Classic villain'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'AMP', number: 26, clue: 'Bassist\'s need'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'OYVEY', number: 27, clue: '"Sheesh!"'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'GLASSPLATE', number: 28, clue: 'Window, e.g.'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'SLUG', number: 29, clue: 'Nickname for a slow person'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'PENIS', number: 30, clue: '"The ___ mightier ..."'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ELENA', number: 31, clue: 'Kagan who saved crossword constructors from having to reference a very old actress or a Russian tennis player'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'PADS', number: 32, clue: 'Monthly toiletries'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TAG', number: 33, clue: '"You\'re it!"'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'LEOX', number: 34, clue: 'He challenged Martin Luther'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'LEE', number: 35, clue: 'Bruce or Ben'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'EDAM', number: 36, clue: 'Mild cheese'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SHOGUNS', number: 37, clue: 'Erstwhile Japanese generals'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'GAMMA', number: 38, clue: 'Kind of ray'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'REDDAWN', number: 39, clue: 'Cold War teen defense fantasy starring Patrick Swayze'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'RABID', number: 39, clue: 'Like some scary dogs'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'AMSO', number: 40, clue: 'Playground retort'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'WIKI', number: 41, clue: 'Collaboratively edited site'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'NASD', number: 42, clue: 'Stock market overseer, formerly: Abbr.'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'AGI', number: 43, clue: 'Tax form fig.'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'SANA', number: 44, clue: 'Yemen\'s capital'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SUBROSA', number: 44, clue: 'In secret'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'MIA', number: 45, clue: 'With 46-Across, soccer star who holds the world record for most goals in international competition'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'HAMM', number: 46, clue: 'See 45-Across'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'HAULER', number: 46, clue: 'Sanitation worker, at times'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ARROYO', number: 47, clue: 'Gulch'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'MOBLED', number: 48, clue: 'Like some street violence'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'SCUBAMASKS', number: 49, clue: 'Divers\' needs'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'CRAMER', number: 50, clue: '"Mad Money" host Jim'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'ANSELM', number: 51, clue: 'Canterbury saint'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'AROMA', number: 52, clue: 'Wafting thing'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ANNEX', number: 53, clue: 'Take, as land'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'RBI', number: 54, clue: 'You might get one for a sac fly'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'NOID', number: 55, clue: 'Character to avoid, in old Domino\'s ads'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'URBANGARDENS', number: 56, clue: 'Sources of local produce'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'GOVT', number: 57, clue: 'The feds, in newspaper headlines'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'EPIC', number: 58, clue: 'Long, as a film'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'NONO', number: 59, clue: 'Taboo'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LOL', number: 60, clue: '"LMAO" alternative'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'NOMO', number: 61, clue: 'Hideo who threw two no-hitters'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 10, dir: 'Across', answer: 'POETRY', number: 62, clue: 'It may be performed at a slam'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'TAI', number: 63, clue: 'Mai ___ (rum cocktail)'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'RIC', number: 64, clue: 'Ocasek of The Cars'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'YDS', number: 65, clue: '"Madden 2010" stats'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EYE', number: 66, clue: 'Keep a watch on'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'EVES', number: 67, clue: 'Nights before holidays'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'INLAID', number: 68, clue: 'Depressed at the craft fair?'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ROD', number: 69, clue: 'One of Ned Flanders\'s sons'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'XTRA', number: 70, clue: 'More, in adspeak'))
clues_ACTION_CR_6_3_10.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'COMICS', number: 71, clue: 'Where one might see the sounds embedded in this puzzle\'s theme answers'))
spec_feat = '1_2:C|1_3:C|1_4:C|1_5:C|1_6:C|4_6:C|4_7:C|4_8:C|4_9:C|6_5:C|6_6:C|6_7:C|6_8:C|6_9:C|10_9:C|10_10:C|10_11:C|12_3:C|12_4:C|12_5:C|12_6:C'
Puzzle.create(title: 'ACTION! ', grid: 'TVROOM.BELA.GIB|BOURNE.EXEC.ONO|ALNICO.TEAT.DUG|...NEWHAMPSHIRE|ABIG..AMP.OYVEY|GLASSPLATE.PADS|TAG.LEOX.LEE...|SHOGUNS.REDDAWN|...AGI.SANA.MIA|HAMM.SCUBAMASKS|AROMA.RBI..NOID|URBANGARDENS...|LOL.NOMO.POETRY|EYE.EVES.INLAID|ROD.XTRA.COMICS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/6/3', entries: clues_ACTION_CR_6_3_10, special_features: spec_feat)
