clues_AtPlay_CR_5_20_10 = Array.new
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PCB', number: 1, clue: 'Chem. contaminant banned by the U.S. in 1979'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PASS', number: 1, clue: '"Press Your Luck" option'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CINEPHILE', number: 2, clue: 'Tarantino, notably'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BROCHURES', number: 3, clue: 'Salesperson\'s handouts'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'SIRE', number: 4, clue: 'Stable father figure?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SUBABBOT', number: 4, clue: 'Clergy member'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'IRANIAN', number: 5, clue: 'From Shiraz, say'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RANTAT', number: 6, clue: 'Berate'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ELKS', number: 7, clue: 'British Columbian wilderness animals'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'JIGSAW', number: 8, clue: 'Puzzle-cutting tool'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'JUT', number: 8, clue: 'Protrude'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ITHINK', number: 9, clue: 'Uncertain caveat'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GOES', number: 10, clue: 'Micturates'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SPITS', number: 11, clue: 'Expectorates'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'AISLE', number: 12, clue: 'What the beverage cart rolls down'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'WATER', number: 13, clue: 'Tend, as houseplants'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AIR', number: 14, clue: 'Filling for some guest mattresses'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'URAL', number: 15, clue: 'Silk Road river'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'UTOPIA', number: 16, clue: 'Literally, "no place," in Greek'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SNO', number: 17, clue: '___-Caps (theater candy)'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'BANKATHEIST', number: 18, clue: 'Godless teller?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'AYEAYE', number: 19, clue: 'Agreement from one on deck'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SEC', number: 20, clue: '"Wait a ___!"'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'ANTSY', number: 21, clue: 'Itching to leave, say'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'ISTLE', number: 22, clue: 'Carpet fiber'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'PHOBIA', number: 23, clue: 'Ungrounded fear'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'OMERTA', number: 24, clue: 'Mario Puzo bestseller'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'EIN', number: 25, clue: 'Article for Gutenberg'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ICE', number: 26, clue: 'Sculpture material'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'SER', number: 27, clue: 'Sun. talk'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'THUMBATTACKS', number: 28, clue: 'Gouger\'s onslaughts?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'THAW', number: 28, clue: '26-Down sculptor\'s concern'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TROVE', number: 29, clue: 'Treasure cache'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'STRIDE', number: 30, clue: 'Unit of progress'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HIREON', number: 31, clue: 'Add to the staff'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'RYE', number: 32, clue: 'Loaf reliably available at cousin Lotte\'s house when we used to go up to Cleveland for brunch'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'TANG', number: 33, clue: 'Space camp drink'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'ALGONQUIN', number: 34, clue: '___ Round Table (erstwhile New York City intelligentsia collective)'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'NEONTETRA', number: 35, clue: 'Common aquarium fish'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'GENE', number: 36, clue: 'Trait carrier'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ALERT', number: 37, clue: 'Sign word that may be followed by an exclamation point'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'ROE', number: 38, clue: 'Sushi roll topper'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'RUNDMC', number: 38, clue: '"Christmas In Hollis" group'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'MRLEE', number: 39, clue: '1957 hit for the Bobbettes'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'MADMONEY', number: 39, clue: 'CNBC show much criticized by Jon Stewart in early 2009'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'WEST', number: 40, clue: 'Loose cannon Kanye'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'SUV', number: 41, clue: 'Wheels notoriously prone to rolling (over)'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'SOD', number: 41, clue: 'Turf'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'SAIGON', number: 42, clue: 'Reunification Train city'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'SNORING', number: 42, clue: 'Being loud in bed?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ATONEANDDONE', number: 43, clue: 'Do a quick Erev Yom Kippur, show your face for Kol Nidre, no muss no fuss?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'TOARMS', number: 44, clue: 'Battle cry'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'AFRAID', number: 45, clue: 'Chicken'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'KGS', number: 46, clue: 'Metric wts.'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'KVASS', number: 46, clue: 'Mildly alcoholic Russian drink made from fermented bread (better than it sounds)'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'GOTTA', number: 47, clue: '"Something\'s ___ Give"'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'SITON', number: 48, clue: 'Use, as a bench'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'ODD', number: 49, clue: 'Curious'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'FOMENT', number: 50, clue: 'Stir up, as a revolt'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'VOILA', number: 51, clue: '"And there you have it!"'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'LIRE', number: 52, clue: 'Milano currency, once'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'MORRO', number: 53, clue: 'Cuba\'s ___ Castle'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'OHME', number: 54, clue: '"Fuck," a whole lot more politely'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'QED', number: 55, clue: '"And there you have it!" to a mathematician'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'DEEP', number: 56, clue: 'Thoughtful'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ATTIRECHAIN', number: 57, clue: 'TJ Maxx, e.g.?'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'EST', number: 58, clue: 'Educated guess: Abbr.'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'UTE', number: 59, clue: 'Colorado native'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'STORMS', number: 60, clue: 'They may be weathered'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'MINE', number: 61, clue: 'Greedy child\'s cry'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'IRE', number: 62, clue: 'Incense'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SANEST', number: 63, clue: 'Most together, mentally'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'EDGY', number: 64, clue: 'Like performance art, often'))
clues_AtPlay_CR_5_20_10.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'NAP', number: 65, clue: 'Cranky person\'s need'))
Puzzle.create(title: '@ Play', grid: 'PCB.SIRE.JIGSAW|AIR.URAL.UTOPIA|SNO.BANKATHEIST|SEC.ANTSY.ISTLE|.PHOBIA.EIN.SER|THUMBATTACKS...|HIREON.RYE.TANG|ALERT.ROE.MRLEE|WEST.SUV.SAIGON|...ATONEANDDONE|KGS.ODD.FOMENT.|VOILA.MORRO.QED|ATTIRECHAIN.UTE|STORMS.MINE.IRE|SANEST.EDGY.NAP', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/5/20', entries: clues_AtPlay_CR_5_20_10)
