clues_Capital_Infusions_CR_6_24_10 = Array.new
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ZOMG', number: 1, clue: 'Variation of an online term that supposedly originated with someone missing the SHIFT key'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ZED', number: 1, clue: 'End of a South African sequence'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ORE', number: 2, clue: 'Raw metal source'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MIL', number: 3, clue: 'A lot of money, casually'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'GEM', number: 4, clue: 'Beaut'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'UZI', number: 5, clue: 'Israeli submachine gun'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'USNR', number: 5, clue: 'Gp. that may be deployed'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ZITI', number: 6, clue: 'Pasta with a ridged surface, often'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'IBEG', number: 7, clue: 'Words before your pardon'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'TRAVIS', number: 8, clue: 'Scottish band with "Sing"'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'THEMOB', number: 8, clue: 'Group where men are made'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'RADIUSES', number: 9, clue: 'Some geometry class lines'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'AMIN', number: 10, clue: 'The "Butcher of Uganda"'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'VISOR', number: 11, clue: 'Golf course headwear'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ITOUT', number: 12, clue: '"Cut ___!" ("Full House" catchphrase)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SENSE', number: 13, clue: 'Have a vague feeling about'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ERIE', number: 14, clue: 'Great Lakes tribe'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'SIB', number: 15, clue: 'Bro or sis'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'HAMITE', number: 16, clue: 'Member of a certain biblical ethnic group'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DELMONTE', number: 17, clue: 'With 60-Across, deliberate damage to a fruit company\'s promotional movie? (Uruguay)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'OOPS', number: 18, clue: 'Post-accident word'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'EDISON', number: 19, clue: '"The Wizard of Menlo Park"'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'ORIGAMINOUS', number: 20, clue: 'Artfully folded? (Latvia)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'AIM', number: 21, clue: 'Noted AOL chat program'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'APP', number: 22, clue: 'iPad thing'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'ARYAN', number: 22, clue: 'Race invoked by many white supremacists'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'PIETY', number: 23, clue: 'Spiritual seriousness'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'IOU', number: 24, clue: 'Chit'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'RTE', number: 25, clue: 'Map abbr.'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PARISHBOMBS', number: 26, clue: 'Failed jokes in Louisiana? (France)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PAHS', number: 26, clue: 'Sounds of dismissal'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ASEA', number: 27, clue: 'Cruising'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'HIE', number: 28, clue: 'Move quickly, anciently'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'BAN', number: 29, clue: 'Axe alternative'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ONSET', number: 30, clue: 'Beginning'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ASYE', number: 31, clue: '" ___ reap ..."'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'IAN', number: 32, clue: 'James Bond creator Fleming'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ELATE', number: 33, clue: 'Delight'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'LTCOL', number: 34, clue: 'Battalion commander, perhaps: Abbr.'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'ANEYE', number: 35, clue: 'Half of a vindictive biblical axiom'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'TONO', number: 36, clue: 'Up ___ good'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ETTU', number: 37, clue: 'Caesar\'s reproach'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'HEATHENSJUSTNOT', number: 38, clue: 'With 45-Across, self-help book for people trying to get over infidels? (Greece)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'HOTLUNCH', number: 39, clue: 'School cafeteria offering'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'JAI', number: 40, clue: '___ alai'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'URN', number: 41, clue: 'Funereal object, perhaps'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SANYO', number: 42, clue: 'Company bought by Panasonic in 2009'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EAR', number: 43, clue: 'Musician\'s asset'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'CENT', number: 44, clue: 'Bit of copper'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'THATINTOYOU', number: 45, clue: 'See 38-Across'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'HEIGHT', number: 46, clue: 'Doctor\'s office datum'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'ANT', number: 47, clue: 'Kitchen invader'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'TUFE', number: 48, clue: 'Shrimp et ___ (modern spelling of a classic Cajun dish)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ADA', number: 49, clue: 'Nabokov girl'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'AMEBA', number: 49, clue: 'Single-celled creature'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'DOALL', number: 50, clue: 'Handy sort'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'ASSAI', number: 51, clue: 'Very, on scores'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'LEN', number: 52, clue: '___ Grossman (Tom Cruise character in "Tropic Thunder")'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'ULE', number: 53, clue: 'Suffix with mod'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MOSQUITODEF', number: 54, clue: 'Dope blood drinker?/Rapper generating a lot of buzz? (Ecuador)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'QING', number: 55, clue: 'Longstanding Chinese dynasty'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'OVEN', number: 56, clue: 'Place for an unborn baby, so to speak'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'DIME', number: 57, clue: 'Smoker\'s quantity'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'EDIT', number: 58, clue: 'Menu bar option'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EASING', number: 59, clue: 'Letting off the throttle, with "up"'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'VIDEOMAR', number: 60, clue: 'See 17-Across'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ONE', number: 61, clue: 'I'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'MAX', number: 62, clue: '"Saved by the Bell" hangout, with "the"'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'AVE', number: 63, clue: 'Map abbr.'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'RID', number: 64, clue: 'Free (of)'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BLANCH', number: 65, clue: 'Boil quickly, as almonds'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'EMI', number: 66, clue: 'London-based music giant'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'NAVI', number: 67, clue: '"Avatar" race'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ALIGHT', number: 68, clue: 'Land'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'NET', number: 69, clue: 'Accounting figure'))
clues_Capital_Infusions_CR_6_24_10.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'EXED', number: 70, clue: 'Crossed (out)'))
Puzzle.create(title: 'Capital Infusions', grid: 'ZOMG.UZI.TRAVIS|ERIE.SIB.HAMITE|DELMONTE.EDISON|....ORIGAMINOUS|..APP...IOU.RTE|PARISHBOMBS....|ASYE.IAN..ELATE|HEATHENSJUSTNOT|SANYO..EAR.CENT|....THATINTOYOU|ADA.LEN...ULE..|MOSQUITODEF....|EASING.VIDEOMAR|BLANCH.EMI.NAVI|ALIGHT.NET.EXED', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/6/24', entries: clues_Capital_Infusions_CR_6_24_10)
