clues_International_Loans_CR_6_17_10 = Array.new
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'GAP', number: 1, clue: 'Word after gender or credibility'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'GASUP', number: 1, clue: 'Fill the tank'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AMERE', number: 2, clue: '___ pittance'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PIXAR', number: 3, clue: '"Up" studio'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'DOG', number: 4, clue: 'Marmaduke, e.g.'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DULUTH', number: 4, clue: 'Bob Dylan\'s hometown in Minnesota'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ONESPADE', number: 5, clue: 'Bridge opening'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'GOD', number: 6, clue: 'Biblical boss'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'EMF', number: 7, clue: 'Band whose "Unbelievable" samples Andrew Dice Clay'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ENOUGH', number: 7, clue: '"Just stop!"'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MAINST', number: 8, clue: 'Thoroughfare in Anytown, USA'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'FENN', number: 9, clue: 'Actress Sherilyn of "Twin Peaks"'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'THC', number: 10, clue: 'Baking ingredient?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'THENINETY', number: 10, clue: 'With 51-Across, book about a terrible baseball season?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'HUR', number: 11, clue: '"Ben-___"'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CDS', number: 12, clue: 'Media that may be ripped to 56-Across'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMI', number: 13, clue: '"Who ___ to say?"'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'UNO', number: 14, clue: 'Mattel game'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'NAE', number: 15, clue: '"If it\'s ___ Scottish ..."'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'HUD', number: 16, clue: 'Paul Newman title role'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SEXILED', number: 17, clue: 'Banished to the dorm\'s common area for fifteen minutes, slangily'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'INO', number: 18, clue: 'She rescued Odysseus'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'OINKERS', number: 19, clue: 'Pigs'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'KAL', number: 20, clue: 'Actor Penn who played Kumar'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'URANUS', number: 21, clue: 'Oft-snickered-at planet'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'YUNNAN', number: 22, clue: 'Southern Chinese province'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 4, col: 8, dir: 'Down', answer: 'YUGOSLAVS', number: 22, clue: 'Ethnic minorities more numerous in the U.S. than in Bosnia and Herzegovina'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'PEROTPLUGS', number: 23, clue: '1992 presidential campaign ads?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'LUIS', number: 24, clue: 'Jorge ___ Borges'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'LIME', number: 25, clue: 'Margarita garnish'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'MACYS', number: 26, clue: 'New York City parade sponsor'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'EMT', number: 27, clue: 'First responder, often, for short'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'HAUGHTY', number: 28, clue: 'Arrogant'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'YEN', number: 29, clue: 'Craving'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'NAM', number: 30, clue: 'Hanoi Hilton setting, casually'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'EPT', number: 31, clue: 'Brand often used with nervous anticipation'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ECOLI', number: 31, clue: 'Bacteria that might cause a food recall'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'PORESIGHT', number: 32, clue: 'Dermatologist\'s asset?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'TNT', number: 33, clue: '"We know drama" station'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'DIO', number: 34, clue: 'Ronnie James who passed away in May 2010'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ELECT', number: 35, clue: 'Choose, as a comptroller'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'LSD', number: 36, clue: 'Subject of some overreaching 1960s anti-drug propaganda movies'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'CONCESSIONSTY', number: 37, clue: 'Unsanitary place to buy soda and popcorn?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'CAT', number: 38, clue: 'Common viral video animal'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'IOLE', number: 39, clue: 'Hercules\' love'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'OBELISKS', number: 40, clue: 'Phallic shapes of some monuments'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SORTA', number: 41, clue: 'Kinda'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SOS', number: 41, clue: 'Big name in scouring pads'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'LOB', number: 42, clue: 'High tennis shot'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'DYS', number: 43, clue: 'Bad start?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'OLE', number: 44, clue: '___ Miss'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'TOTALER', number: 45, clue: 'One trying to get sum?'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'OFNOTE', number: 46, clue: 'Famous'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'TIESTO', number: 47, clue: 'Connects with'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ROMPER', number: 48, clue: 'One-piece my wife says is fashionable right now'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SISI', number: 49, clue: 'Emphatic assent'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'ITO', number: 50, clue: 'Simpson trial judge Lance'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'FIVELOSSES', number: 51, clue: 'See 10-Down'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'SHA', number: 52, clue: 'Doo-wop syllable'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'SENOR', number: 53, clue: 'Respectful title, abroad'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ERODE', number: 54, clue: 'Diminish, as support'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SELES', number: 55, clue: 'Tennis Hall of Famer Monica'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'ITUNES', number: 56, clue: 'Modern library program'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'ULAN', number: 57, clue: '___ Bator'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'IMHERE', number: 58, clue: 'Attendee\'s response'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'GIGOLOS', number: 59, clue: 'Some seedy bathhouse workers'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'GIN', number: 59, clue: 'Liquor in a famous line from "Casablanca"'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ICE', number: 60, clue: 'It keeps drinks from being neat'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'ESPANOL', number: 61, clue: 'Language into which parts of this puzzle\'s theme answers have been translated'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'EES', number: 61, clue: 'Some MIT grads'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ICH', number: 62, clue: 'German pronoun'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ATT', number: 63, clue: 'QB\'s try'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'EKE', number: 64, clue: 'Squeeze (out)'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ODE', number: 65, clue: 'Praiseful poem'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NET', number: 66, clue: 'Alternative to .org and .com'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'NEO', number: 67, clue: '"The Matrix" protagonist'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'SSR', number: 68, clue: 'Map letters until 1991'))
clues_International_Loans_CR_6_17_10.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'RES', number: 69, clue: 'Hi-___ image'))
spec_feat = '5_1:C|5_2:C|5_3:C|5_4:C|7_3:C|8_3:C|9_3:C|8_14:C|11_10:C|11_11:C|11_12:C'
Puzzle.create(title: 'International Loans', grid: 'GAP.DOG.EMF.THC|AMI.UNO.NAE.HUD|SEXILED.OINKERS|URANUS.YUNNAN..|PEROTPLUGS.LIME|....HAUGHTY.NAM|.EPT.DIO..ELECT|.CONCESSIONSTY.|SORTA..LOB.DYS.|OLE.TOTALER....|SISI.FIVELOSSES|..ITUNES.IMHERE|GIGOLOS.ESPANOL|ICH.ATT.EKE.ODE|NET.NEO.SSR.RES', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/6/17', entries: clues_International_Loans_CR_6_17_10, special_features: spec_feat)
