clues_Intersections_CR_7_1_10 = Array.new
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CROSS', number: 1, clue: 'Word that can precede the first word of the twelve starred entries in this puzzle'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CMON', number: 1, clue: '"Let\'s go already!"'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ROMP', number: 2, clue: 'Broadway comedy descriptor'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'OVERTHEHILL', number: 3, clue: '*Phrase on 40th birthday party mugs'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SIG', number: 4, clue: 'John Hancock, for short'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SEA', number: 5, clue: 'The Baltic, e.g.'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'BOB', number: 6, clue: 'Try to retrieve an apple'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BOWHEAD', number: 6, clue: '*Large Arctic whale'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OMOO', number: 7, clue: 'Melville adventure novel'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BARNONE', number: 8, clue: '*To a man'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'REDUX', number: 9, clue: 'Brought back'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'RAP', number: 9, clue: 'Emulate Kanye, say'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ERR', number: 10, clue: 'Go astray'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'DOE', number: 11, clue: 'Anonymous John'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'USS', number: 12, clue: 'Battleship letters'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'XES', number: 13, clue: 'Pornography letters'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MOVIE', number: 14, clue: 'Part of IMDB'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OMA', number: 15, clue: 'Oncologist\'s suffix'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'AROSE', number: 16, clue: 'Made like a phoenix from the ashes'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OMEGA', number: 17, clue: 'Tag Heuer alternative'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'WORDPRESS', number: 18, clue: '*Popular blogging platform'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'DELAY', number: 19, clue: 'Put off for a while'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'NPR', number: 20, clue: '"Talk of the Nation" syndicator'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'HONE', number: 21, clue: 'Sharpen'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'TRITE', number: 22, clue: 'Hackneyed'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'RADAR', number: 23, clue: 'M*A*S*H nickname'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ICY', number: 24, clue: 'Dangerous to walk on, in a way'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'THE', number: 25, clue: 'None other than'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'OLE', number: 26, clue: 'Nelson Mandela Bay Stadium cry'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'EWE', number: 27, clue: 'Fold female'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'SSE', number: 28, clue: 'Johannesburg-to-Durban dir.'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'STREETSMART', number: 28, clue: '*Unlikely to get suckered'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'SPONGE', number: 29, clue: 'Anti-baby option'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'ESPYS', number: 30, clue: 'Best Jockey and Best Bowler, e.g.'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'CHACHA', number: 31, clue: 'Syncopated Cuban dance'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CIGARS', number: 31, clue: 'They may be handed out after a birth'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'NAW', number: 32, clue: 'Rural turndown'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'TPS', number: 33, clue: 'Engages in some Halloween tomfoolery'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TIEDYED', number: 34, clue: '*Like some workhorse summer camp t-shirts'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'TAHOE', number: 34, clue: 'Chevy SUV'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'EYEDROP', number: 35, clue: '*Unit of ocular relief'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'DELTA', number: 36, clue: 'Airline that merged with Northwest in 2008'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AGHA', number: 37, clue: 'Turkish title'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'EENY', number: 38, clue: 'First word of a kids\' rhyme that ends with "moe"'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'HAIRNET', number: 39, clue: '*Part of a lunch lady\'s get-up'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'NTH', number: 40, clue: 'High degree?'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'EIEIO', number: 41, clue: 'Refrain from preschool'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'TOWNCAR', number: 42, clue: '*Lincoln sedan often used as a vehicle-for-hire'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'PEGLEGS', number: 43, clue: '*Pirate ship prosthetics'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'POSTSEX', number: 43, clue: '*Plan B moment'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'EDA', number: 44, clue: 'Childhood writer LeShan'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'GEL', number: 45, clue: 'Form for some deodorant'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ORL', number: 46, clue: 'Losers to BOS in the 2010 NBA playoffs'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'TIO', number: 47, clue: 'Hermano of a padre'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ODETTE', number: 48, clue: '"Swan Lake" swan'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ESL', number: 49, clue: 'Class for immigrants: Abbr.'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'HEW', number: 50, clue: 'Chop down'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SALAS', number: 51, clue: 'Casa rooms'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'INOT', number: 52, clue: 'Facing sudden death, perhaps'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'OKRA', number: 53, clue: 'Gumbo veggie'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'MLS', number: 54, clue: 'Landon Donovan\'s org.'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'LIRA', number: 55, clue: 'Old Italian currency'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SNOG', number: 56, clue: 'Tongue kiss'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'WINDSOCKS', number: 57, clue: '*Some weather vanes'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'WWE', number: 57, clue: 'Big name in sweaty soap operas for men'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'IRA', number: 58, clue: 'Investment choice, for short'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'NES', number: 59, clue: '"Excitebike" gaming platform'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'DAY', number: 60, clue: 'Light time'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'SKA', number: 61, clue: 'Studio One genre'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'USAIN', number: 62, clue: '100 meter record-holder Bolt'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'UZI', number: 62, clue: 'Six-Day War gun'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'SOD', number: 63, clue: 'Yard surface that\'s rolled out'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WREAK', number: 64, clue: 'Create, as havoc'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ARE', number: 65, clue: '"All your base ___ belong to us"'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ZORRO', number: 66, clue: 'Don Diego de la Vega\'s alter ego'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'EASYA', number: 67, clue: 'Course you can float through'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'RAX', number: 68, clue: 'Name in 1990s fast food'))
clues_Intersections_CR_7_1_10.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'IDTAG', number: 69, clue: 'Luggage attachment'))
Puzzle.create(title: 'Intersections', grid: 'CROSS.BOB.REDUX|MOVIE.OMA.AROSE|OMEGA.WORDPRESS|NPR...HONE.....|..TRITE.OLE.SSE|.CHACHA.NAW.TPS|TIEDYED.EYEDROP|AGHA.......EENY|HAIRNET.PEGLEGS|ORL.TIO.ODETTE.|ESL.HEW.SALAS..|.....INOT...MLS|WINDSOCKS.USAIN|WREAK.ARE.ZORRO|EASYA.RAX.IDTAG', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/7/1', entries: clues_Intersections_CR_7_1_10)
