clues_Monumental_Characters_CR_8_26_10 = Array.new
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'URBAN', number: 1, clue: 'Euphemism in album categorization'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'URTEXT', number: 1, clue: 'Original edition'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'REAPER', number: 2, clue: 'Figure with a scythe'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BIKINI', number: 3, clue: '___ wax'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ACETATE', number: 4, clue: 'Film plastic'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NEVA', number: 5, clue: 'River through Saint Petersburg'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'RAIMI', number: 6, clue: '"Drag Me to Hell" producer Sam'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RESHAPED', number: 6, clue: 'Gave a fresh form'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ATP', number: 7, clue: 'Nadal\'s org.'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'INATIN', number: 8, clue: 'How smokeless tobacco may be packaged'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MACH', number: 9, clue: 'Speed-of-sound ratio'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ISEEA', number: 10, clue: '"___ little silhouetto of a man"'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'LSD', number: 11, clue: 'Drug on blotter paper'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LIMAPERV', number: 11, clue: 'Person with a weird butter bean fetish?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SLAV', number: 12, clue: 'Balkan native'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DEEE', number: 13, clue: '___-Lite ("Groove Is in the Heart" band)'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'REICE', number: 14, clue: 'Attend to again, as a sprain'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'ETNAS', number: 15, clue: 'Bunsen burner cousins'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ILE', number: 16, clue: 'Land in la mer'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TAKEVPSPACE', number: 17, clue: 'Park in Biden\'s spot?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'PPM', number: 18, clue: 'EPA meas.'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'MAE', number: 19, clue: 'Brooklyn-born West known for innuendo'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EPITAPH', number: 20, clue: 'Mel Blanc\'s says "That\'s all, folks!"'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'THEWAVE', number: 21, clue: 'Fun way of moving through a crowd?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'WRIT', number: 22, clue: 'Judge\'s order'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'XENA', number: 23, clue: 'Old Lucy Lawless TV role'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'MAGI', number: 24, clue: 'Nativity trio'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'GILBERT', number: 25, clue: '"Eat, Pray, Love" author'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ARP', number: 26, clue: 'Dada co-founder Jean'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TRITE', number: 27, clue: 'Played out'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ELBA', number: 28, clue: 'Noted island of exile'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'PINA', number: 29, clue: '"If you like ___ coladas ..." (Rupert Holmes lyric)'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ASWE', number: 30, clue: 'Life ___ know it'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'IEAT', number: 31, clue: '"___ Your Skin" (1964 cult horror film)'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'AAH', number: 32, clue: 'Note of satisfaction'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'TPS', number: 33, clue: 'Pranks a yard, as on Halloween'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ELIEL', number: 34, clue: 'Eero Saarinen\'s father'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'IVIE', number: 35, clue: 'Jazz singer Anderson'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'SATRAP', number: 36, clue: 'Petty tyrant'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'ALES', number: 37, clue: 'Some draft choices'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'HAM', number: 38, clue: 'Certain terrible actor'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'HMM', number: 38, clue: '"Good question ..."'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'AAA', number: 39, clue: 'Org. that manages blowouts?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'MILKDVDS', number: 40, clue: 'Copies of a Sean Penn flick?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'BVDBOWL', number: 41, clue: 'Vessel for underwear?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'OPERABLE', number: 42, clue: 'Like tumors, hopefully'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'VHS', number: 43, clue: 'Beta competitor'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MAITAI', number: 44, clue: 'Polynesian-themed rum beverage'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'TIFF', number: 45, clue: 'JPEG alternative'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EPEES', number: 46, clue: 'Fencing needs'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'SCALDED', number: 47, clue: 'Damaged by whatever was in the pot?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MALI', number: 48, clue: 'Site of the Sundiata epic'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'EYRE', number: 49, clue: 'Bront&#235; heroine'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'YAMAHA', number: 50, clue: 'Japanese motor company'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'SCOWL', number: 51, clue: 'Intimidating expression'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'OMEGAS', number: 52, clue: 'Some Swiss watches'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'WISETO', number: 53, clue: 'Not fooled by'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'LESSON', number: 54, clue: 'A sub may or may not have one planned'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'KFC', number: 55, clue: '"___ No Longer Permitted To Use Word \'Eat\' In Advertisements": Onion headline'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'COBRA', number: 56, clue: 'Both predator and prey of a mongoose'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'ATRA', number: 57, clue: 'Gillette razor brand'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'AIR', number: 58, clue: 'Atmosphere'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'AMIE', number: 59, clue: 'Gallic girlfriend'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'BADFORM', number: 60, clue: 'What party fouls are'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'BDAY', number: 60, clue: 'Occasion for sending an ecard, maybe'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AMID', number: 61, clue: 'In the center of'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'READ', number: 62, clue: 'Take advantage of study hall, perhaps'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'AIMLESS', number: 63, clue: 'Drifting'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'MINE', number: 64, clue: 'Notoriously dangerous place to work'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DMV', number: 65, clue: 'Where drivers line up: Abbr.'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'BEAVBRIDGES', number: 66, clue: 'Segues in a \'50s-\'60s sitcom?'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'VAG', number: 67, clue: 'Modern anatomical slang'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AID', number: 68, clue: 'Lend a hand to'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'RAHAL', number: 69, clue: '1986 Indy 500 winner Bobby'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'NEATO', number: 70, clue: 'Sarcastic expression of enthusiasm'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'YDS', number: 71, clue: 'RB Chris Johnson ran for 2,006 in 2009'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ADAGE', number: 72, clue: 'Saying'))
clues_Monumental_Characters_CR_8_26_10.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'EDSON', number: 73, clue: 'Pele\'s real first name'))
Puzzle.create(title: 'Monumental Characters', grid: 'URBAN.RAIMI.LSD|REICE.ETNAS.ILE|TAKEVPSPACE.MAE|EPITAPH.THEWAVE|XENA.MAGI.ARP..|TRITE.PINA.IEAT|...ELIEL.SATRAP|HAM.BVDBOWL.VHS|MAITAI.EPEES...|MALI.EYRE.SCOWL|..KFC.ATRA.AMIE|BADFORM.AIMLESS|DMV.BEAVBRIDGES|AID.RAHAL.NEATO|YDS.ADAGE.EDSON', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/8/26', entries: clues_Monumental_Characters_CR_8_26_10)
