clues_Moving_Around_CR_11_4_10 = Array.new
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'QBS', number: 1, clue: 'Brady and Brees, e.g.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'QTIP', number: 1, clue: 'Certain swab'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'BUFF', number: 2, clue: 'Muscular'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SEAU', number: 3, clue: 'Linebacker Junior who debuted in 1990 and still hasn\'t retired'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'MERV', number: 4, clue: '"___ Griffin\'s Crosswords"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'MASKED', number: 4, clue: 'Like some ball attendees'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'EMT', number: 5, clue: 'Ammonia inhalant carrier'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ROOF', number: 6, clue: 'An emcee may ask a crowd to raise it'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'VINTAGE', number: 7, clue: 'Expensive for being used, perhaps'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'ADRIFT', number: 8, clue: 'Without a compass, say'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ANN', number: 8, clue: 'Pundit Coulter'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DOGPOUND', number: 9, clue: 'Facility with cages and howling'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ROSANNE', number: 10, clue: 'Johnny Cash\'s daughter'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ISTS', number: 11, clue: 'Suffix for believers'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'FEET', number: 12, clue: 'Poetry units'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TSPS', number: 13, clue: 'Food Network measures: Abbr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TUE', number: 14, clue: 'Shrovetide day: Abbr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'AMOI', number: 15, clue: 'Mine: Fr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'NOOSES', number: 16, clue: 'Halloween yard props'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'IFA', number: 17, clue: '"___ tree falls in the forest ..."'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'STONINGSTEP', number: 18, clue: 'Removing stems and seeds?'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'ICKS', number: 19, clue: 'Reactions to spiders'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'PFUNK', number: 20, clue: 'Clinton group in the 1970s'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'NORI', number: 21, clue: 'Sheets used in sushi'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'FTC', number: 22, clue: 'Subj. of "The Nader Report"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'PASTS', number: 23, clue: 'They may be sordid'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'OED', number: 24, clue: 'Huge reference: Abbr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'DIVESIN', number: 25, clue: 'Gets started without hesitation'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'AKRON', number: 26, clue: 'Ohio city where Clark Gable lived'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ROSSINI', number: 27, clue: '"Il barbiere di Siviglia" composer'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BOARDINGSOUND', number: 28, clue: 'Steam whistle?'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BMAJ', number: 28, clue: 'Key for the theme song to "Ghostbusters": Abbr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OAHU', number: 29, clue: 'Where Obama was born'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'AGARS', number: 30, clue: 'Lab gels'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'NIX', number: 31, clue: 'Cancel'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'DANZA', number: 32, clue: 'Tony Micelli portrayer on "Who\'s the Boss?"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MAGI', number: 33, clue: 'Gift bearers of Christmas lore'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'VIE', number: 34, clue: 'Contend'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'SNEAKS', number: 35, clue: 'Wears a fake mustache, perhaps'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'KORN', number: 36, clue: 'Nu metal band whose name is written with a backwards "R"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SHAD', number: 37, clue: 'Atlantic food fish'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AHA', number: 38, clue: '"Take On Me" band playing their final shows this December'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'SEX', number: 39, clue: 'Object of some drives'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SERENITY', number: 39, clue: '"___ now!" ("Seinfeld" exclamation)'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'USD', number: 40, clue: 'Yank\'s currency: Abbr.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'URI', number: 40, clue: 'Geller who claims to be telepathic'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'NOH', number: 41, clue: 'Japanese dramatic form'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'JURIES', number: 42, clue: 'They may be hung, legally'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'ITSATIE', number: 43, clue: '"I guess everyone wins today!"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'SRI', number: 44, clue: 'Hindu honorific'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SPRAWLS', number: 44, clue: 'Keeps going and going, as a city'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'EZRA', number: 45, clue: 'Bible book after Daniel'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ELMO', number: 45, clue: 'Red Muppet'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'STRIPPINGLAND', number: 46, clue: 'Vegas?'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'PONG', number: 47, clue: 'Extremely basic game'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'GALPAL', number: 48, clue: 'Tabloid flame'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'SENOR', number: 49, clue: 'Title in the name of some crappy margarita joints'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'IAM', number: 50, clue: 'Words of confession'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'APIAN', number: 51, clue: 'Bee-related'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'APPT', number: 51, clue: 'Thing entered in a PDA, say'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'POOH', number: 52, clue: 'Yellow bear since 1926'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ISLE', number: 53, clue: 'Capri, e.g.'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'NAS', number: 54, clue: 'Rapper with nine Grammy nominations (and no awards)'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SHOO', number: 55, clue: '"Damn it, fly!"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'LOHAN', number: 56, clue: 'Subject of many a 59-Down photo'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'HAJJ', number: 57, clue: 'Big trip to Saudi Arabia'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ASIA', number: 58, clue: 'Region with heavy monsoons'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'NSFW', number: 59, clue: 'Apt to be viewed with a finger on the ESC key, say'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'POSTINGWHIP', number: 60, clue: 'Cruel blogger\'s device for disciplining employees?'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'NEE', number: 61, clue: 'Marriage announcement word'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'ICU', number: 62, clue: 'Area for acute treatment, for short'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'ASS', number: 63, clue: 'Subject of many a 59-Down photo'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'POLITE', number: 64, clue: 'Wary of curses?'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'LOCA', number: 65, clue: '"Livin\' la Vida ___"'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'JIF', number: 66, clue: 'Brand in some peanut butter bomb cakes'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'THEEYE', number: 67, clue: 'What a flirter might give a flirtee'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'SOUL', number: 68, clue: 'White\'s genre'))
clues_Moving_Around_CR_11_4_10.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'JAW', number: 69, clue: 'The mandible is part of it'))
Puzzle.create(title: 'Moving Around', grid: 'QBS.MERV.ADRIFT|TUE.AMOI.NOOSES|IFA.STONINGSTEP|PFUNK.FTC.PASTS|...OED.AKRON...|BOARDINGSOUND..|MAGI.VIE.SNEAKS|AHA.SEX.USD.NOH|JURIES.SRI.EZRA|..STRIPPINGLAND|...SENOR.IAM...|APIAN.NAS.LOHAN|POSTINGWHIP.ASS|POLITE.LOCA.JIF|THEEYE.SOUL.JAW', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/11/4', entries: clues_Moving_Around_CR_11_4_10)
