clues_Oh_Brother_WCP_9_23_10 = Array.new
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'XMEN', number: 1, clue: 'Cyclops and Nightcrawler, e.g.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'XTRA', number: 1, clue: 'Bonus, in the ad business'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MAUL', number: 2, clue: 'Kill, and then some'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ERST', number: 3, clue: 'Prefix with "while"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'NOHOPE', number: 4, clue: 'Total despair'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'UHF', number: 5, clue: 'Old TV dial letters'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'URN', number: 5, clue: 'Brewer'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HIGHTECH', number: 6, clue: 'Like robotics'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'FORE', number: 7, clue: 'Preceding, poetically'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'STJOHN', number: 8, clue: 'Patron of a famous Episcopal Church on 16th and H'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SQUEALS', number: 8, clue: 'Wallowing sounds'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TULSA', number: 9, clue: 'Arkansas River city'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'JOEY', number: 10, clue: 'Russo with the \'90s catchphrase "Whoa!"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ORT', number: 11, clue: 'Table scrap'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'HUT', number: 12, clue: 'Simple abode'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NME', number: 13, clue: 'UK pop music mag'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TARO', number: 14, clue: 'Ingredient in some fake meat'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'RIO', number: 15, clue: '2016 Olympics city'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'QUORUM', number: 16, clue: 'Enough for a meeting'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RUSHINGROULETTE', number: 17, clue: 'Random, casino-based way of deciding whether to admit a pledge?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'INFAVOR', number: 18, clue: 'Pro'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'ORME', number: 19, clue: '"It\'s him ___" (relationship ultimatum)'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ALTON', number: 20, clue: 'TV chef Brown'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'HERESY', number: 21, clue: 'Act of messing with doctrine'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'PFFT', number: 22, clue: '"My ass!"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'FRI', number: 23, clue: 'Part of TGIF: Abbr.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'MAA', number: 24, clue: 'Goat\'s cry'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'DBS', number: 25, clue: 'Sound measuring units: Abbr.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'DREVIL', number: 25, clue: 'To whom the "Me" in "Mini-Me" refers'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'BOREAL', number: 26, clue: 'Northern'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'STERNS', number: 27, clue: 'Outboard rudder places'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'HAZEAREBEL', number: 28, clue: 'Make the wiseass pledge look foolish?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'HUBCAP', number: 28, clue: 'One might spin, on a fancy car'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AFLAME', number: 29, clue: 'Blazing'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ZOOMIN', number: 30, clue: 'Get closer before shooting?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'BEATA', number: 31, clue: '___ quick retreat'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'TROT', number: 32, clue: 'Easy gait'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'THA', number: 32, clue: 'Hip-hop album article'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'UFO', number: 33, clue: 'Night sky vision'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'VICE', number: 34, clue: 'Smoking, say'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'SPHERE', number: 35, clue: 'Suffix with 37-Across'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'PREMIUM', number: 36, clue: 'Really good'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'BLOGO', number: 37, clue: 'Prefix with 35-Across'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'GED', number: 38, clue: 'High school degree equiv.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'HAW', number: 39, clue: '"Hee ___"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'WATERJUG', number: 40, clue: 'Pitcher'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'RAVER', number: 41, clue: 'Invisible energy ball handler'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'CAMERA', number: 42, clue: 'Machine with a shutter'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'AFGHANS', number: 43, clue: 'Some blankets'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'TASE', number: 44, clue: '"Don\'t ___ me, bro!"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'SSR', number: 45, clue: 'Old atlas abbr.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'IAN', number: 46, clue: 'Curtis of Joy Division'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'AMID', number: 47, clue: 'In the center of'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'FRATSMELLS', number: 48, clue: 'B.O. and week-old Miller Chill?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'REIN', number: 49, clue: 'Horse controller'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'ESCAPE', number: 50, clue: 'Leave that asshole zookeeper behind forever, provided you can find a way into the sewer'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'PEN', number: 51, clue: 'Clink'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'AGE', number: 52, clue: 'Get on in years'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ACTOR', number: 52, clue: 'She\'s just playing'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ERIS', number: 53, clue: 'Greek goddess of discord'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'ACHIER', number: 54, clue: 'More flu-like, say'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'ASIA', number: 54, clue: 'Cambodia\'s continent'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'EDGE', number: 55, clue: 'Hipness'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'UCONN', number: 56, clue: 'Huskies\' sch.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'OILS', number: 57, clue: 'Some are essential'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NCAA', number: 58, clue: 'Hoyas\' org.'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'NANU', number: 59, clue: 'Part of an Orkan greeting'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'KEGSTANDJAMAICA', number: 60, clue: 'Red Stripe drinking game?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'KOS', number: 60, clue: 'Puts on canvas?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'EPH', number: 61, clue: 'N.T. book after Galatians'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'GTE', number: 62, clue: 'Verizon forerunner'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'ANO', number: 63, clue: 'It includes mayo and julio'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OPTION', number: 64, clue: 'Possibility'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'GUN', number: 65, clue: 'Rev'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'PLAN', number: 66, clue: '"___ 9 From Outer Space"'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SHEARS', number: 67, clue: 'Shrub cutters'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'EGO', number: 68, clue: 'Star quality?'))
clues_Oh_Brother_WCP_9_23_10.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ESAU', number: 69, clue: 'Biblical birthright seller'))
Puzzle.create(title: 'Oh Brother', grid: 'XMEN.UHF.STJOHN|TARO.RIO.QUORUM|RUSHINGROULETTE|ALTON.HERESY...|...PFFT.MAA.DBS|HAZEAREBEL.TROT|UFO.VICE.SPHERE|BLOGO.HAW.RAVER|CAMERA.TASE.IAN|AMID.FRATSMELLS|PEN.AGE.ERIS...|...ACHIER.UCONN|KEGSTANDJAMAICA|OPTION.GUN.PLAN|SHEARS.EGO.ESAU', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/9/23', entries: clues_Oh_Brother_WCP_9_23_10)
