clues_Oh_You_CR_4_22_10 = Array.new
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'IPAD', number: 1, clue: 'Noted April 2010 debut'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'IUD', number: 1, clue: 'Family planning option'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'POR', number: 2, clue: 'First-day-of-Spanish-class word'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'AMO', number: 3, clue: 'First-day-of-Latin-class word'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'DOZING', number: 4, clue: 'Out, in a way'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'DIETS', number: 5, clue: 'Tries to shed'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DANE', number: 5, clue: 'Viggo Mortensen, e.g.'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IPOS', number: 6, clue: 'Wall St. news items'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'END', number: 7, clue: 'Finish up'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TEEOFF', number: 8, clue: 'Get started'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SAPPHO', number: 9, clue: 'Poet with a special passion for women'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ALAI', number: 10, clue: 'Jai ___'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'AMOS', number: 10, clue: 'Pianist Tori'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LOTSA', number: 11, clue: 'Mucho'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ALOUD', number: 12, clue: 'How things may be read'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ITSME', number: 13, clue: 'Words after knocking at a friend\'s door'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'UOMO', number: 14, clue: 'Italian fellow'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'APNEA', number: 15, clue: 'Certain sleep problem'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'MOLT', number: 16, clue: 'Shed'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DROZ', number: 17, clue: 'Frequent guest on Oprah'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'NODEPHOTOS', number: 18, clue: 'Lymphatic x-rays?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'HOMO', number: 19, clue: 'Pride parade word'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'IDES', number: 20, clue: 'Time to beware'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'DAREI', number: 21, clue: '"Is it too risky?"'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'OPOSSUM', number: 22, clue: 'American marsupial'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'VANNA', number: 23, clue: 'Woman of letters?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'VFW', number: 23, clue: 'Hall with lots of wood paneling, often'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ALIBI', number: 24, clue: 'Crime story?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'NAMED', number: 25, clue: 'Christened'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'FHM', number: 26, clue: 'Gent\'s magazine'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'ADE', number: 27, clue: 'Suffix with lemon or lime'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'FLAGRANTFOOL', number: 28, clue: 'One who makes outlandish mistakes?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'ARN', number: 29, clue: 'Noted sports agent Tellem'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'NIN', number: 30, clue: '"Delta of Venus" author Ana&#239;s'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TEENS', number: 31, clue: '"New Moon" readers, often'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'LAO', number: 32, clue: 'Isan Thai language'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'WIM', number: 33, clue: 'German director Wenders'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'ERIE', number: 34, clue: 'Lake southwest of Lake Ontario'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'AAS', number: 35, clue: 'Sources of remote power, e.g.'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'ACHOO', number: 36, clue: 'Sound that might elicit a "bless you"'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'SKULK', number: 37, clue: 'Move like a ninja'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'BEGINNERSLOCK', number: 38, clue: 'Picking student\'s first assignment?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'GOD', number: 39, clue: 'Shiva, e.g.'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'RAD', number: 40, clue: 'Skateboard movie exclamation'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'SPA', number: 41, clue: 'Bachelorette party locale'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'LAYLA', number: 42, clue: 'Derek and the Dominos classic'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'IDO', number: 43, clue: 'Phrase that must be said twice to really count'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'NAPA', number: 44, clue: 'Arbor-filled California region'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'HUS', number: 45, clue: 'Czech religious reformer Jan'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'STY', number: 46, clue: 'Oinking area'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'DOOMSDAYCOLT', number: 47, clue: 'Young horse wielding an atomic death ray?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'OOZE', number: 48, clue: 'Primordial material'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'OSPREY', number: 49, clue: 'Dangerous "Odell Lake" bird'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'MIASMA', number: 50, clue: 'Unhealthy atmosphere'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'COZYUP', number: 51, clue: 'Put on a Snuggie, e.g.'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ACS', number: 52, clue: 'Summer coolers, for short'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'ACMES', number: 52, clue: 'Peaks'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'CHICK', number: 53, clue: 'New farm presence'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'SUSHI', number: 54, clue: 'By-the-piece cuisine'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'OSI', number: 55, clue: 'George Soros\'s org.'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'LOOKY', number: 56, clue: '"Check it out!"'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CHUTZPA', number: 57, clue: 'Balls'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'TTOP', number: 58, clue: 'Sports car roof choice'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'SPAZ', number: 59, clue: 'Certain freak'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SLID', number: 59, clue: 'Got home safe, perhaps'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'POLS', number: 60, clue: 'Voted-in ones'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MISTERSOLO', number: 61, clue: 'Musician who likes to show off?'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'OAR', number: 62, clue: 'Homonym of a Bruins Hall of Famer'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'YOLK', number: 63, clue: 'Pudding thickener'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'ORR', number: 64, clue: 'Homonym of a crew tool'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'LGE', number: 65, clue: 'T-shirt spec'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'KEY', number: 66, clue: 'Vital'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ECHO', number: 67, clue: 'Studio effect'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EMAIL', number: 68, clue: 'Shoot a message to'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'URGE', number: 69, clue: 'Strong desire'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SKIP', number: 70, clue: 'Go past'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'YARDS', number: 71, clue: 'Fullback\'s pickup'))
clues_Oh_You_CR_4_22_10.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'PREY', number: 72, clue: 'Cobras and mongooses, vis-&#224;-vis each other'))
Puzzle.create(title: 'Oh, You!', grid: 'IPAD.DIETS.ALAI|UOMO.APNEA.MOLT|DROZ.NODEPHOTOS|...IDES.OPOSSUM|VANNA...FHM.ADE|FLAGRANTFOOL...|WIM.ERIE...AAS.|.BEGINNERSLOCK.|.IDO...NAPA.HUS|...DOOMSDAYCOLT|ACS.OSI...LOOKY|CHUTZPA.SPAZ...|MISTERSOLO.YOLK|ECHO.EMAIL.URGE|SKIP.YARDS.PREY', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/4/22', entries: clues_Oh_You_CR_4_22_10)
