clues_Stuck_on_the_Ending_CR_10_14_10 = Array.new
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ATM', number: 1, clue: 'Place to check your balance'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ABORC', number: 1, clue: 'Simple multiple choice options'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TORAH', number: 2, clue: 'Source of some scriptures'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MAYBE', number: 3, clue: '"Dunno yet"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'EBAY', number: 4, clue: 'Gubernatorial candidate Meg Whitman\'s former company'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ELGIZA', number: 4, clue: 'Sphinx city'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'BEA', number: 5, clue: 'Co-star of Rue and Betty'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANN', number: 6, clue: 'Massachusetts cape'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'YOGA', number: 7, clue: 'Ancient exercise that\'s popular now'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'RERANG', number: 8, clue: 'Was persistent, as a door-to-door salesman'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RSTLNE', number: 8, clue: 'Letters given in the bonus round of "Wheel of Fortune"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ETA', number: 9, clue: 'It may be given while cruising: Abbr.'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'RUTABAGAGAGA', number: 10, clue: '"Bad Romance" singer\'s recipe for a root vegetable?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'APAIL', number: 11, clue: '"... to fetch ___ of water"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'NOTME', number: 12, clue: 'Cry of denial'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'GRASS', number: 13, clue: 'Dope'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BOA', number: 14, clue: 'Burlesque prop'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'LENO', number: 15, clue: 'He came back to "The Tonight Show" in March'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'STUPOR', number: 16, clue: 'A drunk may lie in one'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ORY', number: 17, clue: 'Kid ___ (noted jazz trombonist)'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'GANGSTATATA', number: 18, clue: 'Effete goodbye from a true thug?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'STENONONO', number: 19, clue: 'Wasting time by writing in longhand?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'RABBI', number: 20, clue: 'One may stand next to the cantor'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'BETHESDADADA', number: 21, clue: 'Super-weird art coming out of suburban Maryland?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'ATL', number: 22, clue: '2010 MLB playoff team'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'AIMS', number: 23, clue: 'Uses crosshairs'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'CHEEZIT', number: 24, clue: 'Kellogg\'s cracker brand'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ICED', number: 25, clue: '___ out (having lots of diamonds)'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'TOKYOYOYO', number: 26, clue: 'Toy from the biggest city in the world?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'ENABLES', number: 27, clue: 'Makes possible, as someone else\'s addiction'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'AVE', number: 28, clue: 'What the "Mad" in "Mad Men" is'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'TACO', number: 29, clue: 'One might be filled with carnitas'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'NEVA', number: 30, clue: 'Siege of Leningrad river'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MWAH', number: 31, clue: '"Love ya!"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'MSN', number: 31, clue: 'Portal with a butterfly logo'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'WOO', number: 32, clue: 'Pursue romantically'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ARM', number: 33, clue: 'Rick Allen of Def Leppard has only one'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'EKCO', number: 34, clue: 'Big name in kitchen gadgets'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'CID', number: 35, clue: 'Spanish hero El ___'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'EGGON', number: 36, clue: 'Goad'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'GUM', number: 37, clue: 'Trident, e.g.'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ORE', number: 38, clue: 'Miner\'s matter'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'NAN', number: 39, clue: 'Art photographer Goldin'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SORE', number: 40, clue: 'Still mad'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'DYING', number: 41, clue: 'Really anxious (to know)'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'GRIM', number: 42, clue: 'Dark, as prospects'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'AURA', number: 43, clue: 'Subject for Walter Benjamin'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'NOMSG', number: 44, clue: 'Menu claim'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'GOD', number: 45, clue: 'Being in the clouds'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ODOR', number: 46, clue: 'What may emerge when the can is open?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'GMEN', number: 47, clue: 'FBI agents'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'DOBY', number: 48, clue: 'Larry who broke the American League color barrier'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'BIASES', number: 49, clue: 'Political slants'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'NINA', number: 50, clue: 'Deep-voiced Simone'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'NIKONS', number: 51, clue: 'Some Japanese cameras'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CBRADIO', number: 52, clue: 'Communication device on "The Dukes of Hazzard"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'CAPRA', number: 52, clue: '"It\'s a Wonderful Life" director'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'BRION', number: 53, clue: 'Experimental artist Gysin'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'RICAN', number: 54, clue: 'Puerto ___ (like Rosario Dawson and Ricky Martin)'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'OMIGOSH', number: 55, clue: '"I just realized something important"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'OZONE', number: 56, clue: 'Atmospheric layer'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'SOAPY', number: 57, clue: 'Lathered up'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'HORSE', number: 58, clue: 'Certain steed'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ARID', number: 59, clue: 'Suitable for cacti, environmentally'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'AYE', number: 60, clue: '"Yes, sir, captain, sir!"'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ESAU', number: 61, clue: 'Literary birthright seller'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'KAZOO', number: 62, clue: 'Buzzy instrument'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PICASSOSOSO', number: 63, clue: 'Middling review of a great painter?'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'SIL', number: 64, clue: 'Part of RSVP'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ORG', number: 65, clue: 'Certain domain name ending'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'SOG', number: 66, clue: 'Soak, in British dialect'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'OAR', number: 67, clue: 'Regatta implement'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ROADIE', number: 68, clue: 'Tour crew member, often'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ARON', number: 69, clue: 'Elvis\'s middle name, on his birth certificate'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'NPS', number: 70, clue: 'Certain ICU figures'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ANNALS', number: 71, clue: 'Historical records'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'UGGS', number: 72, clue: 'Some sheepskin boots'))
clues_Stuck_on_the_Ending_CR_10_14_10.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'EYE', number: 73, clue: 'One may be private or lazy'))
Puzzle.create(title: 'Stuck on the Ending', grid: 'ATM.EBAY.RERANG|BOA.LENO.STUPOR|ORY.GANGSTATATA|RABBI..ATL.AIMS|CHEEZIT.ENABLES|...TACO.NEVA...|MWAH.EKCO.EGGON|SORE.DYING.AURA|NOMSG.ODOR.GMEN|...DOBY.NINA...|CBRADIO.OMIGOSH|ARID.AYE..KAZOO|PICASSOSOSO.OAR|ROADIE.ARON.NPS|ANNALS.UGGS.EYE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/10/14', entries: clues_Stuck_on_the_Ending_CR_10_14_10)
