clues_Trying_New_Things_Part_One_CR_7_29_10 = Array.new
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SAM', number: 1, clue: '*Noted Seuss protagonist with an upcoming birthday, and a hint to a two-part puzzle that begins this week (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SISI', number: 1, clue: '"Of course, se&#241;or!"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALOT', number: 2, clue: 'Reams'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'METS', number: 3, clue: 'Citi Field ballplayers'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'HUFF', number: 4, clue: 'Snit'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'HWY', number: 4, clue: 'Rte. with orange cones, often'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'UIS', number: 5, clue: 'Most are graphical nowadays: Abbr.'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'FLAW', number: 6, clue: 'Blemish'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'FLYING', number: 7, clue: 'Above it all, in a way'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'PANIC', number: 8, clue: 'Freak out'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'PUSHCART', number: 8, clue: 'Lemonade stand vehicle'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'APPT', number: 9, clue: 'Entry in a PDA'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'NOAHS', number: 10, clue: 'Wyle and Webster'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'INMAY', number: 11, clue: '*When Memorial Day is observed (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CASTS', number: 12, clue: 'Broken bone treatments'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ILER', number: 13, clue: 'Robert of "The Sopranos"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'RHO', number: 14, clue: 'Letter before sigma'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'WILL', number: 15, clue: '*Last ___ and testament (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'UPONA', number: 16, clue: '"Once ___ time..."'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SOTHEYSAY', number: 17, clue: '*"That\'s the rumor, anyway" (3)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'EKED', number: 18, clue: 'Squeezed (out)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'SPAMS', number: 19, clue: 'Sends junk mail, of a sort'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ITSOK', number: 20, clue: '"No worries"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'WITHTHAT', number: 21, clue: '*Emcee\'s concluding segue (2)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'TEO', number: 22, clue: 'Formula One driver Fabi'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'EAT', number: 23, clue: '*Have eucalyptus leaves, if you\'re a koala (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ABLE', number: 24, clue: 'Fit to serve'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'TEAR', number: 25, clue: 'Facial tattoo that represents a dead friend'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'NEC', number: 26, clue: 'Japanese rival of IBM'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'SYS', number: 27, clue: 'Method: Abbr.'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'COULDBE', number: 28, clue: '*"Perhaps" (2)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'COAT', number: 28, clue: 'Paint layer'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ORNO', number: 29, clue: '*Certain question ender (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'UEYS', number: 30, clue: 'Total turnarounds, for short'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'LOWER', number: 31, clue: 'Instruction to someone hanging a painting'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'GOAT', number: 32, clue: '*Hero\'s opposite (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'TOHIM', number: 33, clue: '"Anna (Go ___)": Beatles cover'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OREO', number: 34, clue: 'Cookies \'n\' cream cookie'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'LAY', number: 35, clue: 'Casual sexual partner, as it were'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'YES', number: 36, clue: 'Cry of accomplishment'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ROMAS', number: 37, clue: 'Some tomatoes'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'MENE', number: 38, clue: 'Biblical graffiti word'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ARCO', number: 39, clue: 'Sacramento arena brand'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SEAN', number: 40, clue: 'Knighted Connery'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ANYWHEREINTHERE', number: 41, clue: '*Nonspecific direction to a mover (3)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'HAIRNETS', number: 42, clue: 'Classic lunch lady pieces'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'ILLS', number: 43, clue: 'Social problems'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'NYET', number: 44, clue: 'Da opposite'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TOSEA', number: 45, clue: 'Where many boats head'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'SLY', number: 46, clue: 'Sneaky'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'INCA', number: 47, clue: 'Cuzco people'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'RIPA', number: 48, clue: 'Lee Gifford\'s replacement'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'PEC', number: 49, clue: 'Chest muscle, for short'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'AVATAR', number: 50, clue: 'Film featuring the Na\'vi'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'LETMEON', number: 51, clue: '*Demand from one who wants to board the merry-go-round (3)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'TYPO', number: 52, clue: 'Teh, e.g.'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'APP', number: 53, clue: 'Tip calculator, for example'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'ATMOS', number: 53, clue: 'Clock that\'s sort of like a perpetual motion machine'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'PROWL', number: 54, clue: 'Look for prey'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'PAULO', number: 55, clue: 'S&#227;o ___, Brazil'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'REV', number: 56, clue: 'Gun, as your engine'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'STY', number: 57, clue: 'Wallowing area'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TRAINCAR', number: 58, clue: '*Caboose, e.g. (2)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'ISEE', number: 59, clue: '"Gotcha"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'RHEA', number: 60, clue: 'Perlman of "Cheers"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'PORNO', number: 61, clue: 'Video store section behind saloon doors, sometimes'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'OXY', number: 62, clue: 'Big name in skin care'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'RBIS', number: 63, clue: 'MLBers get four for a grand slam'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NOPE', number: 64, clue: '"Nuh-uh"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'OXEN', number: 65, clue: 'Team that works out in the field'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MOUSE', number: 66, clue: '*Computer controller (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'THEFOXBOX', number: 67, clue: '*Sports broadcast graphic named for its network (3)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ERI', number: 68, clue: 'Verdi\'s "___ tu"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'FIN', number: 69, clue: 'Shark\'s navigator'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OWLET', number: 70, clue: 'Small hooter'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'AERI', number: 71, clue: 'Ethereal: Prefix'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'YIPE', number: 72, clue: '"Oy vey!"'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SLOES', number: 73, clue: 'Gin fizz fruits'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'RAIN', number: 74, clue: '*It may drop acid (1)'))
clues_Trying_New_Things_Part_One_CR_7_29_10.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SEN', number: 75, clue: 'Hill worker: Abbr.'))
Puzzle.create(title: 'Trying New Things: Part One', grid: 'SAM..HUFF.PANIC|ILER.WILL.UPONA|SOTHEYSAY.SPAMS|ITSOK..WITHTHAT|....EAT.NEC.SYS|COULDBE.GOAT...|OREO.LAY..ROMAS|ANYWHEREINTHERE|TOSEA..SLY.INCA|...RIPA.LETMEON|APP.REV.STY....|TRAINCAR..PORNO|MOUSE.THEFOXBOX|OWLET.AERI.YIPE|SLOES.RAIN..SEN', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/7/29', entries: clues_Trying_New_Things_Part_One_CR_7_29_10)
