clues_Verbal_Contracts_CR_1_21_10 = Array.new
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TREMOR', number: 1, clue: 'Aftershock'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'THEAS', number: 1, clue: 'Billy Beane\'s team'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'READEM', number: 2, clue: '"___ and weep!"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ETRADE', number: 3, clue: 'Online investment site'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MEL', number: 4, clue: 'B or C of the Spice Girls'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ORY', number: 5, clue: 'Jazz legend nicknamed "Kid"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ROTC', number: 6, clue: 'Gp. that marches on campus'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'GDR', number: 7, clue: 'East Berlin was its cap.'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GEISHAS', number: 7, clue: 'Painted Japanese ladies'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DIETED', number: 8, clue: 'Practiced portion control, perhaps'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ROSARY', number: 9, clue: 'Prayer beads'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ARMS', number: 10, clue: 'Vishnu\'s four'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ASAP', number: 10, clue: 'Stat'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'RENEGEON', number: 11, clue: 'Weasel out of'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MANLIEST', number: 12, clue: 'Most butch, say'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'STILETTO', number: 13, clue: 'Sharp heel shape'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HETERO', number: 14, clue: 'Straight'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'EIO', number: 15, clue: '"Old MacDonald\'\' ender'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'SEAT', number: 16, clue: 'Parliament spot'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'EARLYTRIES', number: 17, clue: 'First attempts?'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'RATEDR', number: 18, clue: '2009 Rihanna album with "Russian Roulette"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ANNI', number: 19, clue: 'Albers of the Bauhaus school'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ADA', number: 20, clue: '1990 bill that increased wheelchair access: Abbr.'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'CASTASPELL', number: 21, clue: 'Charm people, so to speak'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'SAT', number: 22, clue: 'Common test prep focus'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SEDGE', number: 23, clue: 'Wetlands plant'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'GAMETE', number: 24, clue: 'Reproductive cell'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ELON', number: 25, clue: 'Tobacco Road college'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'THERA', number: 26, clue: 'Commercial prefix with "flu"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'GIE', number: 27, clue: '"O wad some power the giftie ___ us / To see oursels as ithers see us!": Burns'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'MEALREADYTWEET', number: 28, clue: '"#dinner RT @chef: time 4 food"?'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'ROE', number: 29, clue: 'Jane ___ (Norma McCorvey pseudonym in a landmark 1973 case)'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'WHOMSO', number: 30, clue: 'Anyone, formally'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'MOODS', number: 31, clue: 'They may be indicated by rings'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'HOST', number: 32, clue: 'Throw, as a party'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RIPENER', number: 33, clue: 'Something that hastens maturity'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'ROADRAGE', number: 33, clue: 'Blowing a fuse in one\'s car?'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'IMPROVED', number: 34, clue: 'Honed'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'PIPELINE', number: 35, clue: 'Controversial ANWR presence'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'LOGONTO', number: 36, clue: 'Access, digitally'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'LORDLY', number: 36, clue: 'Regal'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ODE', number: 37, clue: 'Words of praise'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'GOAL', number: 38, clue: 'Soccer announcer\'s shout'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OMIT', number: 39, clue: 'Flake on including'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'SODOM', number: 40, clue: 'Biblical city with "strange flesh"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'STREAKY', number: 40, clue: 'Hot-and-cold'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'APPEALSTREASON', number: 41, clue: 'Attempts to get a higher court to overturn one\'s espionage conviction?'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ABM', number: 42, clue: 'SDI weapon'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'LOOPED', number: 43, clue: 'Repeated, as a drum beat'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'SADLER', number: 44, clue: '"Ballad of the Green Berets" writer Barry'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'OUTWIT', number: 45, clue: 'Deceive'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'NIKITA', number: 46, clue: 'Soviet premier Khrushchev'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'DRE', number: 47, clue: 'Ed Lover\'s partner on "Yo! MTV Raps"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'BOARD', number: 48, clue: 'Skater\'s need'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'LOUIS', number: 49, clue: 'Armstrong or Pasteur'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SONIC', number: 50, clue: 'Mildly 1950s-themed fast food chain'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ROLEMODELS', number: 51, clue: '2008 Seann William Scott/Paul Rudd comedy'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'EVEN', number: 52, clue: 'Tied'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'SETS', number: 53, clue: 'Mends, as a broken bone'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TKO', number: 54, clue: 'Decision for Manny Pacquiao'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AVIV', number: 55, clue: 'Tel ___'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'PLAYEDTWIN', number: 56, clue: 'Shared a role, like Mary-Kate and Ashley?'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'DAE', number: 57, clue: 'Daniel ___ Kim of "Lost"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'THA', number: 58, clue: 'Lil Wayne\'s "___ Carter III"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GENE', number: 59, clue: 'Trait determinant'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EEK', number: 60, clue: '"A bug!!"'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'TAHITI', number: 61, clue: 'Island to which Gauguin went after leaving Europe'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'EDEN', number: 62, clue: 'Noted garden'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DRY', number: 63, clue: 'Like some humor'))
clues_Verbal_Contracts_CR_1_21_10.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'SEATAC', number: 64, clue: 'Airport near Puget Sound'))
Puzzle.create(title: 'Verbal Contracts', grid: 'TREMOR.GDR.ARMS|HETERO.EIO.SEAT|EARLYTRIES.ANNI|ADA..CASTASPELL|SEDGE.THERA.GIE|.MEALREADYTWEET|...MOODS...HOST|RIPENER.LOGONTO|OMIT...SODOM...|APPEALSTREASON.|DRE.BOARD.LOUIS|ROLEMODELS..TKO|AVIV.PLAYEDTWIN|GENE.EEK.TAHITI|EDEN.DRY.SEATAC', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2010/1/21', entries: clues_Verbal_Contracts_CR_1_21_10)
