puts "Processing Adios_Articles_CR_11_1_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Adios_Articles_CR_11_1_12_seeds.rb"
puts "Processing Adult_Entertainment_CR_9_13_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Adult_Entertainment_CR_9_13_12_seeds.rb"
puts "Processing Afterthoughts_CR_1_26_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Afterthoughts_CR_1_26_12_seeds.rb"
puts "Processing A_New_Man_CR_5_17_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/A_New_Man_CR_5_17_12_seeds.rb"
puts "Processing A_Separate_Piece_CR_1_5_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/A_Separate_Piece_CR_1_5_12_seeds.rb"
puts "Processing A_View_Changes_CR_9_20_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/A_View_Changes_CR_9_20_12_seeds.rb"
puts "Processing Back_Two_Back_CR_2_16_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Back_Two_Back_CR_2_16_12_seeds.rb"
puts "Processing Before_and_After_CR_3_22_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Before_and_After_CR_3_22_12_seeds.rb"
puts "Processing Brushes_with_Flame_CR_8_30_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Brushes_with_Flame_CR_8_30_12_seeds.rb"
puts "Processing Campaign_Records_CR_1_19_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Campaign_Records_CR_1_19_12_seeds.rb"
puts "Processing Clean_Cuts_CR_12_27_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Clean_Cuts_CR_12_27_12_seeds.rb"
puts "Processing Corporate_Diversity_CR_4_12_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Corporate_Diversity_CR_4_12_12_seeds.rb"
puts "Processing Criminal_Acts_ALCR_9_6_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Criminal_Acts_ALCR_9_6_12_seeds.rb"
puts "Processing Crooked_Numbers_CR_10_11_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Crooked_Numbers_CR_10_11_12_seeds.rb"
puts "Processing Different_Wavelengths_CR_10_4_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Different_Wavelengths_CR_10_4_12_seeds.rb"
puts "Processing Eastern_Bowl_Game_CR_12_13_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Eastern_Bowl_Game_CR_12_13_12_seeds.rb"
puts "Processing Ecological_Change_CR_6_21_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Ecological_Change_CR_6_21_12_seeds.rb"
puts "Processing Etailers_CR_3_8_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Etailers_CR_3_8_12_seeds.rb"
puts "Processing Fare_Increase_CR_10_25_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Fare_Increase_CR_10_25_12_seeds.rb"
puts "Processing Full_of_it_CR_6_28_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Full_of_it_CR_6_28_12_seeds.rb"
puts "Processing Fusions_CR_10_18_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Fusions_CR_10_18_12_seeds.rb"
puts "Processing Getting_an_Et_in_French_CR_2_23_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Getting_an_Et_in_French_CR_2_23_12_seeds.rb"
puts "Processing Heads_of_Planning_CR_6_7_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Heads_of_Planning_CR_6_7_12_seeds.rb"
puts "Processing High_Season_CR_4_20_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/High_Season_CR_4_20_12_seeds.rb"
puts "Processing Hint_Hint_Bonus_puzzle_by_Francis_Heaney_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Hint_Hint_Bonus_puzzle_by_Francis_Heaney_seeds.rb"
puts "Processing iMovie_CR_11_29_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/iMovie_CR_11_29_12_seeds.rb"
puts "Processing Infiltration_CR_8_22_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Infiltration_CR_8_22_12_seeds.rb"
puts "Processing It_All_Revolves_Around_You_CR_3_29_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/It_All_Revolves_Around_You_CR_3_29_12_seeds.rb"
puts "Processing Labor_Movement_CR_5_31_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Labor_Movement_CR_5_31_12_seeds.rb"
puts "Processing Man_in_the_Middle_CR_8_2_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Man_in_the_Middle_CR_8_2_12_seeds.rb"
puts "Processing Middle_Rank_CR_9_27_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Middle_Rank_CR_9_27_12_seeds.rb"
puts "Processing Modified_Foods_CR_8_15_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Modified_Foods_CR_8_15_12_seeds.rb"
puts "Processing Musical_Soundalikes_CR_3_15_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Musical_Soundalikes_CR_3_15_12_seeds.rb"
puts "Processing Ornery_CR_2_9_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Ornery_CR_2_9_12_seeds.rb"
puts "Processing Personal_Styles_CR_11_22_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Personal_Styles_CR_11_22_12_seeds.rb"
puts "Processing Political_Insiders_CR_6_14_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Political_Insiders_CR_6_14_12_seeds.rb"
puts "Processing Prime_Time_Panhandlers_CR_2_2_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Prime_Time_Panhandlers_CR_2_2_12_seeds.rb"
puts "Processing Shaking_Things_Up_CR_12_5_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Shaking_Things_Up_CR_12_5_12_seeds.rb"
puts "Processing Shower_Scene_CR_5_24_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Shower_Scene_CR_5_24_12_seeds.rb"
puts "Processing Signs_of_Stress_CR_7_26_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Signs_of_Stress_CR_7_26_12_seeds.rb"
puts "Processing Spring_Time_CR_2_29_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Spring_Time_CR_2_29_12_seeds.rb"
puts "Processing Staff_Additions_CR_4_26_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Staff_Additions_CR_4_26_12_seeds.rb"
puts "Processing Staying_Loose_CR_11_15_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Staying_Loose_CR_11_15_12_seeds.rb"
puts "Processing Substitute_Parts_CR_4_5_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Substitute_Parts_CR_4_5_12_seeds.rb"
puts "Processing Switching_Positions_CR_5_3_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Switching_Positions_CR_5_3_12_seeds.rb"
puts "Processing The_Jocks_and_the_Squares_CR_8_9_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/The_Jocks_and_the_Squares_CR_8_9_12_seeds.rb"
puts "Processing Two_States_CR_5_10_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Two_States_CR_5_10_12_seeds.rb"
puts "Processing Vision_Quest_CR_7_5_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Vision_Quest_CR_7_5_12_seeds.rb"
puts "Processing Whats_My_Line_CR_7_12_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Whats_My_Line_CR_7_12_12_seeds.rb"
puts "Processing Why_Just_One_Second_CR_12_20_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Why_Just_One_Second_CR_12_20_12_seeds.rb"
puts "Processing Wife_Swap_CR_1_12_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Wife_Swap_CR_1_12_12_seeds.rb"
puts "Processing Yo_Yo_Diet_CR_7_19_12_seeds.rb...\n"
require "/home/peter/xword_db/db/inkwell_seedfiles/2012/Yo_Yo_Diet_CR_7_19_12_seeds.rb"
