puts "Processing 4g_coverage_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/4g_coverage_seeds.rb"
=begin
puts "Processing A_load_of_Bs_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/A_load_of_Bs_seeds.rb"
puts "Processing bobtails_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/bobtails_seeds.rb"
puts "Processing campus_crosswords_feb2_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/campus_crosswords_feb2_seeds.rb"
puts "Processing campus_crosswords_jan25_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/campus_crosswords_jan25_seeds.rb"
puts "Processing consider_yourself_blessed_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/consider_yourself_blessed_seeds.rb"
puts "Processing diagramless_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/diagramless_seeds.rb"
puts "Processing dim_the_headlights_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/dim_the_headlights_seeds.rb"
puts "Processing famous_last_words_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/famous_last_words_seeds.rb"
puts "Processing freestyle19_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/freestyle19_seeds.rb"
puts "Processing freestyle20_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/freestyle20_seeds.rb"
puts "Processing freestyle21_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/freestyle21_seeds.rb"
puts "Processing freestyle_22_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/freestyle_22_seeds.rb"
puts "Processing freestyle23_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/freestyle23_seeds.rb"
puts "Processing green_day_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/green_day_seeds.rb"
puts "Processing greeting_card_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/greeting_card_seeds.rb"
puts "Processing greetings_and_salutations_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/greetings_and_salutations_seeds.rb"
puts "Processing guerrilla_easy_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/guerrilla_easy_seeds.rb"
puts "Processing guerrilla_hard_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/guerrilla_hard_seeds.rb"
puts "Processing guerrilla_medium_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/guerrilla_medium_seeds.rb"
puts "Processing guest_puzzle_steve_riley_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/guest_puzzle_steve_riley_seeds.rb"
puts "Processing hashtags_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/hashtags_seeds.rb"
puts "Processing How_goes_it_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/How_goes_it_seeds.rb"
puts "Processing inflexions_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/inflexions_seeds.rb"
puts "Processing jobsite_safety_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/jobsite_safety_seeds.rb"
puts "Processing magazine_inserts_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/magazine_inserts_seeds.rb"
puts "Processing measuring_schtick_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/measuring_schtick_seeds.rb"
puts "Processing mini_tl_12_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_12_seeds.rb"
puts "Processing mini_tl_13_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_13_seeds.rb"
puts "Processing mini_tl_1_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_1_seeds.rb"
puts "Processing mini_tl_2_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_2_seeds.rb"
puts "Processing mini_tl_3_am_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_3_am_seeds.rb"
puts "Processing mini_tl_3_cdn_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_3_cdn_seeds.rb"
puts "Processing mini_tl_4_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_4_seeds.rb"
puts "Processing mini_tl_5_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_5_seeds.rb"
puts "Processing mini_tl_6_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_6_seeds.rb"
puts "Processing mini_tl_7_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_7_seeds.rb"
puts "Processing mini_tl_8_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_8_seeds.rb"
puts "Processing mini_tl_9_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mini_tl_9_seeds.rb"
puts "Processing mystery_of_the_tired_theme_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/mystery_of_the_tired_theme_seeds.rb"
puts "Processing not_now_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/not_now_seeds.rb"
puts "Processing onetequila_twotequila_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/onetequila_twotequila_seeds.rb"
puts "Processing open_the_gates_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/open_the_gates_seeds.rb"
puts "Processing out_of_season_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/out_of_season_seeds.rb"
puts "Processing play_that_funky_music_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/play_that_funky_music_seeds.rb"
puts "Processing programming_camp_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/programming_camp_seeds.rb"
puts "Processing really_packing_it_in_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/really_packing_it_in_seeds.rb"
puts "Processing sackattack_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/sackattack_seeds.rb"
puts "Processing search_party_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/search_party_seeds.rb"
puts "Processing squares_away_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/squares_away_seeds.rb"
puts "Processing take_the_day_off_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/take_the_day_off_seeds.rb"
puts "Processing the_digital_divide_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/the_digital_divide_seeds.rb"
puts "Processing themeless_10_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless_10_seeds.rb"
puts "Processing themeless_11_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless_11_seeds.rb"
puts "Processing themeless_15_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless_15_seeds.rb"
puts "Processing themeless_16_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless_16_seeds.rb"
puts "Processing themeless17_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless17_seeds.rb"
puts "Processing themeless18_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/themeless18_seeds.rb"
puts "Processing vwllss1_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/vwllss1_seeds.rb"
puts "Processing whatdoyouthinkyouredoing_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/whatdoyouthinkyouredoing_seeds.rb"
puts "Processing xnerd_themeless_14_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/xnerd_themeless_14_seeds.rb"
=end
