puts "Processing CN_freestyle24_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle24_seeds.rb"
puts "Processing CN_freestyle26_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle26_seeds.rb"
puts "Processing CN_freestyle27_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle27_seeds.rb"
puts "Processing CN_freestyle28_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle28_seeds.rb"
puts "Processing CN_freestyle29_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle29_seeds.rb"
puts "Processing CN_freestyle30_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle30_seeds.rb"
puts "Processing CN_freestyle31_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle31_seeds.rb"
puts "Processing CN_freestyle32_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_freestyle32_seeds.rb"
puts "Processing CN_upapole_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_upapole_seeds.rb"
puts "Processing CN_vwllss2_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss2_seeds.rb"
puts "Processing CN_vwllss3_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss3_seeds.rb"
puts "Processing CN_vwllss4_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss4_seeds.rb"
puts "Processing CN_vwllss5_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss5_seeds.rb"
puts "Processing CN_vwllss6_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss6_seeds.rb"
puts "Processing CN_vwllss7_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss7_seeds.rb"
puts "Processing CN_vwllss8_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss8_seeds.rb"
puts "Processing CN_vwllss9_seeds.rb...\n"
require "/home/peter/xword_db/db/CN_seedfiles/CN_vwllss9_seeds.rb"
