=begin
puts "Processing gfp50_heard_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp50_heard_seeds.rb"
puts "Processing gfp51_attention_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp51_attention_seeds.rb"
puts "Processing gfp52_numbersgame2_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp52_numbersgame2_seeds.rb"
puts "Processing gfp53_totgear_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp53_totgear_seeds.rb"
puts "Processing gfp54_themeless11_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp54_themeless11_seeds.rb"
puts "Processing gfp55_sound_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp55_sound_seeds.rb"
puts "Processing gfp56_title_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp56_title_seeds.rb"
puts "Processing gfp57_fist_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp57_fist_seeds.rb"
puts "Processing gfp58_hand_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp58_hand_seeds.rb"
puts "Processing gfp59_themeless13_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp59_themeless13_seeds.rb"
puts "Processing gfp60_clothingtime_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp60_clothingtime_seeds.rb"
puts "Processing gfp61_thesethreewords_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp61_thesethreewords_seeds.rb"
puts "Processing gfp62_actingunions_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp62_actingunions_seeds.rb"
puts "Processing gfp63_taylormade_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp63_taylormade_seeds.rb"
puts "Processing gfp64_soul_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp64_soul_seeds.rb"
puts "Processing gfp65_themeless14_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp65_themeless14_seeds.rb"
puts "Processing gfp66_uprightmen_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp66_uprightmen_seeds.rb"
puts "Processing gfp67_themeless15_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp67_themeless15_seeds.rb"
puts "Processing gfp68_18thhole_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp68_18thhole_seeds.rb"
puts "Processing gfp69_cross_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp69_cross_seeds.rb"
puts "Processing gfp70_cspan_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp70_cspan_seeds.rb"
puts "Processing gfp71_film_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp71_film_seeds.rb"
puts "Processing gfp72_newyears_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp72_newyears_seeds.rb"
puts "Processing gfp73_oneliner_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp73_oneliner_seeds.rb"
puts "Processing gfp74_themeless16_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp74_themeless16_seeds.rb"
puts "Processing gfp75_themeless17_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp75_themeless17_seeds.rb"
puts "Processing gfp76_construction_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp76_construction_seeds.rb"
puts "Processing gfp77_er_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp77_er_seeds.rb"
puts "Processing gfp78_olympic_groanze_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp78_olympic_groanze_seeds.rb"
puts "Processing gfp79_downhill_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp79_downhill_seeds.rb"
=end
puts "Processing gfp80_penaltyboxes_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp80_penaltyboxes_seeds.rb"
=begin
puts "Processing gfp81_ease_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp81_ease_seeds.rb"
puts "Processing gfp82_yourcall_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp82_yourcall_seeds.rb"
puts "Processing gfp83_2legit_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp83_2legit_seeds.rb"
puts "Processing gfp84_themeless18_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp84_themeless18_seeds.rb"
puts "Processing gfp85_string_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp85_string_seeds.rb"
puts "Processing gfp86_sex_sells_seeds.rb...\n"
require "/home/peter/xword_db/db/EA_seedfiles/round_2/gfp86_sex_sells_seeds.rb"
=end
