puts "Processing Guest_Puzzle_1_Stay_Right_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Guest_Puzzle_1_Stay_Right_seeds.rb"
puts "Processing Puzzle_1_First_Things_First_and_Second_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_1_First_Things_First_and_Second_seeds.rb"
puts "Processing Puzzle_2_What_a_Loss_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_2_What_a_Loss_seeds.rb"
puts "Processing Puzzle_3_Themeless_1_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_3_Themeless_1_seeds.rb"
puts "Processing Puzzle_4_Hair_Today_Gone_Tomorrow_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_4_Hair_Today_Gone_Tomorrow_seeds.rb"
puts "Processing Puzzle_5_Seamen_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_5_Seamen_seeds.rb"
puts "Processing Puzzle_6_Themeless_2_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_6_Themeless_2_seeds.rb"
puts "Processing Puzzle_7_Natural_Order_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_7_Natural_Order_seeds.rb"
puts "Processing Puzzle_8_Cutting_Crew_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_8_Cutting_Crew_seeds.rb"
puts "Processing Puzzle_9_Themeless_3_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_9_Themeless_3_seeds.rb"
puts "Processing Puzzle_10_American_Cuisine_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_10_American_Cuisine_seeds.rb"
puts "Processing Puzzle_11_Vacancy_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_11_Vacancy_seeds.rb"
puts "Processing Puzzle_12_Themeless_4_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_12_Themeless_4_seeds.rb"
puts "Processing Puzzle_13_Lovely_Ladies_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_13_Lovely_Ladies_seeds.rb"
puts "Processing Puzzle_14_Streets_Ahead_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_14_Streets_Ahead_seeds.rb"
puts "Processing Puzzle_15_Costume_Party_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_15_Costume_Party_seeds.rb"
puts "Processing Puzzle_16_Election_Projection_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_16_Election_Projection_seeds.rb"
puts "Processing Puzzle_17_Family_TV_Show_Finales_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_17_Family_TV_Show_Finales_seeds.rb"
puts "Processing Puzzle_18_Themeless_5_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_18_Themeless_5_seeds.rb"
puts "Processing Puzzle_19_Black_Friday_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_19_Black_Friday_seeds.rb"
puts "Processing Puzzle_20_One_to_Grow_On_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_20_One_to_Grow_On_seeds.rb"
puts "Processing Puzzle_21_Themeless_6_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_21_Themeless_6_seeds.rb"
puts "Processing Puzzle_22_White_Christmas_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_22_White_Christmas_seeds.rb"
puts "Processing Puzzle_23_Its_the_End_of_the_World_as_We_Know_It_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_23_Its_the_End_of_the_World_as_We_Know_It_seeds.rb"
puts "Processing Puzzle_24_Themeless_7_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_24_Themeless_7_seeds.rb"
puts "Processing Puzzle_25_2012_in_Review_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_25_2012_in_Review_seeds.rb"
puts "Processing Puzzle_26_Team_Spirit_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_26_Team_Spirit_seeds.rb"
puts "Processing Puzzle_27_Themeless_8_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_27_Themeless_8_seeds.rb"
puts "Processing Puzzle_28_Decline_and_Fall_of_the_Puzzle_Empire_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_28_Decline_and_Fall_of_the_Puzzle_Empire_seeds.rb"
puts "Processing Puzzle_29_Country_Cookin_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_29_Country_Cookin_seeds.rb"
puts "Processing Puzzle_30_Cryptic_1_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_30_Cryptic_1_seeds.rb"
puts "Processing Puzzle_31_Hearts_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_31_Hearts_seeds.rb"
puts "Processing Puzzle_32_Bjorn_Again_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_32_Bjorn_Again_seeds.rb"
puts "Processing Puzzle_33_Themeless_9_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_33_Themeless_9_seeds.rb"
puts "Processing Puzzle_34_March_Madness_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_34_March_Madness_seeds.rb"
puts "Processing Puzzle_35_Its_Greek_to_Me_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_35_Its_Greek_to_Me_seeds.rb"
puts "Processing Puzzle_36_Themeless_10_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_36_Themeless_10_seeds.rb"
puts "Processing Puzzle_37_Out_Like_a_Lamb_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_37_Out_Like_a_Lamb_seeds.rb"
puts "Processing Bonus_Puzzle_1_Repairmen_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Bonus_Puzzle_1_Repairmen_seeds.rb"
puts "Processing Puzzle_38_Gone_Fishing_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_38_Gone_Fishing_seeds.rb"
puts "Processing Puzzle_39_Themeless_11_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_39_Themeless_11_seeds.rb"
puts "Processing Puzzle_40_The_Apples_in_Stereo_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_40_The_Apples_in_Stereo_seeds.rb"
puts "Processing Puzzle_41_Hit_the_Gym_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_41_Hit_the_Gym_seeds.rb"
puts "Processing Puzzle_42_Themeless_12_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_42_Themeless_12_seeds.rb"
puts "Processing Puzzle_43_Power_Play_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_43_Power_Play_seeds.rb"
puts "Processing Puzzle_44_Office_Olympics_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_44_Office_Olympics_seeds.rb"
puts "Processing Puzzle_45_Cryptic_2_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_45_Cryptic_2_seeds.rb"
puts "Processing Puzzle_46_Web_Crawlr_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_46_Web_Crawlr_seeds.rb"
puts "Processing Puzzle_47_Two_Two_Two_Two_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_47_Two_Two_Two_Two_seeds.rb"
puts "Processing Puzzle_48_Themeless_13_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_48_Themeless_13_seeds.rb"
puts "Processing Puzzle_49_Stop_Me_If_Youve_Heard_This_One_Before_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_49_Stop_Me_If_Youve_Heard_This_One_Before_seeds.rb"
puts "Processing Puzzle_50_Do_the_Wide_Thing_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_50_Do_the_Wide_Thing_seeds.rb"
puts "Processing Puzzle_51_Themeless_14_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_51_Themeless_14_seeds.rb"
puts "Processing Puzzle_52_Im_Coming_Out_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_52_Im_Coming_Out_seeds.rb"
puts "Processing Puzzle_53_Get_the_Party_Started_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_53_Get_the_Party_Started_seeds.rb"
puts "Processing Puzzle_54_Themeless_15_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_54_Themeless_15_seeds.rb"
puts "Processing Puzzle_55_Capital_Tour_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_55_Capital_Tour_seeds.rb"
puts "Processing Puzzle_56_Triple_Treat_seeds.rb...\n"
require "/home/peter/xword_db/db/NF_seedfiles/Puzzle_56_Triple_Treat_seeds.rb"
