clues_A_Turn_for_the_Worse_CR_1_15_09 = Array.new
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ABBOT', number: 1, clue: 'Main monk'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ABSORB', number: 1, clue: 'Take in, as knowledge'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'BIONDI', number: 2, clue: 'Swimmer Matt who won seven medals in one Olympics'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BRUTAL', number: 3, clue: 'Unrelenting'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OTRO', number: 4, clue: 'Another: Spanish'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'THD', number: 5, clue: 'Minister\'s deg.'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'OJAY', number: 6, clue: 'Member of the group who sang "Love Train"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OTERO', number: 6, clue: 'New Mexico county'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'JEANNIE', number: 7, clue: 'Notable role for Barbara Eden'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ATM', number: 8, clue: 'Machine with a lot of receipts piled on top, often'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'YESYOU', number: 9, clue: 'Response to "Who, me?"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'TOMB', number: 10, clue: 'Lenin\'s is open to the public'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TAROT', number: 10, clue: 'Occult deck'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ONELINER', number: 11, clue: 'Terrible joke, often'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MINDMELD', number: 12, clue: 'Vulcan trick'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BLUEEYES', number: 13, clue: 'Physical feature for Daryl Hall and Frank Sinatra'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BIRTH', number: 14, clue: 'Inaugural event?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'TETE', number: 15, clue: 'Where to put a b&#233;ret'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ANIL', number: 16, clue: 'Indigo source'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SOURDREAMS', number: 17, clue: 'What an evil person wishes others before bed?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'REROLL', number: 18, clue: 'Play more craps, perhaps'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'RENU', number: 19, clue: 'Big name in contact lens solution'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ONTO', number: 20, clue: 'No longer tricked by'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'ERN', number: 21, clue: 'East or west end'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'YEOLDE', number: 22, clue: 'Shoppe descriptor'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'ENS', number: 23, clue: 'Some dash lengths'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'RDA', number: 24, clue: 'Roughly 2,000 - 2,500, for calories'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'WRONGONTIME', number: 25, clue: 'What an evil - yet punctual - person tends to be?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'WALT', number: 25, clue: 'Disney, e.g.'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'GOTUP', number: 26, clue: 'Woke'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BILBAO', number: 27, clue: 'Guggenheim locale'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'BAHT', number: 28, clue: 'Bangkok bankroll'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'IOUS', number: 29, clue: 'Promissory notes'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'NEY', number: 30, clue: 'Marshal under Napoleon'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ALLSET', number: 31, clue: '"Everything\'s cool"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SYRIA', number: 32, clue: 'Fertile Crescent country'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'PELE', number: 33, clue: 'Former New York Cosmos star'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'PANG', number: 33, clue: 'Feeling of hunger or regret'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NIGHTLY', number: 34, clue: 'Always before bed, say'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'NEWDEALS', number: 34, clue: 'Fresh starts, in cards'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'IMEANTIT', number: 35, clue: '"That wasn\'t a joke!!"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'GITRDONE', number: 36, clue: 'Larry the Cable Guy\'s autobiography'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'UPWARDS', number: 37, clue: 'How the successful move'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'PLENTY', number: 38, clue: 'Loads'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'WANG', number: 39, clue: 'Computer company that might make the juvenile snicker'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EMIT', number: 40, clue: 'Voice'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'REPLAN', number: 41, clue: 'Make another blueprint'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ENDORSE', number: 42, clue: 'Get behind, on the trail'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'WET', number: 43, clue: 'Andrew W.K.\'s "I Get ___"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'IWIN', number: 44, clue: '"Success!"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'IRV', number: 44, clue: 'Queens emcee Gotti'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'WEEDED', number: 45, clue: 'Cleaned out the bed?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'ENGIRD', number: 46, clue: 'Go around'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ICIEST', number: 47, clue: 'Most slick'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'RENEES', number: 48, clue: 'Fleming and Zellweger'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'DEEPLY', number: 49, clue: 'From the bottom of one\'s heart'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'DARKREADING', number: 50, clue: 'What an evil homeowner keeps in the bathroom?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'KINKS', number: 51, clue: '"The Village Green Preservation Society" band, with "the"'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'INTER', number: 52, clue: 'Lay to rest'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'CEE', number: 53, clue: 'Middling exam mark'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ENDIVE', number: 54, clue: 'Leaf that may be used as a bed'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ONT', number: 55, clue: 'The Raptors\' prov.'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'ZINE', number: 56, clue: 'Maximumrocknroll or Venus, e.g.'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'ZWAN', number: 56, clue: 'Corgan group that had a bad breakup'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ATON', number: 57, clue: 'Lots and lots'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'DIRTYSWEEP', number: 58, clue: 'How an evil athlete hopes to accomplish victory in a playoff series?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'IRE', number: 59, clue: 'Rage'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'SEA', number: 60, clue: 'One may be landlocked, oddly'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LINK', number: 61, clue: 'Zelda\'s rescuer'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ERSE', number: 62, clue: 'Celtic dialect'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EASEL', number: 63, clue: 'Artist\'s support?'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STES', number: 64, clue: 'Canonized Frenchwomen: Abbr.'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DEER', number: 65, clue: 'Large yard pests'))
clues_A_Turn_for_the_Worse_CR_1_15_09.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ANTSY', number: 66, clue: 'Ready to go, already'))
Puzzle.create(title: 'A Turn For the Worse', grid: 'ABBOT.OJAY.TOMB|BIRTH.TETE.ANIL|SOURDREAMS.RENU|ONTO.ERN.YEOLDE|RDA.WRONGONTIME|BILBAO.IOUS.NEY|...ALLSET..PELE|NIGHTLY.UPWARDS|EMIT..REPLAN...|WET.IWIN.ENGIRD|DARKREADING.CEE|ENDIVE.ONT.ZINE|ATON.DIRTYSWEEP|LINK.ERSE.EASEL|STES.DEER.ANTSY', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/1/15', entries: clues_A_Turn_for_the_Worse_CR_1_15_09)
