clues_Adenine_CR_7_30_09 = Array.new
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PANAM', number: 1, clue: 'Classic airline'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PASDE', number: 1, clue: '___ deux (dance)'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ACTOR', number: 2, clue: 'One who does lines?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NEARS', number: 3, clue: 'Appears bigger and bigger'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ARMS', number: 4, clue: 'Subject of some treaties'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'MSPACMAN', number: 5, clue: 'Maze classic'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'GIGA', number: 6, clue: 'Ten to the ninth: Prefix'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'GAFFE', number: 6, clue: 'Mistake on the campaign trail'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ISAIDSO', number: 7, clue: 'Stubborn parental rationale'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'GASX', number: 8, clue: 'Relief name'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ANTI', number: 9, clue: 'No pro'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MERV', number: 10, clue: 'Late game show mogul Griffin'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MUESLI', number: 10, clue: 'Swiss cereal'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ETC', number: 11, clue: 'List ender'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RAG', number: 12, clue: 'Tease, with "on"'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'VHS', number: 13, clue: 'Beta alternative'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ACERS', number: 14, clue: 'Some Taiwanese PCs'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'ASAN', number: 15, clue: '" ___ alternative ..."'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'UTAH', number: 16, clue: 'Where some raptors have been discovered'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'STAMP', number: 17, clue: 'Licked square'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'FAST', number: 18, clue: 'Repent, say'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ECGS', number: 19, clue: 'Records of beats-per-minute: Abbr.'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'DORSALFIXINS', number: 20, clue: 'Garnish for the tail?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'LOO', number: 21, clue: 'Place to go in England'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'NAP', number: 22, clue: 'Part of a preschool day, often'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ERS', number: 23, clue: '"Um" cousins'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'COED', number: 24, clue: 'Like some imaginary naked sporting events, on dumb old t-shirts'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ALERT', number: 25, clue: 'Warn'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'EXIST', number: 26, clue: 'Be'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'RADAR', number: 27, clue: 'Parked highway patrolman\'s gun'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'TRANE', number: 28, clue: '"The House That ___ Built: The Story of Impulse Records" (2006 jazz book)'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'HMO', number: 29, clue: 'Medical care setup, briefly'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'HBO', number: 29, clue: '"True Blood" airer'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'SUBPIXAR', number: 30, clue: 'Like some second-tier animation?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'UOFM', number: 31, clue: 'Where "Hail to the Victors" is sung: Abbr.'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'BLU', number: 32, clue: '___-ray'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'QDOBA', number: 33, clue: 'Chipotle alternative'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'QTIPS', number: 33, clue: 'Cleaners that ought not to hit the drum, if you can help it'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'DONOT', number: 34, clue: 'Prohibition beginning'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ORATE', number: 35, clue: 'Hold court'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'FOOL', number: 36, clue: 'Pull one over on'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'FOCI', number: 36, clue: 'Algebraic meeting points'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'IDA', number: 37, clue: 'Built to Spill\'s state: Abbr.'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TORONTO', number: 38, clue: 'One of my favourite cities in North America'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'TIX', number: 39, clue: 'Will-call things, casually'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'FUJISAN', number: 40, clue: 'Japanese peak, respectfully'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'JOYRIDES', number: 41, clue: 'Some pseudo-thefts'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'IUD', number: 42, clue: 'Planned Parenthood suggestion, for short'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'INA', number: 43, clue: '___ pickle'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ICBM', number: 44, clue: 'SALT concern'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'BEAKERS', number: 45, clue: 'Lab holders'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'OUTRE', number: 46, clue: 'Artistically unusual'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'POTPIXIE', number: 47, clue: 'Drug-dealing sprite?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'PISSED', number: 48, clue: 'Ired'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'INT', number: 49, clue: 'NFL turnover cause'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'SYD', number: 50, clue: 'Barrett who co-founded Pink Floyd'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'STU', number: 50, clue: 'Texas hold \'em legend Ungar'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'STEIN', number: 51, clue: 'Rathskeller mug'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'ASTR', number: 52, clue: 'NASA sci.'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SQUAT', number: 53, clue: 'Nothing'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'TSP', number: 54, clue: 'Letters on a tiny kitchen implement'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'TOOTS', number: 54, clue: 'Sexist address'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'STOIC', number: 55, clue: 'Unemotional thinker'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'PEPTO', number: 56, clue: 'Alternative to 8-Down, casually'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'STOCKQUIXOTE', number: 57, clue: 'Keep some essential Spanish fiction on the shelf?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'OLAV', number: 58, clue: 'Norway\'s patron'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'CITE', number: 59, clue: 'Use material from'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'XRAY', number: 60, clue: 'Source of inner clarity?'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'JIGS', number: 61, clue: 'Quaint dances'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'JAH', number: 61, clue: 'Name in many a reggae lyric'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ICE', number: 62, clue: 'Seal, as a victory'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'GRR', number: 63, clue: '[Stay the fuck away from this scrap yard]'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'LIEU', number: 64, clue: 'Stead'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'DROOP', number: 65, clue: 'Yield to gravity'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ACRE', number: 66, clue: 'Plot unit'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ATRA', number: 67, clue: 'Discontinued Gillette model'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EATIT', number: 68, clue: 'Grammy-winning Yankovic parody of a Michael Jackson hit'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HERD', number: 69, clue: 'Elephants, collectively'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'VEST', number: 70, clue: 'Attire for a waiter or hipster'))
clues_Adenine_CR_7_30_09.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SYSCO', number: 71, clue: 'Big name in ketchup packets and the like'))
Puzzle.create(title: 'Adenine', grid: 'PANAM.GIGA.MERV|ACERS.ASAN.UTAH|STAMP.FAST.ECGS|DORSALFIXINS...|ERS.COED..ALERT|...HMO.SUBPIXAR|QDOBA.FOOL..IDA|TORONTO.FUJISAN|INA..ICBM.OUTRE|POTPIXIE.SYD...|STEIN..ASTR.TSP|...STOCKQUIXOTE|JIGS.LIEU.DROOP|ACRE.ATRA.EATIT|HERD.VEST.SYSCO', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/7/30', entries: clues_Adenine_CR_7_30_09)
