clues_International_Fare_Mixup_CR_5_7_09 = Array.new
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CENT', number: 1, clue: 'Small change'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CASA', number: 1, clue: 'Certain edif&#237;cio'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELHI', number: 2, clue: 'K thru 12'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NOIR', number: 3, clue: 'Film genre often shot in high contrast'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TENT', number: 4, clue: 'Camping cover'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'MANGA', number: 5, clue: 'Japanese animation style'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MILANO', number: 5, clue: 'Pepperidge Farm option'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALEVEL', number: 6, clue: 'Top-shelf'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NEMESIS', number: 7, clue: 'Newman, to Jerry Seinfeld'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'GAUL', number: 8, clue: 'Ancient France'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ALF', number: 9, clue: 'TV puppet who hosted a very short-lived talk show'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SLO', number: 10, clue: '___-mo'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SKIMP', number: 10, clue: 'Be cheap'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LENORE', number: 11, clue: 'Poe poem'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OYSTER', number: 12, clue: 'Bar food?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALOE', number: 13, clue: 'Medicinal household plant'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ILEAL', number: 14, clue: 'Intestine-related'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'KEY', number: 15, clue: 'It\'ll get you in the door'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SHINGLEMUFFINS', number: 16, clue: 'Rainproof one\'s pastries?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'GROG', number: 17, clue: 'Maritime beverage'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'FESSUP', number: 18, clue: 'Make an admission'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AIRTRAVEL', number: 19, clue: 'It blows; I just got scolded for using portable electronic devices and they\'re out of peanuts'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'EMOTE', number: 20, clue: 'Ham it up'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 4, col: 15, dir: 'Down', answer: 'EYE', number: 21, clue: 'Knack for design'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'ONES', number: 22, clue: '"We need ___" (register note)'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'OSPREY', number: 23, clue: 'Fish hawk'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'OENO', number: 23, clue: 'Sommelier\'s prefix'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'REKEGOLIVES', number: 24, clue: 'Prepare uneaten kalamatas for the next frat party?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'RUT', number: 24, clue: 'Routine'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ERA', number: 25, clue: 'Soviet or Weimar follower'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'KIN', number: 26, clue: 'Brothers and sisters, e.g.'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'ECTO', number: 27, clue: 'Plasm starter'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'VIP', number: 28, clue: 'Loge occupant'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'ERE', number: 29, clue: '"I kissed thee ___ I killed thee": Shakespeare'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'URIC', number: 30, clue: 'Acid type that can cause gout'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'SINUS', number: 31, clue: 'Head cavity'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SURF', number: 32, clue: 'Browse, in creaky internet slang'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TANTRUM', number: 33, clue: 'A toddler might throw one'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'RUSSIA', number: 34, clue: 'Nation with eleven time zones'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'UTWO', number: 35, clue: 'Lockheed spy plane'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'MRI', number: 36, clue: 'Inner view, for short'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'POPUPAD', number: 37, clue: 'Flashing annoyance'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'PEI', number: 38, clue: 'I.M. with family members in China?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'AMS', number: 39, clue: 'Waking moments?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'DOH', number: 40, clue: 'Response to dropping donuts and so forth'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'OUTRO', number: 41, clue: 'Coda, slangily'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'OSBORNE', number: 42, clue: 'Super Dave of stunts'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'REMO', number: 43, clue: 'San ___, Italy'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ISM', number: 44, clue: 'School of thought'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'ITS', number: 44, clue: '"___ Pat" (old "SNL" skit)'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'SHIITE', number: 45, clue: 'One of an Iraqi religious majority'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'MANNED', number: 46, clue: 'Staffed'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'SWISHEDFISH', number: 47, clue: 'Halibut prepared by being shot through a net?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'HODADS', number: 48, clue: 'Beach poseurs'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ELICIT', number: 49, clue: 'Bring out'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'DASH', number: 50, clue: 'Scurry'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'THATSO', number: 51, clue: 'Tough guy\'s rhetorical question'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'TACKY', number: 52, clue: 'Like pretty much everything in Graceland'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'BOLA', number: 53, clue: 'Gaucho\'s weapon'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SINAI', number: 54, clue: 'Moses\' mount'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'GODISDEAD', number: 55, clue: 'Oft-misinterpreted Nietzsche quote'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'GEAR', number: 55, clue: 'Neutral, e.g.'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'DEPP', number: 56, clue: 'Sweeney Todd portrayer'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'EELS', number: 57, clue: 'Sushi creatures'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ASAP', number: 58, clue: '"Stat!"'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'DENS', number: 59, clue: 'Rooms with plush furniture, perhaps'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 13, col: 2, dir: 'Across', answer: 'INCAMERACHEESE', number: 60, clue: 'Gruy&#232;re, framed?'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'MRC', number: 61, clue: 'Howard Cunningham, to Fonzie'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 14, col: 2, dir: 'Across', answer: 'TEK', number: 62, clue: 'Shatner\'s "___War"'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'RANDI', number: 63, clue: 'Left-leaning talk show host Rhodes'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'PLAN', number: 64, clue: 'Program'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 15, col: 2, dir: 'Across', answer: 'EDY', number: 65, clue: 'Big name in ice cream'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'CREST', number: 66, clue: 'Whitestrips maker'))
clues_International_Fare_Mixup_CR_5_7_09.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'PSPS', number: 67, clue: 'On-the-go Sony devices, for short'))
Puzzle.create(title: 'International Fare Mixup', grid: 'CENT.MANGA.SLO.|ALOE.ILEAL.KEY.|SHINGLEMUFFINS.|AIRTRAVEL.EMOTE|....ONES.OSPREY|REKEGOLIVES.ERE|URIC...SINUS...|TANTRUM.POPUPAD|...OUTRO...REMO|ISM.SWISHEDFISH|THATSO.BOLA....|SINAI.GODISDEAD|.INCAMERACHEESE|.TEK.RANDI.PLAN|.EDY.CREST.PSPS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/5/7', entries: clues_International_Fare_Mixup_CR_5_7_09)
