clues_J_Play_CR_7_23_09 = Array.new
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ABC', number: 1, clue: 'Anecdotally, the most ubiquitous song of the last month'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'AMB', number: 1, clue: 'UN rep.'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'BELLOWS', number: 2, clue: 'Roars'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'CHAITEA', number: 3, clue: 'Punjabi breakfast beverage'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'ABATES', number: 4, clue: 'Tapers off'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ASKERS', number: 4, clue: 'They do the posing'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'BEERNUTS', number: 5, clue: 'Bar freebies'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANT', number: 6, clue: 'Unpleasant sight in the kitchen'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TAJ', number: 7, clue: 'Indian hotel in 2008 news, with "the"'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ETON', number: 8, clue: 'English college with a recent swine flu outbreak'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SEGER', number: 9, clue: '"Night Moves" composer Bob'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'JAPE', number: 10, clue: 'Make fun of'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'JAILSATAN', number: 10, clue: 'Chant from a crowd angry at the Antichrist?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ABSINTH', number: 11, clue: 'Wormwood plant product now legal in the U.S.: Var.'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PANEITY', number: 12, clue: 'The state of being bread (!)'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EAT', number: 13, clue: 'Scarf down'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MEH', number: 14, clue: '[Shrug]'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'SENATE', number: 15, clue: 'Franken\'s group'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ABAA', number: 16, clue: 'Simple rhyme scheme'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BLANKETJOG', number: 17, clue: 'Run taken in the extreme cold?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'NGO', number: 18, clue: 'Doctors Without Borders, e.g.'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ISNT', number: 19, clue: 'It\'s ain\'t like you\'d see it in the dictionary'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'LIGER', number: 20, clue: 'Hybrid animal "bred for its skills in magic," per Napoleon Dynamite'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'NELLIE', number: 21, clue: 'Feminist journalist Bly or singer-songwriter McKay'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'LEPEW', number: 22, clue: 'Pep&#233; of cartoons'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'JOTORNOT', number: 23, clue: 'Rating site that asks users whether they would use a given notepad?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'JAE', number: 23, clue: 'One-named South African pop star'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'OSAKAN', number: 24, clue: 'From Japan\'s second-largest city'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'THU', number: 25, clue: 'It may be abbreviated "H," on a calendar'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'RESNIK', number: 26, clue: 'Challenger passenger Judith'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'KYL', number: 27, clue: 'Jon who\'s junior to John McCain, in Arizona'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'AWE', number: 28, clue: 'Shock and ___'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SUSHI', number: 29, clue: 'Rolls at a bar'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ISWEAR', number: 30, clue: 'Words of fealty'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'PATTY', number: 31, clue: 'Burger shape'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ESAI', number: 32, clue: 'Morales on "Jericho"'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'ICEJOCKEY', number: 33, clue: 'One who plays music at skating parties?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'TAUS', number: 34, clue: 'Greek T\'s'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ETHYL', number: 35, clue: '___ alcohol'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'CASK', number: 36, clue: 'Thing to help you hold your liquor'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'AMINO', number: 37, clue: '___ acid (protein component)'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'WAWA', number: 38, clue: 'Psychedelic guitar effect, onomatopoetically'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'AEROSOLS', number: 39, clue: 'Particles of concern to climatologists'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PROEM', number: 40, clue: 'Preamble'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'PBS', number: 40, clue: '"Frontline" network'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'REORDER', number: 41, clue: 'React to selling out'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'ONLEAVE', number: 42, clue: 'Having a baby, say'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ALEE', number: 43, clue: 'Away from the wind, on a ship'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'LEG', number: 44, clue: 'Race section'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'NLCS', number: 45, clue: 'MLB playoff round that featured LA and Phil. in 2008'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'LAJOLLA', number: 46, clue: 'Well-to-do Southern California town'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'COUPLET', number: 47, clue: 'One may be heroic'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'SKG', number: 48, clue: 'DreamWorks ___'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BENJI', number: 49, clue: 'Movie dog'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'NEARS', number: 50, clue: 'Draws close'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'SUNDAE', number: 51, clue: 'Fudge-drenched treat, often'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'AOK', number: 52, clue: 'Hunky-dory'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SOLONG', number: 53, clue: '"Peace"'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'GIJOE', number: 54, clue: '"Knowing is half the battle" doll'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'GROUPJUG', number: 55, clue: 'Big wine vessel passed around?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'POO', number: 56, clue: '___~pourri (bathroom scent brand)'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'RECOIL', number: 57, clue: 'Show horror'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'LEOX', number: 58, clue: 'Pope who excommunicated Martin Luther'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'SNOOP', number: 59, clue: 'Washed-up-but-still-nominally-entertaining "Dogg After Dark" host, casually'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SDAK', number: 60, clue: 'Mt. Rushmore locale'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'SWF', number: 60, clue: 'Abbr. in personal ads'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'JELLODOLLY', number: 61, clue: 'Hand truck for carting around a certain no-bake dessert?'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'LLC', number: 62, clue: 'Inc. relative'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'LAI', number: 63, clue: 'My ___, Vietnam'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'YIP', number: 64, clue: 'Litter cry'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WEVE', number: 65, clue: '"What ___ got here is a failure to communicate ..."'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'OOLALA', number: 66, clue: '"Fan-cy!"'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'LEI', number: 67, clue: 'Oahu necklace'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'FREY', number: 68, clue: 'Glenn of the Eagles'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'EXCISE', number: 69, clue: 'Cut out'))
clues_J_Play_CR_7_23_09.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'ATP', number: 70, clue: 'Federer and Nadal\'s org.'))
Puzzle.create(title: 'J Play', grid: 'ABC.ABATES.JAPE|MEH.SENATE.ABAA|BLANKETJOG.ISNT|.LIGER..NELLIE.|JOTORNOT.RESNIK|AWE.SUSHI.PATTY|ESAI.TAUS.ETHYL|...CASK.WAWA...|PROEM.ALEE.NLCS|BENJI.NEARS.AOK|SOLONG.GROUPJUG|.RECOIL..SNOOP.|SDAK.JELLODOLLY|WEVE.OOLALA.LEI|FREY.EXCISE.ATP', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/7/23', entries: clues_J_Play_CR_7_23_09)
