clues_Or_Not_To_Be_CR_12_3_09 = Array.new
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'INSECTA', number: 1, clue: 'Entomology class?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'INCAS', number: 1, clue: 'Members of a pre-Columbian empire'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'NEATO', number: 2, clue: '"Wowza!"'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SELFDENIAL', number: 3, clue: 'What a dieter practices'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EDE', number: 4, clue: 'Netherlands city'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'CLINICS', number: 5, clue: 'Outpatient treatment points'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TELE', number: 6, clue: 'Prefix with tubby or market'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ARLO', number: 7, clue: 'Woody Guthrie\'s son'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'ISOGRAM', number: 8, clue: 'Word with no repeating letters'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ISABEL', number: 8, clue: 'Deadly 2003 hurricane'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SOCIAL', number: 9, clue: 'Mixer that may involve ice cream'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'OAKTREE', number: 10, clue: 'Source of some expensive wood'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GRR', number: 11, clue: '[Return that bone at once, or I shall bare my teeth and yip!]'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'REAL', number: 12, clue: 'Genuine'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ARCS', number: 13, clue: 'Geometric curves'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MSED', number: 14, clue: 'Teacher\'s deg.'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NEEDLER', number: 15, clue: 'Teasing type'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'SOARERS', number: 16, clue: 'Eagles or hawks, at times'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CALEILL', number: 17, clue: 'Headline about the failing health of a former Velvet Underground member?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'ACKRACE', number: 18, clue: 'Contest to see who can read "Cathy" fastest?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ATF', number: 19, clue: 'Sin tax org.'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'NEO', number: 20, clue: 'Modern: Prefix'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'BIT', number: 21, clue: 'Shtick'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'LSD', number: 22, clue: 'Something to trip on'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SODOI', number: 23, clue: '"Likewise!"'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'OAT', number: 24, clue: 'Cereal unit'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'NEARS', number: 25, clue: 'Gets bigger, visually'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'NOTAONE', number: 25, clue: 'Zip, nada, nil'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'SYD', number: 26, clue: 'Famously burned-out rock musician Barrett'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'EACHVOLLEYALL', number: 27, clue: '"OK, tennis students, I want everyone to practice near the net with everyone else"?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'HUM', number: 28, clue: 'Annoying speaker problem'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'VIE', number: 29, clue: 'Contend'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'ADDISABABA', number: 30, clue: 'Ethiopian National Library city'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'LION', number: 31, clue: 'Football player who won zero games in 2008'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'LESE', number: 32, clue: '___ majest&#233;'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'PANTSUIT', number: 33, clue: 'Sartorial trademark for Clinton'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'PSEC', number: 33, clue: 'One 60-trillionth of a min.'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ACTA', number: 34, clue: 'Cleveland Indians manager Manny'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'EDDIE', number: 35, clue: 'Money with "Two Tickets to Paradise"'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SCI', number: 36, clue: 'Subj. that may have a lab'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'MEADE', number: 37, clue: 'Big name in telescopes'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'DUD', number: 38, clue: 'Failed firework'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ETH', number: 39, clue: 'Biblical verb ender'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'DOS', number: 40, clue: '___ and DON\'Ts ("Vice" feature)'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ETAIL', number: 41, clue: 'Digital business portmanteau'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'IVS', number: 42, clue: 'Medical lines'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'LIPSYNC', number: 43, clue: 'Fake it, musically'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'OUTSHINE', number: 44, clue: 'Upstage'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'SOUPCON', number: 45, clue: 'Tiny trace'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'HEN', number: 46, clue: 'Mother clucker'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'CALVINANDHOES', number: 47, clue: 'Expos&#233; about the tawdry relations of a 16th-century theologian?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'NONONO', number: 48, clue: '"You\'ve got it all wrong"'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'AROMAS', number: 49, clue: 'Wafting things'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'SPORE', number: 50, clue: '2008 video game where you begin as a microscopic organism'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'UNAPT', number: 51, clue: 'Not suitable'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'PISAN', number: 52, clue: 'Galileo, e.g.'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'TVSET', number: 53, clue: 'Tube'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ALT', number: 54, clue: 'Key near CTRL'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'ADAB', number: 54, clue: 'Very little'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'LIRR', number: 55, clue: 'Commuter line to Penn Station'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'TRIO', number: 56, clue: 'The Jonas Brothers, e.g.'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'SNO', number: 57, clue: '___-Cat (cold-weather vehicle)'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'STP', number: 58, clue: 'Scott Weiland\'s band, briefly'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SLAP', number: 58, clue: 'Hit with an open hand'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'TAME', number: 59, clue: 'Domesticated'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'BIV', number: 60, clue: 'Bell ___ DeVoe'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DIRTYOM', number: 61, clue: 'Ribald yoga mantra?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'TAN', number: 62, clue: 'Just back from the beach, apparently'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'LACKASS', number: 63, clue: 'Have a flat bottom?'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'KEN', number: 64, clue: 'Friend of Ryu in the Street Fighter games'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ARIANNA', number: 65, clue: 'Huffington of "The Huffington Post"'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'AMOEBAE', number: 66, clue: 'Microscopic shape-shifters'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'BRONCOS', number: 67, clue: 'Rodeo challenges'))
clues_Or_Not_To_Be_CR_12_3_09.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'PENNANT', number: 68, clue: 'Baseball league winner\'s prize'))
Puzzle.create(title: '... Or Not To Be', grid: 'INSECTA.ISOGRAM|NEEDLER.SOARERS|CALEILL.ACKRACE|ATF.NEO.BIT.LSD|SODOI..NEARS...|..EACHVOLLEYALL|PANTSUIT..EDDIE|SCI..MEADE..DOS|ETAIL..OUTSHINE|CALVINANDHOES..|...SPORE..UNAPT|ALT.SNO.STP.BIV|DIRTYOM.LACKASS|ARIANNA.AMOEBAE|BRONCOS.PENNANT', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/12/3', entries: clues_Or_Not_To_Be_CR_12_3_09)
