clues_Special_K_CR_7_2_09 = Array.new
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ZAC', number: 1, clue: 'Teen idol Efron'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ZAGAT', number: 1, clue: 'Big name in restaurant ratings'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AMAZE', number: 2, clue: 'Bowl over'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'COLON', number: 3, clue: 'Dash alternative'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'GOUDA', number: 4, clue: 'Mild Dutch cheese'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'GOBEFORE', number: 4, clue: 'Face, as a judge'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OWLS', number: 5, clue: 'Temple attenders?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'UNA', number: 6, clue: 'Acapulco article'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DEC', number: 7, clue: 'Cal. ender'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ARK', number: 8, clue: 'Vessel for a famous couples cruise?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'ARFED', number: 9, clue: 'Spoke, as in obedience school'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'APACHE', number: 9, clue: 'Song sampled on "The Adventures of Grandmaster Flash on the Wheels of Steel"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'RESTACKS', number: 10, clue: 'Plays another game of Jenga, say'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'FAQS', number: 11, clue: 'Informative web site sections'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ECUA', number: 12, clue: 'Quito\'s nation: Abbr.'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DEES', number: 13, clue: 'Near-failing grades'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMO', number: 14, clue: 'Latin 101 verb'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'OWNER', number: 15, clue: 'Property tax payer'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'PEACE', number: 16, clue: 'State where no one uses their arms?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GAL', number: 17, clue: 'Guy\'s date'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'BLACKBASQUE', number: 18, clue: 'African immigrant in the Pyrenees?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'BATU', number: 19, clue: 'Mongol ruler Khan descended from Genghis'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AZORES', number: 20, clue: 'Islands west of Portugal'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'ROB', number: 21, clue: 'Knock over'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'ACTSAS', number: 22, clue: 'Does the work of'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TENOF', number: 23, clue: ':50'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'ARETHA', number: 24, clue: 'Preacher and civil rights activist C.L. Franklin\'s daughter'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'ATM', number: 24, clue: 'Place to check your balance'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RIP', number: 25, clue: 'Halloween decoration letters'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'EQS', number: 26, clue: 'Tweaks, as a DJ would'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'BOUTIQUECALL', number: 27, clue: 'Dialing up an expensive shop?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'UAW', number: 28, clue: 'Negotiator with the Big Three'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'AWAR', number: 29, clue: '"What if they gave ___ ..."'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'LAYS', number: 30, clue: '"Betcha can\'t eat just one" chips'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'LIST', number: 31, clue: 'Tick off'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ICK', number: 32, clue: '"Gross, bugs!"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'INCA', number: 32, clue: 'Peruvian of old'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'COHN', number: 33, clue: 'Actress Mindy of "The Facts of Life"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'KNIT', number: 34, clue: 'Be a needle user?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'RAMPS', number: 35, clue: 'Skate park objects'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'KWAI', number: 36, clue: '"The Bridge on the River ___"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NONJEW', number: 37, clue: 'One bubby might not want you to marry'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'JAILBAIT', number: 38, clue: 'Illegal lover, slangily'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'ESSAYS', number: 39, clue: 'Regrettably, easily downloadable things'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ERN', number: 39, clue: 'Directional suffix'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'SHERBETS', number: 40, clue: 'Fruity desserts'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'CHIA', number: 41, clue: '"Ch-ch-ch-___"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'FOURH', number: 42, clue: 'Club for rural youth'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'FEE', number: 42, clue: 'Professional\'s charge'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'OAR', number: 43, clue: 'Crew stick'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'UNS', number: 44, clue: 'Young \'___'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'RST', number: 45, clue: 'Line before U'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ANTIQUEANNES', number: 46, clue: 'Mall kiosk with really stale pretzels?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'QUEBEC', number: 47, clue: 'Canadian province with a separatist movement'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'UGLI', number: 48, clue: 'Homely fruit'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SOS', number: 49, clue: 'Plea to the Coast Guard'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'LUGERS', number: 50, clue: 'Downhill Olympians'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'ROOMS', number: 51, clue: 'Motel vacancies'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'OHJOY', number: 52, clue: 'Catchphrase for Stimpy'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'MOLTS', number: 53, clue: 'Sheds feathers'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'STOOL', number: 54, clue: 'Item manufactured in Blaine in "Waiting for Guffman"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ISABEL', number: 55, clue: '___ Toledo (designer of Michelle Obama\'s inauguration dress)'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'IWON', number: 55, clue: '"You didn\'t sink my battleship!"'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'SAUR', number: 56, clue: 'End of the Jurassic period?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ASTO', number: 57, clue: 'Regarding'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'BBSHOT', number: 58, clue: 'Air rifle ammo'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'BUST', number: 58, clue: 'Chest'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'WASABIPIQUE', number: 59, clue: 'Intense feeling from eating sushi?'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'PJS', number: 60, clue: 'One-piece, perhaps'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'IOC', number: 61, clue: 'Org. that accepted Michael Phelps\' apology for smoking pot'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'QUO', number: 62, clue: 'Status ___'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'JLO', number: 63, clue: 'Eponymous 2001 pop album'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OUTIE', number: 64, clue: 'Belly button type'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'JOUST', number: 65, clue: 'Perform at the faire, perhaps'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'OTO', number: 66, clue: 'Certain Sioux speaker'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NROTC', number: 67, clue: 'Midshipmen\'s prep program'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SCOTS', number: 68, clue: 'Belle & Sebastian, e.g.'))
clues_Special_K_CR_7_2_09.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'YSL', number: 69, clue: 'Monogram on many a fancy handbag'))
Puzzle.create(title: 'Special K', grid: 'ZAC.GOUDA.ARFED|AMO.OWNER.PEACE|GAL.BLACKBASQUE|AZORES...ACTSAS|TENOF.ARETHA...|...BOUTIQUECALL|ICK.RAMPS..KWAI|NONJEW...ESSAYS|CHIA..FOURH.RST|ANTIQUEANNES...|...LUGERS.ROOMS|ISABEL...BBSHOT|WASABIPIQUE.JLO|OUTIE.JOUST.OTO|NROTC.SCOTS.YSL', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/7/2', entries: clues_Special_K_CR_7_2_09)
