clues_Turn_Em_Up_CR_12_17_09 = Array.new
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PPSS', number: 1, clue: 'Secondary letter addenda'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PESACH', number: 1, clue: 'Passover, in the Haggadah'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PANFRY', number: 2, clue: 'Cook, as hash browns'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'STIRUP', number: 3, clue: 'Incite'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'SAPIENS', number: 4, clue: 'Homo ___ (people)'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'RVS', number: 5, clue: 'Campers'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RADAR', number: 5, clue: 'Palindromic "M*A*S*H*" nickname'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'VGA', number: 6, clue: 'Old computer monitor letters'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SEW', number: 7, clue: 'Fix a seam, e.g.'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'ONLATE', number: 8, clue: 'Like infomercials, often'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ORSON', number: 8, clue: 'He directed Charlton in "Touch of Evil"'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NUKED', number: 9, clue: 'Microwaved'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'LXI', number: 10, clue: '61, in old Rome'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'APPARENT', number: 11, clue: 'Clear'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TIPS', number: 12, clue: 'They\'re usually left after dinner'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENYA', number: 13, clue: 'New Age name'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EATA', number: 14, clue: '"I could ___ horse!"'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AGE', number: 15, clue: 'Era'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'RUXPIN', number: 16, clue: 'Animatronic toy bear Teddy'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SNIP', number: 17, clue: 'Minor cut?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'DAWNSKIPPY', number: 18, clue: 'Peanut butter at the break of day?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'NCIS', number: 19, clue: 'Military procedural spun off from "JAG"'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AFRICA', number: 20, clue: 'Ouagadougou\'s continent'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'CLOTHE', number: 21, clue: 'Put in gear?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'COE', number: 22, clue: '"Take This Job and Shove It" composer David Allan'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ASA', number: 23, clue: 'Gay-window link'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'CRUELREWINDER', number: 24, clue: 'One who sets a VHS of "The Crying Game" precisely to the money shot?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'EDIT', number: 25, clue: 'Chop up, as footage'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'WARZONE', number: 26, clue: 'Area with active fire, perhaps'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ELK', number: 27, clue: 'Puma prey'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'HYPNO', number: 28, clue: 'Mentalist\'s prefix'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'DAS', number: 29, clue: '"___ Boot"'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'LEIA', number: 30, clue: 'Carrie played her in Episodes IV - VI'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'IOU', number: 31, clue: 'Note left after stealing a roommate\'s food, say'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'AXE', number: 32, clue: 'Bunyan\'s tool'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'STAIR', number: 33, clue: 'Flight unit?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'AUK', number: 34, clue: 'Diving bird'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'FTKNOX', number: 35, clue: '"Goldfinger" depository'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'FAT', number: 35, clue: 'Oft-saturated stuff'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'THROAT', number: 36, clue: 'It may be cleared before a speech'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SAC', number: 37, clue: 'Kangaroo pouch'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'SOY', number: 37, clue: 'Tofu source'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'ACE', number: 38, clue: 'Big name in hardware'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'CATCHALL', number: 39, clue: 'Multipurpose'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'HUTZPAH', number: 40, clue: 'Balls: Yiddish'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'PUNT', number: 41, clue: 'Give up on fourth down'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'TUE', number: 42, clue: 'Election Day abbr.'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OCASEK', number: 43, clue: 'Ric who produced the first Weezer record'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'SIR', number: 44, clue: 'Round Table title'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'OUTRO', number: 45, clue: 'Album epilogue'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ONLEAVE', number: 46, clue: 'Taking time off'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'YETI', number: 47, clue: 'Himalayan legend'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'CNN', number: 48, clue: 'Station Lou Dobbs recently quit'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'CUBE', number: 48, clue: 'Sugar unit'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ONELS', number: 49, clue: 'First-year law students'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ELAPSE', number: 50, clue: 'Go by'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'LESSON', number: 51, clue: 'Teacher\'s unit'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'STEEPS', number: 52, clue: 'Prepares the pot?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'CROQUETWALLET', number: 53, clue: 'Cash carrier for lawn game enthusiasts?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ONPOT', number: 54, clue: 'One way to be high'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'QUOTE', number: 55, clue: 'Cite'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'WAYIN', number: 56, clue: 'Entrance'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'UGH', number: 57, clue: 'Disgusted word'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'USER', number: 57, clue: 'Software designer\'s consideration'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'GLEE', number: 58, clue: 'Fox drama since May, 2009'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'NUB', number: 59, clue: 'Pencil, late in life'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ATEASE', number: 60, clue: '"Relax, private!"'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SLAWPOETRY', number: 61, clue: '"You\'re rich, with cabbage delish/Once tried, always on my side," e.g.?'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'WPA', number: 62, clue: 'Huge New Deal agcy.'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'TAJ', number: 63, clue: '___ Mahal'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'RNA', number: 64, clue: '"Messenger" molecule'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'APSE', number: 65, clue: 'Place for relics, perhaps'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EELPOT', number: 66, clue: 'Conger catcher'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ANI', number: 67, clue: '"Little Plastic Castle" singer DiFranco'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'VSOP', number: 68, clue: 'Cognac grade'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RELATE', number: 69, clue: 'Have a connection'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'JAN', number: 70, clue: '"Miami Vice" theme composer Hammer'))
clues_Turn_Em_Up_CR_12_17_09.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'EENS', number: 71, clue: 'Poetic nights'))
Puzzle.create(title: 'Turn \'Em Up', grid: 'PPSS.RVS.ONLATE|EATA.AGE.RUXPIN|SNIP.DAWNSKIPPY|AFRICA..COE.ASA|CRUELREWINDER..|HYPNO.DAS..LEIA|...STAIR.FTKNOX|SAC.HUTZPAH.TUE|OCASEK.OUTRO...|YETI..CNN.ONELS|..CROQUETWALLET|UGH.NUB..ATEASE|SLAWPOETRY.APSE|EELPOT.ANI.VSOP|RELATE.JAN.EENS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2009/12/17', entries: clues_Turn_Em_Up_CR_12_17_09)
