clues_Can_you_Digit_CR_6_7_07 = Array.new
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'EME', number: 1, clue: 'Linguist\'s suffix'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ESTONIA', number: 1, clue: 'Northern European nation that instituted internet voting in 2005'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MAHJONG', number: 2, clue: 'Tile game'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'EDUARDO', number: 3, clue: 'Don ___ tequila'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'GAFFES', number: 4, clue: 'Political fumbles'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'GOB', number: 4, clue: '"Arrested Development" brother'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ARNO', number: 5, clue: 'Tuscany river'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'FEAR', number: 6, clue: 'It might make you sweat'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'FLICKR', number: 7, clue: 'Photobucket alternative'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ESL', number: 8, clue: 'Immigrant\'s night school subj.'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SEPIA', number: 9, clue: 'Old-timey tone'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SEEYA', number: 10, clue: '"Later!"'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SUCK', number: 10, clue: 'Word that is both a synonym and an antonym for "blow"'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ENTS', number: 11, clue: 'Otorhinolaryngologists, more commonly'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'EDU', number: 12, clue: 'Part of a teacher\'s contact'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'YER', number: 13, clue: '"___ out!" (call at the plate)'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'ARE', number: 14, clue: 'Art, nowadays?'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'SAD', number: 15, clue: 'Bummed'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ORELSE', number: 16, clue: 'End of a threat'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'UNDER', number: 17, clue: 'Anaesthetized'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'THUMBNAILPICTURE', number: 18, clue: 'Reduced image'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'MISE', number: 19, clue: '___-en-sc&#232;ne'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'INN', number: 20, clue: 'Place with a keeper'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OJAI', number: 21, clue: 'Resort town near Santa Barbara'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'ORC', number: 22, clue: '"The Hobbit" humanoid'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'INKS', number: 23, clue: 'Signs'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NORSE', number: 24, clue: 'Icelandic, e.g.'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'EXPIRE', number: 25, clue: 'Kick the bucket'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'KOAN', number: 26, clue: 'Meditation question'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ODIE', number: 27, clue: 'Two-dimensional beagle'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 14, dir: 'Across', answer: 'ALG', number: 28, clue: 'H.S. math class'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'AMY', number: 28, clue: 'Tan with novels'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'LAO', number: 29, clue: 'Neighbor of a Vietnamese'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 5, col: 16, dir: 'Down', answer: 'GNU', number: 30, clue: 'Bearded grazer'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'INDEXCARD', number: 31, clue: 'Oration aid'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'CODE', number: 32, clue: 'Web composition'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'ADDS', number: 33, clue: 'Puts in the mix'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'PRMAN', number: 34, clue: 'Image manipulator'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'PRETTY', number: 34, clue: 'Good to look at'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'RED', number: 35, clue: 'Commie'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AGO', number: 36, clue: 'Fourth word in the "Star Wars" opening crawl'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'POD', number: 37, clue: 'Legume lodging'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'IDAREYOU', number: 38, clue: 'Challenge to a big talker'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'DAMN', number: 39, clue: '"Wow!"'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'AGOG', number: 40, clue: 'Wowed'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'MIDDLEAGED', number: 41, clue: 'At the top of the hill, so to speak'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'MET', number: 41, clue: 'Made, as a deadline'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 8, col: 8, dir: 'Down', answer: 'LARA', number: 42, clue: 'Game femme Croft'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'STTERESA', number: 43, clue: 'Counter-Reformation figure canonized in 1622'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SEE', number: 43, clue: 'Go with'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'TVS', number: 44, clue: 'Some sets'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'TIP', number: 45, clue: 'Server\'s reward'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'MOT', number: 46, clue: 'Bon ___'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 14, dir: 'Across', answer: 'ERA', number: 47, clue: 'Tide competitor'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'ENCLASP', number: 47, clue: 'Grip'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'REALISM', number: 48, clue: 'Sober outlook'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 9, col: 16, dir: 'Down', answer: 'ASSENTS', number: 49, clue: 'Capitulates'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EVITE', number: 50, clue: 'Social planning site'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'RINGTONES', number: 51, clue: 'Some downloaded ditties'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ICETEA', number: 52, clue: 'Stuff in a pitcher'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'OWER', number: 53, clue: 'One in the hole'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ESP', number: 54, clue: 'Special insight?'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'IMAC', number: 55, clue: 'Core 2 Duo computer'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'IDA', number: 55, clue: 'Ore-___'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'MINTS', number: 56, clue: 'Hostess table bowlful'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'YWCAS', number: 57, clue: 'Some rec centers'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'ANDI', number: 58, clue: '"___ will always love you" (anthemic refrain)'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'AKON', number: 58, clue: 'One-named rapper who launched the Konvict Clothing line'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'NYNY', number: 59, clue: 'Line on a letter to a friend on the Lower East Side'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'EAT', number: 60, clue: 'Use as fuel'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'AHAB', number: 61, clue: 'Obsessive fictional skipper'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'TETE', number: 62, clue: 'Head of France?'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ELLE', number: 63, clue: 'First name in supermodeling, or the magazine that bears her name'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PINKYANDTHEBRAIN', number: 64, clue: '"Animaniacs" spinoff starring two lab mice'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'POM', number: 64, clue: 'Bottled beverage whose name is taken from the fruit it contains'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'IRA', number: 65, clue: '401(k) cousin'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'NIN', number: 66, clue: 'Cleveland industrial band, briefly'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'DRE', number: 67, clue: 'Doctor ___ ("Yo! MTV Raps" host)'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'BYE', number: 68, clue: 'Tournament freebie'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ORION', number: 69, clue: 'Constellation containing Canis Major and Minor'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'TREATY', number: 70, clue: 'Post-feud signing'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 14, col: 14, dir: 'Across', answer: 'SST', number: 71, clue: 'Black Flag label'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MANNY', number: 72, clue: 'Often absurd Red Sox outfielder, to fans'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SEABEE', number: 73, clue: 'Navy construction worker'))
clues_Can_you_Digit_CR_6_7_07.push(Entry.create(row: 15, col: 14, dir: 'Across', answer: 'PMS', number: 74, clue: 'Condition evoked in many a misogynist comment'))
Puzzle.create(title: 'Can You Digit?', grid: 'EME.GAFFES.SEEYA|SAD.ORELSE.UNDER|THUMBNAILPICTURE|OJAI.ORC.INKS...|NORSE..KOAN..ALG|INDEXCARD..PRMAN|AGO.POD.IDAREYOU|...MIDDLEAGED...|STTERESA.MOT.ERA|EVITE..RINGTONES|ESP..IMAC..YWCAS|...ANDI.EAT.ELLE|PINKYANDTHEBRAIN|ORION.TREATY.SST|MANNY.SEABEE.PMS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/6/7', entries: clues_Can_you_Digit_CR_6_7_07)
