clues_Clean_Swap_CR_4_5_07 = Array.new
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BETA', number: 1, clue: 'Test version'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BEEB', number: 1, clue: 'UK network nickname, with "the"'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EAVE', number: 2, clue: 'Icicle site'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TROD', number: 3, clue: 'Walked'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ALLSTARS', number: 4, clue: 'Like six White Sox, in 2006'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'OPUS', number: 5, clue: 'Work in music'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OUTHUD', number: 5, clue: 'Defunct indie band that shared members with !!!'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PLIE', number: 6, clue: 'Ballet move'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'UNOS', number: 7, clue: 'Declarations in a popular Mattel card game'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SANT', number: 8, clue: '"Psycho" re-director Gus Van ___'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'ACCRA', number: 9, clue: 'Home of the Kwame Nkrumah Memorial'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ARTICHOKE', number: 9, clue: 'You can eat its heart out'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'COOPT', number: 10, clue: 'Take as one\'s own'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'CAR', number: 11, clue: 'Skylark or Firebird'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RDA', number: 12, clue: 'Label stat'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ASH', number: 13, clue: '"Evil Dead" hero Williams'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EARL', number: 14, clue: 'Abusive husband in a Dixie Chicks song'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ULNA', number: 15, clue: 'Bone under a bracelet'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'ROADS', number: 16, clue: 'Lines on a map'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'EVOLUTION', number: 17, clue: 'Niche-finding process'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'UTA', number: 18, clue: 'Broadway\'s Hagen'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'TORAH', number: 19, clue: 'Numbers is about 20% of it'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BEDSTHESTRIP', number: 20, clue: 'Has sex with everyone in the heart of Las Vegas?'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'RASTA', number: 21, clue: 'One who smokes pot religiously'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'TAU', number: 22, clue: 'Kind of cross'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'ACTORS', number: 23, clue: 'They might get paid to play'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'OFNOTE', number: 24, clue: 'Important'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'RECURS', number: 25, clue: 'Happens again, as a dream'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'SERTAS', number: 26, clue: 'Some mattresses'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PABA', number: 27, clue: 'UV filter in sunscreen'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PATTIE', number: 27, clue: 'Peppermint candy unit'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ABRADE', number: 28, clue: 'Wear down'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'BOATER', number: 29, clue: 'One making a wake'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'DANISH', number: 30, clue: 'Croissant alternative'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'APHID', number: 31, clue: 'Ladybug\'s prey'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'NIECE', number: 32, clue: 'My cousin, to my mom'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'INTEL', number: 33, clue: 'Chip maker'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'FEE', number: 34, clue: 'Charge'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ABORC', number: 35, clue: 'Scantron choice, maybe'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'CHAMELEON', number: 36, clue: 'Skin color changer'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'PINTO', number: 37, clue: 'Burrito bean'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'NCR', number: 38, clue: 'Big ATM maker'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TRASHTHETAKEOUT', number: 39, clue: 'Mock moo goo gai pan?'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'TSORO', number: 40, clue: 'Ancient African logic game'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'EXHIBITA', number: 41, clue: 'It may kick off a case'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TAT', number: 42, clue: 'B-baller\'s decoration'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ASICE', number: 43, clue: '"Cold ___" (1977 Foreigner hit)'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'EXTRA', number: 44, clue: 'ET competitor'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'IDE', number: 45, clue: 'Chemical ending'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'MODELT', number: 46, clue: 'Henry Ford: "People can have the ___ in any color, as long as it\'s black"'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'TEHRAN', number: 47, clue: 'Where Mahmoud Ahmadinejad was once mayor'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'HESS', number: 48, clue: 'Name on a toy truck'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'EERIER', number: 49, clue: 'More freaky'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'IFIDO', number: 50, clue: '"Don\'t mind ___!"'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'ELI', number: 51, clue: 'Giant Manning'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'LEA', number: 52, clue: 'Grazing ground'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'FLOORTHEBUFF', number: 53, clue: 'Amaze a Civil War expert?'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'ONCE', number: 54, clue: 'Without repetition'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ROOS', number: 55, clue: 'Shoes with an interior pocket'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'TBSP', number: 56, clue: 'Saffron amt., perhaps'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'UNIX', number: 57, clue: 'Bell Labs invention'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'FELL', number: 58, clue: 'Took a spill'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'FREE', number: 59, clue: 'Like the Reader'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CELIE', number: 60, clue: 'Whoopi\'s role in "The Color Purple"'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'CCR', number: 60, clue: '"Up Around the Bend" band, briefly'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ERA', number: 61, clue: 'Long stretch'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'LEG', number: 62, clue: 'Race section'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'NOBRAINER', number: 63, clue: 'Straightforward choice'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CREDO', number: 64, clue: 'Doctrine'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'COSA', number: 65, clue: '___ Nostra'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'TILE', number: 66, clue: 'Mah Jongg piece'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RAGON', number: 67, clue: 'Ride'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'ESPN', number: 68, clue: 'Sweaty athlete shower?'))
clues_Clean_Swap_CR_4_5_07.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'AXLE', number: 69, clue: 'Trucker\'s toll unit'))
Puzzle.create(title: 'Clean Swap', grid: 'BETA.OPUS.ACCRA|EARL.ULNA.ROADS|EVOLUTION.TORAH|BEDSTHESTRIP...|...TAU...ACTORS|PABA.DANISH.FEE|ABORC.PINTO.NCR|TRASHTHETAKEOUT|TAT.ASICE.EXTRA|IDE.MODELT.HESS|EERIER...ELI...|...FLOORTHEBUFF|CELIE.NOBRAINER|CREDO.COSA.TILE|RAGON.ESPN.AXLE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/4/5', entries: clues_Clean_Swap_CR_4_5_07)
