clues_Drug_Combinations_CR_5_31_07 = Array.new
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MAYA', number: 1, clue: 'Guatemala natives'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MEDIC', number: 1, clue: 'Cry from a wounded infantryman'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AWASH', number: 2, clue: 'Teeming'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'YENTA', number: 3, clue: 'Buttinsky'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ASK', number: 4, clue: 'Call upon'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'WAWA', number: 5, clue: 'Psych pedal'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WHOYOU', number: 5, clue: 'Question to a scrawny kid trying out for wrestling'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'AMIE', number: 6, clue: 'Fran&#231;oise\'s flame'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'WON', number: 7, clue: 'Wooed successfully'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ASTRO', number: 8, clue: 'Nolan Ryan, for years'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'XANAX', number: 9, clue: 'Anxiety medication often advertised in spam'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'XMASES', number: 9, clue: 'Present times, casually'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'AIM', number: 10, clue: 'Colgate alternative'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'NAE', number: 11, clue: 'Groundskeeper Willie\'s turndown'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ASS', number: 12, clue: 'Action, slangily'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'XMS', number: 13, clue: 'Some satellite radios'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EWES', number: 14, clue: 'She-sheep'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HMOS', number: 15, clue: 'PCP providers?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'MIASM', number: 16, clue: 'Condition, in homeopathy'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DANKJOINT', number: 17, clue: '*Cave-like bar?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'JERRY', number: 18, clue: 'First name in jamming'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'AMESS', number: 19, clue: 'Make ___ of (trash)'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'IST', number: 20, clue: 'Follower of Marx or Mao?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'EYE', number: 21, clue: 'Haven in a hurricane'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'RSS', number: 22, clue: 'Web feed letters'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'SKULK', number: 23, clue: 'Lurk'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'CHARRO', number: 24, clue: 'Mexican cowboy'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'RANDALL', number: 25, clue: 'Baseball\'s Big Unit, by birth'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'COKETABS', number: 26, clue: '*What you pop on some pop tops?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'CANUCKS', number: 26, clue: 'Team that lost to the Ducks in the 2007 NHL playoffs'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'TOOLKIT', number: 27, clue: 'Nut case?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'APNEA', number: 28, clue: 'Sleeping issue'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'BENET', number: 29, clue: 'Jon___ (ongoing tabloid obsession)'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'SNORE', number: 30, clue: 'Make noise in bed'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ARUBA', number: 31, clue: 'Caribbean destination'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'BAJA', number: 32, clue: 'Gulf of California peninsula'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'USOPEN', number: 33, clue: 'Grand Slam event in both tennis and golf'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CORNY', number: 34, clue: 'Lame'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'CAROB', number: 34, clue: 'So-called "Hippie Chocolate"'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'OTARU', number: 35, clue: 'Hokkaido seaport'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'RAGED', number: 36, clue: 'Partied hard'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'ANAL', number: 37, clue: 'Tight-assed'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ANEW', number: 38, clue: 'From the top'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ONNO', number: 39, clue: '___ account'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ATAD', number: 40, clue: 'Slightly'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'EJUNK', number: 41, clue: '*Spam?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'EMEND', number: 41, clue: 'Polish prose'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'LEER', number: 42, clue: 'Look longingly'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'RAGA', number: 43, clue: 'Carnatic sitar composition'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'MACE', number: 44, clue: 'Purse spray'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'SKATE', number: 45, clue: 'Participate in Ice Capades'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'SLURS', number: 45, clue: 'Reveals intoxication'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ORELSE', number: 46, clue: 'Ultimate words in an ultimatum'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'SIMILE', number: 47, clue: '"Good as new," e.g.'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'KWELI', number: 48, clue: '"If skills sold, truth be told, I\'d probably be / lyrically Talib ___" (Jay-Z lyric)'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'EARWAX', number: 49, clue: 'Canal clogger'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BUDLINES', number: 50, clue: '*Queues for the King of Beers?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'ESSEX', number: 51, clue: 'County in East England'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'AUTEUR', number: 52, clue: 'Miranda July, e.g.'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'EIEIO', number: 53, clue: 'Kid\'s refrain'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'UTERO', number: 54, clue: 'Nirvana\'s "In ___"'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'RODAN', number: 55, clue: 'Kitschy 50\'s film monster'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'MDS', number: 56, clue: '"Grey\'s Anatomy" figs.'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'BRR', number: 57, clue: 'Sub-zero exclamation'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'BOLO', number: 57, clue: 'Tie with a cord'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ITO', number: 58, clue: 'Judge in the Keating S&L trial'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IRAQI', number: 59, clue: 'Al Anbar resident'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'IRE', number: 59, clue: 'Redness?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'REX', number: 60, clue: 'Common dog moniker'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'APU', number: 61, clue: 'A member of Springfield\'s Be Sharps'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'QED', number: 62, clue: 'Proof letters'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'SNOWSPEED', number: 63, clue: 'Skier\'s measure?'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'NUB', number: 64, clue: 'Well-used pencil'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'PMS', number: 65, clue: 'Evenings'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'REPEL', number: 66, clue: 'Turn back'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'EULA', number: 67, clue: 'Faulkner femme fatale Varner'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'MIRA', number: 68, clue: 'A Sorvino'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'EXUDE', number: 69, clue: 'Send out, as a vibe'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'XBOX', number: 70, clue: '360 maker'))
clues_Drug_Combinations_CR_5_31_07.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SOON', number: 71, clue: 'Anon'))
Puzzle.create(title: 'Drug Combinations', grid: 'MAYA.WAWA.XANAX|EWES.HMOS.MIASM|DANKJOINT.AMESS|IST.EYE.RSS....|CHARRO.COKETABS|...ARUBA.USOPEN|CORNY.ANAL.ONNO|ATAD.EJUNK.LEER|RAGA.MACE.SKATE|ORELSE.KWELI...|BUDLINES.AUTEUR|....MDS.BRR.ITO|IRAQI.SNOWSPEED|REPEL.EULA.MIRA|EXUDE.XBOX.SOON', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/5/31', entries: clues_Drug_Combinations_CR_5_31_07)
