clues_Hues_on_First_CR_3_29_07 = Array.new
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ALF', number: 1, clue: 'Cat-eating alien of TV'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ANJOU', number: 1, clue: 'Pear variety'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LIEIN', number: 2, clue: 'Protest tactic'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FATLIP', number: 3, clue: 'Fight souvenir'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'MRRIGHT', number: 4, clue: 'Match.com user\'s goal, perhaps'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'MOLE', number: 4, clue: 'Plant'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RNAS', number: 5, clue: 'Cell messengers'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RECTOR', number: 6, clue: 'Parish head'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'INK', number: 7, clue: 'Liquid from a well'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'GAB', number: 8, clue: 'Jaw'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'HMO', number: 9, clue: 'Managed care grp.'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TEXT', number: 10, clue: 'Contact by phone, in a way'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'JAM', number: 11, clue: 'Hot track'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'JPMORGAN', number: 11, clue: 'Noted robber baron'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ARAPAHOE', number: 12, clue: 'Colorado county named for a local tribe'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MODESTLY', number: 13, clue: 'Without pretense'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NIA', number: 14, clue: '"Big Momma\'s House" actress Long'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ONENAME', number: 15, clue: 'Quality Bono and Cher share'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'PRO', number: 16, clue: 'Paid player'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'JETBLACKBOX', number: 17, clue: 'Accident analysis tool in a commercial aircraft?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'BISECT', number: 18, clue: 'Cut, as a line'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'MAD', number: 19, clue: 'Cracked competitor'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OILIEST', number: 20, clue: 'Most unctuous'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'TROPE', number: 21, clue: 'Figure of speech'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'RBI', number: 22, clue: 'Stat for a HR hitter'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'UNIS', number: 23, clue: 'Colleges Down Under, slangily'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'OGLE', number: 24, clue: 'Look lustfully'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'GET', number: 25, clue: 'Appreciate'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'LEAH', number: 26, clue: 'Wife of Jacob'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ENTAIL', number: 27, clue: 'Involve'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'BRAS', number: 28, clue: 'Two-piece pieces'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'PEAGREENLIGHT', number: 29, clue: 'Permission to consume legumes?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ALOUD', number: 30, clue: 'For all to hear'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'GENTRY', number: 31, clue: 'Landed group'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'LUCRE', number: 32, clue: '"Filthy ___ Tour" (1996 Sex Pistols reunion)'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'CLE', number: 33, clue: 'The Indians, on the scoreboard'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'TATU', number: 34, clue: 'Russian pop duo'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'AOL', number: 35, clue: 'Co. with controversial customer service'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ACETONE', number: 36, clue: 'Active ingredient in nail polish remover'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'ASBESTOS', number: 36, clue: 'Carcinogenic fireproofing'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'CALAMARI', number: 37, clue: 'Cephalopod, on a plate'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'EMOTICON', number: 38, clue: ':-P, e.g.'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'EEEE', number: 39, clue: 'Clown shoe width'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'HACKNEY', number: 40, clue: 'Horse before the cart'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'KARATE', number: 41, clue: 'Art with a ranking system'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SAM', number: 42, clue: 'Frodo\'s friend'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'UTEP', number: 43, clue: 'Lone Star State sch.'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'PDA', number: 44, clue: 'BlackBerry, for one'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'IRA', number: 45, clue: 'Portfolio part'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BLOODREDALERT', number: 46, clue: 'Clotting emergency?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'OAR', number: 47, clue: 'Stick in the crick'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ARABLE', number: 48, clue: 'Agriculturally viable'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'TRALEE', number: 49, clue: 'Kerry\'s county'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'EATA', number: 50, clue: '"...I could ___ horse"'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'YEAR', number: 51, clue: 'Sentence unit'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'ARMA', number: 52, clue: 'First word of Virgil\'s "Aeneid"'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'MIATA', number: 53, clue: 'Sporty Mazda model'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'ANWAR', number: 54, clue: 'Egyptian statesman Sadat'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SMIRK', number: 55, clue: 'Self-satisfied smile'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'KNEW', number: 56, clue: 'Had down pat'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ABSTAIN', number: 57, clue: 'Just not do it?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'BLOG', number: 58, clue: 'Merriam-Webster\'s 2004 Word of the Year'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'SUNG', number: 59, clue: 'Made melodic'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'TAC', number: 60, clue: 'Half a mint?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'NAVYBLUELAW', number: 61, clue: 'No drinking on deck after 5 p.m.?'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'ACE', number: 62, clue: 'Score well on'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'VHS', number: 63, clue: 'Beta beater'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'YET', number: 64, clue: 'Even so'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ORO', number: 65, clue: 'Conquistador\'s prize'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ECHELON', number: 66, clue: 'Command level'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ETA', number: 67, clue: 'Greek "H"'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SIN', number: 68, clue: 'Failing'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'WESTEGG', number: 69, clue: '"The Great Gatsby" setting'))
clues_Hues_on_First_CR_3_29_07.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'EAR', number: 70, clue: 'Musical aptitude'))
Puzzle.create(title: 'Hues on First', grid: 'ALF.MRRIGHT.JAM|NIA.ONENAME.PRO|JETBLACKBOX.MAD|OILIEST...TROPE|UNIS..OGLE.BRAS|..PEAGREENLIGHT|...CLE.TATU.AOL|ACETONE.HACKNEY|SAM.UTEP.IRA...|BLOODREDALERT..|EATA.YEAR..ARMA|SMIRK...ABSTAIN|TAC.NAVYBLUELAW|ORO.ECHELON.ETA|SIN.WESTEGG.EAR', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/3/29', entries: clues_Hues_on_First_CR_3_29_07)
