clues_Jam_Session_CR_8_23_07 = Array.new
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'GCLEF', number: 1, clue: 'Staff starter?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'GWB', number: 1, clue: 'Successor to W.J.C.'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CAL', number: 2, clue: '___ Tech'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LIU', number: 3, clue: 'Lucy of "Lucky Number Slevin"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EVE', number: 4, clue: 'Certain threshold'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'FEMIDOM', number: 5, clue: 'Sponge alternative'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'VTEN', number: 6, clue: 'Powerful engine'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'VANS', number: 6, clue: 'Warped Tour sponsor'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TUDOR', number: 7, clue: 'Style for many a Hyde Park home'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ERA', number: 8, clue: 'It goes down with a shutout'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'NAY', number: 9, clue: 'Vote to kill?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SPRY', number: 10, clue: 'Peppy'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SCARF', number: 10, clue: 'Eat voraciously'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PALAIS', number: 11, clue: '___ Royal (Louvre neighbor)'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'RKELLY', number: 12, clue: 'Indicted musician who said: "Osama Bin Laden is the only one who knows what I\'m going through"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'YESSED', number: 13, clue: 'Green-lighted'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'WAIVE', number: 14, clue: 'Give up'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'AURA', number: 15, clue: 'Walter Benjamin subject'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'CAKE', number: 16, clue: 'One may be erotic'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BLUEMONDAY', number: 17, clue: 'New Order hit'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'OPAL', number: 18, clue: 'Gem mined in Australia'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ALES', number: 19, clue: 'Some are pale'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'IPSO', number: 20, clue: '___ facto'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'ORALS', number: 21, clue: 'Some exams'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'OPEN', number: 21, clue: 'Take the stage first'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'PRAVDA', number: 22, clue: 'Old Bolshevik paper'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'PRAM', number: 22, clue: 'London stroller'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'RARA', number: 23, clue: 'Haitian party music'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'AVON', number: 24, clue: 'Shakespearean stream'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'VIOXX', number: 25, clue: '2004 Merck recall'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'RASPFILE', number: 26, clue: 'Woodworking tool'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ASTRAL', number: 27, clue: 'Starry'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'SHAY', number: 28, clue: 'N*E*R*D*\'s Haley'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'RAVIOLI', number: 29, clue: 'Tasty pockets'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'IBERIA', number: 30, clue: 'Gibraltar\'s locale'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'SHE', number: 31, clue: 'Start of a well-known tongue twister'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'SYD', number: 32, clue: 'Late rock recluse Barrett'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AROOM', number: 33, clue: '"Get ___, you two!"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'BOTANY', number: 34, clue: 'Field of flowers?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ORR', number: 35, clue: 'Seven-time N.H.L. All-Star Bobby'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'YEARS', number: 36, clue: 'The time of one\'s life?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MANX', number: 37, clue: 'Tailless cat'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'BERRY', number: 38, clue: 'Word that may follow the first word of 17-, 26-, 52-, or 60-Across'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'BERM', number: 38, clue: 'Driving shoulder'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'EASE', number: 39, clue: 'Lighten (up)'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'AREA', number: 40, clue: 'Result of calculating  (1/2) a b sin C'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'SEEN', number: 41, clue: 'Taken in by a doctor?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'EDDA', number: 42, clue: 'Icelandic epic'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'XTERRA', number: 43, clue: 'Nissan SUV'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'TOWS', number: 44, clue: 'Enforces a parking restriction'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'JARED', number: 45, clue: 'Weight-loss celebrity, familiarly'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'JUKEBOX', number: 45, clue: 'Pay-per-play device'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'IMF', number: 46, clue: 'Global debt org.'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'ISOPOD', number: 46, clue: 'Aquatic crustacean'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'MTVTWO', number: 47, clue: 'Where "Wonder Showzen" was shown'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'FRAUEN', number: 48, clue: 'Marlene Dietrich und Angela Merkel'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ORI', number: 49, clue: '"...___ will turn this car around!"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'LOUREED', number: 50, clue: 'Laurie Anderson\'s boyfriend'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'OOZE', number: 51, clue: 'Slimy semi-liquid'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'STRAWMAN', number: 52, clue: 'Scarecrow, e.g.'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'ALIST', number: 53, clue: 'Recent Oscar winners, e.g.'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'NAOMI', number: 54, clue: '"No Logo" author Klein'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'OKSANA', number: 55, clue: 'Gold medalist Baiul'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'OVALS', number: 56, clue: 'Circuits for 55-Across'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ADZE', number: 57, clue: 'Woodworking tool'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'DSOS', number: 58, clue: 'U.K. military medals'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PTUI', number: 59, clue: 'Seed-spitter\'s sound'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'GOOSEBUMPS', number: 60, clue: 'Literary series with "Monster Blood" and "Night of the Living Dummies"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'GUT', number: 60, clue: 'Loser\'s target?'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'OOH', number: 61, clue: 'Sound of amazement'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'UTE', number: 62, clue: 'Rocky Mountains Indian'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'MER', number: 63, clue: 'Debussy\'s \'\'La __\'\''))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'PRO', number: 64, clue: 'Expert, in slang'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'SIX', number: 65, clue: 'Blossom\'s pal'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OWES', number: 66, clue: 'Has a balance'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'UOMO', number: 67, clue: 'L\'___ Vogue'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'OTERI', number: 68, clue: 'Former SNL cast member Cheri'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DONT', number: 69, clue: '"No!"'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'THIS', number: 70, clue: 'What we have here'))
clues_Jam_Session_CR_8_23_07.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'XEROX', number: 71, clue: 'Copy'))
Puzzle.create(title: 'Jam Session', grid: 'GCLEF.VTEN.SPRY|WAIVE.AURA.CAKE|BLUEMONDAY.ALES|....IPSO..ORALS|PRAVDA.RASPFILE|RAVIOLI.SHE.SYD|AROOM.BOTANY...|MANX.BERRY.EASE|...XTERRA.JARED|IMF.ORI.LOUREED|STRAWMAN.OKSANA|OVALS..ADZE....|PTUI.GOOSEBUMPS|OWES.UOMO.OTERI|DONT.THIS.XEROX', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/8/23', entries: clues_Jam_Session_CR_8_23_07)
