clues_Land_Locked_CR_11_22_07 = Array.new
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BOWLER', number: 1, clue: 'Cricket figure'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BACOS', number: 1, clue: 'Salad topping brand'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OPART', number: 2, clue: 'Magic Eye picture, e.g.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'WITTY', number: 3, clue: 'Like Oscar Wilde'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'LECHER', number: 4, clue: 'Dirty old man'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ECHO', number: 5, clue: 'Parrot'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'REI', number: 6, clue: 'O ___ do Futebol (Pel&#233;\'s nickname)'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'SPIT', number: 7, clue: 'Dentist\'s command'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'STARR', number: 7, clue: 'Independent counsel in the Lewinsky case'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'POLLO', number: 8, clue: 'Arroz con ___'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'IDIOMS', number: 9, clue: 'Vernacular phrases'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TOE', number: 10, clue: 'Low digit?'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'OWE', number: 11, clue: 'Have a tab'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OBEDIENCE', number: 11, clue: 'Desirable canine trait'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'WILDABOUT', number: 12, clue: 'Really into'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENIAC', number: 13, clue: 'Old 30-ton computer'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'APIECE', number: 14, clue: 'Per'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'TODO', number: 15, clue: 'Type of list'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'BIN', number: 16, clue: 'It may be full of garbage'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CATCHINALIE', number: 17, clue: 'Expose, as a perjurer'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'NAY', number: 18, clue: 'Thumbs-down'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ELI', number: 19, clue: 'Peyton Manning\'s younger brother'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ORTHO', number: 20, clue: 'Cosmetic dentistry, familiarly'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'ARLO', number: 21, clue: '"City of New Orleans" singer Guthrie'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'ADDA', number: 22, clue: 'Start of a recipe direction'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ANDOR', number: 22, clue: 'Words with a / between them'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'STYE', number: 23, clue: 'Lid lesion'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'PYROMANIAC', number: 24, clue: 'One playing with fire'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'PION', number: 24, clue: 'Subatomic particle'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'AIDING', number: 25, clue: 'At the service of'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'RBI', number: 26, clue: 'Slugger\'s stat'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'BRANDO', number: 27, clue: 'Portrayer of Kurtz and Corleone'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'SIDEB', number: 28, clue: 'Wax half'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DOS', number: 29, clue: 'Cuban couple'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'DIO', number: 29, clue: 'Ronnie James of mid-period Black Sabbath'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'OFFHANDED', number: 30, clue: 'Unrehearsed'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'SIMONSAYS', number: 31, clue: 'Mimetic game'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'ROACH', number: 32, clue: 'Joint, at the end'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ATM', number: 33, clue: '"Fast cash" site'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'CHI', number: 34, clue: 'The Sox, on the scoreboard'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'HEX', number: 35, clue: 'Spell'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'DONOT', number: 36, clue: 'Prohibition beginning'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'TSA', number: 37, clue: 'Carry-on checkers: Abbr.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IFIRANTHECIRCUS', number: 38, clue: '1956 Dr. Seuss book about ill-conceived plans'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'RANGE', number: 39, clue: 'Two octaves, maybe'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'CITI', number: 40, clue: 'Big name in credit cards'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OFMAN', number: 41, clue: '"The Descent ___"'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'MIXIN', number: 42, clue: 'Start of a recipe direction'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ETA', number: 43, clue: 'H, to Homer'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'HONDA', number: 44, clue: '"Punch Out!!" fighter Piston ___'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ALGORE', number: 45, clue: 'Noted beard-grower of 2001'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'TGI', number: 46, clue: 'Friday\'s preceder?'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'ISLETS', number: 47, clue: 'Tiny masses in the sea'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'MANGOLASSI', number: 48, clue: 'Mumbai quaff'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'MARKS', number: 48, clue: 'Brands'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'AIMAT', number: 49, clue: 'Target'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'SNAGS', number: 50, clue: 'Starts a run?'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SON', number: 51, clue: 'Jesus, e.g.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'STEW', number: 52, clue: 'Stay mad'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'TARSI', number: 53, clue: 'Anklebones'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ENRON', number: 54, clue: 'Subject of the documentary "The Smartest Guys in the Room"'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'WAYNE', number: 55, clue: 'An Arnold on "The Wonder Years"'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ANSE', number: 56, clue: '"As I Lay Dying" father'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'GINO', number: 57, clue: 'Namesake of a noted Chicago pizza chain'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'ALANA', number: 58, clue: 'Rod Stewart\'s ex'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'AJAR', number: 58, clue: 'Like a door, when it\'s not a door, in a riddle'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RDA', number: 59, clue: '18 mgs. of iron, e.g.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'TOMANDJERRY', number: 60, clue: 'Violent toon duo'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'TBS', number: 60, clue: 'Court TV parent co.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'DRU', number: 61, clue: '___ Hill'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'KEY', number: 62, clue: 'Put a scratch in, as a car\'s paint job'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'BRAG', number: 63, clue: 'Make oneself look big'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'RATSON', number: 64, clue: 'Sells out, in a way'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SDS', number: 65, clue: '\'60s antiwar grp.'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SETS', number: 66, clue: 'Completist\'s goals'))
clues_Land_Locked_CR_11_22_07.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'URSINE', number: 67, clue: 'Like a bear'))
Puzzle.create(title: 'Land Locked', grid: 'BOWLER.SPIT.OWE|APIECE.TODO.BIN|CATCHINALIE.ELI|ORTHO.ARLO.ADDA|STYE.PYROMANIAC|...RBI...SIDEB.|DOS.ROACH.DONOT|IFIRANTHECIRCUS|OFMAN.MIXIN.ETA|.HONDA...TGI...|MANGOLASSI.STEW|ANSE.GINO.ALANA|RDA.TOMANDJERRY|KEY.BRAG.RATSON|SDS.SETS.URSINE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/11/22', entries: clues_Land_Locked_CR_11_22_07)
