clues_Needle_Work_CR_1_25_07 = Array.new
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'NOB', number: 1, clue: 'San Francisco\'s ____ Hill'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'NISSAN', number: 1, clue: 'Datsun, now'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ORELSE', number: 2, clue: '"___ what?" (response to a threat)'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BELAIR', number: 3, clue: '"...to sit on my throne as the prince of ___"'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'AQUA', number: 4, clue: 'Prefix with man or marine'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'APSO', number: 4, clue: 'Lhasa___'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'QUANDARY', number: 5, clue: 'Pickle'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'UPTHE', number: 6, clue: 'Words before ante'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ASSET', number: 7, clue: 'Plus'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'ESHARP', number: 8, clue: 'F, in other words'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'EARWIG', number: 8, clue: 'Insect with pincers'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'STERNO', number: 9, clue: 'Buffet heater'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HOPIS', number: 10, clue: 'People who share a reservation with the Tewa Indians'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ANOS', number: 11, clue: 'Yucat&#225;n years'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'REST', number: 12, clue: 'What\'s left'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'PRE', number: 13, clue: 'The beginning of school, for a toddler?'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IRE', number: 14, clue: 'Indignation'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'PUPS', number: 15, clue: 'Litter contents'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'ATONER', number: 16, clue: 'Lent participant'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SEL', number: 17, clue: 'French seasoning'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'SATS', number: 18, clue: 'Adults score them for HS students'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'REPOSE', number: 19, clue: 'Tranquility'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SLAPONHERWRIST', number: 20, clue: 'Feeling literal, the small-time con woman tattooed the word ___'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'PFUNK', number: 21, clue: 'Parliament style'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'RANCHO', number: 22, clue: '___ Relaxo (one-time getaway for Marge Simpson)'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ASIF', number: 23, clue: '"Not!"'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'DETAINS', number: 24, clue: 'Holds, as for questioning'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'NERUDA', number: 25, clue: '"Il Postino" poet'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'DOE', number: 26, clue: 'Anonymous surname, in court'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'NGO', number: 27, clue: 'The AARP, e.g.'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'ANT', number: 28, clue: 'Farm worker'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'AJA', number: 28, clue: 'Steely Dan album with "Black Cow"'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'NBC', number: 29, clue: '"The Office" network'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'TSK', number: 30, clue: '"I would have thought better of you..."'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'NORDIC', number: 31, clue: 'Like Icelandic and Faeroese'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'DOESSO', number: 32, clue: 'Playground retort'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'INV', number: 33, clue: 'Freelancer\'s bill: Abbr.'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'JBS', number: 34, clue: 'The Godfather\'s backing band'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MONKEYONHERBACK', number: 35, clue: 'Feeling literal, the woman with the zoo-going addiction tattooed the word ___'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'MGM', number: 35, clue: 'Frequent fight spot, with "Grand"'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'OAR', number: 36, clue: 'Stick in the water'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'NYC', number: 37, clue: 'MTA town'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ELITISTS', number: 38, clue: 'Nose-in-the-air types'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'RVS', number: 39, clue: 'Campers, for short'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'BELTS', number: 40, clue: 'Waist products?'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'GAY', number: 41, clue: 'Word with pride or Paree'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'EVOLVE', number: 42, clue: 'Find one\'s niche?'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MRC', number: 43, clue: 'Richie\'s dad, to the Fonz'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'GIS', number: 44, clue: 'Google Earth mapping syst.'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'GAELIC', number: 44, clue: 'Highland tongue'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'INSIST', number: 45, clue: 'Put a foot down'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'ISLAND', number: 46, clue: 'Vancouver or Manhattan'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ARISTA', number: 47, clue: 'Epic competitor'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'NUDIST', number: 48, clue: 'Someone with free junk?'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'DEEDEE', number: 49, clue: 'A Ramone'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'PANSOUT', number: 50, clue: 'Goes as hoped'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'PISTE', number: 50, clue: 'Ski run'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ONTAP', number: 51, clue: 'Not bottled'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'UHURA', number: 52, clue: '"Star Trek" lieutenant who participated in TV\'s first interracial kiss'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'TRUE', number: 53, clue: 'Straight'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'FRIESONHISSIDE', number: 54, clue: 'Feeling literal, the guy with the dead-end fast food job tattooed the word ___'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'FUME', number: 54, clue: 'Seethe'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'REAL', number: 55, clue: 'Street, colloquially'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'SKYS', number: 56, clue: '"The ___ the limit!"'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MUESLI', number: 57, clue: 'Swiss breakfast choice'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'MAS', number: 57, clue: 'More, in Madrid'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'TUSK', number: 58, clue: 'Mammoth weapon'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'SID', number: 59, clue: 'A Sex Pistol'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AMATIS', number: 60, clue: 'Prized violins'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ARTY', number: 61, clue: 'Into shootings and public hangings?'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'TSE', number: 62, clue: 'Twice, a deadly African fly'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SELECT', number: 63, clue: 'Choose'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'PASS', number: 64, clue: 'Choose not to choose'))
clues_Needle_Work_CR_1_25_07.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'ATE', number: 65, clue: 'Had haggis or hamburgers'))
Puzzle.create(title: 'Needle Work', grid: 'NOB.AQUA.ESHARP|IRE.PUPS.ATONER|SEL.SATS.REPOSE|SLAPONHERWRIST.|ASIF.DETAINS...|NERUDA..NGO.ANT|...NORDIC...JBS|MONKEYONHERBACK|GAY...EVOLVE...|MRC.GIS..ISLAND|...PANSOUT.TRUE|.FRIESONHISSIDE|MUESLI.TUSK.SID|AMATIS.ARTY.TSE|SELECT.PASS.ATE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/1/25', entries: clues_Needle_Work_CR_1_25_07)
