clues_Painless_Solutions_CR_2_1_07 = Array.new
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BBQ', number: 1, clue: 'Sauce style, briefly'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BILBO', number: 1, clue: 'John Ronald Reuel\'s hero'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'BCELL', number: 2, clue: 'Immune system lymphocyte'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'QUAID', number: 3, clue: 'Randy who played a homophobic rancher in "Brokeback Mountain"'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'TATA', number: 4, clue: '"So long!"'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TVPG', number: 4, clue: 'Mild program rating'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'AERI', number: 5, clue: 'Atmospheric prefix'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TRON', number: 6, clue: '1982 Midway arcade hit'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ABSTAIN', number: 7, clue: 'Keep one\'s pants on?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'RIFLES', number: 8, clue: 'Rummages (through)'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RESET', number: 8, clue: 'Bowler\'s button'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'INAWE', number: 9, clue: 'Floored'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'FEMIDOM', number: 10, clue: 'Protection for women'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LRON', number: 11, clue: 'Hubbard, founder of the Dianetic Research Foundation'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'EGAD', number: 12, clue: '"Zounds!"'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SYN', number: 13, clue: 'Thes. entry'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ICU', number: 14, clue: 'Hosp. drama locale, perhaps'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'VERB', number: 15, clue: 'Publish or perish, e.g.'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'ENERGY', number: 16, clue: 'By law, it can\'t be destroyed - or produced'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LEA', number: 17, clue: 'Grassy field'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'PROS', number: 18, clue: 'Upsides'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'SAMOAN', number: 19, clue: 'Like Prime Minister Tuilaepa Aiono Sailele Malielegaoi'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'BLINGINTHEWIND', number: 20, clue: 'Jewelry hanging on a clothesline?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'NERD', number: 21, clue: 'Wonk'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'HCL', number: 22, clue: 'Stomach acid, symbolically'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'OLDE', number: 23, clue: 'Ye follower'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'ACTED', number: 24, clue: 'Played a part'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'RETAIL', number: 25, clue: 'What one doesn\'t pay at a clearance sale'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'EDIE', number: 26, clue: 'Little ___ ("Grey Gardens" nickname)'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'TESH', number: 27, clue: 'Former "ET" host John'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'AAA', number: 28, clue: 'Roadside assistance offerer: Abbr.'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'OPAL', number: 29, clue: 'Australian gemstone'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'PASA', number: 30, clue: '"&#191;Qu&#233; ___?"'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'AZUL', number: 31, clue: 'Beb&#233; color'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'LEEK', number: 32, clue: 'Vegetable that\'s a Welsh symbol'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HARDDEAN', number: 33, clue: 'Tough campus boss?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'HAND', number: 33, clue: 'Seinfeldian shorthand for control in a relationship'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'AGER', number: 34, clue: 'Ripening additive'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ROVE', number: 35, clue: 'Bush aide who claimed knowledge of "THE math" before incorrectly predicting the outcome of the 2006 U.S. elections'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'LAMAZE', number: 36, clue: 'Labor class'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'LULL', number: 36, clue: 'Letup'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'AXLE', number: 37, clue: 'Toll unit'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AGO', number: 38, clue: 'Erenow'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'ISA', number: 39, clue: '"Judy___ Punk"'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'TUX', number: 40, clue: 'Prom piece'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'TIE', number: 40, clue: 'Have the same goals?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SUE', number: 41, clue: 'Boys\' name of song'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'NEVAEH', number: 42, clue: 'Anagrammatic girls\' name given to eight babies in 1999, and 4,457 in 2005'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'AIRLINE', number: 43, clue: 'Song, once'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'PILLTALK', number: 44, clue: 'Dosage discussion?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'PERUSED', number: 44, clue: 'Gave the once-over'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'TELL', number: 45, clue: 'Squeal'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'DREI', number: 46, clue: 'Sechs/zwei'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'LEELEE', number: 47, clue: 'Actress Sobieski'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'LAO', number: 47, clue: 'Thai neighbor'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'RADAR', number: 48, clue: 'Defense mechanism?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ALLIN', number: 49, clue: 'Confident-seeming bet'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'DJSET', number: 50, clue: 'Event when the tables turn?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'LPGA', number: 51, clue: 'Lorena Ochoa\'s org.'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'PIANO', number: 52, clue: 'Mover\'s challenge'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'GSPOT', number: 53, clue: 'Good thing to hit'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'AMUST', number: 54, clue: 'Absolutely necessary'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'YELLJOURNALISM', number: 55, clue: 'Style for a loud reporter?'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'YVES', number: 55, clue: 'Part of YSL'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'EARS', number: 56, clue: 'They can burn or ring'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'ROXY', number: 57, clue: 'Half a Bryan Ferry band name'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'NOPE', number: 58, clue: '"Sorry..."'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'ANOS', number: 59, clue: '2006 y 2007'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AVAILS', number: 60, clue: 'Is of use to'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ABA', number: 60, clue: 'Counselors\' org.'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'SOON', number: 61, clue: 'By and by'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'APU', number: 62, clue: '"Much ___ about Nothing" ("Simpsons" episode)'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'BERNIE', number: 63, clue: 'Dead boss in an \'80s film franchise'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'EXPO', number: 64, clue: 'Boat show, e.g.'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'NOS', number: 65, clue: 'Declinations'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ASSENT', number: 66, clue: 'Approval'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'DYES', number: 67, clue: 'Hides grey, say'))
clues_Painless_Solutions_CR_2_1_07.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'OTT', number: 68, clue: 'Slugger in a stamp series, along with Mantle, Greenberg, and Campanella'))
Puzzle.create(title: 'Painless Solutions', grid: 'BBQ.TATA.RIFLES|ICU.VERB.ENERGY|LEA.PROS.SAMOAN|BLINGINTHEWIND.|OLDE...ACTED...|...RETAIL..OPAL|HARDDEAN.LAMAZE|AGO.ISA.TUX.SUE|NEVAEH.PILLTALK|DREI..LEELEE...|...RADAR...LPGA|.YELLJOURNALISM|AVAILS.SOON.APU|BERNIE.EXPO.NOS|ASSENT.DYES.OTT', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/2/1', entries: clues_Painless_Solutions_CR_2_1_07)
