clues_Seesaw_Snacks_CR_8_2_07 = Array.new
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'NAL', number: 1, clue: 'Paperback publisher owned by Penguin: Abbr.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'NAUSEA', number: 1, clue: 'Cruise ship malady'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALFALFA', number: 2, clue: 'Healthy sprout'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LAOTIAN', number: 3, clue: 'One with galangal in the fridge, perhaps'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'THC', number: 4, clue: 'Joint component: Abbr.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'THOU', number: 4, clue: 'Start of a Commandment'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'HEFT', number: 5, clue: 'Clout'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CPU', number: 6, clue: 'Digital "brain," briefly'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'NASTIER', number: 7, clue: 'More mean'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NEWKID', number: 7, clue: 'Donnie Wahlberg, once'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'AXIOM', number: 8, clue: '"He who laughs last..." et al.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SCENT', number: 9, clue: 'Hound\'s trail'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TENAM', number: 10, clue: 'Midmorning'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ILE', number: 11, clue: 'Spot in the Seine'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'EAR', number: 12, clue: 'A friend may lend one'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'RTS', number: 13, clue: 'ACLU concerns: Abbr.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALA', number: 14, clue: 'Chicken ___ King'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'HEP', number: 15, clue: 'In, back in the day'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'EXCELAT', number: 16, clue: 'Do very well in'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UFOTOFU', number: 17, clue: 'Curd from beyond?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'TOASTER', number: 18, clue: 'Appliance with a darkness setting'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 3, col: 9, dir: 'Across', answer: 'WIENERS', number: 19, clue: 'Nerds'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SATOUT', number: 20, clue: 'Elected not to run, say'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'KONA', number: 21, clue: 'Hawaiian coffee district'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ELIA', number: 22, clue: '"On the Waterfront" director Kazan'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'KLIMTMILK', number: 23, clue: 'What Gustav drank while painting Adele Bloch-Bauer?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'KOOL', number: 23, clue: 'Newport rival'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'LEGOSET', number: 24, clue: 'The makings of a toy city, say'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'ICE', number: 25, clue: 'Cubes in a bar'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'LOS', number: 26, clue: 'Article in El Mundo?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'KEY', number: 27, clue: 'Crucial'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'AFAST', number: 28, clue: 'Pull ___ one'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'TIVO', number: 29, clue: 'Heavy viewer\'s aid'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'OED', number: 30, clue: 'Definitive source for linguists: Abbr.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'COE', number: 31, clue: 'College in Cedar Rapids, Iowa'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'ANTIFOG', number: 32, clue: 'Agent on swimming goggles'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'FIN', number: 33, clue: 'The last word in many a foreign film'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'CUTESY', number: 34, clue: 'Like www.catsinsinks.com'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'CID', number: 34, clue: 'El ___ (Spanish hero)'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'UVEA', number: 35, clue: 'Eye layer'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'TEARERS', number: 36, clue: 'Ushers, by trade'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'EVILOLIVE', number: 37, clue: 'Fiend in a martini?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'LIDS', number: 38, clue: 'Toppers'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LEBRON', number: 39, clue: '"King James" of the NBA'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'LPS', number: 39, clue: 'Crate-digger\'s purchases'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'EAT', number: 40, clue: 'Put away, so to speak'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'BTU', number: 41, clue: 'AC fig.'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'SIDEARM', number: 42, clue: 'Pistol, possibly'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'RELAPSE', number: 43, clue: 'Fall off the wagon again'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'MALWARE', number: 44, clue: 'Contaminating download'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'PAT', number: 45, clue: 'Touch, as the bunny in a kid\'s book'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'QED', number: 46, clue: 'Thus, in proofs'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'QUICHE', number: 46, clue: 'Breakfast pie'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'AREAS', number: 47, clue: 'Fields'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'SALMON', number: 48, clue: 'Fish sometimes baked into 46-Down'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'STUNTNUTS', number: 49, clue: 'Cashews used in action films?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'NEMEA', number: 50, clue: 'Site of a Herculean battle'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'TRAIT', number: 51, clue: 'Something bred for'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'NEIGH', number: 52, clue: '[Please feed me hay]'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'ELLA', number: 53, clue: 'First name in scat'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'EREI', number: 54, clue: 'Words in the middle of a noted palindrome'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'SCRAWL', number: 55, clue: 'Jot (down)'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'SAME', number: 55, clue: 'Matching'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'CPAS', number: 56, clue: 'Calculating pros'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ARAMAIC', number: 57, clue: '"The Passion of the Christ" language'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ARS', number: 57, clue: 'Pirate speech disfluencies'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'RAH', number: 58, clue: '"Yay, home team!"'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'ALE', number: 59, clue: 'Bloomsday beverage'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'MAPSPAM', number: 60, clue: 'Canned lunch meat for cartographers?'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'MUY', number: 60, clue: 'Quite, in Quito'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'RALEIGH', number: 61, clue: 'John Edwards\' hometown'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'UMA', number: 62, clue: 'Ex of Ethan and Quentin'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'SRO', number: 63, clue: 'Sign outside a B\'way hit'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SHEATHE', number: 64, clue: 'Put away, as a sword'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'YES', number: 65, clue: 'Last word in "Ulysses"'))
clues_Seesaw_Snacks_CR_8_2_07.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'EEN', number: 66, clue: 'Night, in verse'))
Puzzle.create(title: 'Seesaw Snacks', grid: 'NAL.THC.NASTIER|ALA.HEP.EXCELAT|UFOTOFU.WIENERS|SATOUT..KONA...|ELIA..KLIMTMILK|AFAST.OED...COE|.ANTIFOG.CUTESY|...EVILOLIVE...|LEBRON.SIDEARM.|PAT...QED.AREAS|STUNTNUTS..ELLA|...EREI..SCRAWL|ARAMAIC.MAPSPAM|RALEIGH.UMA.SRO|SHEATHE.YES.EEN', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/8/2', entries: clues_Seesaw_Snacks_CR_8_2_07)
