clues_The_Brand_Wagon_CR_3_15_07 = Array.new
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MARX', number: 1, clue: 'Big name in communism and comedy'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MEG', number: 1, clue: 'Ryan of film'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AXE', number: 2, clue: 'Fire'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RAN', number: 3, clue: 'Sought a Senate seat, say'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'XMEN', number: 4, clue: 'Comic book mutants'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'QANDA', number: 5, clue: 'Follow-up session?'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'QTIPS', number: 5, clue: '*Canal cleaners trademarked by Unilever'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ARCED', number: 6, clue: 'Like rainbows and eyebrows'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NOIT', number: 7, clue: '"Oh, ___\'s Devo!" (1982 LP)'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DUDS', number: 8, clue: 'Independence Day disappointments'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ATE', number: 9, clue: 'Filled up'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SITH', number: 10, clue: '"Star Wars Episode III: Revenge of the ____"'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SACRO', number: 10, clue: 'Prefix with iliac'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'IPHONE', number: 11, clue: 'Highly anticipated product with a June, 2007 release'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TIEDYE', number: 12, clue: 'Threads for the Dead?'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HEROIN', number: 13, clue: '*Pain-reliever once trademarked by Bayer (slogan: "The sedative for coughs")'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EXAM', number: 14, clue: 'Final'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'TROUT', number: 15, clue: 'Brook catch'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'APIE', number: 16, clue: '"...baked in ___"'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GENERICIDE', number: 17, clue: '"The process by which trademark rights are diminished or lost as a result of common use in the marketplace" - Wikipedia'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ROLEN', number: 18, clue: '2006 World Series star Scott'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'CHER', number: 19, clue: 'The #1 greatest thing about being gay, according to Bravo'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'NOPETS', number: 20, clue: 'Lease restriction'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'FRODO', number: 21, clue: 'Ringbearer of fiction and film'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'FOTO', number: 21, clue: 'Pic, in adspeak'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'JIB', number: 22, clue: 'Forward sail'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'JEST', number: 22, clue: 'Fun'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ICEE', number: 23, clue: 'Slurpee alternative'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'BOER', number: 24, clue: 'Transvaal native'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'LSD', number: 25, clue: 'Drug banned in the U.S. in 1967'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'SOONYI', number: 26, clue: 'Woody\'s wife'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'SIDEA', number: 26, clue: 'Hit half'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ECOLE', number: 27, clue: 'Le Cordon Bleu or La Sorbonne'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'LIMB', number: 28, clue: 'An arm or a leg'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'KNIT', number: 29, clue: 'Word after cable or jersey'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'KYOTO', number: 29, clue: 'Site of a noted environmental treaty'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'NETH', number: 30, clue: 'Tolerant EU member'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'EEN', number: 31, clue: 'Cant end'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SEEINGEYEDOG', number: 32, clue: '*Trademarked name for the product of a Morristown, New Jersey animal training program'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'GWENN', number: 33, clue: '"Miracle on 34th Street" Oscar winner Edmund'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ERAS', number: 34, clue: 'Periods'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'GAYE', number: 35, clue: '"Inner City Blues" musician'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TERM', number: 36, clue: 'Incumbency'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'WROTE', number: 37, clue: 'Kept in touch, in a way'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'AERO', number: 38, clue: 'Bubble-filled bar by Nestl&#233;'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'EZRA', number: 39, clue: 'Pound of meter'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'REID', number: 40, clue: 'Majority Leader after Frist'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'OREO', number: 41, clue: 'Lunchbag treat'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'BREATHALYZER', number: 42, clue: '*Highway patrol device once trademarked by Smith and Wesson'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'RIOS', number: 43, clue: 'Spanish bodies'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'LEGOF', number: 44, clue: '___ lamb'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ZAP', number: 45, clue: 'Nuke'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'ZIPPER', number: 45, clue: 'Clothes closer once trademarked by B.F. Goodrich'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ARRIVE', number: 46, clue: 'Hit the big time'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'POISED', number: 47, clue: 'Unflappable'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'INSO', number: 48, clue: 'Words before "many words"'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'EERIE', number: 49, clue: 'Freaky'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IRONON', number: 50, clue: 'Attach, as some patches'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'NEARS', number: 51, clue: 'Gets warmer, in a way'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'AVG', number: 52, clue: 'Spring training fig.'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ARSON', number: 52, clue: 'Result of foul match play'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'VHONE', number: 53, clue: '"I Love the \'90s: Part Deux" airer'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'ADO', number: 54, clue: 'Fuss'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'PRIES', number: 55, clue: 'Butts in'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'BARHOP', number: 56, clue: 'Get shots all over?'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'BALI', number: 56, clue: 'Indonesian vacation isle'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'AWOL', number: 57, clue: 'Missing from the military'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'PLOD', number: 58, clue: 'Trudge'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PISA', number: 59, clue: 'Galileo Airport city'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'JAWSOFLIFE', number: 60, clue: '*Vehicular rescue device trademarked by Hale Products'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'JAM', number: 60, clue: 'Undirected session'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'IRK', number: 61, clue: 'Get to'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'FAN', number: 62, clue: 'Backer'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'ELY', number: 63, clue: 'England\'s Isle of ___'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EVER', number: 64, clue: 'At any time'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ALOON', number: 65, clue: 'Crazy as ___'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ORAL', number: 66, clue: 'Certain fixation'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REDS', number: 67, clue: 'Ohio club with a spring training facility in Sarasota'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'MILNE', number: 68, clue: 'Alan Alexander, whose son was named Christopher Robin'))
clues_The_Brand_Wagon_CR_3_15_07.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'DKNY', number: 69, clue: 'Jeans label from Donna'))
Puzzle.create(title: 'The Brand Wagon', grid: 'MARX.QANDA.SITH|EXAM.TROUT.APIE|GENERICIDE.CHER|...NOPETS.FRODO|JIB.LSD..SOONYI|ECOLE..KNIT.EEN|SEEINGEYEDOG...|TERM.WROTE.AERO|...BREATHALYZER|ZAP.INSO..EERIE|IRONON..AVG.ADO|PRIES.BARHOP...|PISA.JAWSOFLIFE|EVER.ALOON.ORAL|REDS.MILNE.DKNY', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/3/15', entries: clues_The_Brand_Wagon_CR_3_15_07)
