clues_The_JBs_CR_1_11_07 = Array.new
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PALPS', number: 1, clue: 'Insect feelers'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PAJAMA', number: 1, clue: 'Kind of party'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ATONES', number: 2, clue: 'Observes Yom Kippur'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LENDEE', number: 3, clue: 'Borrower'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PUBERTY', number: 4, clue: 'You change when you hit it'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SPORK', number: 5, clue: 'Hybrid utensil'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'RATON', number: 6, clue: 'Boca ___'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RPG', number: 6, clue: 'Dungeons & Dragons, e.g.: Abbr.'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALIG', number: 7, clue: 'HBO character'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TAOS', number: 8, clue: 'New Mexico art community'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'OYVEY', number: 9, clue: '"Leaving Brooklyn: ___!" (sign on the Williamsburg Bridge)'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NAIVE', number: 10, clue: 'Green'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'JLO', number: 11, clue: 'Pop star releasing her first Spanish language record this year, familiarly'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'JOANBAEZ', number: 11, clue: 'Woodstock performer who dated Bob Dylan'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LAD', number: 12, clue: 'Schoolboy'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'OKS', number: 13, clue: 'Permits'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ATEUP', number: 14, clue: 'Consumed hungrily'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'PLAYA', number: 15, clue: 'Pick-up artist, slangily'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'OAK', number: 16, clue: 'Common street name'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'JONBONGIOVI', number: 17, clue: 'New Jersey rock star, at birth'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'NSA', number: 18, clue: 'Personals shorthand for casual romance'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ADS', number: 19, clue: 'Product placements, e.g.'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ANDERS', number: 20, clue: 'Celsius of the Celsius scale'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'GSEVEN', number: 21, clue: 'Powerful economic coalition, before Russia joined'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ESS', number: 22, clue: 'Superman\'s symbol'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'MEERKAT', number: 23, clue: 'Southern African mammal that stands sentry'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'THEKID', number: 24, clue: 'Sobriquet for William H. Bonney'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'YESBUT', number: 25, clue: '"Good point, however..."'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'UGLI', number: 26, clue: 'Trademarked fruit name'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'TEMP', number: 27, clue: 'Impermanent staffer'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ASET', number: 28, clue: '"I hate to break up __"'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'HOG', number: 29, clue: 'Harley'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'OMENS', number: 30, clue: 'Dark clouds, perhaps'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'GIBSON', number: 31, clue: 'Guitar played by Jimmy Page'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'SAGE', number: 32, clue: 'Wise guy'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'YOSEMITE', number: 33, clue: '___ Sam'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'OJS', number: 34, clue: 'Breakfast quaffs, briefly'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'SUP', number: 35, clue: 'Eat in the eve'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'TOT', number: 36, clue: 'Brand new walker, maybe'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'EXE', number: 37, clue: 'Common PC file extension'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ELM', number: 38, clue: 'Common street name'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TAJ', number: 39, clue: 'Atlantic City casino, casually, with "The"'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'TARO', number: 39, clue: 'Luau leaf'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'APEX', number: 40, clue: 'Summit'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'JEFFBECK', number: 41, clue: 'Yardbirds member'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'JUKEBOX', number: 42, clue: 'Bar fixture'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ZIP', number: 43, clue: 'Energy'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'APE', number: 44, clue: 'Make like'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'SPINSTER', number: 45, clue: 'Bachelorette, pejoratively'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'RADIATE', number: 46, clue: 'Give off'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'REFS', number: 47, clue: 'Cries foul?'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'SOL', number: 48, clue: 'Spanish lighter'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'DSO', number: 49, clue: 'British mil. honor'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'ARIA', number: 50, clue: 'Oratorio solo'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'REDFIN', number: 51, clue: 'Freshwater minnow'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'IAGREE', number: 52, clue: '"Totally!"'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ALEAST', number: 53, clue: 'Baseball division won by the same team for the past nine years'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'OXFORD', number: 54, clue: 'Where Clinton didn\'t inhale'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'RAJAS', number: 55, clue: 'Indian nobility'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'DRECK', number: 56, clue: 'Garbage'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'NEWDEAL', number: 57, clue: 'Program that launched the NRA'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'EBB', number: 58, clue: 'Partner of flow'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'WRIST', number: 59, clue: 'Watch part?'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'BLARES', number: 60, clue: 'Cranks the volume'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'ELHI', number: 61, clue: 'K-12'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SLED', number: 62, clue: 'Iditarod conveyance'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'BRIDGE', number: 63, clue: 'Way over'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BYE', number: 64, clue: 'Early-round pass'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'BMW', number: 64, clue: 'Z3 maker'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'YAO', number: 65, clue: 'Rocket from China'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'JELLOBIAFRA', number: 66, clue: 'Alternative Tentacles co-founder'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ODS', number: 67, clue: 'Takes too much'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MAC', number: 68, clue: 'It\'s big in fast food'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ACHED', number: 69, clue: 'Felt the results of a run'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'STIES', number: 70, clue: 'Filthy quarters'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'WOK', number: 71, clue: 'Moo goo gai pan pan'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SKIDS', number: 72, clue: 'Loses traction'))
clues_The_JBs_CR_1_11_07.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'TENET', number: 73, clue: 'Creed'))
Puzzle.create(title: 'The JBs (Dedicated to JB)', grid: 'PALPS.RATON.JLO|ATEUP.PLAYA.OAK|JONBONGIOVI.ADS|ANDERS.GSEVEN..|MEERKAT..YESBUT|ASET..HOG..SAGE|...YOSEMITE.ELM|TAJ.JUKEBOX.ZIP|APE.SPINSTER...|REFS..DSO..ARIA|OXFORD..NEWDEAL|..BLARES.BRIDGE|BYE.JELLOBIAFRA|MAC.ACHED.STIES|WOK.SKIDS.TENET', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2007/1/11', entries: clues_The_JBs_CR_1_11_07)
