clues_mgwcc104_unscrambled = Array.new
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ABBA', number: 1, clue: 'Band of "Gold"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'APPS', number: 1, clue: 'PDA purchases'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'BERT', number: 2, clue: 'Puppet with a striped shirt'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BAIR', number: 3, clue: 'FDIC chairman Sheila'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ASSISTS', number: 4, clue: 'Steve Nash specializes in them'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'TIPOFF', number: 5, clue: 'Battle between centers'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TEN', number: 5, clue: 'Bedtime, for some'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'INGOT', number: 6, clue: 'Bar from the foundry'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'PTUI', number: 7, clue: 'Spitting sound'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ORALB', number: 8, clue: 'Satin Floss maker'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'FER', number: 9, clue: 'Pro in the sticks'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'FEDORA', number: 10, clue: 'It\'s on top of Indiana'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'USC', number: 11, clue: 'Tommy Trojan\'s home'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'UNSCALABLE', number: 11, clue: 'Like the jail walls represented by the four clusters of black squares in the middle of this grid'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SEOUL', number: 12, clue: 'Peninsular metropolis'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'CONES', number: 13, clue: 'They\'ve got the scoop'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PEAS', number: 14, clue: 'Green spheres'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ENTREE', number: 15, clue: 'Major course'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'NEO', number: 16, clue: 'Prefix with pagan'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PRISONGUARD', number: 17, clue: 'Each of the four H\'s in this grid represents one'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'OPEC', number: 18, clue: 'Lands with reserves, for short'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'SON', number: 19, clue: 'Primogeniture beneficiary'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'STRIP', number: 20, clue: 'Lose at poker, perhaps'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'OIL', number: 21, clue: 'Baby or peanut'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'ONCUE', number: 22, clue: 'At the right time'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'NILE', number: 23, clue: 'Desert flower?'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'SEAT', number: 24, clue: 'One of 535 in Congress'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'AHA', number: 25, clue: '"Eureka!"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'BURIALS', number: 26, clue: 'Solemn occasions'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'UHR', number: 27, clue: 'Cologne clock'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BLOTCH', number: 28, clue: 'Irregular mark'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BOIL', number: 28, clue: 'Purify, perhaps'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'LORE', number: 29, clue: 'Oft-told tales'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'OPENSESAME', number: 30, clue: 'Words that may work on some closed doors, but not the ones in this jail'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'HALL', number: 31, clue: 'Pool place'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OOPS', number: 32, clue: 'Word heard before "thud"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ARDOR', number: 33, clue: 'Fire'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'RYA', number: 34, clue: 'Kind of rug popular in the 1970s'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'DOG', number: 35, clue: 'Corgi or collie'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'OUI', number: 36, clue: 'Approval in Annecy'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'EASY', number: 37, clue: 'Not a problem'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'SEAR', number: 38, clue: 'Prepare tuna, maybe'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'YAPS', number: 39, clue: 'Won\'t remain silent'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IRE', number: 40, clue: 'Furor'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'YOU', number: 41, clue: 'Identity of the inmate -- or what the inmate must use to escape this mayhem, in a way'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'BEA', number: 42, clue: 'Arthur who died in 2009'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LENN', number: 43, clue: '___ Sakata (member of the Orioles\' World Series-winning team of 1983)'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'NOEL', number: 44, clue: '2004 Susan Sarandon movie set on Christmas Eve'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'TAGID', number: 45, clue: 'Proof you\'re who you say you are, often worn on the shirt (note: this term is usually seen with its two parts in reverse order from what I use here)'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'THE', number: 45, clue: 'Article in Martha Stewart Living'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'DHL', number: 46, clue: 'FedEx rival'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'SLAP', number: 47, clue: 'Hit'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'STRIKES', number: 47, clue: 'They\'re in the zone'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'SOPH', number: 48, clue: 'Certain teenager, casually'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'PRAISE', number: 49, clue: 'Place on a pedestal'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'HATERS', number: 50, clue: 'Dissing crowd'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'AURA', number: 51, clue: 'Glow'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'STEERED', number: 52, clue: 'Chose where to go'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'STAGS', number: 52, clue: 'Men without women'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'TEVYE', number: 53, clue: 'He asks "Would it spoil some vast eternal plan if I were a wealthy man?"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'DROVE', number: 54, clue: 'Forced'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SLUR', number: 55, clue: 'Cruel name'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SITON', number: 55, clue: 'Squash'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TESLA', number: 56, clue: 'Preceder of coil or principle'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'ROI', number: 57, clue: 'Haitian king'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ONEU', number: 58, clue: 'Prince song "The ___ Wanna C"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'RINKS', number: 59, clue: 'Forwards check there'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'NEUN', number: 60, clue: 'Sechs upside-down'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'KIWI', number: 61, clue: 'Certain Pacific Islander'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'STEP', number: 62, clue: 'By remarriage, usually'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AVA', number: 63, clue: 'Palindromic "Nip/Tuck" character'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'IWONTTAKEIT', number: 64, clue: 'What any 17-across will say if the inmate attempts to escape by bribing them'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'WAX', number: 65, clue: 'Candelabra detritus'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'TNT', number: 66, clue: 'Potent compound'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GYM', number: 67, clue: 'Class to change for'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'SAVEON', number: 68, clue: 'Fail to overspend for'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'EUWE', number: 69, clue: 'Max ___ (Dutchman who was World Chess Champion from 1935-37)'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SEE', number: 70, clue: '"Get it now?"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'EXEUNT', number: 71, clue: 'Latin for "they leave"'))
clues_mgwcc104_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SNIP', number: 72, clue: 'Cut out'))
Puzzle.create(title: 'MGWCC #104 - "Jailbreak"', grid: 'ABBA.TIPOFF.USC|PEAS.ENTREE.NEO|PRISONGUARD.SON|STRIP.OIL.ONCUE|...SEAT.BURIALS|BLOTCH...HALL..|OOPS.ARDOR.EASY|IRE...YOU...BEA|LENN.TAGID.SLAP|..SOPH...HATERS|STEERED.SLUR...|TESLA.ROI.RINKS|AVA.IWONTTAKEIT|GYM.SAVEON.EUWE|SEE.EXEUNT.SNIP', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/6/11', entries: clues_mgwcc104_unscrambled)
