clues_mgwcc108_unscrambled = Array.new
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DEEPER', number: 1, clue: 'More zen'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DOFOR', number: 1, clue: 'Perform on behalf of'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ERUPT', number: 2, clue: 'Go ballistic'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ENNIS', number: 3, clue: 'Bill Cosby\'s late son'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PEQE', number: 4, clue: '___ implant'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ERY', number: 5, clue: 'Bind or brew suffix'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RYE', number: 6, clue: 'Powerful shot'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'MOBS', number: 7, clue: 'They rule an ochlocracy'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'MOOD', number: 7, clue: 'State'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'OPUS', number: 8, clue: 'Nice work'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'BEGET', number: 9, clue: 'Have'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SCHLEP', number: 10, clue: 'Convey with difficulty'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BOG', number: 11, clue: 'Cranberry environs'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BIKIQINES', number: 11, clue: 'Demarcations of private areas on women\'s bodies'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ODELL', number: 12, clue: '"Island of the Blue Dolphins" author Scott'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'GAYLE', number: 13, clue: 'Crystal made in Kentucky'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ORNERY', number: 14, clue: 'Hard to handle'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'OPEC', number: 15, clue: 'Org. Indonesia left in 2008'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'IDA', number: 16, clue: 'Moscow\'s land: abbr.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'FUNQYENOUGH', number: 17, clue: '"You might not believe this, but..."'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'NEAL', number: 18, clue: 'Radio host Boortz'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'KEY', number: 19, clue: 'Cedar ___, Fla.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'OPIE', number: 20, clue: '"___ and the Bully" ("The Andy Griffith Show" episode)'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'EDSEL', number: 21, clue: 'Abhorred Ford'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ILL', number: 22, clue: 'Lying in bed, perhaps'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'RTS', number: 23, clue: 'Some Texans and Patriots: abbr.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'QLA', number: 24, clue: '___ Wafers'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'QES', number: 24, clue: 'Role for which David won four Emmys'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'LEAVE', number: 25, clue: 'Time off'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'TENQLE', number: 26, clue: 'Half a 1970s duo'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'NAGSAT', number: 27, clue: 'Bothers persistently'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'FEELME', number: 28, clue: 'Part of Tommy\'s plea'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'FARADS', number: 28, clue: 'Units named for an Englishman'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'MAQOW', number: 29, clue: 'He didn\'t write "I Write the Songs"'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ELL', number: 30, clue: 'Wing'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'PAI', number: 31, clue: '___ gow'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MICASA', number: 32, clue: 'My house in Mexico'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'MOM', number: 32, clue: 'Child\'s shout'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'IMA', number: 33, clue: 'Black Eyed Peas tune "___ Bee"'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'CAQOOKNOW', number: 34, clue: 'Question from someone covering their eyes'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'ALT', number: 35, clue: '___-country music'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'TAPON', number: 36, clue: 'Hit a bit'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'GNAW', number: 37, clue: 'Work over with the molars'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'AQE', number: 38, clue: 'Like certain seniors'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'WES', number: 39, clue: 'Unseld under the basket'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'OMAR', number: 40, clue: 'He co-starred with Val in "Top Secret!"'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'VAQLA', number: 41, clue: 'Scoop selection'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'AGT', number: 42, clue: 'Officer: abbr.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'SEQE', number: 43, clue: 'Forgetting a lot, say'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MAQA', number: 44, clue: 'City called "The Pearl of the Orient"'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'EGO', number: 45, clue: 'Driving force'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'PHASES', number: 46, clue: 'Moon periods'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'HUE', number: 47, clue: 'Shade'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'ODD', number: 48, clue: 'As one is'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'DETEST', number: 49, clue: 'Be unable to stand'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'TWOOUT', number: 50, clue: 'Kind of single, double, triple or home run'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ONEQ', number: 51, clue: 'Score of the USA\'s win over Algeria on Wednesday'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CLOSED', number: 52, clue: 'Store sign'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'CORPS', number: 52, clue: 'Cohesive group'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'LAURA', number: 53, clue: 'Wilder out on the prairie'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'DELTA', number: 54, clue: 'Northwest Mississippi region'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'NNE', number: 55, clue: 'Up and over a bit: abbr.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'MAP', number: 56, clue: 'Plot'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'MAORI', number: 56, clue: 'Traditional tattooer'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ARIEL', number: 57, clue: 'Beloved mermaid'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'PASSE', number: 58, clue: 'Used by the behind-the-times'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'OAK', number: 59, clue: 'Table makeup, sometimes'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'TEASE', number: 60, clue: 'Ridicule'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'AGOG', number: 61, clue: 'Very interested'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SIPS', number: 62, clue: 'Has a bit of'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'KARA', number: 63, clue: '___ Sea (arm of the Arctic Ocean)'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'KNOX', number: 63, clue: 'Between James and Polk'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RUN', number: 64, clue: 'Head for the tape'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'ELGIQLINOIS', number: 65, clue: 'Chicago suburb'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'LAS', number: 66, clue: '___ Animas County, Colo.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'IZE', number: 67, clue: 'Material finish'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PRO', number: 68, clue: 'Favoring'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'STOP', number: 69, clue: 'Desist'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'AZORES', number: 70, clue: 'Portuguese-speaking archipelago'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SAW', number: 71, clue: 'Cut some cherry, e.g.'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'TAGS', number: 72, clue: 'Price holder'))
clues_mgwcc108_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'SEXILE', number: 73, clue: 'State of being forbidden to enter one\'s own dorm room due to one\'s roommate being engaged in romantic activity therein'))
Puzzle.create(title: 'MGWCC #108 - "I Have Zero Interest in the World Cup"', grid: 'DEEPER.MOBS.BOG|ORNERY.OPEC.IDA|FUNQYENOUGH.KEY|OPIE..EDSEL.ILL|RTS.QLA..TENQLE|...FEELME.PAI..|MICASA.ALT.GNAW|OMAR.VAQLA.SEQE|MAQA.EGO.PHASES|..ODD.TWOOUT...|CLOSED..NNE.MAP|OAK.TEASE..KARA|RUN.ELGIQLINOIS|PRO.STOP.AZORES|SAW.TAGS.SEXILE', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/7/9', entries: clues_mgwcc108_unscrambled)
