clues_mgwcc109_unscrambled = Array.new
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SABRA', number: 1, clue: 'Native-born Israeli'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SAYS', number: 1, clue: 'Verbalizes'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ADEN', number: 2, clue: 'Crucial city during 46-across'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BILLYBUDD', number: 3, clue: 'Unfinished Melville work'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'REL', number: 4, clue: 'Cathol., e.g.'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ATOLLS', number: 5, clue: 'Coral rings'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CAROL', number: 6, clue: 'Funny Burnett'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CACTI', number: 6, clue: 'Prickly plants'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AHERN', number: 7, clue: 'Bertie ___, Ireland\'s prime minister (1997-2008)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'RODEO', number: 8, clue: 'Where some clowns work'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ORA', number: 9, clue: '"___ et labora"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'LARGESSE', number: 10, clue: 'Financial generosity'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ASS', number: 11, clue: 'Behind, crassly'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ALGAE', number: 11, clue: 'Green gunk'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SAUNA', number: 12, clue: 'Helsinki hothouse'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SONAR', number: 13, clue: 'Sub equipment'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ADIET', number: 14, clue: 'On ___ (slimming down)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'AHORA', number: 15, clue: 'Now, to Nicaraguans'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'LAO', number: 16, clue: 'Language spoken in Luang Prabang'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'YELLOWCEDAR', number: 17, clue: 'Alaskan tree'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'WIL', number: 18, clue: 'Wheaton of "Stand By Me"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'GUN', number: 19, clue: 'Rev'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SNL', number: 20, clue: 'Will Forte\'s show, for short'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'LITRE', number: 21, clue: 'Petrol amount'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'GHANA', number: 22, clue: 'Country that knocked the U.S. out of the 2010 World Cup (and is going to get knocked out themselves this afternoon, I hope)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'HST', number: 23, clue: 'Nuclear bomb-dropping prez'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'YELLINONESEAR', number: 24, clue: 'Shriek at a person'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'EYED', number: 25, clue: 'Blue-___ soul (music genre)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'NOAHS', number: 26, clue: '___ Ark'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BABYS', number: 27, clue: '"___ in Black" (Beatles song)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BAMA', number: 27, clue: '2010 college football champs'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AGIN', number: 28, clue: 'Opposing, in dialect'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'OST', number: 29, clue: 'Word before "mark" or "Deutschland"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AGUE', number: 30, clue: 'Fit of fever'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'LHASAS', number: 31, clue: 'Shaggy little dogs, casually'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'LEDUC', number: 31, clue: '___ Tho (Nobel Peace Prize decliner, 1973)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'HOD', number: 32, clue: 'Brick carrier'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'AFI', number: 33, clue: 'Org. that produces top 100 movie lists'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'STE', number: 34, clue: '___ Genevieve, Mo.'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'TNT', number: 35, clue: 'Its middle initial stands for "nitro"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'TENORCLEF', number: 35, clue: 'Sheet music mark'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'NATO', number: 36, clue: 'Its HQ is in Brussels'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'TROT', number: 37, clue: 'With "out," bring up tiresomely'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MIDDLEOFTHEYEAR', number: 38, clue: 'What the publication instant of this puzzle is (July 2nd, noon)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'LEONTYNE', number: 39, clue: 'Price on some opera tickets'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'YUMA', number: 40, clue: 'Arizona county'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'AND', number: 41, clue: '"What else?"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'EDDIES', number: 42, clue: 'Swirling pools'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'UNTO', number: 43, clue: 'Golden Rule preposition'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'LOU', number: 44, clue: 'Gymnast Mary ___ Retton'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'LES', number: 44, clue: 'The, to Thierry'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'SMOOT', number: 45, clue: '1930\'s infamous ___-Hawley Tariff Act'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'SWOOSH', number: 45, clue: 'Nike\'s logo'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'YEMENCIVILWAR', number: 46, clue: 'Current conflict on the Arabian Peninsula'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'YEATS', number: 46, clue: 'First Irish writer to win the Nobel Prize'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'EXCOP', number: 47, clue: 'Former member of the police force'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'MISTY', number: 48, clue: 'Song Cliff Clavin sang to Diane Chambers in a misguided attempt at seduction'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'INNIT', number: 49, clue: '"Don\'t you agree?" in Cockney dialect'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'VOTRE', number: 50, clue: 'Your, in Tours'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ITOSS', number: 51, clue: '"___ and turn..." (Soft Cell lyric)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'LSD', number: 52, clue: 'Trippy tab'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EXIST', number: 53, clue: 'Be'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'NOTSO', number: 54, clue: '"That\'s false!"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'CCX', number: 55, clue: '210'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'CANT', number: 56, clue: 'Doesn\'t have the power to'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'XRAY', number: 57, clue: 'A look inside'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ACS', number: 58, clue: 'Cooling units, for short'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'YENTODOLLAR', number: 59, clue: 'Like many currency conversions at San Francisco Airport'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'EOS', number: 60, clue: 'Greek for "dawn"'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'LIE', number: 61, clue: 'Say you did when you didn\'t'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TOT', number: 62, clue: 'Wee one'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'NOIRS', number: 63, clue: 'Pinot ___ (red wines)'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'SIENA', number: 64, clue: 'Historic city of Tuscany'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SPY', number: 65, clue: 'Cloak and dagger type'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ESTES', number: 66, clue: '"Crosswords for a Rainy Day" author Harvey'))
clues_mgwcc109_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'HEFTY', number: 67, clue: 'Trash bag brand'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #109 - "Half Day"', grid: 'SABRA.CAROL.ASS|ADIET.AHORA.LAO|YELLOWCEDAR.GUN|SNL.LITRE.GHANA|..YELLINONESEAR|BABYS....OST...|AGUE.LHASAS.TNT|MIDDLEOFTHEYEAR|AND.EDDIES.UNTO|...LOU....SMOOT|YEMENCIVILWAR..|EXIST.NOTSO.CCX|ACS.YENTODOLLAR|TOT.NOIRS.SIENA|SPY.ESTES.HEFTY', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/7/16', entries: clues_mgwcc109_unscrambled, instructions: instructions, explanation: explanation)
