clues_mgwcc112_unscrambled = Array.new
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'NEBO', number: 1, clue: 'Mount ___ (where Moses died)'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'NOTED', number: 1, clue: '"So ___"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EPODE', number: 2, clue: 'Part of a poem'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BEGOF', number: 3, clue: 'Implore'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ONE', number: 4, clue: 'Indivisibly interconnected'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'VCR', number: 5, clue: 'Taping tool'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'VETO', number: 5, clue: 'Nixing power'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CAHN', number: 6, clue: 'Four-time Oscar winner Sammy'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RTE', number: 7, clue: '10 or 95: abbr.'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'PENPAL', number: 8, clue: 'Writing partner'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PIERRE', number: 8, clue: 'Capital city named for a fur trader'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ESAU', number: 9, clue: 'Genesis first name'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'NORMAN', number: 10, clue: 'Cousins of the literati, once'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PLY', number: 11, clue: 'Word on packages of toilet paper'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ADO', number: 12, clue: '1-877-MUCH-___ (phone number of the American Shakespeare Center)'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'LEU', number: 13, clue: 'Currency the euro is scheduled to replace in 2014'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OPENSEAT', number: 14, clue: 'No one will hold it'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Down', answer: 'STREET', number: 15, clue: 'Sesame or Bourbon'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'ISOLDE', number: 16, clue: 'Wagnerian woman'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TOGETTHEYEARYOU', number: 17, clue: 'With 60-across, hint to the contest answer'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'YAPS', number: 18, clue: 'Isn\'t quiet'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EDO', number: 19, clue: 'Tokyo\'s ___ Castle'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'RON', number: 20, clue: 'Silver or Goldman'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'ARUM', number: 21, clue: 'Mediterranean plant'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DEFOE', number: 22, clue: 'Friday\'s creator'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'ODIN', number: 23, clue: 'Viking king'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'CPR', number: 24, clue: '15 compressions and two breaths, essentially'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'CANITRY', number: 24, clue: '"Let me do that"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'AJAX', number: 25, clue: 'Dutch soccer powerhouse'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'JETER', number: 26, clue: 'Man in pinstripes'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'AVERT', number: 27, clue: 'Sidestep'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'XAXES', number: 28, clue: 'Horizontal lines'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'DECEASE', number: 29, clue: 'Pass'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'CSI', number: 30, clue: 'Fox show on CBS'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'EID', number: 31, clue: 'Holiday on U.S. postage stamps'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'NEVA', number: 32, clue: 'St. Petersburg\'s river'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SPLITSIN', number: 33, clue: 'With 43-across, cleaves'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'SPICE', number: 33, clue: 'Ginger, say'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'PEROT', number: 34, clue: '85th-richest American in 2009, per "Forbes"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'LEANT', number: 35, clue: 'Didn\'t stand straight, in Surrey'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'TEX', number: 36, clue: 'S.E. Hinton title character'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PEEN', number: 37, clue: 'Hammerhead part'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'IDIOT', number: 38, clue: 'Fool'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'OWL', number: 39, clue: 'Hooters logo feature'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'TOO', number: 40, clue: 'Additionally'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'MERE', number: 41, clue: 'C.S. Lewis\'s "___ Christianity"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'MANX', number: 41, clue: 'European language whose last native speaker died in 1974'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'IRA', number: 42, clue: '"The Ballad of ___ Hayes"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'TWOPARTS', number: 43, clue: 'See 33-across'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'PREREQ', number: 44, clue: 'Univ. class, sometimes'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'CONJ', number: 45, clue: 'Nor or or or for for short'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'JUSTGO', number: 46, clue: '"I want you to leave"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'FORLORN', number: 47, clue: 'Close to hopeless'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'FAKERS', number: 47, clue: 'World Cup soccer players, all too often'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'OMIT', number: 48, clue: 'Keep out'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ETTU', number: 49, clue: 'Quisling-directed quip'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'AMY', number: 50, clue: 'Grant or Carter'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'EXAMS', number: 51, clue: 'Senior troubles'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'AREEL', number: 52, clue: 'Spinning'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'MINSK', number: 53, clue: 'City where Lee Harvey Oswald lived for 2 1/2 years'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SOTTO', number: 54, clue: 'Soft in Siena'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'SAKI', number: 55, clue: 'Burma-born author'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'AGES', number: 56, clue: 'Plenty of time'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ORR', number: 57, clue: 'Winner of eight Norris Trophies'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'OHOK', number: 57, clue: '"Now I see"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'RENE', number: 58, clue: 'Celine\'s husband/manager'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'RIO', number: 59, clue: 'Host after London'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MUSTGETTHEEVENT', number: 60, clue: 'See 17-across'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'MON', number: 60, clue: 'Jamaican gent'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'UNO', number: 61, clue: 'A small number of Mexicans'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'SAL', number: 62, clue: 'Bando of baseball'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'TCU', number: 63, clue: 'Fort Worth sch.'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'VUE', number: 64, clue: 'Saturn model'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ONAGER', number: 65, clue: 'Wild Asian ass'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'CONQUEST', number: 66, clue: 'Victory'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NOLOSS', number: 67, clue: '"Who cares?"'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'UKE', number: 68, clue: 'King David Kalakaua\'s musical passion, briefly'))
clues_mgwcc112_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ELKO', number: 69, clue: 'Huge Nevada county, or its seat'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #112 - "Willpower"', grid: 'NEBO.VCR.PENPAL|OPENSEAT.ISOLDE|TOGETTHEYEARYOU|EDO.RON.ARUM...|DEFOE..CPR.AJAX|...DECEASE.NEVA|SPLITSIN....TEX|PEEN.IDIOT.MERE|IRA....TWOPARTS|CONJ.FORLORN...|ETTU.AMY..EXAMS|...SAKI.ORR.RIO|MUSTGETTHEEVENT|ONAGER.CONQUEST|NOLOSS.UKE.ELKO', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/8/6', entries: clues_mgwcc112_unscrambled, instructions: instructions, explanation: explanation)
