clues_mgwcc114_unscrambled = Array.new
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PARA', number: 1, clue: '___ llevar (to go, in Mexican restaurants)'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PARADES', number: 1, clue: 'Street fun'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ABILENE', number: 2, clue: 'City where Eileen lives, in "All My Ex\'s Live in Texas"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'REVERSE', number: 3, clue: 'Uno card'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ATE', number: 4, clue: 'Consumed consomme'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'RAJAH', number: 5, clue: 'Indian chief'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RAMS', number: 5, clue: 'They left L.A.'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALOUD', number: 6, clue: 'So everyone can hear'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'JEU', number: 7, clue: 'Game, at the French Open'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ART', number: 8, clue: 'Museum pieces'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'HOHOHO', number: 9, clue: 'Christmas trio'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'WISH', number: 10, clue: '"As you ___"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'WOWS', number: 10, clue: 'Impresses greatly'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'INHUMAN', number: 11, clue: 'Cruel'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'STERILE', number: 12, clue: 'Like scalpels before surgery'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HOWELLS', number: 13, clue: '"Gilligan\'s Island" pair'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ABET', number: 14, clue: 'Help on a heist'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ALERO', number: 15, clue: 'Oldsmobile model'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ONTO', number: 16, clue: 'Not tricked by'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RIVERMOUTH', number: 17, clue: 'Delta area'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'RAYE', number: 18, clue: 'Mouthy Martha'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'WHEW', number: 19, clue: '"That was close!"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ALE', number: 20, clue: 'Samuel Adams Summer ___'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'ASU', number: 21, clue: 'Southwest sch.'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'OHSURE', number: 22, clue: 'Sarcastic statement of belief'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'HADJI', number: 23, clue: 'Pakistani pilgrim, perhaps'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DERBY', number: 24, clue: 'Word after Kentucky or roller'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'BUSTUP', number: 25, clue: 'Destroy, as a crime ring'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'DACHA', number: 26, clue: 'Russian vacation home'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'AGAINST', number: 27, clue: 'Fighting'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'COUNT', number: 28, clue: 'Dracula or Chocula'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'MIL', number: 29, clue: 'A thousand thou'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ENSUED', number: 30, clue: 'Went after'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'DEC', number: 31, clue: 'Last of a dozen: abbr.'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'GOODCALL', number: 32, clue: '"That\'s what I would have done, too"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'CANTOO', number: 33, clue: 'Half of a schoolyard back-and-forth'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SEES', number: 34, clue: 'Doesn\'t fold or raise'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ESAU', number: 35, clue: 'Ancient twin'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SKILL', number: 36, clue: 'Ability'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'JANES', number: 37, clue: 'Mary ___ (shoes)'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'TUCKINGIN', number: 38, clue: 'Preparing for sweet dreams'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'UTICA', number: 39, clue: 'New York\'s "Second Chance City"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'GOO', number: 40, clue: 'Gunk'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SCOUT', number: 41, clue: 'High school baseball game attendee, perhaps'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SPINACH', number: 41, clue: 'Chicken Florentine ingredient'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'COROLLA', number: 42, clue: 'Toyota hit'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'OPENAIR', number: 43, clue: 'Unbound by walls'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'INTO', number: 44, clue: 'Liking'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'THAW', number: 45, clue: 'Take out of the freezer'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'HOWDIDO', number: 46, clue: '"Was my performance acceptable?"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'ALLEVEN', number: 47, clue: 'Squared away'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'WESTEND', number: 48, clue: 'London\'s answer to Broadway'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'POPPILLS', number: 49, clue: 'Abuse a prescription, perhaps'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'LETWIN', number: 50, clue: 'Throw the game to'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'OTOOLE', number: 51, clue: 'Lawrence, in "Lawrence of Arabia"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'THEO', number: 52, clue: 'Cliff Huxtable\'s only son'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IRE', number: 53, clue: 'Hatred'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'CELTS', number: 54, clue: 'They once ruled much of Europe'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SPLAT', number: 55, clue: 'Smashing pumpkins sound'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'HOWLS', number: 56, clue: 'Bays at the moon'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'NONFAT', number: 57, clue: 'Like skim milk'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'FROM', number: 58, clue: 'Preposition on a present'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'PEE', number: 59, clue: 'Tinkle'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ETSY', number: 60, clue: 'Online store website'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'DET', number: 61, clue: 'The Tigers, on scoreboards'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ALAR', number: 62, clue: 'Banned growth regulator'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'WILLTOLIVE', number: 63, clue: 'Fighting spirit at a critical time'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'IDA', number: 64, clue: 'B.C. neighbor'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'LES', number: 65, clue: 'The, to Thierry'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'LAB', number: 66, clue: 'Small dog?'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CLIO', number: 67, clue: 'Ad nod'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'IDEAS', number: 68, clue: 'Thoughts'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ADEN', number: 69, clue: 'Yemeni port on an eponymous gulf'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HARM', number: 70, clue: '"First, do no ___"'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'NASTY', number: 71, clue: 'Vicious'))
clues_mgwcc114_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'BOND', number: 72, clue: 'Suave spy'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #114 - "Drinking Game"', grid: 'PARA.RAJAH.WISH|ABET.ALERO.ONTO|RIVERMOUTH.WHEW|ALE.ASU..OHSURE|DERBY.DACHA.MIL|ENSUED.GOODCALL|SEES.ESAU.JANES|...TUCKINGIN...|SCOUT.INTO.THAW|POPPILLS.OTOOLE|IRE.CELTS.HOWLS|NONFAT..PEE.DET|ALAR.WILLTOLIVE|CLIO.IDEAS.ADEN|HARM.NASTY.BOND', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/8/20', entries: clues_mgwcc114_unscrambled, instructions: instructions, explanation: explanation)
