clues_mgwcc117_unscrambled = Array.new
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DEPP', number: 1, clue: 'Sparrow or Crane, really'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DBA', number: 1, clue: 'Abbr. on company checks'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EEL', number: 2, clue: 'Word after longneck or sawtooth'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PAL', number: 3, clue: 'Bud'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PROTEAM', number: 4, clue: 'Bills or Bulls'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'RAW', number: 5, clue: 'Like some talent'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RUFUS', number: 5, clue: 'Singer Wainwright'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'AMOR', number: 6, clue: 'Word that reverses into a place where it meant "love"'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'WARN', number: 7, clue: 'Sound the alarm'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'VOQED', number: 8, clue: 'Made a decision (to)'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'VUE', number: 8, clue: 'Saturn model'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'OSSUARY', number: 9, clue: 'House of ribs?'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'QHENCEFORTH', number: 10, clue: 'From which point'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'EMAIL', number: 11, clue: 'Contact, often'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DELVE', number: 12, clue: 'Ask a lot of questions'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BEAR', number: 13, clue: 'Boo-Boo, for example'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'UMA', number: 14, clue: 'Ex-wife of 27-across'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'PUSHME', number: 15, clue: 'Swinger\'s demand'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'PRYA', number: 15, clue: '___ secret out of (12-across)'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ALLOQFOR', number: 16, clue: 'Set aside'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'QORN', number: 17, clue: 'Like an old shirt\'s fabric'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'RESEAL', number: 18, clue: 'Close a letter the second time'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'TOURNEY', number: 19, clue: 'Sporting event, casually'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'EMU', number: 20, clue: 'Melbourne meat'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'UNIV', number: 21, clue: 'Small college?'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TOQERS', number: 22, clue: 'They move big things around'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'TEAMO', number: 22, clue: 'Senora\'s sentiment'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'OTHER', number: 23, clue: 'Word next to a box, frequently'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'QHEREABOUTS', number: 24, clue: 'Approximate location'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'MANACLE', number: 25, clue: 'Hand holder'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'NOOD', number: 26, clue: 'Without clothing, goofy-style'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ETHAN', number: 27, clue: 'Ex-husband of 14-across'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'DRU', number: 28, clue: '"All the King\'s Men" actress'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'DNA', number: 28, clue: 'Test material'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ROPER', number: 29, clue: 'Tripper\'s landlord'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ORE', number: 30, clue: 'Deposit amount'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AHEM', number: 31, clue: '"Listen to me"'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'UNO', number: 32, clue: 'Wild Draw Four game'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'URN', number: 32, clue: 'Ashes holder'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'JOYFUL', number: 33, clue: 'Gay'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'JET', number: 33, clue: 'Skedaddle'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'UNITE', number: 34, clue: 'Get together'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'LOBOS', number: 35, clue: 'Mexican pack'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MER', number: 36, clue: 'Milieu de Cousteau'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'QRAPPED', number: 37, clue: 'Enveloped entirely'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'QOMB', number: 37, clue: 'Enclosed space at one end of the human life cycle'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'PAC', number: 38, clue: '___-Man'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ONO', number: 39, clue: 'She said "Why do they cover Paul\'s songs but never mine?"'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OREGON', number: 40, clue: 'Home to the Rogue Valley'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'GRINSAT', number: 41, clue: 'Bares one\'s teeth to'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EAT', number: 42, clue: 'First third of a current movie title'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'DRIB', number: 43, clue: 'Little bit'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'DOGTOWN', number: 43, clue: '1997 Mary Stuart Masterson movie (also a National Geographic Channel series that Odie might enjoy)'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'ARM', number: 44, clue: 'Offshoot'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'PRC', number: 45, clue: 'Economic rival of the USA'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'PSI', number: 45, clue: 'Trident-shaped letter'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'JOTTO', number: 46, clue: 'Logic game'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'JUNK', number: 46, clue: 'Garage sale stuff, often'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IMBIBES', number: 47, clue: 'Boozes it up, more poshly'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'IMMER', number: 47, clue: 'It\'s always in Berlin or Vienna'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'MOOSE', number: 48, clue: 'Bullwinkle J. ___'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'EPEE', number: 49, clue: 'Thin weapon'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'HUGHES', number: 50, clue: 'Oscar-nominated DiCaprio role'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'HALVE', number: 50, clue: 'Cut in two'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MOON', number: 51, clue: 'Proteus, to Neptune'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'PISSANT', number: 52, clue: 'Trifling, like Z in a 1998 movie'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SQAT', number: 53, clue: 'Ground rule double, e.g.'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SATE', number: 54, clue: 'Make happy'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MOUSSE', number: 55, clue: 'French for "foam"'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'STS', number: 56, clue: 'They\'re smaller than a 60-down'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'QALKOVER', number: 57, clue: 'Dominate, in a way'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'VOA', number: 58, clue: 'Intl. radio network'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'ERM', number: 59, clue: '"Uh..."'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'RTE', number: 60, clue: '95, e.g.'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ESTATE', number: 61, clue: 'Grounds'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ATV', number: 62, clue: 'Off-road fun'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'WORT', number: 63, clue: 'Follower of St. John\'s?'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RESTS', number: 64, clue: 'Isn\'t active'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'TEE', number: 65, clue: 'Driving stick'))
clues_mgwcc117_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'NAME', number: 66, clue: 'Adam Smith, David Hume or Sean Connery'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #117 - "Twin Tweaks"', grid: 'DEPP.RAW..VOQED|BEAR.UMA.PUSHME|ALLOQFOR.RESEAL|...TOURNEY.UNIV|TOQERS..MANACLE|ETHAN.DRU.ORE..|AHEM.UNO.JOYFUL|MER.QRAPPED.ONO|OREGON.EAT.DRIB|..ARM.PRC.JOTTO|IMBIBES..HUGHES|MOON.PISSANT...|MOUSSE.QALKOVER|ESTATE.ATV.WORT|RESTS..TEE.NAME', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/9/10', entries: clues_mgwcc117_unscrambled, instructions: instructions, explanation: explanation)
