clues_mgwcc126_unscrambled = Array.new
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BATS', number: 1, clue: 'Upside-down figures'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BELLA', number: 1, clue: '"Twilight" character'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ADIEU', number: 2, clue: 'Word heard at Gare du Nord'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TIMER', number: 3, clue: 'Old-___'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'STY', number: 4, clue: 'Farm house'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'RETD', number: 5, clue: 'Living in Fla., often'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'RAJA', number: 5, clue: 'Indian chief'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EQUUS', number: 6, clue: 'Play on horses'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TURNTM', number: 7, clue: 'With 47-down, how to locate the sinister creature'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DAYTRADES', number: 8, clue: 'Tries to make a quick buck'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'HATCH', number: 9, clue: 'Lose one\'s shell'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'HINDI', number: 9, clue: 'Language spoken in 44-across'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ABE', number: 10, clue: 'Maggie\'s grandfather'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TIPI', number: 11, clue: 'Home on the range'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CZAR', number: 12, clue: 'Word after drug or car'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HALE', number: 13, clue: 'Fit looking'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EDIT', number: 14, clue: 'Make her here, for example'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AQUA', number: 15, clue: 'Light shade'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'IBIZA', number: 16, clue: 'Island whose local name is Eivissa'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LIMY', number: 17, clue: 'Citric'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'JURY', number: 18, clue: 'The duty dozen?'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'NEPAL', number: 19, clue: 'Land in high mountains'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'LEE', number: 20, clue: 'Losing pitcher on Wednesday'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'DAUNTED', number: 21, clue: 'Put off'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'DEVOUR', number: 21, clue: 'Gobble up'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'EASEDUP', number: 22, clue: 'Got loose'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'IRE', number: 23, clue: 'Indignation'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'AURAE', number: 24, clue: 'Glows'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'ATMCARD', number: 25, clue: '"CHASE" may be printed on it'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'STRAIT', number: 26, clue: 'Narrow route'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'THEMIST', number: 27, clue: '2007 Stephen King movie -- or what you must remove to rid yourself of the sinister creature'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'TVM', number: 28, clue: '"Appreciate it greatly," while texting'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'MISTAKE', number: 29, clue: 'Slip'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'MAS', number: 30, clue: 'Mates of 48-across'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'HIPS', number: 31, clue: 'Dancers shake them'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'IRAN', number: 32, clue: 'Mt. Damavand is there'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'PIMA', number: 33, clue: 'Tucson\'s county'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'STEM', number: 34, clue: 'Come (from)'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CHAMOIS', number: 35, clue: 'Alpine mammal'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'CITY', number: 35, clue: 'Carson follower'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'HAHA', number: 36, clue: 'Nelson\'s catchphrase, on "The Simpsons"'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ACER', number: 37, clue: 'Laptop choice'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SESSIONAL', number: 38, clue: 'Of a parliamentary meeting'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'DEMERIT', number: 39, clue: 'Mark against'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'MARAUD', number: 40, clue: 'Plunder'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IACCUSE', number: 41, clue: '1958 movie with Jose Ferrer as Alfred Dreyfus'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'EDAMAME', number: 42, clue: 'Popular pods'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'THEARTS', number: 43, clue: 'Not B.S. material'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'SURINAM', number: 44, clue: 'Its capital is Paramaribo'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'YARR', number: 45, clue: 'Pirate\'s shout'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'ASI', number: 46, clue: '"___ Grew Older" (Langston Hughes poem)'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'INTOLU', number: 47, clue: 'See 7-down'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'PAS', number: 48, clue: 'Mates of 30-across'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'DUKING', number: 49, clue: 'Fought (it out)'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ULCER', number: 50, clue: 'Duodenum problem'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'GAGON', number: 51, clue: 'Be unable to swallow'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'UTURN', number: 52, clue: 'Reversal'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'UZBEK', number: 53, clue: 'Chess grandmaster Rustam Kasimdzhanov, for example'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ROOMY', number: 54, clue: 'Nice and large'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'NEEDY', number: 55, clue: 'Poor'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AXE', number: 56, clue: 'Get rid of'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'ATOM', number: 56, clue: 'Small amount of gold or silver'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'XOXO', number: 57, clue: 'Note affection'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'EXIT', number: 58, clue: 'Get out of'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'LEOTARD', number: 59, clue: 'Gymnastics cover'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ROTE', number: 60, clue: 'Memory'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ZOE', number: 61, clue: 'California congresswoman Lofgren'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'TOXIC', number: 62, clue: 'Inedible'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'IDO', number: 63, clue: '"Indeed!"'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'NOGO', number: 64, clue: 'Unfeasible'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'OBOE', number: 65, clue: 'Mitch Miller specialty'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'OHS', number: 65, clue: 'Surprised cries'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OXIDE', number: 66, clue: 'Lead ___'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ALOT', number: 67, clue: 'In spades'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'HEMD', number: 68, clue: 'Shirt: Ger.'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MOTOR', number: 69, clue: 'Skedaddle'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'LUNE', number: 70, clue: 'Crescent shape'))
clues_mgwcc126_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SKYY', number: 71, clue: 'Brand in a blue bottle'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #126 - "Halloween Party"', grid: 'BATS.RETD.HATCH|EDIT.AQUA.IBIZA|LIMY.JURY.NEPAL|LEE.DAUNTED.IRE|AURAE.STRAIT...|...TVM.MAS.HIPS|CHAMOIS.DEMERIT|IACCUSE.EDAMAME|THEARTS.SURINAM|YARR.ASI.PAS...|...DUKING.UTURN|AXE.LEOTARD.ZOE|TOXIC.NOGO.OBOE|OXIDE.ALOT.HEMD|MOTOR.LUNE.SKYY', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/11/12', entries: clues_mgwcc126_unscrambled, instructions: instructions, explanation: explanation)
