clues_mgwcc128_unscrambled = Array.new
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'RELAID', number: 1, clue: 'Put down again, as tiles'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'RAHS', number: 1, clue: 'Cheers'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELAH', number: 2, clue: 'Valley in a 2007 movie title'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LANE', number: 3, clue: 'Pleasant road'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ANG', number: 4, clue: 'Director Lee'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'INI', number: 5, clue: 'Magician\'s surname ending'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DANTE', number: 6, clue: 'Director of "Gremlins" and "Amazon Women on the Moon"'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'RITT', number: 7, clue: '"Norma Rae" and "Sounder" director Martin'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RUHR', number: 7, clue: 'Dortmund\'s river'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ITEM', number: 8, clue: 'Thingy'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TARS', number: 9, clue: 'Blackens, as someone\'s reputation'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'THEOC', number: 10, clue: 'TV show named for an area of southern California'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'VOS', number: 11, clue: 'Marilyn ___ Savant (high-IQ writer)'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'VACUUM', number: 11, clue: 'Do a household chore'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OCASEY', number: 12, clue: '"Juno and the Paycock" playwright'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SEWELL', number: 13, clue: '"Black Beauty" author Anna'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALANNA', number: 14, clue: 'Actress Ubach of "Meet the Fockers"'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'UTAH', number: 15, clue: 'Promontory Point\'s place'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ACE', number: 16, clue: 'Expert'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'HANGINTHERE', number: 17, clue: '"Don\'t give up!"'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'TEA', number: 18, clue: '___ Partier'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'CAW', number: 19, clue: 'As the crow sighs'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SHE', number: 20, clue: 'First-year English word'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'TERMSOFUSE', number: 21, clue: 'Contract section'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'FRAN', number: 22, clue: '"The Nanny" name'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'IKEA', number: 23, clue: 'Aneboda dresser seller'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'IRE', number: 23, clue: 'Nat. of 12-down'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'KNORR', number: 24, clue: 'Soup brand'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'CRUEL', number: 25, clue: 'Word before fate or logic'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ADORN', number: 26, clue: 'Decorate'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ACT', number: 26, clue: 'Do a few lines'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'DOW', number: 27, clue: 'Chemical giant'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'OMA', number: 28, clue: 'Mutti\'s Mutti'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'ROB', number: 29, clue: 'Burgle'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'RIKKI', number: 29, clue: '"___ Don\'t Lose That Number"'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'OLIO', number: 30, clue: 'Mishmash'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'BEER', number: 31, clue: 'Homer Simpson\'s passion'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'AMYL', number: 32, clue: '___ nitrite (inhaled drug)'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'COMEONEILEEN', number: 33, clue: '1983 #1 hit with the line "We are far too young and clever"'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'NOIR', number: 34, clue: 'Drakkar ___ (cologne brand)'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ECCE', number: 35, clue: 'Palindromic Latin word'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'ESTES', number: 36, clue: '___ Park, Colo.'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TWA', number: 37, clue: 'Former flyers'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'ROCKIES', number: 38, clue: 'Colorado crew'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'PSI', number: 39, clue: 'One of 24'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'PER', number: 39, clue: 'Each'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'SAO', number: 40, clue: '___ Miguel (largest island in the Azores)'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'ITS', number: 41, clue: 'That creature\'s'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'TRICKORTREAT', number: 42, clue: 'Mild fall threat'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'TEED', number: 42, clue: '___ off on (hit hard, as a pitcher)'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'RUE', number: 43, clue: 'Regret'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'CONE', number: 44, clue: 'Dunce cap shape'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'CALDER', number: 44, clue: 'Mobile man'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'OREIDA', number: 45, clue: 'Tater Tots brand'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'NINETY', number: 46, clue: 'Lowest A'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'REI', number: 47, clue: 'King, to Brazilians'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'EUROS', number: 48, clue: 'Mannheim money'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ARIEL', number: 49, clue: '"The Little Mermaid" mermaid'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'LSATS', number: 50, clue: 'Future atty.\'s exams'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'BASE', number: 51, clue: 'Crude'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'BAY', number: 51, clue: 'Charleston or Chesapeake'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ARLES', number: 52, clue: '"Cafe Terrace at Night" city'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LENDSANEAR', number: 53, clue: 'Listens'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'ALOU', number: 54, clue: 'Baseball family name'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'NLRB', number: 55, clue: 'Union monitoring govt. arm'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'EMTS', number: 56, clue: 'Amb. workers'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'HOA', number: 57, clue: 'Real estate developer\'s gp.'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'HINT', number: 57, clue: 'Nudge'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ONCE', number: 58, clue: 'In the past'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AGER', number: 59, clue: 'Teen ending'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'DIE', number: 60, clue: 'The Germans\' the'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'ALLMYLOVING', number: 61, clue: '1963 Beatles classic'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'OVA', number: 62, clue: 'Biology class plural'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'VIL', number: 63, clue: 'Cruella De ___'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EDT', number: 64, clue: 'Clock setting abbr.'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TORT', number: 65, clue: 'Legal wrong'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'EVINCE', number: 66, clue: 'Demonstrate'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RAY', number: 67, clue: 'Sunbeam'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SUBS', number: 68, clue: 'Benchwarmers'))
clues_mgwcc128_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'SALTER', number: 69, clue: 'Nut plant worker'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#128 - "The Abridged Version"', grid: 'RELAID.RITT.VOS|ALANNA.UTAH.ACE|HANGINTHERE.CAW|SHE..TERMSOFUSE|...IKEA...CRUEL|ADORN..ROB.AMYL|COMEONEILEEN...|TWA.ROCKIES.PSI|...TRICKORTREAT|CONE.REI..EUROS|ARIEL...BASE...|LENDSANEAR..HOA|DIE.ALLMYLOVING|EDT.TORT.EVINCE|RAY.SUBS.SALTER', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/11/26', entries: clues_mgwcc128_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')