clues_mgwcc130_unscrambled = Array.new
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'RELIC', number: 1, clue: 'Anachronism'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'RASA', number: 1, clue: 'Blank, to Brutus'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELIS', number: 2, clue: 'Some were miffed by 29-across in last week\'s puzzle'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LULU', number: 3, clue: 'Great thing, in old slang'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ILLSPENT', number: 4, clue: 'Wasted'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'CAYUGA', number: 5, clue: 'One of the five tribes of the Iroquois Confederacy'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'EGAD', number: 6, clue: '"My word!"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ELAL', number: 6, clue: 'They frequently cross the Mediterranean'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GIT', number: 7, clue: '"Go on!"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AMOUR', number: 8, clue: 'Francophile\'s feeling'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DONPABLO', number: 9, clue: '___\'s Mexican restaurants'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'QUIK', number: 10, clue: 'A bunny pitches it'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'QIGONG', number: 10, clue: 'Chinese system'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ULAN', number: 11, clue: 'Part of a world capital'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'IAGO', number: 12, clue: 'Play soldier'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KNEW', number: 13, clue: '"I ___ it!"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALULA', number: 14, clue: 'Be-Bop follower'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'LIMO', number: 15, clue: 'Long ride'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ILAN', number: 16, clue: '"Top Chef" season 2 champ ___ Hall'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SILLY', number: 17, clue: 'Ridiculous'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Across', answer: 'ATON', number: 18, clue: 'Scads'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'GAGE', number: 19, clue: 'Thomas ___ (British general in the Revolutionary War)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ASUSUAL', number: 20, clue: 'Unsurprisingly'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Down', answer: 'ASP', number: 21, clue: 'Ancient method of execution'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'UPTONOW', number: 22, clue: 'Yet'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'TWOLF', number: 23, clue: 'Minn. athlete'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'PGS', number: 24, clue: 'Movie ratings'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'BRAWN', number: 25, clue: 'Might'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'BLUESEA', number: 25, clue: 'Deep place'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OHBEAPAL', number: 26, clue: '"Do me this one favor!"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'OHMIC', number: 26, clue: '___ resistance (physics measurement)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'HAUSA', number: 27, clue: 'One of Nigeria\'s official languages'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'BALER', number: 28, clue: 'Person it\'s fun to shout "hey!" at'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'ABLY', number: 29, clue: 'With precision'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'BOGART', number: 30, clue: '"Sabrina" actor, 1954'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'ASIDE', number: 31, clue: 'To the right, sometimes'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'REVUE', number: 32, clue: 'Show'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'TWEEN', number: 33, clue: 'Sixth-grader, e.g.'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HAAN', number: 34, clue: 'Cole ___ shoes'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'BUELL', number: 35, clue: 'Harley-Davidson motorcycle brand discontinued in 2009'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ESAI', number: 36, clue: 'Morales of "The Burning Season"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'SEW', number: 37, clue: 'Put on the button'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MULTIPLESOFFIVE', number: 38, clue: '13 to examine'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'IDEAL', number: 39, clue: 'Unimprovable'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'PARNELLS', number: 40, clue: 'They succeeded the Palins as Alaska\'s first family'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'FATTENUP', number: 41, clue: 'Prepare for slaughter'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ISE', number: 42, clue: 'English verb ending'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'DAYSA', number: 43, clue: '"Every ___ Holiday" (1937 Mae West comedy)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ADUE', number: 44, clue: 'For two'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'CAREER', number: 45, clue: '___ criminals'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ESALEN', number: 46, clue: 'Big Sur institute'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'EIGHTEEN', number: 47, clue: 'Course number'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'GPA', number: 48, clue: '0.00, for John Belushi in "Animal House"'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'HOVELS', number: 49, clue: 'Ratholes'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'SANAA', number: 50, clue: 'Capital with an apostrophe'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'ASIAN', number: 51, clue: '___-Canadians'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'POT', number: 52, clue: 'Smoke'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'USMALES', number: 53, clue: 'Some Americans, per an Elvis title'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'UGGS', number: 53, clue: 'Fashionable boots'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'SEEP', number: 54, clue: 'Get (through)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'MONA', number: 55, clue: 'With 61-across, it was stolen in 1911'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'CAVEMEN', number: 56, clue: 'Brutes'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'CAPP', number: 56, clue: 'Comical Al'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'MERE', number: 57, clue: 'Pathetic'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'EMIL', number: 58, clue: '___ Jannings (first person to receive an Oscar)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'NYET', number: 59, clue: 'Volgograd adverb'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'GEOL', number: 60, clue: 'Rock history, briefly'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'LISA', number: 61, clue: 'See 55-down'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'SPA', number: 62, clue: '___ treatment'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Across', answer: 'ENEMY', number: 63, clue: '"Our true ___ has yet to reveal himself" ("The Sopranos" line)'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GENE', number: 64, clue: 'DNA dweller'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'LAPP', number: 65, clue: 'Reindeer herder, traditionally'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'LURIE', number: 66, clue: 'Philadelphia Eagles owner Jeffrey'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SPAN', number: 67, clue: 'Period'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SNAP', number: 68, clue: 'Lose control'))
clues_mgwcc130_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SPELT', number: 69, clue: 'Quinoa alternative'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#130 - "Linkin\' Continental"', grid: 'RELIC.EGAD.QUIK|ALULA.LIMO.ILAN|SILLY.ATON.GAGE|ASUSUAL.UPTONOW|...PGS.BRAWN...|OHBEAPAL.BOGART|HAAN..BUELL.SEW|MULTIPLESOFFIVE|ISE.DAYSA..ADUE|CAREER.EIGHTEEN|...SANAA.POT...|USMALES.CAVEMEN|GEOL.LISA.ENEMY|GENE.LAPP.LURIE|SPAN.SNAP.SPELT', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/12/10', entries: clues_mgwcc130_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')