clues_mgwcc138_unscrambled = Array.new
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BAJA', number: 1, clue: '___ Bean Co. (Mexican restaurant in Staunton, Va.)'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BBS', number: 1, clue: 'Small shots'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALI', number: 2, clue: 'Pakistan\'s founder Muhammad ___ Jinnah'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'JOT', number: 3, clue: 'Scribble'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AGA', number: 4, clue: 'Palindromic title'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'CANCAN', number: 5, clue: 'Repetitive dance, so to speak'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'CATBED', number: 5, clue: 'Fur-covered place'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ARABS', number: 6, clue: 'Marsh ___ (group in southern Iraq)'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NERA', number: 7, clue: 'Black, in Bari'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'COT', number: 8, clue: 'Basic bed'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ALA', number: 9, clue: 'Mobile home, for short'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NARCSON', number: 10, clue: 'Turns in'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'TSP', number: 11, clue: 'Recipe abbr.'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TOKENKENKEN', number: 11, clue: 'Single math puzzle thrown in with all the sudoku?'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SWEAT', number: 12, clue: 'Hard work, in metaphor'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'PEARS', number: 13, clue: 'Still life fruits'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BLOG', number: 14, clue: 'MGWCC, e.g.'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'AREOLA', number: 15, clue: 'Breast area'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'OWE', number: 16, clue: 'Have karmic debt to'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SITARTARTAR', number: 17, clue: 'Gunk that builds up on a musical instrument?'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'RAGED', number: 18, clue: 'Went ballistic'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'KEA', number: 19, clue: 'Mauna ___'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'ABBA', number: 20, clue: 'Musical acronym'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'CLEAR', number: 21, clue: 'Make after expenses'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'LEO', number: 22, clue: 'Fire sign'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ENGAGES', number: 23, clue: 'Debates with'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'ELEGY', number: 23, clue: 'Words to remember someone by'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'NOBLE', number: 24, clue: 'Unlike knaves'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'GABONBONBON', number: 25, clue: 'Candy from an African nation?'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'ANEW', number: 26, clue: 'From the top'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'RESENTS', number: 27, clue: 'Holds a grudge against'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'RELAY', number: 27, clue: 'Pass along'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ETON', number: 28, clue: 'King Henry VI founded it in 1440'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LOANED', number: 29, clue: 'Ceded for some time'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'RETOOK', number: 30, clue: 'Got back'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'RECAP', number: 30, clue: 'Summary'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'EBBED', number: 31, clue: 'Went back'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'FELON', number: 32, clue: 'Prisoner, often'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'FEMUR', number: 32, clue: 'Big bone'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'EPS', number: 33, clue: 'JPEG alternative'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'POISE', number: 34, clue: 'Composure'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'SWEAR', number: 35, clue: '___ up and down'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'GLOW', number: 36, clue: 'Shine'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'PECAN', number: 37, clue: '"Yes, ___!" (2009 Ben & Jerry\'s flavor)'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'POKE', number: 37, clue: 'Facebook nudge'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'SNOW', number: 38, clue: 'Hoodwink'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'SOLD', number: 38, clue: '"You get it!"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'YEN', number: 39, clue: 'It\'s worth about a penny'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'SOMAY', number: 40, clue: 'Pat Metheny\'s "___ It Secretly Begin"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SCHISMS', number: 40, clue: 'Rifts'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'HOKIE', number: 41, clue: 'Virginia Tech athlete'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'HARSH', number: 41, clue: 'Adjective often following "unduly"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'BUCKUP', number: 42, clue: 'Quit whining'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'UTZ', number: 43, clue: 'Bruce Chatwin novel that\'s also a pretzel brand'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'WALESA', number: 44, clue: 'Pole vaulting to prominence, in the 1980s'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'WARCRY', number: 44, clue: 'Shout meant to intimidate'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'BROTHER', number: 45, clue: 'Close male friend'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'BPLUS', number: 45, clue: 'Good grade'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ROOFS', number: 46, clue: 'High places'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'GARDNER', number: 47, clue: 'Puzzling Martin'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'GAIUS', number: 47, clue: 'Roman praenomen'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'PONZI', number: 48, clue: 'Infamous swindler Charles ___'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'OARS', number: 49, clue: 'Boat propellers'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'OHMS', number: 49, clue: 'Physics measurement'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LOB', number: 50, clue: 'It often gets smashed'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'SOCHICHICHI', number: 51, clue: 'Stylish person at the 2014 Olympics?'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'OUT', number: 52, clue: '"Skedaddle!"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'CRU', number: 53, clue: 'Puzzle-loving group, with "The"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'IKE', number: 54, clue: 'Horrific 2008 Atlantic hurricane'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'CIA', number: 55, clue: 'Org. mentioned in the lyrics to the Beatles\' "Dig It"'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'HES', number: 56, clue: 'Fellows'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'IVY', number: 57, clue: 'Wall climber'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'UFO', number: 58, clue: 'Lenticular cloud, as some mistake it for'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'MURMUR', number: 59, clue: 'Low sound'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'KIEV', number: 60, clue: 'Sister city of Munich and Minsk'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SSN', number: 61, clue: 'Digits with dashes: abbr.'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'STUSSY', number: 62, clue: 'Sportswear line with an umlaut'))
clues_mgwcc138_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'EASY', number: 63, clue: 'Word on many crossword book covers'))
Puzzle.create(title: 'MGWCC #138 - "Three-Piece Suite"', grid: 'BAJA.CANCAN.TSP|BLOG.AREOLA.OWE|SITARTARTAR.KEA|....ABBA..CLEAR|ENGAGES.RESENTS|LOANED.RETOOK..|EBBED.FELON.EPS|GLOW.PECAN.SNOW|YEN.SOMAY.HOKIE|..BUCKUP.WALESA|BROTHER.GARDNER|PONZI..OARS....|LOB.SOCHICHICHI|UFO.MURMUR.KIEV|SSN.STUSSY.EASY', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/2/4', entries: clues_mgwcc138_unscrambled)
