clues_mgwcc140_unscrambled = Array.new
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MOSCOW', number: 1, clue: 'Birth city of former World Chess Champion Vassily Smyslov'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MELD', number: 1, clue: 'Pinochle play'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OLEO', number: 2, clue: 'Crossword spread'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SPAN', number: 3, clue: 'Distance'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'CANTWAIT', number: 4, clue: 'Has to be done now'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'OST', number: 5, clue: 'East, in the former East Germany'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WOLFF', number: 6, clue: 'Soccer player Josh or author Tobias'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'ADD', number: 7, clue: 'Throw in'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALTO', number: 7, clue: 'One voice'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DEEPBLUE', number: 8, clue: 'Computer that beat Garry Kasparov in a 1997 chess match'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DER', number: 9, clue: '___ Spiegel (German news magazine)'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'DOPE', number: 10, clue: 'Nitwit'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'DAZZLE', number: 10, clue: 'Wow'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OLETAECLAT', number: 11, clue: 'Great success for singer Adams?'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PETES', number: 12, clue: '"For ___ sake!"'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EXACT', number: 13, clue: 'Precise'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ELPASO', number: 14, clue: 'City over the border from Juarez, Mexico'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'LEE', number: 15, clue: 'Spike in film production'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ALEX', number: 16, clue: '"Famous Names for $200, ___"'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LEANTLATER', number: 17, clue: 'Waited a while to stop standing straight?'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'ALIG', number: 18, clue: 'Character for Sacha B.C.'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ZETA', number: 19, clue: 'Letter after epsilon'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'DONT', number: 20, clue: '"Cut that out!"'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'FLOP', number: 21, clue: 'Box office disaster'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'AZTEC', number: 22, clue: 'Conquering Mexican'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'ALTA', number: 22, clue: 'Utah ski resort near Snowbird'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'WIFI', number: 23, clue: 'Coffee shop attraction'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'IRE', number: 24, clue: 'Rage'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'BALLAST', number: 25, clue: 'Hot air balloon stabilizer'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'AFROS', number: 26, clue: 'High hairdos'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OSCAR', number: 27, clue: 'Grouch in a trash can'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ORFF', number: 27, clue: '"Carmina Burana" composer'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'SEER', number: 28, clue: 'Prophet'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'CLEATLATHE', number: 29, clue: 'Machine used on athletic footwear?'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'GOLFTEE', number: 30, clue: 'Driving stick'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'OASES', number: 31, clue: 'Sahara stops'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'RELIES', number: 32, clue: 'Counts (on)'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'SPORE', number: 33, clue: 'Fern of the future'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'AURA', number: 34, clue: 'Luminous radiation'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'CHA', number: 35, clue: '"___-ching!"'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'HURL', number: 36, clue: 'Toss'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ARTY', number: 37, clue: 'Highfalutin\''))
clues_mgwcc140_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'FEET', number: 38, clue: 'Pair on the ground'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'PASEO', number: 39, clue: 'Evening stroll'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'ADELAIDE', number: 40, clue: 'Australia\'s fifth-largest city'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'SLUR', number: 41, clue: 'Low blow'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'SUPPLANT', number: 41, clue: 'Take the place of'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'FRA', number: 42, clue: 'Religious brother'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'RODE', number: 43, clue: 'Enjoyed a roller coaster'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'REFS', number: 43, clue: 'They call hacks and blocks'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'STUART', number: 44, clue: 'Small Little'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'TAR', number: 45, clue: 'Smear'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'THEREST', number: 46, clue: 'Everything not yet mentioned'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'HASHED', number: 47, clue: 'Worked (out), as details'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'TAPA', number: 48, clue: 'Spanish small plate'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'APTLY', number: 49, clue: 'In a fitting way'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'FALAFEL', number: 50, clue: 'Pita patty'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'FARAD', number: 50, clue: 'Unit of capacitance'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'AMUSE', number: 51, clue: 'Entertain'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'AARP', number: 52, clue: '50+ org.'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ASTRO', number: 53, clue: 'Houston hitter'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AMASS', number: 54, clue: 'Gather gradually'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'APPS', number: 55, clue: 'Phone progs'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'PLAX', number: 56, clue: 'Dental rinse brand'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'LESS', number: 57, clue: 'Minus'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'ETNA', number: 58, clue: 'Mediterranean volcano'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'STEW', number: 59, clue: 'Polish bigos or Vietnamese Bo Kho'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SERA', number: 60, clue: 'It follows "que" twice'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RUTH', number: 61, clue: 'Mystery novelist Rendell'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'EILATLATTE', number: 62, clue: 'Coffee drunk in an Israeli city?'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'EPS', number: 62, clue: 'Alternative to a TIFF'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'LET', number: 63, clue: 'Permit'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ASHE', number: 64, clue: 'Richmond-born tennis champ'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'PDA', number: 65, clue: 'Droid, e.g.'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'RENNER', number: 66, clue: 'Current Best Supporting Actor nominee for "The Town"'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DEED', number: 67, clue: 'Act'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SEX', number: 68, clue: 'Touching moments?'))
clues_mgwcc140_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'OTTAWA', number: 69, clue: 'Canada\'s fourth-largest city'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#140 - "There\'s More to This Tale..."', grid: 'MOSCOW.ADD.DOPE|ELPASO.LEE.ALEX|LEANTLATER.ZETA|DONT.FLOP.AZTEC|...WIFI.BALLAST|OSCAR.GOLFTEE..|RELIES.AURA.CHA|FEET.PASEO.SLUR|FRA.RODE.STUART|..THEREST.APTLY|FALAFEL.AARP...|AMASS.APPS.LESS|RUTH.EILATLATTE|ASHE.PDA.RENNER|DEED.SEX.OTTAWA', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/2/18', entries: clues_mgwcc140_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')