clues_mgwcc143_unscrambled = Array.new
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BKGPB', number: 1, clue: 'Meeting members, maybe'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BAH', number: 1, clue: '"Ridiculous!"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'KVCP', number: 2, clue: '"How ___ Mehta Got Kissed, Got Wild and Got a Life" (infamous plagiarized novel of 2006)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'GPXE', number: 3, clue: '___-Masonic Party (1820s-30s political force)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PEWH', number: 4, clue: 'Snorkeling environs, often'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'BWFFKUK', number: 5, clue: 'Have the nerve to vocalize'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'SWJM', number: 6, clue: 'Hits, as on the head: var.'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SSAIA', number: 6, clue: '___ finger at (scolds)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'WPEAN', number: 7, clue: 'Cheering'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'JYJH', number: 8, clue: 'Part of an Asian capital'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MWNC', number: 9, clue: '___-Flush'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ASK', number: 10, clue: '"Indeed, that is true about me"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AFUUW', number: 10, clue: 'Unable to speak, perhaps'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SFRSJ', number: 11, clue: 'Church piece'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KAAUC', number: 12, clue: '"Right!"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AVPEW', number: 13, clue: 'Trouble in the bedroom'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'SPYW', number: 14, clue: 'Field'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'EFFA', number: 15, clue: 'At the very least'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Down', answer: 'EXZD', number: 15, clue: '"A-ha moment" utterance'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'HCXWFKAEJNQXURA', number: 16, clue: 'Self-evident phrase about unwarranted criticism'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'KCO', number: 17, clue: 'Word usually seen in brackets'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'QWAPQ', number: 18, clue: 'Hassle, in "Sopranos" scripts'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'PEHFCIAHCWZUSU', number: 19, clue: '1991 Tom Cochrane hit covered for the 2006 Disney/Pixar movie "Cars"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'KOAN', number: 20, clue: 'Damage'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'ADWJC', number: 21, clue: '"Why am ___?" (memorable phrase from the 1992 vice presidential debate)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SGORU', number: 22, clue: 'Fluffy-tailed companion'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'SLI', number: 22, clue: 'Friend to the Haitian people'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'GGPX', number: 23, clue: 'Deep Prussian'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'OLCZ', number: 24, clue: 'Foot part'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'RYJC', number: 25, clue: 'Banks on a successful show'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'MUP', number: 26, clue: 'Prepared to read a book, often'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'MMJS', number: 26, clue: 'They have two dashes: abbr.'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'UHON', number: 27, clue: 'Loads'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'LGLYKAWPMHQJWL', number: 28, clue: 'Words indicating that an author has omitted a portion of events'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'ASMQ', number: 29, clue: 'Relaxation'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'WBZS', number: 30, clue: 'Red, white and blue: abbr.'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'PQU', number: 31, clue: 'Johannes ___ (Germany\'s president, 1994-2004)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'JQJN', number: 32, clue: 'High pool'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'WJCW', number: 33, clue: 'Weapon in London, next year'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'LCWI', number: 34, clue: 'Scads of sheets'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IPCJ', number: 35, clue: 'Quick uptick?'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'SBQJO', number: 36, clue: 'John Hersey title word'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'QJCU', number: 37, clue: 'Famous Gibraltarians'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'UPU', number: 38, clue: 'Pig\'s digs'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'XZCPMZUSNWJCWP', number: 39, clue: 'Phrase you might say after yet another bad thing happens'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'PZYFW', number: 40, clue: 'O with an anvil-thingy inside it'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'WWOJKJA', number: 41, clue: 'Action indicating sympathy or respect'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ZQS', number: 42, clue: '"___ in the Jailhouse Now"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'WNWIU', number: 43, clue: 'Word before lines or fire'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'LWTGY', number: 44, clue: 'Sault Ste. ___'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'LZIKZ', number: 44, clue: 'CDI times IV'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'WOQPE', number: 45, clue: 'Beloved sauce for Scrabble players'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'TCOAN', number: 46, clue: 'Try again at the squeak'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'GDDG', number: 47, clue: 'Unemployed'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'OHYO', number: 48, clue: 'Yahtzee category'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'OHWDG', number: 48, clue: '"___ knew only darkness and stillness"--Helen Keller'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'HYQRI', number: 49, clue: 'Toxicity beginning'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'YTY', number: 50, clue: 'V. good'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ZOCDFDAHYTJXSW', number: 51, clue: 'What a 98-year-old man did after winning the lottery, in a song'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'DKVO', number: 52, clue: 'Big bank'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'AYHL', number: 53, clue: '___ Boykins (5\' 5" guard who is the shortest current NBA player)'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'XGCL', number: 54, clue: 'Scale for certain pieces: abbr.'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'SVYV', number: 55, clue: 'Suffix with Allah or Islam'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'WGPE', number: 56, clue: 'Mystery "man"'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IQODWKYWQYKGVGP', number: 57, clue: 'Unflappable'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'PCP', number: 58, clue: 'Person born in 1972, say'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'KPAG', number: 59, clue: 'Romanian form of the name Elijah'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'VHDR', number: 60, clue: '___ Rabbit'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'JCYPC', number: 61, clue: 'Old west rope'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ZEN', number: 62, clue: 'Cruella de ___'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'OLGI', number: 63, clue: '"Mad Men" award'))
clues_mgwcc143_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ALVEP', number: 64, clue: 'Cut off one\'s intimate relationship'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #143 - "Un-freakin\'-believable!"', grid: 'BKGPB.SWJM..ASK|AVPEW.SPYW.EFFA|HCXWFKAEJNQXURA|.PEHFCIAHCWZUSU|....KOAN..ADWJC|SGORU...MUP....|LGLYKAWPMHQJWL.|IPCJ.SBQJO.QJCU|.XZCPMZUSNWJCWP|....ZQS...WNWIU|LWTGY..OHYO....|ZOCDFDAHYTJXSW.|IQODWKYWQYKGVGP|KPAG.VHDR.JCYPC|ZEN..OLGI.ALVEP', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/3/11', entries: clues_mgwcc143_unscrambled, instructions: instructions, explanation: explanation)
