clues_mgwcc155_unscrambled = Array.new
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PIMA', number: 1, clue: 'Tucson\'s county'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PEG', number: 1, clue: 'Identify'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IROC', number: 2, clue: '___-Z (classic Camaro)'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MOOR', number: 3, clue: '"The Hound of the Baskervilles" takes place on one'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ASSISTS', number: 4, clue: 'Stockton stat'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'ESSAY', number: 5, clue: 'Persuasive words, it\'s hoped'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ERBIUM', number: 5, clue: 'Element #68'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SOUSA', number: 6, clue: 'March man'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SUM', number: 7, clue: 'Number after an equals sign, sometimes'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ASP', number: 8, clue: 'Slithering danger'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'YES', number: 9, clue: '"Correct"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SCUM', number: 10, clue: 'The lowest'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SHIATSU', number: 10, clue: 'Literally, "finger pressure"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'COOPT', number: 11, clue: 'Get out in front of'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'UNTIL', number: 12, clue: 'Stevie Wonder\'s "___ You Come Back to Me"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MEADE', number: 13, clue: 'He defeated Lee at Gettysburg'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EROS', number: 14, clue: 'Psyche psyched him up'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ROUSE', number: 15, clue: 'Get up'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'HONE', number: 16, clue: 'Fight dullness'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GOOSEBUMPS', number: 17, clue: '1990s young adult series with titles like "You Can\'t Scare Me!" and "Stay Out of the Basement"*'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ESTATE', number: 18, clue: 'Compound'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'IOTA', number: 19, clue: 'Small amount'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'CRISIS', number: 20, clue: 'Chicago\'s mayor never wastes one'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'VAPID', number: 21, clue: 'Without meaningful content'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'VIE', number: 21, clue: 'Go toe-to-toe'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'STUARTLITTLE', number: 22, clue: '1945 novel made into a 1999 movie*'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RAGTIME', number: 23, clue: '1975 novel with Harry Houdini as a character*'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'TREAT', number: 24, clue: 'Pay for'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'LISP', number: 25, clue: 'It makes bass bath'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BANTAM', number: 26, clue: 'Small chicken'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'BEAU', number: 26, clue: 'Bridges of southern California'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'AXIS', number: 27, clue: 'Allies\' non-allies'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'NILS', number: 28, clue: 'First name in the E Street Band'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'ARIES', number: 29, clue: 'Dodge in traffic'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'EXIST', number: 30, clue: 'Are'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'AGES', number: 31, clue: 'A long time'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'AIMAT', number: 31, clue: 'Try to hit'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'UNIT', number: 32, clue: 'Apartment'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'NABS', number: 33, clue: 'Finds a forger'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ITEM', number: 34, clue: 'Object'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'TADA', number: 35, clue: '"And there it is!"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AIL', number: 36, clue: 'Be abed'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'EPITAPH', number: 37, clue: 'Grave words'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'PEES', number: 38, clue: 'Tinkles'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'HEINIE', number: 39, clue: 'Rear'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ATA', number: 40, clue: '___ loss'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'USSR', number: 41, clue: '___ vs. Rest of the World (famous chess match of 1970)'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'ROWBOAT', number: 42, clue: 'Human-powered craft'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'EMIT', number: 43, clue: 'Send off'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'EMBED', number: 44, clue: 'Install'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'MADEFOR', number: 45, clue: 'Tried to reach, as an exit'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ONEAM', number: 46, clue: 'Early hour'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'NAY', number: 47, clue: 'House rejection'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'MIASMA', number: 48, clue: 'Oppressive atmosphere'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'MAPLES', number: 48, clue: 'Canada\'s national silver coins'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'THEWASTELAND', number: 49, clue: '1922 poem that begins "April is the cruellest month"*'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'TRAPS', number: 49, clue: 'Catches'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HALLO', number: 50, clue: 'How a Frenchman may answer the phone'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'ENTER', number: 51, clue: 'Try to win'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'LABEL', number: 52, clue: 'Pigeonhole'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'RANBY', number: 53, clue: 'Passed quickly'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'APIECE', number: 54, clue: 'Each'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'CITE', number: 55, clue: 'Reference'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ESTA', number: 56, clue: '"___ bien"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ALTO', number: 57, clue: 'One voice'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'RUMBLEFISH', number: 58, clue: '1975 novel whose main characters include Rusty-James and the Motorcycle Boy*'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'RAP', number: 58, clue: 'Lay down some rhymes'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'UGH', number: 59, clue: '"Sick!"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'MRI', number: 60, clue: 'Body scan'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'HOP', number: 61, clue: 'Quick, easily made trip'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PLEA', number: 62, clue: 'S.O.S., e.g.'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'AGREE', number: 63, clue: 'See it the same'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'OTTO', number: 64, clue: 'Miranda of "War of the Worlds"'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SORT', number: 65, clue: 'Go (through)'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'PHILS', number: 66, clue: 'The O\'s beat them in the 1983 World Series'))
clues_mgwcc155_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'REAP', number: 67, clue: 'Cut crops'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #155 - "Popular Fiction"', grid: 'PIMA.ESSAY.SCUM|EROS.ROUSE.HONE|GOOSEBUMPS.IOTA|.CRISIS...VAPID|...STUARTLITTLE|BANTAM.ARIES...|EXIST.AGES.UNIT|AIL.EPITAPH.ATA|USSR.EMIT.EMBED|...ONEAM.MIASMA|THEWASTELAND...|RANBY...APIECE.|ALTO.RUMBLEFISH|PLEA.AGREE.OTTO|SORT.PHILS.REAP', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/6/3', entries: clues_mgwcc155_unscrambled, instructions: instructions, explanation: explanation)
