clues_mgwcc158_unscrambled = Array.new
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PIC', number: 1, clue: 'Photo'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PUTSCH', number: 1, clue: 'Coup d\'etat attempt'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'INAPIE', number: 2, clue: 'How two dozen blackbirds were baked'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'CANAAN', number: 3, clue: 'New ___, Conn.'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'DEJA', number: 4, clue: '___ vu all over again'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DAME', number: 4, clue: 'Lady'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ELIO', number: 5, clue: '1960s second baseman ___ Chacon'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'JIFF', number: 6, clue: 'Hurry'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AGFA', number: 7, clue: 'Film company'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'HICKOK', number: 8, clue: 'Bill killed in Deadwood'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'HORDES', number: 8, clue: 'Big, scary groups'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'INEED', number: 9, clue: '"All ___" (1984 Jack Wagner ballad)'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CLOSERTO', number: 10, clue: 'More intimate with'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'KIP', number: 11, clue: '"Napoleon Dynamite" dork'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ONE', number: 12, clue: '12 months old'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KEN', number: 13, clue: 'Spy novelist Follett'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'UNA', number: 14, clue: '___ vez (once, in Spanish)'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ALIG', number: 15, clue: 'Goateed goofball'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'ONLINE', number: 16, clue: 'Surfing'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TAN', number: 17, clue: 'Vacation "souvenir"'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'MIFF', number: 18, clue: 'Irritate'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'REOPEN', number: 19, clue: 'Take another look at, as a cold case'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SPACEOFAIDES', number: 20, clue: 'Work area for your assistants?'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'COO', number: 21, clue: 'Sweet sound'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'IRT', number: 22, clue: 'N.Y.C. subway line'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'CIAO', number: 23, clue: 'Hollywood goodbye'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'REDEYES', number: 24, clue: 'Night flights'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'YARN', number: 25, clue: 'Unlikely-to-be-true story'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'ERIS', number: 26, clue: 'Goddess of strife'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'SEA', number: 27, clue: 'Aegean or Ionian'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'HENOFTARTS', number: 28, clue: 'She lays eggs, then bakes pastries with them?'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'FROM', number: 29, clue: 'Born and raised in'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'TIN', number: 30, clue: 'Shortest element'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'ADO', number: 31, clue: 'Fuss'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'REFED', number: 32, clue: 'Gave more chow to'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'RARE', number: 33, clue: 'Tough to get your hands on'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'RIDE', number: 34, clue: 'Amusement park attraction'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'ATRIA', number: 35, clue: 'Ventricles\' counterparts'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'AMEN', number: 35, clue: '"I\'m with you on that!"'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'DEVONOFSIMONS', number: 36, clue: 'English county with many people like Le Bon and Cowell?'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'DOME', number: 36, clue: 'Stadium or cathedral feature'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'EDIT', number: 37, clue: 'Change for the better, hopefully'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'VERACRUZ', number: 38, clue: 'Port on the Gulf of Mexico'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'SAD', number: 39, clue: 'Pathetic'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'IVE', number: 40, clue: '"So ___ heard!"'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MODEM', number: 41, clue: 'External ___'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'MER', number: 41, clue: '___ M&#233;diterran&#233;e'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EAVE', number: 42, clue: 'Roof overhang'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EMIR', number: 43, clue: 'Mideast leader'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'HIDDENCARD', number: 44, clue: 'Magician\'s secret, or what you need to find in the grid'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'HEISTS', number: 44, clue: 'Bank jobs'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'INC', number: 45, clue: '"Fast Company" rival'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'CBS', number: 46, clue: '"How I Met Your Mother" network'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ALUMNI', number: 47, clue: 'Donors, often'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'RUBOUT', number: 48, clue: 'Off'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'DESERT', number: 49, clue: 'Wasteland'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'RETAKEN', number: 50, clue: 'Won back'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'KLINE', number: 51, clue: 'Oscar winner for "A Fish Called Wanda"'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'BLUE', number: 52, clue: 'Down'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'CLICKSOFSUBS', number: 53, clue: 'U-boat noises?'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'KNEE', number: 54, clue: 'Joint for proposing'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SUIT', number: 55, clue: 'You don\'t need it for 44-across'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'OKRA', number: 56, clue: 'Vegetable often pickled'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'FEEL', number: 57, clue: 'Get the sense'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HARRIS', number: 58, clue: 'Best Actor nominee for "Pollock"'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'HIS', number: 58, clue: 'Greetings'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'ACE', number: 59, clue: 'Count it as 13, for the meta'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'ROI', number: 60, clue: 'King of Quebec'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'NUKE', number: 61, clue: 'Heat up quickly, casually'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'MOE', number: 62, clue: '"___ Letter Blues" (2010 "Simpsons" episode)'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ICOUNT', number: 63, clue: 'Words before a tentative total'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'EIRE', number: 64, clue: 'Ireland, to the Irish'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'NUR', number: 65, clue: 'It\'s only for Germans'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SEIZES', number: 66, clue: 'Annexes'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'ETAL', number: 67, clue: 'Among others'))
clues_mgwcc158_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'ITT', number: 68, clue: 'Creepy cousin'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #158 - "Cut the Deck"', grid: 'PIC.DEJA.HICKOK|UNA.ALIG.ONLINE|TAN.MIFF.REOPEN|SPACEOFAIDES...|CIAO....REDEYES|HENOFTARTS.RARE|....RIDE..ATRIA|.DEVONOFSIMONS.|MODEM..EAVE....|EMIR.HIDDENCARD|RETAKEN....BLUE|...CLICKSOFSUBS|HARRIS.NUKE.MOE|ICOUNT.EIRE.NUR|SEIZES.ETAL.ITT', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/6/24', entries: clues_mgwcc158_unscrambled, instructions: instructions, explanation: explanation)
