clues_mgwcc160_unscrambled = Array.new
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SHAMAN', number: 1, clue: 'Link to the spirit world'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'STEAKS', number: 1, clue: 'A.1. targets'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HOLLIES', number: 2, clue: '2010 Rock and Roll Hall of Fame inductees, with "The"'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ATLANTA', number: 3, clue: 'Hawk\'s home'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MAI', number: 4, clue: 'Chiang ___ (Thai city)'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ALPS', number: 5, clue: 'Frequent Olympics setting'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'NITE', number: 6, clue: 'Marquee noun'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'VBS', number: 7, clue: 'To have and to hold, for short'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'VICUNA', number: 7, clue: 'Peru\'s national animal'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BOA', number: 8, clue: 'Gaudy neckwear'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'STL', number: 9, clue: 'Mo. city'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'LOEW', number: 10, clue: 'Marcus of movies'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'LIVER', number: 10, clue: 'Excellent source of vitamin B12'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ONETIME', number: 11, clue: 'Former'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ELEANOR', number: 12, clue: 'Name in a "Revolver" song title'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'WARGAME', number: 13, clue: 'Exercise with an F-15, say'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TOTALIDIOT', number: 14, clue: 'Fool, emphatically'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Down', answer: 'DIII', number: 15, clue: '503'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'INLA', number: 16, clue: '"To Live and Die ___"'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ELLIPTICAL', number: 17, clue: 'Machine in a gym'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'VEER', number: 18, clue: 'Keep'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ALA', number: 19, clue: 'Modeled after'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'SEIU', number: 20, clue: 'It has about two million members: abbr.'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'RETAG', number: 21, clue: 'Price differently, say'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'RADICAL', number: 21, clue: 'Protest leader, to some'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'KINK', number: 22, clue: 'Hose issue'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'KOFI', number: 23, clue: 'Ki-moon\'s predecessor'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'INAMARINA', number: 24, clue: 'One place to keep your boat'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ARUBA', number: 25, clue: 'Sint Nicolaas\' island'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'MOBILE', number: 26, clue: 'City that I-10 runs through'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SETOFF', number: 27, clue: 'Detonate'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'FACTORY', number: 28, clue: 'Works'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'FRESNO', number: 29, clue: 'California\'s fifth-largest city'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'AROD', number: 30, clue: 'He\'s hit 626 HR (as of today)'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'MOM', number: 31, clue: 'Kid\'s shout'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'SAFARI', number: 32, clue: 'Explorer rival'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ITALY', number: 33, clue: 'Part of the G7'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'UBI', number: 34, clue: 'Quaestor\'s question'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ERE', number: 35, clue: 'Before'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'ICET', number: 36, clue: 'Det. Odafin Tutuola\'s portrayer'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'BICS', number: 37, clue: 'Some pens'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'SNIP', number: 38, clue: 'Cut'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SER', number: 39, clue: 'To be, to Bolivians'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'SEDARIS', number: 39, clue: '"Dress Your Family in Corduroy and Denim" author, 2004'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'EVEREST', number: 40, clue: 'K2\'s superior'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'RESCALE', number: 41, clue: 'Use Photoshop, sometimes'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'TSA', number: 42, clue: 'Much-criticized govt. body since 2001'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'ALANIS', number: 43, clue: '"Jagged Little Pill" name'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'ICESHOW', number: 44, clue: 'Entertainment that lets you chill'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SISTINE', number: 45, clue: 'Chapel name'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EVE', number: 46, clue: 'It ends at midnight'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ONLY', number: 47, clue: 'Just'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'YERTLE', number: 48, clue: 'Dr. Seuss title character'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'ELICIT', number: 49, clue: 'Bring out'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'TOUPEE', number: 50, clue: 'Locks in a drawer, maybe'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'DESTROYER', number: 51, clue: 'Ship in 61-across'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'THREW', number: 52, clue: 'Lost on purpose'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'RATT', number: 53, clue: '1980s metal band that did "Round and Round"'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'PESO', number: 54, clue: 'Uruguay\'s unit of currency'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ARCHY', number: 55, clue: '-ocracy'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'RASP', number: 56, clue: 'Farrier\'s tool'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'SLAP', number: 57, clue: 'Hit, sometimes'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'PEKE', number: 58, clue: 'Toy dog, for short'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'STU', number: 59, clue: 'Name made of consecutive letters'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'REAR', number: 60, clue: 'Hitchcock title word'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'BATTLESHIP', number: 61, clue: 'Game where you can stage a coordinated attack?'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'BIT', number: 61, clue: 'Was awful, to teenagers'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ALI', number: 62, clue: 'Larter of "Heroes"'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'SEE', number: 63, clue: 'Grok'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ISLE', number: 64, clue: 'Skye, notably'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ILLTAKEONE', number: 65, clue: 'Response to an offer'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STEW', number: 66, clue: 'Homophone for another grid entry'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TIE', number: 67, clue: '1 to 1, say'))
clues_mgwcc160_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'PEEWEE', number: 68, clue: 'Squirt'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #160 - "Plot Device"', grid: 'SHAMAN.VBS.LOEW|TOTALIDIOT.INLA|ELLIPTICAL.VEER|ALA.SEIU..RETAG|KINK..INAMARINA|SETOFF.AROD.MOM|.SAFARI.UBI.ERE|...ICET.BICS...|SER.TSA.ALANIS.|EVE.ONLY.ELICIT|DESTROYER..PESO|ARCHY..RASP.STU|REAR.BATTLESHIP|ISLE.ILLTAKEONE|STEW.TIE.PEEWEE', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/7/8', entries: clues_mgwcc160_unscrambled, instructions: instructions, explanation: explanation)
