clues_mgwcc164_unscrambled = Array.new
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'REF', number: 1, clue: 'Technical caller'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ROB', number: 1, clue: 'Plunder'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EEL', number: 2, clue: 'Member of the order Anguilliformes'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'FRAGMENTED', number: 3, clue: 'In pieces'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'ESP', number: 4, clue: 'Unproven ability'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ELKE', number: 4, clue: 'She had a long-running Hollywood feud with Zsa Zsa'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'SAFE', number: 5, clue: 'Having beaten the throw'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PORN', number: 6, clue: 'Net Nanny filters it'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'RCA', number: 7, clue: 'They make Symphonix amplifiers'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'REDID', number: 7, clue: 'Took another shot at'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'COATI', number: 8, clue: 'Mexican mammal'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ANYHOW', number: 9, clue: '"As I was saying..."'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'SKI', number: 10, clue: 'One of a Whistler pair'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SKIN', number: 10, clue: 'Prepare a chicken'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'KIEV', number: 11, clue: 'City that\'s home to the Mother Motherland statue'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'INDY', number: 12, clue: 'Adventurer with a whip'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OER', number: 13, clue: 'Preposition with an apostrophe'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'LAO', number: 14, clue: 'Tonal tongue'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'EON', number: 15, clue: 'Serious stretch'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'KIN', number: 16, clue: 'Not unrelated'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BLACKFRIDAY', number: 17, clue: '11/28/03, for example'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'CREED', number: 18, clue: 'Words to live by'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'IWILL', number: 19, clue: '"White Album" favorite'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'IED', number: 20, clue: 'Iraq danger, for short'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 4, col: 3, dir: 'Across', answer: 'GREENWITHENVY', number: 21, clue: 'Highly covetous'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'EMAJ', number: 22, clue: 'One key, briefly'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SOME', number: 23, clue: 'Neither all nor none'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'STKATE', number: 23, clue: 'Namesake of a Twin Cities college, casually'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ORIGIN', number: 24, clue: 'Beginning'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'IDIOM', number: 25, clue: '"I\'m all thumbs," for instance'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TREENAIL', number: 26, clue: 'Wooden peg'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'NOM', number: 27, clue: 'NPL appellation'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'AFEW', number: 28, clue: 'Nonspecific number'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'IBLE', number: 29, clue: 'Exhaust finish'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'WADER', number: 30, clue: 'Rail or crane'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'DIVINELAWS', number: 31, clue: 'Thomas Aquinas concerned himself with them'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'EVICTS', number: 32, clue: 'Sends packing'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'RECAST', number: 33, clue: 'Found new actors'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'KINDOFBLUE', number: 34, clue: '1959 masterpiece that\'s #12 on Rolling Stone\'s "500 Greatest Albums of All Time"'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'UPTO', number: 35, clue: 'Doing'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'ELAN', number: 36, clue: 'Spirit'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'JIVE', number: 37, clue: 'Nonsense'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AGT', number: 38, clue: 'Rep.'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'MEL', number: 39, clue: '___ Sharples (TV diner owner)'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'PLO', number: 40, clue: 'It has UN observer status'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'OFT', number: 41, clue: 'It\'s frequently before a hyphen'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'VIC', number: 42, clue: 'Perp\'s target'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TIED', number: 43, clue: 'Level'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'DUCT', number: 44, clue: 'Tear tube'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'WESTAFRICA', number: 45, clue: 'Guinea-Bissau is there'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SCRAM', number: 46, clue: 'Word to a critter'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'RERUN', number: 47, clue: 'Show over'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ENDUP', number: 48, clue: 'Ultimately land'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'PEBBLE', number: 49, clue: '___ Beach, Calif.'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'CONTENTS', number: 50, clue: 'What\'s inside'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'CEDAR', number: 51, clue: 'First word of Iowa\'s second-largest city'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'DELAY', number: 52, clue: 'Put off'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'ABATE', number: 53, clue: 'Ease'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'REST', number: 54, clue: 'Chillax'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'DONTBEBASHFUL', number: 55, clue: '"Step on up!"'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'DALI', number: 55, clue: 'Catalonia\'s Teatre-Museu ___'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'OHIO', number: 56, clue: 'Wheeling\'s river'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'NAZI', number: 57, clue: '"Hogan\'s Heroes" extra'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'SEGA', number: 58, clue: 'Game name'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'HCUP', number: 59, clue: 'Big bra size'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'FAST', number: 60, clue: 'Stop eating'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AHA', number: 61, clue: '"Eureka!"'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'BLAMECANADA', number: 62, clue: 'Surprise Oscar nominee for Best Original Song, 1999'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'DOE', number: 63, clue: 'Ena, e.g.'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'AKA', number: 64, clue: 'Called at times'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LIZ', number: 65, clue: 'Phair who sang at Lilith Fair'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'LAT', number: 66, clue: 'WSJ rival'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'GUS', number: 67, clue: 'Gloomy dude, it\'s said'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'WOK', number: 68, clue: 'Men at ___ (Chinese restaurant in Williston, Vt.)'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'IOI', number: 69, clue: 'Intro college class, so to write'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'EYE', number: 70, clue: 'Socket occupant'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'APT', number: 71, clue: 'Suitable'))
clues_mgwcc164_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SEA', number: 72, clue: 'White or Irish'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #164 - "Seven Wonders"', grid: 'REF.ESP.RCA.SKI|OER.LAO.EON.KIN|BLACKFRIDAY.IED|..GREENWITHENVY|SOME...IDIOM...|TREENAIL..WADER|KINDOFBLUE.JIVE|AGT.MEL.PLO.VIC|TIED.WESTAFRICA|ENDUP..CONTENTS|...CEDAR...REST|DONTBEBASHFUL..|AHA.BLAMECANADA|LIZ.LAT.GUS.WOK|IOI.EYE.APT.SEA', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/8/5', entries: clues_mgwcc164_unscrambled, instructions: instructions, explanation: explanation)
