clues_mgwcc169_unscrambled = Array.new
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'COMESIN', number: 1, clue: 'Shows up'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CAMELOT', number: 1, clue: 'The Kennedy years'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OBADIAH', number: 2, clue: 'Short book'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MUDDERS', number: 3, clue: 'They thrive after a storm'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EDWINS', number: 4, clue: 'Booth and Aldrin'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SHOES', number: 5, clue: 'Tennis, bowling and golf'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'IAMS', number: 6, clue: 'ProActive Health dog food maker'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'NBA', number: 7, clue: 'Shooting org.'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'BURST', number: 8, clue: 'Sudden activity'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'BIER', number: 8, clue: 'Stand in a ceremony'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'UNA', number: 9, clue: 'Acapulco A'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'RIVIERA', number: 10, clue: 'Las Vegas Strip hotel'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'STENGEL', number: 11, clue: 'He hit .316 in 1914'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TONKAS', number: 12, clue: 'Small trucks'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ABUDHABI', number: 13, clue: 'The wealthiest city in the world, according to Fortune magazine in 2007'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Down', answer: 'INSOLE', number: 14, clue: 'Arch protection'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'FINITO', number: 15, clue: 'Over'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'FLAN', number: 15, clue: 'Egg dish'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MADWOMAN', number: 16, clue: 'Nut'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'LEAVEN', number: 17, clue: 'Make your dough grow'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EDDIES', number: 18, clue: 'Money and such'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'STAR / STARR', number: 19, clue: 'One of the Beatles, e.g.'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'TRE', number: 20, clue: '___ Cool (Green Day\'s drummer)'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'INK / RINK', number: 21, clue: 'A figure 8 may be made in it'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LIENS', number: 22, clue: 'Some have them on their houses'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'PORN / PORNO', number: 23, clue: 'Blue material'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'PINE', number: 23, clue: 'Air freshener scent'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'MEGA / OMEGA', number: 24, clue: 'It\'s great in Greece'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'MENA', number: 24, clue: 'One of Kevin\'s "American Beauty" co-stars'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OARS', number: 25, clue: 'Water blades'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'FILE / FILET', number: 26, clue: 'Cut finely'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'FINN', number: 26, clue: 'She greets you with "Hyv&#228;&#228; paiv&#228;&#228;!"'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'HERES / THERES', number: 27, clue: '"___ your problem..."'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'HOME', number: 27, clue: 'Not out'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'THS', number: 28, clue: 'Suffix with four, seven or ten'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'LINE / LINEA', number: 29, clue: 'Section of a tax form'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'LANA', number: 29, clue: 'Name that reverses embarrassingly'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'TONAL / ATONAL', number: 30, clue: 'Like some of Schoenberg\'s music'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'TASK', number: 30, clue: 'It may be at hand'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'PANE / PANEL', number: 31, clue: 'Part of a wooden door'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'PAIN', number: 31, clue: 'Hassle'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'LAMA / LLAMA', number: 32, clue: 'Character in an Ogden Nash poem'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'LOCH', number: 32, clue: 'Fjord\'s cousin'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'JOANN / JOANNA', number: 33, clue: 'Woman\'s name from the Hebrew for "God is gracious"'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'JAMAICA', number: 33, clue: 'Spanish Town is there'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'ONEPART', number: 34, clue: 'Measurement for a mixologist'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ROSE / AROSE', number: 35, clue: 'Came up'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ROSLYN', number: 35, clue: 'Affluent New York City suburb'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'CUM', number: 36, clue: 'With, poshly'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'CINEMAS', number: 36, clue: 'Flick showers'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'URINATE', number: 37, clue: 'Perform a biological imperative'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'MENACED', number: 38, clue: 'Threatened'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MANIA / MANIAC', number: 39, clue: 'Ending for mono or ego'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'MACCAM', number: 39, clue: 'Palindromic device named for a tennis player'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'LOCK / CLOCK', number: 40, clue: 'Standard iPhone feature'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'LAI', number: 40, clue: 'Mauna ___ (tropical drink brand)'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'TIRE', number: 41, clue: 'Lose steam'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'TELUGU', number: 41, clue: 'First language of 75 million people'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'AMEN / AMENS', number: 42, clue: 'What\'s heard in church on Sunday'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'MASH / SMASH', number: 43, clue: 'Pulverize'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'MASS', number: 43, clue: 'Big blob'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'BENIN', number: 44, clue: 'Its capital is Porto-Novo'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'BASIC', number: 44, clue: 'Not that complicated'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CAP / CAPE', number: 45, clue: 'Part of a matador\'s getup'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'MAIL / EMAIL', number: 46, clue: 'Common medium of communication'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'MISS', number: 46, clue: 'Not spot'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'GALENA', number: 47, clue: 'Lead ore'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'GAVE', number: 47, clue: 'Threw in the towel'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CIALIS', number: 48, clue: 'It\'ll keep you up at night'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'LOT', number: 49, clue: 'Destiny'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'YMASUMAC', number: 50, clue: 'She sang in Quechua on Letterman in 1987'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'MAR', number: 51, clue: 'Disfigure'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ACROSS', number: 52, clue: '-___ (you are here)'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'NAVIGATE', number: 53, clue: 'Successfully avoid the dangers of'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MATTS', number: 54, clue: 'Me and others'))
clues_mgwcc169_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'RECUSED', number: 55, clue: 'Disqualified'))
spec_feat = '4_12:BR|5_11:BO|6_10:BT|7_9:BA|8_8:BL|9_7:BA|10_6:BC|11_5:BS|12_4:BE'
instructions = 'This week\'s contest answer is a common form of transportation.'
explanation = '<MA>ESCALATOR</MA><TEXT>This remarkable puzzle was awarded Best Crossword in the 2011 Orca Awards (<a href="http://www.crosswordfiend.com/blog/2012/02/26/the-2011-orca-awards/" target="_blank">view the full listings here</a>).</TEXT>'
Puzzle.create(title: 'MGWCC #169 - "Moving Day"', grid: 'COMESIN...BURST|ABUDHABI.FINITO|MADWOMAN.LEAVEN|EDDIES.STAR.INK|LIENS.PORN.MEGA|OARS.FILE.HERES|THS.LINE.TONAL.|...PANE.LAMA...|.JOANN.ROSE.CUM|MANIA.LOCK.TIRE|AMEN.MASH.BENIN|CAP.MAIL.GALENA|CIALIS.YMASUMAC|ACROSS.NAVIGATE|MATTS...RECUSED', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/9/9', entries: clues_mgwcc169_unscrambled, instructions: instructions, explanation: explanation, special_features: spec_feat)
