clues_mgwcc179_unscrambled = Array.new
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'POTCLUB', number: 1, clue: 'Smoking establishment type'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PUGS', number: 1, clue: 'Toy dogs'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OKRA', number: 2, clue: 'Eaters-of-Apple-and-___ (ill-fated tribe)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TRIG', number: 3, clue: 'High school math class'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'CAFE', number: 4, clue: 'Business named for a drink'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'LIFT', number: 5, clue: 'Elevate'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'UNI', number: 6, clue: 'College, in German slang'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BETSON', number: 7, clue: 'Puts money behind, as a horse or a stock'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'OBTAINS', number: 8, clue: 'Gets one\'s hands on'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'OAKWOOD', number: 8, clue: 'Redundantly-named section of London'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'BRA', number: 9, clue: 'The Showstopper by Victoria\'s Secret, e.g.'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TAUT', number: 10, clue: 'Not slack'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ALFA', number: 11, clue: '___ Romeo cars'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ISMS', number: 12, clue: 'Ways of thinking'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'NEAT', number: 13, clue: 'Without ice'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SANE', number: 14, clue: 'All there'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'UKRAINE', number: 15, clue: 'Country with four chessplayers in the world\'s top 50'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'ARALSEA', number: 16, clue: 'Shrinking body of water'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GRIFFITHKAUFMAN', number: 17, clue: 'College known for its school of performing arts?'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'HAJJI', number: 18, clue: 'Person who\'s seen the Qa\'aba'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SAGET', number: 19, clue: 'Bob who narrates "How I Met Your Mother"'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'SAW', number: 20, clue: 'Witnessed'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'TASTE', number: 21, clue: 'Likes and dislikes, collectively'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'DOJOS', number: 22, clue: 'Chigasaki chophouses, as it were'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'DOS', number: 22, clue: 'Recommended actions'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'SHE', number: 23, clue: '"And ___ Was" (Grateful Dead tune)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'JACKSONJOHNSON', number: 24, clue: 'College known for its school of political science?'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'JAMI', number: 24, clue: 'Gertz of "Less Than Zero"'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ADINS', number: 25, clue: 'Points that are essentially the same score as 40-30'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'CORFU', number: 26, clue: 'Greek island in the Ionian Sea'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'KNELL', number: 27, clue: 'Sound of a funeral bell'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'SISAL', number: 28, clue: 'Rope material'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'NABOO', number: 29, clue: 'Planet in the "Star Wars" movies'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'STENO', number: 30, clue: 'Ampad Evidence 6" x 9" Blue ___ Pad (Staples purchase)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'OILON', number: 31, clue: 'Pour ___ troubled waters (calm arguing people down, in British slang)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'NOLTE', number: 32, clue: 'Best Actor nominee for "The Prince of Tides" and "Affliction"'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ADONIS', number: 33, clue: 'Attractive man'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'IDEATION', number: 34, clue: 'The forming of concepts'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'NOSY', number: 35, clue: 'Prying'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MIRES', number: 36, clue: 'Keeps bogged down'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'BELLO', number: 37, clue: 'Maria of "ER"'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'INFLATES', number: 38, clue: 'Strips the value from, as a currency'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'TIN', number: 39, clue: 'Element whose chemical symbol is only one letter shorter than the element itself'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'EVEREST', number: 40, clue: 'Highest protrusion on a relief globe'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'SAHIB', number: 41, clue: 'Title of respect, in India'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'DONOTS', number: 42, clue: 'Highly unrecommended actions'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'DRS', number: 42, clue: 'They do residencies: abbr.'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'SULLIVANROONEY', number: 43, clue: 'College known for its school of journalism?'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'NIMBUS', number: 44, clue: 'Rain-producing cloud'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'NEHIS', number: 45, clue: 'Retro soft drinks'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'FERDE', number: 46, clue: '___-lance (poisonous snake)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'FLAB', number: 46, clue: 'Extra weight'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ELLA', number: 47, clue: 'Lady ___ (jazz nickname)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ROLL', number: 48, clue: 'Toss the dice'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'DYED', number: 49, clue: 'Turned blue, perhaps'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'EDGE', number: 50, clue: 'Slight lead'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'RIM', number: 51, clue: 'North ___ (area of the Grand Canyon)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'AUDIO', number: 52, clue: 'Part of A/V'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'ARUM', number: 52, clue: 'Poisonous lily'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'UGLI', number: 53, clue: 'Fruit from Jamaica'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'DIET', number: 54, clue: 'South Beach, e.g.'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IBLE', number: 55, clue: 'Ending for convert or exhaust'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'OBES', number: 56, clue: 'U.K. awards'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LLOYDWEBBERGIBB', number: 57, clue: 'College known for its music school?'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'WES', number: 58, clue: '"Rushmore" director Anderson'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'EKE', number: 59, clue: 'Squeeze (by)'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ALLEGES', number: 60, clue: 'Claims'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'UKULELE', number: 61, clue: 'Israel Kamakawiwo\'ole\'s instrument'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'BALDEST', number: 62, clue: 'Most blatant, as a lie'))
clues_mgwcc179_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'SEMITES', number: 63, clue: 'Arabs and Jews'))
Puzzle.create(title: 'MGWCC #179 - "College Knowledge"', grid: 'POTCLUB.OBTAINS|UKRAINE.ARALSEA|GRIFFITHKAUFMAN|SAGET.SAW.TASTE|.....DOJOS.....|JACKSONJOHNSON.|ADONIS.IDEATION|MIRES.....BELLO|INFLATES.DONOTS|.SULLIVANROONEY|.....NEHIS.....|FERDE.RIM.AUDIO|LLOYDWEBBERGIBB|ALLEGES.UKULELE|BALDEST.SEMITES', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2011/11/18', entries: clues_mgwcc179_unscrambled)
