clues_mgwcc191_unscrambled = Array.new
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'COPIED', number: 1, clue: 'Made more of'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CAM', number: 1, clue: 'Small recorder'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OMA', number: 2, clue: 'Elder German'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PARVENU', number: 3, clue: 'Member of the nouveau riche, e.g.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'INTOW', number: 4, clue: 'Not self-powered'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'EDIT', number: 5, clue: 'What I didnt due properly to thsi clue'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DANE', number: 6, clue: 'Jutlander, e.g.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'EPSOM', number: 7, clue: '___ salt (magnesium sulfate)'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ERG', number: 7, clue: 'A little work'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'PILAF', number: 8, clue: 'Rice dish'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SNARF', number: 9, clue: 'Eat quickly, in slang (with "down")'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'OSSIE', number: 10, clue: 'Davis of "Grumpy Old Men"'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MESELF', number: 11, clue: 'Humorous reflexive pronoun'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Across', answer: 'STIR', number: 12, clue: 'Kerfuffle'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SML', number: 12, clue: 'T-shirt sizes, briefly'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TEOTWAWKI', number: 13, clue: 'Apocalyptic acronym'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'INAWE', number: 14, clue: 'With jaw on floor'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'RUMOR', number: 15, clue: 'Whispered words'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMANDA', number: 16, clue: 'Knox in the news'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'RINSE', number: 17, clue: 'Washing cycle'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 2, col: 14, dir: 'Across', answer: 'MENU', number: 18, clue: 'Dining options'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MARTINIGLASS', number: 19, clue: 'Vessel for James Bond'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'IDEAS', number: 20, clue: 'Memes'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 3, col: 14, dir: 'Across', answer: 'LOAM', number: 21, clue: 'Good earth'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 4, col: 3, dir: 'Across', answer: 'VOTED', number: 22, clue: 'Made a selection'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'ARIES', number: 23, clue: 'Sheep stars'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Down', answer: 'STAN', number: 24, clue: '"50 Ways to Leave Your Lover" name'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 4, col: 15, dir: 'Across', answer: 'TWO', number: 25, clue: 'II'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BREW', number: 26, clue: 'Make mocha'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'BFF', number: 26, clue: 'They\'re, like, always together'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'RIO', number: 27, clue: 'Angry Birds-themed movie'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'EIFFELTOWER', number: 28, clue: 'Max Fischer\'s doodle, in the opening scene of "Rushmore"'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'INT', number: 29, clue: 'Bank abbr.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'OLE', number: 30, clue: 'Mexican food brand with an accented final letter'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'FIN', number: 31, clue: 'Minnow mover'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'OMAN', number: 32, clue: 'Dry land'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'OPAH', number: 32, clue: 'Funny-shaped fish'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'MOTIF', number: 33, clue: 'Recurring pattern, as in a chess problem'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'FALA', number: 34, clue: 'He\'s buried beside Franklin D. Roosevelt'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'FOURPOSTBED', number: 35, clue: 'Posh place to sleep'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'RST', number: 36, clue: 'QU chain'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'BIDEN', number: 37, clue: 'U.S. senator from 1973-2009'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'EPI', number: 38, clue: 'Prefix with phenomena'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'DAM', number: 39, clue: 'Large power source'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'NEWLY', number: 40, clue: 'Just now'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 16, dir: 'Down', answer: 'LOO', number: 41, clue: 'W.C.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 7, col: 17, dir: 'Down', answer: 'YIN', number: 42, clue: 'Womanly half'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'SAT', number: 43, clue: 'Got comfortable, perhaps'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'IPAD', number: 44, clue: '___ 3 (powerful tablet)'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'DEFAT', number: 45, clue: 'Make healthier, perhaps'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Across', answer: 'KOI', number: 46, clue: 'Pond figure'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'THETHIRDDIMENSION', number: 47, clue: 'What you\'ll need to think in'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'TED', number: 47, clue: 'One of Larry\'s "Curb Your Enthusiasm" pals'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'HER', number: 48, clue: 'P.D. James mystery "Cover ___ Face"'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'ELIZABETH', number: 49, clue: 'My mom\'s first name'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'RID', number: 50, clue: 'Cleansed (of)'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'DVI', number: 51, clue: '506'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'NOUS', number: 52, clue: 'See 72-down'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SPR', number: 53, clue: 'One of the seasons: abbr.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EEL', number: 54, clue: 'Slippery character'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'FIVE', number: 55, clue: 'Half of this clue number'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'FOP', number: 56, clue: 'Dandy'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'DRIPS', number: 57, clue: 'Plumbers\' problems'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'PAN', number: 58, clue: 'Kitchen item'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'SPED', number: 59, clue: 'Hightailed it'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'DINOSAUREGG', number: 60, clue: 'T. Rex of the future'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'OAT', number: 61, clue: 'Quaker piece'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'SCHWA', number: 62, clue: 'One of a pair in Alaska'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'ENTRANT', number: 63, clue: 'Contest hopeful'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 16, dir: 'Down', answer: 'GEE', number: 64, clue: '"Never thought of it that way before"'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 11, col: 17, dir: 'Down', answer: 'GEN', number: 65, clue: 'Marine Corps rank: abbr.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'ZAPS', number: 66, clue: 'Nukes'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'STASES', number: 67, clue: 'Balances'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ACTS', number: 68, clue: '"Macbeth" quintet'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Across', answer: 'NEE', number: 69, clue: 'She was born in France'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PLANETEARTH', number: 70, clue: 'Third of eight'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'PLAZA', number: 70, clue: 'Shopping center'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'LOBES', number: 71, clue: 'Studs go there'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ENTRE', number: 72, clue: 'With 52-down, privately'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'AKIRA', number: 73, clue: '"Ran" man'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'RECON', number: 74, clue: 'Scout activity'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Across', answer: 'DTEN', number: 75, clue: 'Far-right Battleship guess'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'DEBRA', number: 75, clue: 'First name of a 1982, 1983 and 1993 Best Actress nominee'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LOB', number: 76, clue: 'High ball'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'DANKE', number: 77, clue: 'Graz "grazie"'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'WISER', number: 78, clue: 'Older, one hopes'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Down', answer: 'INNS', number: 79, clue: 'Stops for the night'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Down', answer: 'SDAK', number: 80, clue: 'Its state quarter features the heads of four presidents: abbr.'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ABEL', number: 81, clue: 'Genesis name'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 4, dir: 'Down', answer: 'LAY', number: 82, clue: 'Make eggs'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'STICKANDBALL', number: 83, clue: 'Large category of games'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Down', answer: 'KRS', number: 84, clue: 'Rapper ___-One'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 16, dir: 'Down', answer: 'LIE', number: 85, clue: 'False claim'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 15, col: 17, dir: 'Down', answer: 'LAD', number: 86, clue: 'Youngster, sometimes'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'ZETA', number: 87, clue: '___ Jones (grandmother-in-law of Michael Douglas)'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 16, col: 6, dir: 'Across', answer: 'ERROR', number: 88, clue: 'Slip'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 16, col: 12, dir: 'Across', answer: 'NARNIA', number: 89, clue: 'Fictional land named for an Italian village'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'ASHY', number: 90, clue: 'Wan'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 17, col: 6, dir: 'Across', answer: 'SEANS', number: 91, clue: 'Combs and Young'))
clues_mgwcc191_unscrambled.push(Entry.create(row: 17, col: 12, dir: 'Across', answer: 'SKATED', number: 92, clue: 'Enjoyed a pond, perhaps'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #191 - "Depth Squad"', grid: 'COPIED.EPSOM.STIR|AMANDA.RINSE.MENU|MARTINIGLASS.LOAM|..VOTED.ARIES.TWO|BREW..EIFFELTOWER|FIN.OMAN...FALA..|FOURPOSTBED.NEWLY|...SAT..IPAD..KOI|THETHIRDDIMENSION|EEL..FIVE..FOP...|DRIPS.DINOSAUREGG|..ZAPS...ACTS.NEE|PLANETEARTH..DTEN|LOB.DANKE.WISER..|ABEL.STICKANDBALL|ZETA.ERROR.NARNIA|ASHY.SEANS.SKATED', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/2/10', entries: clues_mgwcc191_unscrambled, instructions: instructions, explanation: explanation)
