clues_mgwcc195_unscrambled = Array.new
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ELM', number: 1, clue: '15th most common street name in the U.S.'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ETC', number: 1, clue: 'Abbreviation not pronounced as such'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LOCA', number: 2, clue: 'Ricky Martin title word'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MMCV', number: 3, clue: '93 years from now'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'TAD', number: 4, clue: 'Iota'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TOLSTOY', number: 4, clue: 'Novelist portrayed in 2009 by Christopher Plummer'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALI', number: 5, clue: 'Athlete referenced more times than anyone else in the NYT crossword since 1993'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DAVINCI', number: 6, clue: 'Code name'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'BMX', number: 7, clue: 'Bike letters'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BICE', number: 7, clue: 'He lost Season Four of "American Idol" to Underwood'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'METS', number: 8, clue: 'They went 40-120 in 1962'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'XLS', number: 9, clue: 'Big tees'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'TOMS', number: 10, clue: '___ of Maine (toothpaste brand)'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'SPOILT', number: 11, clue: 'No longer drinkable, as milk'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'DOLAR', number: 12, clue: 'U.S. currency, south of the border'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'DODECA', number: 12, clue: 'Fitting prefix for this clue'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'RESORT', number: 13, clue: 'Family vacation site'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'CIEL', number: 14, clue: 'Sky: Fr.'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Down', answer: 'CAUSAL', number: 14, clue: 'Resulting directly from'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CCCP', number: 15, clue: 'Letters on many spacecraft'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'OLIVE', number: 16, clue: 'Sort of green'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ACTS', number: 17, clue: 'Source of the quote: "Ye men of Athens, I perceive that in all things ye are too superstitious"'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'AVOIDS', number: 18, clue: 'Keeps some distance from'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'ICES', number: 19, clue: 'Treats a bump, maybe'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'ISSUES', number: 20, clue: 'Problems'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'STOA', number: 21, clue: 'Covered walkway'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ICET', number: 22, clue: 'Reality TV rapper'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'NOTS', number: 23, clue: 'Have-___'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'COLECO', number: 24, clue: 'HINT: Number of the letter you must write twice into this grid; CLUE: Video game company of the 1980s'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CAROM', number: 24, clue: 'Ricochet'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ONEBC', number: 25, clue: 'Year in Augustus\'s reign'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'CROATS', number: 26, clue: '2001 Wimbledon hero Goran Ivanisevic et al.'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'TITAN', number: 27, clue: 'Saturn\'s largest moon'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'SAUDS', number: 28, clue: 'Royal family'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CANTSAY', number: 29, clue: 'Keeps silent due to lack of knowledge'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'CAR', number: 29, clue: 'Fiat, for one'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Across', answer: 'ITALIAN', number: 30, clue: 'Sub variety'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'NBA', number: 31, clue: '"Lin-sanity" org.'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ARE', number: 32, clue: '"You ___?"'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'TUB', number: 33, clue: 'Butter container'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ROBUSTO', number: 34, clue: 'Cigar type'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'UNTOLD', number: 35, clue: 'How some stories remain'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SAWN', number: 36, clue: 'Cut'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'TBONED', number: 37, clue: 'Hit perpendicularly'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'OBSEQUY', number: 38, clue: 'Funeral rite'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 9, dir: 'Across', answer: 'ESTRADA', number: 39, clue: 'Poncherello\'s portrayer'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'EARLIER', number: 39, clue: 'Ere'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'SLEEPS', number: 40, clue: 'Crashes'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'TIPS', number: 41, clue: 'You must wait for them'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'RESIST', number: 42, clue: 'Fight back against'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'MCNABB', number: 43, clue: 'Losing quarterback in Super Bowl XXXIX'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ALIENS', number: 44, clue: 'James Cameron hit set on another planet'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'TWOS', number: 45, clue: 'About 17% of Risk rolls'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'REPS', number: 46, clue: 'Agents, for short'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'DIONNE', number: 47, clue: '(The late) Whitney\'s cousin'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'DDAY', number: 47, clue: 'Time of a scheduled military operation'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'IDIP', number: 48, clue: '"Bed in the bush with stars to see, bread ___ in the river"--Robert Louis Stevenson'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'LESION', number: 49, clue: 'Word from the Latin for "injury"'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'OTIS', number: 50, clue: 'Mr. Redding'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NOLO', number: 51, clue: 'One plea, for short'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ADDL', number: 52, clue: 'Extra, briefly'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ASH', number: 52, clue: 'Remains of a 34-across'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'EQUIP', number: 53, clue: 'Deck out'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'UKE', number: 54, clue: 'Ho\'s hands held one'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'STOP', number: 55, clue: 'Knock off'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'PEU', number: 56, clue: 'Un ___ (a little, to the French)'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SAID', number: 57, clue: 'Went'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'DUKES', number: 58, clue: 'Fighters put them up'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'TILE', number: 59, clue: 'Bingo seventh or eighth, usually'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HYP', number: 60, clue: 'Prefix meaning "deficient"'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'YER', number: 61, clue: 'Norah Jones song "Tell ___ Mama"'))
clues_mgwcc195_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SOU', number: 62, clue: 'Tiny bit, to the French'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#195 - "Treasure Hunt"', grid: 'ELM...TAD...BMX|TOMS.DOLAR.CIEL|CCCP.OLIVE.ACTS|.AVOIDS.ISSUES.|...ICET.NOTS...|.COLECO.CROATS.|CANTSAY.ITALIAN|ARE.........TUB|ROBUSTO.ESTRADA|.MCNABB.ALIENS.|...TWOS.REPS...|.DIONNE.LESION.|ADDL.EQUIP.STOP|SAID.DUKES.TILE|HYP...YER...SOU', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/3/9', entries: clues_mgwcc195_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')