clues_mgwcc197_unscrambled = Array.new
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BSIDE', number: 1, clue: 'Second-best song on a 45, usually'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BERET', number: 1, clue: 'Painter\'s cap'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'SAYAH', number: 2, clue: 'Prepare for the tongue depressor'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'IRATE', number: 3, clue: 'Seriously ticked off'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'DEN', number: 4, clue: 'Thieves\' hangout'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'EDGIER', number: 5, clue: 'More appealing to hipsters'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CHILD', number: 6, clue: 'Dependent, often'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CASE', number: 6, clue: 'Etui, e.g.'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HULA', number: 7, clue: 'Motion by the Pacific Ocean'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'IDI', number: 8, clue: 'Forrest played him in "The Last King of Scotland"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LIN', number: 9, clue: 'Jeremy of jump shots'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DOGRACES', number: 10, clue: 'Events that use a fake rabbit'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'HBO', number: 11, clue: '"Game of Thrones" channel'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'HOMEDEPOT', number: 11, clue: 'Store whose website has a "Lumber & Composites" section'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BOOK', number: 12, clue: 'Novel, novella or novelette'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'OOPS', number: 13, clue: '"Wish I could take that one back..."'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EARED', number: 14, clue: 'Like some seals'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'AUDIO', number: 15, clue: 'Sound'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'OOO', number: 16, clue: '"Tic-Tac-Dough" line'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RYANGOSLING', number: 17, clue: 'Best Actor nominee of 2006 for "Half Nelson"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'OKAYS', number: 18, clue: 'Approves'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'MOP', number: 19, clue: 'Item in a janitor\'s closet'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EAT', number: 20, clue: '"Dig in!"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'IKEA', number: 21, clue: 'They sell Klubbo tables and Ektorp chairs'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'REEKS', number: 22, clue: 'Doesn\'t have a pleasing bouquet at all'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'EEL', number: 23, clue: 'Favorite fish of the llama and aardvark?'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'THESEA', number: 24, clue: 'Yachter\'s waters'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'SCAT', number: 25, clue: '"Skedaddle, varmint!"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'BAAED', number: 26, clue: 'Opined like ovines'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'BARACK', number: 26, clue: 'Boss of 61-across'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ALC', number: 27, clue: 'Abbr. on bottles of beer'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'CRYSTALCLEAR', number: 28, clue: 'Unlikely to be misinterpreted'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'SOUPUP', number: 29, clue: 'Make more awesome, like a car'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'TUNIC', number: 30, clue: 'Clothing for Claudius'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ARTS', number: 31, clue: '___ & Letters Daily'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ROSY', number: 32, clue: 'Red, as a complexion'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OSHA', number: 33, clue: 'Dept. of Labor arm'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ONEK', number: 33, clue: '.62 miles'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'SEMI', number: 34, clue: 'Kinda'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'HAIRPIECE', number: 35, clue: 'Rug'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'SOURCE', number: 36, clue: 'Journalist\'s secret'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'PRO', number: 37, clue: 'On the side of'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NEATH', number: 38, clue: 'Not o\'er'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'HAYLOFTS', number: 39, clue: 'Stable storage areas'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'UNA', number: 40, clue: '"___ cerveza, por favor" (words often heard in Cancun)'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'SLOTS', number: 41, clue: 'Vegas fun'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'LETT', number: 42, clue: 'Leon ___ (NFL lineman known for two embarrassing plays)'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EMI', number: 43, clue: 'They own Virgin Records'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ASPICS', number: 44, clue: 'Jellies with pate'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'SPY', number: 45, clue: 'Kim Philby or Robert Hanssen'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'SEGAR', number: 46, clue: 'Cartoonist who created Popeye the Sailor'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ETSY', number: 47, clue: 'Website that\'s "your place to buy and sell all things handmade"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'KIRBYPUCKETT', number: 48, clue: 'MLB All-Star Game MVP, 1993'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'BOG', number: 49, clue: 'Quagmire'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'TEMPEH', number: 50, clue: 'Protein source for vegans'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'POLYP', number: 51, clue: 'Abnormal growth'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'GETSET', number: 52, clue: '"Go!" preceder'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'SMILE', number: 53, clue: '"I\'m about to take your picture!"'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'EXCEL', number: 54, clue: 'Spreadsheet name'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'TIERS', number: 55, clue: 'Wedding cake layers'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AMIGO', number: 56, clue: 'Compadre'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'AJAR', number: 56, clue: 'Close to being closed'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'MOBY', number: 57, clue: 'Techno musician so self-named because he\'s a descendant of Herman Melville'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'SPAM', number: 58, clue: 'Inbox irritations'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SHOP', number: 58, clue: 'Hit the mall'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'PEPE', number: 59, clue: 'Skunk\'s first name'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'MXI', number: 60, clue: '1,001 years ago'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'JOE', number: 61, clue: '26-down\'s right-hand man'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'FISHERPRICE', number: 62, clue: 'Toy company since 1930'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'IRK', number: 63, clue: 'Aggravate'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'SOY', number: 64, clue: '___ milk'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'RUE', number: 65, clue: 'Street of Paris'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ABC', number: 66, clue: '"Cougar Town" network'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TROOP', number: 67, clue: '___ movements (military maneuvers)'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EULER', number: 68, clue: 'Mathematician seen on Swiss 10-franc notes'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RYE', number: 69, clue: 'Bread for a Reuben'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SKYPE', number: 70, clue: 'Videoconferencing website'))
clues_mgwcc197_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'HEELS', number: 71, clue: 'Tricky shoes'))
Puzzle.create(title: 'MGWCC #197 - "Star Search"', grid: 'BSIDE.CHILD.HBO|EARED.AUDIO.OOO|RYANGOSLING.MOP|EAT.IKEA..REEKS|THESEA..BAAED..|...CRYSTALCLEAR|OSHA.SOURCE.PRO|NEATH.UNA.SLOTS|EMI.ASPICS.ETSY|KIRBYPUCKETT...|..POLYP..GETSET|AMIGO..SPAM.MXI|JOE.FISHERPRICE|ABC.TROOP.EULER|RYE.SKYPE.HEELS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/3/23', entries: clues_mgwcc197_unscrambled)
