clues_mgwcc198_unscrambled = Array.new
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CROWD', number: 1, clue: 'Lots of people'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CHACHA', number: 1, clue: 'Dance that rhymes with a Gabor'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'RANOUT', number: 2, clue: 'Left with speed'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ONYXES', number: 3, clue: 'Some gemstones'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'WOW', number: 4, clue: 'Blow away'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DIOR', number: 5, clue: 'French Christian'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ASST', number: 6, clue: 'Abbr. in job titles'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ADDON', number: 6, clue: 'Extend'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SAYIF', number: 7, clue: '"Let\'s just suppose..."'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SNELL', number: 8, clue: 'Fishhook line'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TOTEA', number: 9, clue: '"When I Take My Sugar ___"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'AJC', number: 10, clue: 'Georgia\'s largest newspaper, for short'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ALL', number: 10, clue: 'Hog\'s share'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'JOEPESCI', number: 11, clue: 'He played David Ferrie in "JFK"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CONCRETE', number: 12, clue: 'Specific'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HANOI', number: 13, clue: 'Capital on the Red River'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'DANO', number: 14, clue: 'Paul of "Being Flynn" and "Little Miss Sunshine"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'LOOP', number: 15, clue: 'Chi-town downtown, with "The"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 2, col: 15, dir: 'Down', answer: 'POSSESS', number: 16, clue: 'Take over, as someone\'s body'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ANYWORDYET', number: 17, clue: 'Request for an update'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'REI', number: 18, clue: 'Eastern Mountain Sports rival'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'LENO', number: 19, clue: 'Jovial Jay'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'COX', number: 20, clue: 'Rathvon\'s cruciverbal partner'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'REOILED', number: 21, clue: 'Went after squeaking again'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'DNR', number: 22, clue: 'ER order'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'PCS', number: 23, clue: 'Some desktops'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'HUED', number: 24, clue: 'Many-___ (polychromatic)'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'DEADMEN', number: 25, clue: 'They tell no tales'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'INFLANDERS', number: 26, clue: 'Where Ostende, Antwerp and Ghent are located'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'DEARDAD', number: 27, clue: 'Letter opening, perhaps'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ATSEA', number: 28, clue: 'Far from land'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ALI', number: 29, clue: 'Boxer found in boxes'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'RESEE', number: 30, clue: 'Catch again, as a movie'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ALBERTA', number: 31, clue: 'One of the 42 territories in Risk'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'BCC', number: 32, clue: 'E-mail option, for short'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ECO', number: 33, clue: 'Green, in combinations'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'RON', number: 34, clue: '"The Case for Gold" author Paul'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'TUG', number: 35, clue: 'Yank'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'ANA', number: 36, clue: 'Palindromic United rival'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ACTS', number: 37, clue: 'Pretends'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NORDICCOUNTRIES', number: 38, clue: 'Cold quintet'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'NOSWEAT', number: 38, clue: '"I got ya covered"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'ORIENTAL', number: 39, clue: 'Light blue avenue, in Monopoly'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'REDDFOXX', number: 40, clue: '#24 on Comedy Central\'s list of 100 greatest stand-up comedians'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'TED', number: 41, clue: 'Man\'s name that\'s also a lecture series'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OREM', number: 42, clue: 'Utah Valley University\'s city'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'CONGAED', number: 43, clue: 'Danced like a Cuban'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SIDER', number: 44, clue: 'Supply-___ (kind of economist)'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'REV', number: 45, clue: 'Show off, like your Harley\'s engine'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'DARTS', number: 46, clue: 'Pub fun'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'RETORT', number: 47, clue: 'It may be snappy'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'TEETER', number: 48, clue: 'Balance precariously'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'SPEEDY', number: 49, clue: 'Rapid'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'WEDNESDAYS', number: 50, clue: 'Once a week, sometimes'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'SEMIS', number: 51, clue: 'Interstate giants'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'DRACO', number: 52, clue: 'Constellation near Hercules and Cygnus'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ABREU', number: 53, clue: 'Bobby with 284 home runs'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'YOKEL', number: 54, clue: 'Hardly a sophisticate'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'SSE', number: 55, clue: 'Way to go, for short'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'DEEP', number: 56, clue: 'Not easy to understand at first reading'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ENF', number: 57, clue: 'Part of LEO'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'VERBOSE', number: 58, clue: 'Wordy'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'EDGE', number: 59, clue: 'Small lead'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TEE', number: 60, clue: 'Titleist\'s perch'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ATOM', number: 61, clue: 'There\'s trouble when it\'s split'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'MIX', number: 62, clue: 'Be social, at a party'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'MARKEDNOTE', number: 63, clue: 'Bill to foil bank robbers'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'NON', number: 64, clue: 'L\'antonyme de "oui"'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TAXI', number: 65, clue: 'Classic 1970s-80s sitcom with a wordless theme song'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ICEE', number: 66, clue: 'Frozen drink brand'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'GORED', number: 67, clue: 'Mauled, like matadors'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 15, col: 2, dir: 'Across', answer: 'LXX', number: 68, clue: '+2, to Tacitus'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SOUL', number: 69, clue: 'Record store section'))
clues_mgwcc198_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ENTRY', number: 70, clue: 'Contest submission'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#198 - "National Assembly"', grid: 'CROWD.ASST.AJC.|HANOI.DANO.LOOP|ANYWORDYET.LENO|COX.REOILED.PCS|HUED.INFLANDERS|ATSEA.....RESEE|...ALBERTA.ACTS|NORDICCOUNTRIES|OREM.CONGAED...|SIDER.....DARTS|WEDNESDAYS.DEEP|ENF.VERBOSE.TEE|ATOM.MARKEDNOTE|TAXI.ICEE.GORED|.LXX.SOUL.ENTRY', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/3/30', entries: clues_mgwcc198_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')