clues_mgwcc019_unscrambled = Array.new
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JAM', number: 1, clue: 'Paper ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JAB', number: 1, clue: 'Hit'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ABADIDEA', number: 2, clue: 'Not advisable'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MONIKERS', number: 3, clue: 'Nicknames'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'SML', number: 4, clue: 'Size choices, for short'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SNIPED', number: 4, clue: 'Outbid at the last second, as in an eBay auction'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'MTN', number: 5, clue: 'Pk.'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LOG', number: 6, clue: 'Put in, as hours'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'FLICKS', number: 7, clue: 'Chick ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'FRANC', number: 7, clue: 'Rwandan ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LINDA', number: 8, clue: 'Blair or Evans'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ICK', number: 9, clue: '"I\'m not touching that"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CHIA', number: 10, clue: '___ Pet ("the pottery that grows")'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'KINGME', number: 11, clue: 'Demand for additional powers'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SEGUES', number: 12, clue: 'Shifts'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ABOONTO', number: 13, clue: 'Highly profitable for'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 2, col: 4, dir: 'Down', answer: 'OKOK', number: 14, clue: '"Alright already"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'RICHIE', number: 15, clue: 'He sang a #1 duet with Ross'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BANKINGTANKING', number: 16, clue: 'Goldman Sachs at $120/share on Monday 10/6/08, down to $80/share today, and Morgan Stanley down from $23 to $5 in the same period, for example'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'TEE', number: 17, clue: 'Bag peg'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'DIOP', number: 18, clue: '7-foot Dallas Mavericks center DeSagana ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'END', number: 19, clue: 'Wind up'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'AGUA', number: 20, clue: 'Restaurante request'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 4, col: 15, dir: 'Down', answer: 'AWE', number: 21, clue: 'Leave breathless'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NIKKEIDECAY', number: 22, clue: 'A noted index falling from 10,700 on Monday 10/6/08 to 8,300 today'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'NAAN', number: 22, clue: 'Palindromic food'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'IRAQI', number: 23, clue: 'Basran, e.g.'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'DUMB', number: 24, clue: '___ down (simplify)'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'YOST', number: 25, clue: '1952 All-Star third baseman Eddie'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'MEW', number: 26, clue: 'Siamese sound'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ADE', number: 27, clue: 'Lime suffix'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'DRU', number: 28, clue: '"All the King\'s Men" actress, 1949'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'OBESE', number: 29, clue: 'Bigger than big'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'BORE', number: 30, clue: 'Soporific interlocutor'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AERO', number: 31, clue: 'Inflatable mattress brand'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'ODOR', number: 32, clue: 'Body ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'AMP', number: 33, clue: 'Concert piece'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'PAM', number: 34, clue: 'Non-stick cooking spray'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'ESO', number: 35, clue: 'That: Sp.'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'EKING', number: 35, clue: '___ out (managing)'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NASDAQBACKTRACK', number: 36, clue: 'A stock exchange slipping from 1,900 on Monday 10/6/08 to 1,550 today'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'AHAB', number: 37, clue: 'Fictional sailor'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'CAAN', number: 38, clue: '"The Godfather" Oscar nominee'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'ALLINFOR', number: 39, clue: 'Backing 100%'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'CHINAINK', number: 40, clue: 'Black writing material'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'KING', number: 41, clue: '"It" author'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'OHI', number: 42, clue: '"___ get it!"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'MAI', number: 43, clue: 'With 69-across, one place to find a wet umbrella'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ELHI', number: 44, clue: 'Thru 12th grade'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'TIARA', number: 45, clue: 'Wedding ___'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'TIM', number: 45, clue: 'Director Burton'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ISABEL', number: 46, clue: 'Worst Atlantic hurricane of 2003'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'ATTUNE', number: 47, clue: 'Get used to'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ANA', number: 48, clue: '2008 Australian Open finalist Ivanovic'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'AGOUTI', number: 49, clue: 'South American rodent'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'LIN', number: 50, clue: 'New York\'s Maya ___ Studio'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'IST', number: 51, clue: '-follower'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'BOEINGGOING', number: 52, clue: 'Dow Jones stock trading at $53 on Monday 10/6/08 but flying down to $41 today'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'OMEGA', number: 53, clue: 'Literally, "great O"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'EATEN', number: 54, clue: 'Swallowed'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'INT', number: 55, clue: 'Bank abbr.'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'OOFS', number: 56, clue: 'Sounds from the just-punched'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MATE', number: 57, clue: 'Defeat, in a way'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'EFGH', number: 58, clue: 'I will often go after them in elementary schools'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'MAN', number: 59, clue: '"That\'s amazing!"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'OONA', number: 60, clue: 'Charlie\'s wife'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Across', answer: 'BUFFETTSTUFFIT', number: 61, clue: 'My comment to the billionaire thug who stridently pushed the bailout with economic threats against the American people, then pocketed huge sums of money from it as the markets collapsed this week anyway'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'FAM', number: 62, clue: '\'Rents and sibs'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'SGT', number: 63, clue: 'Army rank: abbr.'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'TEA', number: 64, clue: 'Black or green'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'TEO', number: 65, clue: 'Queen\'s "___ Torriate"'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 14, col: 2, dir: 'Across', answer: 'ENGAGE', number: 66, clue: 'Fight'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'GETSONE', number: 67, clue: 'Finally comes up with a correct answer, as a hapless game show contestant'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 15, col: 2, dir: 'Across', answer: 'LEHMAN', number: 68, clue: 'Failed investment bank, familiarly'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'TAI', number: 69, clue: 'See 43-across'))
clues_mgwcc019_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'RKO', number: 70, clue: 'Studio that produced "King Kong"'))
instructions = 'This week\'s contest answer phrase is the two-word insult that ends the entry at 61-across (i.e. the last words in the entry at 61-Across).'
explanation = '<MA>STUFF IT</MA><TEXT>Should be self-explanatory.</TEXT>'
Puzzle.create(title: 'MGWCC #19 - "Bailout: Fail, Rout"', grid: 'JAM.SML.FLICKS.|ABOONTO.RICHIE.|BANKINGTANKING.|.DIOP..END.AGUA|NIKKEIDECAY.MEW|ADE.DRU...OBESE|AERO.AMP.ESO...|NASDAQBACKTRACK|...OHI.MAI.ELHI|TIARA...ANA.LIN|IST.BOEINGGOING|MATE.MAN..OONA.|.BUFFETTSTUFFIT|.ENGAGE.GETSONE|.LEHMAN.TAI.RKO', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2008/10/24', entries: clues_mgwcc019_unscrambled, instructions: instructions, explanation: explanation)
