clues_mgwcc200_unscrambled = Array.new
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'RCRUSOE', number: 1, clue: 'Fictional character based on Scottish sailor Alexander Selkirk'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'RFAMILY', number: 1, clue: 'Missing Swiss'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CRUISEOFF', number: 2, clue: 'Leave casually, on a boat'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RANRAGGED', number: 3, clue: 'Wore out'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'UNTO', number: 4, clue: 'Old-school preposition'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SKI', number: 5, clue: 'Indulge at Davos'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OLEARY', number: 6, clue: 'She had a cow'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'EYELID', number: 7, clue: 'Pupil\'s cover'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'CAMEF', number: 8, clue: 'Was a pioneer'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CONTRA', number: 8, clue: 'Against: Lat.'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ACE', number: 9, clue: 'It may have three diamonds'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'MAINE', number: 10, clue: 'Its highest peak is Mt. Katahdin'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ERDOS', number: 11, clue: 'Traveling mathematician'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'FBASE', number: 12, clue: 'Target usually overrun'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'FRANKLY', number: 13, clue: '"If we\'re being honest..."'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'LOCARB', number: 14, clue: 'Like some recipes'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Down', answer: 'LOS', number: 14, clue: '___ Fresnos, Tex.'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'AUNTIEEM', number: 15, clue: 'Gale female'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'MEL', number: 16, clue: 'Crazed fan on "Flight of the Conchords"'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'ONEIDA', number: 17, clue: 'Longtime New Yorkers'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MIRO', number: 18, clue: 'Barcelona-born artist'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'ALEAST', number: 19, clue: 'The Rays and the Jays, et al.'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'ALIBI', number: 20, clue: 'Good defense'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'NOS', number: 21, clue: 'Some answers'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ISA', number: 22, clue: 'Simple Plan song "Your Love ___ Lie"'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'BRILL', number: 23, clue: 'Eponymous 1990s media magazine founder Steven ___'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'BSS', number: 23, clue: 'Some coll. degrees'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'REESE', number: 24, clue: 'Confectioner Harry Burnett ___'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'EMMAS', number: 25, clue: 'Woodhouse and Watson'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LEG', number: 26, clue: 'Trip section'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SYD', number: 27, clue: 'Pink Floyd name'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'IMAM', number: 28, clue: 'Kind of 46-down'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'MCS', number: 29, clue: 'They rock the mike'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'YOGIS', number: 30, clue: 'Flexible individuals'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'INRED', number: 31, clue: 'Dressed to dazzle, perhaps'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'BBC', number: 32, clue: 'Telly option'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'BRT', number: 32, clue: 'NBA MVP, 2007-2008'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'MSS', number: 33, clue: 'Novelists submit them: abbr.'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'SCLEROTIC', number: 34, clue: 'Inflexible'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'STEVENASH', number: 35, clue: 'NBA MVP, 2004-2005 & 2005-2006'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'FEN', number: 36, clue: 'Wetland'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'BIRIS', number: 37, clue: 'Rice dishes'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'BAT', number: 37, clue: 'Try for a hit'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'IMSAD', number: 38, clue: '"Things are getting me down"'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'ACT', number: 39, clue: 'Do a dress rehearsal, say'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'FDR', number: 40, clue: 'Philosophical opponent of Sen. Taft'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'AMT', number: 41, clue: 'Sum: abbr.'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ASLEW', number: 42, clue: '___ of (many)'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'ART', number: 42, clue: 'Works on walls'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'WEIGHTB', number: 43, clue: 'Furniture often grunted upon'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'EMTS', number: 44, clue: 'They can administer IVs'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'MERGER', number: 45, clue: 'Corporate combining'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'CCR', number: 46, clue: 'The Fogerty Bros. and bandmates'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'CLERIC', number: 46, clue: 'Holy person'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'COMETH', number: 47, clue: 'O\'Neill title word'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'EVE', number: 48, clue: 'Sistine Chapel figure'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'EVADE', number: 49, clue: 'Escape'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'ERICS', number: 49, clue: 'Google\'s CEO, 2001-2011'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'VOCAB', number: 50, clue: 'Brief words?'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'ADELE', number: 51, clue: 'Grammys queen of 2012'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'ALLOT', number: 52, clue: 'Distribute'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'LEOS', number: 53, clue: 'Policemen and women, for short'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'REI', number: 54, clue: 'King of Brazil'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ROD', number: 55, clue: '___ Laver Arena (Australian Open venue)'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'REDEEM', number: 56, clue: 'Save'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'EER', number: 57, clue: 'Slogan\'s ending'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'PONG', number: 58, clue: 'Ping follower'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'PURR', number: 58, clue: 'Run smoothly, as a car\'s motor'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ICEAGE', number: 59, clue: 'Cold spell'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'ALE', number: 60, clue: 'Drink in a bar'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'OREMUTAH', number: 61, clue: '"Family City USA"'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'MAU', number: 62, clue: 'Egyptian ___ (cat breed)'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CALLER', number: 63, clue: '"First-time" person'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'SITARIST', number: 64, clue: 'Indian strummer'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SBEER', number: 65, clue: '"The Brew That Grew With the Great Northwest"'))
clues_mgwcc200_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'CHURCHB', number: 66, clue: 'Pew'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#200 - "Game of the Century"', grid: 'RCRUSOE...CAMEF|FRANKLY..LOCARB|AUNTIEEM.ONEIDA|MIRO.ALEAST.NOS|ISA.BRILL.REESE|LEG.SYD.IMAM...|YOGIS..BBC.MSS.|.FEN.BIRIS.ACT.|.FDR.AMT..ASLEW|...EMTS.CCR.EVE|EVADE.ALLOT.REI|ROD.REDEEM.PONG|ICEAGE.OREMUTAH|CALLER.SITARIST|SBEER...CHURCHB', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/4/13', entries: clues_mgwcc200_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')