clues_mgwcc201_unscrambled = Array.new
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PDQV', number: 1, clue: 'Circumstance\'s partner'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'POD', number: 1, clue: 'Set of cubicles'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'DCCKUYROB', number: 2, clue: 'Small egg-carrying tubes, in biology'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'QUCCGWLWA', number: 3, clue: 'Hardly the lead'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'VVAS', number: 4, clue: 'ASAP cousins'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'VIZF', number: 5, clue: 'Sandler of "Just Go With It"'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'VKHFF', number: 5, clue: 'Lower (oneself)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IHNSA', number: 6, clue: 'Group elder'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ZDTAZ', number: 7, clue: 'Poe\'s middle name'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'FYX', number: 8, clue: '"The Simpsons" role'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'CTQBU', number: 9, clue: 'Unlike dirt roads'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CDJRTMOET', number: 9, clue: 'Little punk'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TNGQUI', number: 10, clue: 'Patronized a pizzeria, say'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'QESFQ', number: 11, clue: 'Bulgaria\'s third largest city'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BCQHA', number: 12, clue: '1985 movie based on a Nicholas Gage book'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'UISXG', number: 13, clue: 'Slept soundly'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OCUV', number: 14, clue: 'Roman poet'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'KHDY', number: 15, clue: 'Western necktie'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'DNECI', number: 16, clue: 'Author Calvino'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DCCADHNTX', number: 17, clue: 'Al Gore\'s predecessor'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'DVU', number: 18, clue: 'America\'s currency: abbr.'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'JGSQS', number: 19, clue: 'Gossip blogger ___ Hilton'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 4, col: 2, dir: 'Across', answer: 'KCSVFSA', number: 20, clue: 'Body of water by Antarctica'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'RQFHX', number: 21, clue: 'Sun, for Germans (anagram of NONES)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'EUG', number: 22, clue: '"Pardon me, my good fellow..."'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'EVQRG', number: 22, clue: 'Not a club, heart or diamond'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'UFAZUDTUQAG', number: 23, clue: 'He played Jerry Lee Lewis in "Great Balls of Fire!"'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'UKLBE', number: 24, clue: 'Opponent of 40-across, in a 1980s war'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'DYID', number: 25, clue: 'Yearly presidential speech, for short'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'VYWP', number: 26, clue: 'Preferred meat in Washington, D.C.'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'PVN', number: 27, clue: 'Hawaiian peak Mauna ___'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'KYMI', number: 28, clue: 'Easy victory'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'QRLVH', number: 29, clue: 'Fleshy plants'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'HBNWYQNLN', number: 30, clue: 'Flip-floppers'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'BNLIO', number: 31, clue: 'Price of government bonds, casually'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'BDJOH', number: 31, clue: 'Zookeeper\'s injection, for short'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'NJS', number: 32, clue: 'Stimpy\'s bud'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ZTW', number: 33, clue: '___ treatments'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'ZIVAKETQD', number: 33, clue: 'Takes things to the next level'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'TYWDQWMSA', number: 34, clue: 'Make inroads'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'WFHOT', number: 35, clue: 'Quicken Loans ___ (where the Cleveland Cavaliers play)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ROWNBIDJBDEHIYF', number: 36, clue: 'First coin issued in a familiar set, 1999'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ILJF', number: 37, clue: 'Smelling ___ (suspicious)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'HAU', number: 38, clue: '___ Speedwagon ("Roll With the Changes" band)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'GBA', number: 39, clue: 'Ending for Bhutan or Nepal'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'NLJSE', number: 40, clue: 'Opponent of 24-down, in a 1980s war'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'TAVWH', number: 41, clue: 'Pseudonymous Nancy Drew creator Carolyn ___'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'IWJO', number: 42, clue: 'Ending for many central Asian nations'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'IJCWEY', number: 42, clue: 'Becomes accepted, as a new reality'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'UADO', number: 43, clue: 'Ready for business'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'KNEJYFHQQVG', number: 44, clue: 'Exactly what someone said'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'KRCFW', number: 44, clue: 'Swimming pool measurement'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'NIPEU', number: 45, clue: 'Tater state'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'EFGOU', number: 46, clue: 'Late ___ (night owl)'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'QHZUZ', number: 47, clue: 'Home to the Huskies'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'QSLYJ', number: 48, clue: '___ and aahed'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'VUXJE', number: 49, clue: 'Morgan of "30 Rock"'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'GVE', number: 50, clue: 'Atty.'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'KQT', number: 51, clue: 'Metro stop: abbr.'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'RIFCQ', number: 52, clue: 'She sings "Those Were the Days" with Archie'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'HSUVCEW', number: 53, clue: 'Ford of the 1950s'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'CWSK', number: 54, clue: 'Tiny battery'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CPGWN', number: 55, clue: 'No longer in style'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'DZLXEWTMF', number: 56, clue: 'Capital on the Persian Gulf'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'DJA', number: 56, clue: 'Classic 1950 movie that begins with a man reporting his own murder to the police'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'FUU', number: 57, clue: 'Mr. Stewart'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'FEOEL', number: 58, clue: 'Very common word with two very common homonyms'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'JUYJ', number: 59, clue: 'First-floor apartment'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'SQSU', number: 60, clue: 'Self-'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'WUUYN', number: 61, clue: 'Devil\'s pair'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'AZJE', number: 62, clue: 'Williams or Warhol'))
clues_mgwcc201_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'KDAU', number: 63, clue: 'Copied'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #201 - "Chain Letters"', grid: 'PDQV.VIZF.CTQBU|OCUV.KHDY.DNECI|DCCADHNTX.JGSQS|.KCSVFSA..RQFHX|EUG.UFAZUDTUQAG|VYWP....KYMI...|QRLVH.BNLIO.ZTW|ROWNBIDJBDEHIYF|GBA.NLJSE.TAVWH|...IWJO....UADO|KNEJYFHQQVG.KQT|RIFCQ..HSUVCEW.|CPGWN.DZLXEWTMF|FEOEL.JUYJ.SQSU|WUUYN.AZJE.KDAU', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/4/20', entries: clues_mgwcc201_unscrambled, instructions: instructions, explanation: explanation)
