clues_mgwcc208_unscrambled = Array.new
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'HAI', number: 1, clue: '"Bali ___"'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'HUGO', number: 1, clue: 'Fantasy award'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARID', number: 2, clue: 'Saharan'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'INFORMANT', number: 3, clue: 'Rat'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'ALLOW', number: 4, clue: 'Let slide'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ADO', number: 4, clue: 'Shakespeare title word'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'LEFTHOME', number: 5, clue: 'Went out on one\'s own'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LEGIT', number: 6, clue: 'Walk'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ORAN', number: 7, clue: 'Mediterranean port'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'WEBS', number: 8, clue: 'Woven pads'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'GOALS', number: 9, clue: 'Messi\'s non-misses'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'GABLES', number: 9, clue: 'Architectural features'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'OUR', number: 10, clue: 'Popular possessive pronoun'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AROSE', number: 11, clue: 'Was the topic of conversation'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LIKUD', number: 12, clue: 'Bibi\'s party'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SCENE', number: 13, clue: 'Theater instructor\'s shout'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'URN', number: 14, clue: 'Decorative piece, often'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'DEERE', number: 15, clue: 'John ___ Classic (annual golf tournament)'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'AURIC', number: 16, clue: 'James\'s enemy, in one movie'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GIFTOFGAB', number: 17, clue: 'Blarney Stone conferral'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'TRIA', number: 18, clue: 'Three: Lat.'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'BROKE', number: 19, clue: 'Not just low on funds'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ODOR', number: 20, clue: 'Suggestion'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'TINSEL', number: 21, clue: 'December decoration'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ERA', number: 22, clue: 'Time of history'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'SUN', number: 23, clue: 'Phoenix ballplayer'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'RIGHT', number: 24, clue: 'True'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'GTOS', number: 25, clue: 'Classic Pontiacs'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'RECEDE', number: 26, clue: 'Get less prominent'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'CHAO', number: 27, clue: 'Cabinet member under Bush'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TOMATO', number: 28, clue: 'Bruschetta ingredient'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'TAFT', number: 28, clue: 'He was large and in charge'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OHIO', number: 29, clue: 'Cairo\'s river'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'CRASH', number: 30, clue: 'Turn in'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'CHESS', number: 30, clue: 'The mating game'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'RANT', number: 31, clue: 'Go off on a tangent'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AHA', number: 32, clue: '"Interesting!"'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'OMAHA', number: 33, clue: 'Its largest newspaper is the World-Herald'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'AVID', number: 34, clue: 'Enthusiastic'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'APIA', number: 35, clue: 'City where Polynesian Airlines is headquartered'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'PRETTYONE', number: 36, clue: '"My Sharona" moniker'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'IDDO', number: 37, clue: '"That\'s what ___ if I were you"'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ASSN', number: 38, clue: 'Org.'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'FINDSEVENBWORDS', number: 39, clue: 'How to solve the meta'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'DOCK', number: 40, clue: 'Marina structure'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'BOBAFETT', number: 41, clue: '"Star Wars" bounty hunter'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'WOOL', number: 42, clue: 'Itchy stuff'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TOTO', number: 43, clue: 'Hollywood barker'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ISTOO', number: 44, clue: 'Half of a childish argument'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'EDS', number: 45, clue: 'Copy chiefs: abbr.'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'CLODS', number: 46, clue: 'Clumsy folk'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'LOWERS', number: 47, clue: 'Puts down'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'OOH', number: 48, clue: '"Amazing!"'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'BOSTON', number: 49, clue: 'Brahmin\'s city'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SUEZ', number: 50, clue: 'Gulf of ___ (Red Sea arm)'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CUCKOO', number: 51, clue: 'Wild'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'CANED', number: 51, clue: 'Punished corporally'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'UNITY', number: 52, clue: 'Baha\'i tenet'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'CACHE', number: 53, clue: 'Secret supply'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SALUT', number: 54, clue: 'Drinking word'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'SIENA', number: 54, clue: 'Tuscan province'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ANA', number: 55, clue: 'Palindromic airline'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'WHATIF', number: 56, clue: '"Say..."'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'AGRA', number: 57, clue: 'City on the Yamuna River'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'TRAM', number: 58, clue: 'Kind of public transportation'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'EYES', number: 59, clue: 'You\'re using them now'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ENID', number: 60, clue: 'Great Plains city named for a character in English literature'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SEAU', number: 61, clue: 'Late Junior'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'NICHE', number: 62, clue: 'Market section'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'HER', number: 63, clue: 'That lady'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'GREENZONE', number: 64, clue: 'Baghdad area'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'NOI', number: 65, clue: '"___ didn\'t!"'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ETHER', number: 66, clue: 'Cyberspace'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'RANTO', number: 67, clue: 'Sought assistance from'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'NIA', number: 68, clue: 'Pilates alternative'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DYERS', number: 69, clue: 'They work with vats'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'AMATI', number: 70, clue: 'Nice violin'))
clues_mgwcc208_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'EDU', number: 71, clue: 'www.carleton.___'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#208 - "Lost Island"', grid: 'HAI.ALLOW.GOALS|URN.DEERE.AURIC|GIFTOFGAB.BROKE|ODOR.TINSEL.SUN|..RIGHT..RECEDE|TOMATO.CRASH...|AHA.OMAHA..APIA|FINDSEVENBWORDS|TOTO..ISTOO.EDS|...CLODS.BOSTON|CUCKOO..SALUT..|ANA.WHATIF.EYES|NICHE.GREENZONE|ETHER.RANTO.NIA|DYERS.AMATI.EDU', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/6/8', entries: clues_mgwcc208_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')