clues_mgwcc210_unscrambled = Array.new
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MCCC', number: 1, clue: 'Middle Ages leap year'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MPTY', number: 1, clue: 'Seriously in danger of running out of gas'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'CUBA', number: 2, clue: 'Largest of the West Indies'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'CZAR', number: 3, clue: 'Old Russian'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'CORNERSMONUMENT', number: 4, clue: 'It\'s found where Utah, Arizona, New Mexico and Colorado meet'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'LATER', number: 5, clue: '"Bye-bye!"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'LOCKUP', number: 5, clue: 'Incarcerate'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ACHE', number: 6, clue: 'Dull pain'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'THINNINGSTRETCH', number: 7, clue: 'Baseball break'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ERR', number: 8, clue: 'Make a false step'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'REPAINTS', number: 9, clue: 'Puts another coat on'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'NOSH', number: 10, clue: 'Graze'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'NESSEEERNIEFORD', number: 10, clue: 'Country great named for a state'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OTTO', number: 11, clue: '___ von Bismarck (unifier of Germany)'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'STEP', number: 12, clue: 'Like some facilitated programs'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HUMS', number: 13, clue: 'Dull sounds'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PUZO', number: 14, clue: '"The Godfather" author Mario'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'OCHRE', number: 15, clue: 'Earthy tone'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ETTU', number: 16, clue: 'Phrase to the traitorous Brutus'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'TBAR', number: 17, clue: 'Ski resort contraption'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'CHIRP', number: 18, clue: 'Canary\'s sound'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'STEM', number: 19, clue: 'Come (from)'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'YARN', number: 20, clue: 'Tall tale'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'KEN', number: 21, clue: '"Jeopardy!" juggernaut Jennings'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'AESOPS', number: 22, clue: '___ Fables'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'EVE', number: 23, clue: 'Night before'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'EMU', number: 24, clue: 'Meat on Melbourne menus'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'MAO', number: 25, clue: 'Dictator mentioned by John Lennon in "Revolution"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'NAIVE', number: 26, clue: 'Willing to believe anything'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'AFOOT', number: 27, clue: 'Underway'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TSTRAP', number: 28, clue: 'Kind of shoe'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'THEMS', number: 28, clue: '"___ the breaks!"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'SODOI', number: 29, clue: '"Same here!"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'TWANG', number: 30, clue: 'Feature of Dwight Yoakam\'s voice'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'IFNEEDBE', number: 31, clue: 'Should suboptimal circumstances arise'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'DRUID', number: 32, clue: 'Ancient Brit'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'BASTA', number: 33, clue: '"Enough!" in Europe'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ESSAY', number: 34, clue: 'Academic paper'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HOWSO', number: 35, clue: '"Can you explain what you mean by that?"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'SNOT', number: 36, clue: '___-nosed kid'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SOUSE', number: 36, clue: 'Heavy drinker'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ERAS', number: 37, clue: 'Times'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'EDAM', number: 38, clue: 'Cheese that\'s made backwards?'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'GOGOS', number: 39, clue: 'Belinda Carlisle\'s old band, with "The"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'GOODNEWS', number: 39, clue: 'Happy messenger\'s shout'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'RUSS', number: 40, clue: 'Former Wisconsin senator Feingold'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MONO', number: 41, clue: 'Kisser\'s condition'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'OUST', number: 42, clue: 'Boot out'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ANITA', number: 43, clue: 'Baker or Bryant'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'ART', number: 43, clue: 'John Singer Sargent\'s field'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SIGNPOST', number: 44, clue: 'Traveler\'s guide'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'PDA', number: 45, clue: 'Handheld device'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'FRIDAY', number: 46, clue: 'Rebecca Black\'s YouTube hit'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'FRESNO', number: 46, clue: 'California city'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'UDDER', number: 47, clue: '___ nonsense (what a goofy cow spouts)'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'RTE', number: 48, clue: 'Numbered rd.'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ICEMAN', number: 49, clue: '"The ___ Cometh" (Eugene O\'Neill play)'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'IMPS', number: 49, clue: 'Little devils'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'CENT', number: 50, clue: '"Get Rich or Die Tryin\'" rapper'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ERIE', number: 51, clue: 'Great Lakes port'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ERE', number: 52, clue: 'Heir\'s homophonic palindrome'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'REAM', number: 53, clue: 'Lots of paper'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'FRAT', number: 54, clue: 'Word before brother or house'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'RAYE', number: 55, clue: 'Old-school comic Martha'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ATEN', number: 56, clue: 'Egyptian sun god'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'THST', number: 57, clue: 'Carnegie Hall\'s address: abbr.'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MERE', number: 58, clue: 'Hardly worth mentioning'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'ESTES', number: 59, clue: '___ Park, Colo.'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'SEC', number: 60, clue: 'Brief moment?'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'OATH', number: 61, clue: 'Serious words'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PNIN', number: 62, clue: 'Title professor in a Nabokov book'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'WECAN', number: 63, clue: 'Follower of "Yes," in a political slogan'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'RYES', number: 64, clue: 'Hard liquors'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'STET', number: 65, clue: 'Latin for "let it stand"'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SCHMO', number: 66, clue: 'Joe ___ (average guy)'))
clues_mgwcc210_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'DENT', number: 67, clue: 'Impala imperfection'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#210 - June 8th, 2012 - Take a Number', grid: 'MCCC.LATER.NOSH|PUZO.OCHRE.ETTU|TBAR.CHIRP.STEM|YARN.KEN.AESOPS|...EMU.NAIVE...|TSTRAP.IFNEEDBE|HOWSO.SNOT.ERAS|EDAM.GOGOS.RUSS|MONO.OUST.ANITA|SIGNPOST.FRIDAY|...UDDER.RTE...|ICEMAN.ERE.FRAT|MERE.ESTES.OATH|PNIN.WECAN.RYES|STET.SCHMO.DENT', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/6/22', entries: clues_mgwcc210_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')