clues_mgwcc213_unscrambled = Array.new
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CABOX', number: 1, clue: 'Make two moves in a row, perhaps'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'CAP', number: 1, clue: 'Baseball stadium purchase'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AAI', number: 2, clue: 'Percy Sledge\'s "Take Time to Know ___"'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BBF', number: 3, clue: 'Crossword finish'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OSQWYA', number: 4, clue: 'Plane\'s lanes'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'XEJT', number: 5, clue: 'Branch manager'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'BTL', number: 6, clue: 'She can go either way'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BBNBXGESDKY', number: 6, clue: 'Top part of a classical building'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TRA', number: 7, clue: 'Cleverness'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'LSOWAHSGLWI', number: 8, clue: 'Plus'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'IGOXI', number: 9, clue: 'Attach'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ICLR', number: 9, clue: 'About 4,047 square meters'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'GTHDHP', number: 10, clue: 'Tuck and more'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OXU', number: 11, clue: 'Turning cooler'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'XMD', number: 12, clue: 'Financial company with ads making fun of their own name'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'IBQ', number: 13, clue: 'Marks, sometimes'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AABSE', number: 14, clue: 'Literally, "gods"'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'BRS', number: 15, clue: 'One of (Henry) Miller\'s Paris friends'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'CTXMB', number: 16, clue: 'Common origami sculpture'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PIFQJWNAOXLHUDQ', number: 17, clue: 'Perform a wedding ceremony task'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'WMPEGI', number: 18, clue: 'Family tree members'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'XAIDNI', number: 19, clue: 'Balladeer Badu'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'WTMB', number: 20, clue: 'Bun-haired princess'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'WARD', number: 21, clue: 'Section'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'VRYY', number: 22, clue: 'Ice off Iceland'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'VKOQS', number: 22, clue: 'Uses American services'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'RNEXJ', number: 23, clue: 'Butterfly of the future'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'YNXEL', number: 24, clue: 'Southern or Indian'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'PXOAI', number: 25, clue: 'Dark wood'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'OWQ', number: 26, clue: 'Well liquid'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'HCHI', number: 27, clue: 'February flower'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'COXML', number: 28, clue: 'Monkey\'s cousin'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'HBARP', number: 29, clue: 'American gold medalist at the 1996 Olympics'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'IVWEB', number: 30, clue: 'Deserves'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'KNNA', number: 31, clue: 'Mille ___ County, Minn.'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'EGWHD', number: 32, clue: 'Suddenly make sense'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'POBV', number: 33, clue: 'Mexican miss, briefly'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OEX', number: 34, clue: 'More than hostility'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'VGEQSNP', number: 35, clue: 'Drink source'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'VIGO', number: 35, clue: '"It\'s not ___..."'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'PWHA', number: 36, clue: 'D.C. barker of the 1940s'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'XAW', number: 37, clue: 'Airport abbr.'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'QXE', number: 38, clue: 'Model Mendes'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'IIS', number: 39, clue: 'Presidential inits.'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'GIW', number: 40, clue: 'Hospital worker\'s deg.'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'MRE', number: 41, clue: 'She can go either way, too'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SJLXG', number: 42, clue: 'Arabic-speaking capital'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'XZSASL', number: 43, clue: 'Howard of "Little Shop of Horrors"'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'DUL', number: 44, clue: 'Put to work'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'UYP', number: 45, clue: 'House girl'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'HALPB', number: 46, clue: 'Hose brand'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'AMARNQ', number: 47, clue: 'Foreign-language phrase usually abbreviated'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'ZOJKYWQAM', number: 48, clue: 'Watching intently'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'JNWVTE', number: 49, clue: 'Common protection in a rainstorm'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'QKGTND', number: 50, clue: 'One key'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'HWS', number: 51, clue: 'Loudest word heard in the library, often'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HJPYA', number: 51, clue: 'Cut'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'WRICS', number: 52, clue: 'Word from the Greek for "twisted"'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'NYPIK', number: 53, clue: 'Mae and Adam'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'AZI', number: 54, clue: 'Letters that denote the structure of many blues compositions'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'ZOBPW', number: 55, clue: 'Naproxen, commercially'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'IWNMF', number: 56, clue: 'On a boat'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'JRARW', number: 57, clue: 'Terrible move, in old chess slang'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'RQRN', number: 58, clue: 'Dim, drawn dog'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'GZROW', number: 59, clue: 'Plant late in the year'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'ZCHR', number: 60, clue: 'Slimy food'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'KPISQVC', number: 61, clue: 'Chivalrous type'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'KQY', number: 61, clue: 'Nixon or Buchanan'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'CSC', number: 62, clue: 'Turn down, casually'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'CTCNBNW', number: 63, clue: 'Most slathered on, like makeup'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'CQH', number: 63, clue: 'Calcium sulfide, for short'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'WYM', number: 64, clue: 'Recipe abbr.'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'QYCLRTS', number: 65, clue: 'Stoopid'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'QNHQPMY', number: 66, clue: 'Hits it big'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'YAS', number: 67, clue: '"Pls" follow-up'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'NEC', number: 68, clue: 'Poacher\'s target'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'HDR', number: 69, clue: 'Relaxing place'))
clues_mgwcc213_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'WFM', number: 70, clue: '"The Gold-Bug" inits.'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#213 - "Special Occasion"', grid: 'CABOX.BTL.IGOXI|AABSE.BRS.CTXMB|PIFQJWNAOXLHUDQ|...WTMB.WARD...|VRYY.PXOAI.HCHI|KNNA.EGWHD.POBV|OEX.VGEQSNP.XAW|QXE.IIS.GIW.MRE|SJLXG.DUL.HALPB|...ZOJKYWQAM...|.HWS.NYPIK.AZI.|.JRARW...GZROW.|KPISQVC.CTCNBNW|QYCLRTS.QNHQPMY|YAS.NEC.HDR.WFM', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/7/13', entries: clues_mgwcc213_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')