clues_mgwcc221_unscrambled = Array.new
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'CAKE', number: 1, clue: 'Sweet slices'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'COATIS', number: 1, clue: 'Raccoon cousins'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARMADA', number: 2, clue: 'Feared navy'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'KAYOED', number: 3, clue: 'Defeated soundly'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ELS', number: 4, clue: 'Current British Open champion'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'SWUNG', number: 5, clue: 'Used a wood, say'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'SKOAL', number: 5, clue: 'Jutlander\'s "Here\'s mud in your eye!"'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'WINDY', number: 6, clue: 'Like Chicago'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'UREY', number: 7, clue: 'Chemistry Nobelist Harold ___'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NBA', number: 8, clue: '"Where amazing happens" org.'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'GYM', number: 9, clue: 'Boxers often hit it'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'TSAR', number: 10, clue: 'Peter the Great, e.g.'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TOTO', number: 10, clue: 'He barked at the Tin Man'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SHAMPOOS', number: 11, clue: 'Suave and Finesse'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'AIRMILE', number: 12, clue: 'About 6,076 feet'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ROTATES', number: 13, clue: 'Turns'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ORAL', number: 14, clue: 'Like some contraceptives'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'KIRBY', number: 15, clue: '"City Slickers" co-star of Crystal'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'OHIO', number: 16, clue: 'Xenian\'s state'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'AMYS', number: 17, clue: 'Adams, Grant and Carter'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'ONEAM', number: 18, clue: 'Late bedtime'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'TART', number: 19, clue: 'Sharp'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'TAO', number: 20, clue: 'The way, in China'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'CADY', number: 21, clue: 'Early feminist Elizabeth ___ Stanton'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'CLYDE', number: 21, clue: 'The orange ghost in Pac-Man'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'COMMA', number: 22, clue: 'Writer\'s pause'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'CBS', number: 22, clue: '"2 Broke Girls" network'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'IDEALLY', number: 23, clue: 'In a perfect world'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'ALIVE', number: 24, clue: 'Still around'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'BOB', number: 25, clue: 'Seger with the Silver Bullet Band'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'BOOYA', number: 25, clue: 'Victorious exclamation'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'OUTER', number: 26, clue: '___ planets (Jupiter, Saturn, Uranus and Neptune)'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'PIT', number: 27, clue: 'Edgar Allan Poe title word'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SADLY', number: 28, clue: '"Sorry to say..."'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'IOUS', number: 29, clue: 'Promises to pay'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'INQTH', number: 29, clue: 'Two spots away from an Olympic medal'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'OLE', number: 30, clue: 'Grand ___ Opry (Minnie Pearl\'s place)'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'IDIDNOT', number: 31, clue: 'Phrase of denial'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'IRATE', number: 32, clue: 'Madder than mad'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'DYSON', number: 33, clue: 'Physics giant Freeman ___'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'TOES', number: 34, clue: 'Ten-digit group'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'TRENT', number: 34, clue: 'Dilfer or Reznor'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'EVERYQYEARS', number: 35, clue: 'How often George pledges to visit his parents when they move to Florida, in a "Seinfeld" episode'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'ELEPHANT', number: 35, clue: 'Animal often carved out of jade'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'ATARI', number: 36, clue: 'Company started in 1972 by Nolan Bushnell'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ERLE', number: 37, clue: '___ Halliburton (eponymous oil company founder)'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'EDAMAME', number: 37, clue: 'Soybeans as a snack'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'REFACES', number: 38, clue: 'Works on kitchen cabinets, perhaps'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'ASTARTE', number: 39, clue: 'Goddess of fertility'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'DEE', number: 40, clue: 'Ruby of "American Gangster"'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'OTOH', number: 41, clue: 'However briefly?'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ODE', number: 41, clue: 'Pretty lines'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ANVIL', number: 42, clue: 'Object that inexplicably falls from the sky in cartoons'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'VITTER', number: 43, clue: 'Louisiana senator David'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'INATIE', number: 44, clue: 'How baseball games can\'t end'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'LAZULI', number: 45, clue: 'Lapis ___ (semiprecious stone once called sapphire because of its color)'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'AFP', number: 46, clue: 'AP rival'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'DEN', number: 47, clue: 'Work room'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'MARTINA', number: 48, clue: 'Noted tennis autobiography of 1986'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'MACAW', number: 48, clue: 'Colorful bird'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'AXELS', number: 49, clue: 'Jumps on the ice'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MAHRE', number: 50, clue: 'Phil who won gold at the Sarajevo Olympics'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'RIDE', number: 51, clue: 'Get on board'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'TAXI', number: 52, clue: 'It has a meter and an odometer'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'TYRO', number: 52, clue: 'Rookie'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TAZ', number: 53, clue: 'Little devil?'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ACAI', number: 54, clue: 'Brazilian berry'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'JOYCE', number: 55, clue: 'Emerald Isle chronicler'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'JAG', number: 55, clue: 'Bender'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'OUR', number: 56, clue: 'Owned by more than one person, including me'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'ETTU', number: 57, clue: 'Latin reproach'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'END', number: 57, clue: 'Fitting final entry in a crossword'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MEND', number: 58, clue: 'Fix'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'AURAL', number: 59, clue: 'Of hearing'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'NEIL', number: 60, clue: '[No clue]'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ESTE', number: 61, clue: 'East of Ecuador'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'GROWS', number: 62, clue: 'Gets higher'))
clues_mgwcc221_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'DREI', number: 63, clue: 'Central European trio'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #221 - "At the Present Time"', grid: 'CAKE.SWUNG.TSAR|ORAL.KIRBY.OHIO|AMYS.ONEAM.TART|TAO.CADY..COMMA|IDEALLY.BOB.PIT|SADLY..IOUS.OLE|...IDIDNOT.TOES|..EVERYQYEARS..|ERLE.ASTARTE...|DEE.OTOH..ANVIL|AFP.DEN.MARTINA|MAHRE..TAXI.TAZ|ACAI.JOYCE.ETTU|MEND.AURAL.NEIL|ESTE.GROWS.DREI', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/9/7', entries: clues_mgwcc221_unscrambled, instructions: instructions, explanation: explanation)
