clues_mgwcc232_unscrambled = Array.new
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SID', number: 1, clue: 'Meier, Caesar or Luckman'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SIDEB', number: 1, clue: 'Part of a 45'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IRENE', number: 2, clue: '"Me, Myself & ___" (2000 Jim Carrey movie)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'DECAF', number: 3, clue: 'Coffee in an orange-lidded pot'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'BARES', number: 4, clue: 'Reveals'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'BISTRO', number: 4, clue: 'Casual restaurant'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ANI', number: 5, clue: 'Defiant DiFranco'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'RIO', number: 6, clue: 'Angry Birds movie'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ENNIO', number: 7, clue: 'Film scorer Morricone'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SKIMP', number: 8, clue: 'Cut corners'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'SIPE', number: 9, clue: '1980 NFL MVP Brian'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SACKRACE', number: 9, clue: 'Family picnic fun'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ITO', number: 10, clue: 'Lance in a robe'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PAULO', number: 11, clue: 'Sao ___, Brazil'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ERROL', number: 12, clue: 'Mr. Flynn'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IRE', number: 13, clue: 'Anger'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ININK', number: 14, clue: 'Written by a pen'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'ATARI', number: 15, clue: '___ 2600 (nostalgia-evoking console)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 2, col: 15, dir: 'Down', answer: 'ITLL', number: 16, clue: '"___ have to do"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DECISIONINCOURT', number: 17, clue: 'The first nominee'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'ICON', number: 18, clue: '"Recycling Bin" or "Mozilla Firefox" image'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'NOON', number: 19, clue: 'When the sun is highest in the sky'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ENACT', number: 20, clue: 'Put on the books'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'IMOK', number: 21, clue: '"Everything\'s fine"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'LOL', number: 22, clue: 'Fun palindrome'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'BEFOREPOPORROLL', number: 23, clue: 'The second nominee'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'EPIC', number: 24, clue: 'Amazing'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'PESOS', number: 25, clue: 'Mexican money'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'READ', number: 26, clue: 'Take in some (Francis) Bacon'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'NOPE', number: 27, clue: '"Don\'t think so"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'NAE', number: 28, clue: 'Glaswegian\'s "get outta town!"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ABS', number: 29, clue: 'Six-pack on the torso'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ANT', number: 29, clue: 'Tiny worker'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'BOO', number: 30, clue: 'Halloween shout'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'STU', number: 31, clue: 'Poker great Ungar'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ISHE', number: 32, clue: '"As a man thinks in his heart, so ___" (Proverbs)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'HUH', number: 33, clue: '"Whadja say?"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ENOCH', number: 34, clue: 'Father of Methuselah'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'CAIRO', number: 35, clue: 'Largest Arabic-speaking city in the world'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'IFS', number: 36, clue: 'Questions yet to be settled'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'ROE', number: 37, clue: 'Fish eggs'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ORE', number: 38, clue: 'Valuable minerals'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'NOTACCOUNTEDFOR', number: 39, clue: 'The third nominee'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'ACHT', number: 40, clue: 'Between 7 and 9, east of the Rhine'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'CHEMICAL', number: 41, clue: 'Lab liquid'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'TEAL', number: 42, clue: 'Blue shade'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'TOUCH', number: 43, clue: 'iPod choice'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'SHOE', number: 44, clue: 'One of two that\'s found on the ground'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'SEE', number: 45, clue: '"Understand?"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'HEM', number: 46, clue: 'Stall for time'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'MAKO', number: 47, clue: 'Skinny shark'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'CARM', number: 48, clue: 'Tony\'s wife, on "The Sopranos"'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'REACTS', number: 49, clue: 'Responds'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'MALT', number: 50, clue: '___ liquor (Colt 45, e.g.)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SALTMARCHLEADER', number: 51, clue: 'The fourth nominee'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'SUCK', number: 51, clue: 'Enjoy a lollipop'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'APAIN', number: 52, clue: 'Be ___ in the neck (aggravate)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'LIETO', number: 53, clue: 'Deceive'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'RENDS', number: 54, clue: 'Tears'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'CAJUN', number: 55, clue: 'Southern cooking style'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'DEISM', number: 56, clue: 'Belief in a "watchmaker" god'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'EVOKE', number: 57, clue: 'Bring to mind, as images'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'RENAL', number: 58, clue: 'Of the kidneys'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'UPI', number: 59, clue: 'AP or AFP rival'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'IKEA', number: 60, clue: 'Brand name often written in all caps'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'ALEVE', number: 61, clue: 'Brand name of naproxen'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CAENCONJUNCTION', number: 62, clue: 'The fifth nominee'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'NNE', number: 63, clue: 'Opposite SSW'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'UVA', number: 64, clue: 'ACC school'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'NEG', number: 65, clue: 'O-___ (blood type, for short)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'KITNA', number: 66, clue: 'Seahawks-Bengals-Lions-Cowboys quarterback Jon'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'DUVET', number: 67, clue: 'Hefty blanket'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'SKA', number: 68, clue: 'Music from Jamaica'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 15, col: 2, dir: 'Across', answer: 'NOEL', number: 69, clue: 'Joyeux ___ (Merry Christmas, in France)'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SNAGS', number: 70, clue: 'Unanticipated problems'))
clues_mgwcc232_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'MEL', number: 71, clue: 'Brooks who directed "Young Frankenstein"'))
Puzzle.create(title: 'MGWCC #232 - "And the Winner Was..."', grid: 'SID.BARES.SIPE.|IRE.ININK.ATARI|DECISIONINCOURT|ENACT..IMOK.LOL|BEFOREPOPORROLL|...NOPE..NAE...|ABS..ISHE.CAIRO|NOTACCOUNTEDFOR|TOUCH.SHOE..SEE|...HEM..CARM...|SALTMARCHLEADER|UPI.IKEA..ALEVE|CAENCONJUNCTION|KITNA.DUVET.SKA|.NOEL.SNAGS.MEL', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2012/11/23', entries: clues_mgwcc232_unscrambled)
