clues_mgwcc238_unscrambled = Array.new
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TORR', number: 1, clue: 'A little pressure'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TOOL', number: 1, clue: 'Knife or fork'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OHNO', number: 2, clue: '"That\'s awful!"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RIEL', number: 3, clue: 'Angkor Wat scratch'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ROLLER', number: 4, clue: 'High ___'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'HASPS', number: 5, clue: 'Lock parts'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'HUMANOID', number: 5, clue: 'Similar to you and me'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANET', number: 6, clue: 'Without ___ (dangerously)'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'STEVEMC', number: 7, clue: '"Papillon" actor; movie with songs by Elton John'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'PIS', number: 8, clue: 'Dicks'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SLEUTH', number: 9, clue: 'He may not have a clue'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ABIE', number: 10, clue: 'Title Broadway role of the 1920s'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'AGUE', number: 10, clue: 'Flu symptom'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BONN', number: 11, clue: 'World capital until 1990'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ISIN', number: 12, clue: 'OK Go\'s "The Fix ___"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EST', number: 13, clue: 'One of the Baltic States: abbr.'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OHIO', number: 14, clue: 'Home to 11.5 million people'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'UNTIL', number: 15, clue: 'Up to'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'GOSS', number: 16, clue: '2000s CIA director Porter ___'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ONEL', number: 17, clue: 'Book with chapters titled "Learning to Love the Law" and "Exams (Last Act)"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'MEESE', number: 18, clue: 'Noted 1958 graduate of Berkeley Law'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'UNIT', number: 19, clue: 'Condo'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'LOLL', number: 20, clue: 'Do nothing'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'ATV', number: 21, clue: 'Kawasaki\'s Brute Force 650 or Suzuki\'s KingQuad 750AXi'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'UPENN', number: 22, clue: 'Philly Ivy'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'PSA', number: 23, clue: 'TV filler'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'EIN', number: 24, clue: 'Brahms piece "___ deutsches Requiem"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'ITTO', number: 25, clue: '"Take ___ the Limit"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'EATS', number: 26, clue: 'Victuals'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ACTVI', number: 27, clue: 'Part of a long play'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SPORTO', number: 28, clue: 'Old chum'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'STEER', number: 28, clue: 'Cow'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'PEPSI', number: 29, clue: 'Dark drink'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ODIST', number: 30, clue: 'Kind of poet'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'MCHAMMER', number: 31, clue: 'He was 2 legit 2 quit'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'MST', number: 32, clue: 'Clock setting in Great Falls: abbr.'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'MAURA', number: 33, clue: 'Jacobson of crosswords or Tierney of acting'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ENRON', number: 34, clue: 'Houston, they had a problem'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'REASK', number: 35, clue: 'Pose again'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'TED', number: 36, clue: 'Conference series'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'TINCT', number: 37, clue: 'Hue'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'NESTS', number: 38, clue: 'Makes a nice home'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'SANE', number: 39, clue: 'All there'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'EPISODE', number: 40, clue: '"The Empire Strikes Back," casually; her books have been made into movies starring Emma Thompson, Keira Knightley and Gwyneth Paltrow'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'SEE', number: 41, clue: '"There you have it!"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'VENTURA', number: 42, clue: 'Jim Carrey role; with "The," movie where a character has M&#252;nchausen syndrome by proxy'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'ELEMENTS', number: 43, clue: 'Boxy Hondas'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'NEWB', number: 44, clue: 'Rook'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ESSE', number: 45, clue: 'It used to be "to be"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'STILE', number: 46, clue: 'Fence passage'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'TOTANGO', number: 47, clue: '1999 Matthew Perry/Neve Campbell romcom; Tarantino movie that opens with Pam Grier riding an airport people mover'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ROS', number: 48, clue: 'Icelandic band Sigur ___'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'RITENUTO', number: 49, clue: 'Musical command to decrease tempo'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'NAS', number: 50, clue: '___ in "Nancy"'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'USERID', number: 51, clue: 'Password preceder, often'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'EWBANK', number: 52, clue: 'Winning coach of Super Bowl III'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'BARRES', number: 53, clue: 'Ballet beams'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'ASST', number: 54, clue: 'Abbr. in job titles'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'MBA', number: 55, clue: 'Kellogg deg.'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'PAESE', number: 56, clue: 'Bel ___ (cheese)'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'PEAK', number: 56, clue: 'Zenith'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ANAL', number: 57, clue: 'OCD'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'EDAM', number: 58, clue: 'Food that becomes an unrelated food if you tack three letters onto its end'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ADE', number: 59, clue: 'Drink finish'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'DIOR', number: 60, clue: 'Christian who died in 1957'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'RBIS', number: 61, clue: 'Baseball stat, as sometimes seen'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'BOUT', number: 62, clue: 'Fight'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IOWA', number: 63, clue: 'Land of shuckers'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'STEN', number: 64, clue: 'British blaster'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'TEND', number: 65, clue: 'Keep your eye on'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'TAJ', number: 65, clue: 'India\'s ___ Mahal Museum'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'RONIN', number: 66, clue: 'Masterless warrior'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ONO', number: 67, clue: 'Palindromic peacenik'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'ROOT', number: 68, clue: 'Cheer'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AAAA', number: 69, clue: 'Laser pointer battery, often'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'INGOT', number: 70, clue: 'Expensive bar'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'EUWE', number: 71, clue: 'World chess champion, 1935-37 (hidden in ADIEU, WENDY)'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'JKLM', number: 72, clue: 'They\'re in I-N'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DOORS', number: 73, clue: 'Opportunities, in metaphor'))
clues_mgwcc238_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'STAN', number: 74, clue: 'Last syllable of many countries'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #238 - "You Don\'t Know Jack"', grid: 'TORR.HASPS.ABIE|OHIO.UNTIL.GOSS|ONEL.MEESE.UNIT|LOLL.ATV.UPENN.|...EIN.EATS....|SPORTO.MCHAMMER|TED.TINCT..SANE|EPISODE.VENTURA|ESSE..STILE.ROS|RITENUTO.EWBANK|....ASST.MBA...|.PAESE.ADE.RBIS|TEND.RONIN.ROOT|AAAA.INGOT.EUWE|JKLM.DOORS.STAN', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/1/4', entries: clues_mgwcc238_unscrambled, instructions: instructions, explanation: explanation)
