clues_mgwcc241_unscrambled = Array.new
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'STAGED', number: 1, clue: 'Not spontaneous'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SACKS', number: 1, clue: 'Flour holders'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TYSON', number: 2, clue: '"Iron Mike"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'AEIOU', number: 3, clue: 'Alphabetical quintet'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'GAB', number: 4, clue: 'Chat'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'EYES', number: 5, clue: 'Viewing pair'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DECLASSE', number: 6, clue: 'Vulgar'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'ELATE', number: 7, clue: 'Make very happy'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EVENS', number: 7, clue: '2, 4, 6, 8, etc.'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'LARD', number: 8, clue: 'Paleo diet fat'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'APSE', number: 9, clue: 'Church recess'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'TOUR', number: 10, clue: 'Band\'s trip'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ERR', number: 11, clue: 'Do the wrong thing'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Across', answer: 'ARKS', number: 12, clue: 'Biblical boat replicas'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'AFIRE', number: 12, clue: 'Blazing'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ROVED', number: 13, clue: 'Had no specific destination'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'KRONA', number: 14, clue: 'Currency some of whose bills feature Carl Linnaeus and Jenny Lind'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'STRAY', number: 15, clue: 'Adoptable cat'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AYEAYE', number: 16, clue: '"Will do, captain"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'VAPOR', number: 17, clue: 'Steam'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 2, col: 14, dir: 'Across', answer: 'FORT', number: 18, clue: 'What kids make from cushions'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'CSIBECKERSURVIVOR', number: 19, clue: 'Show about forensic science; Ted Danson sitcom; It\'s been set on Vanuatu, Palau and Fiji'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'KABOB', number: 20, clue: 'Meal on a skewer'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Down', answer: 'VANYA', number: 21, clue: 'Chekhov play "Uncle ___"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'KOO', number: 22, clue: '1970s actress ___ Stark'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'SLANDER', number: 23, clue: 'Actionable words'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ARENA', number: 24, clue: '___ football'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SNUG', number: 25, clue: 'Comfy'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'GASPING', number: 26, clue: 'Fighting for air'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'ABS', number: 27, clue: '"8 Minute ___" (bestselling exercise video)'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'ONEDAY', number: 28, clue: 'Sometime in the distant future'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ORZO', number: 28, clue: 'Pasta that\'s Italian for "barley"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ALSO', number: 29, clue: '"One other thing..."'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'LEST', number: 30, clue: '"Heaven forfend..."'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'SCARY', number: 31, clue: 'Anxiety-inducing'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'SNIVELS', number: 31, clue: 'Acts like a toady'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'CANUTE', number: 32, clue: 'Great Dane?'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'ANTE', number: 33, clue: 'A chip or two, often'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'NURSESBONANZACTRL', number: 34, clue: '"Empty Nest" spinoff set in a hospital; Classic western; First network web-only series, named for a computer keyboard key'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'NEATH', number: 34, clue: 'Poetic preposition'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ULURU', number: 35, clue: 'Australia\'s Ayers Rock, alternatively'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'RADON', number: 36, clue: 'Colorless element'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'OPENTO', number: 37, clue: 'Not completely turned off by'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'CHURROS', number: 38, clue: 'Pastries Spaniards dip in hot chocolate'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'TALES', number: 39, clue: 'Possibly untrue stories'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 16, dir: 'Down', answer: 'RHINO', number: 40, clue: 'Animal that\'s one letter off from a river'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 7, col: 17, dir: 'Down', answer: 'LAPAZ', number: 41, clue: 'South American capital'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ELAPSE', number: 42, clue: 'Pass by'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 8, col: 8, dir: 'Across', answer: 'PINTO', number: 43, clue: '1970s Ford'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Across', answer: 'HAHA', number: 44, clue: '"u r so funny"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'AUDIT', number: 45, clue: 'Sit in on, like a college class'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'REVUE', number: 46, clue: 'Variety show'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'ROTE', number: 46, clue: 'Simple memorization'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'TULIP', number: 47, clue: 'Symbol of Holland'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'TEAL', number: 47, clue: 'Blue hue'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'TRON', number: 48, clue: '1982 Disney movie'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'MONET', number: 49, clue: '"Impression, Sunrise" impressionist'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'MARK', number: 49, clue: 'Con artist\'s victim'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'SERENA', number: 50, clue: 'She\'s beaten Venus in six Grand Slam finals'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'STARWARS', number: 50, clue: 'Movie with the line "I find your lack of faith disturbing"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'HUNGBATTLESTARSOZ', number: 51, clue: 'Show about a gigolo; 1980s game show hosted by Alex Trebek; Prison show with Edie Falco as a guard'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'BONDS', number: 52, clue: 'Ties'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'SHEET', number: 53, clue: 'Bed cover'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'OREOS', number: 54, clue: 'Food that comes in a sleeve'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'HALO', number: 55, clue: 'Gold ring'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'SHRINK', number: 56, clue: 'Doc with a couch'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'SHAPE', number: 56, clue: 'Parallelogram or trapezoid'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'HOLED', number: 57, clue: 'Made, as a putt'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'RUING', number: 58, clue: 'Wishing you hadn\'t'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'INANE', number: 59, clue: 'Silly'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Across', answer: 'PER', number: 60, clue: 'Each'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'PITHS', number: 60, clue: 'Essential parts'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Across', answer: 'SANE', number: 61, clue: 'All there'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'ABACK', number: 62, clue: 'Taken ___'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 16, dir: 'Down', answer: 'NICHE', number: 63, clue: 'Pocket of the market'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 13, col: 17, dir: 'Down', answer: 'ETHOS', number: 64, clue: 'Precious name of Starbucks\' in-house bottled water brand'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'HOUND', number: 65, clue: 'Pester persistently'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'REVIEWS', number: 66, clue: 'Amazon.com writeups'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Down', answer: 'RARE', number: 66, clue: 'Really pink'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Down', answer: 'ERIE', number: 67, clue: 'County of northern Ohio'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Down', answer: 'VEST', number: 68, clue: 'Sleeveless garment'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Down', answer: 'SCAM', number: 69, clue: 'Fast one'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 14, col: 15, dir: 'Across', answer: 'BIT', number: 70, clue: 'Chomped'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ALIASBARETTACOACH', number: 71, clue: 'Jennifer Garner played a CIA agent on it; Robert Blake title role; Sitcom set in Minnesota'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Down', answer: 'BIB', number: 72, clue: 'Palindromic cover'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 15, col: 14, dir: 'Down', answer: 'ONO', number: 73, clue: 'Yoko from Tokyo'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'PENN', number: 74, clue: 'One of the Ivies'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 16, col: 6, dir: 'Across', answer: 'IRISH', number: 75, clue: 'Like the chauffeur on "Downton Abbey"'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 16, col: 12, dir: 'Across', answer: 'RANCHO', number: 76, clue: 'Word in many California place names'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'EDGE', number: 77, clue: 'Rim'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 17, col: 6, dir: 'Across', answer: 'BEETS', number: 78, clue: 'Root vegetables'))
clues_mgwcc241_unscrambled.push(Entry.create(row: 17, col: 12, dir: 'Across', answer: 'SMOKES', number: 79, clue: 'Cigs'))
instructions = 'One of the twelve TV shows in this puzzle\'s four theme entries is out of place. Which one is it?'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #241 - "Network Solutions"', grid: 'STAGED.ELATE.ARKS|AYEAYE.VAPOR.FORT|CSIBECKERSURVIVOR|KOO.SLANDER.ARENA|SNUG.ABS...ONEDAY|...ALSO.SCARY....|NURSESBONANZACTRL|ELAPSE.PINTO.HAHA|AUDIT.REVUE.TULIP|TRON.MONET.SERENA|HUNGBATTLESTARSOZ|....OREOS.HALO...|SHRINK...PER.SANE|HOUND.REVIEWS.BIT|ALIASBARETTACOACH|PENN.IRISH.RANCHO|EDGE.BEETS.SMOKES', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/1/25', entries: clues_mgwcc241_unscrambled, instructions: instructions, explanation: explanation)
