clues_mgwcc244_unscrambled = Array.new
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'FROM', number: 1, clue: 'With 69-across, play on a familiar phrase that describes how this puzzle\'s theme answers run'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'FELIZ', number: 1, clue: '"___ Navidad"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'REYNA', number: 2, clue: 'American soccer star Claudio ___ (anagram of YEARN)'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ORING', number: 3, clue: 'Faulty part of the Challenger'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MONARCHS', number: 4, clue: 'Kings and queens'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'GOODS', number: 5, clue: 'Valuable items'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GAZEBO', number: 5, clue: 'Lawn structure'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ONO', number: 6, clue: 'Lady Lennon loved'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ONE', number: 7, clue: 'Undivided'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'DIS', number: 8, clue: 'Show no respect to'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SEAFARER', number: 9, clue: 'Sailor'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'BLAB', number: 10, clue: 'Tell everyone a secret'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BADDIE', number: 10, clue: 'Hateable character in kids\' books'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LEADACTOR', number: 11, clue: 'Star'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ARNE', number: 12, clue: 'Barack\'s Education Secretary'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'BOAR', number: 13, clue: 'Wild pig that sounds dull'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EERO', number: 14, clue: 'Gateway Arch architect ___ Saarinen'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ANNIE', number: 15, clue: 'Musical with the songs "Maybe" and "Tomorrow"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'AERO', number: 16, clue: 'Brand of inflatable mattress'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LYIN', number: 17, clue: '"___ Eyes" (Eagles hit)'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'ZOESALDANA', number: 18, clue: '"Avatar" actress'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'LOT', number: 19, clue: 'Place to park your Prius'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'INNATE', number: 20, clue: 'Hard-wired'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'TERESA', number: 21, clue: 'Mother ___ (Nobel Peace Prize winner)'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'FODDER', number: 22, clue: 'Grub for horses'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ZAGREBCROATIA', number: 23, clue: 'European capital since 1992'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'CWM', number: 24, clue: 'Seemingly vowelless Welsh word for a valley(though its middle letter is in fact a vowel)'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RBI', number: 25, clue: 'Cleanup hitter\'s stat'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'OAK', number: 26, clue: 'Strong tree'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'CROWBAR', number: 27, clue: 'Item to pry a manhole open'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'ECCE', number: 28, clue: '"Behold!" to Brutus'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'CHIC', number: 29, clue: 'In style'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'EONS', number: 30, clue: 'Ages and ages'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ATTHE', number: 31, clue: '"A Night ___ Opera"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'APPS', number: 31, clue: 'Droid downloads'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'TROT', number: 32, clue: 'Horse\'s pace'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'TIMEZONES', number: 33, clue: 'Central and Mountain, for two'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'MIKED', number: 34, clue: 'Wired for sound, like game show hosts'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'DENIRO', number: 35, clue: 'Robert of "Ronin" and "Raging Bull"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'THO', number: 36, clue: 'Despite, in poems'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PRISSY', number: 37, clue: 'Uptight'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'YANKOVIC', number: 38, clue: '"Amish Paradise" parodist'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'REJOIN', number: 39, clue: 'Sign into again, as an online discussion group'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'JANOWITZ', number: 40, clue: '"Slaves of New York" novelist Tama ___'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'POM', number: 41, clue: 'Little frizzy-haired dog, for short'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'AAHED', number: 42, clue: 'Oohed and ___'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'HID', number: 43, clue: 'Concealed'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ENE', number: 44, clue: 'Away from WSW'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 9, dir: 'Down', answer: 'DEL', number: 45, clue: 'State almost entirely on a peninsula: abbr.'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'NARCS', number: 46, clue: 'They rat on dealers to the fuzz'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'STEP', number: 47, clue: 'Part of a process'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'PATDRY', number: 48, clue: 'Forgo using a salad spinner on your greens, maybe'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'NINEPIN', number: 49, clue: 'Member of the back row, in bowling'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'PASADO', number: 50, clue: 'El a&#241;o ___ (last year, in Spanish)'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'ZACKDELAROCHA', number: 51, clue: 'Rage Against the Machine\'s lead singer'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'CHA', number: 52, clue: '"___-ching!"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'CHEAT', number: 53, clue: 'Peek over at someone else\'s test paper, e.g.'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'HADTO', number: 54, clue: 'Lacked options'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'ATSEA', number: 55, clue: 'Far from shore'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CLOTHO', number: 56, clue: 'One of the Fates'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'CZAR', number: 56, clue: 'Peter the Great was one'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'LEGO', number: 57, clue: 'Building block from Denmark'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'SOWHAT', number: 58, clue: '"And?"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ZENDAVESTA', number: 59, clue: 'Holy book for Zoroastrians'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'EVA', number: 60, clue: 'Longoria of "Desperate Housewives"'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'SIR', number: 61, clue: 'Olivier-Newton-John title?'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'TEL', number: 62, clue: '___ Aviv, Israel'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'IEDS', number: 63, clue: 'Iraqi dangers: abbr.'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'AGER', number: 64, clue: 'Ending for teen'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'IVIED', number: 65, clue: 'Like the walls of Harvard Yard'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'TATE', number: 66, clue: 'London art gallery'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ROSY', number: 67, clue: '___-cheeked'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'CARLO', number: 68, clue: 'Monte ___'))
clues_mgwcc244_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ZTOA', number: 69, clue: 'See 1-across'))
instructions = 'This week\'s contest answer is a four-legged animal who would feel at home in this grid.'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#244 - "Thus Solved Zarathustra"', grid: 'FROM.GOODS.BLAB|EERO.ANNIE.AERO|LYIN.ZOESALDANA|INNATE...FODDER|ZAGREBCROATIA..|...CROWBAR.ECCE|ATTHE.MIKED.THO|PRISSY...REJOIN|POM.AAHED.NARCS|STEP.NINEPIN...|..ZACKDELAROCHA|CLOTHO...SOWHAT|ZENDAVESTA.IEDS|AGER.IVIED.TATE|ROSY.CARLO.ZTOA', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/2/15', entries: clues_mgwcc244_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')