clues_mgwcc249_unscrambled = Array.new
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BOMBS', number: 1, clue: 'Films that fail'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BASSET', number: 1, clue: 'Hangdog-faced hound'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ORELSE', number: 2, clue: 'End of a demand'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MIXUPS', number: 3, clue: 'Miscommunications'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'BAUM', number: 4, clue: '"The Wizard of Oz" author'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SLA', number: 5, clue: 'Patty Hearst\'s kidnappers: abbr.'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ABCS', number: 6, clue: 'Letters of the alphabet'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ARCED', number: 6, clue: 'Like three-point shots, or the three-point line'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BAHAI', number: 7, clue: 'Religion headquartered in Haifa'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'COERCION', number: 8, clue: 'Force'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SUM', number: 9, clue: 'Grand total'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'VPS', number: 10, clue: 'Many corporate execs'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'VITAMINC', number: 10, clue: 'Citrus fruits contain it'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PARTAKES', number: 11, clue: 'Doesn\'t forgo'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SLY', number: 12, clue: 'Crafty'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ARIAL', number: 13, clue: 'Common font'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'RAOUL', number: 14, clue: 'Duke or Wallenberg'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Down', answer: 'LIMNS', number: 15, clue: 'Describes'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'IAL', number: 16, clue: 'Ending for ambassador or professor'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SEXUALCHEMISTRY', number: 17, clue: 'What the leads need, in romantic comedies'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'LYE', number: 18, clue: 'Meth lab caustic'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'SEE', number: 19, clue: '"What\'d I tell you?"'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SLUM', number: 20, clue: 'Bad part of town'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'YEAR', number: 21, clue: '1000 or 2000'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'MEAT', number: 22, clue: 'Mutton or emu'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ESP', number: 23, clue: 'Mystical claim'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'MEDICINEMAN', number: 24, clue: 'Healer'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'MANE', number: 24, clue: 'The lion ring?'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'IDIOM', number: 25, clue: '"Like it\'s nobody\'s business" or "Look what the cat dragged in!"'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'NEW', number: 26, clue: '___ South Wales (Sydney\'s state)'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TESLA', number: 27, clue: 'Inventor slighted in the missing category'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'LAME', number: 28, clue: 'Weak, as an excuse'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'IDS', number: 29, clue: 'Traveler\'s needs'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'IKE', number: 30, clue: 'Infamous 2008 hurricane'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ANG', number: 31, clue: 'He recently beat Steven out for Best Director'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'GETAT', number: 32, clue: 'Indicate'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'POI', number: 33, clue: 'Hawaiian paste'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'POX', number: 33, clue: '"A ___ on both your houses!"'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'KNEW', number: 34, clue: 'Was aware of'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'KITE', number: 34, clue: 'Toy in the air'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'HOMEECONOMICS', number: 35, clue: 'Sewing class'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'HOMEBREW', number: 35, clue: 'Suds in the basement, perhaps'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'ONTARIAN', number: 36, clue: 'New Yorker\'s neighbor'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'CHIRPILY', number: 37, clue: 'How a bird may sing'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'MANY', number: 38, clue: 'Not just a handful'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'DONE', number: 39, clue: 'Finis'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'DEP', number: 39, clue: 'Part of DOT'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'THX', number: 40, clue: 'Appreciation, while texting'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'MAT', number: 41, clue: 'A Downward Dog is done on one'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EMT', number: 42, clue: 'IV inserter'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'HAI', number: 43, clue: 'Yes, in Yokohama'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'HESHE', number: 43, clue: 'Pronoun with a slash'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'NEIGH', number: 44, clue: 'Vote in the Equine Senate, perhaps'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'IMPURE', number: 45, clue: 'Tainted'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'GOURDE', number: 46, clue: 'Haitian monetary unit'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'HONEST', number: 47, clue: 'Without guile'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'PEACETREATY', number: 48, clue: 'Agreement on armaments'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'COS', number: 49, clue: 'Businesses: abbr.'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'EATEN', number: 50, clue: 'Had'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'APERY', number: 51, clue: 'Mimicry'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'TAR', number: 52, clue: 'Roof goop'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'MOO', number: 53, clue: '"Greetings, fellow cows!"'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'BROS', number: 54, clue: 'Close buds'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'PAPA', number: 55, clue: '___ John\'s'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'SPUN', number: 56, clue: 'Went around'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'STEW', number: 56, clue: 'Simmered food'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'IRISHLITERATURE', number: 57, clue: 'Ulysses, Dubliners, anything by Yeats, etc.'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'IDO', number: 57, clue: 'Altar agreement'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'LEN', number: 58, clue: 'Director Wiseman'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'ANT', number: 59, clue: 'Crawling critter'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'DEA', number: 60, clue: '"Traffic" org.'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'EELER', number: 61, clue: 'Kind of fisherman'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'NERDS', number: 62, clue: 'They\'re so smart'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'OWN', number: 63, clue: 'Take responsibility for'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'NYNY', number: 64, clue: 'Cultural rival of LA, CA'))
clues_mgwcc249_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'TWEET', number: 65, clue: 'Communication by a certain form of social media in which writers may use only 140 characters, including spaces, as I\'ve done with this clue'))
instructions = 'This week\'s meta answer is a word beginning with P.'
explanation = '<MA>PHYSICS</MA><TEXT>Each theme answer contains a Nobel Prize category: Chemistry, Medicine, Economics, Peace, and Literature. PHYSICS is the only one not represented.</TEXT>'
Puzzle.create(title: '#249 - "Categorically Denied"', grid: 'BOMBS.ABCS..VPS|ARIAL.RAOUL.IAL|SEXUALCHEMISTRY|SLUM.YEAR.MEAT.|ESP.MEDICINEMAN|TESLA...IDS.IKE|...ANG.POI.KNEW|.HOMEECONOMICS.|DONE.THX.MAT...|EMT.HAI...NEIGH|PEACETREATY.MOO|.BROS.PAPA.SPUN|IRISHLITERATURE|DEA.EELER.NERDS|OWN..NYNY.TWEET', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/3/22', entries: clues_mgwcc249_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')