clues_mgwcc250_unscrambled = Array.new
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DOG', number: 1, clue: 'Pom or pug'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DAWG', number: 1, clue: 'Cooler version of 1-across'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OAHU', number: 2, clue: 'State quarter with this island\'s outline? It\'s Hawaii'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'GAEL', number: 3, clue: 'Manxman, e.g.'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'WAGON', number: 4, clue: 'Traditionally red transportation (not this one; go to 4-down)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'WEIGHTS', number: 4, clue: 'Features a gym is very likely to have'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ARM', number: 5, clue: 'One of a bodily pair'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'GOSS', number: 6, clue: 'Former CIA head Porter ___'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ODIE', number: 7, clue: 'Dim 1-across'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NEXT', number: 8, clue: '"Who\'s up?"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'TRASH', number: 9, clue: 'Refuse'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'THY', number: 9, clue: 'Your of yore'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'REF', number: 10, clue: 'Clipping caller'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ALOON', number: 11, clue: 'Crazy as ___'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'SLUNG', number: 12, clue: 'Tossed'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HORSE', number: 13, clue: 'Basketball game'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AAA', number: 14, clue: 'Roadside rescuers'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ERODE', number: 15, clue: 'Slowly destroy'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'HELLO', number: 16, clue: '"What is it, caller?"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'WHENIMSIXTYFOUR', number: 17, clue: 'It mentions the Isle of Wight (first, quarter; then first quarter)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'NASH', number: 18, clue: 'West Virginia-born Nobelist (in the fake Economics category, though)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Down', answer: 'THOU', number: 19, clue: 'Grand'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'GULAG', number: 20, clue: 'Prison system'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'SETH', number: 21, clue: 'First name in Oscar hosts'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ONS', number: 22, clue: 'Switch settings'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'SHY', number: 23, clue: 'Like wallflowers'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'YOWL', number: 24, clue: 'Loud shout'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'ORANGE', number: 25, clue: 'Piece of fruit that also just happens to be a common color'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'RBI', number: 26, clue: '___ single'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ASKS', number: 27, clue: 'Opens the bidding at'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'EIGHTOFCLUBS', number: 28, clue: 'Part of the Dead Man\'s Hand (first, quarter; then first quarter)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'EARP', number: 28, clue: 'Virgil or Morgan at Tombstone'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'IDEA', number: 29, clue: 'Brainstorm'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'GOAL', number: 30, clue: 'Pitch point'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'FOOTE', number: 31, clue: 'Civil War historian Shelby ___'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'CROAT', number: 32, clue: 'Zagreb denizen'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'LETUS', number: 33, clue: 'Words usually contracted'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ADO', number: 34, clue: 'Ballyhoo'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'SWORE', number: 35, clue: 'Said bad words'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'IKNOW', number: 36, clue: '"Seriously!"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'NOME', number: 37, clue: 'City with a University of Alaska satellite campus'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'OBOE', number: 38, clue: 'First ___ (orchestra chair)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'WEEN', number: 39, clue: 'Band with Dean and Gene'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'READ', number: 40, clue: 'Enjoy your Kindle'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'DESI', number: 41, clue: 'South Asian'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'LOOTS', number: 42, clue: 'Plunders'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'SPIT', number: 43, clue: 'Expectorate, less delicately'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'SOBE', number: 44, clue: 'Drink named for part of the Florida Coast'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PALEO', number: 45, clue: 'Diet whose name means "old"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'OWN', number: 46, clue: 'Have'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'TAUPE', number: 47, clue: 'Tan/gray hue'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'EXMAYOR', number: 48, clue: 'Rudy Giuliani or David Dinkins'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'MOE', number: 49, clue: '"The Simpsons" small business owner'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'SWEETSIXTEEN', number: 50, clue: 'NIT teams who\'ve won their first two games, collectively (first, quarter; then first quarter)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ESPN', number: 51, clue: '"Around the Horn" channel'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'TIDE', number: 52, clue: 'High or low'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TAPINS', number: 53, clue: 'Golf gimmes'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'TOOTH', number: 53, clue: '"Chopper"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ANNIE', number: 54, clue: 'Musical redhead'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'POEMS', number: 55, clue: 'Wordsworth words'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'TMI', number: 56, clue: '"You can stop telling me this now"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ONO', number: 57, clue: 'She said of her frequent inclusion in crosswords: "They just use my name as a filler"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'PATH', number: 58, clue: 'Way'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'ADJS', number: 59, clue: 'Black and blue are two: abbr.'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'TRUE', number: 60, clue: '"Good point"'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'HELD', number: 61, clue: 'Possessed'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'ADDER', number: 62, clue: 'Scary snake'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'DAMP', number: 63, clue: 'Not quite dry'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ERIC', number: 64, clue: 'Holder of much power in D.C.'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'RSVP', number: 65, clue: 'Send regrets, say'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ONEHUNDREDYEARS', number: 66, clue: 'Duration of solitude, in a literary title (first, quarter; then first quarter)'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'HEH', number: 67, clue: 'Nervous chuckle'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'USE', number: 68, clue: 'Put to work'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'DIE', number: 69, clue: 'Reno roller'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TIMES', number: 70, clue: 'Uses a stopwatch'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'JULIO', number: 71, clue: 'Man\'s name that\'s also a month'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'MIV', number: 72, clue: '1004'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HESHE', number: 73, clue: 'Five-letter pronoun'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'SEDER', number: 74, clue: 'Holiday feast'))
clues_mgwcc250_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'PCP', number: 75, clue: 'Angel dust'))
instructions = 'This puzzle\'s meta-answer is the answer to a hidden trivia question.'
Puzzle.create(title: 'MGWCC #250 - "First-Quarter Action"', grid: 'DOG.WAGON.TRASH|AAA.ERODE.HELLO|WHENIMSIXTYFOUR|GULAG.SETH..ONS|...SHY...ORANGE|EIGHTOFCLUBS...|ADO.SWORE.IKNOW|READ.LOOTS.SOBE|PALEO.TAUPE.MOE|...SWEETSIXTEEN|TAPINS...TMI...|ONO..PATH.ADDER|ONEHUNDREDYEARS|TIMES.JULIO.MIV|HESHE.SEDER.PCP', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/3/29', entries: clues_mgwcc250_unscrambled)
