clues_mgwcc253_unscrambled = Array.new
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'LEAH', number: 1, clue: 'Biblical wife of Jacob'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'LAMP', number: 1, clue: 'Light source'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'EWER', number: 2, clue: 'Big pitcher'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ARGO', number: 3, clue: 'Oscar-winning movie directed by Ben Affleck'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'HYACINTH', number: 4, clue: 'Flower named for a figure in Greek myth'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'AMANDA', number: 5, clue: 'Knox, Bynes or Blake'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ADORE', number: 5, clue: 'More than love'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MEME', number: 6, clue: 'Internet fad'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ATAD', number: 7, clue: 'Not very much'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NAN', number: 8, clue: 'Palindromic woman\'s name'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DII', number: 9, clue: '502, in old Rome'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ANAHEIM', number: 10, clue: 'Largest city in Orange County, Calif.'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ATE', number: 11, clue: 'Gobbled up'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AFEW', number: 11, clue: 'Not many'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TOSS', number: 12, clue: 'Flip of the coin'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EXPO', number: 13, clue: 'Trade show'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AWRY', number: 14, clue: 'Not as planned'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'DETAIN', number: 15, clue: 'Keep in custody'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'FOX', number: 16, clue: 'Animal that\'s also a TV network'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MEGALOMANIA', number: 17, clue: 'God complex'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'LUCKY', number: 18, clue: '"I envy you!"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ESP', number: 19, clue: 'Supernatural "ability"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'PROCURED', number: 20, clue: 'Managed to obtain'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'HOWSO', number: 21, clue: '"In what way?"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ODD', number: 22, clue: 'Not even'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ICE', number: 23, clue: 'Winter walking worry'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'TIED', number: 24, clue: 'Like soccer games requiring a penalty shootout'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'TYRANT', number: 24, clue: 'Ruler unaccountable to the people'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'IRAN', number: 25, clue: 'Iraq neighbor'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SPANK', number: 26, clue: 'Defeat soundly, in sports slang'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'SHRUB', number: 26, clue: 'Tree\'s little cousin'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'PAUSE', number: 27, clue: 'YouTube video button'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ASSET', number: 28, clue: 'Plus'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'JOYRIDING', number: 29, clue: 'Stealing a car just to drive it around for a while'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'JARRED', number: 29, clue: 'Gave a shock to'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'OBOES', number: 30, clue: 'Some woodwinds'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'IBEAM', number: 31, clue: 'Big girder'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'NORSE', number: 32, clue: 'Old ___ (Scandinavian language)'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'GOUTS', number: 33, clue: 'Painful conditions'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HASTY', number: 34, clue: 'Too quick'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'ABRAM', number: 35, clue: 'Middle name of President Garfield'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'BOO', number: 36, clue: '"You\'re a terrible singer/comedian/whatever!"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RUSH', number: 37, clue: 'Hurry'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'GROAN', number: 38, clue: 'Reaction to a pun'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'GABE', number: 38, clue: 'Kaplan of "Welcome Back, Kotter"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'PERU', number: 39, clue: 'Machu Picchu is there'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'PECTORAL', number: 39, clue: '___ muscles'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'USE', number: 40, clue: 'Find a place for'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'KAREN', number: 41, clue: 'Singer Carpenter or novelist Blixen'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'KEYPADS', number: 41, clue: 'Phone features'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'YEAST', number: 42, clue: 'Rising force?'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'YACHT', number: 42, clue: 'Big boat'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'BETHEBEST', number: 43, clue: 'Defeat everyone'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'HEM', number: 44, clue: '___ and haw (stall for time)'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'ACMES', number: 45, clue: 'High points'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'EYED', number: 46, clue: '"Brown ___ Girl" (Van Morrison song)'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'OCT', number: 47, clue: '10th mo.'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'OPINE', number: 47, clue: 'Tell everyone what you think'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TRUMP', number: 48, clue: '"The Donald"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'TOGA', number: 48, clue: 'Frat party clothing'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ROTS', number: 49, clue: 'Becomes inedible'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'UHOH', number: 50, clue: '"Whoops!"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'EUPHORIC', number: 51, clue: 'Incredibly happy'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ELLE', number: 51, clue: 'French magazine'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'UNIT', number: 52, clue: 'Foot or inch'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'RIGA', number: 53, clue: 'Latvia\'s capital'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ITEM', number: 54, clue: 'Object'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'CEDE', number: 55, clue: 'Give up'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OOH', number: 56, clue: '"That\'s amazing!"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'AMYLNITRITE', number: 57, clue: 'Chemical name of the recreational drug called "poppers"'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'MET', number: 58, clue: 'Shook hands with'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'YAP', number: 59, clue: 'Talk and talk and talk and talk'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GTO', number: 60, clue: 'Classic Pontiac'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'DEALIN', number: 61, clue: 'Give cards to'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'AGED', number: 62, clue: 'Got older'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ASH', number: 63, clue: 'Cigar stuff'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'STPETE', number: 64, clue: 'Tampa\'s twin'))
clues_mgwcc253_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'LAME', number: 65, clue: 'Weak, as an excuse'))
instructions = 'This week\'s contest answer is a well-known American novel.'
explanation = '<MA>LITTLE WOMEN</MA><TEXT>The names of the four main characters of "Little Women," Meg, Jo, Beth, and Amy, can be found at the beginnings of the theme answers.</TEXT>'
Puzzle.create(title: '#253 - "Book Club"', grid: 'LEAH.AMANDA.ATE|AWRY.DETAIN.FOX|MEGALOMANIA.ESP|PROCURED..HOWSO|...ICE..TIED...|SPANK.JOYRIDING|HASTY.ABRAM.BOO|RUSH.GROAN.PERU|USE.KAREN.YEAST|BETHEBEST.ACMES|...EYED..OCT...|TRUMP..EUPHORIC|OOH.AMYLNITRITE|GTO.DEALIN.AGED|ASH.STPETE.LAME', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/4/19', entries: clues_mgwcc253_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')