clues_mgwcc256_unscrambled = Array.new
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PELE', number: 1, clue: 'Reuters named him Athlete of the Century in 1999'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'POSIT', number: 1, clue: 'Assume for the moment'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELUDE', number: 2, clue: 'Slip past'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LAZED', number: 3, clue: 'Was a ne\'er-do-well'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'EVA', number: 4, clue: 'Gabrielle\'s portrayer'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'FWD', number: 5, clue: 'E-mail abbr.'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'FANFIC', number: 5, clue: 'Alt-universe form of literature'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'WREATH', number: 6, clue: 'Graveside item'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DAS', number: 7, clue: '7th most commonly used word in German'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'MASS', number: 8, clue: 'Kind of service'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MEMO', number: 8, clue: 'Words from the boss'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ALEX', number: 9, clue: 'Boisvert who declined a co-author credit on MGWCC #255, or game show host Trebek'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SLR', number: 10, clue: 'Kind of camera: abbr.'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SASHAYS', number: 11, clue: 'Owns the runway'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Across', answer: 'SAM', number: 12, clue: 'Unisex name'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SADISM', number: 12, clue: 'Finding pleasure in pain'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'AZALEA', number: 13, clue: 'Plant from the Greek for "dry"'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'MODERN', number: 14, clue: 'New'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'OLAV', number: 15, clue: '___ V (king from 1957-1991)'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ARABELLA', number: 16, clue: 'Opera that debuted in 1933'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Down', answer: 'BOLERO', number: 17, clue: 'Ravel piece'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 2, col: 15, dir: 'Across', answer: 'AZO', number: 18, clue: 'Handy three-letter word to know for Scrabble'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SUZANNESOMERS', number: 19, clue: '"Three\'s Company" actress'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'NOLIMIT', number: 20, clue: 'Poker stipulation'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 3, col: 15, dir: 'Across', answer: 'DAD', number: 21, clue: 'Palindromic man'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'IDE', number: 22, clue: 'Chemistry suffix'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'OFA', number: 23, clue: 'Friend ___ friend'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'LOX', number: 24, clue: 'Katz\'s fish'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'HAILE', number: 25, clue: 'First name in African history'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 4, col: 14, dir: 'Down', answer: 'AINT', number: 26, clue: 'Colloquial contraction'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TED', number: 27, clue: 'Senator Cruz'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'LITRE', number: 28, clue: 'Oxford unit'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RACE', number: 29, clue: 'Go fast'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'RAISER', number: 30, clue: 'Word with hell or fund'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'REDTOP', number: 30, clue: 'European grass'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'RICHARDFEYNMAN', number: 31, clue: '"What Do You Care What Other People Think?" autobiographer'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'RILE', number: 31, clue: 'Agitate'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'DUN', number: 32, clue: 'Hassle debtors'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'FLYBY', number: 33, clue: 'Looksee from above'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'CLAIM', number: 34, clue: 'State'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'CCCI', number: 34, clue: 'Fourth century start'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'LAOS', number: 35, clue: 'Luang Prabang is there'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'ARLO', number: 36, clue: 'Janis\'s husband, in the comics'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'COULDST', number: 37, clue: '"That very time I saw (but thou ___ not)"--"A Midsummer Night\'s Dream"'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CARLISLE', number: 38, clue: 'Home to Dickinson College'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'STEALS', number: 39, clue: 'Gets to second base, perhaps'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'LENDL', number: 40, clue: 'He never won Wimbledon'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Across', answer: 'NYT', number: 41, clue: 'USAT competitor'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Across', answer: 'TBA', number: 42, clue: 'Still up in the air, briefly'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'TAOS', number: 42, clue: 'Home to the Kit Carson Home and Museum'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 16, dir: 'Down', answer: 'BRUT', number: 43, clue: 'Deodorant brand'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 8, col: 17, dir: 'Down', answer: 'ARTY', number: 44, clue: 'Not for a general audience'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'COLETTE', number: 45, clue: '"Gigi" novelist'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'BOBBARR', number: 46, clue: 'Libertarian Party nominee for president in 2008'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'BENZENE', number: 47, clue: 'Crude oil component'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'BDAY', number: 48, clue: 'Present time, for short'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ISO', number: 49, clue: 'Looking for, briefly'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'ENO', number: 50, clue: 'Producer on the 1980 Talking Heads album "Remain in Light"'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Down', answer: 'ORB', number: 51, clue: 'Circle'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'TYPEDOUT', number: 52, clue: 'Put onto the computer screen'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'TWOA', number: 52, clue: 'Low-level apartment'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'INADRAW', number: 53, clue: 'How yesterday\'s Nakamura-Radjabov game ended'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'IBIS', number: 53, clue: 'Its beak curves downward'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'NICECAR', number: 54, clue: 'What every Ferrari owner loves to hear'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ARCHON', number: 55, clue: 'Leader, in Greek city-states'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'NASTY', number: 56, clue: 'More than unpleasant'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'BIGBILLBROONZY', number: 57, clue: '"Guitar Shuffle" bluesman'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'BETRAY', number: 57, clue: 'Cross'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ITHACA', number: 58, clue: 'New York city'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'GHETTO', number: 59, clue: 'Elvis Presley title word'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'ONEFOR', number: 60, clue: 'Words before "the money" or "the ages"'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'NOOUTS', number: 61, clue: 'Promising situation for a rally'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ETHICS', number: 62, clue: 'Medical school subject'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Across', answer: 'CANOE', number: 63, clue: 'Quiet craft'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Across', answer: 'GOB', number: 64, clue: 'Amorphous amount'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'GITMO', number: 64, clue: 'Controversial prison, for short'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 16, dir: 'Down', answer: 'ODEON', number: 65, clue: 'Theater'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 13, col: 17, dir: 'Down', answer: 'BASSO', number: 66, clue: 'Deep part'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'THESE', number: 67, clue: 'Items at hand'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'DOH', number: 68, clue: 'Word in the titles of nine "Simpsons" episodes'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Down', answer: 'DRIP', number: 68, clue: 'Plumber\'s challenge'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Down', answer: 'OLES', number: 69, clue: 'Shouts of approval'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'EON', number: 70, clue: 'Long stretch'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 14, col: 15, dir: 'Across', answer: 'IDA', number: 71, clue: 'Moscow is there: abbr.'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'RAT', number: 72, clue: 'Treacherous mafioso'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'CARLOSFUENTES', number: 73, clue: '"The Old Gringo" novelist'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Down', answer: 'ABE', number: 74, clue: 'Japan\'s prime minister Shinzo ___'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Down', answer: 'STY', number: 75, clue: 'Hog digs'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 15, col: 14, dir: 'Down', answer: 'NAB', number: 76, clue: 'Collar'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'ACT', number: 77, clue: 'Don\'t just stand there'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 16, col: 5, dir: 'Across', answer: 'ABIENTOT', number: 78, clue: 'Paris parting words'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 16, col: 14, dir: 'Across', answer: 'AMOS', number: 79, clue: '"Famous" baker'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'YAO', number: 80, clue: 'Blocking Ming'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 17, col: 5, dir: 'Across', answer: 'REPS', number: 81, clue: 'Weight room count'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 17, col: 10, dir: 'Across', answer: 'YRS', number: 82, clue: 'M, MM, MMM, et al.'))
clues_mgwcc256_unscrambled.push(Entry.create(row: 17, col: 14, dir: 'Across', answer: 'BONO', number: 83, clue: 'Singer on "One Tree Hill"'))
instructions = 'This week\'s contest answer is a Best Actress winner who should be in this grid, but isn\'t.'
explanation = '<MA>LOUISE FLETCHER</MA><TEXT>The initial(s) of each theme answer is shorthand for a baseball position: P (pitcher), SS (shortstop), RF (right fielder), C (catcher), BB (second baseman), BBB (third baseman), CF (center fielder), and B (first baseman). The only position missing is left fielder (LF), and the only Best Actress winner with those initials as of 2013 is Louise Fletcher.</TEXT>'
Puzzle.create(title: '#256 - "Diamond Girl"', grid: 'PELE.FWD.MASS.SAM|OLAV.ARABELLA.AZO|SUZANNESOMERS.DAD|IDE.OFA.LOX.HAILE|TED.LITRE..RAISER|...RICHARDFEYNMAN|CLAIM..COULDST...|CARLISLE.NYT..TBA|COLETTE...BOBBARR|ISO..ENO.TYPEDOUT|...INADRAW..NASTY|BIGBILLBROONZY...|ETHICS..CANOE.GOB|THESE.DOH.EON.IDA|RAT.CARLOSFUENTES|ACT.ABIENTOT.AMOS|YAO.REPS.YRS.BONO', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/5/10', entries: clues_mgwcc256_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')