clues_mgwcc258_unscrambled = Array.new
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'THEJAYS', number: 1, clue: '1992 and 1993 World Series champs'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TRU', number: 1, clue: 'Play about Capote'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HON', number: 2, clue: 'Sweet thang'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ELF', number: 3, clue: 'Christmas movie extra'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'JLO', number: 4, clue: '"The Wedding Planner" actress, for short'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'AOL', number: 5, clue: 'ISP founded by a Hawaiian, and which reverses to a Hawaiian mountain'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'YUL', number: 6, clue: 'Mr. Brynner'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'STORKS', number: 7, clue: 'Baby carriers, maybe'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'MIAMIHEAT', number: 8, clue: '2012 NBA champions'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'MITLA', number: 8, clue: '"___ Pass" (Leon Uris book)'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'INHER', number: 9, clue: 'Josh Groban\'s "___ Eyes"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ADE', number: 10, clue: 'Ending for Power or Gator'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MEL', number: 11, clue: 'Kiper or Brooks'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ICE', number: 12, clue: 'Stuff in a tray, maybe'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'HEARSE', number: 13, clue: 'Coffin carrier'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENDO', number: 14, clue: 'Prefix meaning "within"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'ACES', number: 15, clue: 'Powerful foursome'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'TYRA', number: 16, clue: 'Banks on the runway'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ROLLOUT', number: 17, clue: 'Introduce gradually'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'INDECENCY', number: 18, clue: 'Poor taste'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UNFOLLOWTHELEADER', number: 19, clue: 'Quit receiving updates about one of Obama\'s posts on this site?'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'WIPED', number: 20, clue: 'Extremely tired'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'RILE', number: 21, clue: 'Stir up'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 4, col: 14, dir: 'Across', answer: 'ROSA', number: 22, clue: 'Marxist Luxemburg'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'UNBLOCKPARTIES', number: 23, clue: 'Events where everyone forgets past grudges on this site?'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'UTAH', number: 23, clue: 'Home state of Kayden Troff, current Under-14 World Chess Champion'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'NERO', number: 24, clue: '___ Claudius Caesar Augustus Germanicus (Roman emperor)'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'BLEWUPAT', number: 25, clue: 'Gave an earful to'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'LENIN', number: 26, clue: 'Historical figure into whose tomb I brought a bag of oranges in January 1991, whereupon a guard, thinking they might be a weapon, poked at the bag with a club, causing the oranges to fall all over the floor'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'OVA', number: 27, clue: 'Eggs'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'CIS', number: 28, clue: 'Successor state to the USSR'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'TIAMO', number: 29, clue: 'Sophia Loren\'s "I love you!"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'INNER', number: 30, clue: '___ Mongolia'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'EVIAN', number: 31, clue: 'Rival of 38-across'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TELEVISE', number: 32, clue: 'Broadcast'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'INVESTS', number: 33, clue: 'Gambles on Wall Street'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'SANTELLI', number: 34, clue: 'Rick of CNBC'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 6, col: 16, dir: 'Down', answer: 'TLA', number: 35, clue: 'IMO, BRB or FYI'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 6, col: 17, dir: 'Down', answer: 'SLY', number: 36, clue: 'Crafty'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARENAS', number: 37, clue: 'Stadiums'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'DASANI', number: 38, clue: 'Rival of 31-down'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ADIEU', number: 39, clue: '"A bientot!"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'SIT', number: 40, clue: 'Take a load off'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Across', answer: 'ALL', number: 41, clue: 'With 71-down, Steve Martin/Lily Tomlin movie of 1984'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'HOWI', number: 42, clue: 'Start of many explanatory titles'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'DIMEA', number: 43, clue: 'A ___ dozen'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Across', answer: 'NAY', number: 44, clue: 'Not yea'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 3, dir: 'Across', answer: 'UNLIKEITORNOT', number: 45, clue: '"Hurry up and make a decision about that post on this site already!"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'LEDIN', number: 46, clue: 'Showed past the foyer'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'IRISH', number: 47, clue: 'Adjective for Corkonians'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'KASHI', number: 48, clue: 'Healthy cereal brand'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'ESC', number: 49, clue: 'Corner key, usually'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'OZARK', number: 50, clue: 'County of southern Missouri'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'DIP', number: 51, clue: 'Slight decrease'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'DUH', number: 51, clue: 'A-ha moment utterance'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ISO', number: 52, clue: 'Looking for, in personal ads'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'ERASE', number: 53, clue: 'Use one end of a pencil'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Across', answer: 'ZELL', number: 54, clue: 'Chicago billionaire Sam'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 16, dir: 'Down', answer: 'LIED', number: 55, clue: 'Crafted a cover story'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 10, col: 17, dir: 'Down', answer: 'LAYS', number: 56, clue: 'Chip brand'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'USA', number: 57, clue: 'Home to 94% of MGWCC solvers, per Google Analytics'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'DISCUS', number: 58, clue: 'Old-school Olympic event'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'SAYIF', number: 59, clue: '"Let\'s suppose..."'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'ETALIA', number: 60, clue: 'And others'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'EDU', number: 60, clue: 'www.odu.___'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'TER', number: 61, clue: 'Dutch painter Gerard ___ Borch'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HOTDISH', number: 62, clue: 'Winter food'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'DUPREE', number: 63, clue: '"You, Me and ___" (2006 Owen Wilson/Kate Hudson movie)'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ADDERLEY', number: 64, clue: 'Jazz great Cannonball ___'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'DOSAGE', number: 65, clue: 'Amount from a nurse'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Across', answer: 'UNHIDEYOURKIDS', number: 66, clue: 'Make one of the children\'s posts visible again on this site?'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'DIDIT', number: 67, clue: 'Was guilty'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'EBONY', number: 68, clue: 'Chicago-based magazine since 1945'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'COOP', number: 69, clue: 'Chick\'s pad'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Down', answer: 'CULO', number: 69, clue: 'Last word in an Italian insult'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 14, col: 2, dir: 'Down', answer: 'ONAN', number: 70, clue: 'Biblical spiller'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 14, col: 3, dir: 'Down', answer: 'OFME', number: 71, clue: 'See 41-across'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'IBIS', number: 72, clue: 'Holy wader'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'UNFRIENDOFAFRIEND', number: 73, clue: 'Particularly painful dis on this site?'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Down', answer: 'IBI', number: 74, clue: 'There, in old Rome'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Down', answer: 'ERG', number: 75, clue: 'Work unit'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Down', answer: 'NAH', number: 76, clue: '"Don\'t think so"'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Down', answer: 'FEN', number: 77, clue: 'Wetland area'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Down', answer: 'ROC', number: 78, clue: '1990\'s FOX sitcom'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 14, dir: 'Down', answer: 'IRA', number: 79, clue: '___ Fried ("The Sopranos" doctor)'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 15, dir: 'Down', answer: 'EGG', number: 80, clue: 'One of twelve'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 16, dir: 'Down', answer: 'NEE', number: 81, clue: 'Born in France'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 15, col: 17, dir: 'Down', answer: 'DVD', number: 82, clue: 'Palindromic present'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'LAMEBRAIN', number: 83, clue: 'Fool'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 16, col: 11, dir: 'Across', answer: 'GEORGEV', number: 84, clue: 'King of England during WWI'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'ONEEIGHTY', number: 85, clue: 'Uey'))
clues_mgwcc258_unscrambled.push(Entry.create(row: 17, col: 11, dir: 'Across', answer: 'ENCAGED', number: 86, clue: 'Surrounded by bars'))
instructions = 'This week\'s contest answer is a familiar website.'
explanation = '<MA>FACEBOOK</MA><TEXT>The first word of each theme answer is an action that can be performed on Facebook.</TEXT>'
Puzzle.create(title: '#258 - "Site Unseen"', grid: 'THEJAYS.MIAMIHEAT|ROLLOUT.INDECENCY|UNFOLLOWTHELEADER|......RILE...ROSA|UNBLOCKPARTIES...|TELEVISE..INVESTS|ARENAS.DASANI.ALL|HOWI....DIMEA.NAY|..UNLIKEITORNOT..|DIP.ERASE....ZELL|USA.DISCUS.ETALIA|HOTDISH..ADDERLEY|...UNHIDEYOURKIDS|COOP...IBIS......|UNFRIENDOFAFRIEND|LAMEBRAIN.GEORGEV|ONEEIGHTY.ENCAGED', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/5/24', entries: clues_mgwcc258_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')