clues_mgwcc262_unscrambled = Array.new
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'TAURUS', number: 1, clue: 'Astrological sign that\'s also a car'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'TEDS', number: 1, clue: 'Turner, Nugent and Cruz'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALEE', number: 2, clue: 'Protected from the wind'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'UPUP', number: 3, clue: 'Words before "...and away!"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'RATTY', number: 4, clue: 'Dilapidated'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'USE', number: 5, clue: 'Put to work'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'SORTOF', number: 6, clue: 'In a way'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'TODD', number: 7, clue: '"Sweeney ___"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TYNAN', number: 7, clue: 'Tenon Ronan ___'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'OOO', number: 8, clue: 'Tic-tac-toe victory'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DUMBDORA', number: 9, clue: 'Gracie Allen character'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DRYAIR', number: 10, clue: 'It may cause a nosebleed'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'ANN', number: 11, clue: 'Landers of advice'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AGAIN', number: 11, clue: 'Once more'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'NOFUN', number: 12, clue: 'Unpleasant'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NOTME', number: 13, clue: '"Find someone else"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ELPASO', number: 14, clue: 'Texas city that borders Mexico and New Mexico'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'YOUR', number: 15, clue: '"Watch ___ step!"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'GOO', number: 16, clue: 'Gunk'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'DEUTERONOMY', number: 17, clue: 'Source of the saying "man does not live by bread alone"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'OWNS', number: 18, clue: 'Has in one\'s possession'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'AFT', number: 19, clue: 'Back, on a ship'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SEPT', number: 20, clue: 'Month before Oct.'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'TWA', number: 21, clue: 'Carrier founded in 1925'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'BARIUM', number: 22, clue: 'Element #56'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ROTHKO', number: 23, clue: 'Abstract Mark'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'YVONNEDIONNE', number: 24, clue: 'Oldest of French-Canadian girls born on May 28th, 1934'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'VISA', number: 25, clue: 'MasterCard rival'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'EMAJ', number: 26, clue: 'Musical key: abbr.'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'HOG', number: 27, clue: 'Take all of, as the covers'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'HAJJ', number: 27, clue: 'Muslim who\'s been to Mecca'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'OREO', number: 28, clue: 'Crossword cookie'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'GIRD', number: 29, clue: 'Prepare (oneself) for a shock'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'IFS', number: 30, clue: 'Unanswered questions'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'MORT', number: 31, clue: 'Zuckerman or Kondracke'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARIES', number: 32, clue: 'Another astrological sign that\'s also a car'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'EMINEM', number: 33, clue: '"8 Mile" rapper'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'FAR', number: 34, clue: 'A long way away'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'FEW', number: 34, clue: 'Not a lot'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'HOJO', number: 35, clue: 'Hotel chain founder, casually'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'OSLO', number: 36, clue: 'Norway\'s biggest city'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'JOES', number: 37, clue: 'Biden and Namath'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ONYX', number: 38, clue: 'Black gemstone'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'JERMAINEJACKSON', number: 39, clue: 'One of Michael\'s brothers'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'INNUENDO', number: 40, clue: 'Double entendre'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'NEAP', number: 41, clue: 'One of the tides'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'CHOO', number: 42, clue: 'Jimmy of shoes'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'JODI', number: 43, clue: '___ Arias trial (recent murder case)'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'NEW', number: 44, clue: 'Fresh'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'HOLEY', number: 45, clue: 'Like old socks, often'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'NINA', number: 46, clue: 'Sister ship of the Santa Maria and Pinta'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ISAIAH', number: 47, clue: 'Biblical prophet'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'TAO', number: 48, clue: '"The ___ of Pooh"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'TRIX', number: 48, clue: 'Colorful cereal'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'AIMFOR', number: 49, clue: 'Try to hit'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'OSX', number: 50, clue: 'Apple system'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'LAKESUPERIOR', number: 51, clue: 'Duluth\'s body of water'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'LOPES', number: 51, clue: 'Walks lazily'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ADELE', number: 52, clue: 'One-named singer of "Someone Like You"'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'KARMA', number: 53, clue: 'What goes around and comes around'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'EVENT', number: 54, clue: 'Happening'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'RENIN', number: 55, clue: 'Kidney enzyme'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ODAMAE', number: 56, clue: '___ Brown (Whoopi Goldberg\'s Oscar-winning role in "Ghost")'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'VIM', number: 57, clue: '___ and vigor'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'EATA', number: 58, clue: '"___ Peach" (Allman Brothers album)'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'AGOG', number: 59, clue: 'In eager anticipation'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'TELE', number: 60, clue: 'Prefix with vision or commuter'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ARES', number: 61, clue: 'God of war'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PER', number: 62, clue: 'Apiece'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'INDEXFINGER', number: 63, clue: 'It\'s pointed at things'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'DIS', number: 64, clue: 'Show no respect toward'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'IRA', number: 65, clue: 'Tax shelter, for short'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ELM', number: 66, clue: 'Common tree'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'ADIN', number: 67, clue: 'Point after deuce, if the serve was an ace'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'ORIOLE', number: 68, clue: 'Maryland bird'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SEA', number: 69, clue: 'Aegean or Adriatic'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'HOST', number: 70, clue: 'Have people over'))
clues_mgwcc262_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'RANGES', number: 71, clue: 'The Appalachians and the Andes'))
instructions = 'This week\'s contest answer is a number between 1 and 10.'
Puzzle.create(title: 'MGWCC #262 - "Group Activity"', grid: 'TAURUS.TODD.ANN|ELPASO.YOUR.GOO|DEUTERONOMY.AFT|SEPT.TWA.BARIUM|...YVONNEDIONNE|HOG.IFS.MORT...|ARIES..FAR.HOJO|JERMAINEJACKSON|JODI.NEW..HOLEY|...NINA.TAO.OSX|LAKESUPERIOR...|ODAMAE.VIM.EATA|PER.INDEXFINGER|ELM.ADIN.ORIOLE|SEA.HOST.RANGES', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/6/21', entries: clues_mgwcc262_unscrambled)
