clues_mgwcc264_unscrambled = Array.new
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SEMIS', number: 1, clue: 'Late round, casually'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SPAM', number: 1, clue: 'It\'s rarely answered'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELLA', number: 2, clue: 'Peruvian pronoun'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MAIL', number: 3, clue: 'Medieval protection'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ITSOK', number: 4, clue: '10-down, in English'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SOONAS', number: 5, clue: 'When, casually'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'THATCH', number: 6, clue: 'Roof material'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TPK', number: 6, clue: 'Hwy.'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HUR', number: 7, clue: '"Ben-___"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ARABY', number: 8, clue: 'Dry land, poetically'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TRUANCY', number: 9, clue: 'Skipping school'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'CESTBIEN', number: 10, clue: '4-down, in French'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HDS', number: 11, clue: 'Highest body pts.'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Across', answer: 'INCR', number: 12, clue: 'Hike: abbr.'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'IBIDEM', number: 12, clue: 'Preposition in footnotes'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'NIKOLA', number: 13, clue: 'Tinkering Tesla'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'CLOROX', number: 14, clue: 'Cleaning brand'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 1, col: 17, dir: 'Down', answer: 'RENEW', number: 15, clue: 'Say again, as wedding vows'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PLATO', number: 16, clue: 'Originator of the "noble lie"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'PURRED', number: 17, clue: 'Dug the petting'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 2, col: 14, dir: 'Across', answer: 'BILE', number: 18, clue: 'Spite'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ALISONKRAUSS', number: 19, clue: '"Please Read the Letter" singer, with Robert Plant (A)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'NETH', number: 20, clue: 'First foreign country I ever visited, 1990: abbr.'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 3, col: 14, dir: 'Across', answer: 'IKON', number: 21, clue: 'Holy image'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MALONE', number: 22, clue: 'Moses or Sam'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'BAT', number: 23, clue: 'Scary mammal'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'ADORE', number: 24, clue: 'More than like'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Down', answer: 'AGE', number: 24, clue: 'Historical period'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'KATHRYNBIGELOW', number: 25, clue: '"The Hurt Locker" director (A)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'HUGH', number: 26, clue: 'Grant from England'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'RERUN', number: 27, clue: 'Show already shown'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'INDIGO', number: 28, clue: 'One of seven'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'CCD', number: 29, clue: 'Included, as on correspondence'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'CABLE', number: 29, clue: 'Gondola holder'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CLEAR', number: 30, clue: 'Sweep off'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'DIANA', number: 31, clue: 'Mythical hunter'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'SHUE', number: 32, clue: 'Good surname for a podiatrist'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'CINEMAX', number: 33, clue: 'Starz rival'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALIG', number: 34, clue: 'Alistair Leslie Graham, familiarly'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'GADS', number: 35, clue: 'Wanders (about)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'GRAYED', number: 36, clue: 'Visibly aged'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'AREEL', number: 37, clue: 'Staggering'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'BEAARTHUR', number: 38, clue: 'Dorothy Zbornak portrayer (A)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'RAE', number: 39, clue: 'Woman\'s name that reverses to a part of the body'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'TUREEN', number: 40, clue: 'Stew holder'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'NICEDOG', number: 41, clue: '"Please don\'t bite me!"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'CAP', number: 42, clue: 'Put a limit on'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'EMIT', number: 43, clue: 'Send forth'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'DENIM', number: 44, clue: 'Blue material'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 16, dir: 'Down', answer: 'OOZED', number: 45, clue: 'Moved very slowly'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 8, col: 17, dir: 'Down', answer: 'GNARL', number: 46, clue: 'Knot'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LANDAU', number: 47, clue: 'Thespian Martin'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'NEO', number: 48, clue: 'Paleo- counterpart'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'OZONE', number: 49, clue: 'Trioxygen, alternatively'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'GAMEON', number: 50, clue: '"It\'s go time!"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ERASERS', number: 51, clue: 'Mechanical pencil parts'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'SPRAINED', number: 52, clue: 'In need of ice, perhaps'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'EZIOPINZA', number: 53, clue: 'Noted Don Giovanni (V)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IGOR', number: 54, clue: 'Late chess grandmaster Ivanov'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'EPILOG', number: 55, clue: 'Literary coda'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'IGNORES', number: 56, clue: 'Lets be'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Across', answer: 'TIER', number: 57, clue: 'Level'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'SAMBERG', number: 58, clue: 'Andy of digital shorts'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'SANELY', number: 58, clue: 'In a rational way'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ARISEN', number: 59, clue: 'Up'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'MITTEN', number: 60, clue: 'Piece of winter clothing'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'BAY', number: 61, clue: 'Green ___'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'NOUN', number: 62, clue: 'Word like "word"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'USMC', number: 63, clue: '"Semper Fi" folk'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'NOCASH', number: 64, clue: 'Store sign, sometimes'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Across', answer: 'MDL', number: 65, clue: '1550'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MARIANANDERSON', number: 66, clue: 'She sang at the Lincoln Memorial on Easter Sunday, 1939 (V)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'MURAL', number: 66, clue: 'Work on the wall'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'DNINE', number: 67, clue: 'Battleship guess'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'NARCO', number: 68, clue: 'Prefix with "trafficking"'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'UNITY', number: 69, clue: 'Cohesion'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'ION', number: 70, clue: 'Word after positive or hydrogen'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'MCADOO', number: 71, clue: 'NBA MVP, 1974-75'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 15, dir: 'Down', answer: 'DUAL', number: 72, clue: 'Multipurpose, in a way'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 16, dir: 'Down', answer: 'OSLO', number: 73, clue: '___ Opera House (Norwegian landmark)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 14, col: 17, dir: 'Down', answer: 'OOPS', number: 74, clue: 'Word followed by bad news'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REST', number: 75, clue: 'Take a break'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ENRICOCARUSO', number: 76, clue: 'First singer to sell a million recordings (V)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Down', answer: 'EKE', number: 76, clue: 'Palindromic verb'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Down', answer: 'CEL', number: 77, clue: 'Frame'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Down', answer: 'ODS', number: 78, clue: 'Has too much of, casually'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 16, col: 1, dir: 'Across', answer: 'ALEE', number: 79, clue: '"Hard ___!" (skipper\'s shout)'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 16, col: 6, dir: 'Across', answer: 'KEENED', number: 80, clue: 'Lamented loudly'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 16, col: 13, dir: 'Across', answer: 'SCALP', number: 81, clue: 'Sell outside a stadium'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'LYNN', number: 82, clue: 'Unisex name'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 17, col: 6, dir: 'Across', answer: 'EDSELS', number: 83, clue: 'Road failures'))
clues_mgwcc264_unscrambled.push(Entry.create(row: 17, col: 13, dir: 'Across', answer: 'HOLOS', number: 84, clue: '3-D images, for short'))
instructions = 'This week\'s contest answer is a famous fictional character.'
explanation = '<MA>TONY SOPRANO</MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #264 - "AV Club"', grid: 'SEMIS.THATCH.INCR|PLATO.PURRED.BILE|ALISONKRAUSS.IKON|MALONE..BAT.ADORE|...KATHRYNBIGELOW|CCD.SHUE.CINEMAX.|ALIG..GRAYED.....|BEAARTHUR.NICEDOG|LANDAU.NEO.GAMEON|ERASERS.EZIOPINZA|.....EPILOG..TIER|.SAMBERG.NOUN.MDL|MARIANANDERSON...|UNITY.ION..MCADOO|REST.ENRICOCARUSO|ALEE.KEENED.SCALP|LYNN.EDSELS.HOLOS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/7/5', entries: clues_mgwcc264_unscrambled, instructions: instructions, explanation: explanation)
