clues_mgwcc266_unscrambled = Array.new
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'NOUGATS', number: 1, clue: 'Nutty confections'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'NIPS', number: 1, clue: 'Uses pincers'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OKRA', number: 2, clue: 'Pod plant'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'UNIT', number: 3, clue: 'Condo, for example'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'GOV', number: 4, clue: 'End of many DC URLs'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'AWASH', number: 5, clue: 'Deluged'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'TITTER', number: 6, clue: 'Hardly a guffaw'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'STEELE', number: 7, clue: 'Brosnan portrayal'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'SAGUARO', number: 8, clue: 'Arizona\'s ___ National Park'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SELLSOUT', number: 8, clue: 'Betrays'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ALA', number: 9, clue: 'In the manner of'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'GAYE', number: 10, clue: 'Motown\'s Marvin'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'UTES', number: 11, clue: 'Pac-12 team'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AIDS', number: 12, clue: '"And the Band Played On" subject'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ROBE', number: 13, clue: 'Trial coverage?'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ONYX', number: 14, clue: 'Cameo stone'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IKNOWIT', number: 15, clue: '"You needn\'t remind me"'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 2, col: 9, dir: 'Across', answer: 'ELATION', number: 16, clue: 'Glee'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'PRIVATEPLAYEDBY', number: 17, clue: 'WHO AM I? (Part 1)'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Down', answer: 'PAIDFORHALF', number: 18, clue: 'Shared the cost'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SAT', number: 19, clue: 'Remained inactive'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'STEAL', number: 20, clue: 'Thieve'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'ESSEX', number: 21, clue: 'Roaring \'20s car name'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'THELIST', number: 22, clue: '2009 Rosanne Cash album'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TOKEN', number: 22, clue: 'Shoe on Boardwalk, e.g.'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'TECH', number: 23, clue: 'PC whiz'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'RADO', number: 24, clue: '"Hair" co-writer James'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'RAJAH', number: 24, clue: 'Indian royal'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ALAMO', number: 25, clue: 'National competitor'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'DIMAG', number: 26, clue: 'Joltin\' Joe'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'REDOES', number: 27, clue: 'Overhauls'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'SHIP', number: 28, clue: 'Craft'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'TRU', number: 29, clue: 'Play about Capote'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'TITLE', number: 29, clue: '"Wheel of Fortune" category'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'RAHAL', number: 30, clue: 'Race car driver Bobby'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'USERS', number: 31, clue: 'Detox clientele'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALIKE', number: 32, clue: 'Much the same'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'ESPN', number: 33, clue: '"SportsCenter" channel'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'FUCHSIAS', number: 34, clue: 'Purplish-red flowers'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SNOGS', number: 35, clue: 'Necks'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'JAMESBOOTHINTHE', number: 36, clue: 'WHO AM I? (Part 2)'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'BOOP', number: 37, clue: 'Betty who was a cocktail waitress in "Who Framed Roger Rabbit"'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'OUTLIVED', number: 38, clue: 'Survived'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'AMANPOUR', number: 39, clue: 'London-born CNN staffer'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'POLAR', number: 40, clue: 'On top of the world?'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'HOG', number: 41, clue: 'Glutton'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'NOTHIN', number: 42, clue: 'Reply to "Whatcha doin\'?"'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ITGIRL', number: 43, clue: 'Clara Bow, with "The"'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'NEWLEY', number: 44, clue: 'Singer who put "Pop Goes the Weasel" on Billboard\'s Hot 100'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'GELS', number: 45, clue: 'Comes together'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'PLATERS', number: 46, clue: 'Flatware workers'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'RUMPS', number: 47, clue: 'Rear ends'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TEASE', number: 48, clue: 'Rib'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'TMAN', number: 48, clue: 'Revenue collector'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ECCO', number: 49, clue: '___ Domani (wine brand)'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'AMON', number: 50, clue: 'Chief Theban deity'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'SLUG', number: 51, clue: 'Phony coin'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'EXPO', number: 52, clue: 'World\'s fair'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'ILGWU', number: 53, clue: '"Look for the union label" org.'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'JAM', number: 54, clue: 'Traffic tie-up'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'JUST', number: 54, clue: 'Equitable'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ALIT', number: 55, clue: 'Dismounted'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'MUTE', number: 56, clue: 'Remote control button'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MCMLXIVFILMZULU', number: 57, clue: 'WHO AM I? (Part 3)'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'ILL', number: 58, clue: 'Sick'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ZOE', number: 59, clue: 'Actress Saldana'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ACOUPLE', number: 60, clue: 'Two'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 14, col: 9, dir: 'Across', answer: 'REPOSIT', number: 61, clue: 'Put in storage'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NONGOLD', number: 62, clue: 'Like second- and third-place medals'))
clues_mgwcc266_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'LYSETTE', number: 63, clue: 'British actress Anthony of "Husbands and Wives" and "Look Who\'s Talking Now"'))
instructions = 'This week\'s contest answer is the author of this crossword puzzle.'
explanation = '<MA>HENRY HOOK</MA><TEXT>Henry Hook, who contsructed the puzzle, shares the name of a PRIVATE PLAYED BY / JAMES BOOTH IN THE / MCMLXIV FILM "ZULU"</TEXT>'
Puzzle.create(title: 'MGWCC #266 - "Who Am I?"', grid: 'NOUGATS.SAGUARO|IKNOWIT.ELATION|PRIVATEPLAYEDBY|SAT.STEAL.ESSEX|...THELIST.....|RADO.REDOES.TRU|ALIKE..FUCHSIAS|JAMESBOOTHINTHE|AMANPOUR..POLAR|HOG.NOTHIN.GELS|.....PLATERS...|TEASE.ILGWU.JAM|MCMLXIVFILMZULU|ACOUPLE.REPOSIT|NONGOLD.LYSETTE', :constructors => Constructor.where(:name => 'Henry Hook'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2013/7/19', entries: clues_mgwcc266_unscrambled, instructions: instructions, explanation: explanation, explanation: explanation)
