clues_mgwcc002_unscrambled = Array.new
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AARON', number: 1, clue: 'First name?'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ASSMAN', number: 1, clue: 'Word on Frank Costanza\'s proctologist\'s vanity license plate, in a "Seinfeld" episode'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AIKIDO', number: 2, clue: 'Tokyo throws'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'REELER', number: 3, clue: 'See 4-down'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ONE', number: 4, clue: 'With 3-down, shortish film'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NAZI', number: 5, clue: 'Dictatorial type'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'MAYAN', number: 6, clue: '___ calendar'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MEDUSA', number: 6, clue: 'She got a lot of guys stoned'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AROSE', number: 7, clue: 'Sprang (from)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'YAP', number: 8, clue: 'Keep talking'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ASEC', number: 9, clue: '"Gimme ___"'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'NERO', number: 10, clue: 'Emperor known for his interest in music'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'TWO', number: 11, clue: 'Second'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'THANKYOU', number: 11, clue: '"I already knew that," when spoken sarcastically'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'WHITEOIL', number: 12, clue: 'Homemade insecticide'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'OHMYGOD', number: 13, clue: '"Unreal!"'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'SIENA', number: 14, clue: 'Italian province, or its capital'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'ERASE', number: 15, clue: 'Get rid of'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'HHH', number: 16, clue: 'Veep born in South Dakota'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'SKEEZYDOPER', number: 17, clue: 'Pothead who freaks you out?'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'YOUGOTME', number: 18, clue: '"Alright, so maybe I was lying..."'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'AIM', number: 19, clue: 'Goal'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MIL', number: 20, clue: 'A thou thou'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'IOUS', number: 21, clue: 'Papers promising payment'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'COUNTY', number: 22, clue: 'Jim Hogg, Jim Wells or Tom Green, in Texas'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'USN', number: 23, clue: 'Lieutenant James E. Carter, Jr., ___'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ADER', number: 24, clue: 'Late Dutch artist Bas Jan ___'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'RIFE', number: 25, clue: 'Replete (with)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'USED', number: 26, clue: '___ trucks'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'DJIA', number: 27, clue: 'It was at 12,144.59 at 9 AM today'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'SKEG', number: 28, clue: 'Fin on a surfboard'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'NORIEGA', number: 29, clue: 'General currently incarcerated in Miami'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'ELEGY', number: 30, clue: '2008 Penelope Cruz movie'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'JOHNYOO', number: 31, clue: 'Lawyer who abetted in writing the PATRIOT Act'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ONTHEWAY', number: 32, clue: 'Coming'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'HOHOS', number: 33, clue: 'Twinkie alternatives'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'FLO', number: 34, clue: '___ Rida (rapper with the 2008 #1 hit "Low"; or, where he\'s from)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'NINO', number: 35, clue: 'Film scorer ___ Rota'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'NBC', number: 35, clue: 'GE property'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'OID', number: 36, clue: '-like'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'SLEETYBATHFUL', number: 37, clue: 'Amount of freezing rain a tub can hold?'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'SNOWTIRE', number: 37, clue: 'Buffalo ring'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'LONESTAR', number: 38, clue: 'Steakhouse chain with, ironically, no locations in Texas'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'YADA', number: 39, clue: 'When repeated twice, et cetera'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'FITS', number: 40, clue: 'Seems right'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ENO', number: 41, clue: 'Roger of ambient music'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'EMAILED', number: 41, clue: 'Wrote, often'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'GMAC', number: 42, clue: 'One way to buy a Jeep: abbr.'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'HOI', number: 43, clue: '___ polloi (the proletariat)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'MONEYED', number: 44, clue: 'Rich'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ESP', number: 45, clue: 'Zener cards test for it'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'TESTATE', number: 46, clue: 'With a will'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'TEMPLE', number: 46, clue: 'Bill Cosby\'s alma mater'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'ANDREA', number: 47, clue: 'Comic Martin'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'TOOPID', number: 48, clue: 'Not real bright, slangily'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'ETHYLS', number: 49, clue: 'Some radicals'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'AWES', number: 50, clue: 'Knocks out'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'AFEW', number: 51, clue: 'Not lots'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'FAMED', number: 52, clue: 'Known'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'SNOT', number: 53, clue: 'Kleenex crud'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ITSPAT', number: 54, clue: '1994 comedy that\'s the 93rd worst movie of all time, according to IMDb.com'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'AFRO', number: 55, clue: '___-Caribbean'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'TREX', number: 56, clue: 'Rock band named for an extinct creature'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'AMAS', number: 57, clue: 'Basic verb for 10-down'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'SHOD', number: 58, clue: 'Covered a few feet'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'DOH', number: 59, clue: 'Simpson trial outburst?'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LIT', number: 60, clue: 'Wasted'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'FRUMPYHARPY', number: 61, clue: 'Shrewish woman who doesn\'t dress well?'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'UBI', number: 62, clue: '"Semper ___ sub ___" (note: same word goes in both blanks)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'ANY', number: 63, clue: '___ minute (soon)'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ERA', number: 64, clue: 'Gain rival'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'REBEL', number: 65, clue: 'Test one\'s boundaries'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ONEIL', number: 66, clue: 'Negro Leagues great Buck ___'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DER', number: 67, clue: 'Word in many Dutch surnames'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'OXIDE', number: 68, clue: 'Silver ___'))
clues_mgwcc002_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'DYADS', number: 69, clue: 'Twosomes'))
Puzzle.create(title: 'MGWCC #2 - "It Themes Like Something\'s Missing"', grid: 'AARON.MAYAN.TWO|SIENA.ERASE.HHH|SKEEZYDOPER.AIM|MIL.IOUS.COUNTY|ADER.USED..SKEG|NORIEGA.JOHNYOO|...FLO.NINO.OID|.SLEETYBATHFUL.|ENO.GMAC.HOI...|MONEYED.TESTATE|AWES..AFEW.SNOT|ITSPAT.AMAS.DOH|LIT.FRUMPYHARPY|ERA.REBEL.ONEIL|DER.OXIDE.DYADS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2008/6/27', entries: clues_mgwcc002_unscrambled)
