clues_mgwcc031_unscrambled = Array.new
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JOAN', number: 1, clue: 'Cusack of "Say Anything," "High Fidelity" and "Grosse Pointe Blank"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JANETS', number: 1, clue: 'Reno and Jackson'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OLAFII', number: 2, clue: 'Norwegian king called "The Fat"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'AVALON', number: 3, clue: 'Legendary island'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'NANA', number: 4, clue: 'Grandma'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'INC', number: 5, clue: 'Magazine with a period in its name'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'INN', number: 5, clue: 'Business with a keeper'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'NANCY', number: 6, clue: 'Singer Sinatra'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'CHAOTIC', number: 7, clue: 'Marked by madness'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'POTTED', number: 8, clue: 'Like some plants'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PISTON', number: 8, clue: 'Detroit dunker'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ONCE', number: 9, clue: 'Not repeatedly'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'TWIXT', number: 10, clue: 'In the midst of'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TOOTOTTO', number: 11, clue: '"Bus driver on \'The Simpsons,\' blow your horn!"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ERN', number: 12, clue: 'Northeast finisher'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DDS', number: 13, clue: 'Tooth doc\'s deg.'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALVA', number: 14, clue: '1982 Nobel Peace Prize winner ___ Myrdal'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'NAH', number: 15, clue: '"Don\'t think so"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'INWORD', number: 16, clue: 'Via written language'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'NAANANNA', number: 17, clue: '"Designer Sui, bring me some Indian bread!"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ATWITTER', number: 18, clue: 'Gossiping'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'SCIONS', number: 19, clue: 'Toyota makes them'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EFLAT', number: 20, clue: '___ major (key for Beethoven)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'CONTEXT', number: 21, clue: 'Background'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'NOSHOT', number: 22, clue: 'What a hapless competitor has'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'TIO', number: 23, clue: '___ Pepe (sherry brand)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'WAYTOO', number: 24, clue: 'Overly, and then some'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ANTE', number: 25, clue: 'Chips for cards'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'TOTO', number: 26, clue: '"Africa" band'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'TACT', number: 27, clue: 'Delicate social touch'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'OOHS', number: 28, clue: 'Sighs of wonder'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SINGIN', number: 29, clue: 'Gene Kelly title word'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Down', answer: 'GAEL', number: 30, clue: '"The Motorcycle Diaries" actor ___ Garcia Bernal'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'ISNT', number: 31, clue: 'Fails to be'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'THERULES', number: 32, clue: 'Controversial 1995 bestseller for women'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'TAO', number: 33, clue: '2000 comedy "The ___ of Steve"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'ATTACH', number: 34, clue: 'Hook on'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ARABIA', number: 35, clue: 'Lawrence\'s land'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'HATCH', number: 36, clue: 'Give birth to, as a plot'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'ALOT', number: 37, clue: 'Plenty'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'STPETER', number: 38, clue: 'Famous fisherman'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'SHOP', number: 38, clue: 'Hit the mall'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'TARO', number: 39, clue: 'Posh chip source'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'POOPOPPO', number: 40, clue: 'Tire out those digging up dirt on your political campaign?'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'OCELOTS', number: 41, clue: 'Colombian cats'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'CUBE', number: 42, clue: '10\'s is 1,000'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'HAOLE', number: 43, clue: 'Non-native Hawaiian'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ARTURO', number: 44, clue: 'Jazzman Sandoval'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'RACKSUP', number: 45, clue: 'Amasses'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'ORO', number: 46, clue: 'Bacardi ___ (popular rum)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'REBA', number: 47, clue: 'Sitcom set in suburban Houston'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ENTERS', number: 48, clue: 'Gains access'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'BUTTED', number: 49, clue: 'Hit with the head'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'TOSSER', number: 50, clue: '"IRAQI COURT DELAYS TRIAL OF SHOE-___" (recent Denver Post headline)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'ERASER', number: 51, clue: 'Chalkboard tool'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'DRYERS', number: 52, clue: 'Sources of warm clothing'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'POPO', number: 53, clue: 'Cops, in slang'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'OUIJA', number: 54, clue: 'Game where the medium is the message?'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'NICKEL', number: 55, clue: 'Buffalo, for example'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'KEENE', number: 56, clue: '"Nancy Drew" author'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'ORR', number: 57, clue: 'Colton or Bobby of NHL fame'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'OUTTAKE', number: 58, clue: 'Footage showing an actor humorously botching a scene'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'TRAK', number: 59, clue: '___ Auto (car parts chain)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'ESSAY', number: 60, clue: 'Blog post, often'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Down', answer: 'SESE', number: 61, clue: 'Former Zairian dictator Mobutu ___ Seko'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'EMPIRE', number: 62, clue: 'Word after "Soviet" or "American"'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ETC', number: 62, clue: 'And so forth'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'MIL', number: 63, clue: 'www.pentagon.___ (Department of Defense\'s website)'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'SEESESSE', number: 64, clue: 'Lays eyes on a Latin verb?'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'EON', number: 65, clue: 'Period'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'TIPJAR', number: 66, clue: 'Coffee shop cylinder'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'UNO', number: 67, clue: 'Game with "skip" cards'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'SEER', number: 68, clue: 'Mystic'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'CLOAKS', number: 69, clue: 'Hides'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'PEN', number: 70, clue: 'Author'))
clues_mgwcc031_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'ERRS', number: 71, clue: 'Strays'))
Puzzle.create(title: 'MGWCC #31 - "The Inversion Version"', grid: 'JOAN.INC.POTTED|ALVA.NAH.INWORD|NAANANNA.SCIONS|EFLAT.CONTEXT..|TIO.WAYTOO.TOTO|SINGIN.ISNT.TAO|...ATTACH.HATCH|STPETER.OCELOTS|HAOLE.ARTURO...|ORO.REBA.BUTTED|POPO.NICKEL.ORR|..OUTTAKE.ESSAY|EMPIRE.SEESESSE|TIPJAR.UNO.SEER|CLOAKS.PEN.ERRS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/1/16', entries: clues_mgwcc031_unscrambled)
