clues_mgwcc036_unscrambled = Array.new
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'HOSTS', number: 1, clue: 'Guest ___ (performs an oxymoronic entertainment industry task)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'HAWES', number: 1, clue: 'London shirtmakers ___ & Curtis'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OCHRE', number: 2, clue: 'Earth tone'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'STARR', number: 3, clue: 'Good surname for an astronomer'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TIT', number: 4, clue: 'Long-tailed ___ (Eurasian bird)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SIGNIN', number: 5, clue: 'Announce one\'s presence, in a way'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'CAFE', number: 6, clue: 'Kind of business named for a drink'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'COOKE', number: 6, clue: '"Bring It On Home To Me" singer, 1961'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ALGER', number: 7, clue: 'Hiss in a courtroom'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'FALSE', number: 8, clue: '___ choice (logical fallacy)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'EYE', number: 9, clue: 'Masonic symbol of the omniscient god-king'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'IBET', number: 10, clue: '"Yeah, whatever"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'INTURN', number: 10, clue: 'Respectively'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BEERSTEIN', number: 11, clue: 'Hamburger\'s beverage holder'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ERASE', number: 12, clue: 'Get rid of'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TORTS', number: 13, clue: 'Law school class'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ACTII', number: 14, clue: 'When stuff really starts to happen, often'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OLAY', number: 15, clue: 'Oil of ___'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'NERO', number: 16, clue: 'Black, in Bari'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'WHATGOOGLE', number: 17, clue: 'PART 1 OF RIDDLE'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'OUCH', number: 18, clue: '"That was very expensive!"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'TEAR', number: 19, clue: 'Drop on one\'s head'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ERR', number: 20, clue: 'Pick poorly'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'NUKES', number: 21, clue: 'Microwaves, casually'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'BURST', number: 22, clue: 'Go pop'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'BESET', number: 22, clue: 'Plagued'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SERVICEREVERSES', number: 23, clue: 'PART 2 OF RIDDLE'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'VETO', number: 24, clue: 'Tempt an override'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'VINE', number: 25, clue: 'Hollywood crosser'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'ENH', number: 26, clue: 'Higher definition version: abbr.'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'ISNT', number: 27, clue: '"___ that true?"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ALOT', number: 28, clue: 'Scads'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ATE', number: 28, clue: 'Polished off'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'LOL', number: 29, clue: '"2 funny"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'OFITSKIND', number: 30, clue: 'In the given category'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'IRENE', number: 31, clue: '2005 Atlantic Hurricane'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ISM', number: 31, clue: 'British finish'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'ROT', number: 32, clue: 'Become inedible'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'EMO', number: 33, clue: 'Sullen'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ETA', number: 34, clue: '"CHI PS?I BETA PI ___!"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'TNT', number: 35, clue: 'Have a blast'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'AGO', number: 36, clue: 'In the past'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TOFORMSOMETHING', number: 37, clue: 'PART 3 OF RIDDLE'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'RANGE', number: 38, clue: 'Spectrum'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'MISO', number: 39, clue: 'Sapporo soup'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'HUES', number: 40, clue: 'Tints'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ELI', number: 41, clue: '"___ Stone" (ABC dramedy)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'AIMTO', number: 42, clue: 'Have as one\'s goal'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'UNTO', number: 43, clue: 'Posh preposition'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'TANS', number: 44, clue: 'Gets dark outside'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'ATEASE', number: 45, clue: 'Order in the army'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'LGE', number: 46, clue: 'Big: abbr.'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'LENO', number: 46, clue: '"Leading With My Chin" autobiographer'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'GUYANA', number: 47, clue: 'Country whose capital is Georgetown'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'MOSTGOOGLEUSERS', number: 48, clue: 'PART 4 OF RIDDLE'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'MMCCL', number: 48, clue: '241 years from now'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'OCHOA', number: 49, clue: 'Golfer Lauren'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'ORRIN', number: 50, clue: 'Thompson of the New York Giants'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'GAYLE', number: 51, clue: 'Crystal from Kentucky'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'LITES', number: 52, clue: 'Miller ___'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'EBOOK', number: 53, clue: 'Kindle product'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'RAIMI', number: 54, clue: '"The Quick and the Dead" and "Spider-Man" director Sam'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SADIE', number: 55, clue: '"Sexy ___" ("White Album" song)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MCKEE', number: 56, clue: 'Thom ___ (contestant who won $312,700 on "Tic Tac Dough" in 1980, an American game show record at the time)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'RAINY', number: 57, clue: 'Coming down hard'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'BAA', number: 58, clue: '"I\'ll do whatever I\'m told"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'CHIA', number: 59, clue: '___ Obama (plant product marketed in 2009)'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'TRYTOAVOID', number: 60, clue: 'PART 5 OF RIDDLE'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'TWO', number: 60, clue: 'Second'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'VAL', number: 61, clue: 'Kilmer of "Thunderheart"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CONS', number: 62, clue: 'Reasons not to'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'WILE', number: 63, clue: 'Craft'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'NAOMI', number: 64, clue: 'Wolf who warns of creeping fascism in "The End of America"'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'LADE', number: 65, clue: 'Burden'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'ONES', number: 66, clue: 'Many Federal Reserve Notes'))
clues_mgwcc036_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ALKIE', number: 67, clue: 'Boozer'))
Puzzle.create(title: 'MGWCC #36 - "Get Back Online"', grid: 'HOSTS.CAFE.IBET|ACTII.OLAY.NERO|WHATGOOGLE.TEAR|ERR.NUKES.BURST|SERVICEREVERSES|...ENH...ISNT..|ALOT..IRENE.ETA|TOFORMSOMETHING|ELI.AIMTO..UNTO|..TANS...LGE...|MOSTGOOGLEUSERS|MCKEE.RAINY.BAA|CHIA.TRYTOAVOID|CONS.WILE.NAOMI|LADE.ONES.ALKIE', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/2/20', entries: clues_mgwcc036_unscrambled)
