clues_mgwcc047_unscrambled = Array.new
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Across', answer: 'AMIS', number: 1, clue: '"Time\'s Arrow" novelist'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AGAVES', number: 1, clue: 'Plants that yield mezcal'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'MANETS', number: 2, clue: 'Pricy paintings'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ISH', number: 3, clue: '-like'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SPADE', number: 4, clue: '"Black Sheep" actor'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'ARM', number: 5, clue: 'Branch'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AVA', number: 5, clue: '___ Moore ("Nip/Tuck" character)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'RAN', number: 6, clue: 'Analyzed'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MCKEE', number: 7, clue: 'Jay of the St. Louis Blues'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'BABA', number: 8, clue: 'Word in a Who song title'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BANKS', number: 8, clue: '"Mary Poppins" name'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ALS', number: 9, clue: 'Davis and Smith'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'BAA', number: 10, clue: '"I believe what politicians say"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ASS', number: 11, clue: 'Unpleasant person'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 2, col: 2, dir: 'Across', answer: 'GASPS', number: 12, clue: 'Betrays disbelief'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'STER', number: 13, clue: 'Joke\'s ending, possibly'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'VAC', number: 14, clue: 'Household appliance, for short'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ALAS', number: 15, clue: '"Give me your sympathy!"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MANHATTANKANSAS', number: 16, clue: '"The Little Big Apple"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Down', answer: 'MEL', number: 16, clue: 'Obsessed fan on "Flight of the Conchords"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'TENE', number: 17, clue: 'High-rise apartment number, perhaps'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'AER', number: 18, clue: 'Word painted on green planes'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EVE', number: 19, clue: 'St. John\'s ___'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'DEE', number: 20, clue: '"What\'s Happening!!" daughter'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'EEK', number: 21, clue: 'Shout while leaping onto a chair'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LETTERNEVERSENT', number: 22, clue: 'R.E.M. song off "Reckoning"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TRIS', number: 23, clue: 'Speaker on the field'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'EXTINCT', number: 24, clue: 'Like homo floresiensis'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'VERP', number: 25, clue: 'E-mail program feature (hidden in RIVER PHOENIX)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Down', answer: 'ENZI', number: 26, clue: 'Wyoming senator Mike'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'NAIR', number: 27, clue: 'Depilatory brand'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'TELL', number: 28, clue: 'Poker giveaway'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Across', answer: 'SSR', number: 29, clue: 'Part of a Cold War empire: abbr.'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'EXE', number: 30, clue: 'River that flows both ways, so to speak'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'NAE', number: 31, clue: 'Clan rejection'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'INC', number: 32, clue: '"Fast Company" rival'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'NIK', number: 33, clue: '-proponent'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'CSI', number: 34, clue: 'Show since 2000'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'TRIP', number: 35, clue: 'Riot'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'IPS', number: 36, clue: 'Some address markers'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'PIC', number: 37, clue: 'Photo'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ZIL', number: 38, clue: 'Soviet limo'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MISSISSIPPIGIRL', number: 39, clue: '#1 country hit of 2005 for Faith Hill'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'MILF', number: 39, clue: '"___ Island" (Tina Fey-written "30 Rock" episode featuring attractive older women)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'INOR', number: 40, clue: '"Are you ___ out?"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'SILO', number: 41, clue: 'Plains landscape feature'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'SHOP', number: 42, clue: 'See 43-down'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'GIFT', number: 43, clue: 'With 42-down, feature of most hospitals'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'INI', number: 44, clue: 'Singer Kamoze'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'KIHN', number: 45, clue: 'Greg ___ Band (group with the 1983 hit "Jeopardy")'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'SCI', number: 46, clue: '___ Fi Channel'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'LOL', number: 47, clue: 'Chat room props'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'OCH', number: 48, clue: 'Ben Nevis cry'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'HOWS', number: 49, clue: '"___ that again?"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'FSK', number: 50, clue: 'KGB\'s successor'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'STORKS', number: 51, clue: 'Baby carriers'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'KORBUT', number: 52, clue: '"The Sparrow from Minsk"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'FROMTOPTOBOTTOM', number: 53, clue: 'Thoroughly'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'MOUTH', number: 54, clue: 'Cavity for a canine'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'TOM', number: 55, clue: 'Waits onstage'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'OFBUD', number: 56, clue: '"And Billy likes to peel the labels off his bottles ___" (Sheryl Crow lyric)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'BOUT', number: 57, clue: 'Spell'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'OKBUT', number: 58, clue: '"True, however..."'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'MOS', number: 59, clue: '___ def (surely)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Across', answer: 'OOF', number: 60, clue: '"I\'ve been hit!"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'WOK', number: 61, clue: '___ This Way (Chinese restaurant in Austin, Tex.)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ORO', number: 62, clue: '5 Soles de ___ (Peruvian coin)'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'COLUMBUSSUBURBS', number: 63, clue: 'Marble Cliff, Ohio, and Grove City, Ohio, for two'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'CPU', number: 63, clue: 'Computer\'s brain'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'OSH', number: 64, clue: '___Kosh B\'Gosh clothing'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 3, dir: 'Down', answer: 'LSU', number: 65, clue: 'Baton Rouge inst.'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ULM', number: 66, clue: 'Neu-___, Germany'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'SUV', number: 67, clue: 'Big wheels'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'URS', number: 68, clue: 'USA rival, in Cold War Olympics shorthand'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'PSST', number: 69, clue: '"Over here!"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ULU', number: 70, clue: 'Blubber cutter'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'TURKU', number: 71, clue: 'Finland\'s fifth-biggest city'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'UHUH', number: 72, clue: '"Negatory"'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DMV', number: 73, clue: 'Patty and Selma\'s employer'))
clues_mgwcc047_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'TSST', number: 74, clue: 'Palindromic, onomatopoeic "South Park" episode title'))
instructions = 'This week\'s contest answer word is a well-known four-letter geographical place name.'
explanation = '<MA>IOWA</MA><TEXT>Dividing the grid up into 5 horizontal bands of three rows each, we see that each band contains only a certain vowel (only A in rows 1, 2, and 3, only E in 4, 5, and 6, etc.). The only exceptions are the I at 3-Down, the A in 27-Down/31-Across, the W at 61-Across, and the O at 64-Down. These letters anagram to the answer. Note that W, like Y, is often considered a vowel in certain contexts. This puzzle was somewhat controversial since the W functions as a vowel in 49-Down (HOW\'S) but as a consonant in 61-Across (WOK).</TEXT>'
Puzzle.create(title: '#47 - "Disconsonant Vowels"', grid: '.AMIS..ARM.BABA|.GASPS.VAC.ALAS|MANHATTANKANSAS|EVE.DEE..EEK...|LETTERNEVERSENT|.SSR..EXE...NAE|...INC.TRIP.ZIL|MISSISSIPPIGIRL|INI.KIHN.SCI...|LOL...OCH..FSK.|FROMTOPTOBOTTOM|...OOF..WOK.ORO|COLUMBUSSUBURBS|PSST.ULU.TURKU.|UHUH.DMV..TSST.', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/5/8', entries: clues_mgwcc047_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')