clues_mgwcc048_unscrambled = Array.new
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'NOTME', number: 1, clue: '"Find someone else to do it!"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'NAWS', number: 1, clue: 'Dialectical turndowns'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OBEY', number: 2, clue: 'Do what you\'re told'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'THELAKERS', number: 3, clue: 'Staples Center basketball team'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MOW', number: 4, clue: 'Lower the lawn'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ERICA', number: 5, clue: 'Hill or Jong'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'SIMPS', number: 6, clue: 'Easily fooled people'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'SELENA', number: 6, clue: '1997 title role for Jennifer Lopez'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'IBI', number: 7, clue: 'There, to 44-across'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'MOE', number: 8, clue: 'Bart often crank calls him'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'POW', number: 9, clue: 'Punching sound'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'SKI', number: 10, clue: 'Schuss'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'TOS', number: 11, clue: 'Talking-___ (tongue lashings)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TIKKA', number: 11, clue: 'Chicken ___ masala'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ORIBI', number: 12, clue: 'African antelope'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'STEYN', number: 13, clue: 'Gadfly journalist Mark ___'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ABHOR', number: 14, clue: 'Truly despise'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'EBOOK', number: 15, clue: 'Monitor reading?'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'IRT', number: 16, clue: 'NYC subway of yore'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'WEEWILLIEWINKIE', number: 17, clue: 'Sleepy fictitious Scotsman'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'LEI', number: 18, clue: 'Waikiki wear'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'NOG', number: 19, clue: 'Egg ___'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SYL', number: 20, clue: 'Pt. of a word'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'CEE', number: 21, clue: 'Letter after "bee"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'OKBY', number: 22, clue: 'Fine with'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Across', answer: 'AGAINANDAGAIN', number: 23, clue: 'Endlessly'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'GARN', number: 24, clue: 'Astronaut and former Senator Jake'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'ALPHORN', number: 25, clue: 'Innsbruck instrument'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'NILE', number: 26, clue: 'Word in an Agatha Christie title'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'DEATH', number: 27, clue: 'Another word from the same Agatha Christie title'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'ANNAO', number: 28, clue: 'Famous Freud subject, known by her (pseudonymous) first name and last initial'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ASKA', number: 29, clue: '"___ silly question..."'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ASTO', number: 29, clue: 'About'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'SHUN', number: 30, clue: 'Avoid socially'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'ALIEN', number: 31, clue: 'Creature in sci-fi movies'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SHERPA', number: 32, clue: 'Guide to the Himalayas'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'PESCI', number: 33, clue: '"Goodfellas" actor'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'ADHOC', number: 34, clue: '___ committee'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'PLAN', number: 35, clue: 'Sketch out a course of action'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'PSU', number: 36, clue: 'Nittany Lions\' sch.'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'PLANETRIP', number: 36, clue: 'Voyage among the clouds'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'SECT', number: 37, clue: 'Religious group'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'USES', number: 38, clue: 'Takes drugs, in slang'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'TURNEDTHETABLES', number: 39, clue: 'Altered a situation\'s power dynamics'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'TORO', number: 40, clue: 'John Deere rival'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'BRAN', number: 41, clue: 'Cracklin\' Oat ___ (Kellogg\'s cereal)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ONS', number: 42, clue: 'Put-___ (pranks)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'SHOO', number: 43, clue: 'Word to a gnat'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'HORACE', number: 44, clue: 'Latin poet who coined the phrase "carpe diem"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'CORRS', number: 45, clue: 'Noted Irish band, with "The"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'SCOURS', number: 46, clue: 'Searches thoroughly'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'ANTS', number: 47, clue: 'Sign it\'s time to clean the kitchen'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CHILICONCARNE', number: 48, clue: 'Cook-off food'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'COHEN', number: 48, clue: 'Ben & Jerry\'s co-founder Ben'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'HAUTE', number: 49, clue: 'Terre ___, Ind.'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'ITBAD', number: 50, clue: 'Have ___ (suffer)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'LYE', number: 51, clue: 'More common name for caustic soda'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ARM', number: 52, clue: 'Quarterback\'s pride'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'REPLY', number: 53, clue: 'E-mail program button'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'OATY', number: 54, clue: 'Like many breakfast cereals'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ORE', number: 55, clue: 'Eugene\'s state: abbr.'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TWA', number: 56, clue: '___ Flight 800 (still unexplained 1996 explosion off Long Island)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'WERE', number: 57, clue: '"Where ___ you?"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AYES', number: 58, clue: 'Pro team?'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HUBERTHHUMPHREY', number: 59, clue: 'Vice President from Minnesota'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'RBS', number: 60, clue: 'John Riggins and LaDainian Tomlinson: abbr.'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'TAP', number: 61, clue: 'Faucet'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'HUE', number: 62, clue: 'Homophone for 63-down'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'HEW', number: 63, clue: 'Homophone for 62-down'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'HOI', number: 64, clue: '___ polloi (general population)'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ETA', number: 65, clue: 'Airport arrival approximation, abbreviated'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'BAUER', number: 66, clue: '"24" agent Jack ___'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'LOIRE', number: 67, clue: 'French river known for its valley'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'NED', number: 68, clue: '1998 Irish comedy "Waking ___ Devine"'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'SPEWS', number: 69, clue: 'Spits out'))
clues_mgwcc048_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'YIPES', number: 70, clue: '"Omigosh!"'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #48 - "Quite Quaint Quintet"', grid: 'NOTME.SIMPS.TOS|ABHOR.EBOOK.IRT|WEEWILLIEWINKIE|SYL.CEE....OKBY|..AGAINANDAGAIN|ASKA..ALIEN....|SHERPA.PLAN.PSU|TURNEDTHETABLES|ONS.SHOO.HORACE|....CORRS..ANTS|CHILICONCARNE..|OATY....ORE.TWA|HUBERTHHUMPHREY|ETA.BAUER.LOIRE|NED.SPEWS.YIPES', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/5/15', entries: clues_mgwcc048_unscrambled, instructions: instructions, explanation: explanation)
