clues_mgwcc004_unscrambled = Array.new
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SHOT', number: 1, clue: 'Broken for good'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SERA', number: 1, clue: '1968 comedy "Buona ___, Mrs. Campbell"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HOOD', number: 2, clue: 'The ___ (one\'s own part of town)'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ONCD', number: 3, clue: 'Stored, in a way'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TSK', number: 4, clue: '"You should not have done that"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'MISS', number: 5, clue: 'Word before any U.S. state'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MICAH', number: 5, clue: 'Political writer Joshua ___ Marshall'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'INK', number: 6, clue: 'Press'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SEE', number: 7, clue: '"Get it?"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'STRATA', number: 8, clue: 'Societal levels'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'DUCK', number: 9, clue: '"Watch out!"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'DIVAC', number: 9, clue: 'Former center in L.A.'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'UMIAK', number: 10, clue: 'Literally, "woman\'s boat"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CANBE', number: 11, clue: 'Often turns into'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KOSAR', number: 12, clue: '1987 Pro Bowl quarterback'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EONS', number: 13, clue: 'Hadean and Archean, for two'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'BINET', number: 14, clue: 'IQ pioneer Alfred'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'BUSTLED', number: 14, clue: 'Showed great activity'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'IMAO', number: 15, clue: '"So sayeth me," online'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ROCKSUCKER', number: 16, clue: 'Old name for the lamprey eel'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'STOW', number: 17, clue: 'Pack'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'VINS', number: 18, clue: '___ blancs'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ADD', number: 19, clue: 'Also mention'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'TSA', number: 20, clue: 'Govt. arm whose website notes: "All liquids, gels, and aerosols must be placed in a single, quart-sized, zip-top, clear plastic bag.  Gallon-size bags or bags that are not zip-top such as fold-over sandwich bags are not allowed."'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'ABAABA', number: 21, clue: 'Sestet rhyme scheme used by Dante Alighieri and John Berryman'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'BULOW', number: 22, clue: 'Sunny von ___ (famed victim of attempted murder)'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'MOTHERTUCKER', number: 23, clue: 'Season Five "Family Guy" episode centered on one of Peter\'s parents'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'MANET', number: 23, clue: '"Olympia" painter'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'EMERITA', number: 24, clue: 'Professor ___'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'RENTS', number: 25, clue: 'Isn\'t buying it'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SCRAWL', number: 26, clue: 'Doctor\'s handwriting, stereotypically'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'SASS', number: 26, clue: 'Disrespect'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'CREE', number: 27, clue: 'Some Montanans'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'ROVE', number: 28, clue: 'He\'s disparagingly called "Unca Karl"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'MEAL', number: 29, clue: 'Happy ___'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ARON', number: 30, clue: 'Chess great ___ Nimzovich'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'EDEN', number: 31, clue: 'Steinbeck title word'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'DIREC', number: 32, clue: 'Letters before TV, in a brand name'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'OSTIA', number: 33, clue: 'Ancient Rome\'s port'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'SOLON', number: 34, clue: 'Athenian reformer'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'TREY', number: 35, clue: '"South Park" co-creator Parker'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'IDED', number: 36, clue: 'Pegged'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'ASKS', number: 37, clue: 'Invites'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'SEVENDIRTYWORDS', number: 38, clue: 'Famous routine of 48-across'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'NOWGO', number: 39, clue: '"So beat it!"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'YELLFOR', number: 40, clue: 'Summon noisily'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SEETO', number: 41, clue: 'Mind'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'RISE', number: 42, clue: 'Move up'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'LEEK', number: 43, clue: 'Potato ___ soup'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'WHET', number: 44, clue: 'Sharpen'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'HEPCAT', number: 45, clue: 'Cool type'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'LLOYDS', number: 46, clue: 'London insurers'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'LIAR', number: 47, clue: '"You know they are a ___" (grammatically incorrect Doors line)'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'GEORGECARLIN', number: 48, clue: 'He said in 2007, "I always question the received reality"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'GHANA', number: 48, clue: 'The Gold Coast, now'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'EIDER', number: 49, clue: 'Down on a bed'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'OPINE', number: 50, clue: 'Say what you think'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'RHEAS', number: 51, clue: 'Big birds'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ROSAS', number: 52, clue: 'Parks and more'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HIPHOP', number: 53, clue: 'Beatboxing, breakdancing, etc.'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'OFA', number: 54, clue: 'Diary ___ Crossword Fiend (noted blog)'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'TSS', number: 55, clue: 'Gender-benders, in personal ads'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'THOU', number: 55, clue: 'Word used with "art"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'SIGN', number: 56, clue: '"___ here"'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'SPOT', number: 57, clue: 'Locate'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ADIE', number: 58, clue: 'Throw ___ (go, sometimes)'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'CENSORSHIP', number: 59, clue: 'Theme of this puzzle'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ERI', number: 60, clue: 'Olympic abbreviation of Asmara\'s country'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'NON', number: 61, clue: 'Nice response'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'SPA', number: 62, clue: 'Hotel feature'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NENA', number: 63, clue: 'German pop star ___ Kerner'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'AROAR', number: 64, clue: 'Raging'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'POGO', number: 65, clue: 'Stick in the air'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ARES', number: 66, clue: 'NASA rocket series'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TINS', number: 67, clue: 'Bath containers'))
clues_mgwcc004_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'AUNT', number: 68, clue: '"Beloved ___" ("Curb Your Enthusiasm" episode)'))
instructions = 'This week\'s contest answer is a seven-letter word that describes a good one we recently lost (N.B.: the contest answer word does not begin with the letter D)'
explanation = '<MA>MORDANT</MA><TEXT>The grid contains seven entries that correspond to George Carlin\'s "Seven Dirty Words," but with one letter changed. The new letters anagram to the answer. Note that DORMANT is also an anagram of the letters, which is why Matt provided the N.B. in the instructions. MORDANT is also an apt description of George Carlin\'s style.</TEXT>'
Puzzle.create(title: '#4 - "For the Last Time -- You Can\'t Say That!"', grid: 'SHOT..MISS.DUCK|EONS.BINET.IMAO|ROCKSUCKER.VINS|ADD.TSA..ABAABA|...MOTHERTUCKER|SCRAWL.MEAL....|ARON.EDEN.OSTIA|SEVENDIRTYWORDS|SEETO.RISE.LEEK|....WHET.LLOYDS|GEORGECARLIN...|HIPHOP..OFA.TSS|ADIE.CENSORSHIP|NENA.AROAR.POGO|ARES.TINS..AUNT', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2008/7/11', entries: clues_mgwcc004_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')