clues_mgwcc053_unscrambled = Array.new
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'RATEDG', number: 1, clue: 'Like "Toy Story" and "Finding Nemo"'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'RABIES', number: 1, clue: 'Foaming-at-the-mouth condition'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AMILATE', number: 2, clue: 'Question from a person who\'s just rushed in'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'TELLSALL', number: 3, clue: 'Spares no lurid details'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ELL', number: 4, clue: 'Kay follower'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'DISC', number: 5, clue: '___ golf'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GOBLIN', number: 6, clue: 'Common Halloween costume'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'VAIL', number: 7, clue: 'Resort about 35 miles from Aspen'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'VELDT', number: 7, clue: 'Scrub areas of southern Africa'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ATL', number: 8, clue: 'Mauritania\'s ocean: abbr.'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'INS', number: 9, clue: 'Personal connections'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'LAB', number: 10, clue: 'Physicist\'s workplace'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'APU', number: 11, clue: 'Hank voices him'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ATLAST', number: 11, clue: '"Finally!"'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PALLID', number: 12, clue: 'Not too hale-looking'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'UPSETS', number: 13, clue: 'Surprising wins'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AMELIO', number: 14, clue: '1990s Apple CEO Gil ___'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'ETNA', number: 15, clue: 'Italy\'s tallest non-Alpine mountain'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'TAP', number: 16, clue: 'Touch on the shoulder'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BILLSBILLSBILLS', number: 17, clue: '#1 hit for Destiny\'s Child in 1999'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'IOF', number: 18, clue: '"So full was ___ slumber at that point"--Dante'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Down', answer: 'IBI', number: 19, clue: 'There, to Caesar'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ILL', number: 20, clue: 'Unwell'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'CLOD', number: 21, clue: 'Clumsy oaf'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'BALE', number: 22, clue: 'Christian of "American Psycho"'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'EAST', number: 23, clue: '___ Berlin'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TRAIL', number: 24, clue: 'Lag behind'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Across', answer: 'IFTHISISIT', number: 25, clue: '#6 Huey Lewis & the News hit of 1984'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'HEMIN', number: 26, clue: 'Restrict the movement of'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'ICON', number: 27, clue: 'Larger-than-life figure'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'SUNSET', number: 28, clue: 'Death, in metaphor'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'STARIN', number: 29, clue: 'Headline, as a film'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Down', answer: 'INVEST', number: 30, clue: 'Get stocky, as it were'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'ECU', number: 31, clue: 'Precursor to the euro'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Across', answer: 'TDS', number: 32, clue: 'Six-point scores: abbr.'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'ELAN', number: 33, clue: 'Verve'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'KIMONO', number: 34, clue: 'Geisha\'s garment'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'KNISH', number: 34, clue: 'It\'s doughy in a deli'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'IGO', number: 35, clue: '"Can ___ now?"'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Down', answer: 'OILUP', number: 36, clue: 'Prepare to wrestle, Turkish-style'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Across', answer: 'LIVINGINSIN', number: 37, clue: '#9 Bon Jovi hit of 1989'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ISIS', number: 38, clue: 'Motherhood deified'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'NINEFIVE', number: 39, clue: 'Almost a week into September, when written out'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'LESION', number: 40, clue: 'Tissue problem'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ELIS', number: 41, clue: 'Some New Haveners'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SENORES', number: 42, clue: 'Misters of Managua'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'AVA', number: 43, clue: '"___ Adore" (Smashing Pumpkins song about a girl with a palindromic first name)'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'ANIMAL', number: 43, clue: 'Okapi, opossum or ocelot'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'VIRILE', number: 44, clue: 'Manly'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'AGASSI', number: 45, clue: 'Graf\'s husband'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Across', answer: 'SIS', number: 46, clue: '"Pretty sneaky, ___" (memorable line from a 1980\'s Connect Four ad)'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'ITUNES', number: 47, clue: 'Digital record store'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ITSPAT', number: 47, clue: '1994 comedy whose promotional posters featured a huge question mark'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'STELLA', number: 48, clue: 'Classic Brando shout'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'NIGHTSHIFT', number: 49, clue: 'Only Commodores hit without Lionel Richie'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Down', answer: 'HQS', number: 50, clue: 'Where CEOs work'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ILIAD', number: 51, clue: 'Trojan War epic'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'FOP', number: 52, clue: 'Metrosexual, perhaps'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 11, col: 12, dir: 'Across', answer: 'PENT', number: 53, clue: '___-up rage'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'IRAQ', number: 54, clue: 'Country about the size of California'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'LOST', number: 55, clue: 'Plane crash show'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Down', answer: 'TILE', number: 56, clue: 'One of 100 in Scrabble'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'FOE', number: 57, clue: 'No friend'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'MISSISSIPPIGIRL', number: 58, clue: '#1 country hit of 2005 for Faith Hill'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'ISM', number: 59, clue: 'Suffix with Yogi or Yiddish'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'SHE', number: 60, clue: 'Word whose first letter is sometimes seen in parentheses'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'SEA', number: 61, clue: 'Irish or Dead'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'GER', number: 62, clue: 'Where some people miss their marks: abbr.'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ALS', number: 63, clue: 'Capone and Pacino'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'SHEA', number: 64, clue: 'New York\'s William A. ___ Municipal Stadium'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'ALEVEL', number: 65, clue: 'Parking garage section, perhaps'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'LEI', number: 66, clue: '"Did you get ___\'d?" (cheesy question asked of someone who\'s just returned from Hawaii)'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'MEAD', number: 67, clue: 'Drink made from honey'))
clues_mgwcc053_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'TERESA', number: 68, clue: 'Nun of Calcutta'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #53 - "Doctor My Eyes"', grid: 'RATEDG.VAIL.APU|AMELIO.ETNA.TAP|BILLSBILLSBILLS|ILL.CLOD...BALE|EAST.IFTHISISIT|STARIN..ECU.TDS|.ELAN.KIMONO...|..LIVINGINSIN..|...LESION.ELIS.|AVA.SIS..ITUNES|NIGHTSHIFT.PENT|IRAQ...LOST.FOE|MISSISSIPPIGIRL|ALS.SHEA.ALEVEL|LEI.MEAD.TERESA', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/6/19', entries: clues_mgwcc053_unscrambled, instructions: instructions, explanation: explanation)
