clues_mgwcc054_unscrambled = Array.new
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SEEMOK', number: 1, clue: 'Appear alright at first glance'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SIEM', number: 1, clue: '___ Reap (historic Cambodian city)'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELBA', number: 2, clue: 'Exile isle'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ELAL', number: 3, clue: 'Transportation to Tel Aviv'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MIYAZAKI', number: 4, clue: '"Princess Mononoke" director Hayao ___'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ONE', number: 5, clue: 'Unified'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'KIRSTY', number: 6, clue: 'MacColl of \'80s-\'90s pop'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'ATOM', number: 7, clue: 'Small amount of gold or silver'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ATTY', number: 7, clue: 'Court figure: abbr.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'TOIL', number: 8, clue: 'Work very hard'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ONCE', number: 9, clue: 'Not repeatedly'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'MEAN', number: 10, clue: 'Average'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'PPS', number: 11, clue: '"Another thing I forgot to mention is..."'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'PAVLOV', number: 11, clue: 'Stimulating scientist'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'PLEASE', number: 12, clue: 'Make happy'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SIGNAL', number: 13, clue: 'Indicate'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ILLINI', number: 14, clue: 'Fighting Midwesterners'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'TONE', number: 15, clue: '"Don\'t take that ___ with me!"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ALI', number: 16, clue: 'Boxing biopic'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'EBAYEROTICA', number: 17, clue: 'Old issues of Playboy you can bid on?'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'OTS', number: 18, clue: 'Extra pds.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'VEG', number: 19, clue: 'Just chill'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MALA', number: 20, clue: 'Bad: Sp.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'STYLENOLAN', number: 21, clue: 'Give pitcher Ryan a makeover?'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'ORE', number: 22, clue: 'Calif. neighbor'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ZITS', number: 23, clue: 'Face problems'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'INAJAM', number: 24, clue: 'Stuck'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'ROSA', number: 25, clue: 'Sub ___ (secretly)'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LITANY', number: 26, clue: 'Laundry list'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'LOM', number: 26, clue: 'Herbert of the Pink Panther movies'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ISA', number: 27, clue: '"This ___ joke, right?"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'TAR', number: 28, clue: 'Smear'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'SEALEVEL', number: 29, clue: 'Death Valley is below it'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'SONYS', number: 29, clue: 'Some HDTVs'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ERAS', number: 30, clue: 'Jacksonian and Clinton'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ACC', number: 31, clue: 'UVA, FSU, et al.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'LAIDON', number: 32, clue: 'Applied, as flattery'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OSAKA', number: 33, clue: 'Japan\'s ___ Castle'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'LORCA', number: 34, clue: 'Poet killed in the Spanish Civil War'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'LABS', number: 34, clue: 'Popular dogs, for short'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MARIJUANACINEMA', number: 35, clue: 'Cheech & Chong movies, for example?'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'URI', number: 36, clue: 'Gullible-getter Geller'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'NOREALLY', number: 37, clue: '"I\'m completely serious!"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'EVE', number: 38, clue: 'St. Mark\'s ___ (Apr. 24)'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'MEN', number: 39, clue: 'Uncles, usually'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'ASA', number: 40, clue: '"___ Man Thinketh"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ARBYS', number: 41, clue: 'KFC rival'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'DOVES', number: 42, clue: 'No warmongers'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'NEARMISS', number: 43, clue: 'Sky scare'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'NOMADS', number: 43, clue: 'Many Tibetans'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ELAINE', number: 44, clue: 'Former Labor Secretary Chao'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'AIRMAN', number: 45, clue: 'He gets high at work'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'REM', number: 46, clue: '"Perfect Circle" band'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'LORENA', number: 47, clue: 'John Bobbitt\'s ex-wife'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'LOGINS', number: 47, clue: 'Computer entries'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'OLIE', number: 48, clue: '___ the Goalie (hockey nickname)'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'IONE', number: 49, clue: 'Skye of "Zodiac"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'INV', number: 49, clue: 'Stock: abbr.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MARMOTRING', number: 50, clue: 'Illegal squirrel-smuggling operation?'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'OTTO', number: 51, clue: 'Palindromic "Simpsons" character'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'TOOL', number: 52, clue: 'Person often taken advantage of'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'RATE', number: 53, clue: 'Use a scale from 1 to 10'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'IDOS', number: 54, clue: 'Wedding day exchange'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'ABIT', number: 55, clue: 'Kind of'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'BASE', number: 56, clue: 'First, second or third, but not fourth'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'IGOR', number: 57, clue: 'Borodin opera "Prince ___"'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'TENS', number: 58, clue: 'Hamiltons'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AIM', number: 59, clue: 'Intent'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'TOADVILLAGE', number: 60, clue: 'Where some amphibians live?'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'LEA', number: 61, clue: 'Actress Thompson'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'DNA', number: 62, clue: 'Encoded material'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'TOTO', number: 63, clue: 'Baum barker'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'NELSON', number: 64, clue: 'Willie or Craig T.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SEN', number: 65, clue: 'Obama, once: abbr.'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'OLES', number: 66, clue: 'Shouts at the successful'))
clues_mgwcc054_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'SAYERS', number: 67, clue: 'Author of the first prominent crossword-based mystery story, 1925'))
Puzzle.create(title: 'MGWCC #54 - "Achy Breaky Heart"', grid: 'SEEMOK.ATOM.PPS|ILLINI.TONE.ALI|EBAYEROTICA.VEG|MALA.STYLENOLAN|...ZITS....ROSA|LITANY.SEALEVEL|OSAKA.LORCA....|MARIJUANACINEMA|....ARBYS.DOVES|NEARMISS.LORENA|OLIE....IONE...|MARMOTRING.ABIT|AIM.TOADVILLAGE|DNA.TOTO.NELSON|SEN.OLES.SAYERS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/6/26', entries: clues_mgwcc054_unscrambled)
