clues_mgwcc060_unscrambled = Array.new
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'GABOR', number: 1, clue: '"Lili" actress, 1953'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'GEL', number: 1, clue: 'Get hard'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ABE', number: 2, clue: 'Ed\'s predecessor in New York City'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'BOA', number: 3, clue: '___ madagascariensis (long snake)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OLDSPICE', number: 4, clue: 'Makers of the Red Zone body wash'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'RANWITH', number: 5, clue: 'Had as one\'s friends'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'TARPS', number: 6, clue: 'Covers'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TAWNY', number: 6, clue: 'Orange-brown'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ASHE', number: 7, clue: 'Nastase beat him in the 1972 U.S. Open final'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'RYE', number: 8, clue: '"The ___" ("Seinfeld" episode set partly in a bakery)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PER', number: 9, clue: 'Contained in each'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'STENNIS', number: 10, clue: 'U.S.S. John C. ___ (one of America\'s 12 active aircraft carriers)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'HAH', number: 11, clue: '"I knew it!"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'HITADEADEND', number: 11, clue: 'Misstep in a labyrinth'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ALITO', number: 12, clue: 'Noted 1975 Yale Law School graduate'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HECHE', number: 13, clue: '"Donnie Brasco" actress'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EBOLA', number: 14, clue: 'Infamously eponymous Congolese river'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'ASYET', number: 15, clue: 'Hitherto'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'ILE', number: 16, clue: '___-a-Vache, Haiti'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LEADNOWHERE', number: 17, clue: 'What wild goose chases do'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'OILY', number: 18, clue: 'Like bad hummus'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'TIC', number: 19, clue: 'Unwanted movement'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'SWINE', number: 20, clue: 'Animals in recent headlines'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'NEATH', number: 21, clue: '"___ the Arizona Skies" (1934 John Wayne movie)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'EEC', number: 22, clue: 'Its flag showed a circle of twelve gold stars on a blue background: abbr.'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'HAPPILY', number: 23, clue: 'Without reservations'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'HEDGE', number: 23, clue: 'Fence alternative'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'AQUAM', number: 24, clue: 'In ___ (submerged in water)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'PUTTOGETHER', number: 25, clue: 'Join'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'JANEDOE', number: 26, clue: 'No-namer, in a way'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'JONAH', number: 26, clue: '"Your Code Name Is ___" (classic Choose Your Own Adventure book)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'AVEC', number: 27, clue: '___ curiosit&#233; (inquisitively)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'EQUITY', number: 28, clue: 'Part of HELOC'))
clues_mgwcc060_unscrambled.push(Entry.create(dir: 'Down', answer: '-', number: 28, clue: 'Any'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'NOVICE', number: 29, clue: 'Unskilled party'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'NOMAS', number: 29, clue: '"I can\'t eat another bite"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DUTCH', number: 30, clue: 'Source of the words "freebooter" and "skipper"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'BONES', number: 31, clue: 'Femora, e.g.'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'BURTS', number: 31, clue: '___ Bees'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ALI', number: 32, clue: 'Lindsay Lohan\'s sister'))
clues_mgwcc060_unscrambled.push(Entry.create(dir: 'Across', answer: '-', number: 33, clue: 'Enter (by)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'LIBER', number: 33, clue: 'It was free to citizens of Ancient Rome'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'IVORY', number: 34, clue: 'Like metaphorical towers'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'GATE', number: 35, clue: 'Way out, perhaps'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'SUMAC', number: 36, clue: 'Skunkbush ___ (plant found in the American West)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'SPUR', number: 36, clue: 'Push (into action)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'MDIV', number: 37, clue: 'Year Michelangelo finished "David"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'MAUNAKEA', number: 37, clue: 'Lake Waiau is on it'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'EMO', number: 38, clue: 'Given to brooding'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'OPRAH', number: 39, clue: 'Gayle King\'s best friend'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'ONEOFUS', number: 39, clue: 'Not with the enemy'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'TAEBO', number: 40, clue: 'Sport formed from the name of two other sports'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'TRUMANS', number: 40, clue: 'Former tenants at the Obamas\''))
clues_mgwcc060_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'GONUTS', number: 41, clue: 'Fail to keep one\'s cool'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'OWW', number: 42, clue: '"I\'m in a great deal of pain"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'PRUNER', number: 43, clue: 'Sharp purchase at Lowe\'s'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'POOF', number: 43, clue: 'Vanishing sound'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'SKEWERS', number: 44, clue: 'Kebab shop supply'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'SWANK', number: 44, clue: 'Oscar winner whose surname is also the name of a pornographic magazine'))
clues_mgwcc060_unscrambled.push(Entry.create(dir: 'Across', answer: '-', number: 45, clue: 'Submitting'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'KEANU', number: 45, clue: '54-down, in reality -- but what is reality?'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'FOUNDRY', number: 46, clue: 'Metals business'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'FROTH', number: 46, clue: 'Cafe mocha feature'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'WETWO', number: 47, clue: 'You and me and no one else'))
clues_mgwcc060_unscrambled.push(Entry.create(dir: 'Down', answer: '-', number: 47, clue: 'Large island'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'AROMA', number: 48, clue: 'Redolence'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ARES', number: 48, clue: 'New NASA rocket'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AAH', number: 49, clue: '"Keep doing that"'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'FOUROFAKIND', number: 50, clue: 'Straight crusher'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'OPT', number: 51, clue: 'Go (for)'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'USA', number: 52, clue: 'TV network created by Barry Diller'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'IVY', number: 53, clue: 'Invasive climber'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'NEO', number: 54, clue: '45-down, in fantasy -- or is it reality?'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'DRK', number: 55, clue: '1985 Cy Young winner, for short'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'NNE', number: 56, clue: 'Upright, so to speak: abbr.'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'UPSET', number: 57, clue: 'Knock off shockingly'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'NEVER', number: 58, clue: 'One less than once'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'KUR', number: 59, clue: 'Longtime NBC News correspondent'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'STASH', number: 60, clue: 'Put away'))
clues_mgwcc060_unscrambled.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SAYOK', number: 61, clue: 'Give permission (to)'))
instructions = 'This week\'s contest answer is of no specific length.'
explanation = '<MA>The name of any large island</MA><TEXT>As hinted by 17-Across and 11-Down, four clues lack corresponding entries in the grid. These FOUR OF A KIND are 33-A, 45-A, 28-D, and 47-D, which, when PUT TOGETHER, read "Enter by submitting any large island."</TEXT>'
Puzzle.create(title: 'MGWCC #60 - Can\'t Get There From Here', grid: 'GABOR.TARPS.HAH|EBOLA.ASYET.ILE|LEADNOWHERE.TIC|...SWINE..NEATH|HAPPILY.JANEDOE|EQUITY.NOVICE..|DUTCH.BONES.ALI|GATE.SUMAC.MDIV|EMO.OPRAH.TAEBO|..GONUTS.PRUNER|SKEWERS.FOUNDRY|WETWO..AROMA...|AAH.FOUROFAKIND|NNE.UPSET.NEVER|KUR.STASH.SAYOK', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/7/24', entries: clues_mgwcc060_unscrambled, instructions: instructions, explanation: explanation)
