clues_mgwcc062_unscrambled = Array.new
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'OWL', number: 1, clue: 'Bright bird'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ORB', number: 1, clue: 'Heavenly body'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'WOO', number: 2, clue: 'Pitch ___ (court)'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LOO', number: 3, clue: 'Bath bathroom'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'INCHUP', number: 4, clue: 'Make slow, steady progress (on)'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'IMELDA', number: 4, clue: '2005 Best Actress nominee ___ Staunton'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'NADA', number: 5, clue: 'Less than "un poco"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'CLIMB', number: 6, clue: 'Go up the wall'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HOTEL', number: 7, clue: 'Monopoly investment'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'UNO', number: 8, clue: 'Card game with a colorful deck'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'PER', number: 9, clue: 'For every one'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ATMS', number: 10, clue: 'Cash spewers'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ADLIBS', number: 10, clue: 'Doesn\'t use a script'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TRINES', number: 11, clue: 'Groups of three'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'MORALE', number: 12, clue: '"The firings will continue until ___ improves"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SPRITZ', number: 13, clue: 'Hair spray'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ROO', number: 14, clue: 'Perth puncher, for short'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'MALONE', number: 15, clue: 'NBA "Mailman" Karl ___'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'DROP', number: 16, clue: 'Get rid of'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BOOKEDITOR', number: 17, clue: 'New York literati member Judith Regan, notably'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'KAISER', number: 18, clue: 'Round roll'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'LIRR', number: 19, clue: 'N.Y. transportation network'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'ALAME', number: 20, clue: '"That\'s ___ excuse"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'SINAI', number: 21, clue: 'African peninsula'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'SKITO', number: 21, clue: 'Arrive at by schussing'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ACRID', number: 22, clue: 'Bitter'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'ABBA', number: 22, clue: 'Singing Scandinavians'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'COLM', number: 23, clue: 'Actor Meaney of "Star Trek: TNG"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'ROUE', number: 24, clue: 'Hedonist'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'BLACKBELT', number: 25, clue: '"Walker, Texas Ranger" star Chuck Norris, notably'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ALICE', number: 26, clue: 'She talked to a caterpillar'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'CASHEW', number: 27, clue: 'Crescent-shaped nut'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'BOOSAT', number: 28, clue: 'Certainly doesn\'t applaud, as a comedian'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'TACTIC', number: 29, clue: 'Pin, fork or skewer, in chess'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'LAISSEZ', number: 30, clue: '___-faire'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BLUE', number: 31, clue: 'Saddened'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'ASSIST', number: 32, clue: 'Helping hand'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SATCH', number: 33, clue: 'Louis Armstrong nickname'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'SNL', number: 34, clue: 'Eddie Murphy\'s old show, for short'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AMERICANCHOPPER', number: 35, clue: 'TV show whose name categorizes each of the people in this puzzle\'s four theme clues'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'IAMBS', number: 36, clue: 'Feet for Pound'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Down', answer: 'PARROT', number: 37, clue: 'Pirate\'s bird'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'PURE', number: 38, clue: 'Undiluted'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'EDEN', number: 39, clue: 'Heaven on earth'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'RIND', number: 40, clue: 'Part of a watermelon'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'ATTLEE', number: 41, clue: 'Prime minister after (and before) Churchill'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'AUDI', number: 42, clue: 'A5 automaker'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'OPENMIC', number: 43, clue: 'Night for amateurs to sing'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'OCTOPI', number: 43, clue: 'Creatures that can "high eight"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'PEAPOD', number: 44, clue: 'Vegetable container'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'ELPASO', number: 45, clue: 'City that\'s also a brand of Mexican food'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'NEALES', number: 46, clue: '1960 Wimbledon champ Fraser et al.'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'WARREN', number: 47, clue: 'Big bailout beneficiary Buffett'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ATHENS', number: 48, clue: '1896 Olympics host city'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'CELEBCHEF', number: 49, clue: 'The Food Network\'s Rachael Ray, notably'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ENTRY', number: 50, clue: 'Contest attempt'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'FACES', number: 51, clue: 'Turns toward'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'TREND', number: 52, clue: 'The way things are going'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TAPAS', number: 53, clue: 'Spanish bar food'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'NACHO', number: 54, clue: '"___ Libre"'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'CHET', number: 55, clue: 'Jazzman Baker'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OPAL', number: 56, clue: 'Australia\'s national gemstone'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'HATCHETMAN', number: 57, clue: 'Watergate Era attack dog Chuck Colson, notably'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'HST', number: 57, clue: 'Atomic bomb dropper, for short'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ACR', number: 58, clue: 'Unlike this answer: abbr.'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'MAR', number: 59, clue: 'Ruin'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'ALE', number: 60, clue: 'Samuel Adams Boston ___'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'NIX', number: 61, clue: '86'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'POSE', number: 62, clue: 'Mug for the camera'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'SCREEN', number: 63, clue: 'Door material'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ALI', number: 64, clue: 'Boxer Laila ___'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'IDOS', number: 65, clue: 'Wedding exchange'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TRYSTS', number: 66, clue: 'Midnight meetings, maybe'))
clues_mgwcc062_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'REX', number: 67, clue: 'Puzzle personality ___ Parker'))
instructions = 'Brendan Quigley and Matt decided to each try to construct a themed puzzle around an entry provided by a third party, in this case Rex Parker. This week\'s contest answer is the theme entry Rex Parker gave Brendan and Matt.'
explanation = '<MA>HATCHET MAN</MA><TEXT>The answer is the only theme entry that appears in both Brendan\'s and Matt\'s puzzle.<br/>See Brendan\'s puzzle <a target="_blank" href="http://www.brendanemmettquigley.com/2009/08/puzzle-105.html">here</a>.</TEXT>'
Puzzle.create(title: '#62 - "Give It a Whack"', grid: 'OWL.INCHUP.ATMS|ROO.MALONE.DROP|BOOKEDITOR.LIRR|...ALAME..SINAI|ACRID.BLACKBELT|BOOSAT..LAISSEZ|BLUE.ASSIST....|AMERICANCHOPPER|....ATTLEE.AUDI|OPENMIC..WARREN|CELEBCHEF.TREND|TAPAS..NACHO...|OPAL.HATCHETMAN|POSE.SCREEN.ALI|IDOS.TRYSTS.REX', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/8/21', entries: clues_mgwcc062_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')