clues_mgwcc064_unscrambled = Array.new
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AHS', number: 1, clue: '"Eureka!" alternatives'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'AHMED', number: 1, clue: '1999 Chemistry Nobelist ___ Zewail'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HAITI', number: 2, clue: 'Its motto is "L\'Union Fait La Force"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'STANS', number: 3, clue: 'The ___ (much of central Asia, casually)'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'BRIDAL', number: 4, clue: 'Shower or party preceder'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'BMI', number: 4, clue: 'Meas. of obesity'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ROSE', number: 5, clue: 'Title word for Stephen King or Woody Allen'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IRAS', number: 6, clue: 'Complex shelters'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'DOLTS', number: 7, clue: 'Fools'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ASSET', number: 8, clue: 'Good thing'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'LEASE', number: 9, clue: 'Forgo buying'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'SHUT', number: 10, clue: 'Slam, say'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SPIEDON', number: 10, clue: 'Followed'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'HENRYVIII', number: 11, clue: 'He twice committed uxoricide'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'UNIV', number: 12, clue: 'Part of UTEP'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TATE', number: 13, clue: '___ St. Ives (English museum)'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HAT', number: 14, clue: 'Role, in metaphor'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'MOROSE', number: 15, clue: 'Word whose sixth, first and second letters form a synonymous word'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'PENA', number: 16, clue: 'Five-time baseball All-Star of the 1980\'s Tony'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MIAMISALSA', number: 17, clue: 'Hot music in Florida?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'MACAU', number: 18, clue: 'World\'s busiest gambling mecca, overtaking Las Vegas as of 2006'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'INIT', number: 19, clue: 'Contending'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ETNA', number: 20, clue: 'Geographic feature mentioned by Vergil'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'ESTESVERVE', number: 21, clue: 'The panache of a top crossword constructor?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'VAN', number: 22, clue: 'Loek ___ Wely (noted Dutch chessplayer)'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DISCO', number: 23, clue: '___ ball'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'OWNS', number: 24, clue: 'Controls'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'STEADY', number: 25, clue: '"Watch yourself"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'AWOL', number: 26, clue: 'Desert, with "go"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'OTIS', number: 27, clue: 'Mayberry lush'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'LOME', number: 28, clue: 'African capital'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'NOVAK', number: 29, clue: '"Vertigo" actress, 1958'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ALPO', number: 30, clue: 'Purina label word'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'KEAN', number: 31, clue: '9/11 Commission co-chair Thomas ___'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'UNFUNTONTO', number: 32, clue: 'TV character who\'s a wet blanket?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'URIS', number: 32, clue: 'Baltimore-born novelist'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'NOHO', number: 33, clue: 'NYC section'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'FOOLSGOLD', number: 34, clue: 'Iron pyrite, humorously'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'NIN', number: 35, clue: 'Palindromic diarist'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'TASE', number: 36, clue: 'Zap, sometimes fatally'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'ONEL', number: 37, clue: 'Its second chapter is "Learning to Love the Law"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'NILE', number: 38, clue: 'Ethiopia\'s Blue ___ Falls'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ROO', number: 39, clue: 'Jumping boxer, for short'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'SIMIANS', number: 40, clue: 'Marmosets and such'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'SOLD', number: 41, clue: 'Didn\'t hold'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'IPA', number: 42, clue: 'Copper drink'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'IHOP', number: 43, clue: 'Their slogan is "Come Hungry. Leave Happy."'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'POWELLS', number: 44, clue: 'Famous bookstore in Portland, Ore.'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'SENSEONION', number: 45, clue: 'Start to tear up?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'NEATO', number: 46, clue: 'So cool'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'SOLON', number: 47, clue: 'Great Greek'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'NED', number: 48, clue: 'Rod and Todd\'s dad'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'ELLE', number: 49, clue: 'Hachette Filipacchi title'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'SWEETS', number: 50, clue: 'Candy, e.g.'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'ETHAN', number: 51, clue: 'Allen of furniture'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'THESE', number: 52, clue: 'Guess Who hit "___ Eyes"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'SOCHI', number: 53, clue: '2014 Olympics host city'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'DANES', number: 54, clue: 'Smorrebrod eaters'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'NOLTE', number: 55, clue: 'Best Actor nominee of 1991 and 1997'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ELVIS', number: 56, clue: '1960 R&B album "___ Is Back!"'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SLOPE', number: 57, clue: 'Grade'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'EDGEDTHOTH', number: 58, clue: 'Managed to defeat an Egyptian god?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'EGGO', number: 58, clue: 'Blueberry pancakes brand'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'DEAL', number: 59, clue: 'Situation'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'THOM', number: 60, clue: 'Yorke of Radiohead'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'HERA', number: 61, clue: 'She married her brother'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'TOLL', number: 62, clue: 'Charge down the highway'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'GEOL', number: 63, clue: 'Earth sci.'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'HECHEVOLVO', number: 64, clue: 'Car dealership owned by a Hollywood actress?'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'VEN', number: 65, clue: '"Come," in Colombia'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'GALL', number: 66, clue: 'Stones'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ASHORE', number: 67, clue: 'In ports of call, e.g.'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'TIP', number: 68, clue: 'What\'s left on the table after a meal'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'OLDS', number: 69, clue: 'Brand until 2004'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'NEIMAN', number: 70, clue: '"Borg/Connors" artist, 1977'))
clues_mgwcc064_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'ESE', number: 71, clue: 'Crossword finish'))
instructions = 'This week\'s contest answer phrase consists of the surname of a famous author AND the surname of one of his characters. Taken together, they would\'ve made an excellent theme entry this week.'
explanation = '<MA>KAFKA SAMSA</MA><TEXT>Each theme answer consists of a pair of words, each of which has the letter pattern 1-2-3-1-2. Both KAFKA and SAMSA (as in Gregor Samsa, from The Metamorphosis) also have this pattern.</TEXT>'
Puzzle.create(title: '#64 - "Almost A Murmur"', grid: 'AHS.BRIDAL.SHUT|HAT.MOROSE.PENA|MIAMISALSA.INIT|ETNA.ESTESVERVE|DISCO..STEADY..|...AWOL...NOVAK|UNFUNTONTO.NILE|ROO.SIMIANS.IPA|IHOP.SENSEONION|SOLON...ELLE...|..SWEETS..DANES|EDGEDTHOTH.TOLL|GEOL.HECHEVOLVO|GALL.ASHORE.TIP|OLDS.NEIMAN.ESE', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/9/4', entries: clues_mgwcc064_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')