clues_mgwcc069_unscrambled = Array.new
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'STATELINES', number: 1, clue: 'Laws change over them'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SMELLS', number: 1, clue: 'Carnival stimuli'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'TAXIED', number: 2, clue: 'Prepared to fly'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ALEUTIANISLANDS', number: 3, clue: 'Arc near the Arctic'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TIC', number: 4, clue: 'Involuntary action'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'EAU', number: 5, clue: 'Evian ou Perrier'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'LOT', number: 6, clue: 'Destiny'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'IBIDEM', number: 7, clue: 'Latin for "in the same place"'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NAVALAIRSTATION', number: 8, clue: 'Key West or Corpus Christi military installation'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EMERALDS', number: 9, clue: 'Verdant valuables'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SABINES', number: 10, clue: 'Tribe of ancient Italy'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MMII', number: 11, clue: 'It was seven years ago'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MEASUREUP', number: 11, clue: 'Compare'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'MINIATUREBEAGLE', number: 12, clue: 'Pocket pooch'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'INC', number: 13, clue: 'Papa John\'s International, ___'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ISH', number: 14, clue: 'Suffix with six'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MALIAOBAMA', number: 15, clue: 'Sasha\'s sister'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'EINS', number: 16, clue: 'One of the Austrians'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'EXECUTIVEBRANCH', number: 17, clue: 'All the president\'s men (and women)'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'RUG', number: 18, clue: 'Poor headwear'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'LIU', number: 19, clue: '"Lucky Number Slevin" actress, 2006'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'DARIUSI', number: 20, clue: '"Great" Persian'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'LET', number: 21, clue: 'Request for better service?'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Across', answer: 'UTELANGUAGE', number: 22, clue: 'It\'s endangered in the American West'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'UTEP', number: 22, clue: 'Lone Star State inst.'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'TAN', number: 23, clue: 'Get dark'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 14, dir: 'Down', answer: 'GERE', number: 24, clue: 'Former husband of Crawford'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Down', answer: 'ESO', number: 25, clue: '"___ es asi" ("That\'s how it is," in Spanish)'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'SDI', number: 26, clue: '"Star Wars" initials'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 6, col: 5, dir: 'Across', answer: 'TAMALE', number: 27, clue: 'Corn husk-wrapped food'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'RTES', number: 28, clue: 'Well-traveled paths: abbr.'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Across', answer: 'ADEN', number: 29, clue: 'British Crown colony, 1937-63'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'DONALDSON', number: 30, clue: 'Newsman with an obvious 18-down'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'IDS', number: 31, clue: 'Pegs'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'EURO', number: 32, clue: 'Prefix with zone'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'MNOP', number: 33, clue: 'Pre-Q quartet'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'MARU', number: 33, clue: 'Word in some ship names'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'HRS', number: 34, clue: 'Work units: abbr.'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'HIAWATHA', number: 34, clue: 'Mohawk hero'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'LURE', number: 35, clue: 'Tempt'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'LOSS', number: 35, clue: 'Experience preceding grief'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'CAIN', number: 36, clue: 'Murderous farmer'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'CUP', number: 36, clue: 'World Chess ___ (November 2009 tournament in Russia)'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'TIS', number: 37, clue: '"Agreed," poshly'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'TWOLAPS', number: 37, clue: 'Four lengths'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Across', answer: 'MOPE', number: 38, clue: 'Act sullen'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'MRD', number: 38, clue: 'Philip Drummond, to Arnold and Willis Jackson'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'URSA', number: 39, clue: 'Bear to look at, partially'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'WATERS', number: 40, clue: '"Multiple Maniacs" and "Hairspray" director John'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'ERECTS', number: 41, clue: 'Throws up'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'BAJ', number: 42, clue: 'Italian pop artist Enrico ___'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'ANNULI', number: 43, clue: 'Rings, in botany and mathematics'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'JAMESL', number: 44, clue: '"As Good As It Gets" director ___ Brooks'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'PULLTOWARDS', number: 45, clue: 'Draw'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'TUE', number: 46, clue: 'Calendar abbr.'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Across', answer: 'ENA', number: 47, clue: 'Doe aunt'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Across', answer: 'ADULATE', number: 48, clue: 'Give props to'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ANM', number: 49, clue: '"Gimme ___!" (cheer start in Ann Arbor, maybe)'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HANSEATICLEAGUE', number: 50, clue: 'Maritime monopoly'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'HUB', number: 50, clue: 'Locus for connecting flights'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 2, dir: 'Down', answer: 'APO', number: 51, clue: 'Military address part'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'LOS', number: 52, clue: 'Gabriel Garcia Marquez classic "El amor en ___ tiempos del colera"'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'ECO', number: 53, clue: '"The thinking man\'s Dan Brown"'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'AAL', number: 54, clue: 'Slippery fish, in Stuttgart'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'UPDO', number: 55, clue: 'Forehead revealer'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'PHOTOCALLS', number: 56, clue: 'Picture taking events, for British celebs'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'BOSN', number: 57, clue: 'Ship officer'))
clues_mgwcc069_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SANSSOLEIL', number: 58, clue: 'Influential 1983 French film whose English title is "Sunless"'))
instructions = 'Matt says he has "always disliked the phrase \'themeless crossword,\' since it\'s negative, stressing what\'s not there (a theme) over what is there (generally livelier vocabulary than themed puzzles)." This week\'s contest will be to come up with a better term for "themeless crossword."'
explanation = '<MA>N/A</MA><TEXT>Of all the proposed names, Matt preferred "Freestyle Crossword" as a replacement for "themeless."</TEXT>'
Puzzle.create(title: '#69 - "Not Themeless"', grid: 'STATELINES.MMII|MALIAOBAMA.EINS|EXECUTIVEBRANCH|LIU...DARIUSI..|LET.UTELANGUAGE|SDI.TAMALE.RTES|..ADEN.IDS.EURO|.MNOP.HRS.LURE.|CAIN.TIS.MOPE..|URSA.WATERS.BAJ|PULLTOWARDS.ENA|..ADULATE...ANM|HANSEATICLEAGUE|UPDO.PHOTOCALLS|BOSN.SANSSOLEIL', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/10/9', entries: clues_mgwcc069_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')
