clues_mgwcc071_unscrambled = Array.new
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'ASP', number: 1, clue: 'Coiled creature'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ABIE', number: 1, clue: 'Broadway title role of the 1920s'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'SYLVESTER', number: 2, clue: 'He shouted "Yo Adrian, I did it!" to Talia*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'POLANEGRI', number: 3, clue: 'Actress born Apolonia Chalupiec'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'TWA', number: 4, clue: 'It had a hub at JFK'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'TAKEI', number: 4, clue: 'Mr. Sulu'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WNW', number: 5, clue: 'Least common of the eight compass pts., in crosswords'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ANATHEMA', number: 6, clue: 'Reviled entity'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Across', answer: 'FURBISH', number: 7, clue: 'Make like new'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'FUZE', number: 7, clue: 'Drink brand in colorful bottles'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'UNAS', number: 8, clue: 'Healy and Merkel'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'RCA', number: 9, clue: 'Maker of the L32HD31R television'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'BECKONER', number: 10, clue: 'Person summoning you'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ISAID', number: 11, clue: 'Clarifying phrase'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'STRAD', number: 12, clue: 'Sweet strings'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HODS', number: 13, clue: 'Brick carriers'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'BYO', number: 14, clue: 'Letters indicating "none provided"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'ANNOUNCESTO', number: 15, clue: 'Informs'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Down', answer: 'ONO', number: 16, clue: 'Palindromic artist'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ILL', number: 17, clue: 'Feeling bad'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Across', answer: 'KWANZAACARD', number: 18, clue: 'December purchase at a Hallmark store'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'EVADE', number: 19, clue: 'Get around'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Down', answer: 'DRS', number: 20, clue: 'They\'ve been given the third degree: abbr.'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'TOES', number: 21, clue: 'Feet ten'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'KIAS', number: 22, clue: 'Korean cars'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Across', answer: 'ENRICH', number: 23, clue: 'Make money for'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'CRANIO', number: 24, clue: 'Of the skull: pref.'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'TODD', number: 25, clue: 'Mr. Sarah Palin'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'THOUS', number: 25, clue: 'Grands'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'USES', number: 26, clue: 'Makes a tool out of'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'UMP', number: 26, clue: '"Out!" shouter'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'REF', number: 27, clue: 'Flag-bearer, of a sort'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'FELIX', number: 28, clue: 'Neat roommate*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'AHN', number: 29, clue: 'Philip of "Kung Fu"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ALONZO', number: 29, clue: '___ Mourning (longtime Miami Heat center)*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'MTG', number: 30, clue: 'Powwow: abbr.'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'SAME', number: 31, clue: '"I agree"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'SOCKS', number: 31, clue: 'Hits hard*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'LOESS', number: 32, clue: 'Superb soil'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'SNEEREDAT', number: 33, clue: 'Showed contempt for'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'SEGREGATE', number: 34, clue: 'Keep apart'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'PERSONALJOURNEY', number: 35, clue: 'One\'s own odyssey through life*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'SCRATCHY', number: 36, clue: 'Uncomfortable, as some blankets*'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'JOYSTICK', number: 37, clue: 'Pac-Man controller'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'YON', number: 38, clue: 'Hardly hither'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'RICCI', number: 39, clue: 'Christina of "Speed Racer"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'IONS', number: 40, clue: 'They can be radical'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'EGO', number: 41, clue: 'Self-importance'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'RKO', number: 42, clue: '"King Kong" studio'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'XYZ', number: 43, clue: '"The barn door is open"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'BERN', number: 44, clue: 'Switzerland\'s capital'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'BUM', number: 44, clue: 'Request, as a cigarette'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'CPAS', number: 45, clue: 'Return signers, often: abbr.'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'CONAN', number: 45, clue: 'Arnold, once'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'PLACE', number: 46, clue: 'Locality'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'SOSURE', number: 47, clue: '"I\'m ___!" ("As if!")'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'SOYUZ', number: 48, clue: '1975\'s Apollo-___ mission'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'MOLT', number: 49, clue: 'Shed one\'s shell'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'MIMO', number: 49, clue: 'Wireless acronym'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'PHAT', number: 50, clue: 'Baby ___ (clothing line)'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'PUPA', number: 50, clue: 'Insect\'s stage'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'HAIR', number: 51, clue: 'Bangs and beards'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ALC', number: 52, clue: 'Abbr. on beer bottles'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'OMEGA', number: 53, clue: '"Great O"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'AMEX', number: 54, clue: 'MC alternative'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'INACTUALITY', number: 55, clue: '"Truth be told..."'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'TUE', number: 56, clue: 'After MON'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'THO', number: 57, clue: 'Despite, when texting'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Across', answer: 'DAM', number: 58, clue: 'If it\'s broken, you\'re soakin\''))
clues_mgwcc071_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MACHUPICCHU', number: 59, clue: 'Quechua for "old peak"'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ATE', number: 60, clue: 'Chomped on'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ONEYEAR', number: 61, clue: 'Like many leases'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 15, col: 9, dir: 'Across', answer: 'KOZ', number: 62, clue: 'Dave on saxophone'))
clues_mgwcc071_unscrambled.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'TEX', number: 63, clue: 'S.E. Hinton classic'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: 'MGWCC #71 - "Walk in Fear"', grid: 'ASP.TWA.FURBISH|BYO.ANNOUNCESTO|ILL.KWANZAACARD|EVADE.TOES.KIAS|.ENRICH...TODD.|USES.REF.AHN...|MTG.SAME.LOESS.|PERSONALJOURNEY|.RICCI.IONS.EGO|...RKO.XYZ.BERN|.CPAS...SOSURE.|MOLT.PHAT.OMEGA|INACTUALITY.DAM|MACHUPICCHU.ATE|ONEYEAR.KOZ.TEX', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/10/23', entries: clues_mgwcc071_unscrambled, instructions: instructions, explanation: explanation)
