clues_mgwcc073_unscrambled = Array.new
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MAZDAS', number: 1, clue: 'CX-7 and CX-9'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MAUMAU', number: 1, clue: 'Cow'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARBORS', number: 2, clue: 'Shady areas'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ZOUNDS', number: 3, clue: '"Great Merlin\'s beard!"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'DINGERS', number: 4, clue: 'They\'re outta here'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ANTON', number: 5, clue: 'Corbijn or Bruckner'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'STU', number: 6, clue: 'RV hookup'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'ACCESSED', number: 7, clue: 'Got into'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ACE', number: 7, clue: 'Powerful club'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'COLDER', number: 8, clue: 'Fall comparative'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'CLARA', number: 9, clue: 'Bow in front of the cameras'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ELSE', number: 10, clue: 'Beyond'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SET', number: 11, clue: 'Volleyball maneuver'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'STICKERS', number: 12, clue: 'Campaign paraphernalia'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ETCHINTO', number: 13, clue: 'Carve on permanently'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DESISTED', number: 14, clue: 'Cut it out'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AROINT', number: 15, clue: '"___ thee!"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'COLLETTE', number: 16, clue: '"About a Boy" actress, 2002'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'UBUNTU', number: 17, clue: 'Operating system with a South African name'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 3, col: 8, dir: 'Across', answer: 'ELASTICS', number: 18, clue: 'Rubber bands on braces'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'MONGO', number: 19, clue: 'Huge gingerbread man in "Shrek 2"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'DRE', number: 20, clue: 'Dr. without an advanced degree'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'CHI', number: 21, clue: 'Flow of life'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ARDENT', number: 22, clue: 'Unyielding'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'TALIA', number: 23, clue: 'Ex-wife of film scorer David Shire'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'WEA', number: 24, clue: '"Are ___ little cranky?"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'WAXBEAN', number: 24, clue: 'Food in a yellow pod'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'SKIS', number: 25, clue: 'Sporting pair'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'SHA', number: 25, clue: '___ Cha Beef (Chinese dish)'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'USSR', number: 26, clue: 'Birthplace of no one under the age of 17'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'ADAR', number: 27, clue: 'Sixth of twelve'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'DEX', number: 28, clue: 'TV psychopath, for short'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'GHENT', number: 29, clue: 'Museum voor Schone Kunsten\'s city'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'GUST', number: 29, clue: 'It really blows'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 7, col: 4, dir: 'Across', answer: 'SILEX', number: 30, clue: 'Hard rock'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'ISLA', number: 31, clue: 'Word on Puerto Rico\'s state quarter'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'DUARTE', number: 32, clue: 'Central American leader of the 1980s'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'DROSS', number: 32, clue: 'Impurity'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ASS', number: 33, clue: 'Trunk'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'ALITALIA', number: 33, clue: 'Company with (fittingly) a red, white and green logo'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Down', answer: 'SABATINI', number: 34, clue: '1990 U.S. Open winner'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 3, dir: 'Down', answer: 'SLIPOVER', number: 35, clue: 'Escape past, as a wall'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'SIXBARS', number: 36, clue: 'Average itinerary for a Halloween night pub crawl, maybe'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'AMU', number: 37, clue: '___ Darya (Asian river)'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SOD', number: 38, clue: '___ cutter (gardening tool)'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'LALALA', number: 39, clue: 'Meaningless triad'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'AZE', number: 40, clue: 'Olympic abbreviation of an Asian nation'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EMOTE', number: 41, clue: 'Overdo it'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'EAGERLY', number: 42, clue: 'Without cajoling'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'IBIZA', number: 43, clue: 'Catalan is spoken there'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'MAUS', number: 44, clue: 'Autobiography subtitled "A Survivor\'s Tale"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'METROS', number: 44, clue: 'Takes the train, in D.C. slang'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'ASOF', number: 45, clue: 'From'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 13, dir: 'Down', answer: 'SURGED', number: 46, clue: 'Rose'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Down', answer: 'ORTEGA', number: 47, clue: 'Old El Paso rival'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 10, col: 15, dir: 'Down', answer: 'FOSSEY', number: 48, clue: 'Murder victim in Rwanda, 1985'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TAPE', number: 49, clue: 'Sticky stuff'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'PEN', number: 50, clue: 'Pig\'s place'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'PAINE', number: 50, clue: 'Speaker of the words "It is error only, and not truth, that shrinks from inquiry"'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'SEGURO', number: 51, clue: 'Positive in Peru'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'EBOLA', number: 52, clue: 'Painful strain'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ATO', number: 53, clue: '"From ___ Zinc" (multivitamin ad phrase)'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'TAT', number: 54, clue: 'Leg work, perhaps'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'TWIN', number: 54, clue: 'One may be evil'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'BERTS', number: 55, clue: 'Pitcher Blyleven and others'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'LIVEWIRE', number: 56, clue: 'Pistol'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'EMI', number: 57, clue: '___ Latin'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ERS', number: 58, clue: '-ites'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Across', answer: 'BORGES', number: 59, clue: 'He went blind in the mid-1950s'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'BAG', number: 59, clue: 'Cancel'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'INEMINOR', number: 60, clue: '"Bourree ___" (J.S. Bach piece)'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'ALLEGE', number: 61, clue: 'State'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'AIRINESS', number: 62, clue: 'Quality of atria'))
clues_mgwcc073_unscrambled.push(Entry.create(row: 15, col: 10, dir: 'Across', answer: 'GAYDAY', number: 63, clue: 'Fabulous annual event at many amusement parks'))
Puzzle.create(title: 'MGWCC #73 - "Outrageous Death"', grid: 'MAZDAS.ACCESSED|AROINT.COLLETTE|UBUNTU.ELASTICS|MONGO...DRE.CHI|ARDENT.WEA.SKIS|USSR.ADAR.GHENT|...SILEX.DUARTE|ASS.SIXBARS.SOD|LALALA.EMOTE...|IBIZA.MAUS.ASOF|TAPE.PEN.SEGURO|ATO.TAT...BERTS|LIVEWIRE.BORGES|INEMINOR.ALLEGE|AIRINESS.GAYDAY', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/11/6', entries: clues_mgwcc073_unscrambled)
