clues_mgwcc077_unscrambled = Array.new
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'GALT', number: 1, clue: '"Who is John ___?"'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'GAGA', number: 1, clue: 'Lady ___'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ACES', number: 2, clue: '"Rockets," in poker slang'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LARS', number: 3, clue: '"Breaking the Waves" director ___ von Trier'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TIMEOFF', number: 4, clue: 'It\'s not working'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'APPS', number: 5, clue: 'iPhone progs'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ALF', number: 5, clue: 'Franklin crushed him'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'PEA', number: 6, clue: 'Item under a mattress'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'PIN', number: 7, clue: 'Paragon of neatness'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SAYSO', number: 8, clue: 'Authorization'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'ASADA', number: 9, clue: 'Adjective on Tex-Mex menus'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ASOF', number: 9, clue: 'From'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SARAZEN', number: 10, clue: 'Golfer who hit "the shot heard \'round the world"'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AGAME', number: 11, clue: 'Peak performance'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'DELOS', number: 12, clue: 'One of the Cyclades'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ATBAT', number: 13, clue: 'Single chance'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ACAI', number: 14, clue: 'Faddish fruit'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'LEIA', number: 15, clue: 'Fisher part'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'SAGET', number: 16, clue: 'Former Stamos co-star'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'GERMOFANY', number: 17, clue: 'Whichever biothreat you happen to have handy?'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'OSU', number: 18, clue: 'Alma mater of U.S. Sens. George Voinovich and Sherrod Brown'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'ORALB', number: 19, clue: 'Procter & Gamble brand'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ASSES', number: 20, clue: 'Wild ___'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'SOFAMOA', number: 21, clue: 'Extinct bird whose habitat was the living room couch?'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ORDINALS', number: 22, clue: 'First, second, and fourth'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'OUI', number: 23, clue: 'Senegalese agreement'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'ICANTELL', number: 24, clue: '"Yeah, it shows"'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'FOR', number: 25, clue: 'Not anti'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'FAA', number: 25, clue: 'Just plane folks: abbr.'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'ZEST', number: 26, clue: 'Part of an orange'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'USAF', number: 27, clue: 'F-16 quartet'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'USC', number: 27, clue: 'Pac-10 team'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'STUB', number: 28, clue: 'Proof you paid'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'AUDI', number: 29, clue: 'Make Bavarians make'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'CIA', number: 30, clue: 'Org. that\'s the subject of Gary Webb\'s 1996 book "Dark Alliance"'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'INCH', number: 31, clue: 'Slightest concession, metaphorically'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'DRE', number: 32, clue: '"Forgot About ___" (Grammy-winning 2001 rap song featuring Eminem\'s vocals)'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'ROAM', number: 33, clue: 'Go around'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'STUFFANATIONAL', number: 34, clue: 'With 44-across, how to find the Thanksgiving food'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'FIDO', number: 35, clue: 'Dog name, in many cartoons'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'TASE', number: 36, clue: 'Electrocute on purpose'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'AIWA', number: 37, clue: 'Sony bought it'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'LEAF', number: 38, clue: 'Flip (through)'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'CUD', number: 39, clue: 'Re-chewed chow'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'INC', number: 40, clue: 'Business letters'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Across', answer: 'ANA', number: 41, clue: 'Wonkette founder ___ Marie Cox'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'IED', number: 42, clue: 'Baghdad danger'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'DYE', number: 43, clue: 'Turn red, maybe'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 9, col: 2, dir: 'Across', answer: 'BIRDTHESAMEWAY', number: 44, clue: 'See 34-across'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'REDFORD', number: 45, clue: '"Quiz Show" director'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 9, col: 8, dir: 'Down', answer: 'EGG', number: 46, clue: 'Chick of the future'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ECSTASY', number: 47, clue: '3,4-Methylenedioxymethamphetamine, casually'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'EOE', number: 48, clue: 'Want ad palindrome'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 10, col: 8, dir: 'Across', answer: 'GEL', number: 49, clue: 'Shaving ___'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Across', answer: 'CAFE', number: 50, clue: 'Business named for a drink'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'OWND', number: 51, clue: 'Dominated, in internet lingo'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'OCCUR', number: 51, clue: 'Take place'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'WHOLE', number: 52, clue: '___ milk'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'NOLTE', number: 53, clue: 'Two-time Murphy co-star'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'LEG', number: 54, clue: 'Section'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'EERIE', number: 55, clue: 'Chilling'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'SIS', number: 56, clue: 'Big ___'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'ISM', number: 57, clue: 'Way of looking at things'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CHOFILE', number: 58, clue: 'Dossier on comic Margaret?'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'IRAS', number: 59, clue: 'Glass and Hayes'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 11, dir: 'Across', answer: 'STUMP', number: 60, clue: 'Make political promises'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'UNUM', number: 61, clue: 'Word on Puerto Rico\'s state quarter'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'MISC', number: 62, clue: 'Random: abbr.'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'PASA', number: 63, clue: '"El Condor ___" (Simon & Garfunkel hit)'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'COLOR', number: 64, clue: 'Gold, silver or bronze'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'ROOFMANIA', number: 65, clue: 'Craze where everyone stands on top of their houses?'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'ODD', number: 66, clue: 'Not like the others'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'OLD', number: 67, clue: '___ Navy'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'FEY', number: 68, clue: 'Precious'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ULTRA', number: 69, clue: 'Highly'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'IDLE', number: 70, clue: 'Shiftless'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'SUSS', number: 71, clue: '___ out (discover)'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'REEDS', number: 72, clue: 'Strips in a jazz club'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'EDDY', number: 73, clue: 'Swirling danger'))
clues_mgwcc077_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'YMCA', number: 74, clue: 'Organization whose tax-free status has been challenged by health clubs'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#77 - "Middle of Somewhere"', grid: 'GALT.APPS.ASADA|ACAI.LEIA.SAGET|GERMOFANY.ORALB|ASSES...SOFAMOA|...OUI.FOR.ZEST|USAF.CIA.DRE...|STUFFANATIONAL.|CUD.INC.ANA.IED|.BIRDTHESAMEWAY|...EOE.GEL.CAFE|OWND.LEG.SIS...|CHOFILE...STUMP|COLOR.ROOFMANIA|ULTRA.IDLE.SUSS|REEDS.EDDY.YMCA', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/12/4', entries: clues_mgwcc077_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')