clues_mgwcc078_unscrambled = Array.new
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MARV', number: 1, clue: 'First name in sportscasting'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MMM', number: 1, clue: '"So good"'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'AAA', number: 2, clue: 'Kind of baseball'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RLS', number: 3, clue: '"Kidnapped" inits'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'VISAING', number: 4, clue: 'Allowing to travel'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'OTTER', number: 5, clue: 'Fish-eating mammal'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ORCHID', number: 5, clue: 'Organism studied in detail by Darwin'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'THREE', number: 6, clue: 'In pre-K, perhaps'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TOI', number: 7, clue: 'You may be this to a Canadian'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EDNA', number: 8, clue: 'Bart torments her'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RAGS', number: 9, clue: 'Poverty, in metaphor'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MMIX', number: 10, clue: 'It ends in about a month'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MELISSA', number: 10, clue: 'Manchester or Gilbert'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'MAINTENANCE', number: 11, clue: 'Word on a janitor\'s door*'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ISNT', number: 12, clue: '"That ___ funny"'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'XENO', number: 13, clue: 'Strange start'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MALI', number: 14, clue: 'Ancient Africa\'s ___ Empire'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'RHODA', number: 15, clue: 'She moved from Minneapolis to New York City'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'EASE', number: 16, clue: 'Relax'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MASSACRING', number: 17, clue: 'Doing a lot of damage to*'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'ACTION', number: 18, clue: 'Set shout'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'LINN', number: 19, clue: 'Actor Mark ___-Baker'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'ACHE', number: 20, clue: 'Signal from one\'s body'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'ASKINTO', number: 21, clue: 'Offer (someone) entry'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'KIN', number: 22, clue: 'Those related'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'USCITIES', number: 23, clue: 'Washington, Lincoln and Jackson'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'ULLAGE', number: 23, clue: 'Unfilled part of a wine container'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'SEINED', number: 24, clue: 'Swept the sea clean'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'CONNOISSEUR', number: 25, clue: 'Expert*'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'SOPHIST', number: 26, clue: 'Maker of false but clever arguments'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'IST', number: 27, clue: '-ite'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'LEONID', number: 28, clue: '___ meteor shower (recent phenomenon)'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Across', answer: 'OPENSEAT', number: 29, clue: 'Congressional retirement result'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'PAAR', number: 30, clue: 'Jack up at night, once'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'ERR', number: 31, clue: 'Go astray'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'AENEAS', number: 32, clue: 'Venus was his mom'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'TWERPS', number: 33, clue: 'Punks'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'LINGO', number: 34, clue: 'Speech'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'SPAR', number: 35, clue: 'Throw a few hooks out there'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'SWAN', number: 35, clue: 'Black ___ (unforeseen, paradigm-shifting event)'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ANEW', number: 36, clue: 'Once more'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ANN', number: 37, clue: 'Word in a Michigan city\'s name'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'NEWHART', number: 38, clue: 'Show set in the Northeast*'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ELO', number: 39, clue: '"Strange Magic" singers'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'TACTIC', number: 40, clue: 'Deflection or underpromotion, in chess'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'ANE', number: 41, clue: 'Meth addition'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'GEOS', number: 42, clue: 'Metros, e.g.'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'STARTIT', number: 43, clue: 'Throw the first punch'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'LAIR', number: 44, clue: 'Pawed pad'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'AVNER', number: 45, clue: 'Lead role in the 2005 Spielberg movie "Munich"'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'VELVETY', number: 46, clue: 'Soft'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'EDITIONS', number: 47, clue: 'Incarnations'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'IDO', number: 48, clue: 'Pre-kiss statement'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'ICECAP', number: 49, clue: 'Big white sheet'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'ICHING', number: 49, clue: 'Book featuring hexagrams'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'SAD', number: 50, clue: 'Sorry'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Across', answer: 'TACTLESS', number: 51, clue: 'Blunt'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ASMAN', number: 52, clue: 'Fox Business anchor David ___'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'HASROOM', number: 53, clue: 'Doesn\'t need someone else to move'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'HAMM', number: 53, clue: 'Soccer surname'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ABAA', number: 54, clue: 'Rhyme scheme used in some Roethke quatrains'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'OVUM', number: 55, clue: '___ donation'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'MERC', number: 56, clue: 'Gun for hire, for short'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'SHIV', number: 57, clue: 'Get the blade in'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ABET', number: 58, clue: 'Take money with, e.g.'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'VERMICELLI', number: 59, clue: 'Literally, "little worms"*'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'RBI', number: 60, clue: 'Someone getting home safely'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'LOU', number: 61, clue: 'Reed on a musical instrument'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'LUC', number: 62, clue: 'Man\'s name from the Latin for "light"'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'IRK', number: 63, clue: 'Get to'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MAUI', number: 64, clue: '___ Gold (pineapple brand)'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'URBAN', number: 65, clue: 'Metropolitan'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'TOUR', number: 66, clue: 'Series of gigs'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MART', number: 67, clue: 'Store'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'MCING', number: 68, clue: 'Leading'))
clues_mgwcc078_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'YUCK', number: 69, clue: '"That\'s disgusting"'))
Puzzle.create(title: 'MGWCC #78 - "Regional Variation"', grid: 'MARV.OTTER.MMIX|MALI.RHODA.EASE|MASSACRING.LINN|...ACHE.ASKINTO|USCITIES..IST..|LEONID.OPENSEAT|LINGO.SPAR.ANEW|ANN.NEWHART.ANE|GEOS.LAIR.AVNER|EDITIONS.ICECAP|..SAD..TACTLESS|HASROOM.SHIV...|ABET.VERMICELLI|MAUI.URBAN.TOUR|MART.MCING.YUCK', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2009/12/11', entries: clues_mgwcc078_unscrambled)
