clues_mgwcc083_unscrambled = Array.new
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BELONG', number: 1, clue: 'Fit well'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BALK', number: 1, clue: 'Be hesitant'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELIA', number: 2, clue: 'He directed Marlon in "On the Waterfront"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'LAST', number: 3, clue: 'Final'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ORATOR', number: 4, clue: 'Verbal essayist'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NIL', number: 5, clue: 'Zero on the pitch'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'GEISHAS', number: 6, clue: 'Some women of Kyoto'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'AVS', number: 7, clue: 'Wide rds.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'AMEX', number: 7, clue: 'MC rival'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'VALISE', number: 8, clue: 'Suitcase'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'SAYSAH', number: 9, clue: 'Obeys the dentist'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'MILER', number: 10, clue: 'Track athlete'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'MBA', number: 10, clue: 'Wharton deg.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ISNT', number: 11, clue: '"___ that true?"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LIDO', number: 12, clue: 'Beach area'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'EDISON', number: 13, clue: 'Bright guy?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 16, dir: 'Down', answer: 'REFUND', number: 14, clue: 'Money back'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 18, dir: 'Across', answer: 'TICS', number: 15, clue: 'Forced movements'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 18, dir: 'Down', answer: 'TALC', number: 15, clue: 'Soft mineral'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 19, dir: 'Down', answer: 'IVIED', number: 16, clue: 'Like the walls at Harvard'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 20, dir: 'Down', answer: 'COVER', number: 17, clue: 'Song you didn\'t write'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 1, col: 21, dir: 'Down', answer: 'SWEDE', number: 18, clue: 'Uppsala resident'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALARIE', number: 19, clue: '1980s-90s NBA player Mark'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'MAA', number: 20, clue: 'Goat\'s sound'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'BSIDE', number: 21, clue: '45 half'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 2, col: 18, dir: 'Across', answer: 'AVOW', number: 22, clue: 'Claim'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LISALIKELY', number: 23, clue: 'With 30-across, what a smart "Simpsons" character is when she sits down with one of Merl\'s crosswords?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'KEOGH', number: 24, clue: 'Pension type'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ANDIF', number: 25, clue: '"But what happens when..."'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 3, col: 18, dir: 'Across', answer: 'LIVE', number: 26, clue: 'Like many albums'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'KATT', number: 27, clue: 'William of "The Greatest American Hero"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'SEXIST', number: 28, clue: 'Affording unequal treatment, sometimes'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'TRAPP', number: 29, clue: 'Von ___ family of "The Sound of Music"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 4, col: 13, dir: 'Across', answer: 'TOSUCCEED', number: 30, clue: 'See 23-across'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 4, col: 17, dir: 'Down', answer: 'COEDS', number: 31, clue: 'Dated term for women in college'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'OTHO', number: 32, clue: 'One of four emperors in 69 A.D.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'TEAL', number: 33, clue: 'Blue shade'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'SARI', number: 34, clue: 'Delhi dress'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 12, dir: 'Down', answer: 'ISLA', number: 35, clue: 'Menorca o Mallorca, e.g.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 15, dir: 'Across', answer: 'ONO', number: 36, clue: 'Palindromic Grammy winner'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 5, col: 19, dir: 'Across', answer: 'DRE', number: 37, clue: 'Non-palindromic Grammy winner'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'THEREAGLEHASLANDED', number: 38, clue: 'Airport P.A. announcement when Merl reaches his destination?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'TEAM', number: 38, clue: 'Squad'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'HATE', number: 39, clue: 'Be unable to stand'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'EROS', number: 40, clue: 'Lustful deity'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'LETU', number: 41, clue: 'Usher\'s "Can\'t ___ Go"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'LORD', number: 42, clue: 'Manor owner'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'APERCU', number: 43, clue: 'First glance'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 6, col: 18, dir: 'Down', answer: 'DATA', number: 44, clue: 'Just the facts'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'EAR', number: 45, clue: 'Good listener?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'ASHE', number: 46, clue: 'Arthur of the court'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'PLOP', number: 47, clue: 'Sit (oneself down) on, as the sofa'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 17, dir: 'Across', answer: 'DAVIS', number: 48, clue: 'Bette or Miles'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 19, dir: 'Down', answer: 'VALID', number: 49, clue: 'OK'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 20, dir: 'Down', answer: 'INTO', number: 50, clue: 'Digging'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 7, col: 21, dir: 'Down', answer: 'STAN', number: 51, clue: 'Ending of many Asian countries'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ATOLL', number: 52, clue: 'Ring in the Pacific'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'LAPP', number: 53, clue: 'Reindeer-herding Finn'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 8, dir: 'Across', answer: 'TAMPARESISTANT', number: 54, clue: 'Like people who don\'t want to move to Merl\'s hometown?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'ASTR', number: 55, clue: 'Sky study: abbr.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'MARYS', number: 56, clue: 'Cassatt and Shelley'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 15, dir: 'Down', answer: 'SALTER', number: 57, clue: 'Person who preserves food'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 8, col: 16, dir: 'Down', answer: 'ITALIA', number: 58, clue: '2006 World Cup winner, to them'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MESA', number: 59, clue: 'Arizona city'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'IOUSA', number: 60, clue: 'Documentary by the guy who directed "Wordplay"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'INAZOO', number: 60, clue: 'How many pandas are housed'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Down', answer: 'ONHULU', number: 61, clue: 'Where some watch internet TV'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'DRAT', number: 62, clue: '"Shucks!"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 9, col: 18, dir: 'Across', answer: 'ALTA', number: 63, clue: 'Rockies ski resort'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'PENN', number: 64, clue: '"Dead Man Walking" actor'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ERA', number: 65, clue: 'Past time'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'TRLS', number: 66, clue: 'Some MTV episodes'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'LIT', number: 67, clue: 'Wasted'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SNIDE', number: 68, clue: 'Impolite, as remarks'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 14, dir: 'Across', answer: 'CLAW', number: 69, clue: 'Crab\'s weapon'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 17, dir: 'Down', answer: 'WON', number: 70, clue: 'Came out on top'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 10, col: 19, dir: 'Across', answer: 'ION', number: 71, clue: 'Particular particle'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'OPRAHCRYINOUTLOUD', number: 72, clue: 'How Merl had a TV host, while cracking jokes on her show?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'OPELS', number: 72, clue: 'German cars'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'CRAMER', number: 73, clue: '"Mad Money" man Jim'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'OREM', number: 74, clue: 'Utah city'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 11, col: 18, dir: 'Down', answer: 'USSR', number: 75, clue: 'Country many world chess champs represented'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'LAP', number: 76, clue: 'Once around'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'LOWA', number: 76, clue: '90%, say'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AGIT', number: 77, clue: 'Word form with "prop"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 5, dir: 'Across', answer: 'AZUR', number: 78, clue: 'Bayou "blue"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'STIR', number: 79, clue: 'Mix'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Across', answer: 'EINS', number: 80, clue: 'One in Wiesbaden'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'OGEA', number: 81, clue: 'Pitcher Chad'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 4, dir: 'Down', answer: 'ALEC', number: 82, clue: 'Guinness or Baldwin'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'OLAF', number: 83, clue: 'Norwegian saint'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'FARM', number: 84, clue: 'It\'s full of crop'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'DEBRA', number: 85, clue: 'Winger in "Terms of Endearment"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'BEAT', number: 86, clue: 'Dominate'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 18, dir: 'Across', answer: 'SHOP', number: 87, clue: 'Hit the mall'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 19, dir: 'Down', answer: 'HIYA', number: 88, clue: '"How\'s it goin\'?"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 20, dir: 'Down', answer: 'OVER', number: 89, clue: '"Your turn to talk"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 13, col: 21, dir: 'Down', answer: 'PEND', number: 90, clue: 'Await'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'WILLYOUMARIEME', number: 91, clue: 'How Merl proposed to his wife?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 5, dir: 'Down', answer: 'YAHOO', number: 92, clue: 'Google rival'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 10, dir: 'Down', answer: 'RIAL', number: 93, clue: 'Iranian currency'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 11, dir: 'Down', answer: 'INNER', number: 94, clue: 'Close at hand'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 17, dir: 'Across', answer: 'DRIVE', number: 95, clue: 'Ambition'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 14, col: 17, dir: 'Down', answer: 'DEBT', number: 95, clue: 'Interest-ing topic?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ATSEA', number: 96, clue: 'Totally lost'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'ERIN', number: 97, clue: 'Julia played her'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 14, dir: 'Across', answer: 'ACRE', number: 98, clue: 'Land unit'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 15, dir: 'Down', answer: 'CHEAT', number: 99, clue: 'Swindle'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 16, dir: 'Down', answer: 'READYTO', number: 100, clue: 'Saying one will'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 15, col: 19, dir: 'Across', answer: 'YEN', number: 101, clue: 'Sushi money, maybe'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 4, dir: 'Across', answer: 'CHAIRMANOFTHEBEARD', number: 102, clue: 'Nickname for Merl\'s barber?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 6, dir: 'Down', answer: 'AWHILE', number: 103, clue: 'Some time'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 7, dir: 'Down', answer: 'INPAIN', number: 104, clue: 'Hurting'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 12, dir: 'Down', answer: 'ONESEC', number: 105, clue: '"Hold on!"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 13, dir: 'Down', answer: 'FARINA', number: 106, clue: 'Dennis formerly of "Law & Order"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 16, col: 18, dir: 'Down', answer: 'ESTEEM', number: 107, clue: 'Rate'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Across', answer: 'TEA', number: 108, clue: 'Green or black'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 1, dir: 'Down', answer: 'TWIST', number: 108, clue: 'Plot shocker'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 2, dir: 'Down', answer: 'EIDER', number: 109, clue: 'Down on the bed'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 3, dir: 'Down', answer: 'ADORE', number: 110, clue: 'Love so much'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 5, dir: 'Across', answer: 'OWN', number: 111, clue: 'Hold'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 10, dir: 'Across', answer: 'LENA', number: 112, clue: 'Yakutsk\'s river'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 17, col: 15, dir: 'Across', answer: 'EATS', number: 113, clue: 'Chow'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 1, dir: 'Across', answer: 'WIDEOHPUN', number: 114, clue: 'Like Merl\'s crossword grids?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 4, dir: 'Down', answer: 'ELBE', number: 115, clue: 'Hamburg\'s river'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 8, dir: 'Down', answer: 'UGGS', number: 116, clue: 'Fashionable boots'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 9, dir: 'Down', answer: 'NOHO', number: 117, clue: 'Section of Manhattan one letter off from another section of Manhattan'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 11, dir: 'Across', answer: 'REREAD', number: 118, clue: 'Look over again'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 14, dir: 'Down', answer: 'EXED', number: 119, clue: 'Crossed out'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 18, dir: 'Across', answer: 'TONI', number: 120, clue: 'Singer Braxton'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 19, dir: 'Down', answer: 'OAHE', number: 121, clue: 'Huge Dakotas lake one letter off from a Hawaiian island'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 20, dir: 'Down', answer: 'NSEC', number: 122, clue: 'Instant: abbr.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 18, col: 21, dir: 'Down', answer: 'ITES', number: 123, clue: 'Suffix with New Jersey or Jerusalem'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 19, col: 1, dir: 'Across', answer: 'IDOL', number: 124, clue: 'Adam Lambert\'s show'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 19, col: 6, dir: 'Across', answer: 'IAGOS', number: 125, clue: 'Shakespearean actors, at times'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 19, col: 10, dir: 'Down', answer: 'STR', number: 126, clue: 'Narrow waterway: abbr.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 19, col: 12, dir: 'Across', answer: 'SIXTYBEAST', number: 127, clue: 'Movie with Ben Kingsley as Merl, after his birthday this coming Tuesday?'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 19, col: 17, dir: 'Down', answer: 'BEL', number: 128, clue: '"The Fresh Prince of ___-Air"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 20, col: 1, dir: 'Across', answer: 'SERB', number: 129, clue: 'Balkans native'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 20, col: 6, dir: 'Across', answer: 'LIGHT', number: 130, clue: 'Easy on the calories'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 20, col: 12, dir: 'Across', answer: 'ENE', number: 131, clue: 'Compass dir.'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 20, col: 16, dir: 'Across', answer: 'TEEHEE', number: 132, clue: '"That\'s funny!"'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 21, col: 1, dir: 'Across', answer: 'TREE', number: 133, clue: 'Apple or lemon'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 21, col: 6, dir: 'Across', answer: 'ENSOR', number: 134, clue: 'Belgian painter James'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 21, col: 12, dir: 'Across', answer: 'CAD', number: 135, clue: 'Boor'))
clues_mgwcc083_unscrambled.push(Entry.create(row: 21, col: 16, dir: 'Across', answer: 'OLMECS', number: 136, clue: 'Mesoamerican tribe noted for sculptures of large stone heads'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#83 - "Merlin\' the Wizard"', grid: 'BELONG.AVS.MILER.TICS|ALARIE.MAA.BSIDE.AVOW|LISALIKELY.ANDIF.LIVE|KATT.SEXIST.TOSUCCEED|...OTHO.SARI..ONO.DRE|THEREAGLEHASLANDED...|EAR.ASHE..PLOP..DAVIS|ATOLL..TAMPARESISTANT|MESA.IOUSA..DRAT.ALTA|...PENN.TRLS.CLAW.ION|..OPRAHCRYINOUTLOUD..|LAP.AZUR.STIR.EINS...|OGEA.OLAF..DEBRA.SHOP|WILLYOUMARIEME..DRIVE|ATSEA..ERIN..ACRE.YEN|...CHAIRMANOFTHEBEARD|TEA.OWN..LENA.EATS...|WIDEOHPUN.REREAD.TONI|IDOL.IAGOS.SIXTYBEAST|SERB.LIGHT.ENE.TEEHEE|TREE.ENSOR.CAD.OLMECS', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/1/15', entries: clues_mgwcc083_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')