clues_mgwcc085_unscrambled = Array.new
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'YPPY', number: 1, clue: '"Success!"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'YER', number: 1, clue: 'Tom Petty\'s "___ So Bad"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PPQ', number: 2, clue: 'Perrier ou Evian'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PIA', number: 3, clue: 'Tray contents'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'YHHBBX', number: 4, clue: 'Legalese preposition'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'OUYX', number: 5, clue: 'Hannibal "conquered" them'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'OFWX', number: 5, clue: 'Jacques\' girlfriend'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'UZSIQ', number: 6, clue: 'Former European currency'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'YXIIG', number: 7, clue: 'With "on," victimizes'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'XPQLR', number: 8, clue: 'Palindromic billionaire'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'DCGXT', number: 9, clue: 'Jack, 25% of the time'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'DJZZZEZB', number: 9, clue: 'Element #34'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CSPB', number: 10, clue: 'Ballet bend'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'GRJUXR', number: 11, clue: 'Health food pioneer Davis'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'XABLIW', number: 12, clue: 'Believers in a "watchmaker" god'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'TMMHXV', number: 13, clue: 'Margaux Hemingway\'s grandfather'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'EPIH', number: 14, clue: 'Let (up)'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'FZXP', number: 15, clue: 'Joan born in Barcelona'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'JSRAM', number: 16, clue: 'Church chief'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RQAHJWSIQ', number: 17, clue: 'Its mouth is near Mulheim'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'JTAC', number: 18, clue: 'Street person?'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'ZPJBM', number: 19, clue: 'Occupy, as a coffin'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'BTXIILBZBULH', number: 20, clue: 'Those not yet mentioned'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'BHLAVCE', number: 21, clue: 'Treatment once used for a serious case of depression'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'NAYBA', number: 22, clue: 'Connecticut collegian'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'NAE', number: 22, clue: 'Base of the West African dish called "fufu"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'ACCN', number: 23, clue: 'Surrounded by'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'YIXP', number: 24, clue: 'Stories'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'QGRHZ', number: 25, clue: 'City on 17-across'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 5, col: 13, dir: 'Across', answer: 'XIX', number: 26, clue: 'Some football linemen: abbr.'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'ACIXCS', number: 27, clue: 'Egyptian mega-god'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'SKXICMN', number: 28, clue: 'Guru'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'LEHRWV', number: 29, clue: 'Like Papa, among the Smurfs'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 6, col: 12, dir: 'Down', answer: 'HFY', number: 30, clue: 'Place for pampering'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ECX', number: 31, clue: 'Russian for "peace"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'KOLGAZF', number: 32, clue: 'Wizened'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'OLV', number: 33, clue: 'Indian lands, in slang'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'LMB', number: 34, clue: '"Agreed"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'GHEU', number: 35, clue: 'Mrs. Garrett\'s first name, on "The Facts of Life"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'NPODXLMHVBYSU', number: 36, clue: 'Higher ketchup sales when french fries become more popular, for example'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'OBU', number: 37, clue: '___4 (Toyota SUV)'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'DJNNGAMD', number: 38, clue: 'Reagan Era scandal'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'SYEN', number: 39, clue: 'Bully\'s shout'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'UFPF', number: 40, clue: 'January 15th, 2010, for example'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'BJIVBEC', number: 41, clue: 'Iced tea brand'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'YFE', number: 42, clue: '"Come on, before it gets cold!"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'EXE', number: 43, clue: 'Smear'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'WLFUNC', number: 44, clue: 'Week-long mourning periods'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'WSPTDH', number: 44, clue: 'Show weariness with'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'LTTMCP', number: 45, clue: 'Zimbabwe\'s capital'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'FSUPWF', number: 46, clue: 'Alternative game to Truth or Dare or If You Had To'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'UEHBEPX', number: 47, clue: 'Landlocked province'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'HKPP', number: 48, clue: 'Ives of "The Big Country"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'BQFXON', number: 49, clue: 'With hipness'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'STS', number: 50, clue: 'John in the Highlands'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 11, col: 5, dir: 'Across', answer: 'NMUR', number: 51, clue: '"The Big Easy"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'UJWMQ', number: 52, clue: 'Comic strip about a girl in high school'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'RDRHA', number: 53, clue: '"Maybe" musical'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'KQNFE', number: 54, clue: 'Milking organ'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'PTUGGNJDKNPF', number: 55, clue: 'Actor with starring roles in "Heroes," "Felicity" and "Alias"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 12, col: 4, dir: 'Down', answer: 'GXJB', number: 56, clue: 'Mil. leaders'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'KZEF', number: 57, clue: 'Streisand moniker'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'NIFP', number: 58, clue: 'Towards the Atlantic, to Americans'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'TMPXA', number: 59, clue: 'Bonnie Raitt hit "___ Heart"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'WRZIPXUDJ', number: 60, clue: '"Falcon Crest" actress'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'UGF', number: 61, clue: 'Taper, for short'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'DPX', number: 62, clue: 'Business letters'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'JDU', number: 63, clue: 'Sometimes calling oneself'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'DCWJM', number: 64, clue: 'Stevie Wonder song "Moments ___ Moments"'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'MHEF', number: 65, clue: 'Tips for writers'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'OGPD', number: 66, clue: 'Slender'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HPFBD', number: 67, clue: 'Not in any way, shape or form like this particular crossword puzzle clue'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'QAFP', number: 68, clue: 'Make a nice home'))
clues_mgwcc085_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'NFXU', number: 69, clue: 'Place to pump iron'))
Puzzle.create(title: 'MGWCC #85 - "Aenigma Alphabetica"', grid: 'YPPY.OUYX.DCGXT|EPIH.FZXP.JSRAM|RQAHJWSIQ.ZPJBM|...BTXIILBZBULH|NAYBA.QGRHZ.XIX|ACIXCS...LEHRWV|ECX..KOLGAZF...|.NPODXLMHVBYSU.|...BJIVBEC..YFE|WLFUNC..UEHBEPX|STS.NMUR..KQNFE|PTUGGNJDKNPF...|TMPXA.WRZIPXUDJ|DCWJM.MHEF.OGPD|HPFBD.QAFP.NFXU', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/1/29', entries: clues_mgwcc085_unscrambled)
