clues_mgwcc091_unscrambled = Array.new
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AMPM', number: 1, clue: 'Watch selections'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ANUS', number: 1, clue: 'Endpoint of a familiar canal'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'MYST', number: 2, clue: 'Riven\'s predecessor'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'PEAR', number: 3, clue: 'Bulb-shaped food'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MTFUJI', number: 4, clue: 'Japanese Mecca'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'CHEAT', number: 5, clue: 'Move twice in a row, maybe'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'CHOKESON', number: 5, clue: 'Can\'t get down'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'HERB', number: 6, clue: 'Word whose first letter is silent in American English, pronounced in British'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'EDDY', number: 7, clue: 'Maelstrom'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AGE', number: 8, clue: '47, for Michael Jordan'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'TERSER', number: 9, clue: 'Not so imprecise'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'DROZ', number: 10, clue: 'Oprah buddy'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'DRAMBUIE', number: 10, clue: 'Rusty Nail ingredient'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ROBO', number: 11, clue: 'Humorous prefix meaning "mindlessly energetic"'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'OWES', number: 12, clue: 'Has to hand over'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ZETA', number: 13, clue: 'Zorba\'s beginning'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'NYET', number: 14, clue: 'Novosibirsk no'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HEDGE', number: 15, clue: 'Play both sides'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'ROWE', number: 16, clue: '"Dirty Jobs" host Mike'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'USAF', number: 17, clue: 'High branch, for short'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'ORDER', number: 18, clue: '20-piece McNuggets and fries, say'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'ABET', number: 19, clue: 'Burgle beside'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'STRUCKBY', number: 20, clue: 'Unable to overlook'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'COEN', number: 21, clue: '"Blood Simple" director'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'SAMOSA', number: 22, clue: 'Mumbai munchie'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'ALOT', number: 23, clue: 'Reams'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'JOE', number: 24, clue: 'Boxer of boxers'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'GELB', number: 25, clue: 'Yellow: Ger.'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'GREEDY', number: 25, clue: 'Into the dough'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'CITIESSURROUND', number: 26, clue: 'PART 1 OF HINT'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'CHIP', number: 26, clue: 'Token'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'IMOUT', number: 27, clue: '"Get someone else"'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'TOUCH', number: 28, clue: 'Dexterity'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'STERNA', number: 29, clue: 'Breastbones'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'URGED', number: 30, clue: 'Pushed'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'NERVE', number: 31, clue: 'Gumption'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'DUNCE', number: 32, clue: 'Word on a cap'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'HMO', number: 33, clue: 'System for an M.D.'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'NOTRE', number: 34, clue: 'Ours on the Oise'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'TIEUP', number: 35, clue: 'Monopolize'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'PORK', number: 36, clue: 'Congresscritter\'s food'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IOUS', number: 37, clue: 'Promises on paper'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'SKELETON', number: 38, clue: 'Amy Williams of the U.K. won a gold medal in it last week'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'NEGEV', number: 39, clue: 'Triangular desert'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'VIOLATOR', number: 40, clue: 'Breaker of rules'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'ERNO', number: 41, clue: '___ Laszlo Cosmetics'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'PUCKS', number: 42, clue: 'Rangers shoot them'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'SLIM', number: 43, clue: 'Like some chances'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'REDID', number: 44, clue: 'Tried again'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'DUET', number: 45, clue: 'Work for two people'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'VCR', number: 46, clue: 'Tape holder'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 10, col: 2, dir: 'Across', answer: 'THELANDYOUSEEK', number: 47, clue: 'PART 2 OF HINT'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ARAMIS', number: 48, clue: 'One of a noted trio'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'STRAIT', number: 49, clue: 'Narrow pass'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'LIRA', number: 50, clue: 'Old money'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'LET', number: 51, clue: 'Word heard before "first service"'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SCHEMA', number: 52, clue: 'Model'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SHEP', number: 52, clue: 'Smith of Fox News'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'COLE', number: 53, clue: 'Ship bombed in 2000'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'HYMN', number: 54, clue: 'Song sung Sundays'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'CHATROOM', number: 55, clue: 'Where you can be u'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'CRAG', number: 55, clue: 'Eagle\'s perch'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'HAHA', number: 56, clue: 'Schadenfreude shout'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'OUZO', number: 57, clue: 'Greek spirit'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ODOR', number: 58, clue: 'Suggestion'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'MIDI', number: 59, clue: '___-Pyrenees (large region of France)'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'HOYT', number: 60, clue: '1983 AL Cy Young winner'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'MARAT', number: 61, clue: 'He beat Pete to win the 2000 U.S. Open'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'ADU', number: 62, clue: 'Ghana-born soccer star'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'AUDI', number: 63, clue: 'Q5 company'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ELMO', number: 64, clue: 'He\'s a doll'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'IDAHO', number: 65, clue: 'Moscow is there'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'IZOD', number: 66, clue: 'Polo rival'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'PENN', number: 67, clue: '"Shanghai Surprise" actor, 1986'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'SUGAR', number: 68, clue: 'Honey'))
clues_mgwcc091_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'TORI', number: 69, clue: 'Aaron\'s daughter'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#91 - "Risk Analysis"', grid: 'AMPM.CHEAT.DROZ|NYET.HEDGE.ROWE|USAF.ORDER.ABET|STRUCKBY.SAMOSA|...JOE..GELB...|CITIESSURROUND.|HMO.NOTRE.TIEUP|IOUS.NEGEV.ERNO|PUCKS.REDID.VCR|.THELANDYOUSEEK|...LIRA..LET...|SCHEMA.CHATROOM|HOYT.MARAT.AUDI|ELMO.IDAHO.IZOD|PENN.SUGAR.TORI', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/3/12', entries: clues_mgwcc091_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')