clues_mgwcc093_unscrambled = Array.new
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SPAT', number: 1, clue: 'Slight fight'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SCROD', number: 1, clue: 'Food fish'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'PAINE', number: 2, clue: '"Common Sense" author'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ASSOC', number: 3, clue: 'Org.'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'THERAJ', number: 4, clue: 'Gandhi helped end it'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'SOROR', number: 5, clue: 'Frater\'s sibling'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'STROPHE', number: 5, clue: 'Ode part'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'OREM', number: 6, clue: 'Utah city'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'RAPA', number: 7, clue: '___ Nui (Easter Island)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ODOR', number: 8, clue: 'Scent'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'RESIGNS', number: 9, clue: 'Throws in the towel, in chess'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'PAAS', number: 10, clue: 'Company that makes Easter egg coloring kits'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'PARALLEL', number: 10, clue: 'Never crossing'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'AZUR', number: 11, clue: 'Color, on the other half of Hispaniola'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'AUDI', number: 12, clue: 'German wheels'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SLY', number: 13, clue: 'Crafty'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'CASH', number: 14, clue: 'Federal Reserve Notes'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'TRADE', number: 15, clue: 'Barter'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'AZUL', number: 16, clue: 'Color on half of Hispaniola'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'RISE', number: 17, clue: 'Court order'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'REPOS', number: 18, clue: 'Camrys taken back'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'RUDY', number: 19, clue: 'Tearjerker about the Notre Dame football team'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ONORIOMARINARI', number: 20, clue: 'Baroque Era painter of Florence (surname is one letter off from a pasta sauce)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 4, col: 5, dir: 'Down', answer: 'IMORE', number: 21, clue: '"___ fear what is within me than what comes from without"--Martin Luther'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'NAG', number: 22, clue: 'Engage in henpecking'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DECAMP', number: 23, clue: 'Get back on the trail'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'GAL', number: 24, clue: 'Chick'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'JOHNRINGLING', number: 25, clue: 'Rival of P.T. Barnum (who later bought his circus)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'NOCHE', number: 26, clue: 'En la ___ (at night)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'RIGEL', number: 27, clue: 'Orion\'s brightest star'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'ILIAC', number: 28, clue: '___ artery'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'IVAN', number: 29, clue: 'Drago or Lendl'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'NERO', number: 30, clue: 'Emperor from 54 to 68'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'GNAW', number: 31, clue: 'Chew (on)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'OLD', number: 32, clue: 'Former'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ORAL', number: 32, clue: 'Spoken'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'LOCI', number: 33, clue: 'Places'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'DUES', number: 34, clue: 'Club money'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'REOILS', number: 35, clue: 'Gives the squeak another shot'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'EVEN', number: 36, clue: 'Golf score better than one over par'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ROUTE', number: 37, clue: 'Pathway'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'TRAUMATA', number: 38, clue: 'Scarring events'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 8, col: 7, dir: 'Across', answer: 'CGI', number: 39, clue: 'Film graphics initials'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Across', answer: 'CLARA', number: 40, clue: 'Bow in a movie theater'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'CHECK', number: 40, clue: '"The king is in danger"'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ACER', number: 41, clue: 'Computer brand'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'SHEATH', number: 42, clue: 'Epee protector'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Down', answer: 'SHEETED', number: 42, clue: 'Short-___ (played an old-school prank on)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 9, col: 10, dir: 'Down', answer: 'THECARS', number: 43, clue: '"Just What I Needed" band'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'NOW', number: 44, clue: '"Act ___!"'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'LISAWHELCHEL', number: 45, clue: '"The Facts of Life" actress'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'WSU', number: 46, clue: 'Walla Walla sch.'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'LOWEST', number: 47, clue: 'At the bottom'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'USE', number: 48, clue: 'Point'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'ECOLES', number: 49, clue: 'Grandes ___ (France\'s Ivy Leagues)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'LILLE', number: 50, clue: 'France\'s fourth-largest city'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ECLAT', number: 51, clue: 'Brilliant success'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'SKATE', number: 52, clue: 'Participate in a roller derby'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Across', answer: 'SAMUELPICKWICK', number: 53, clue: 'Dickens title character'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'SOBE', number: 53, clue: 'Brand bought by Pepsi in 2000'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'ALES', number: 54, clue: 'Pale ___'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'LILI', number: 55, clue: 'Taylor of "Say Anything"'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'PAGO', number: 56, clue: 'Half a Pacific capital'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'IRAN', number: 57, clue: 'Turkmenistan neighbor'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ZOLA', number: 58, clue: 'Eminent Emile'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Down', answer: 'ZIM', number: 58, clue: 'Afr. nation that suffered recent hyperinflation'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'TIARA', number: 59, clue: 'Head piece'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'ELLA', number: 60, clue: '"___ Enchanted" (2004 movie)'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'IBET', number: 61, clue: '"Yeah, right!"'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ELGAR', number: 62, clue: '"Pomp and Circumstance" composer'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'SLAT', number: 63, clue: 'Bed part'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'MESA', number: 64, clue: 'Southwest city'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'DIONS', number: 65, clue: 'Celine\'s family'))
clues_mgwcc093_unscrambled.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'TETE', number: 66, clue: 'Word on either side of "&#224;"'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#93 - "Namegame"', grid: 'SPAT.SOROR.PAAS|CASH.TRADE.AZUL|RISE.REPOS.RUDY|ONORIOMARINARI.|DECAMP...GAL...|...JOHNRINGLING|OLD.REOILS.EVEN|ROUTE.CGI.CLARA|ACER.SHEATH.NOW|LISAWHELCHEL...|...USE...ECOLES|.SAMUELPICKWICK|ZOLA.TIARA.ELLA|IBET.ELGAR.SLAT|MESA.DIONS.TETE', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/3/26', entries: clues_mgwcc093_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')