clues_mgwcc095_unscrambled = Array.new
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'MISMANAGED', number: 1, clue: 'Like Enron'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'MAMA', number: 1, clue: 'Peter Tosh\'s "___ Africa"'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'INES', number: 2, clue: 'Model Sastre'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SNAP', number: 3, clue: 'Go nuts'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'MATSUI', number: 4, clue: '2009 World Series MVP'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ABC', number: 5, clue: '"Lost" tribe?'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'NEU', number: 6, clue: '___-Anspach, Germany'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALTA', number: 7, clue: 'Deer Valley neighbor'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'GLIB', number: 8, clue: 'Like game show hosts, often'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EENS', number: 9, clue: 'Nights for Burns'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DER', number: 10, clue: 'Brecht short story "___ Augsburger Kreidekreis"'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'CLAM', number: 11, clue: 'Shell dweller'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'CHAINSAW', number: 11, clue: 'Loud weapon'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LOSESTRACK', number: 12, clue: 'Forgets'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ATTN', number: 13, clue: 'Envelope letters'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'MESS', number: 14, clue: 'Basket case'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ANNABELLEE', number: 15, clue: 'Poem that begins "It was many and many a year ago / In a kingdom by the sea"'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'HOTE', number: 16, clue: 'Table d\'___'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MEATCUTINROASTS', number: 17, clue: 'Clue #1'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 3, col: 11, dir: 'Down', answer: 'OLAF', number: 18, clue: 'Count in the Lemony Snicket books'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ASPS', number: 19, clue: 'Dangerous reptiles'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 4, col: 7, dir: 'Across', answer: 'ABS', number: 20, clue: 'Ripped section, perhaps'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'LIENS', number: 21, clue: 'They\'re placed on some houses'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'UPC', number: 22, clue: 'Code letters'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'PCS', number: 23, clue: 'Dell champions them'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'CAPELLA', number: 24, clue: '5th-brightest star in the Northern Hemisphere'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Across', answer: 'SANS', number: 25, clue: 'Lacking, pretentiously'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'SLYNESS', number: 25, clue: 'Craft'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'AFRICANGOLFSTAR', number: 26, clue: 'Clue #2'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ANOOP', number: 26, clue: '"American Idol" season 8 finalist ___ Desai'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'FERMI', number: 27, clue: 'Rome-born Nobelist'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'RECONCILES', number: 28, clue: 'Does accounting work'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'NAVEL', number: 29, clue: 'Gazed-at body part'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'GRIMM', number: 30, clue: 'Fitting literary surname'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 9, dir: 'Down', answer: 'OKAPI', number: 31, clue: 'Animal with striped legs'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'ANGIE', number: 32, clue: '#1 hit possibly about David Bowie\'s wife'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ROSAS', number: 33, clue: 'Parks and then some'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'NEE', number: 34, clue: 'Called once'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'SPARKY', number: 35, clue: '1977 AL Cy Young winner Lyle'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'ARNO', number: 36, clue: 'Pisa splitter'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ORCH', number: 37, clue: 'Classical group: abbr.'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'HOBOCAMP', number: 38, clue: 'Depression Era sight'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'EVIAN', number: 39, clue: 'Spring in France'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 8, col: 12, dir: 'Across', answer: 'WAGS', number: 40, clue: 'Goes back and forth'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'OMOO', number: 41, clue: 'Tale of mutiny'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 9, col: 6, dir: 'Across', answer: 'LEMPEL', number: 42, clue: 'Crossword constructor Lynn'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'LTS', number: 43, clue: '6\'s, in Stratego: abbr.'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'CIA', number: 44, clue: 'Org. JFK sought to reform'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'PINBALLMISTAKES', number: 45, clue: 'Clue #3'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'ALOT', number: 46, clue: 'Oceans'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'ANGLOS', number: 47, clue: 'Some Texans'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'COLA', number: 48, clue: 'Cherry ___'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'SSN', number: 49, clue: 'The IRS has yours'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'CHICO', number: 50, clue: 'California\'s "City of Roses"'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'CROW', number: 50, clue: 'Boast'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'HERA', number: 51, clue: 'She married her brother'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'LSU', number: 52, clue: 'Southeastern Conference sch.'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 7, dir: 'Down', answer: 'LVOV', number: 52, clue: 'Historic city of the USSR'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'SEVE', number: 53, clue: 'He edged Tom out to win the 1984 British Open'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'UBER', number: 54, clue: 'Greatest, in combinations'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'GIGO', number: 55, clue: 'Acronym sort of like TANSTAAFL'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'IOUS', number: 56, clue: 'Promised pounds, perhaps'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'GONE', number: 57, clue: 'Outta there'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'ODDS', number: 58, clue: 'Track numbers'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RELATIVEBYBLOOD', number: 59, clue: 'Clue #4'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'IMO', number: 60, clue: 'Humble TLA'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'YAP', number: 61, clue: 'Eschew silence'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'BRA', number: 62, clue: 'Top'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OREM', number: 63, clue: 'Great Basin city'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'MOVEAROUND', number: 64, clue: 'Get the blood circulating'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'WASP', number: 65, clue: 'Preppy, perhaps'))
clues_mgwcc095_unscrambled.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'OVERPASSES', number: 66, clue: 'High ways'))
instructions = 'Coming soon...'
explanation = '<MA></MA><TEXT>Coming soon...</TEXT>'
Puzzle.create(title: '#95 - "Silence Is Golden"', grid: 'MISMANAGED.CLAM|ANNABELLEE.HOTE|MEATCUTINROASTS|ASPS..ABS.LIENS|...UPC...SANS..|AFRICANGOLFSTAR|NEE.SPARKY.ARNO|ORCH.EVIAN.WAGS|OMOO.LEMPEL.CIA|PINBALLMISTAKES|..COLA...SSN...|CHICO.LSU..GIGO|RELATIVEBYBLOOD|OREM.MOVEAROUND|WASP.OVERPASSES', :constructors => Constructor.where(:name => 'Matt Gaffney'), :sources => Source.where(:name => 'Matt Gaffney\'s Weekly Crossword Contest'), publication_date: '2010/4/9', entries: clues_mgwcc095_unscrambled, instructions: instructions, explanation: explanation, puzzle_type: 'meta', puzzle_type: 'meta')