clues_A_New_Man_CR_5_17_12 = Array.new
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SLAP', number: 1, clue: 'Hit, as with a fine'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SMORE', number: 1, clue: 'Sweet camping treat'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LAXER', number: 2, clue: 'More likely to allow football in the house'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ARYAN', number: 3, clue: 'Ancient Indo-European'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'PVCPIPE', number: 4, clue: 'Dangerous thing to make a bong with'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'DUMB', number: 5, clue: 'Unthinking'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'DANL', number: 5, clue: 'Twain\'s jumping frog'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'UDAY', number: 6, clue: 'Hussein killed in 2003'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'MID', number: 7, clue: 'Prefix with term or town'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'BAABAA', number: 8, clue: 'Nursery rhyme starter'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'PABLO', number: 9, clue: '"Il Postino" character Neruda'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'PORSCHES', number: 9, clue: 'Cars with a coat of arms logo'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'ANATOLE', number: 10, clue: 'French Nobelist France'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'BEJEWELED', number: 11, clue: 'Bestselling puzzle game since 2001'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'LBAR', number: 12, clue: 'Letter-shaped brace'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'OCHS', number: 13, clue: 'Adolph who adamantly opposed anti-Semitism'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'MARV', number: 14, clue: 'Albert of announcing'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ADIA', number: 15, clue: 'McLachlan single with the line "I do believe I failed you"'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'ONEBC', number: 16, clue: 'Divine conception year'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OXYCANADA', number: 17, clue: 'Acne care company\'s North American branch?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'APER', number: 18, clue: 'One who parrots'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'RAJAH', number: 19, clue: 'Ranee\'s husband'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'REAPPLY', number: 20, clue: 'Try for the same job'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'BASTERS', number: 21, clue: 'Home insemination kit implements'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'ADT', number: 22, clue: 'Letters in security'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ERNIE', number: 23, clue: '"The Adventures of Elmo in Grouchland" host'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'MADCOW', number: 24, clue: 'Bovine spongiform encephalopathy, casually'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'MYSTIFY', number: 24, clue: 'Puzzle'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'PROXYATHLETE', number: 25, clue: 'Ballplayer\'s body double?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'ONO', number: 26, clue: 'Musician who still lives in the Dakota, next to Central Park'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'XOO', number: 27, clue: 'Losing tic-tac-toe row'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'TEND', number: 28, clue: 'Keep going, as a fire'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'EDDY', number: 29, clue: 'Swirl in the tub'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'SKEE', number: 30, clue: '___-ball'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'SWAG', number: 30, clue: 'Free junk'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'KALA', number: 31, clue: 'M.I.A. album with "Paper Planes"'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'EVALUATOR', number: 32, clue: 'Professor, at times'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'NOS', number: 33, clue: 'Frequent insurance company responses'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'EELED', number: 34, clue: 'Moved sinuously'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'WAV', number: 35, clue: 'Uncompressed audio format'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'BOOTIES', number: 36, clue: 'Little one\'s footwear'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'BMXRACES', number: 36, clue: 'Some offroad bike competitions'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'IMF', number: 37, clue: 'Org. that advocates neoliberal restructuring'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'EPA', number: 38, clue: 'Frequent GOP debate target'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'END', number: 39, clue: 'The bitter ___'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ALARM', number: 40, clue: 'Chili rating unit'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'RANWILD', number: 41, clue: 'Went off the leash, say'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'IMP', number: 42, clue: 'Hellion'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'ADDY', number: 43, clue: 'Contact info datum, casually'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'ARAMEAN', number: 43, clue: 'Ancient Mesopotamian'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'GALAXYAFFAIR', number: 44, clue: 'Tryst in space?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'YUL', number: 45, clue: 'Brynner from Russia'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'ALLBUT', number: 46, clue: 'Except'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IPAD', number: 47, clue: 'April 2010 technological debut'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'UNRULY', number: 48, clue: 'Like hair on a bad hair day, say'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'PAPER', number: 49, clue: 'Times, in many cities'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'PORNO', number: 50, clue: 'Blue screen genre'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'EDENS', number: 51, clue: 'Unblemished spots?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'REKEY', number: 52, clue: 'Type again'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SEAWALL', number: 53, clue: 'Tidal wave defense'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SASH', number: 53, clue: 'Strip at homecoming?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ETTE', number: 54, clue: 'Ending that connotes smallness'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'ALAMODE', number: 55, clue: 'Served with a scoop'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'AXED', number: 55, clue: 'Got rid of, as an agency'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'LYRE', number: 56, clue: 'Instrument in some old paintings'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ATTIC', number: 57, clue: 'Floor with retro clothes, often'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'BOXYDEREK', number: 58, clue: 'Jeter with robotic features?'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'OSU', number: 59, clue: 'Sch. for Sooners, Buckeyes, or Beavers'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'STOLE', number: 60, clue: 'Ganked'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'USER', number: 61, clue: 'Methadone clinic client'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ANNE', number: 62, clue: 'Name for two of Henry VIII\'s wives'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'HERDS', number: 63, clue: 'Groups of cattle'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'TUDE', number: 64, clue: 'Sassiness, briefly'))
clues_A_New_Man_CR_5_17_12.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'NOSY', number: 65, clue: 'Up in others\' business'))
Puzzle.create(title: 'A New Man', grid: 'SLAP.DUMB.PABLO|MARV.ADIA.ONEBC|OXYCANADA.RAJAH|REAPPLY.BASTERS|ERNIE..MADCOW..|...PROXYATHLETE|SKEE.NOS..EELED|WAV.BOOTIES.END|ALARM..IMP.ADDY|GALAXYAFFAIR...|..UNRULY..PAPER|SEAWALL.ALAMODE|ATTIC.BOXYDEREK|STOLE.USER.ANNE|HERDS.TUDE.NOSY', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/5/17', entries: clues_A_New_Man_CR_5_17_12)
