clues_Eastern_Bowl_Game_CR_12_13_12 = Array.new
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'SLAV', number: 1, clue: 'Bohemian, e.g.'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'SPATS', number: 1, clue: 'Certain sibling interactions'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'LECHE', number: 2, clue: 'Beb&#233;\'s treat'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ATEAM', number: 3, clue: 'Group that included Mr. T as "Bad Attitude" Baracus'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'VERTIGO', number: 4, clue: 'Hitchcock film that ends with a nun saying "God, have mercy"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'FLIED', number: 5, clue: 'Popped (out)'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'FLEXOR', number: 5, clue: 'Biceps, e.g.'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'LIVEN', number: 6, clue: 'Jazz (up)'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'IVANI', number: 7, clue: 'Russian prince known as "Moneybag"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'ERDOC', number: 8, clue: 'Colleague of Nurse Jackie, casually'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'DEEP', number: 9, clue: 'Profound'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'IDEA', number: 10, clue: 'Result of ruminating'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'INTOTAL', number: 10, clue: 'All told'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'DOUBLOONS', number: 11, clue: 'Pirate\'s coins'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'ELSIE', number: 12, clue: 'Smiling cow of advertising'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'AOKAY', number: 13, clue: 'Fine'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'PETE', number: 14, clue: 'Either brother in a Nickelodeon show'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'LIVRE', number: 15, clue: 'Belgian book'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'NOLO', number: 16, clue: '___ contendere'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'ACER', number: 17, clue: 'Netbook name'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 3, col: 6, dir: 'Across', answer: 'EVADE', number: 18, clue: 'Duck, as the Feds'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'TUSK', number: 19, clue: 'Fleetwood Mac\'s "cocaine opus"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'THAT', number: 20, clue: '"What\'s up with ___?"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'XENOPHOBIA', number: 21, clue: 'Racism\'s cousin'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'HUMANOID', number: 22, clue: 'Like many "Star Trek" races'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'SEMISONIC', number: 23, clue: '"Closing Time" band'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'SENSORIA', number: 24, clue: 'Perceptions'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 5, col: 11, dir: 'Across', answer: 'UTLEY', number: 25, clue: 'Phillie Chase on Sports Illustrated\'s "MLB All-Decade Team"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'GER', number: 26, clue: 'Fritz Lang\'s lang.'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'LMAO', number: 27, clue: 'ROFL alternative'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 6, col: 10, dir: 'Down', answer: 'LEO', number: 27, clue: 'Astrological diva'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DIJON', number: 28, clue: 'Mustard with white wine'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'DRJ', number: 28, clue: 'Winner of the 1976 ABA Slam Dunk contest'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'ICU', number: 29, clue: 'Post-op place'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'JAMPACKED', number: 30, clue: 'Mobbed'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'HOMEALONE', number: 31, clue: 'Film in which Joe Pesci does not curse'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'HUE', number: 31, clue: 'One of fifty shades of grey, say?'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'OPT', number: 32, clue: '___ out (stop subscribing)'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'MCS', number: 33, clue: 'XXL article subjects'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'NOT', number: 34, clue: 'Sarcastic \'90s negation'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'EMS', number: 35, clue: 'Big name in outdoor equipment, for short'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RCA', number: 36, clue: 'Label for Alicia Keys'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'SOUPCON', number: 37, clue: 'Small taste or, pronounced aloud, a hint to this puzzle\'s theme'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'OJS', number: 38, clue: 'Brunch special drinks'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'NOM', number: 39, clue: 'Eating sound'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'JUMBOJETS', number: 40, clue: '747s, e.g.'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'BARRENS', number: 41, clue: 'Pine plains'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'OUSTS', number: 42, clue: 'Fires from Washington'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'UNOWNED', number: 43, clue: 'Like the moon, in real estate terms'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'PARS', number: 44, clue: 'Course averages?'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'QIN', number: 45, clue: 'Emperor Qinshihuang\'s dynasty'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'QUOTED', number: 45, clue: 'Gave, as an estimate'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ATARI', number: 46, clue: '"Business is fun" company'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'ASPIC', number: 46, clue: 'Jelly dish'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'TAITO', number: 47, clue: '"Space Invaders" maker'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 7, dir: 'Across', answer: 'PSEUDONYM', number: 48, clue: 'Jon Stewart or Mark Twain'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'PEDRO', number: 48, clue: 'Class presidential nominee in "Napoleon Dynamite"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'SNOUT', number: 49, clue: 'Afghan protrusion'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ETUDE', number: 50, clue: 'Piano student\'s practice'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'NIECE', number: 51, clue: 'Jenna, to Jeb'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'YKNOW', number: 52, clue: '"Amirite?"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'MIENS', number: 53, clue: 'Manners'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SACRAMENTO', number: 54, clue: 'Bee locale'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 12, col: 6, dir: 'Down', answer: 'MATT', number: 55, clue: 'Bart and Lisa\'s creator'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'WIKI', number: 56, clue: 'Modifiable site'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'PIKE', number: 57, clue: '"Lord of the Rings" weapon'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'ADOUT', number: 58, clue: 'Break point, in tennis'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 13, col: 12, dir: 'Across', answer: 'NENE', number: 59, clue: 'Leakes of "The Real Housewives of Atlanta"'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ITEN', number: 60, clue: 'Transnational highway built by Ike'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'TRUDE', number: 61, clue: 'Frau in a really dark Brothers Grimm story'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ECON', number: 62, clue: 'Paul Krugman\'s subj.'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'CODS', number: 63, clue: 'Some UPS deliveries'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TOTED', number: 64, clue: 'Carried, as a gun'))
clues_Eastern_Bowl_Game_CR_12_13_12.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'DEWS', number: 65, clue: 'Morning moistures'))
Puzzle.create(title: 'Eastern Bowl Game', grid: 'SLAV.FLIED.IDEA|PETE.LIVRE.NOLO|ACER.EVADE.TUSK|THAT.XENOPHOBIA|SEMISONIC.UTLEY|...GER...LMAO..|DIJON.HOMEALONE|RCA.SOUPCON.NOM|JUMBOJETS.OUSTS|..PARS...QIN...|ATARI.PSEUDONYM|SACRAMENTO.WIKI|PIKE.ADOUT.NENE|ITEN.TRUDE.ECON|CODS.TOTED.DEWS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/12/13', entries: clues_Eastern_Bowl_Game_CR_12_13_12)
