clues_Ecological_Change_CR_6_21_12 = Array.new
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'BARK', number: 1, clue: 'Certain traditional medicine source'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'BFFS', number: 1, clue: 'Inseparable middle sch. pals, perhaps'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ALEE', number: 2, clue: 'Sheltered, on a ship'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'RENE', number: 3, clue: 'Russo of "Ransom"'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'KASHMIR', number: 4, clue: 'Long song from "Physical Graffiti"'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'WBA', number: 5, clue: 'Org. that awards belts'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'WHIRR', number: 5, clue: 'Blender noise'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'BITESIZE', number: 6, clue: 'Like some Halloween candy'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'ASH', number: 7, clue: 'Cigar tip stuff'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'AMPSUP', number: 8, clue: 'Excites'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'APPIA', number: 8, clue: 'Via ___ (noted Roman road)'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'MAINDRAG', number: 9, clue: 'Strip with a lot of people around?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'PREENED', number: 10, clue: 'Strutted one\'s stuff'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'SETSEYESON', number: 11, clue: 'Beholds'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'UVEAS', number: 12, clue: 'Eye layers'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'PERPS', number: 13, clue: '"CSI" characters'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'FLEA', number: 14, clue: 'Pet parasite'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'HIS', number: 15, clue: '___ Holiness the Dalai Lama'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'PAREVE', number: 16, clue: 'Kosher product word'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'FENSWITH', number: 17, clue: 'With 55-Across, wetlands where you can collect a little peat but not feel committed?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'WEAN', number: 18, clue: 'Move slowly away from the breasts'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 3, col: 10, dir: 'Across', answer: 'PIETER', number: 19, clue: 'Painter Bruegel the Elder'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SEEHERE', number: 20, clue: '"Now you listen to me!"'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'WINESAP', number: 21, clue: 'Cider apple'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 4, col: 9, dir: 'Down', answer: 'WMD', number: 21, clue: 'Nukes, e.g.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'MARSHMADNESS', number: 22, clue: 'Annual wetlands tournament involving cattails and water lilies, casually?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'HEIRESS', number: 23, clue: 'Paris Hilton, e.g.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'TOBIN', number: 24, clue: '___ Sprout of Guided by Voices'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'TOMB', number: 24, clue: 'Archetypically silent place'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'ODIE', number: 25, clue: 'Cartoon beagle born in 1978'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'BOLTCUTTER', number: 26, clue: 'Bike thief\'s tool'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 7, dir: 'Across', answer: 'IED', number: 27, clue: 'Modern war hazard, briefly'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'REY', number: 28, clue: 'WWE wrestler Mysterio'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ODOR', number: 29, clue: 'Diaper changing hint'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'UZI', number: 30, clue: '"Scarface" gun'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 6, dir: 'Down', answer: 'UEY', number: 30, clue: 'Highway maneuver in some movie chase scenes'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 10, dir: 'Across', answer: 'MADEDO', number: 31, clue: 'Scraped by'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'MOA', number: 31, clue: 'Minnesota shopping mecca, briefly'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'DELI', number: 32, clue: 'Store with cold cuts'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'OPEC', number: 33, clue: 'Big oil gp.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'MIL', number: 34, clue: 'Part of a sergeant\'s address?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'BEERBOG', number: 35, clue: 'Wetland area that hosts keggers?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'BASILICA', number: 35, clue: 'St. Peter\'s, e.g.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'BROWSERS', number: 36, clue: 'Opera and Chrome, for two'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SEP', number: 37, clue: 'Mo. evoked in many an end-of-summer song'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'BETRAY', number: 38, clue: 'Two-time'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'ROSIEST', number: 39, clue: 'Most 41-Down'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'ERA', number: 40, clue: 'Feminist cause opposed by the LDS'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'HOLE', number: 41, clue: 'Sock problem'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'HOPEFUL', number: 41, clue: 'Utopian, say'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 10, col: 3, dir: 'Across', answer: 'COS', number: 42, clue: 'They\'re treated as people, legally: Abbr.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 10, col: 7, dir: 'Across', answer: 'USO', number: 43, clue: 'Org. that sent Stephen Colbert to Iraq in 2009'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'UGG', number: 43, clue: 'Australian boot brand'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 10, col: 11, dir: 'Across', answer: 'IONIC', number: 44, clue: 'National Gallery exterior column type'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IMRE', number: 44, clue: '2002 Literature Nobelist Kert&#233;sz'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'HOUSINGSWAMP', number: 45, clue: 'Wetland that rents living spaces to crocodiles and dragonflies?'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'HAVES', number: 45, clue: 'Well-off people'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'ONONE', number: 46, clue: 'Band leader\'s cue'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'NONOS', number: 47, clue: 'Taboos'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 11, col: 10, dir: 'Down', answer: 'ACNED', number: 48, clue: 'In need of Clearasil'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ANTILOG', number: 49, clue: 'Pre-calc calculation'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 12, col: 9, dir: 'Across', answer: 'SCREWUP', number: 50, clue: 'Produce a boner'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'WIKI', number: 51, clue: 'Web prefix that means "fast"'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'UTES', number: 52, clue: 'Colorado plateau tribespeople'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'PSST', number: 53, clue: 'Beckoning sound'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'VOTEIN', number: 54, clue: 'Elect'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 13, col: 8, dir: 'Across', answer: 'BENEFITS', number: 55, clue: 'See 17-Across'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'BOL', number: 55, clue: 'NBA center Manute who was 7\'7"'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ENESCO', number: 56, clue: '"Romanian Rhapsodies" composer Georges'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ORE', number: 57, clue: 'Source of iron, e.g.'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'UKES', number: 58, clue: 'You may play them where there are leis'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'SERTAS', number: 59, clue: 'Alternatives to Tempur-Pedics'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'LSD', number: 60, clue: 'Psychedelic music drug'))
clues_Ecological_Change_CR_6_21_12.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'LIST', number: 61, clue: 'Tick off'))
Puzzle.create(title: 'Ecological Change', grid: 'BARK.WBA.AMPSUP|FLEA.HIS.PAREVE|FENSWITH.PIETER|SEEHERE.WINESAP|...MARSHMADNESS|TOBIN.IED.REY..|ODOR.UZI.MADEDO|MIL.BEERBOG.SEP|BETRAY.ERA.HOLE|..COS.USO.IONIC|HOUSINGSWAMP...|ANTILOG.SCREWUP|VOTEIN.BENEFITS|ENESCO.ORE.UKES|SERTAS.LSD.LIST', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/6/21', entries: clues_Ecological_Change_CR_6_21_12)
