clues_High_Season_CR_4_20_12 = Array.new
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'THC', number: 1, clue: 'April 20th substance, and a hint to this puzzle\'s theme'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'THEDUDE', number: 1, clue: '"Big Lebowski" protagonist'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'HOARSER', number: 2, clue: 'More speechless, in a way'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'CEREALS', number: 3, clue: 'Life and Total, for two'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 5, dir: 'Across', answer: 'AIRBAG', number: 4, clue: 'Device inside the wheel'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'ASH', number: 4, clue: 'Fire remains'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ITCH', number: 5, clue: 'Urge'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ROHE', number: 6, clue: 'Le Corbusier contemporary Mies van der ___'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'BRANG', number: 7, clue: 'Took with ya'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'AMI', number: 8, clue: '"___ dreaming?"'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'GYRATE', number: 9, clue: 'Dance like Shakira'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'PICK', number: 10, clue: 'Guitarist\'s need'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'PIERCING', number: 10, clue: 'Nipple or tongue accentuation'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'INDIANA', number: 11, clue: 'Home state of Michael Jackson and Will Shortz'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CREEPER', number: 12, clue: 'Certain vine'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'KENNEDY', number: 13, clue: 'Subject of conspiracy rumors for nearly 50 years'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'HOE', number: 14, clue: 'Tool for cultivation'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 2, col: 5, dir: 'Across', answer: 'STORMY', number: 15, clue: 'Hailing, say'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'INRE', number: 16, clue: 'On the topic of, briefly'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'EARTHCHAIR', number: 17, clue: 'Eco-friendly seating?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 3, col: 4, dir: 'Down', answer: 'TWIT', number: 18, clue: 'Tool'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'EDEN', number: 19, clue: 'Garden in the Qur\'an'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'DREW', number: 20, clue: 'Sketched out'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 4, col: 6, dir: 'Across', answer: 'HEN', number: 21, clue: 'She\'s fowl'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 4, col: 10, dir: 'Across', answer: 'ADRIEN', number: 22, clue: 'Brody who played Salvador Dal&#237;'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'DHL', number: 23, clue: 'Shipper with red-and-yellow trucks'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'USAIN', number: 24, clue: 'Bolt with a 100 meter record'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'NOIR', number: 25, clue: '"Drive" genre'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'GOTHCAPE', number: 26, clue: 'Long black garment for a Bauhaus fan?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'ORACLE', number: 27, clue: 'Delphi figure'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'DELTOID', number: 28, clue: 'Muscle near the rotator cuff'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'IMO', number: 29, clue: 'Shorthand before offering one\'s POV'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'DOTEDU', number: 30, clue: 'Part of a collegiate address'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 6, col: 9, dir: 'Across', answer: 'RELINED', number: 31, clue: 'Fixed, as a coat'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ERS', number: 32, clue: 'Lousy but common substitutes for primary care docs'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 7, col: 5, dir: 'Across', answer: 'IMONA', number: 33, clue: 'Words before boat or roll'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'NHL', number: 34, clue: 'League with Ducks and Canucks'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 7, col: 12, dir: 'Across', answer: 'NARY', number: 35, clue: 'Not'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 8, col: 4, dir: 'Across', answer: 'BROTHCHUG', number: 36, clue: 'Competitive soup eater\'s technique?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'BARTLETT', number: 36, clue: 'John of "Familiar Quotations"'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'HEX', number: 37, clue: 'Spell badly?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 8, col: 11, dir: 'Down', answer: 'UNIT', number: 38, clue: 'Apartment, to a realtor'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'ILSA', number: 39, clue: '"___, She Wolf of the SS"'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 1, dir: 'Down', answer: 'IMTIRED', number: 39, clue: 'Pooped words'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 2, dir: 'Down', answer: 'LEETIDE', number: 40, clue: 'Current running with the wind'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 3, dir: 'Down', answer: 'STEALIN', number: 41, clue: 'Enter on the sly'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 7, dir: 'Across', answer: 'ELLEN', number: 42, clue: '"Puppy Episode" sitcom'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ASP', number: 43, clue: 'Source of ancient Egyptian poison'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 13, dir: 'Down', answer: 'AFRAMES', number: 43, clue: 'Many ski houses'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 14, dir: 'Down', answer: 'SEMIPRO', number: 44, clue: '2008 Will Ferrell sports comedy'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'PEERSAT', number: 45, clue: 'Eyes'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'METROID', number: 46, clue: 'Nintendo shooter set in outer space'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 10, col: 5, dir: 'Down', answer: 'OHI', number: 47, clue: '"___ wish I were an Oscar Mayer wiener"'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'ICEMEN', number: 48, clue: 'Hired killers, in slang'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'EXITFEE', number: 49, clue: 'Certain airport tax'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'TOFU', number: 50, clue: 'Vegan protein source'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'TEETHCUP', number: 51, clue: 'Denture wearer\'s receptacle?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'PETCO', number: 52, clue: 'Store that sells tanks'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'TORME', number: 53, clue: 'Crooner Mel'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ITALIE', number: 54, clue: 'Rome\'s country, to Parisians'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'ETA', number: 55, clue: 'It might get pushed back in the air, for short'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 12, col: 9, dir: 'Down', answer: 'THEN', number: 56, clue: '"In that case ..."'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'ACNE', number: 57, clue: 'Spots that might make you unpopular'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'FAIR', number: 58, clue: 'Liable to burn at the beach'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'RILE', number: 59, clue: 'Annoy'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'MYTHCHUMPS', number: 60, clue: 'Saps who believe apocryphal stories?'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'YOO', number: 61, clue: '___-hoo (bottled chocolate drink)'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'HER', number: 62, clue: '"That\'s the woman!"'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'EDIT', number: 63, clue: 'Take the word count down'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'EOCENE', number: 64, clue: 'Epoch when mammals arose'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 14, col: 13, dir: 'Across', answer: 'ERA', number: 65, clue: 'Baseball stat that corrects for errors'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'DENT', number: 66, clue: 'Ding on a car'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'NOONER', number: 67, clue: 'Midday tryst'))
clues_High_Season_CR_4_20_12.push(Entry.create(row: 15, col: 13, dir: 'Across', answer: 'SOT', number: 68, clue: 'One often wasted'))
Puzzle.create(title: 'High Season', grid: 'THC.AIRBAG.PICK|HOE.STORMY.INRE|EARTHCHAIR.EDEN|DREW.HEN.ADRIEN|USAIN..GOTHCAPE|DELTOID.RELINED|ERS.IMONA..NARY|...BROTHCHUG...|ILSA..ELLEN.ASP|METROID.EXITFEE|TEETHCUP..TORME|ITALIE.ETA.FAIR|RILE.MYTHCHUMPS|EDIT.EOCENE.ERA|DENT.NOONER.SOT', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/4/20', entries: clues_High_Season_CR_4_20_12)
