clues_Prime_Time_Panhandlers_CR_2_2_12 = Array.new
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'FIVEK', number: 1, clue: 'High school cross country race, typically'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'FAHD', number: 1, clue: 'Former Saudi Arabian king'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'IGOR', number: 2, clue: '2008 Cusack film about a hunchback'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'VICE', number: 3, clue: 'Hipster magazine co-founded by Gavin McInnes'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'ELK', number: 4, clue: 'Great Smoky Mountains deer'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'KEELED', number: 5, clue: 'Fell (over)'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'ANNA', number: 6, clue: 'Ms. Karenina'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ALPINE', number: 6, clue: 'Like some skiing'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'NOUN', number: 7, clue: 'Rock, paper, or scissors'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'NECKBONE', number: 8, clue: 'Chicken soup broth flavorer'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'AWK', number: 9, clue: 'Teacher\'s comment that she maybe might write near sentences sort of like this current clue here'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'ETCH', number: 10, clue: 'Engrave like Lucian Freud'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'EASIER', number: 10, clue: 'More of a breeze'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TELEPORTED', number: 11, clue: 'Traveled, a la "Star Trek"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'CROSSWORD', number: 12, clue: 'Popular subway pastime'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'HOPE', number: 13, clue: '2008 campaign word'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'AGILE', number: 14, clue: 'Light on one\'s feet'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'LOEW', number: 15, clue: 'Cineplex magnate Marcus'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'AERO', number: 16, clue: 'Prefix with -nautic'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'HOCKEYPUCK', number: 17, clue: 'Unflattering comparison for a fruitcake'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'YANG', number: 18, clue: 'I Ching principle'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'SLOP', number: 19, clue: 'Funkadelic\'s "Cosmic ___"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'DRE', number: 20, clue: 'Cube\'s former groupmate'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'LAINK', number: 21, clue: 'Reality show starring Kat Von D'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'DIESE', number: 22, clue: '"O Freunde, nicht ___ T&#246;ne! (opening line to Beethoven\'s Ninth)'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 4, col: 11, dir: 'Down', answer: 'DEBTS', number: 22, clue: 'They might be consolidated'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'PENN', number: 23, clue: 'Badgley of "Gossip Girl"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'PUT', number: 23, clue: 'Place'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'BLEEPS', number: 24, clue: 'Censors'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'LEIF', number: 25, clue: 'Ericson with a U.S. national holiday in his honor'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 6, col: 3, dir: 'Across', answer: 'JUDGEJOEBROWN', number: 26, clue: '"Texas Justice" alternative'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'JAMESBEARD', number: 26, clue: 'Cook for whom a culinary award is named'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'JOHNS', number: 27, clue: 'Bawdyhouse clients'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'NEYO', number: 28, clue: 'One-named R&B singer with "Give Me Everything"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'ATAT', number: 29, clue: '"Empire Strikes Back" attack bot'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 7, col: 1, dir: 'Down', answer: 'ARID', number: 29, clue: 'Like the air on planes'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'TAKEAVOTE', number: 30, clue: 'Proceed democratically'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'ONIT', number: 31, clue: 'Taking care of business'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'ROE', number: 32, clue: 'Salty bar order'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'RAM', number: 33, clue: 'He does it all for ewe'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'TVCHEFS', number: 34, clue: 'Names at the end of 17-, 26-, 41-, and 55-Across'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'TWIST', number: 34, clue: 'Lime quantity'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'VANE', number: 35, clue: 'It\'ll tell you which way the wind blows'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'CRYSTALS', number: 36, clue: 'Mystic\'s charms'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'TRY', number: 37, clue: 'Sip, say'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'IKE', number: 38, clue: 'Kyle\'s little brother on "South Park"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'WARN', number: 39, clue: 'Raise a red flag'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'REDO', number: 40, clue: 'Execute again'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'RLS', number: 40, clue: 'Disease associated with jerks: Abbr.'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'DESTINYSCHILD', number: 41, clue: 'Group called Girls Tyme when they lost on "Star Search" in 1993'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'TURTLE', number: 42, clue: 'Michelangelo or Donatello, e.g.'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'CASHED', number: 43, clue: 'Redeemed, as a check'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'HALO', number: 44, clue: 'Los Angeles Angel, colloquially'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'IHADTO', number: 45, clue: '"There was no other choice!"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 11, col: 2, dir: 'Across', answer: 'ABUSES', number: 46, clue: 'Eats in excess, as mushrooms'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'AAHS', number: 47, clue: 'Sounds after sitting down, at last'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'AVERT', number: 48, clue: 'Duck'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'ABCB', number: 48, clue: '"The Rime of the Ancient Mariner" rhyme scheme'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'TESLA', number: 49, clue: 'Glam band that covered "Signs" in 1990'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'ETTE', number: 50, clue: 'Kitchen addition?'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ING', number: 51, clue: 'NYC Marathon sponsor'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'IROC', number: 51, clue: '\'80s muscle car'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'NAPA', number: 52, clue: 'California wine country city'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'GYMS', number: 53, clue: 'Toners\' places?'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BOAT', number: 54, clue: 'It might go wherever the wind takes it'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'CATHODERAY', number: 55, clue: 'Vacuum tube type'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'CAB', number: 55, clue: '"Cash ___"'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'EWR', number: 56, clue: 'Airport stop on New Jersey Transit, briefly'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'CTRL', number: 57, clue: 'Key in many shortcuts, for short'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ALTE', number: 58, clue: 'Aged Hamburger?'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'TWOPM', number: 59, clue: 'Latish lunch time'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'BEDE', number: 60, clue: '"Venerable" English writer'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'BSED', number: 61, clue: 'Spoke above one\'s pay grade'))
clues_Prime_Time_Panhandlers_CR_2_2_12.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ORCAS', number: 62, clue: 'Black-and-white ocean predators'))
Puzzle.create(title: 'Prime Time Panhandlers', grid: 'FIVEK.ANNA.ETCH|AGILE.LOEW.AERO|HOCKEYPUCK.SLOP|DRE.LAINK.DIESE|...PENN.BLEEPS.|..JUDGEJOEBROWN|ATAT...ONIT.ROE|RAM.TVCHEFS.TRY|IKE.WARN...REDO|DESTINYSCHILD..|.ABUSES.AAHS...|AVERT.TESLA.ING|BOAT.CATHODERAY|CTRL.ALTE.TWOPM|BEDE.BSED.ORCAS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/2/2', entries: clues_Prime_Time_Panhandlers_CR_2_2_12)
