clues_Signs_of_Stress_CR_7_26_12 = Array.new
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'GERONIMO', number: 1, clue: 'Parachutist\'s cry'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'GALA', number: 1, clue: 'Big shindig'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ELAL', number: 2, clue: 'Company on the Tel Aviv Stock Exchange'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ROMA', number: 3, clue: 'Tomato that does not come from the capital of Italy'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OPENMRI', number: 4, clue: 'Medical scanning option for the claustrophobic'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'NED', number: 5, clue: 'Stark of "Game of Thrones"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'ICU', number: 6, clue: 'Shock treatment site, briefly?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'MIC', number: 7, clue: 'What an MC grips'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'OAK', number: 8, clue: '"Mighty" tree'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 10, dir: 'Across', answer: 'APHIDS', number: 9, clue: 'Bugs that bug farmers'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'AGEONE', number: 9, clue: 'When a baby might say his first word'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'POSTE', number: 10, clue: 'Mail in Paris'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'HASHTAG', number: 11, clue: 'Twitter trend symbol'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'ILIA', number: 12, clue: 'Hip bones'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'DION', number: 13, clue: 'Singer who redefined double standards by recording both "Runaround Sue" and "The Wanderer" in 1961'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'SEND', number: 14, clue: 'Ship'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ALOPECIA', number: 15, clue: 'Condition for Homer'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 2, col: 10, dir: 'Across', answer: 'GOALIE', number: 16, clue: 'Net security personnel?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'LAMEDUCKSESSION', number: 17, clue: 'Discussion with one\'s therapist about a sparkly gold bath toy?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 3, col: 9, dir: 'Down', answer: 'SHES', number: 18, clue: 'Joy Division\'s "___ Lost Control"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'ALAN', number: 19, clue: 'Colmes of "Hannity & Colmes"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 4, col: 9, dir: 'Across', answer: 'HOTHAND', number: 20, clue: 'Imaginary craps advantage'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'MTA', number: 21, clue: 'NYC transit org. created in Robert Moses\'s waning years'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 5, col: 5, dir: 'Down', answer: 'TENOF', number: 22, clue: 'Just before the hour'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 5, col: 6, dir: 'Down', answer: 'AXEL', number: 23, clue: 'Olympic leap for Evan Lysacek'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 5, col: 8, dir: 'Across', answer: 'TENET', number: 24, clue: 'Basic belief'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 5, col: 8, dir: 'Down', answer: 'TORMENT', number: 24, clue: 'Bully mercilessly'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'OVEREXPOSE', number: 25, clue: 'Totally tired of yellow journalism?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'ODIST', number: 25, clue: 'Praiseful poet'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'VODKA', number: 26, clue: 'Skyy, for one'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'EMAIL', number: 27, clue: 'Missive from a smartphone, say'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 7, dir: 'Down', answer: 'PEE', number: 28, clue: 'Number one in bowls?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'ARFS', number: 29, clue: 'Sounds frowned upon at dog shows'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 13, dir: 'Down', answer: 'RISES', number: 30, clue: '"The Dark Knight ___"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'FLUTE', number: 31, clue: 'Champagne glass'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'SEUSS', number: 32, clue: 'Dr. who created Horton'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'DOMINEER', number: 33, clue: 'Tyrannize'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 7, col: 11, dir: 'Across', answer: 'AGILE', number: 34, clue: 'Like a dancer or an antelope'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'ASTRO', number: 34, clue: 'NL player certain to be traded midseason, if he\'s any good'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'IDA', number: 35, clue: '___ Mae Martinez (early female pro wrestler)'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'OLEMISS', number: 36, clue: '"You go, se&#241;orita!"?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 8, col: 9, dir: 'Down', answer: 'IPS', number: 37, clue: 'Online ID numbers'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 8, col: 10, dir: 'Down', answer: 'SINS', number: 38, clue: 'Confessional topics'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'SUU', number: 39, clue: 'Burmese activist Aung San ___Kyi'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'SKIFF', number: 40, clue: 'Sailing craft'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'FEELERS', number: 41, clue: 'Antennae'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 9, col: 8, dir: 'Across', answer: 'EPITHETS', number: 42, clue: 'The Great and the Fat, e.g.'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'HOUSEMD', number: 43, clue: 'Hugh Laurie role'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'TALE', number: 44, clue: 'Legend'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'GUNSNROSES', number: 45, clue: 'The NRA\'s official winery?'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 10, col: 6, dir: 'Down', answer: 'GENTLY', number: 45, clue: '"How do I put this ___?"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 10, col: 7, dir: 'Down', answer: 'URGE', number: 46, clue: 'Compulsion'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 11, col: 4, dir: 'Across', answer: 'EBERT', number: 47, clue: 'Critic who gave "Police Academy" zero stars'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'BICEP', number: 48, clue: 'Feature of a Flex magazine spread'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 11, col: 10, dir: 'Across', answer: 'SOU', number: 49, clue: 'Piddling amount'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'SAPLING', number: 50, clue: 'Small palm, say'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'SALK', number: 50, clue: 'Jonas who tested the polio vaccine on himself'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'AFAR', number: 51, clue: 'A great distance'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 3, dir: 'Down', answer: 'PFUI', number: 52, clue: '"Bah, humbug!"'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 12, dir: 'Across', answer: 'SKAT', number: 53, clue: 'Card game with 32 cards'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'KNEW', number: 54, clue: 'Had sex with, biblically'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'ATRA', number: 55, clue: 'Trac II alternative'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'TSAR', number: 56, clue: '2009 Russian film about Ivan the Terrible'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AFFECTEDACCENTS', number: 57, clue: 'Pompous pretensions, and this puzzle\'s theme'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 13, col: 8, dir: 'Down', answer: 'DOW', number: 58, clue: 'Market index name'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'ANO', number: 59, clue: 'Sol revolution'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 13, col: 10, dir: 'Down', answer: 'CCR', number: 60, clue: '"Proud Mary" quartet, briefly'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 13, col: 11, dir: 'Down', answer: 'CAL', number: 61, clue: 'Occupy ___ (West Coast tuition hike protests)'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'LAUREL', number: 62, clue: 'Hardy\'s partner'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 14, col: 8, dir: 'Across', answer: 'ONCAMERA', number: 63, clue: 'Like celebrities, much of the time'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'KRISPY', number: 64, clue: '___ Kreme'))
clues_Signs_of_Stress_CR_7_26_12.push(Entry.create(row: 15, col: 8, dir: 'Across', answer: 'WORLDWAR', number: 65, clue: 'A third one is the subject of many science fiction stories'))
Puzzle.create(title: 'Signs of Stress', grid: 'GERONIMO.APHIDS|ALOPECIA.GOALIE|LAMEDUCKSESSION|ALAN....HOTHAND|...MTA.TENET...|OVEREXPOSE.ARFS|DOMINEER..AGILE|IDA.OLEMISS.SUU|SKIFF..EPITHETS|TALE.GUNSNROSES|...EBERT.SOU...|SAPLING....SKAT|AFFECTEDACCENTS|LAUREL.ONCAMERA|KRISPY.WORLDWAR', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/7/26', entries: clues_Signs_of_Stress_CR_7_26_12)
