clues_Staying_Loose_CR_11_15_12 = Array.new
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'DOJO', number: 1, clue: '"Karate Kid" locale'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'DIMS', number: 1, clue: 'Lowers'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'OMOO', number: 2, clue: 'Melville novel about Tahiti'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'JUDI', number: 3, clue: 'Dench who plays M'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'OPERATE', number: 4, clue: 'Do a hip job, say?'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 6, dir: 'Across', answer: 'LETS', number: 5, clue: '"Sounds like a plan!"'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 6, dir: 'Down', answer: 'LATETO', number: 5, clue: 'Missing, perhaps'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'ELO', number: 6, clue: 'Classic rock band that sort of reunited in 2012'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'TOWEL', number: 7, clue: 'Hot handout at a Japanese restaurant'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'SUNRA', number: 8, clue: 'Jazz legend born on Saturn (or so he said)'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 11, dir: 'Across', answer: 'AWOKE', number: 9, clue: '"As Gregor Samsa ___ one morning ..."'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'ARF', number: 9, clue: 'Sound a child might imitate'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'WEEZER', number: 10, clue: '"Buddy Holly" band'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'OPRAH', number: 11, clue: 'Hostess with a television empire'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'KEANU', number: 12, clue: 'Reeves in a "sad" meme'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ELLEN', number: 13, clue: 'Hostess with a television empire'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'IMUP', number: 14, clue: 'Words from one about to bat'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'ALOU', number: 15, clue: 'Matty, Jesus, Felipe, or Moises'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 2, col: 11, dir: 'Across', answer: 'REPEL', number: 16, clue: 'Keep away'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'MODELTOWN', number: 17, clue: 'Planned community'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'LETO', number: 18, clue: 'He played Pre'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 3, col: 11, dir: 'Across', answer: 'FERAL', number: 19, clue: 'Raised by wolves, say'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'SOIREE', number: 20, clue: 'Shindig'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 4, col: 8, dir: 'Across', answer: 'ERS', number: 21, clue: 'TV drama sites'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 4, col: 10, dir: 'Down', answer: 'STATE', number: 22, clue: 'Washington, e.g.'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'ZANE', number: 23, clue: 'Billy who played the bad guy in "Titanic"'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 5, col: 4, dir: 'Across', answer: 'ATTILATHEHUN', number: 24, clue: 'Fifth-century king renowned for his cruelty'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 5, col: 7, dir: 'Down', answer: 'IPASS', number: 25, clue: '"Check," in poker'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'HISS', number: 26, clue: '[You smell like some other cat and I don\'t like you]'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'PHOTOOP', number: 27, clue: 'Moment of mugging'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 6, col: 1, dir: 'Down', answer: 'PLAX', number: 27, clue: 'Pre-brushing brand'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 6, col: 2, dir: 'Down', answer: 'HOAX', number: 28, clue: 'Snopes subject'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 6, col: 3, dir: 'Down', answer: 'OVAL', number: 29, clue: 'Face shape'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'AIR', number: 30, clue: 'Something to come up for'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'LOVE', number: 31, clue: 'Certain human drive'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'ABUTS', number: 32, clue: 'Sits next to'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'BCE', number: 33, clue: 'Pre-A.D.'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'ULRIC', number: 34, clue: 'German patron saint against mice and moles'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 13, dir: 'Across', answer: 'VHF', number: 35, clue: 'TV channels 2 to 13, once'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 13, dir: 'Down', answer: 'VOID', number: 35, clue: 'Word on a check'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 14, dir: 'Down', answer: 'HUNG', number: 36, clue: 'Big'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 7, col: 15, dir: 'Down', answer: 'FREE', number: 37, clue: 'Not booked'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'AAA', number: 38, clue: 'Ken Griffey Jr. skipped it on his way to the majors'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 8, col: 5, dir: 'Across', answer: 'MUSCLES', number: 39, clue: 'Stretchable things stretched across 17-, 24-, 49-, and 62-Across'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'MULL', number: 39, clue: 'Cogitate'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'UNION', number: 40, clue: 'Striking people, at times'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'OUR', number: 41, clue: '"___ Idiot Brother" (Paul Rudd comedy)'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'XXL', number: 42, clue: 'Magazine that profiles MCs'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 9, col: 5, dir: 'Across', answer: 'UNSER', number: 43, clue: 'Racing family with a museum in New Mexico'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 9, col: 12, dir: 'Across', answer: 'SINE', number: 44, clue: 'Math wave'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'SAZERAC', number: 44, clue: 'Old-fashioned, in New Orleans'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 10, col: 4, dir: 'Across', answer: 'MLI', number: 45, clue: 'Year in the life of William the Conqueror'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 10, col: 4, dir: 'Down', answer: 'METIME', number: 45, clue: 'Break that might involve a pint of ice cream'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 10, col: 9, dir: 'Across', answer: 'IDBADGE', number: 46, clue: 'One might get you in the door'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'DREADS', number: 47, clue: 'Coiled locks'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'BUND', number: 48, clue: 'German political group'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'PENELOPECRUZ', number: 49, clue: 'Best Supporting Actress of 2008'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 1, dir: 'Down', answer: 'PABST', number: 49, clue: 'Hipster draft pick?'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 2, dir: 'Down', answer: 'EBOLA', number: 50, clue: 'Virus that inspired "Outbreak"'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 3, dir: 'Down', answer: 'NEXUS', number: 51, clue: 'Middle'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'PEACE', number: 52, clue: 'One meaning of "aloha"'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'ESQUE', number: 53, clue: '-ish'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'ABET', number: 54, clue: 'Help create a racket, say'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 6, dir: 'Across', answer: 'NES', number: 55, clue: '"Konami code" game platform'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 10, dir: 'Across', answer: 'ENERGY', number: 56, clue: 'What some bars offer?'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 13, dir: 'Down', answer: 'RANI', number: 57, clue: 'Title in Indian restaurant names'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 14, dir: 'Down', answer: 'GMAT', number: 58, clue: 'Bus. student\'s exam'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 12, col: 15, dir: 'Down', answer: 'YALE', number: 59, clue: 'Where Anderson Cooper went to school'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'BOXIN', number: 60, clue: 'Trap'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 13, col: 5, dir: 'Down', answer: 'NPR', number: 61, clue: '"All Things Considered" org.'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 13, col: 7, dir: 'Across', answer: 'AQUADRAMA', number: 62, clue: 'Nineteenth-century stage genre involving watery sets'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 13, col: 9, dir: 'Down', answer: 'URL', number: 63, clue: 'Something to bookmark'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'SLUMP', number: 64, clue: 'Bad spell at the plate'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 14, col: 7, dir: 'Across', answer: 'CURD', number: 65, clue: 'Tofu, e.g.'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'ANAL', number: 66, clue: 'Retentive, in a way'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'TASER', number: 67, clue: 'Acronym for a modern police weapon'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 15, col: 7, dir: 'Across', answer: 'EELS', number: 68, clue: 'Consumers of crustaceans'))
clues_Staying_Loose_CR_11_15_12.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'CITE', number: 69, clue: 'Put in a footnote'))
Puzzle.create(title: 'Staying Loose', grid: 'DOJO.LETS.AWOKE|IMUP.ALOU.REPEL|MODELTOWN.FERAL|SOIREE.ERS.ZANE|...ATTILATHEHUN|PHOTOOP..AIR...|LOVE..ABUTS.VHF|AAA.MUSCLES.OUR|XXL.UNSER..SINE|...MLI..IDBADGE|PENELOPECRUZ...|ABET.NES.ENERGY|BOXIN.AQUADRAMA|SLUMP.CURD.ANAL|TASER.EELS.CITE', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/11/15', entries: clues_Staying_Loose_CR_11_15_12)
