clues_Switching_Positions_CR_5_3_12 = Array.new
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'JONAS', number: 1, clue: 'Joe, Kevin, or Nick with such soft white cheeks'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'JEB', number: 1, clue: 'A Bush'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ORE', number: 2, clue: '"Portlandia" state: Abbr.'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'NBA', number: 3, clue: 'Org. whose champion is determined at the beginning of each season by a cackling David Stern'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'AIRSEA', number: 4, clue: 'Flexible, as a shipping company'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'SUBPOP', number: 5, clue: 'Nirvana label, for a while'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 8, dir: 'Across', answer: 'SEVE', number: 6, clue: 'Golf legend Ballesteros'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'SALTI', number: 6, clue: 'Treaty signed by Nixon and Brezhnev'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'EMIRS', number: 7, clue: 'Muslim movers-and-shakers'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'VENAE', number: 8, clue: 'Some blood vessels, formally'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'EXGI', number: 9, clue: 'Military vet'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'MTV', number: 10, clue: 'Channel with VJs'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'METIME', number: 10, clue: 'Period to turn off one\'s phone and catch up on TV, say'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'TOWNIE', number: 11, clue: 'Off-campus local'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'VSIGNS', number: 12, clue: '"We did it!" hand gestures'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'ERBIUM', number: 13, clue: 'Element used in nuclear technology'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'MAO', number: 14, clue: 'Chinese chairman before Deng'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 2, col: 8, dir: 'Across', answer: 'AMEX', number: 15, clue: 'Credit card with a Roman gladiator logo, briefly'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'EOS', number: 16, clue: 'Morning dew is her tears, in mythology'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BEARBALLING', number: 17, clue: 'Grizzly hoops?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 3, col: 7, dir: 'Down', answer: 'LTR', number: 18, clue: 'Something to send to your congressman, briefly'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'TWI', number: 19, clue: 'Prefix for light'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'SPOTTRAINING', number: 20, clue: 'Obedience school objective?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'NICKI', number: 21, clue: 'Minaj of strange outfits'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ROMEO', number: 22, clue: 'Master P\'s son who used to have "Lil\'" in front of his name'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'RCA', number: 22, clue: 'Big name in phonographs'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'OHOH', number: 23, clue: '"Please call on me, please!"'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'MELO', number: 24, clue: 'Linsanity\'s teammate'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 7, dir: 'Across', answer: 'RISE', number: 25, clue: 'Get up'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 5, col: 12, dir: 'Across', answer: 'IMIN', number: 26, clue: 'Positive response to a recruiter'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'CHEAPO', number: 27, clue: 'Cut-rate'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 6, col: 6, dir: 'Down', answer: 'ODES', number: 28, clue: 'Lyric poems'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 6, col: 11, dir: 'Across', answer: 'ICEES', number: 29, clue: 'Nutrition-free beverages'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 6, col: 11, dir: 'Down', answer: 'ICH', number: 29, clue: 'Bundestag pronoun'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'AOL', number: 30, clue: 'Pass&#233; email address'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 6, dir: 'Across', answer: 'DADROCK', number: 31, clue: 'Don Henley or Tom Petty songs, e.g.'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'ARK', number: 32, clue: 'Torah\'s place'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'DOI', number: 33, clue: '"___ really have to keep explaining this to you?"'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'RUE', number: 34, clue: 'French way?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 7, col: 10, dir: 'Down', answer: 'OGRE', number: 35, clue: 'Man-eating giant'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'HOUSEROUGHING', number: 36, clue: 'Hockey penalty for members of the Committee on Ways & Means?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 8, col: 4, dir: 'Down', answer: 'URGED', number: 37, clue: 'Implored'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 8, col: 5, dir: 'Down', answer: 'SIN', number: 38, clue: '___ City'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 8, col: 13, dir: 'Down', answer: 'NEIN', number: 39, clue: 'Non, across the Rhine'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'GLEE', number: 40, clue: 'Show with choreography'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 9, col: 4, dir: 'Across', answer: 'RISKIER', number: 41, clue: 'Having more pitfalls'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 9, col: 13, dir: 'Across', answer: 'ELM', number: 42, clue: 'One might grow to over 100 feet'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'MRS', number: 43, clue: 'Title for Fields or Dash'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'FEIGN', number: 44, clue: 'Fake'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'FATJOE', number: 44, clue: 'Outsized Puerto Rican rapper'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ERROLL', number: 45, clue: 'Jazz pianist Garner'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 3, dir: 'Down', answer: 'ISABEL', number: 46, clue: 'Deadly 2003 hurricane'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'EASIER', number: 47, clue: 'More of a cinch'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 11, dir: 'Down', answer: 'ANNOYS', number: 48, clue: 'Keeps poking, say'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 10, col: 12, dir: 'Down', answer: 'SIGNON', number: 49, clue: 'Join up'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ARSE', number: 50, clue: 'One might be sodomised'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 6, dir: 'Across', answer: 'ALUM', number: 51, clue: 'Person in old yearbooks'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 6, dir: 'Down', answer: 'ABHOR', number: 51, clue: 'Be intolerant of'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'LOINS', number: 52, clue: 'Junk area?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'UNLET', number: 53, clue: 'Still for rent'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'MDL', number: 54, clue: 'Year in the life of Nostradamus'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 11, col: 11, dir: 'Across', answer: 'NINES', number: 55, clue: 'Go Fish request'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'TRADEBONDING', number: 56, clue: 'Retreat activity for investment bankers?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 12, col: 5, dir: 'Down', answer: 'ECCE', number: 57, clue: '"___ homo" (Pontius Pilate phrase)'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 12, col: 10, dir: 'Down', answer: 'IBM', number: 58, clue: '"Smarter Planet" company'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'JOB', number: 59, clue: 'What a recent grad might hunt for'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'CHILLBONING', number: 60, clue: 'Slow sex?'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'IPA', number: 61, clue: 'Content of a linguist\'s chart, for short'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'NIP', number: 62, clue: '1/3rd of a pint, in alcohol measurements'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'GAS', number: 63, clue: 'Solid alternative'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'OLE', number: 64, clue: 'Word repeated in a common football chant'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'CONE', number: 65, clue: 'Parking spot blocker'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 14, col: 10, dir: 'Across', answer: 'MYOPIA', number: 66, clue: 'Magoo\'s condition'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ELL', number: 67, clue: 'Angled pipe'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'ERST', number: 68, clue: 'Formerly, once upon a time'))
clues_Switching_Positions_CR_5_3_12.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'SNAPS', number: 69, clue: 'Loses one\'s shit'))
Puzzle.create(title: 'Switching Positions', grid: 'JONAS..SEVE.MTV|ERBIUM.AMEX.EOS|BEARBALLING.TWI|...SPOTTRAINING|ROMEO.RISE.IMIN|CHEAPO....ICEES|AOL..DADROCK...|.HOUSEROUGHING.|...RISKIER..ELM|FEIGN....EASIER|ARSE.ALUM.NINES|TRADEBONDING...|JOB.CHILLBONING|OLE.CONE.MYOPIA|ELL.ERST..SNAPS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/5/3', entries: clues_Switching_Positions_CR_5_3_12)
