clues_Whats_My_Line_CR_7_12_12 = Array.new
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'AWOL', number: 1, clue: 'Desert, with "go"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'ALOAD', number: 1, clue: '"That\'s ___ of crap"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'WUSHU', number: 2, clue: 'Chinese martial arts form'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'ORCAS', number: 3, clue: 'Black-and-white crossword staples'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'LEA', number: 4, clue: 'Michele whose Twitter describes her as a "Streisand Worshiper"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'TVMA', number: 5, clue: '"Breaking Bad" rating'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'THIRD', number: 5, clue: 'Down before a punt, perhaps'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'VILLI', number: 6, clue: 'Intestinal wall projections'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'MEDEA', number: 7, clue: 'Jason\'s bride'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'ADE', number: 8, clue: 'Roadside beverage'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 12, dir: 'Across', answer: 'STYE', number: 9, clue: 'Lid bump'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 12, dir: 'Down', answer: 'SEVENAM', number: 9, clue: 'When "Today" starts'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'TWEEDCOAT', number: 10, clue: 'Bit of "Mad Men" attire'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'YALL', number: 11, clue: 'Yinz, south of Pittsburgh'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'ENDS', number: 12, clue: 'Means may justify them'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'LURE', number: 13, clue: 'One might attract mullets'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 2, col: 6, dir: 'Across', answer: 'SHIED', number: 14, clue: 'Drew back, with "away"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 2, col: 6, dir: 'Down', answer: 'SWANS', number: 14, clue: 'Birds that are rarely black'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 2, col: 12, dir: 'Across', answer: 'EWAN', number: 15, clue: 'McGregor who turned down the role of James Bond'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'OSCARWILDE', number: 16, clue: 'Author who doesn\'t maintain an Academy Awards fansite'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 3, col: 5, dir: 'Down', answer: 'REIGN', number: 17, clue: 'Time on the throne'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 3, col: 12, dir: 'Across', answer: 'VELD', number: 18, clue: 'South African plain'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 4, col: 1, dir: 'Across', answer: 'AHA', number: 19, clue: '"So that\'s your game!"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 4, col: 5, dir: 'Across', answer: 'EARLE', number: 20, clue: 'Lefty country musician Steve'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 4, col: 12, dir: 'Across', answer: 'EELS', number: 21, clue: 'Ribbon-like fish'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'DUSTINDIAMOND', number: 22, clue: 'Actor who doesn\'t polish jewelry'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 5, col: 4, dir: 'Down', answer: 'TOO', number: 23, clue: 'Outlandishly'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'MEDS', number: 24, clue: 'Daily doses, say'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 5, col: 11, dir: 'Down', answer: 'OXY', number: 25, clue: 'Brand on one\'s face?'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 6, col: 4, dir: 'Across', answer: 'OGS', number: 26, clue: 'Tough dudes, in \'90s hip-hop slang'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 6, col: 10, dir: 'Across', answer: 'EXACTA', number: 27, clue: 'Two-horse bet'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 6, col: 14, dir: 'Down', answer: 'TSKS', number: 28, clue: 'Chidings'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 6, col: 15, dir: 'Down', answer: 'ASS', number: 29, clue: 'Can'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 2, dir: 'Across', answer: 'CMON', number: 30, clue: '"You are so obviously lying to me"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 2, dir: 'Down', answer: 'CRIP', number: 30, clue: 'Person carrying on a Blood feud?'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 3, dir: 'Down', answer: 'MAKEJOKES', number: 31, clue: 'Try to lighten the mood, say'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 7, dir: 'Across', answer: 'RANDYMOSS', number: 32, clue: 'Wide receiver who doesn\'t study plant reproduction'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 7, dir: 'Down', answer: 'RID', number: 32, clue: 'Unburdened'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 8, dir: 'Down', answer: 'AVG', number: 33, clue: 'Hits over ABs'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 7, col: 9, dir: 'Down', answer: 'NAE', number: 34, clue: '"If It\'s ___ Scottish, It\'s Crap!"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 8, col: 1, dir: 'Across', answer: 'ERA', number: 35, clue: 'Word after progressive or dead-ball'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 8, col: 1, dir: 'Down', answer: 'EMA', number: 35, clue: '"Past Life Martyred Saints" musician'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 8, col: 6, dir: 'Across', answer: 'DIVAS', number: 36, clue: 'Queen bees'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'DUNN', number: 36, clue: 'Country music partner of Brooks'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 8, col: 13, dir: 'Across', answer: 'AKS', number: 37, clue: 'Common USSR guns'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 1, dir: 'Across', answer: 'MIKEJUDGE', number: 38, clue: 'Writer/director who doesn\'t test audio equipment'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 4, dir: 'Down', answer: 'EMOBAND', number: 39, clue: 'Death Cab for Cutie, e.g.'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 5, dir: 'Down', answer: 'JAH', number: 40, clue: 'Rastafarian Jesus'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'SITS', number: 41, clue: 'Uses a stool'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 11, dir: 'Down', answer: 'SEEYA', number: 41, clue: '"TTFN"'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 9, col: 12, dir: 'Down', answer: 'IAN', number: 42, clue: '"Love Will Tear Us Apart" singer Curtis'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'APEMAN', number: 43, clue: 'The missing link, e.g.'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 10, col: 10, dir: 'Across', answer: 'SEA', number: 44, clue: 'Body governed by UN law'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'SPEWS', number: 44, clue: 'Erupts'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 3, dir: 'Across', answer: 'JOHNCARPENTER', number: 45, clue: 'Director who doesn\'t build wooden toilets'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 7, dir: 'Down', answer: 'CHARS', number: 46, clue: 'Makes black'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 8, dir: 'Down', answer: 'AORTA', number: 47, clue: 'Artery described by Gray'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 9, dir: 'Down', answer: 'ROKER', number: 48, clue: 'Al on The Weather Channel'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 13, dir: 'Down', answer: 'TONTO', number: 49, clue: 'Cringeworthily racist "Lone Ranger" depiction'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 14, dir: 'Down', answer: 'ENERO', number: 50, clue: 'Barcelona\'s coldest month'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 11, col: 15, dir: 'Down', answer: 'RERAN', number: 51, clue: 'Showed in syndication'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'DOOB', number: 52, clue: 'Sparked thing'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 12, col: 1, dir: 'Down', answer: 'DAMP', number: 52, clue: 'In need of a dehumidifier'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 12, col: 2, dir: 'Down', answer: 'ONIT', number: 53, clue: 'Ahead of the game'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 12, col: 7, dir: 'Across', answer: 'HOOEY', number: 54, clue: 'Bullshit'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 12, col: 13, dir: 'Across', answer: 'ONE', number: 55, clue: 'Bill below five'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'ANKA', number: 56, clue: '1950s-\'60s heartthrob Paul'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 13, col: 6, dir: 'Across', answer: 'MARKWARNER', number: 57, clue: 'Senator who isn\'t a strict schoolteacher'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'MET', number: 57, clue: 'NYC museum that contains the Temple of Dendur'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 13, col: 12, dir: 'Down', answer: 'RXS', number: 58, clue: 'Scripts for drugs'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'MIEN', number: 59, clue: 'Way of carrying oneself'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 14, col: 6, dir: 'Across', answer: 'ERTES', number: 60, clue: 'Some Ziegfeld Follies fashion designs'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 14, col: 12, dir: 'Across', answer: 'XTRA', number: 61, clue: 'More, minimally'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'PTSD', number: 62, clue: 'Vet\'s affliction'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 15, col: 6, dir: 'Across', answer: 'TSAR', number: 63, clue: 'Descriptor for a domineering person'))
clues_Whats_My_Line_CR_7_12_12.push(Entry.create(row: 15, col: 12, dir: 'Across', answer: 'SOON', number: 64, clue: 'Within minutes, say'))
Puzzle.create(title: 'What\'s My Line?', grid: 'AWOL..TVMA.STYE|LURE.SHIED.EWAN|OSCARWILDE.VELD|AHA.EARLE..EELS|DUSTINDIAMOND..|...OGS...EXACTA|.CMON.RANDYMOSS|ERA..DIVAS..AKS|MIKEJUDGE.SITS.|APEMAN...SEA...|..JOHNCARPENTER|DOOB..HOOEY.ONE|ANKA.MARKWARNER|MIEN.ERTES.XTRA|PTSD.TSAR..SOON', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/7/12', entries: clues_Whats_My_Line_CR_7_12_12)
