clues_Yo_Yo_Diet_CR_7_19_12 = Array.new
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 1, dir: 'Across', answer: 'PASTA', number: 1, clue: 'Elbows on the table, say?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 1, dir: 'Down', answer: 'PCB', number: 1, clue: 'Hudson River pollutant'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 2, dir: 'Down', answer: 'ARI', number: 2, clue: 'State with controversial immigration laws: Abbr.'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 3, dir: 'Down', answer: 'SAL', number: 3, clue: '"On the Road" narrator Paradise'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 4, dir: 'Down', answer: 'TIBBS', number: 4, clue: '"They Call Me MISTER ___!" (1970 film)'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 5, dir: 'Down', answer: 'AGORA', number: 5, clue: 'Ruined Greek market?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 7, dir: 'Across', answer: 'THUMP', number: 6, clue: 'Defeat soundly'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 7, dir: 'Down', answer: 'TOPTEN', number: 6, clue: 'Nightly Letterman list'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 8, dir: 'Down', answer: 'HUHS', number: 7, clue: '"What?" alternatives'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 9, dir: 'Down', answer: 'UTE', number: 8, clue: 'Tribe with a coyote and duck legend'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 10, dir: 'Down', answer: 'MIR', number: 9, clue: 'Space station that operated on Moscow time'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 11, dir: 'Down', answer: 'PEETA', number: 10, clue: 'Katniss\'s partner from District 12'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 13, dir: 'Across', answer: 'LID', number: 11, clue: 'Pot part'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 13, dir: 'Down', answer: 'LEATHERNECK', number: 11, clue: 'Marine'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 14, dir: 'Down', answer: 'IVTUBE', number: 12, clue: 'Drug connection?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 1, col: 15, dir: 'Down', answer: 'DOESUP', number: 13, clue: 'Makes more schmancy'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 2, col: 1, dir: 'Across', answer: 'CRAIG', number: 14, clue: 'Newmark with an online list'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 2, col: 7, dir: 'Across', answer: 'OUTIE', number: 15, clue: 'Unusual belly protrusion'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 2, col: 13, dir: 'Across', answer: 'EVO', number: 16, clue: 'Leftist president Morales'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 3, col: 1, dir: 'Across', answer: 'BILBOSPHERE', number: 17, clue: 'Middle-earth?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 3, col: 6, dir: 'Down', answer: 'SARS', number: 18, clue: 'WHO challenge of the early \'00s'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 3, col: 13, dir: 'Across', answer: 'ATE', number: 19, clue: 'Fueled up, so to speak'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 4, col: 4, dir: 'Across', answer: 'BRATS', number: 20, clue: 'Cheese state sausages'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 4, col: 11, dir: 'Across', answer: 'TUTUS', number: 21, clue: 'Everyday outfits for some little kids'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 4, col: 12, dir: 'Down', answer: 'USSOIL', number: 22, clue: 'Where the FBI operates'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 1, dir: 'Across', answer: 'ODDSARE', number: 23, clue: '"More likely than not ..."'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 1, dir: 'Down', answer: 'ODB', number: 23, clue: '"Shimmy Shimmy Ya" rapper'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 2, dir: 'Down', answer: 'DULL', number: 24, clue: 'Unlikely to cut'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 3, dir: 'Down', answer: 'DEALBREAKER', number: 25, clue: 'Fatal relationship problem'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 9, dir: 'Across', answer: 'FLASHBU', number: 26, clue: 'Put on a show for a Beantown campus?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 9, dir: 'Down', answer: 'FRAU', number: 26, clue: 'Farbissina\'s "Austin Powers" title'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 5, col: 10, dir: 'Down', answer: 'LENI', number: 27, clue: '"Triumph of the Will" filmmaker Riefenstahl'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 6, col: 1, dir: 'Across', answer: 'DUE', number: 28, clue: 'Set to deliver (on)'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 6, col: 6, dir: 'Across', answer: 'SNARE', number: 29, clue: 'Tom\'s neighbor'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 6, col: 8, dir: 'Down', answer: 'ACCRA', number: 30, clue: 'Ghanaian metropolis'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 6, col: 12, dir: 'Across', answer: 'SEEP', number: 31, clue: 'Pass through pores'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 7, col: 1, dir: 'Across', answer: 'BLAHS', number: 32, clue: 'Winter ennui, e.g.'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 7, col: 4, dir: 'Down', answer: 'HBOMBS', number: 33, clue: 'Thermonuclear threats'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 7, col: 5, dir: 'Down', answer: 'SEX', number: 34, clue: 'Subject of much magazine advice'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 7, col: 8, dir: 'Across', answer: 'CANTOR', number: 35, clue: 'Synagogue singer'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 7, col: 11, dir: 'Down', answer: 'TSA', number: 36, clue: 'Pat-down agcy.'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 8, col: 2, dir: 'Across', answer: 'LLBEANCUISINE', number: 37, clue: 'Meals shipped from Maine with every fleece vest or backpack purchased?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 8, col: 6, dir: 'Down', answer: 'ACDC', number: 38, clue: 'Group with a tribute band called Live Wire'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 8, col: 7, dir: 'Down', answer: 'NARK', number: 39, clue: 'One might snitch to a constable'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 8, col: 14, dir: 'Down', answer: 'ERIE', number: 40, clue: 'Source of lake effect snow in Cleveland'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 9, col: 3, dir: 'Across', answer: 'BOXCAR', number: 41, clue: 'Hobo\'s home'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 9, col: 11, dir: 'Across', answer: 'ALERT', number: 42, clue: 'Keeping one\'s radar up'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 9, col: 15, dir: 'Down', answer: 'TOY', number: 43, clue: '"The dog is not a ___!"'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 1, dir: 'Across', answer: 'FARM', number: 44, clue: '___-to-table'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 1, dir: 'Down', answer: 'FIGARO', number: 44, clue: '"The Barber of Seville" barber'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 2, dir: 'Down', answer: 'ALLFOR', number: 45, clue: 'Totally in favor of'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 6, dir: 'Across', answer: 'DRAFT', number: 46, clue: 'Early copy'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 9, dir: 'Down', answer: 'FRITES', number: 47, clue: 'Belgian potato snack'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 10, dir: 'Down', answer: 'TOTS', number: 48, clue: 'American potato snack'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 10, col: 13, dir: 'Across', answer: 'CIO', number: 49, clue: 'It merged with the AFL in 1955'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 11, col: 1, dir: 'Across', answer: 'ILEBACK', number: 50, clue: 'Rear part of Martinique?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 11, col: 5, dir: 'Down', answer: 'ASLAN', number: 51, clue: 'Lion in Narnia'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 11, col: 9, dir: 'Across', answer: 'ROOMKEY', number: 52, clue: 'Check-in counter pickup'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 11, col: 11, dir: 'Down', answer: 'ORTIZ', number: 53, clue: 'Slugger "Big Papi" of the Red Sox'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 11, col: 12, dir: 'Down', answer: 'MORTE', number: 54, clue: 'Death of the Roman Empire?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 12, col: 1, dir: 'Across', answer: 'GLASS', number: 55, clue: 'Certain bong material'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 12, col: 8, dir: 'Across', answer: 'NITRO', number: 56, clue: 'Marvel supervillain'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 12, col: 8, dir: 'Down', answer: 'NERO', number: 56, clue: 'Fabled fiddler during the burning of Rome'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 1, dir: 'Across', answer: 'AFK', number: 57, clue: 'Acronym used when you plan to BRB, say'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 5, dir: 'Across', answer: 'LBJETSTREAM', number: 58, clue: 'Online video of a 1960s president talking to aliens?'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 6, dir: 'Down', answer: 'BMI', number: 59, clue: 'Personal trainer\'s meas.'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 7, dir: 'Down', answer: 'JAN', number: 60, clue: 'Pres. inauguration month'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 13, dir: 'Down', answer: 'EST', number: 61, clue: 'Extreme suffix'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 14, dir: 'Down', answer: 'AMA', number: 62, clue: '"I ___ Man of Constant Sorrow"'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 13, col: 15, dir: 'Down', answer: 'MES', number: 63, clue: 'Juno or Julio, por ejemplo'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 14, col: 1, dir: 'Across', answer: 'ROE', number: 64, clue: 'Legal pseudonym for Norma McCorvey'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 14, col: 5, dir: 'Across', answer: 'AMARE', number: 65, clue: 'Teammate of Carmelo'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 14, col: 11, dir: 'Across', answer: 'ITSME', number: 66, clue: 'Announcement confirmed by the speaker\'s voice'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 15, col: 1, dir: 'Across', answer: 'ORR', number: 67, clue: 'Legendary Bruin Bobby'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 15, col: 5, dir: 'Across', answer: 'NINOS', number: 68, clue: 'Mexican children'))
clues_Yo_Yo_Diet_CR_7_19_12.push(Entry.create(row: 15, col: 11, dir: 'Across', answer: 'ZETAS', number: 69, clue: 'Mexican drug cartel, with "Los"'))
Puzzle.create(title: 'Yo-Yo Diet', grid: 'PASTA.THUMP.LID|CRAIG.OUTIE.EVO|BILBOSPHERE.ATE|...BRATS..TUTUS|ODDSARE.FLASHBU|DUE..SNARE.SEEP|BLAHS..CANTOR..|.LLBEANCUISINE.|..BOXCAR..ALERT|FARM.DRAFT..CIO|ILEBACK.ROOMKEY|GLASS..NITRO...|AFK.LBJETSTREAM|ROE.AMARE.ITSME|ORR.NINOS.ZETAS', :constructors => Constructor.where(:name => 'Ben Tausig'), :sources => Source.where(:name => 'Ink Well'), publication_date: '2012/7/19', entries: clues_Yo_Yo_Diet_CR_7_19_12)
